In [ ]:
[١:١٠ ص, ١٧‏/١٠‏/٢٠٢٦] نجلاء: # ============================================================
# 🌧️ الودق AI — استعادة الجداول المفقودة
# المرحلة 68A — استعادة آمنة دون حذف أو تحديث الأسعار
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — استعادة الجداول المفقودة")
print("=" * 65)

# ------------------------------------------------------------
# 1. الجداول المطلوبة
# ------------------------------------------------------------

required_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df"
]

# ------------------------------------------------------------
# 2. مصادر بديلة معروفة لاستعادة الجداول
#    لن يتم استبدال أي جدول موجود
# ------------------------------------------------------------

recovery_sources = {
    "wadq_stage66_final_report_df": [
        "wadq_stage65_final_report_df",
        "wadq_stage65_unified_report_df",
        "wadq_final_ai_report"
    ],

    "wadq_stage67_final_report_df": [
        "wadq_stage67_audit_df",
        "wadq_stage67_review_df",
        "wadq_stage66_final_report_df"
    ],

    "wadq_final_ai_report": [
        "wadq_stage66_final_report_df",
        "wadq_stage67_final_report_df",
        "wadq_stage65_final_report_df"
    ],

    "wadq_global_master_report_df": [
        "wadq_global_integrated_df",
        "wadq_global_market_df"
    ],

    "wadq_global_integrated_df": [
        "wadq_global_master_report_df",
        "wadq_global_market_df"
    ],

    "wadq_global_alerts_df": [
        "wadq_global_master_report_df",
        "wadq_global_integrated_df"
    ],

    "wadq_stage66_price_check_df": [
        "wadq_stage65_price_check_df",
        "price_check_df"
    ],

    "wadq_stage66_price_update_df": [
        "wadq_stage65_price_update_df",
        "price_update_df"
    ],

    "wadq_stage66_quality_check_df": [
        "wadq_stage65_quality_check_df",
        "quality_check_df"
    ],

    "wadq_stage66_decision_board_df": [
        "wadq_stage65_decision_board_df",
        "wadq_decision_board_df"
    ]
}

# ------------------------------------------------------------
# 3. فحص الجداول واستعادة المتاح منها
# ------------------------------------------------------------

restored_tables = []
existing_tables = []
missing_tables = []

for table_name in required_tables:

    # إذا كان الجدول موجودًا، لا نلمسه
    if table_name in globals():
        obj = globals()[table_name]

        if isinstance(obj, pd.DataFrame):
            existing_tables.append(table_name)
            print(f"✅ موجود: {table_name} — {obj.shape}")
            continue

    # البحث عن مصدر بديل موجود
    recovered = False

    for source_name in recovery_sources.get(table_name, []):

        if source_name not in globals():
            continue

        source_obj = globals()[source_name]

        if not isinstance(source_obj, pd.DataFrame):
            continue

        # نسخ الجدول دون تعديل المصدر
        globals()[table_name] = source_obj.copy()

        restored_tables.append(table_name)
        recovered = True

        print(
            f"♻️ تمت استعادة: {table_name} "
            f"من: {source_name} — {source_obj.shape}"
        )

        break

    if not recovered:
        missing_tables.append(table_name)
        print(f"⚠️ لم يُعثر على مصدر لاستعادة: {table_name}")

# ------------------------------------------------------------
# 4. تقرير الاستعادة
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("📊 النتيجة النهائية")
print("=" * 65)

print(f"📅 وقت الفحص: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print(f"✅ الجداول الموجودة: {len(existing_tables)}")
print(f"♻️ الجداول المستعادة: {len(restored_tables)}")
print(f"⚠️ الجداول التي تحتاج إلى مصدر: {len(missing_tables)}")

if restored_tables:
    print("\nالجداول التي تمت استعادتها:")
    for name in restored_tables:
        print(f"  - {name}")

if missing_tables:
    print("\nالجداول التي لم يتوفر مصدر لاستعادتها:")
    for name in missing_tables:
        print(f"  - {name}")

# ------------------------------------------------------------
# 5. فحص نهائي دون تعديل البيانات
# ------------------------------------------------------------

print("\n🔍 فحص الجداول المطلوبة:")

for table_name in required_tables:

    obj = globals().get(table_name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {table_name}: {obj.shape}")
    else:
        print(f"❌ {table_name}: غير متوفر")

print("\n🌧️ انتهى الفحص.")
print("لم يتم حذف أو تحديث أي أسعار أو تشغيل مراحل التحليل.")
print("=" * 65)
[١:١٤ ص, ١٧‏/١٠‏/٢٠٢٦] نجلاء: # ============================================================
# 🌧️ الودق AI — البحث عن ملفات Excel المحفوظة
# ============================================================

from google.colab import drive
import os

# ربط Google Drive
drive.mount('/content/drive')

# البحث في ملفات Google Drive
search_path = "/content/drive/MyDrive"

print("=" * 70)
print("🌧️ البحث عن ملفات Excel الخاصة بمشروع الودق AI")
print("=" * 70)

excel_files = []

for root, dirs, files in os.walk(search_path):
    for file in files:
        if file.lower().endswith((".xlsx", ".xls")):
            full_path = os.path.join(root, file)
            excel_files.append(full_path)

if excel_files:
    print(f"\n✅ تم العثور على {len(excel_files)} ملف Excel:\n")

    for i, path in enumerate(excel_files, 1):
        print(f"{i}. {os.path.basename(path)}")
        print(f"   المسار: {path}\n")

else:
    print("⚠️ لم يتم العثور على ملفات Excel في Google Drive.")

SyntaxError: invalid character '١' (U+0661) (411873581.py, line 1)

In [1]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص ملفات Google Drive دون تعديل أو حذف
# ============================================================

import os
from google.colab import drive

print("🌧️ بدء فحص ملفات الودق AI...")
print("📌 الفحص للقراءة فقط — لن يتم حذف أو تعديل أي ملف.")

# ربط Google Drive
if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")

# مجلد البحث
ROOT = "/content/drive/MyDrive"

# أنواع الملفات التي قد تحتوي على الجداول أو سجل المشروع
extensions = (
    ".csv", ".xlsx", ".xls", ".parquet",
    ".pkl", ".pickle", ".json", ".txt", ".ipynb"
)

# كلمات البحث
keywords = [
    "wadq", "الودق", "stage67", "stage_67",
    "stage68", "مرحلة67", "مرحلة_67",
    "report", "تقرير", "سجل"
]

found_files = []

# البحث داخل Google Drive
for folder, subfolders, files in os.walk(ROOT):

    for filename in files:

        ext = os.path.splitext(filename)[1].lower()
        name_lower = filename.lower()

        # استبعاد الملفات غير المناسبة
        if ext not in extensions:
            continue

        # البحث عن الملفات ذات الصلة بالمشروع
        if any(word in name_lower for word in keywords):

            full_path = os.path.join(folder, filename)

            try:
                size_mb = os.path.getsize(full_path) / (1024 * 1024)
            except:
                size_mb = 0

            found_files.append({
                "الملف": filename,
                "المسار": full_path,
                "الحجم MB": round(size_mb, 3)
            })

# عرض النتائج
print("\n" + "=" * 65)
print("📂 نتائج فحص Google Drive")
print("=" * 65)

if found_files:

    for i, item in enumerate(found_files, 1):

        print(f"\n{i}. 📄 {item['الملف']}")
        print(f"   📍 المسار: {item['المسار']}")
        print(f"   📦 الحجم: {item['الحجم MB']} MB")

    print("\n" + "=" * 65)
    print(f"✅ عدد الملفات التي عُثر عليها: {len(found_files)}")

else:

    print("⚠️ لم يُعثر على ملفات مطابقة لأسماء البحث.")
    print("لم يتم حذف أو تعديل أي ملف.")

print("\n🌧️ انتهى الفحص.")

🌧️ بدء فحص ملفات الودق AI...
📌 الفحص للقراءة فقط — لن يتم حذف أو تعديل أي ملف.
Mounted at /content/drive

=================================================================
📂 نتائج فحص Google Drive
=================================================================

1. 📄 سجل_الودق_AI.txt
   📍 المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt
   📦 الحجم: 0.003 MB

2. 📄 سجل_الاستئناف.txt
   📍 المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الاستئناف.txt
   📦 الحجم: 0.0 MB

=================================================================
✅ عدد الملفات التي عُثر عليها: 2

🌧️ انتهى الفحص.

In [2]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# قراءة سجل المشروع وسجل الاستئناف فقط
# ============================================================

import os

files_to_read = [
    "/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt",
    "/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الاستئناف.txt"
]

for file_path in files_to_read:

    print("\n" + "=" * 70)
    print("📄 الملف:", os.path.basename(file_path))
    print("=" * 70)

    if not os.path.exists(file_path):
        print("⚠️ الملف غير موجود.")
        continue

    try:
        with open(file_path, "r", encoding="utf-8-sig") as f:
            content = f.read()

        print(content if content.strip() else "⚠️ الملف فارغ.")

    except Exception as e:
        print("⚠️ تعذرت قراءة الملف:", e)

print("\n🌧️ انتهت قراءة السجلين دون تعديل أي ملف.")

======================================================================
📄 الملف: سجل_الودق_AI.txt
======================================================================

============================================================
🌧️ مشروع الودق AI — سجل التقدم
============================================================
تاريخ آخر تحديث: 2026-10-14
اسم ملف المشروع:
Copy of الودق AI
آخر مرحلة مكتملة:
المرحلة 67 — التدقيق الشامل لجودة البيانات والمخاطر
المراحل المكتملة:
- المرحلة 59: تحديث الأسعار
- المرحلة 60: فحص جودة البيانات
- المرحلة 61: تقييم الفرص الفنية
- المرحلة 62: مستويات فنية استرشادية
- المرحلة 63: إدارة المخاطر
- المرحلة 64: التقرير الموحد
- المرحلة 65: اختبارات الجودة
- المرحلة 66: إنشاء التقرير النهائي
- المرحلة 67: التدقيق الشامل
عدد الأصول:
26 أصلًا
نتائج المرحلة 67:
- 26 سعرًا صالحًا رقميًا
- 26 تاريخًا صالحًا وغير مستقبلي
- 12 أصلًا اجتاز الفحوص الأولية
- 14 أصلًا يحتاج إلى مراجعة
- 14 أصلًا لديه مستويات غير مكتملة أو تحتاج إلى مراجعة
- 14 أصلًا لديه كميات غير محسوبة أو غير صالحة
الجداول الأصلية لم تُعدّل عمدًا.
الجداول التي أنشأتها المرحلة 67:
1. wadq_stage67_audit_df
2. wadq_stage67_review_df
3. wadq_stage67_passed_df
4. wadq_stage67_summary_df
5. wadq_stage67_log_df
الخطوة التالية:
المرحلة 68A — فحص مصادر الأسعار التاريخية
ومعرفة الجداول المتاحة وأعمدتها قبل إصلاح البيانات.
بعد المرحلة 68A:
تحديد مصدر الأسعار التاريخية الصحيح،
ثم إصلاح المستويات الفنية وحسابات المخاطر.
تعليمات مهمة عند العودة:
1. لا تحذف أي خلية سابقة.
2. لا تضغط Run all.
3. لا تعيدي تشغيل المراحل السابقة دون حاجة.
4. افتحي ملف Copy of الودق AI نفسه.
5. تحققي من آخر مرحلة مكتملة قبل المتابعة.
6. إذا اختفت الجداول، افحصي المصادر المتاحة أولًا.
7. أضيفي المراحل الجديدة أسفل آخر خلية.
8. لا تعتمدي على كمية تداول نظرية قبل التحقق
   من العملة والعقد والعمولات وشروط الوسيط.
ملاحظة:
هذا السجل يحفظ وصف حالة المشروع، وليس الجداول
الموجودة في ذاكرة جلسة Colab.
============================================================


======================================================================
📄 الملف: سجل_الاستئناف.txt
======================================================================

وقت الحفظ: 2026-10-14 00:16:40
آخر مرحلة مكتملة: 67
الخطوة التالية: 68A
ملف المشروع: Copy of الودق AI
----------------------------------------


🌧️ انتهت قراءة السجلين دون تعديل أي ملف.

In [3]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص محتويات مجلد المشروع في Google Drive
# قراءة فقط — لا حذف ولا تعديل
# ============================================================

import os

PROJECT_FOLDER = "/content/drive/MyDrive"

# تحديد مجلد المشروع
project_path = os.path.join(PROJECT_FOLDER, "الودق AI - سجل المشروع")

print("🔎 البحث عن ملفات المشروع ودفاتر Colab...")
print("=" * 70)

# نعرض الملفات في مجلد المشروع وسجلاته
if os.path.exists(project_path):

    for folder, subfolders, files in os.walk(project_path):

        for filename in files:

            full_path = os.path.join(folder, filename)

            try:
                size_mb = os.path.getsize(full_path) / (1024 * 1024)
            except:
                size_mb = 0

            print(f"📄 {filename}")
            print(f"   المسار: {full_path}")
            print(f"   الحجم: {size_mb:.3f} MB")

else:
    print("⚠️ مجلد سجل المشروع غير موجود.")

print("\n" + "=" * 70)
print("🔎 البحث عن دفاتر Colab وملفات البيانات في Google Drive")
print("=" * 70)

# نبحث في Google Drive عن ملفات المشروع المرتبطة بالودق
extensions = (
    ".ipynb", ".csv", ".xlsx", ".xls",
    ".parquet", ".pkl", ".pickle", ".json"
)

keywords = ["wadq", "الودق", "stage67", "stage_67", "stage66"]

count = 0

for folder, subfolders, files in os.walk(PROJECT_FOLDER):

    for filename in files:

        name_lower = filename.lower()
        ext = os.path.splitext(filename)[1].lower()

        if ext in extensions and any(k in name_lower for k in keywords):

            full_path = os.path.join(folder, filename)

            try:
                size_mb = os.path.getsize(full_path) / (1024 * 1024)
            except:
                size_mb = 0

            print(f"\n📄 {filename}")
            print(f"   المسار: {full_path}")
            print(f"   الحجم: {size_mb:.3f} MB")

            count += 1

print("\n" + "=" * 70)
print(f"✅ عدد الملفات المطابقة: {count}")
print("🌧️ انتهى الفحص دون تعديل أو حذف أي ملف.")

🔎 البحث عن ملفات المشروع ودفاتر Colab...
======================================================================
📄 سجل_الودق_AI.txt
   المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt
   الحجم: 0.003 MB
📄 سجل_الاستئناف.txt
   المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الاستئناف.txt
   الحجم: 0.000 MB
📄 سجل_الودق_AI.gdoc
   المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.gdoc
   الحجم: 0.000 MB

======================================================================
🔎 البحث عن دفاتر Colab وملفات البيانات في Google Drive
======================================================================

======================================================================
✅ عدد الملفات المطابقة: 0
🌧️ انتهى الفحص دون تعديل أو حذف أي ملف.

In [4]:
# ============================================================
# 🌧️ الودق AI — محاولة استعادة الجداول المفقودة
# دون تعديل الجداول الأصلية أو إعادة تشغيل المراحل السابقة
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — فحص واستعادة الجداول")
print("=" * 65)

# ------------------------------------------------------------
# 1) فحص الجداول الموجودة في ذاكرة Colab
# ------------------------------------------------------------

print("\n🔎 الجداول الموجودة حاليًا في الذاكرة:")

available = {}

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        available[name] = obj
        print(f"✅ {name} | {obj.shape[0]} صف × {obj.shape[1]} عمود")

if not available:
    print("⚠️ لا توجد جداول DataFrame في ذاكرة Colab حاليًا.")

# ------------------------------------------------------------
# 2) مصادر محتملة للاستعادة
# ------------------------------------------------------------
# الكود لا يخترع بيانات؛ ينشئ نسخة من مصدر موجود فقط.

recovery_map = {
    "wadq_evaluation_df": [
        "wadq_stage67_review_df",
        "wadq_stage67_audit_df",
        "wadq_stage66_final_report_df",
        "wadq_final_ai_report",
        "wadq_smart_report",
    ],

    "wadq_smart_report": [
        "wadq_stage66_final_report_df",
        "wadq_final_ai_report",
        "wadq_stage67_review_df",
        "wadq_stage67_audit_df",
    ],

    "wadq_final_ai_report": [
        "wadq_stage66_final_report_df",
        "wadq_smart_report",
        "wadq_stage67_review_df",
        "wadq_stage67_audit_df",
    ],

    "wadq_global_master_report_df": [
        "wadq_global_integrated_df",
        "wadq_global_market_df",
        "wadq_global_alerts_df",
        "wadq_global_news_analysis_df",
    ],
}

# ------------------------------------------------------------
# 3) محاولة استعادة كل جدول مفقود
# ------------------------------------------------------------

restored = []
not_restored = []
already_exists = []

for target, sources in recovery_map.items():

    # لا نستبدل جدولًا موجودًا
    if target in globals() and isinstance(globals()[target], pd.DataFrame):
        already_exists.append(target)
        print(f"\n⏭️ موجود مسبقًا، لم يتم تغييره: {target}")
        continue

    source_found = None

    # البحث عن أول مصدر موجود وصالح
    for source_name in sources:
        source_obj = globals().get(source_name)

        if isinstance(source_obj, pd.DataFrame) and not source_obj.empty:
            source_found = source_name
            break

    if source_found is not None:
        # نسخة مستقلة، لا تعديل للمصدر
        globals()[target] = globals()[source_found].copy(deep=True)

        restored.append(target)

        print(f"\n✅ أُنشئ الجدول: {target}")
        print(f"   المصدر: {source_found}")
        print(f"   الحجم: {globals()[target].shape[0]} صف × "
              f"{globals()[target].shape[1]} عمود")

    else:
        not_restored.append(target)
        print(f"\n⚠️ تعذرت استعادة: {target}")
        print("   لم يُعثر على مصدر بيانات مناسب في الذاكرة.")

# ------------------------------------------------------------
# 4) النتيجة النهائية
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("📊 ملخص الاستعادة")
print("=" * 65)

print(f"✅ جداول أُنشئت: {len(restored)}")
print(f"⏭️ جداول كانت موجودة: {len(already_exists)}")
print(f"⚠️ جداول تعذرت استعادتها: {len(not_restored)}")

print("\n📋 الجداول التي أُنشئت:")
for name in restored:
    print(f" - {name}")

print("\n📋 الجداول التي تعذرت استعادتها:")
for name in not_restored:
    print(f" - {name}")

print("\n📅 وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

print("\n🌧️ انتهت المحاولة.")
print("لم يتم حذف أو تعديل الجداول الأصلية.")
print("=" * 65)

=================================================================
🌧️ الودق AI — فحص واستعادة الجداول
=================================================================

🔎 الجداول الموجودة حاليًا في الذاكرة:
⚠️ لا توجد جداول DataFrame في ذاكرة Colab حاليًا.

⚠️ تعذرت استعادة: wadq_evaluation_df
   لم يُعثر على مصدر بيانات مناسب في الذاكرة.

⚠️ تعذرت استعادة: wadq_smart_report
   لم يُعثر على مصدر بيانات مناسب في الذاكرة.

⚠️ تعذرت استعادة: wadq_final_ai_report
   لم يُعثر على مصدر بيانات مناسب في الذاكرة.

⚠️ تعذرت استعادة: wadq_global_master_report_df
   لم يُعثر على مصدر بيانات مناسب في الذاكرة.

=================================================================
📊 ملخص الاستعادة
=================================================================
✅ جداول أُنشئت: 0
⏭️ جداول كانت موجودة: 0
⚠️ جداول تعذرت استعادتها: 4

📋 الجداول التي أُنشئت:

📋 الجداول التي تعذرت استعادتها:
 - wadq_evaluation_df
 - wadq_smart_report
 - wadq_final_ai_report
 - wadq_global_master_report_df

📅 وقت الفحص: 2026-10-17 13:22:11

🌧️ انتهت المحاولة.
لم يتم حذف أو تعديل الجداول الأصلية.
=================================================================

In [5]:
# ============================================================
# 🌧️ الودق AI — إعادة إنشاء الجداول المفقودة
# ============================================================

!pip -q install yfinance

import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — إنشاء الجداول الأربعة من جديد")
print("=" * 65)

# ------------------------------------------------------------
# 1) الأصول المعروفة في المشروع
# ------------------------------------------------------------

us_tickers = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY"
]

global_tickers = [
    "^GSPC", "^IXIC", "^DJI", "^GDAXI",
    "^FCHI", "^FTSE", "^N225", "^HSI",
    "GC=F", "SI=F", "CL=F", "BZ=F",
    "NG=F", "BTC-USD"
]

all_tickers = us_tickers + global_tickers

# ------------------------------------------------------------
# 2) دالة تحليل الأصل
# ------------------------------------------------------------

def wadq_analyze_asset(ticker):

    try:
        data = yf.download(
            ticker,
            period="6mo",
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )

        if data is None or data.empty:
            return None

        # معالجة اختلاف شكل بيانات yfinance
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.get_level_values(0)

        data = data.dropna(subset=["Close"])

        if len(data) < 25:
            return None

        close = data["Close"].astype(float)
        latest_price = float(close.iloc[-1])
        previous_price = float(close.iloc[-2])

        daily_change = (
            (latest_price - previous_price) / previous_price
        ) * 100

        # المتوسطات المتحركة
        sma20 = float(close.rolling(20).mean().iloc[-1])
        sma50 = float(close.rolling(50).mean().iloc[-1])

        # RSI
        delta = close.diff()

        gain = delta.clip(lower=0).rolling(14).mean()
        loss = (-delta.clip(upper=0)).rolling(14).mean()

        rs = gain / loss.replace(0, np.nan)
        rsi_series = 100 - (100 / (1 + rs))
        rsi = float(rsi_series.iloc[-1])

        # MACD
        ema12 = close.ewm(span=12, adjust=False).mean()
        ema26 = close.ewm(span=26, adjust=False).mean()

        macd = ema12 - ema26
        signal = macd.ewm(span=9, adjust=False).mean()

        macd_value = float(macd.iloc[-1])
        signal_value = float(signal.iloc[-1])

        # الاتجاه الفني
        if latest_price > sma20 and sma20 > sma50:
            trend = "صاعد"
        elif latest_price < sma20 and sma20 < sma50:
            trend = "هابط"
        else:
            trend = "متذبذب"

        # تقييم فني أولي
        score = 0

        if latest_price > sma20:
            score += 25

        if sma20 > sma50:
            score += 25

        if rsi >= 50 and rsi < 70:
            score += 25

        if macd_value > signal_value:
            score += 25

        if score >= 75:
            assessment = "إيجابي فنيًا"
        elif score >= 50:
            assessment = "متوسط"
        else:
            assessment = "ضعيف فنيًا"

        # ملاحظة فنية
        if rsi >= 70:
            technical_note = "RSI مرتفع — احتمال تشبع شرائي"
        elif rsi <= 30:
            technical_note = "RSI منخفض — احتمال تشبع بيعي"
        elif macd_value > signal_value:
            technical_note = "زخم إيجابي"
        else:
            technical_note = "زخم ضعيف أو سلبي"

        return {
            "ticker": ticker,
            "latest_price": latest_price,
            "previous_price": previous_price,
            "daily_change_pct": daily_change,
            "date": str(data.index[-1].date()),
            "RSI": rsi,
            "SMA20": sma20,
            "SMA50": sma50,
            "MACD": macd_value,
            "MACD_signal": signal_value,
            "trend": trend,
            "technical_score": score,
            "assessment": assessment,
            "technical_note": technical_note,
            "data_status": "بيانات مسترجعة"
        }

    except Exception as e:
        print(f"⚠️ تعذر تحليل {ticker}: {str(e)[:100]}")
        return None


# ------------------------------------------------------------
# 3) جلب البيانات وإنشاء التقارير
# ------------------------------------------------------------

results = []

for ticker in all_tickers:

    print(f"🔎 تحليل {ticker} ...")

    result = wadq_analyze_asset(ticker)

    if result is not None:
        results.append(result)

# ------------------------------------------------------------
# 4) إنشاء الجدول الرئيسي
# ------------------------------------------------------------

if len(results) == 0:

    raise RuntimeError(
        "❌ لم يتم جلب أي بيانات. "
        "تحققي من اتصال الإنترنت في Colab ثم أعيدي تشغيل الخلية."
    )

wadq_new_master_df = pd.DataFrame(results)

# فصل الأسهم الأمريكية
wadq_final_ai_report = (
    wadq_new_master_df[
        wadq_new_master_df["ticker"].isin(us_tickers)
    ].copy()
)

# التقرير الرئيسي للأسواق العالمية
wadq_global_master_report_df = (
    wadq_new_master_df[
        wadq_new_master_df["ticker"].isin(global_tickers)
    ].copy()
)

# ------------------------------------------------------------
# 5) إنشاء جدول التقييم
# ------------------------------------------------------------

wadq_evaluation_df = wadq_new_master_df[
    [
        "ticker",
        "latest_price",
        "daily_change_pct",
        "RSI",
        "trend",
        "technical_score",
        "assessment"
    ]
].copy()

wadq_evaluation_df["evaluation_date"] = datetime.now().strftime(
    "%Y-%m-%d %H:%M"
)

# ------------------------------------------------------------
# 6) إنشاء التقرير الذكي
# ------------------------------------------------------------

wadq_smart_report = wadq_new_master_df[
    [
        "ticker",
        "latest_price",
        "daily_change_pct",
        "trend",
        "technical_score",
        "assessment",
        "technical_note"
    ]
].copy()

wadq_smart_report["report_date"] = datetime.now().strftime(
    "%Y-%m-%d %H:%M"
)

# ------------------------------------------------------------
# 7) فحص الجداول الأربعة
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("📊 نتائج إنشاء الجداول")
print("=" * 65)

tables = {
    "wadq_evaluation_df": wadq_evaluation_df,
    "wadq_smart_report": wadq_smart_report,
    "wadq_final_ai_report": wadq_final_ai_report,
    "wadq_global_master_report_df": wadq_global_master_report_df
}

for name, df in tables.items():

    print(f"\n✅ {name}")
    print(f"عدد الصفوف: {len(df)}")
    print(f"عدد الأعمدة: {len(df.columns)}")

    display(df.head(5))

# ------------------------------------------------------------
# 8) حفظ نسخة احتياطية واحدة في Google Drive
# ------------------------------------------------------------

try:

    from google.colab import drive
    drive.mount("/content/drive")

    backup_path = (
        "/content/drive/MyDrive/"
        "الودق AI - سجل المشروع/"
        "الودق_AI_الجداول_المستعادة.xlsx"
    )

    with pd.ExcelWriter(backup_path, engine="openpyxl") as writer:

        wadq_evaluation_df.to_excel(
            writer, sheet_name="evaluation", index=False
        )

        wadq_smart_report.to_excel(
            writer, sheet_name="smart_report", index=False
        )

        wadq_final_ai_report.to_excel(
            writer, sheet_name="US_report", index=False
        )

        wadq_global_master_report_df.to_excel(
            writer, sheet_name="global_report", index=False
        )

    print("\n✅ تم حفظ نسخة احتياطية من الجداول الأربعة.")
    print(backup_path)

except Exception as e:

    print("\n⚠️ تم إنشاء الجداول في الذاكرة،")
    print("لكن تعذر حفظ النسخة الاحتياطية تلقائيًا.")
    print(str(e)[:200])

print("\n" + "=" * 65)
print("🌧️ انتهت إعادة إنشاء الجداول")
print("عدد الأصول التي جرى تحليلها:", len(wadq_new_master_df))
print("المرحلة التالية: التحقق من الجداول قبل استكمال المرحلة 68")
print("=" * 65)

=================================================================
🌧️ الودق AI — إنشاء الجداول الأربعة من جديد
=================================================================
🔎 تحليل NVDA ...
🔎 تحليل TSLA ...
🔎 تحليل AAPL ...
🔎 تحليل MSFT ...
🔎 تحليل AMZN ...
🔎 تحليل GOOGL ...
🔎 تحليل META ...
🔎 تحليل QQQ ...
🔎 تحليل SPY ...
🔎 تحليل ^GSPC ...
🔎 تحليل ^IXIC ...
🔎 تحليل ^DJI ...
🔎 تحليل ^GDAXI ...
🔎 تحليل ^FCHI ...
🔎 تحليل ^FTSE ...
🔎 تحليل ^N225 ...
🔎 تحليل ^HSI ...
🔎 تحليل GC=F ...
🔎 تحليل SI=F ...
🔎 تحليل CL=F ...
🔎 تحليل BZ=F ...
🔎 تحليل NG=F ...
🔎 تحليل BTC-USD ...

=================================================================
📊 نتائج إنشاء الجداول
=================================================================

✅ wadq_evaluation_df
عدد الصفوف: 23
عدد الأعمدة: 8

,ticker,latest_price,daily_change_pct,RSI,trend,technical_score,assessment,evaluation_date
0,NVDA,214.130005,-1.427055,32.947441,متذبذب,25,ضعيف فنيًا,2026-10-17 13:29
1,TSLA,354.720001,-2.130008,48.185076,متذبذب,25,ضعيف فنيًا,2026-10-17 13:29
2,AAPL,343.459991,0.426898,56.398594,صاعد,100,إيجابي فنيًا,2026-10-17 13:29
3,MSFT,529.049988,-1.926074,63.193573,صاعد,100,إيجابي فنيًا,2026-10-17 13:29
4,AMZN,250.000000,-1.868423,54.387969,هابط,50,متوسط,2026-10-17 13:29

✅ wadq_smart_report
عدد الصفوف: 23
عدد الأعمدة: 8

,ticker,latest_price,daily_change_pct,trend,technical_score,assessment,technical_note,report_date
0,NVDA,214.130005,-1.427055,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,2026-10-17 13:29
1,TSLA,354.720001,-2.130008,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,2026-10-17 13:29
2,AAPL,343.459991,0.426898,صاعد,100,إيجابي فنيًا,زخم إيجابي,2026-10-17 13:29
3,MSFT,529.049988,-1.926074,صاعد,100,إيجابي فنيًا,زخم إيجابي,2026-10-17 13:29
4,AMZN,250.000000,-1.868423,هابط,50,متوسط,زخم إيجابي,2026-10-17 13:29

✅ wadq_final_ai_report
عدد الصفوف: 9
عدد الأعمدة: 15

,ticker,latest_price,previous_price,daily_change_pct,date,RSI,SMA20,SMA50,MACD,MACD_signal,trend,technical_score,assessment,technical_note,data_status
0,NVDA,214.130005,217.229996,-1.427055,2026-10-16,32.947441,228.177001,222.963153,-0.148878,2.216203,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة
1,TSLA,354.720001,362.440002,-2.130008,2026-10-16,48.185076,370.333499,359.462198,1.413186,3.503323,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة
2,AAPL,343.459991,342.000000,0.426898,2026-10-16,56.398594,337.424002,325.694000,4.138097,3.943890,صاعد,100,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة
3,MSFT,529.049988,539.440002,-1.926074,2026-10-16,63.193573,520.220500,505.365515,11.251145,10.977267,صاعد,100,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة
4,AMZN,250.000000,254.759995,-1.868423,2026-10-16,54.387969,253.225999,257.075999,0.184119,0.054368,هابط,50,متوسط,زخم إيجابي,بيانات مسترجعة

✅ wadq_global_master_report_df
عدد الصفوف: 14
عدد الأعمدة: 15

,ticker,latest_price,previous_price,daily_change_pct,date,RSI,SMA20,SMA50,MACD,MACD_signal,trend,technical_score,assessment,technical_note,data_status
9,^GSPC,7659.439941,7744.060059,-1.092710,2026-10-16,47.582884,7739.241553,7706.416230,18.250942,26.640947,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة
10,^IXIC,26140.029297,26713.029297,-2.145021,2026-10-16,37.263303,27051.172266,26631.213086,60.055160,185.188290,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة
11,^DJI,52002.410156,52177.691406,-0.335931,2026-10-16,58.233352,51531.079492,52460.308672,-118.083275,-259.341437,متذبذب,75,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة
12,^GDAXI,25622.609375,25382.619141,0.945490,2026-10-16,54.987914,25296.322363,25720.518008,-75.965333,-134.632290,متذبذب,75,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة
13,^FCHI,7956.700195,7934.700195,0.277263,2026-10-16,42.112703,7940.713501,8199.633184,-89.262226,-110.988747,متذبذب,50,متوسط,زخم إيجابي,بيانات مسترجعة

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

✅ تم حفظ نسخة احتياطية من الجداول الأربعة.
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_الجداول_المستعادة.xlsx

=================================================================
🌧️ انتهت إعادة إنشاء الجداول
عدد الأصول التي جرى تحليلها: 23
المرحلة التالية: التحقق من الجداول قبل استكمال المرحلة 68
=================================================================

In [6]:
import pandas as pd
import os

path = "/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_الجداول_المستعادة.xlsx"

if os.path.exists(path):
    excel = pd.ExcelFile(path)

    print("✅ ملف الودق AI محفوظ")
    print("📋 الجداول الموجودة في الملف:")

    for sheet in excel.sheet_names:
        df = pd.read_excel(path, sheet_name=sheet)
        print(f"✅ {sheet}: {len(df)} صف")

    print("\n🌧️ الجداول جاهزة للمرحلة 68.")
else:
    print("⚠️ لم يتم العثور على ملف النسخة الاحتياطية.")

✅ ملف الودق AI محفوظ
📋 الجداول الموجودة في الملف:
✅ evaluation: 23 صف
✅ smart_report: 23 صف
✅ US_report: 9 صف
✅ global_report: 14 صف

🌧️ الجداول جاهزة للمرحلة 68.

In [7]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68
# التدقيق بعد استعادة الجداول
# ============================================================

import pandas as pd
import numpy as np
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — المرحلة 68: تدقيق الجداول المستعادة")
print("=" * 65)

# ------------------------------------------------------------
# 1) تحميل الجداول المحفوظة
# ------------------------------------------------------------

path = "/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_الجداول_المستعادة.xlsx"

wadq_evaluation_df = pd.read_excel(path, sheet_name="evaluation")
wadq_smart_report = pd.read_excel(path, sheet_name="smart_report")
wadq_final_ai_report = pd.read_excel(path, sheet_name="US_report")
wadq_global_master_report_df = pd.read_excel(path, sheet_name="global_report")

print("✅ تم تحميل الجداول الأربعة من النسخة الاحتياطية")

# ------------------------------------------------------------
# 2) توحيد التقرير
# ------------------------------------------------------------

wadq_stage68_unified_report_df = pd.concat(
    [
        wadq_final_ai_report,
        wadq_global_master_report_df
    ],
    ignore_index=True
)

wadq_stage68_unified_report_df["market_type"] = np.where(
    wadq_stage68_unified_report_df["ticker"].isin(
        wadq_final_ai_report["ticker"]
    ),
    "US",
    "Global"
)

wadq_stage68_unified_report_df["stage"] = 68

wadq_stage68_unified_report_df["audit_date"] = datetime.now().strftime(
    "%Y-%m-%d %H:%M"
)

# ------------------------------------------------------------
# 3) فحص الجودة
# ------------------------------------------------------------

quality_results = []

for ticker in wadq_stage68_unified_report_df["ticker"].unique():

    row = wadq_stage68_unified_report_df[
        wadq_stage68_unified_report_df["ticker"] == ticker
    ].iloc[0]

    price = row.get("latest_price", np.nan)
    rsi = row.get("RSI", np.nan)
    score = row.get("technical_score", np.nan)

    issues = []

    if pd.isna(price) or price <= 0:
        issues.append("سعر غير صالح")

    if pd.isna(rsi) or not 0 <= rsi <= 100:
        issues.append("RSI غير صالح")

    if pd.isna(score) or not 0 <= score <= 100:
        issues.append("التقييم الفني غير صالح")

    quality_results.append({
        "ticker": ticker,
        "price_check": "سليم" if not pd.isna(price) and price > 0 else "مراجعة",
        "RSI_check": "سليم" if not pd.isna(rsi) and 0 <= rsi <= 100 else "مراجعة",
        "score_check": "سليم" if not pd.isna(score) and 0 <= score <= 100 else "مراجعة",
        "quality_status": "سليم" if len(issues) == 0 else "مراجعة",
        "issues": "؛ ".join(issues) if issues else "لا توجد"
    })

wadq_stage68_quality_df = pd.DataFrame(quality_results)

# ------------------------------------------------------------
# 4) ملخص المرحلة
# ------------------------------------------------------------

print("\n📊 ملخص المرحلة 68")
print("-" * 65)

print("عدد الأصول:", len(wadq_stage68_unified_report_df))
print("عدد الأسهم الأمريكية:", len(wadq_final_ai_report))
print("عدد الأصول العالمية:", len(wadq_global_master_report_df))

print(
    "الأصول السليمة:",
    (wadq_stage68_quality_df["quality_status"] == "سليم").sum()
)

print(
    "الأصول التي تحتاج مراجعة:",
    (wadq_stage68_quality_df["quality_status"] == "مراجعة").sum()
)

print("\n📋 تقرير جودة البيانات:")
display(wadq_stage68_quality_df)

print("\n📋 التقرير الموحد:")
display(wadq_stage68_unified_report_df)

# ------------------------------------------------------------
# 5) حفظ المرحلة 68
# ------------------------------------------------------------

backup_path = "/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_68.xlsx"

with pd.ExcelWriter(backup_path, engine="openpyxl") as writer:

    wadq_stage68_unified_report_df.to_excel(
        writer,
        sheet_name="stage68_unified",
        index=False
    )

    wadq_stage68_quality_df.to_excel(
        writer,
        sheet_name="stage68_quality",
        index=False
    )

    wadq_evaluation_df.to_excel(
        writer,
        sheet_name="evaluation",
        index=False
    )

    wadq_smart_report.to_excel(
        writer,
        sheet_name="smart_report",
        index=False
    )

    wadq_final_ai_report.to_excel(
        writer,
        sheet_name="US_report",
        index=False
    )

    wadq_global_master_report_df.to_excel(
        writer,
        sheet_name="global_report",
        index=False
    )

print("\n✅ تم حفظ المرحلة 68")
print("📁", backup_path)

print("\n🌧️ انتهت المرحلة 68")
print("=" * 65)

=================================================================
🌧️ الودق AI — المرحلة 68: تدقيق الجداول المستعادة
=================================================================
✅ تم تحميل الجداول الأربعة من النسخة الاحتياطية

📊 ملخص المرحلة 68
-----------------------------------------------------------------
عدد الأصول: 23
عدد الأسهم الأمريكية: 9
عدد الأصول العالمية: 14
الأصول السليمة: 23
الأصول التي تحتاج مراجعة: 0

📋 تقرير جودة البيانات:

     ticker price_check RSI_check score_check quality_status   issues
0      NVDA        سليم      سليم        سليم           سليم  لا توجد
1      TSLA        سليم      سليم        سليم           سليم  لا توجد
2      AAPL        سليم      سليم        سليم           سليم  لا توجد
3      MSFT        سليم      سليم        سليم           سليم  لا توجد
4      AMZN        سليم      سليم        سليم           سليم  لا توجد
5     GOOGL        سليم      سليم        سليم           سليم  لا توجد
6      META        سليم      سليم        سليم           سليم  لا توجد
7       QQQ        سليم      سليم        سليم           سليم  لا توجد
8       SPY        سليم      سليم        سليم           سليم  لا توجد
9     ^GSPC        سليم      سليم        سليم           سليم  لا توجد
10    ^IXIC        سليم      سليم        سليم           سليم  لا توجد
11     ^DJI        سليم      سليم        سليم           سليم  لا توجد
12   ^GDAXI        سليم      سليم        سليم           سليم  لا توجد
13    ^FCHI        سليم      سليم        سليم           سليم  لا توجد
14    ^FTSE        سليم      سليم        سليم           سليم  لا توجد
15    ^N225        سليم      سليم        سليم           سليم  لا توجد
16     ^HSI        سليم      سليم        سليم           سليم  لا توجد
17     GC=F        سليم      سليم        سليم           سليم  لا توجد
18     SI=F        سليم      سليم        سليم           سليم  لا توجد
19     CL=F        سليم      سليم        سليم           سليم  لا توجد
20     BZ=F        سليم      سليم        سليم           سليم  لا توجد
21     NG=F        سليم      سليم        سليم           سليم  لا توجد
22  BTC-USD        سليم      سليم        سليم           سليم  لا توجد

📋 التقرير الموحد:

,ticker,latest_price,previous_price,daily_change_pct,date,RSI,SMA20,SMA50,MACD,MACD_signal,trend,technical_score,assessment,technical_note,data_status,market_type,stage,audit_date
0,NVDA,214.130005,217.229996,-1.427055,2026-10-16,32.947441,228.177001,222.963153,-0.148878,2.216203,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,US,68,2026-10-17 13:34
1,TSLA,354.720001,362.440002,-2.130008,2026-10-16,48.185076,370.333499,359.462198,1.413186,3.503323,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,US,68,2026-10-17 13:34
2,AAPL,343.459991,342.000000,0.426898,2026-10-16,56.398594,337.424002,325.694000,4.138097,3.943890,صاعد,100,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة,US,68,2026-10-17 13:34
3,MSFT,529.049988,539.440002,-1.926074,2026-10-16,63.193573,520.220500,505.365515,11.251145,10.977267,صاعد,100,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة,US,68,2026-10-17 13:34
4,AMZN,250.000000,254.759995,-1.868423,2026-10-16,54.387969,253.225999,257.075999,0.184119,0.054368,هابط,50,متوسط,زخم إيجابي,بيانات مسترجعة,US,68,2026-10-17 13:34
5,GOOGL,340.589996,349.220001,-2.471223,2026-10-16,47.708944,346.414000,344.491907,1.020196,1.193340,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,US,68,2026-10-17 13:34
6,META,709.330017,736.719971,-3.717824,2026-10-16,48.189726,735.774997,654.955577,19.471765,25.558288,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,US,68,2026-10-17 13:34
7,QQQ,709.799988,728.000000,-2.500002,2026-10-16,33.370621,742.519003,726.326044,1.656604,6.321640,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,US,68,2026-10-17 13:34
8,SPY,763.250000,771.789978,-1.106516,2026-10-16,47.588902,771.183997,767.400020,2.022146,2.881864,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,US,68,2026-10-17 13:34
9,^GSPC,7659.439941,7744.060059,-1.092710,2026-10-16,47.582884,7739.241553,7706.416230,18.250942,26.640947,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,Global,68,2026-10-17 13:34
10,^IXIC,26140.029297,26713.029297,-2.145021,2026-10-16,37.263303,27051.172266,26631.213086,60.055160,185.188290,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,Global,68,2026-10-17 13:34
11,^DJI,52002.410156,52177.691406,-0.335931,2026-10-16,58.233352,51531.079492,52460.308672,-118.083275,-259.341437,متذبذب,75,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
12,^GDAXI,25622.609375,25382.619141,0.945490,2026-10-16,54.987914,25296.322363,25720.518008,-75.965333,-134.632290,متذبذب,75,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
13,^FCHI,7956.700195,7934.700195,0.277263,2026-10-16,42.112703,7940.713501,8199.633184,-89.262226,-110.988747,متذبذب,50,متوسط,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
14,^FTSE,10881.900391,10840.400391,0.382827,2026-10-16,60.678637,10629.570020,10716.761953,12.070538,-30.215231,متذبذب,75,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
15,^N225,65324.289062,64425.949219,1.394376,2026-10-16,46.423099,66891.545313,66295.014844,306.623257,635.021688,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,Global,68,2026-10-17 13:34
16,^HSI,24186.830078,24062.720703,0.515774,2026-10-16,44.124949,24418.344922,24985.569609,-231.596952,-247.669374,هابط,25,ضعيف فنيًا,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
17,GC=F,4181.100098,4170.100098,0.263783,2026-10-16,51.536439,4214.109985,4374.413984,-55.715676,-58.861655,هابط,50,متوسط,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
18,SI=F,56.994999,56.837002,0.277983,2026-10-16,34.870715,60.844150,63.902140,-1.868098,-1.470257,هابط,0,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,Global,68,2026-10-17 13:34
19,CL=F,101.410004,97.970001,3.511281,2026-10-16,68.016356,92.938500,90.982601,1.295326,0.566908,صاعد,100,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
20,BZ=F,109.860001,105.919998,3.719791,2026-10-16,61.840742,103.691499,98.415000,2.206142,1.997910,صاعد,100,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
21,NG=F,3.116000,3.236000,-3.708286,2026-10-16,57.073163,3.106350,2.943880,0.073238,0.072181,صاعد,100,إيجابي فنيًا,زخم إيجابي,بيانات مسترجعة,Global,68,2026-10-17 13:34
22,BTC-USD,81428.531250,81500.804688,-0.088678,2026-10-17,38.576907,83409.925000,81323.824063,85.203762,609.016794,متذبذب,25,ضعيف فنيًا,زخم ضعيف أو سلبي,بيانات مسترجعة,Global,68,2026-10-17 13:34

✅ تم حفظ المرحلة 68
📁 /content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_68.xlsx

🌧️ انتهت المرحلة 68
=================================================================

In [8]:
# ============================================================
# 🌧️ الودق AI — المرحلة 69: تدقيق التقييم الفني
# ============================================================

import pandas as pd
import numpy as np
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — المرحلة 69: تدقيق التقييم الفني")
print("=" * 65)

# التأكد من وجود التقرير الموحد
if "wadq_stage68_unified_report_df" not in globals():
    raise RuntimeError(
        "التقرير الموحد غير موجود في الذاكرة. "
        "شغّلي خلية المرحلة 68 أولًا."
    )

df = wadq_stage68_unified_report_df.copy()

# ------------------------------------------------------------
# 1) تدقيق التقييم بناءً على المؤشرات
# ------------------------------------------------------------

audit_results = []

for _, row in df.iterrows():

    ticker = row["ticker"]

    price = row["latest_price"]
    sma20 = row["SMA20"]
    sma50 = row["SMA50"]
    rsi = row["RSI"]
    macd = row["MACD"]
    signal = row["MACD_signal"]

    # اتجاه السعر بالنسبة للمتوسطات
    if price > sma20 and sma20 > sma50:
        expected_trend = "صاعد"
    elif price < sma20 and sma20 < sma50:
        expected_trend = "هابط"
    else:
        expected_trend = "متذبذب"

    # التحقق من الزخم
    macd_momentum = (
        "إيجابي" if macd > signal else "سلبي أو ضعيف"
    )

    # درجة فنية وفق المؤشرات
    score = 0

    if price > sma20:
        score += 25

    if sma20 > sma50:
        score += 25

    if 50 <= rsi < 70:
        score += 25

    if macd > signal:
        score += 25

    if score >= 75:
        assessment = "إيجابي فنيًا"
    elif score >= 50:
        assessment = "متوسط"
    else:
        assessment = "ضعيف فنيًا"

    # مقارنة النتيجة السابقة بالنتيجة المدققة
    old_score = row["technical_score"]

    audit_results.append({
        "ticker": ticker,
        "old_score": old_score,
        "new_score": score,
        "old_trend": row["trend"],
        "new_trend": expected_trend,
        "macd_momentum": macd_momentum,
        "new_assessment": assessment,
        "score_changed": old_score != score,
        "trend_changed": row["trend"] != expected_trend
    })

wadq_stage69_audit_df = pd.DataFrame(audit_results)

# ------------------------------------------------------------
# 2) إنشاء تقرير فني مدقق دون تعديل التقرير الأصلي
# ------------------------------------------------------------

wadq_stage69_final_report_df = df.merge(
    wadq_stage69_audit_df,
    on="ticker",
    how="left"
)

print("\n📊 ملخص التدقيق الفني")
print("-" * 65)

print("عدد الأصول:", len(wadq_stage69_audit_df))

print(
    "الأصول التي تغير تقييمها:",
    wadq_stage69_audit_df["score_changed"].sum()
)

print(
    "الأصول التي تغير اتجاهها:",
    wadq_stage69_audit_df["trend_changed"].sum()
)

print("\n📋 نتائج التدقيق:")
display(wadq_stage69_audit_df)

# ------------------------------------------------------------
# 3) حفظ المرحلة 69
# ------------------------------------------------------------

path = (
    "/content/drive/MyDrive/الودق AI - سجل المشروع/"
    "الودق_AI_المرحلة_69.xlsx"
)

with pd.ExcelWriter(path, engine="openpyxl") as writer:

    wadq_stage69_audit_df.to_excel(
        writer,
        sheet_name="technical_audit",
        index=False
    )

    wadq_stage69_final_report_df.to_excel(
        writer,
        sheet_name="audited_report",
        index=False
    )

print("\n✅ تم حفظ المرحلة 69")
print("📁", path)

print("=" * 65)

=================================================================
🌧️ الودق AI — المرحلة 69: تدقيق التقييم الفني
=================================================================

📊 ملخص التدقيق الفني
-----------------------------------------------------------------
عدد الأصول: 23
الأصول التي تغير تقييمها: 0
الأصول التي تغير اتجاهها: 0

📋 نتائج التدقيق:

,ticker,old_score,new_score,old_trend,new_trend,macd_momentum,new_assessment,score_changed,trend_changed
0,NVDA,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
1,TSLA,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
2,AAPL,100,100,صاعد,صاعد,إيجابي,إيجابي فنيًا,False,False
3,MSFT,100,100,صاعد,صاعد,إيجابي,إيجابي فنيًا,False,False
4,AMZN,50,50,هابط,هابط,إيجابي,متوسط,False,False
5,GOOGL,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
6,META,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
7,QQQ,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
8,SPY,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
9,^GSPC,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
10,^IXIC,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
11,^DJI,75,75,متذبذب,متذبذب,إيجابي,إيجابي فنيًا,False,False
12,^GDAXI,75,75,متذبذب,متذبذب,إيجابي,إيجابي فنيًا,False,False
13,^FCHI,50,50,متذبذب,متذبذب,إيجابي,متوسط,False,False
14,^FTSE,75,75,متذبذب,متذبذب,إيجابي,إيجابي فنيًا,False,False
15,^N225,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False
16,^HSI,25,25,هابط,هابط,إيجابي,ضعيف فنيًا,False,False
17,GC=F,50,50,هابط,هابط,إيجابي,متوسط,False,False
18,SI=F,0,0,هابط,هابط,سلبي أو ضعيف,ضعيف فنيًا,False,False
19,CL=F,100,100,صاعد,صاعد,إيجابي,إيجابي فنيًا,False,False
20,BZ=F,100,100,صاعد,صاعد,إيجابي,إيجابي فنيًا,False,False
21,NG=F,100,100,صاعد,صاعد,إيجابي,إيجابي فنيًا,False,False
22,BTC-USD,25,25,متذبذب,متذبذب,سلبي أو ضعيف,ضعيف فنيًا,False,False

✅ تم حفظ المرحلة 69
📁 /content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_69.xlsx
=================================================================

In [13]:
# =====================================================================
# 🌧️ الودق AI — المراحل 70 إلى 75
# تحديث الأسعار + التحليل الفني + التقييم + المخاطر + التدقيق + التقرير
# =====================================================================

!pip -q install yfinance openpyxl

import os
import warnings
import numpy as np
import pandas as pd
import yfinance as yf
from datetime import datetime

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------
# 1) إعداد المشروع وحفظ الملفات
# ---------------------------------------------------------------------

from google.colab import drive
drive.mount('/content/drive')

PROJECT_DIR = "/content/drive/MyDrive/الودق AI - سجل المشروع"
os.makedirs(PROJECT_DIR, exist_ok=True)

SOURCE_FILE = os.path.join(
    PROJECT_DIR,
    "الودق_AI_المرحلة_69.xlsx"
)

FINAL_FILE = os.path.join(
    PROJECT_DIR,
    "الودق_AI_المراحل_70_الى_75.xlsx"
)

RUN_DATE = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

print("=" * 75)
print("🌧️ الودق AI — تشغيل المراحل 70 إلى 75")
print("=" * 75)


# ---------------------------------------------------------------------
# 2) المرحلة 70 — تحديد الأصول
# ---------------------------------------------------------------------

# الأصول التي سبق العمل عليها في المشروع
DEFAULT_TICKERS = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY",
    "^GSPC", "^IXIC", "^DJI", "^GDAXI", "^FCHI",
    "^FTSE", "^N225", "^HSI",
    "GC=F", "SI=F", "CL=F", "BZ=F", "NG=F",
    "BTC-USD"
]

tickers = DEFAULT_TICKERS.copy()

# قراءة ملف المرحلة 69 إن كان موجودًا
if os.path.exists(SOURCE_FILE):

    try:
        source_excel = pd.ExcelFile(SOURCE_FILE)

        print("\n✅ تم العثور على ملف المرحلة 69")
        print("الأوراق:", source_excel.sheet_names)

        # محاولة استعادة الأصول من ملف المرحلة 69
        recovered_tickers = []

        for sheet in source_excel.sheet_names:

            try:
                temp_df = pd.read_excel(SOURCE_FILE, sheet_name=sheet)

                if "ticker" in temp_df.columns:
                    recovered_tickers.extend(
                        temp_df["ticker"].dropna().astype(str).tolist()
                    )

            except Exception:
                pass

        recovered_tickers = list(dict.fromkeys(recovered_tickers))

        if recovered_tickers:
            tickers = recovered_tickers
            print("✅ تم استعادة الأصول من ملف المرحلة 69")

    except Exception as e:
        print("⚠️ تعذر قراءة ملف المرحلة 69:", e)

else:
    print("⚠️ لم يُعثر على ملف المرحلة 69")
    print("سيتم استخدام قائمة الأصول المعروفة في المشروع")

tickers = list(dict.fromkeys(tickers))

print("\nعدد الأصول:", len(tickers))
print(tickers)


# ---------------------------------------------------------------------
# 3) المرحلة 71 — تحديث الأسعار وجمع البيانات
# ---------------------------------------------------------------------

print("\n" + "=" * 75)
print("📈 المرحلة 71 — تحديث الأسعار")
print("=" * 75)

results = []
raw_data = {}

for ticker in tickers:

    try:

        df = yf.download(
            ticker,
            period="6mo",
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )

        if df is None or df.empty:
            print("⚠️ لا توجد بيانات:", ticker)
            continue

        # معالجة اختلاف شكل أعمدة yfinance
        if isinstance(df.columns, pd.MultiIndex):

            if ticker in df.columns.get_level_values(-1):
                df = df.xs(ticker, axis=1, level=-1)

            elif ticker in df.columns.get_level_values(0):
                df = df.xs(ticker, axis=1, level=0)

        df.columns = [
            str(c).lower().replace(" ", "_")
            for c in df.columns
        ]

        if "close" not in df.columns:
            print("⚠️ لا يوجد عمود إغلاق:", ticker)
            continue

        df = df.dropna(subset=["close"]).copy()

        if len(df) < 2:
            print("⚠️ بيانات غير كافية:", ticker)
            continue

        raw_data[ticker] = df.copy()

        close = df["close"].astype(float)

        latest_price = float(close.iloc[-1])
        previous_price = float(close.iloc[-2])

        latest_date = pd.Timestamp(df.index[-1]).strftime("%Y-%m-%d")

        daily_change = (
            (latest_price - previous_price) / previous_price * 100
            if previous_price != 0 else np.nan
        )

        # -----------------------------------------------------------------
        # المرحلة 72 — المؤشرات الفنية
        # -----------------------------------------------------------------

        sma20 = close.rolling(20).mean()
        sma50 = close.rolling(50).mean()

        # RSI 14
        delta = close.diff()

        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.rolling(14).mean()
        avg_loss = loss.rolling(14).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)
        rsi = 100 - (100 / (1 + rs))

        # MACD
        ema12 = close.ewm(span=12, adjust=False).mean()
        ema26 = close.ewm(span=26, adjust=False).mean()

        macd = ema12 - ema26
        macd_signal = macd.ewm(span=9, adjust=False).mean()

        # ATR 14
        high = df["high"].astype(float) if "high" in df.columns else close
        low = df["low"].astype(float) if "low" in df.columns else close

        previous_close_series = close.shift(1)

        true_range = pd.concat(
            [
                high - low,
                (high - previous_close_series).abs(),
                (low - previous_close_series).abs()
            ],
            axis=1
        ).max(axis=1)

        atr14 = true_range.rolling(14).mean()

        # استخراج آخر المؤشرات
        latest_sma20 = sma20.iloc[-1]
        latest_sma50 = sma50.iloc[-1]
        latest_rsi = rsi.iloc[-1]
        latest_macd = macd.iloc[-1]
        latest_macd_signal = macd_signal.iloc[-1]
        latest_atr = atr14.iloc[-1]

        # -----------------------------------------------------------------
        # المرحلة 73 — حساب التقييم الفني والاتجاه
        # -----------------------------------------------------------------

        score = 0

        if pd.notna(latest_sma20) and latest_price > latest_sma20:
            score += 25

        if (
            pd.notna(latest_sma20)
            and pd.notna(latest_sma50)
            and latest_sma20 > latest_sma50
        ):
            score += 25

        if pd.notna(latest_rsi) and 50 <= latest_rsi <= 70:
            score += 25

        if (
            pd.notna(latest_macd)
            and pd.notna(latest_macd_signal)
            and latest_macd > latest_macd_signal
        ):
            score += 25

        # اتجاه فني
        if (
            pd.notna(latest_sma20)
            and pd.notna(latest_sma50)
            and latest_price > latest_sma20 > latest_sma50
        ):
            trend = "صاعد"

        elif (
            pd.notna(latest_sma20)
            and pd.notna(latest_sma50)
            and latest_price < latest_sma20 < latest_sma50
        ):
            trend = "هابط"

        else:
            trend = "متذبذب"

        # التقييم
        if score >= 75:
            assessment = "إيجابي فنيًا"

        elif score >= 50:
            assessment = "متوسط"

        else:
            assessment = "ضعيف فنيًا"

        # زخم MACD
        if (
            pd.notna(latest_macd)
            and pd.notna(latest_macd_signal)
            and latest_macd > latest_macd_signal
        ):
            momentum = "إيجابي"

        else:
            momentum = "سلبي أو ضعيف"

        # -----------------------------------------------------------------
        # المرحلة 74 — حساب مستويات المخاطر الفنية
        # -----------------------------------------------------------------

        # مستويات إرشادية مبنية على ATR وليست توصيات شراء أو بيع
        if pd.notna(latest_atr) and latest_atr > 0:

            technical_stop = latest_price - (2 * latest_atr)
            technical_target = latest_price + (3 * latest_atr)

            atr_percent = (latest_atr / latest_price) * 100

        else:

            technical_stop = np.nan
            technical_target = np.nan
            atr_percent = np.nan

        # جودة البيانات
        if (
            latest_price > 0
            and pd.notna(latest_price)
            and pd.notna(latest_date)
            and pd.notna(latest_sma20)
            and pd.notna(latest_rsi)
        ):
            data_status = "مكتملة مبدئيًا"

        else:
            data_status = "تحتاج مراجعة"

        # حفظ نتيجة الأصل
        results.append({
            "ticker": ticker,
            "latest_price": latest_price,
            "previous_price": previous_price,
            "daily_change_pct": daily_change,
            "latest_date": latest_date,
            "SMA20": latest_sma20,
            "SMA50": latest_sma50,
            "RSI14": latest_rsi,
            "MACD": latest_macd,
            "MACD_signal": latest_macd_signal,
            "ATR14": latest_atr,
            "ATR_percent": atr_percent,
            "technical_score": score,
            "trend": trend,
            "macd_momentum": momentum,
            "assessment": assessment,
            "technical_stop_guide": technical_stop,
            "technical_target_guide": technical_target,
            "data_status": data_status,
            "audit_date": RUN_DATE
        })

        print(
            f"✅ {ticker} | السعر: {latest_price:.4f} | "
            f"التقييم: {assessment} | الاتجاه: {trend}"
        )

    except Exception as e:

        print(f"⚠️ خطأ في {ticker}: {str(e)[:150]}")


# ---------------------------------------------------------------------
# 4) إنشاء التقرير الموحد
# ---------------------------------------------------------------------

print("\n" + "=" * 75)
print("📊 إنشاء التقرير الموحد")
print("=" * 75)

if not results:
    raise RuntimeError(
        "لم يتم تحديث أي أصل. تحقق من اتصال الإنترنت أو مصدر البيانات."
    )

wadq_stage75_final_report_df = pd.DataFrame(results)

# ترتيب حسب الدرجة الفنية
wadq_stage75_final_report_df = (
    wadq_stage75_final_report_df
    .sort_values(
        by=["technical_score", "daily_change_pct"],
        ascending=[False, False]
    )
    .reset_index(drop=True)
)

# تقرير جودة البيانات
quality_rows = []

for _, row in wadq_stage75_final_report_df.iterrows():

    issues = []

    if pd.isna(row["latest_price"]) or row["latest_price"] <= 0:
        issues.append("سعر غير صالح")

    if pd.isna(row["RSI14"]):
        issues.append("RSI غير متوفر")

    if pd.isna(row["SMA20"]):
        issues.append("SMA20 غير متوفر")

    if pd.isna(row["latest_date"]):
        issues.append("تاريخ السعر غير متوفر")

    quality_rows.append({
        "ticker": row["ticker"],
        "latest_date": row["latest_date"],
        "latest_price": row["latest_price"],
        "quality_status": "سليم مبدئيًا" if not issues else "تحتاج مراجعة",
        "quality_notes": "؛ ".join(issues) if issues else "لا توجد مشكلة شكلية مكتشفة",
        "audit_date": RUN_DATE
    })

wadq_stage75_quality_df = pd.DataFrame(quality_rows)


# ---------------------------------------------------------------------
# 5) المرحلة 75 — التدقيق النهائي
# ---------------------------------------------------------------------

print("\n" + "=" * 75)
print("🔍 المرحلة 75 — التدقيق النهائي")
print("=" * 75)

total_assets = len(wadq_stage75_final_report_df)

valid_prices = (
    wadq_stage75_final_report_df["latest_price"].notna()
    & (wadq_stage75_final_report_df["latest_price"] > 0)
)

valid_rsi = (
    wadq_stage75_final_report_df["RSI14"].between(0, 100)
)

valid_scores = (
    wadq_stage75_final_report_df["technical_score"].between(0, 100)
)

quality_tests = pd.DataFrame([
    {
        "test": "وجود سعر صالح",
        "passed": int(valid_prices.sum()),
        "failed": int((~valid_prices).sum())
    },
    {
        "test": "RSI بين 0 و100",
        "passed": int(valid_rsi.sum()),
        "failed": int((~valid_rsi).sum())
    },
    {
        "test": "الدرجة الفنية بين 0 و100",
        "passed": int(valid_scores.sum()),
        "failed": int((~valid_scores).sum())
    }
])

# ملخص التنفيذ
summary_df = pd.DataFrame([
    {"item": "اسم المشروع", "value": "الودق AI"},
    {"item": "المراحل المنفذة", "value": "70 إلى 75"},
    {"item": "وقت التنفيذ", "value": RUN_DATE},
    {"item": "عدد الأصول المطلوبة", "value": len(tickers)},
    {"item": "عدد الأصول التي تم تحديثها", "value": total_assets},
    {"item": "عدد الأصول ذات الأسعار الصالحة", "value": int(valid_prices.sum())},
    {"item": "عدد الأصول التي تحتاج مراجعة", "value": int((~valid_prices).sum())},
    {"item": "ملاحظة", "value": "التحليل الفني أولي ولا يضمن نتائج التداول"}
])


# ---------------------------------------------------------------------
# 6) حفظ ملف Excel النهائي
# ---------------------------------------------------------------------

print("\n" + "=" * 75)
print("💾 حفظ التقرير النهائي")
print("=" * 75)

with pd.ExcelWriter(FINAL_FILE, engine="openpyxl") as writer:

    wadq_stage75_final_report_df.to_excel(
        writer,
        sheet_name="final_report",
        index=False
    )

    wadq_stage75_quality_df.to_excel(
        writer,
        sheet_name="quality_report",
        index=False
    )

    quality_tests.to_excel(
        writer,
        sheet_name="quality_tests",
        index=False
    )

    summary_df.to_excel(
        writer,
        sheet_name="project_summary",
        index=False
    )

    # حفظ بيانات الأسعار التاريخية المستخدمة
    for ticker, df in raw_data.items():

        safe_name = (
            ticker.replace("^", "")
            .replace("=", "")
            .replace("-", "")
            .replace("/", "")
        )

        sheet_name = ("raw_" + safe_name)[:31]

        try:
            df.to_excel(writer, sheet_name=sheet_name)
        except Exception:
            pass


# ---------------------------------------------------------------------
# 7) عرض النتيجة
# ---------------------------------------------------------------------

print("\n" + "=" * 75)
print("🌧️ اكتمل تشغيل الودق AI")
print("=" * 75)

print("عدد الأصول المطلوبة:", len(tickers))
print("عدد الأصول التي تم تحديثها:", total_assets)
print("عدد الأسعار الصالحة:", int(valid_prices.sum()))
print("عدد الأسعار التي تحتاج مراجعة:", int((~valid_prices).sum()))

print("\n📋 التقرير النهائي:")
display(wadq_stage75_final_report_df)

print("\n🔍 اختبارات الجودة:")
display(quality_tests)

print("\n💾 تم حفظ الملف:")
print(FINAL_FILE)

print("\n" + "=" * 75)
print("انتهى الكود — لا تعيدي تشغيل المراحل السابقة")
print("=" * 75

_IncompleteInputError: incomplete input (4057301360.py, line 537)

In [14]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 68 إلى 75
# إعادة بناء الجداول + تحديث الأسعار + التحليل الفني
# التقييم + المخاطر + التدقيق + التقرير النهائي
# =====================================================================

!pip -q install yfinance openpyxl

import os
import warnings
import numpy as np
import pandas as pd
import yfinance as yf

from datetime import datetime
from IPython.display import display

warnings.filterwarnings("ignore")

# =====================================================================
# 1) الاتصال بـ Google Drive
# =====================================================================

try:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)

    DRIVE_OK = True
    BASE_PATH = "/content/drive/MyDrive"

except Exception as e:
    DRIVE_OK = False
    BASE_PATH = "/content"

    print("⚠️ تعذر الاتصال بـ Google Drive")
    print("سيتم الحفظ مؤقتًا في:", BASE_PATH)


# =====================================================================
# 2) إعداد المشروع
# =====================================================================

PROJECT_NAME = "الودق AI"

# رأس المال التجريبي بالريال
CAPITAL_SAR = 100

# نسبة المخاطرة النظرية من رأس المال
RISK_PERCENT = 0.01

# الفترة المستخدمة للتحليل الفني
PERIOD = "6mo"

# =====================================================================
# 3) قائمة الأصول — 26 أصلًا
# =====================================================================

assets = [
    # الأسهم الأمريكية
    ("NVDA", "NVIDIA", "US"),
    ("TSLA", "Tesla", "US"),
    ("AAPL", "Apple", "US"),
    ("MSFT", "Microsoft", "US"),
    ("AMZN", "Amazon", "US"),
    ("GOOGL", "Alphabet", "US"),
    ("META", "Meta", "US"),
    ("QQQ", "Nasdaq ETF", "US"),
    ("SPY", "S&P 500 ETF", "US"),

    # مؤشرات عالمية
    ("^GSPC", "S&P 500", "INDEX"),
    ("^IXIC", "NASDAQ Composite", "INDEX"),
    ("^DJI", "Dow Jones", "INDEX"),
    ("^GDAXI", "DAX Germany", "INDEX"),
    ("^FCHI", "CAC 40 France", "INDEX"),
    ("^FTSE", "FTSE 100 UK", "INDEX"),
    ("^N225", "Nikkei 225", "INDEX"),
    ("^HSI", "Hang Seng", "INDEX"),

    # المعادن والطاقة والعملات الرقمية
    ("GC=F", "Gold", "COMMODITY"),
    ("SI=F", "Silver", "COMMODITY"),
    ("CL=F", "US Oil", "COMMODITY"),
    ("BZ=F", "Brent Oil", "COMMODITY"),
    ("NG=F", "Natural Gas", "COMMODITY"),
    ("BTC-USD", "Bitcoin", "CRYPTO"),

    # أسهم سعودية
    ("2222.SR", "Saudi Aramco", "SAUDI"),
    ("1120.SR", "Al Rajhi Bank", "SAUDI"),
    ("2010.SR", "SABIC", "SAUDI"),
]

assets_df = pd.DataFrame(
    assets,
    columns=["ticker", "asset", "market"]
)

print("=" * 65)
print("🌧️ الودق AI — بدء إعادة بناء الجداول")
print("=" * 65)

print("عدد الأصول:", len(assets_df))
print("رأس المال التجريبي:", CAPITAL_SAR, "ريال")


# =====================================================================
# 4) فحص الجداول الموجودة مسبقًا
# =====================================================================

print("\n🔎 فحص الجداول الموجودة في الذاكرة:")

old_tables = [
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_evaluation_df",
    "wadq_smart_report",
    "wadq_global_alerts_df",
    "wadq_global_integrated_df",
    "wadq_global_news_df",
    "wadq_global_market_df",
    "wadq_ticker_news_df",
    "wadq_price_comparison",
]

for table_name in old_tables:

    if table_name in globals():

        obj = globals()[table_name]

        if isinstance(obj, pd.DataFrame):
            print(
                f"✅ {table_name}: "
                f"{obj.shape[0]} صف × {obj.shape[1]} عمود"
            )

        else:
            print(f"⚠️ {table_name}: موجود لكنه ليس DataFrame")

    else:
        print(f"❌ {table_name}: غير موجود")


# =====================================================================
# 5) تنزيل الأسعار
# =====================================================================

print("\n📥 تحديث الأسعار من Yahoo Finance...")

price_tables = {}
download_errors = []

for ticker in assets_df["ticker"].tolist():

    try:

        data = yf.download(
            ticker,
            period=PERIOD,
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )

        if data is None or data.empty:
            download_errors.append(ticker)
            print(f"⚠️ لا توجد بيانات: {ticker}")
            continue

        # معالجة اختلاف شكل الأعمدة في yfinance
        if isinstance(data.columns, pd.MultiIndex):

            if ticker in data.columns.get_level_values(-1):
                data = data.xs(
                    ticker,
                    axis=1,
                    level=-1
                )

            else:
                data.columns = data.columns.get_level_values(0)

        data = data.copy()

        if "Close" not in data.columns:
            download_errors.append(ticker)
            continue

        data = data.dropna(subset=["Close"])

        if data.empty:
            download_errors.append(ticker)
            continue

        price_tables[ticker] = data

        print(f"✅ تم تحديث {ticker}")

    except Exception as e:

        download_errors.append(ticker)
        print(f"⚠️ خطأ في {ticker}: {str(e)[:100]}")


# =====================================================================
# 6) إنشاء جدول الأسعار الموحد
# =====================================================================

price_rows = []

for ticker, data in price_tables.items():

    row = assets_df[
        assets_df["ticker"] == ticker
    ].iloc[0]

    latest = data.iloc[-1]

    previous = (
        data.iloc[-2]
        if len(data) >= 2
        else latest
    )

    latest_close = float(latest["Close"])
    previous_close = float(previous["Close"])

    daily_change = (
        (latest_close / previous_close) - 1
    ) * 100 if previous_close else np.nan

    price_rows.append({

        "ticker": ticker,

        "asset": row["asset"],

        "market": row["market"],

        "previous_close": previous_close,

        "latest_close": latest_close,

        "daily_change_pct": daily_change,

        "latest_date": data.index[-1],

        "data_status": "OK",

        "data_rows": len(data)

    })


wadq_price_df = pd.DataFrame(price_rows)

if not wadq_price_df.empty:

    wadq_price_df = wadq_price_df.sort_values(
        "daily_change_pct",
        ascending=False
    ).reset_index(drop=True)


print("\n📊 جدول الأسعار:")
display(wadq_price_df.head(30))


# =====================================================================
# 7) التحليل الفني
# =====================================================================

technical_rows = []

for ticker, data in price_tables.items():

    try:

        close = data["Close"].astype(float)

        if len(close) < 30:
            continue

        # المتوسطات المتحركة
        sma20 = close.rolling(20).mean().iloc[-1]

        sma50 = close.rolling(50).mean().iloc[-1]

        # RSI
        delta = close.diff()

        gain = delta.clip(lower=0)

        loss = -delta.clip(upper=0)

        avg_gain = gain.rolling(14).mean()

        avg_loss = loss.rolling(14).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)

        rsi = 100 - (100 / (1 + rs))

        latest_rsi = rsi.iloc[-1]

        # MACD
        ema12 = close.ewm(
            span=12,
            adjust=False
        ).mean()

        ema26 = close.ewm(
            span=26,
            adjust=False
        ).mean()

        macd = ema12 - ema26

        signal = macd.ewm(
            span=9,
            adjust=False
        ).mean()

        latest_macd = macd.iloc[-1]

        latest_signal = signal.iloc[-1]

        latest_close = close.iloc[-1]

        # الاتجاه
        if latest_close > sma20 and sma20 > sma50:
            trend = "صاعد"

        elif latest_close < sma20 and sma20 < sma50:
            trend = "هابط"

        else:
            trend = "متذبذب"

        # ملاحظات فنية
        notes = []

        if latest_close > sma20:
            notes.append("السعر فوق متوسط 20")

        else:
            notes.append("السعر تحت متوسط 20")

        if latest_rsi >= 70:
            notes.append("RSI مرتفع")

        elif latest_rsi <= 30:
            notes.append("RSI منخفض")

        else:
            notes.append("RSI متوسط")

        if latest_macd > latest_signal:
            notes.append("MACD إيجابي")

        else:
            notes.append("MACD سلبي")

        # درجة فنية أولية
        score = 0

        if latest_close > sma20:
            score += 1

        if sma20 > sma50:
            score += 1

        if latest_macd > latest_signal:
            score += 1

        if 40 <= latest_rsi <= 65:
            score += 1

        technical_rows.append({

            "ticker": ticker,

            "latest_close": latest_close,

            "SMA20": sma20,

            "SMA50": sma50,

            "RSI": latest_rsi,

            "MACD": latest_macd,

            "MACD_signal": latest_signal,

            "trend": trend,

            "technical_score": score,

            "technical_notes": " | ".join(notes)

        })

    except Exception as e:

        print(f"⚠️ تعذر التحليل الفني: {ticker}")


wadq_technical_df = pd.DataFrame(technical_rows)


# =====================================================================
# 8) التقييم الموحد
# =====================================================================

if not wadq_price_df.empty and not wadq_technical_df.empty:

    wadq_evaluation_df = wadq_price_df.merge(
        wadq_technical_df,
        on="ticker",
        how="left",
        suffixes=("", "_technical")
    )

else:

    wadq_evaluation_df = pd.DataFrame()


evaluation_rows = []

for _, row in wadq_evaluation_df.iterrows():

    score = row.get("technical_score", np.nan)

    if pd.isna(score):

        assessment = "بيانات غير كافية"

    elif score >= 3:

        assessment = "إيجابي فنيًا"

    elif score == 2:

        assessment = "محايد"

    else:

        assessment = "ضعيف فنيًا"

    evaluation_rows.append({

        "ticker": row["ticker"],

        "asset": row["asset"],

        "market": row["market"],

        "latest_close": row["latest_close"],

        "daily_change_pct": row["daily_change_pct"],

        "RSI": row.get("RSI", np.nan),

        "trend": row.get("trend", "غير متوفر"),

        "technical_score": score,

        "evaluation": assessment

    })


wadq_evaluation_df = pd.DataFrame(evaluation_rows)


# =====================================================================
# 9) إدارة المخاطر النظرية
# =====================================================================

risk_rows = []

risk_budget = CAPITAL_SAR * RISK_PERCENT

for _, row in wadq_evaluation_df.iterrows():

    price = row["latest_close"]

    # وقف خسارة نظري 5% — ليس توصية شراء أو بيع
    stop_loss = price * 0.95

    target_1 = price * 1.05

    target_2 = price * 1.10

    risk_per_unit = price - stop_loss

    theoretical_quantity = (
        risk_budget / risk_per_unit
        if risk_per_unit > 0
        else 0
    )

    # منع تجاوز رأس المال
    max_quantity_by_capital = (
        CAPITAL_SAR / price
        if price > 0
        else 0
    )

    theoretical_quantity = min(
        theoretical_quantity,
        max_quantity_by_capital
    )

    risk_rows.append({

        "ticker": row["ticker"],

        "latest_close": price,

        "stop_loss_guide": stop_loss,

        "target_1_guide": target_1,

        "target_2_guide": target_2,

        "risk_budget_sar": risk_budget,

        "theoretical_quantity": theoretical_quantity,

        "theoretical_position_value": (
            theoretical_quantity * price
        ),

        "risk_calculation_status": "نظري"

    })


wadq_risk_df = pd.DataFrame(risk_rows)


# =====================================================================
# 10) التقرير النهائي الموحد
# =====================================================================

if not wadq_evaluation_df.empty:

    wadq_final_ai_report = wadq_evaluation_df.merge(
        wadq_risk_df,
        on="ticker",
        how="left",
        suffixes=("", "_risk")
    )

else:

    wadq_final_ai_report = pd.DataFrame()


# =====================================================================
# 11) لوحة القرار
# =====================================================================

decision_rows = []

for _, row in wadq_final_ai_report.iterrows():

    score = row.get("technical_score", np.nan)

    if pd.isna(score):

        decision = "مراقبة البيانات"

    elif score >= 3:

        decision = "مراقبة إيجابية"

    elif score == 2:

        decision = "مراقبة محايدة"

    else:

        decision = "مراقبة سلبية"

    decision_rows.append({

        "ticker": row["ticker"],

        "asset": row["asset"],

        "market": row["market"],

        "latest_close": row["latest_close"],

        "daily_change_pct": row["daily_change_pct"],

        "trend": row.get("trend", "غير متوفر"),

        "technical_score": score,

        "decision": decision,

        "risk_budget_sar": row.get("risk_budget_sar", np.nan)

    })


wadq_decision_board_df = pd.DataFrame(decision_rows)


# =====================================================================
# 12) فحص جودة البيانات
# =====================================================================

quality_rows = []

for ticker in assets_df["ticker"]:

    exists = ticker in price_tables

    quality_rows.append({

        "ticker": ticker,

        "price_data_available": exists,

        "technical_analysis_available": (
            ticker in wadq_technical_df["ticker"].values
            if not wadq_technical_df.empty
            else False
        ),

        "price_is_valid": (
            float(
                price_tables[ticker]["Close"].iloc[-1]
            ) > 0
            if exists
            else False
        ),

        "status": "OK" if exists else "NEEDS_REVIEW"

    })


wadq_quality_df = pd.DataFrame(quality_rows)


# =====================================================================
# 13) إنشاء التقرير العالمي
# =====================================================================

wadq_global_master_report_df = wadq_final_ai_report[
    wadq_final_ai_report["market"].isin(
        ["INDEX", "COMMODITY", "CRYPTO"]
    )
].copy() if not wadq_final_ai_report.empty else pd.DataFrame()


# =====================================================================
# 14) إنشاء التقرير السعودي
# =====================================================================

wadq_saudi_report_df = wadq_final_ai_report[
    wadq_final_ai_report["market"] == "SAUDI"
].copy() if not wadq_final_ai_report.empty else pd.DataFrame()


# =====================================================================
# 15) إنشاء مجلد جديد للحفظ
# =====================================================================

run_time = datetime.now().strftime("%Y%m%d_%H%M%S")

OUTPUT_FOLDER = os.path.join(
    BASE_PATH,
    "الودق AI - نتائج إعادة البناء",
    f"تقرير_{run_time}"
)

os.makedirs(
    OUTPUT_FOLDER,
    exist_ok=True
)


# =====================================================================
# 16) حفظ جميع الجداول في Excel
# =====================================================================

excel_path = os.path.join(
    OUTPUT_FOLDER,
    "wadq_ai_final_report.xlsx"
)

with pd.ExcelWriter(
    excel_path,
    engine="openpyxl"
) as writer:

    wadq_price_df.to_excel(
        writer,
        sheet_name="Prices",
        index=False
    )

    wadq_technical_df.to_excel(
        writer,
        sheet_name="Technical",
        index=False
    )

    wadq_evaluation_df.to_excel(
        writer,
        sheet_name="Evaluation",
        index=False
    )

    wadq_risk_df.to_excel(
        writer,
        sheet_name="Risk",
        index=False
    )

    wadq_final_ai_report.to_excel(
        writer,
        sheet_name="Final_Report",
        index=False
    )

    wadq_decision_board_df.to_excel(
        writer,
        sheet_name="Decision_Board",
        index=False
    )

    wadq_quality_df.to_excel(
        writer,
        sheet_name="Quality",
        index=False
    )

    wadq_global_master_report_df.to_excel(
        writer,
        sheet_name="Global_Report",
        index=False
    )

    wadq_saudi_report_df.to_excel(
        writer,
        sheet_name="Saudi_Report",
        index=False
    )


# =====================================================================
# 17) حفظ الجداول بصيغة CSV
# =====================================================================

tables_to_save = {

    "wadq_price_df": wadq_price_df,

    "wadq_technical_df": wadq_technical_df,

    "wadq_evaluation_df": wadq_evaluation_df,

    "wadq_risk_df": wadq_risk_df,

    "wadq_final_ai_report": wadq_final_ai_report,

    "wadq_decision_board_df": wadq_decision_board_df,

    "wadq_quality_df": wadq_quality_df,

    "wadq_global_master_report_df": wadq_global_master_report_df,

    "wadq_saudi_report_df": wadq_saudi_report_df

}


for name, table in tables_to_save.items():

    csv_path = os.path.join(
        OUTPUT_FOLDER,
        f"{name}.csv"
    )

    table.to_csv(
        csv_path,
        index=False,
        encoding="utf-8-sig"
    )


# =====================================================================
# 18) تسجيل نتائج التنفيذ
# =====================================================================

log_path = os.path.join(
    OUTPUT_FOLDER,
    "سجل_إعادة_البناء.txt"
)

with open(
    log_path,
    "w",
    encoding="utf-8"
) as f:

    f.write("الودق AI — سجل إعادة البناء\n")

    f.write("=" * 50 + "\n")

    f.write(f"وقت التنفيذ: {datetime.now()}\n")

    f.write(f"عدد الأصول المطلوبة: {len(assets_df)}\n")

    f.write(f"عدد الأصول المحدثة: {len(price_tables)}\n")

    f.write(
        f"عدد الأصول التي تعذر تحديثها: "
        f"{len(download_errors)}\n"
    )

    f.write(
        f"عدد الأصول في التقرير النهائي: "
        f"{len(wadq_final_ai_report)}\n"
    )

    f.write(f"مسار النتائج: {OUTPUT_FOLDER}\n")


# =====================================================================
# 19) عرض النتيجة النهائية
# =====================================================================

print("\n" + "=" * 65)

print("🌧️ الودق AI — اكتملت إعادة بناء التقارير")

print("=" * 65)

print("عدد الأصول المطلوبة:", len(assets_df))

print("عدد الأصول المحدثة:", len(price_tables))

print("عدد الأصول التي تعذر تحديثها:", len(download_errors))

print("عدد الأصول في التقرير النهائي:", len(wadq_final_ai_report))

print("\n📁 مجلد النتائج:")

print(OUTPUT_FOLDER)

print("\n📊 التقرير النهائي:")

display(wadq_final_ai_report.head(30))

print("\n📋 لوحة القرار:")

display(wadq_decision_board_df.head(30))

print("\n🔍 جودة البيانات:")

display(wadq_quality_df)

print("\n💾 ملف Excel النهائي:")

print(excel_path)

print("\n⚠️ تنبيه:")
print(
    "التحليل الفني وإدارة المخاطر أدوات معلوماتية نظرية، "
    "وليست توصيات مالية أو أوامر شراء وبيع."
)

print("\n🌧️ انتهى التنفيذ.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=================================================================
🌧️ الودق AI — بدء إعادة بناء الجداول
=================================================================
عدد الأصول: 26
رأس المال التجريبي: 100 ريال

🔎 فحص الجداول الموجودة في الذاكرة:
✅ wadq_final_ai_report: 9 صف × 15 عمود
✅ wadq_global_master_report_df: 14 صف × 15 عمود
✅ wadq_evaluation_df: 23 صف × 8 عمود
✅ wadq_smart_report: 23 صف × 8 عمود
❌ wadq_global_alerts_df: غير موجود
❌ wadq_global_integrated_df: غير موجود
❌ wadq_global_news_df: غير موجود
❌ wadq_global_market_df: غير موجود
❌ wadq_ticker_news_df: غير موجود
❌ wadq_price_comparison: غير موجود

📥 تحديث الأسعار من Yahoo Finance...
✅ تم تحديث NVDA
✅ تم تحديث TSLA
✅ تم تحديث AAPL
✅ تم تحديث MSFT
✅ تم تحديث AMZN
✅ تم تحديث GOOGL
✅ تم تحديث META
✅ تم تحديث QQQ
✅ تم تحديث SPY
✅ تم تحديث ^GSPC
✅ تم تحديث ^IXIC
✅ تم تحديث ^DJI
✅ تم تحديث ^GDAXI
✅ تم تحديث ^FCHI
✅ تم تحديث ^FTSE
✅ تم تحديث ^N225
✅ تم تحديث ^HSI
✅ تم تحديث GC=F
✅ تم تحديث SI=F
✅ تم تحديث CL=F
✅ تم تحديث BZ=F
✅ تم تحديث NG=F
✅ تم تحديث BTC-USD
✅ تم تحديث 2222.SR
✅ تم تحديث 1120.SR
✅ تم تحديث 2010.SR

📊 جدول الأسعار:

,ticker,asset,market,previous_close,latest_close,daily_change_pct,latest_date,data_status,data_rows
0,BZ=F,Brent Oil,COMMODITY,105.919998,109.860001,3.719791,2026-10-16,OK,127
1,CL=F,US Oil,COMMODITY,97.970001,101.410004,3.511281,2026-10-16,OK,127
2,^N225,Nikkei 225,INDEX,64425.949219,65324.289062,1.394376,2026-10-16,OK,122
3,^GDAXI,DAX Germany,INDEX,25382.619141,25622.609375,0.945490,2026-10-16,OK,131
4,^HSI,Hang Seng,INDEX,24062.720703,24186.830078,0.515774,2026-10-16,OK,127
5,AAPL,Apple,US,342.000000,343.459991,0.426898,2026-10-16,OK,127
6,^FTSE,FTSE 100 UK,INDEX,10840.400391,10881.900391,0.382827,2026-10-16,OK,129
7,SI=F,Silver,COMMODITY,56.837002,56.994999,0.277983,2026-10-16,OK,127
8,^FCHI,CAC 40 France,INDEX,7934.700195,7956.700195,0.277263,2026-10-16,OK,131
9,GC=F,Gold,COMMODITY,4170.100098,4181.100098,0.263783,2026-10-16,OK,127
10,1120.SR,Al Rajhi Bank,SAUDI,60.849998,61.000000,0.246510,2026-10-15,OK,126
11,BTC-USD,Bitcoin,CRYPTO,81500.804688,81386.367188,-0.140413,2026-10-17,OK,184
12,2010.SR,SABIC,SAUDI,44.700001,44.560001,-0.313198,2026-10-15,OK,126
13,^DJI,Dow Jones,INDEX,52177.691406,52002.410156,-0.335931,2026-10-16,OK,127
14,2222.SR,Saudi Aramco,SAUDI,25.379999,25.280001,-0.394005,2026-10-15,OK,126
15,^GSPC,S&P 500,INDEX,7744.060059,7659.439941,-1.092710,2026-10-16,OK,127
16,SPY,S&P 500 ETF,US,771.789978,763.250000,-1.106516,2026-10-16,OK,127
17,NVDA,NVIDIA,US,217.229996,214.130005,-1.427055,2026-10-16,OK,127
18,AMZN,Amazon,US,254.759995,250.000000,-1.868423,2026-10-16,OK,127
19,MSFT,Microsoft,US,539.440002,529.049988,-1.926074,2026-10-16,OK,127
20,TSLA,Tesla,US,362.440002,354.720001,-2.130008,2026-10-16,OK,127
21,^IXIC,NASDAQ Composite,INDEX,26713.029297,26140.029297,-2.145021,2026-10-16,OK,127
22,GOOGL,Alphabet,US,349.220001,340.589996,-2.471223,2026-10-16,OK,127
23,QQQ,Nasdaq ETF,US,728.000000,709.799988,-2.500002,2026-10-16,OK,127
24,NG=F,Natural Gas,COMMODITY,3.236000,3.116000,-3.708286,2026-10-16,OK,127
25,META,Meta,US,736.719971,709.330017,-3.717824,2026-10-16,OK,127

=================================================================
🌧️ الودق AI — اكتملت إعادة بناء التقارير
=================================================================
عدد الأصول المطلوبة: 26
عدد الأصول المحدثة: 26
عدد الأصول التي تعذر تحديثها: 0
عدد الأصول في التقرير النهائي: 26

📁 مجلد النتائج:
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449

📊 التقرير النهائي:

,ticker,asset,market,latest_close,daily_change_pct,RSI,trend,technical_score,evaluation,latest_close_risk,stop_loss_guide,target_1_guide,target_2_guide,risk_budget_sar,theoretical_quantity,theoretical_position_value,risk_calculation_status
0,BZ=F,Brent Oil,COMMODITY,109.860001,3.719791,61.840742,صاعد,4,إيجابي فنيًا,109.860001,104.367001,115.353001,120.846001,1.0,0.182050,20.0,نظري
1,CL=F,US Oil,COMMODITY,101.410004,3.511281,68.016356,صاعد,3,إيجابي فنيًا,101.410004,96.339503,106.480504,111.551004,1.0,0.197219,20.0,نظري
2,^N225,Nikkei 225,INDEX,65324.289062,1.394376,46.423099,متذبذب,2,محايد,65324.289062,62058.074609,68590.503516,71856.717969,1.0,0.000306,20.0,نظري
3,^GDAXI,DAX Germany,INDEX,25622.609375,0.945490,54.987914,متذبذب,3,إيجابي فنيًا,25622.609375,24341.478906,26903.739844,28184.870313,1.0,0.000781,20.0,نظري
4,^HSI,Hang Seng,INDEX,24186.830078,0.515774,44.124949,هابط,2,محايد,24186.830078,22977.488574,25396.171582,26605.513086,1.0,0.000827,20.0,نظري
5,AAPL,Apple,US,343.459991,0.426898,56.398594,صاعد,4,إيجابي فنيًا,343.459991,326.286992,360.632991,377.805991,1.0,0.058231,20.0,نظري
6,^FTSE,FTSE 100 UK,INDEX,10881.900391,0.382827,60.678637,متذبذب,3,إيجابي فنيًا,10881.900391,10337.805371,11425.995410,11970.090430,1.0,0.001838,20.0,نظري
7,SI=F,Silver,COMMODITY,56.994999,0.277983,34.870715,هابط,0,ضعيف فنيًا,56.994999,54.145249,59.844749,62.694499,1.0,0.350908,20.0,نظري
8,^FCHI,CAC 40 France,INDEX,7956.700195,0.277263,42.112703,متذبذب,3,إيجابي فنيًا,7956.700195,7558.865186,8354.535205,8752.370215,1.0,0.002514,20.0,نظري
9,GC=F,Gold,COMMODITY,4181.100098,0.263783,51.536439,هابط,2,محايد,4181.100098,3972.045093,4390.155103,4599.210107,1.0,0.004783,20.0,نظري
10,1120.SR,Al Rajhi Bank,SAUDI,61.000000,0.246510,26.415108,هابط,0,ضعيف فنيًا,61.000000,57.950000,64.050000,67.100000,1.0,0.327869,20.0,نظري
11,BTC-USD,Bitcoin,CRYPTO,81386.367188,-0.140413,38.465803,متذبذب,1,ضعيف فنيًا,81386.367188,77317.048828,85455.685547,89525.003906,1.0,0.000246,20.0,نظري
12,2010.SR,SABIC,SAUDI,44.560001,-0.313198,27.485395,هابط,0,ضعيف فنيًا,44.560001,42.332001,46.788001,49.016002,1.0,0.448833,20.0,نظري
13,^DJI,Dow Jones,INDEX,52002.410156,-0.335931,58.233352,متذبذب,3,إيجابي فنيًا,52002.410156,49402.289648,54602.530664,57202.651172,1.0,0.000385,20.0,نظري
14,2222.SR,Saudi Aramco,SAUDI,25.280001,-0.394005,36.633678,هابط,1,ضعيف فنيًا,25.280001,24.016001,26.544001,27.808001,1.0,0.791139,20.0,نظري
15,^GSPC,S&P 500,INDEX,7659.439941,-1.092710,47.582884,متذبذب,2,محايد,7659.439941,7276.467944,8042.411938,8425.383936,1.0,0.002611,20.0,نظري
16,SPY,S&P 500 ETF,US,763.250000,-1.106516,47.588902,متذبذب,2,محايد,763.250000,725.087500,801.412500,839.575000,1.0,0.026204,20.0,نظري
17,NVDA,NVIDIA,US,214.130005,-1.427055,32.947441,متذبذب,1,ضعيف فنيًا,214.130005,203.423505,224.836505,235.543005,1.0,0.093401,20.0,نظري
18,AMZN,Amazon,US,250.000000,-1.868423,54.387969,هابط,2,محايد,250.000000,237.500000,262.500000,275.000000,1.0,0.080000,20.0,نظري
19,MSFT,Microsoft,US,529.049988,-1.926074,63.193573,صاعد,4,إيجابي فنيًا,529.049988,502.597488,555.502487,581.954987,1.0,0.037804,20.0,نظري
20,TSLA,Tesla,US,354.720001,-2.130008,48.185076,متذبذب,2,محايد,354.720001,336.984001,372.456001,390.192001,1.0,0.056382,20.0,نظري
21,^IXIC,NASDAQ Composite,INDEX,26140.029297,-2.145021,37.263303,متذبذب,1,ضعيف فنيًا,26140.029297,24833.027832,27447.030762,28754.032227,1.0,0.000765,20.0,نظري
22,GOOGL,Alphabet,US,340.589996,-2.471223,47.708944,متذبذب,2,محايد,340.589996,323.560497,357.619496,374.648996,1.0,0.058722,20.0,نظري
23,QQQ,Nasdaq ETF,US,709.799988,-2.500002,33.370621,متذبذب,1,ضعيف فنيًا,709.799988,674.309988,745.289987,780.779987,1.0,0.028177,20.0,نظري
24,NG=F,Natural Gas,COMMODITY,3.116000,-3.708286,57.073163,صاعد,4,إيجابي فنيًا,3.116000,2.960200,3.271800,3.427600,1.0,6.418485,20.0,نظري
25,META,Meta,US,709.330017,-3.717824,48.189726,متذبذب,2,محايد,709.330017,673.863516,744.796518,780.263019,1.0,0.028196,20.0,نظري

📋 لوحة القرار:

,ticker,asset,market,latest_close,daily_change_pct,trend,technical_score,decision,risk_budget_sar
0,BZ=F,Brent Oil,COMMODITY,109.860001,3.719791,صاعد,4,مراقبة إيجابية,1.0
1,CL=F,US Oil,COMMODITY,101.410004,3.511281,صاعد,3,مراقبة إيجابية,1.0
2,^N225,Nikkei 225,INDEX,65324.289062,1.394376,متذبذب,2,مراقبة محايدة,1.0
3,^GDAXI,DAX Germany,INDEX,25622.609375,0.945490,متذبذب,3,مراقبة إيجابية,1.0
4,^HSI,Hang Seng,INDEX,24186.830078,0.515774,هابط,2,مراقبة محايدة,1.0
5,AAPL,Apple,US,343.459991,0.426898,صاعد,4,مراقبة إيجابية,1.0
6,^FTSE,FTSE 100 UK,INDEX,10881.900391,0.382827,متذبذب,3,مراقبة إيجابية,1.0
7,SI=F,Silver,COMMODITY,56.994999,0.277983,هابط,0,مراقبة سلبية,1.0
8,^FCHI,CAC 40 France,INDEX,7956.700195,0.277263,متذبذب,3,مراقبة إيجابية,1.0
9,GC=F,Gold,COMMODITY,4181.100098,0.263783,هابط,2,مراقبة محايدة,1.0
10,1120.SR,Al Rajhi Bank,SAUDI,61.000000,0.246510,هابط,0,مراقبة سلبية,1.0
11,BTC-USD,Bitcoin,CRYPTO,81386.367188,-0.140413,متذبذب,1,مراقبة سلبية,1.0
12,2010.SR,SABIC,SAUDI,44.560001,-0.313198,هابط,0,مراقبة سلبية,1.0
13,^DJI,Dow Jones,INDEX,52002.410156,-0.335931,متذبذب,3,مراقبة إيجابية,1.0
14,2222.SR,Saudi Aramco,SAUDI,25.280001,-0.394005,هابط,1,مراقبة سلبية,1.0
15,^GSPC,S&P 500,INDEX,7659.439941,-1.092710,متذبذب,2,مراقبة محايدة,1.0
16,SPY,S&P 500 ETF,US,763.250000,-1.106516,متذبذب,2,مراقبة محايدة,1.0
17,NVDA,NVIDIA,US,214.130005,-1.427055,متذبذب,1,مراقبة سلبية,1.0
18,AMZN,Amazon,US,250.000000,-1.868423,هابط,2,مراقبة محايدة,1.0
19,MSFT,Microsoft,US,529.049988,-1.926074,صاعد,4,مراقبة إيجابية,1.0
20,TSLA,Tesla,US,354.720001,-2.130008,متذبذب,2,مراقبة محايدة,1.0
21,^IXIC,NASDAQ Composite,INDEX,26140.029297,-2.145021,متذبذب,1,مراقبة سلبية,1.0
22,GOOGL,Alphabet,US,340.589996,-2.471223,متذبذب,2,مراقبة محايدة,1.0
23,QQQ,Nasdaq ETF,US,709.799988,-2.500002,متذبذب,1,مراقبة سلبية,1.0
24,NG=F,Natural Gas,COMMODITY,3.116000,-3.708286,صاعد,4,مراقبة إيجابية,1.0
25,META,Meta,US,709.330017,-3.717824,متذبذب,2,مراقبة محايدة,1.0

🔍 جودة البيانات:

,ticker,price_data_available,technical_analysis_available,price_is_valid,status
0,NVDA,True,True,True,OK
1,TSLA,True,True,True,OK
2,AAPL,True,True,True,OK
3,MSFT,True,True,True,OK
4,AMZN,True,True,True,OK
5,GOOGL,True,True,True,OK
6,META,True,True,True,OK
7,QQQ,True,True,True,OK
8,SPY,True,True,True,OK
9,^GSPC,True,True,True,OK
10,^IXIC,True,True,True,OK
11,^DJI,True,True,True,OK
12,^GDAXI,True,True,True,OK
13,^FCHI,True,True,True,OK
14,^FTSE,True,True,True,OK
15,^N225,True,True,True,OK
16,^HSI,True,True,True,OK
17,GC=F,True,True,True,OK
18,SI=F,True,True,True,OK
19,CL=F,True,True,True,OK
20,BZ=F,True,True,True,OK
21,NG=F,True,True,True,OK
22,BTC-USD,True,True,True,OK
23,2222.SR,True,True,True,OK
24,1120.SR,True,True,True,OK
25,2010.SR,True,True,True,OK

💾 ملف Excel النهائي:
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_ai_final_report.xlsx

⚠️ تنبيه:
التحليل الفني وإدارة المخاطر أدوات معلوماتية نظرية، وليست توصيات مالية أو أوامر شراء وبيع.

🌧️ انتهى التنفيذ.

In [15]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 76
# محرك الفرص للأسهم السعودية والأمريكية
# تحديث البيانات | التحليل الفني | تقييم الفرص | إدارة المخاطر
# =====================================================================
# ملاحظات:
# 1) لا يحذف الجداول القديمة.
# 2) لا ينفذ عمليات شراء أو بيع حقيقية.
# 3) لا توجد توصيات مضمونة الربح.
# 4) يحتاج إلى قائمة رموز الأسهم CSV لفحص نطاق واسع.
# =====================================================================

!pip -q install yfinance openpyxl

import os
import time
import warnings
import numpy as np
import pandas as pd
import yfinance as yf

from datetime import datetime
from pathlib import Path

warnings.filterwarnings("ignore")

# =====================================================================
# 1) الإعدادات
# =====================================================================

# أدخلي رأس المال المتاح بالريال
CAPITAL_SAR = float(input("أدخلي رأس المال بالريال السعودي: ") or 100)

# نسبة المخاطرة المستهدفة من رأس المال لكل صفقة
RISK_PERCENT = 1.0

# أقصى نسبة من رأس المال تخصص لصفقة واحدة
MAX_POSITION_PERCENT = 20.0

# تحويل تقريبي للدولار إلى الريال
USD_SAR = 3.75

# وقف الخسارة يعتمد على ATR
ATR_STOP_MULTIPLIER = 2.0

# الهدف الأول: ضعف المسافة إلى وقف الخسارة
TARGET_R_MULTIPLIER = 2.0

# السماح بالأسهم الأمريكية الجزئية؟
ALLOW_FRACTIONAL_US = False

# أقل متوسط قيمة تداول يومية مقبولة بالريال
MIN_DAILY_VALUE_SAR = 500000

# عدد الأيام المطلوبة للتحليل
PERIOD = "1y"

# مجلد النتائج
try:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)
    OUTPUT_DIR = "/content/drive/MyDrive/الودق AI - نتائج المرحلة 76"
except Exception:
    OUTPUT_DIR = "/content/ودق_AI_المرحلة_76"

os.makedirs(OUTPUT_DIR, exist_ok=True)

RUN_DATE = datetime.now().strftime("%Y%m%d_%H%M%S")

print("=" * 70)
print("🌧️ الودق AI — المرحلة 76")
print("=" * 70)
print("رأس المال:", CAPITAL_SAR, "ريال")
print("ميزانية المخاطرة المستهدفة:", CAPITAL_SAR * RISK_PERCENT / 100, "ريال")
print("مجلد النتائج:", OUTPUT_DIR)

# =====================================================================
# 2) تحميل قوائم الأسهم
# =====================================================================

def load_ticker_csv(path, market):
    """
    قراءة قائمة الأسهم من CSV.
    يتوقع عمود ticker.
    """

    if not os.path.exists(path):
        return []

    try:
        df = pd.read_csv(path)

        ticker_col = None

        for col in df.columns:
            if str(col).strip().lower() in [
                "ticker", "symbol", "رمز", "الرمز"
            ]:
                ticker_col = col
                break

        if ticker_col is None:
            print(f"⚠️ ملف {market} لا يحتوي عمود ticker أو symbol.")
            return []

        tickers = (
            df[ticker_col]
            .dropna()
            .astype(str)
            .str.strip()
            .str.upper()
            .unique()
            .tolist()
        )

        return tickers

    except Exception as e:
        print(f"خطأ في قراءة ملف {market}: {e}")
        return []


# قائمة تجريبية عند عدم وجود ملفات CSV
DEFAULT_SAUDI = [
    "2222.SR", "1120.SR", "2010.SR",
    "1211.SR", "2380.SR", "7010.SR",
    "1150.SR", "1180.SR", "2082.SR",
    "7203.SR", "1320.SR", "4200.SR",
    "4001.SR", "4002.SR", "4003.SR",
    "4004.SR", "4005.SR", "4006.SR",
    "4007.SR", "4008.SR"
]

DEFAULT_US = [
    "AAPL", "MSFT", "NVDA", "AMZN", "GOOGL",
    "META", "TSLA", "AMD", "AVGO", "NFLX",
    "JPM", "BAC", "XOM", "LLY", "UNH",
    "COST", "WMT", "ORCL", "CRM", "QQQ",
    "SPY"
]

SAUDI_CSV = os.path.join(OUTPUT_DIR, "saudi_tickers.csv")
US_CSV = os.path.join(OUTPUT_DIR, "us_tickers.csv")

wadq76_saudi_tickers = load_ticker_csv(SAUDI_CSV, "السوق السعودي")
wadq76_us_tickers = load_ticker_csv(US_CSV, "السوق الأمريكي")

if not wadq76_saudi_tickers:
    wadq76_saudi_tickers = DEFAULT_SAUDI.copy()
    print("⚠️ لم توجد قائمة سعودية كاملة؛ سيتم استخدام القائمة التجريبية.")

if not wadq76_us_tickers:
    wadq76_us_tickers = DEFAULT_US.copy()
    print("⚠️ لم توجد قائمة أمريكية كاملة؛ سيتم استخدام القائمة التجريبية.")

wadq76_saudi_tickers = list(dict.fromkeys(wadq76_saudi_tickers))
wadq76_us_tickers = list(dict.fromkeys(wadq76_us_tickers))

wadq76_all_tickers = (
    wadq76_saudi_tickers + wadq76_us_tickers
)

wadq76_market_map = {}

for ticker in wadq76_saudi_tickers:
    wadq76_market_map[ticker] = "السوق السعودي"

for ticker in wadq76_us_tickers:
    wadq76_market_map[ticker] = "السوق الأمريكي"

print("عدد الأسهم السعودية:", len(wadq76_saudi_tickers))
print("عدد الأسهم الأمريكية:", len(wadq76_us_tickers))
print("إجمالي الأسهم:", len(wadq76_all_tickers))

# =====================================================================
# 3) تنزيل الأسعار
# =====================================================================

def download_market_data(tickers, period="1y", chunk_size=40):

    all_data = {}

    for start in range(0, len(tickers), chunk_size):

        batch = tickers[start:start + chunk_size]

        print(
            f"📥 تنزيل المجموعة "
            f"{start + 1} إلى {start + len(batch)}"
        )

        try:

            data = yf.download(
                tickers=batch,
                period=period,
                interval="1d",
                auto_adjust=True,
                group_by="ticker",
                threads=True,
                progress=False
            )

            if data is None or data.empty:
                print("⚠️ المجموعة لم تُرجع بيانات.")
                continue

            for ticker in batch:

                try:

                    # إذا كان تنزيل سهم واحد
                    if len(batch) == 1:

                        df = data.copy()

                    else:

                        if isinstance(data.columns, pd.MultiIndex):

                            ticker_level_found = False

                            for level in range(data.columns.nlevels):

                                vals = data.columns.get_level_values(level)

                                if ticker in vals:

                                    df = data.xs(
                                        ticker,
                                        axis=1,
                                        level=level,
                                        drop_level=True
                                    )

                                    ticker_level_found = True
                                    break

                            if not ticker_level_found:
                                continue

                        else:
                            df = data.copy()

                    if isinstance(df.columns, pd.MultiIndex):
                        df.columns = df.columns.get_level_values(-1)

                    df = df.copy()
                    df.columns = [str(c).title() for c in df.columns]

                    needed = [
                        "Open", "High", "Low",
                        "Close", "Volume"
                    ]

                    if not all(c in df.columns for c in needed):
                        continue

                    df = df[needed].dropna(subset=["Close"])

                    if len(df) >= 80:
                        all_data[ticker] = df

                except Exception as e:
                    print(f"⚠️ تعذر استخراج بيانات {ticker}: {e}")

        except Exception as e:
            print(f"⚠️ خطأ تنزيل المجموعة: {e}")

        time.sleep(1)

    return all_data


wadq76_price_data = download_market_data(
    wadq76_all_tickers,
    period=PERIOD
)

print("=" * 70)
print("عدد الأسهم التي نجح تنزيل بياناتها:", len(wadq76_price_data))
print("=" * 70)

# =====================================================================
# 4) حساب المؤشرات الفنية
# =====================================================================

def calculate_rsi(series, period=14):

    delta = series.diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    rs = avg_gain / avg_loss.replace(0, np.nan)

    rsi = 100 - (100 / (1 + rs))

    return rsi


def calculate_atr(df, period=14):

    high = df["High"]
    low = df["Low"]
    close = df["Close"]

    previous_close = close.shift(1)

    tr1 = high - low
    tr2 = (high - previous_close).abs()
    tr3 = (low - previous_close).abs()

    true_range = pd.concat(
        [tr1, tr2, tr3],
        axis=1
    ).max(axis=1)

    atr = true_range.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    return atr


def analyze_one_ticker(ticker, df):

    df = df.copy()
    df = df.sort_index()

    df["SMA20"] = df["Close"].rolling(20).mean()
    df["SMA50"] = df["Close"].rolling(50).mean()
    df["SMA200"] = df["Close"].rolling(200).mean()

    df["EMA12"] = df["Close"].ewm(
        span=12, adjust=False
    ).mean()

    df["EMA26"] = df["Close"].ewm(
        span=26, adjust=False
    ).mean()

    df["MACD"] = df["EMA12"] - df["EMA26"]

    df["MACD_SIGNAL"] = df["MACD"].ewm(
        span=9, adjust=False
    ).mean()

    df["MACD_HIST"] = (
        df["MACD"] - df["MACD_SIGNAL"]
    )

    df["RSI14"] = calculate_rsi(df["Close"], 14)
    df["ATR14"] = calculate_atr(df, 14)

    df["VOLUME_AVG20"] = df["Volume"].rolling(20).mean()

    df["VOLUME_RATIO"] = (
        df["Volume"] /
        df["VOLUME_AVG20"].replace(0, np.nan)
    )

    df["RETURN_5D"] = df["Close"].pct_change(5) * 100
    df["RETURN_20D"] = df["Close"].pct_change(20) * 100
    df["RETURN_60D"] = df["Close"].pct_change(60) * 100

    latest = df.iloc[-1]

    previous = df.iloc[-2]

    close = float(latest["Close"])
    sma20 = latest["SMA20"]
    sma50 = latest["SMA50"]
    sma200 = latest["SMA200"]

    rsi = latest["RSI14"]
    macd = latest["MACD"]
    macd_signal = latest["MACD_SIGNAL"]
    atr = latest["ATR14"]

    volume = latest["Volume"]
    volume_ratio = latest["VOLUME_RATIO"]

    # ---------------------------------------------------------------
    # فحص جودة البيانات
    # ---------------------------------------------------------------

    data_quality = "مقبولة"

    if not np.isfinite(close) or close <= 0:
        data_quality = "غير صالحة"

    elif not np.isfinite(rsi):
        data_quality = "مؤشرات ناقصة"

    elif not np.isfinite(atr) or atr <= 0:
        data_quality = "مؤشرات ناقصة"

    # ---------------------------------------------------------------
    # تحليل الاتجاه
    # ---------------------------------------------------------------

    trend_score = 0

    if np.isfinite(sma20) and close > sma20:
        trend_score += 1

    if np.isfinite(sma50) and close > sma50:
        trend_score += 1

    if np.isfinite(sma200) and close > sma200:
        trend_score += 1

    # ---------------------------------------------------------------
    # تحليل الزخم
    # ---------------------------------------------------------------

    momentum_score = 0

    if np.isfinite(macd) and np.isfinite(macd_signal):

        if macd > macd_signal:
            momentum_score += 1

        if macd > 0:
            momentum_score += 1

    if np.isfinite(rsi):

        if 50 <= rsi <= 68:
            momentum_score += 1

        elif rsi > 75:
            momentum_score -= 1

    # ---------------------------------------------------------------
    # تحليل السيولة
    # ---------------------------------------------------------------

    liquidity_score = 0

    if np.isfinite(volume_ratio):

        if volume_ratio >= 1.2:
            liquidity_score += 1

        if volume_ratio >= 2.0:
            liquidity_score += 1

    # ---------------------------------------------------------------
    # الدرجة الفنية
    # ---------------------------------------------------------------

    raw_score = (
        trend_score * 40 / 3
        + momentum_score * 40 / 4
        + liquidity_score * 20 / 2
    )

    score = max(0, min(100, raw_score))

    # ---------------------------------------------------------------
    # القرار المبدئي
    # ---------------------------------------------------------------

    if data_quality != "مقبولة":

        signal = "غير كافٍ للتحليل"

    elif (
        score >= 75
        and close > sma20
        and rsi >= 50
        and rsi <= 68
        and macd > macd_signal
    ):

        signal = "فرصة شراء محتملة"

    elif (
        score >= 55
        and close > sma20
    ):

        signal = "مراقبة وانتظار"

    else:

        signal = "تجنب الدخول حاليًا"

    # ---------------------------------------------------------------
    # مستويات المخاطر
    # ---------------------------------------------------------------

    stop_loss = np.nan
    target = np.nan
    risk_per_share_sar = np.nan
    quantity = 0
    position_value_sar = 0
    risk_amount_sar = 0

    market = wadq76_market_map.get(
        ticker,
        "غير معروف"
    )

    # السعر بالريال
    if market == "السوق السعودي":

        price_sar = close

    else:

        price_sar = close * USD_SAR

    # مستويات نظرية وليست أوامر تنفيذ
    if (
        np.isfinite(atr)
        and atr > 0
        and close > 0
    ):

        stop_loss = close - (
            ATR_STOP_MULTIPLIER * atr
        )

        target = close + (
            TARGET_R_MULTIPLIER
            * ATR_STOP_MULTIPLIER
            * atr
        )

        if stop_loss > 0:

            if market == "السوق السعودي":

                risk_per_share_sar = close - stop_loss

            else:

                risk_per_share_sar = (
                    close - stop_loss
                ) * USD_SAR

            risk_budget = (
                CAPITAL_SAR
                * RISK_PERCENT
                / 100
            )

            max_position_value = (
                CAPITAL_SAR
                * MAX_POSITION_PERCENT
                / 100
            )

            if risk_per_share_sar > 0:

                qty_by_risk = (
                    risk_budget
                    / risk_per_share_sar
                )

                qty_by_capital = (
                    max_position_value
                ) / price_sar

                qty = min(
                    qty_by_risk,
                    qty_by_capital
                )

                if market == "السوق السعودي":

                    quantity = int(np.floor(qty))

                elif ALLOW_FRACTIONAL_US:

                    quantity = round(qty, 4)

                else:

                    quantity = int(np.floor(qty))

                if quantity > 0:

                    position_value_sar = (
                        quantity * price_sar
                    )

                    risk_amount_sar = (
                        quantity
                        * risk_per_share_sar
                    )

    # ---------------------------------------------------------------
    # فحص إضافي: هل رأس المال يكفي؟
    # ---------------------------------------------------------------

    if quantity <= 0:

        capital_status = (
            "رأس المال لا يكفي للكمية المحسوبة "
            "أو لا توجد بيانات مناسبة"
        )

    else:

        capital_status = "الكمية النظرية محسوبة"

    # ---------------------------------------------------------------
    # درجة جودة البيانات
    # ---------------------------------------------------------------

    latest_date = df.index[-1]

    try:
        latest_date = pd.to_datetime(
            latest_date
        ).strftime("%Y-%m-%d")
    except Exception:
        latest_date = str(latest_date)

    result = {

        "ticker": ticker,
        "market": market,

        "date": latest_date,

        "price": close,
        "price_sar": price_sar,

        "SMA20": sma20,
        "SMA50": sma50,
        "SMA200": sma200,

        "RSI14": rsi,

        "MACD": macd,
        "MACD_SIGNAL": macd_signal,

        "ATR14": atr,

        "volume": volume,
        "volume_ratio": volume_ratio,

        "return_5d": latest["RETURN_5D"],
        "return_20d": latest["RETURN_20D"],
        "return_60d": latest["RETURN_60D"],

        "trend_score": trend_score,
        "momentum_score": momentum_score,
        "liquidity_score": liquidity_score,

        "technical_score": round(score, 2),

        "signal": signal,

        "stop_loss": stop_loss,
        "target": target,

        "risk_per_share_sar": risk_per_share_sar,

        "quantity": quantity,

        "position_value_sar": position_value_sar,

        "risk_amount_sar": risk_amount_sar,

        "capital_status": capital_status,

        "data_quality": data_quality
    }

    return result, df


# =====================================================================
# 5) تحليل جميع الأسهم
# =====================================================================

wadq76_results = []
wadq76_history = {}

for ticker, df in wadq76_price_data.items():

    try:

        result, history = analyze_one_ticker(
            ticker,
            df
        )

        wadq76_results.append(result)
        wadq76_history[ticker] = history

    except Exception as e:

        print(f"⚠️ تعذر تحليل {ticker}: {e}")


wadq76_analysis_df = pd.DataFrame(
    wadq76_results
)

if wadq76_analysis_df.empty:

    raise ValueError(
        "لم يتم إنشاء نتائج. راجعي تنزيل الأسعار وقائمة الأسهم."
    )

# =====================================================================
# 6) ترتيب الفرص
# =====================================================================

wadq76_analysis_df = wadq76_analysis_df.sort_values(
    by=["technical_score", "volume_ratio"],
    ascending=[False, False]
).reset_index(drop=True)

wadq76_analysis_df["rank"] = (
    np.arange(1, len(wadq76_analysis_df) + 1)
)

wadq76_opportunities_df = wadq76_analysis_df[
    wadq76_analysis_df["signal"] == "فرصة شراء محتملة"
].copy()

wadq76_watchlist_df = wadq76_analysis_df[
    wadq76_analysis_df["signal"] == "مراقبة وانتظار"
].copy()

wadq76_avoid_df = wadq76_analysis_df[
    wadq76_analysis_df["signal"] == "تجنب الدخول حاليًا"
].copy()

# =====================================================================
# 7) تقرير الفرص النهائي
# =====================================================================

wadq76_final_report_df = wadq76_analysis_df[
    [
        "rank",
        "ticker",
        "market",
        "date",
        "price",
        "price_sar",
        "technical_score",
        "RSI14",
        "MACD",
        "MACD_SIGNAL",
        "volume_ratio",
        "return_20d",
        "signal",
        "stop_loss",
        "target",
        "quantity",
        "position_value_sar",
        "risk_amount_sar",
        "capital_status",
        "data_quality"
    ]
].copy()

# =====================================================================
# 8) لوحة القرار
# =====================================================================

wadq76_decision_board_df = wadq76_final_report_df[
    [
        "rank",
        "ticker",
        "market",
        "technical_score",
        "signal",
        "price",
        "stop_loss",
        "target",
        "quantity",
        "position_value_sar",
        "risk_amount_sar"
    ]
].copy()

# =====================================================================
# 9) تقرير جودة البيانات
# =====================================================================

wadq76_quality_df = wadq76_analysis_df[
    [
        "ticker",
        "market",
        "date",
        "data_quality",
        "technical_score",
        "signal"
    ]
].copy()

wadq76_quality_df["quality_check"] = np.where(
    wadq76_quality_df["data_quality"] == "مقبولة",
    "اجتاز الفحص الأساسي",
    "يحتاج مراجعة"
)

# =====================================================================
# 10) ملخص التنفيذ
# =====================================================================

wadq76_summary = pd.DataFrame([{

    "run_date": datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    ),

    "capital_sar": CAPITAL_SAR,

    "risk_percent": RISK_PERCENT,

    "risk_budget_sar": (
        CAPITAL_SAR * RISK_PERCENT / 100
    ),

    "max_position_percent": MAX_POSITION_PERCENT,

    "saudi_tickers": len(wadq76_saudi_tickers),

    "us_tickers": len(wadq76_us_tickers),

    "downloaded_tickers": len(wadq76_price_data),

    "analyzed_tickers": len(wadq76_analysis_df),

    "buy_opportunities": len(wadq76_opportunities_df),

    "watch_opportunities": len(wadq76_watchlist_df),

    "avoid_opportunities": len(wadq76_avoid_df),

    "failed_downloads": (
        len(wadq76_all_tickers)
        - len(wadq76_price_data)
    )

}])

# =====================================================================
# 11) حفظ التقرير
# =====================================================================

excel_path = os.path.join(
    OUTPUT_DIR,
    f"wadq76_report_{RUN_DATE}.xlsx"
)

csv_path = os.path.join(
    OUTPUT_DIR,
    f"wadq76_report_{RUN_DATE}.csv"
)

with pd.ExcelWriter(
    excel_path,
    engine="openpyxl"
) as writer:

    wadq76_final_report_df.to_excel(
        writer,
        sheet_name="Final Report",
        index=False
    )

    wadq76_decision_board_df.to_excel(
        writer,
        sheet_name="Decision Board",
        index=False
    )

    wadq76_opportunities_df.to_excel(
        writer,
        sheet_name="Opportunities",
        index=False
    )

    wadq76_watchlist_df.to_excel(
        writer,
        sheet_name="Watchlist",
        index=False
    )

    wadq76_avoid_df.to_excel(
        writer,
        sheet_name="Avoid",
        index=False
    )

    wadq76_quality_df.to_excel(
        writer,
        sheet_name="Quality",
        index=False
    )

    wadq76_summary.to_excel(
        writer,
        sheet_name="Summary",
        index=False
    )

wadq76_final_report_df.to_csv(
    csv_path,
    index=False,
    encoding="utf-8-sig"
)

print("=" * 70)
print("🌧️ انتهت المرحلة 76")
print("=" * 70)

print("عدد الأسهم المحللة:", len(wadq76_analysis_df))
print("فرص شراء محتملة:", len(wadq76_opportunities_df))
print("فرص مراقبة:", len(wadq76_watchlist_df))
print("أسهم تحتاج تجنب الدخول:", len(wadq76_avoid_df))

print("=" * 70)
print("📊 أفضل 20 سهم حسب الدرجة الفنية")
print("=" * 70)

display(
    wadq76_final_report_df.head(20)
)

print("=" * 70)
print("📁 ملف Excel:")
print(excel_path)

print("=" * 70)
print("📁 ملف CSV:")
print(csv_path)

print("=" * 70)
print("⚠️ هذه إشارات تحليلية وليست ضمانًا للربح.")
print("⚠️ راجعي البيانات والرسوم والسيولة قبل تنفيذ أي صفقة.")
print("=" * 70)

أدخلي رأس المال بالريال السعودي: 1000
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
======================================================================
🌧️ الودق AI — المرحلة 76
======================================================================
رأس المال: 1000.0 ريال
ميزانية المخاطرة المستهدفة: 10.0 ريال
مجلد النتائج: /content/drive/MyDrive/الودق AI - نتائج المرحلة 76
⚠️ لم توجد قائمة سعودية كاملة؛ سيتم استخدام القائمة التجريبية.
⚠️ لم توجد قائمة أمريكية كاملة؛ سيتم استخدام القائمة التجريبية.
عدد الأسهم السعودية: 20
عدد الأسهم الأمريكية: 21
إجمالي الأسهم: 41
📥 تنزيل المجموعة 1 إلى 40
📥 تنزيل المجموعة 41 إلى 41
======================================================================
عدد الأسهم التي نجح تنزيل بياناتها: 41
======================================================================
======================================================================
🌧️ انتهت المرحلة 76
======================================================================
عدد الأسهم المحللة: 41
فرص شراء محتملة: 2
فرص مراقبة: 7
أسهم تحتاج تجنب الدخول: 32
======================================================================
📊 أفضل 20 سهم حسب الدرجة الفنية
======================================================================

,rank,ticker,market,date,price,price_sar,technical_score,RSI14,MACD,MACD_SIGNAL,volume_ratio,return_20d,signal,stop_loss,target,quantity,position_value_sar,risk_amount_sar,capital_status,data_quality
0,1,1320.SR,السوق السعودي,2026-10-15,55.799999,55.799999,80.00,56.526097,0.362243,0.394183,2.508544,0.000000,مراقبة وانتظار,52.243158,62.913682,2,111.599998,7.113683,الكمية النظرية محسوبة,مقبولة
1,2,AAPL,السوق الأمريكي,2026-10-16,343.459991,1287.974968,80.00,62.082319,4.138792,3.944912,1.619236,2.180700,فرصة شراء محتملة,330.064631,370.250713,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
2,3,UNH,السوق الأمريكي,2026-10-16,401.429993,1505.362473,80.00,63.275710,2.542475,-1.679734,1.366476,6.508357,فرصة شراء محتملة,377.260468,449.769043,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
3,4,MSFT,السوق الأمريكي,2026-10-16,529.049988,1983.937454,70.00,57.358140,11.253144,10.980207,1.111926,7.142855,مراقبة وانتظار,505.035697,577.078569,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
4,5,CRM,السوق الأمريكي,2026-10-16,240.699997,902.624989,70.00,55.841043,1.941746,1.225412,0.927656,1.168459,مراقبة وانتظار,222.560707,276.978578,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
5,6,XOM,السوق الأمريكي,2026-10-16,178.979996,671.174984,60.00,72.994191,3.879453,2.499435,1.123151,9.441117,مراقبة وانتظار,171.707579,193.524828,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
6,7,COST,السوق الأمريكي,2026-10-16,989.109985,3709.162445,60.00,72.484886,14.851196,7.226108,1.092320,10.476817,مراقبة وانتظار,956.125117,1055.079721,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
7,8,LLY,السوق الأمريكي,2026-10-16,1257.030029,4713.862610,60.00,68.583846,15.510110,5.148791,1.048977,9.029167,مراقبة وانتظار,1185.439215,1400.211659,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
8,9,WMT,السوق الأمريكي,2026-10-16,118.809998,445.537491,60.00,73.014710,2.262457,0.912477,0.949741,11.318274,مراقبة وانتظار,113.906066,128.617862,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
9,10,JPM,السوق الأمريكي,2026-10-16,339.720001,1273.950005,46.67,52.345394,-3.006941,-4.236789,1.028799,-2.360849,تجنب الدخول حاليًا,326.685144,365.789716,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
10,11,META,السوق الأمريكي,2026-10-16,709.330017,2659.987564,46.67,50.258922,19.475681,25.564046,0.945816,6.630084,تجنب الدخول حاليًا,658.733607,810.522837,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
11,12,QQQ,السوق الأمريكي,2026-10-16,709.799988,2661.749954,33.33,35.136131,1.659163,6.325403,1.854021,-1.512288,تجنب الدخول حاليًا,688.686813,752.026337,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
12,13,SPY,السوق الأمريكي,2026-10-16,763.250000,2862.187500,33.33,44.185450,2.024268,2.884984,1.526261,0.204807,تجنب الدخول حاليًا,749.262399,791.225203,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
13,14,NFLX,السوق الأمريكي,2026-10-16,70.529999,264.487495,33.33,45.526101,-1.130443,-1.600641,1.252639,-1.755122,تجنب الدخول حاليًا,66.745625,78.098746,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
14,15,AMZN,السوق الأمريكي,2026-10-16,250.000000,937.500000,33.33,44.993070,0.185668,0.056647,1.125863,-1.462302,تجنب الدخول حاليًا,238.100667,273.798667,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
15,16,GOOGL,السوق الأمريكي,2026-10-16,340.589996,1277.212486,23.33,44.465854,1.021960,1.195935,1.135028,-2.560512,تجنب الدخول حاليًا,322.779937,376.210114,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
16,17,AMD,السوق الأمريكي,2026-10-16,528.750000,1982.812500,23.33,37.765730,7.829021,21.929172,1.057600,-5.549999,تجنب الدخول حاليًا,474.208065,637.833870,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
17,18,TSLA,السوق الأمريكي,2026-10-16,354.720001,1330.200005,20.00,42.203875,1.414684,3.505525,1.794872,-2.621678,تجنب الدخول حاليًا,331.024064,402.111876,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
18,19,NVDA,السوق الأمريكي,2026-10-16,214.130005,802.987518,13.33,37.558177,-0.147866,2.217692,1.152517,-3.662212,تجنب الدخول حاليًا,202.200704,237.988606,0,0.000000,0.000000,رأس المال لا يكفي للكمية المحسوبة أو لا توجد ب...,مقبولة
19,20,1150.SR,السوق السعودي,2026-10-15,23.629999,23.629999,13.33,37.963927,-0.289459,-0.202278,0.898081,-4.215650,تجنب الدخول حاليًا,22.912416,25.065165,8,189.039993,5.740662,الكمية النظرية محسوبة,مقبولة

======================================================================
📁 ملف Excel:
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.xlsx
======================================================================
📁 ملف CSV:
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.csv
======================================================================
⚠️ هذه إشارات تحليلية وليست ضمانًا للربح.
⚠️ راجعي البيانات والرسوم والسيولة قبل تنفيذ أي صفقة.
======================================================================

In [16]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 77
# تصحيح خطة الكميات وإدارة رأس المال
# لا يعيد تنزيل الأسعار
# لا ينفذ صفقات حقيقية
# =====================================================================

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------
# 1) إعداد رأس المال والمخاطر
# ---------------------------------------------------------------------

CAPITAL_SAR = float(
    input("أدخلي رأس المال المتاح بالريال: ") or 1000
)

RISK_PERCENT = 1.0
MAX_POSITION_PERCENT = 20.0

risk_budget_sar = CAPITAL_SAR * RISK_PERCENT / 100
max_position_sar = CAPITAL_SAR * MAX_POSITION_PERCENT / 100

print("=" * 65)
print("🌧️ الودق AI — المرحلة 77")
print("=" * 65)
print("رأس المال:", CAPITAL_SAR, "ريال")
print("ميزانية المخاطرة النظرية:", risk_budget_sar, "ريال")
print("الحد الأقصى المخصص للصفقة:", max_position_sar, "ريال")

# ---------------------------------------------------------------------
# 2) استخدام جدول المرحلة 76 الموجود
# ---------------------------------------------------------------------

if "wadq76_analysis_df" not in globals():
    raise ValueError(
        "جدول wadq76_analysis_df غير موجود. "
        "شغّلي المرحلة 76 أولًا."
    )

wadq77_source_df = wadq76_analysis_df.copy()

# ---------------------------------------------------------------------
# 3) بناء خطة تداول جديدة
# ---------------------------------------------------------------------

wadq77_trade_plan = []

for _, row in wadq77_source_df.iterrows():

    ticker = row["ticker"]
    market = row["market"]
    signal = row["signal"]

    price_sar = float(row["price_sar"])
    stop_loss = float(row["stop_loss"])
    target = float(row["target"])

    quantity = 0
    position_value = 0
    expected_risk = 0

    status = "لا توجد إشارة شراء"

    # لا نحسب كمية شراء للأسهم التي ليست فرص شراء
    if signal != "فرصة شراء محتملة":

        status = "انتظار — لا شراء"

    elif (
        not np.isfinite(price_sar)
        or not np.isfinite(stop_loss)
        or price_sar <= 0
        or stop_loss <= 0
        or stop_loss >= price_sar
    ):

        status = "رفض — مستويات الأسعار غير صالحة"

    else:

        # -------------------------------------------------------------
        # حساب المخاطرة للسهم الواحد
        # -------------------------------------------------------------

        risk_per_share = price_sar - (
            stop_loss * (
                1 if market == "السوق السعودي" else 3.75
            )
        )

        # السعر الأمريكي في التقرير بالدولار،
        # والوقف أيضًا بالدولار
        if market == "السوق الأمريكي":

            risk_per_share = (
                float(row["price"]) - stop_loss
            ) * 3.75

        if risk_per_share <= 0:

            status = "رفض — المخاطرة غير صالحة"

        else:

            # الكمية التي تسمح بها ميزانية المخاطرة
            qty_by_risk = (
                risk_budget_sar / risk_per_share
            )

            # الكمية التي يسمح بها رأس المال
            qty_by_capital = (
                max_position_sar / price_sar
            )

            qty = min(
                qty_by_risk,
                qty_by_capital
            )

            # الأسهم السعودية والأمريكية: أسهم كاملة فقط
            quantity = int(np.floor(qty))

            if quantity <= 0:

                status = (
                    "رفض — رأس المال لا يكفي لشراء سهم كامل"
                )

            else:

                position_value = quantity * price_sar
                expected_risk = quantity * risk_per_share

                status = (
                    "خطة نظرية — راجعي السعر والرسوم قبل التنفيذ"
                )

    wadq77_trade_plan.append({

        "ticker": ticker,
        "market": market,
        "technical_score": row["technical_score"],
        "signal": signal,

        "price_sar": price_sar,

        "stop_loss": stop_loss,
        "target": target,

        "quantity": quantity,

        "position_value_sar": position_value,
        "expected_risk_sar": expected_risk,

        "status": status

    })

# ---------------------------------------------------------------------
# 4) إنشاء التقرير
# ---------------------------------------------------------------------

wadq77_trade_plan_df = pd.DataFrame(
    wadq77_trade_plan
)

wadq77_buy_candidates_df = wadq77_trade_plan_df[
    wadq77_trade_plan_df["quantity"] > 0
].copy()

wadq77_rejected_df = wadq77_trade_plan_df[
    wadq77_trade_plan_df["quantity"] == 0
].copy()

# ---------------------------------------------------------------------
# 5) حفظ النتائج
# ---------------------------------------------------------------------

import os
from datetime import datetime

OUTPUT_DIR = (
    "/content/drive/MyDrive/"
    "الودق AI - نتائج المرحلة 76"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)

RUN_DATE = datetime.now().strftime("%Y%m%d_%H%M%S")

excel_path = os.path.join(
    OUTPUT_DIR,
    f"wadq77_trade_plan_{RUN_DATE}.xlsx"
)

csv_path = os.path.join(
    OUTPUT_DIR,
    f"wadq77_trade_plan_{RUN_DATE}.csv"
)

with pd.ExcelWriter(
    excel_path,
    engine="openpyxl"
) as writer:

    wadq77_trade_plan_df.to_excel(
        writer,
        sheet_name="Trade Plan",
        index=False
    )

    wadq77_buy_candidates_df.to_excel(
        writer,
        sheet_name="Buy Candidates",
        index=False
    )

    wadq77_rejected_df.to_excel(
        writer,
        sheet_name="Rejected",
        index=False
    )

wadq77_trade_plan_df.to_csv(
    csv_path,
    index=False,
    encoding="utf-8-sig"
)

# ---------------------------------------------------------------------
# 6) عرض النتيجة
# ---------------------------------------------------------------------

print("=" * 65)
print("🌧️ انتهت المرحلة 77")
print("=" * 65)

print("الأسهم التي لديها خطة شراء نظرية:",
      len(wadq77_buy_candidates_df))

print("الأسهم التي لم تسمح الكمية بشرائها:",
      len(wadq77_rejected_df))

print("=" * 65)
print("📊 خطة الشراء النظرية")
print("=" * 65)

display(wadq77_buy_candidates_df)

print("=" * 65)
print("📁 ملف Excel:")
print(excel_path)

print("📁 ملف CSV:")
print(csv_path)

print("=" * 65)
print("⚠️ هذه ليست أوامر تداول.")
print("⚠️ الحساب لا يضمن أن وقف الخسارة سينفذ بالسعر المحدد.")
print("⚠️ لا يشمل الرسوم أو الانزلاق السعري.")
print("=" * 65)

أدخلي رأس المال المتاح بالريال: 10000
=================================================================
🌧️ الودق AI — المرحلة 77
=================================================================
رأس المال: 10000.0 ريال
ميزانية المخاطرة النظرية: 100.0 ريال
الحد الأقصى المخصص للصفقة: 2000.0 ريال
=================================================================
🌧️ انتهت المرحلة 77
=================================================================
الأسهم التي لديها خطة شراء نظرية: 2
الأسهم التي لم تسمح الكمية بشرائها: 39
=================================================================
📊 خطة الشراء النظرية
=================================================================

,ticker,market,technical_score,signal,price_sar,stop_loss,target,quantity,position_value_sar,expected_risk_sar,status
1,AAPL,السوق الأمريكي,80.0,فرصة شراء محتملة,1287.974968,330.064631,370.250713,1,1287.974968,50.232602,خطة نظرية — راجعي السعر والرسوم قبل التنفيذ
2,UNH,السوق الأمريكي,80.0,فرصة شراء محتملة,1505.362473,377.260468,449.769043,1,1505.362473,90.635719,خطة نظرية — راجعي السعر والرسوم قبل التنفيذ

=================================================================
📁 ملف Excel:
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.xlsx
📁 ملف CSV:
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.csv
=================================================================
⚠️ هذه ليست أوامر تداول.
⚠️ الحساب لا يضمن أن وقف الخسارة سينفذ بالسعر المحدد.
⚠️ لا يشمل الرسوم أو الانزلاق السعري.
=================================================================

In [17]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 78
# ضبط إجمالي مخاطر المحفظة
# =====================================================================

import numpy as np
import pandas as pd

# استخدام رأس المال من المرحلة 77
portfolio_capital = CAPITAL_SAR

# ميزانية المخاطرة القصوى للمحفظة
portfolio_risk_limit = portfolio_capital * 0.01

# الحد الأقصى لإجمالي المراكز
portfolio_position_limit = portfolio_capital * 0.20

# استخدام فرص الشراء الحالية
candidates = wadq77_buy_candidates_df.copy()

# ترتيب الفرص حسب الدرجة الفنية
candidates = candidates.sort_values(
    "technical_score",
    ascending=False
)

allocated = []
remaining_risk = portfolio_risk_limit
remaining_capital = portfolio_position_limit

for _, row in candidates.iterrows():

    ticker = row["ticker"]

    price_sar = float(row["price_sar"])

    risk_per_share = (
        float(row["expected_risk_sar"])
        / max(int(row["quantity"]), 1)
    )

    # لا نقبل بيانات غير صالحة
    if (
        not np.isfinite(price_sar)
        or not np.isfinite(risk_per_share)
        or price_sar <= 0
        or risk_per_share <= 0
    ):
        continue

    # الكمية المسموحة وفق المخاطر المتبقية
    qty_by_risk = int(
        np.floor(remaining_risk / risk_per_share)
    )

    # الكمية المسموحة وفق رأس المال المتبقي
    qty_by_capital = int(
        np.floor(remaining_capital / price_sar)
    )

    # الكمية النهائية
    qty = min(qty_by_risk, qty_by_capital)

    if qty <= 0:
        print(
            f"⏸️ {ticker}: لم يعد هناك "
            "رأس مال أو ميزانية مخاطر كافية."
        )
        continue

    position_value = qty * price_sar
    expected_risk = qty * risk_per_share

    allocated.append({
        "ticker": ticker,
        "market": row["market"],
        "technical_score": row["technical_score"],
        "quantity": qty,
        "price_sar": price_sar,
        "position_value_sar": position_value,
        "expected_risk_sar": expected_risk
    })

    remaining_risk -= expected_risk
    remaining_capital -= position_value

# إنشاء التقرير
wadq78_portfolio_df = pd.DataFrame(allocated)

print("=" * 60)
print("🌧️ الودق AI — المرحلة 78")
print("=" * 60)

if wadq78_portfolio_df.empty:

    print("لا توجد كمية تسمح بها ميزانية المخاطر الحالية.")

else:

    display(wadq78_portfolio_df)

    print("إجمالي قيمة المراكز:",
          round(wadq78_portfolio_df["position_value_sar"].sum(), 2),
          "ريال")

    print("إجمالي المخاطرة النظرية:",
          round(wadq78_portfolio_df["expected_risk_sar"].sum(), 2),
          "ريال")

    print("ميزانية المخاطرة:",
          round(portfolio_risk_limit, 2),
          "ريال")

print("=" * 60)
print("⚠️ هذه محاكاة حسابية وليست توصية شراء.")
print("⚠️ لم تشمل الرسوم والانزلاق السعري.")
print("=" * 60)

⏸️ UNH: لم يعد هناك رأس مال أو ميزانية مخاطر كافية.
============================================================
🌧️ الودق AI — المرحلة 78
============================================================

,ticker,market,technical_score,quantity,price_sar,position_value_sar,expected_risk_sar
0,AAPL,السوق الأمريكي,80.0,1,1287.974968,1287.974968,50.232602

إجمالي قيمة المراكز: 1287.97 ريال
إجمالي المخاطرة النظرية: 50.23 ريال
ميزانية المخاطرة: 100.0 ريال
============================================================
⚠️ هذه محاكاة حسابية وليست توصية شراء.
⚠️ لم تشمل الرسوم والانزلاق السعري.
============================================================

In [18]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 79
# محرك التوصيات الفنية وإدارة المخاطر
# =====================================================================

!pip -q install yfinance pandas numpy openpyxl

import warnings
import numpy as np
import pandas as pd
import yfinance as yf
from datetime import datetime

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------
# 1. إعداد رأس المال والمخاطر
# ---------------------------------------------------------------------

WADQ_CAPITAL_SAR = 100.0
WADQ_RISK_PCT = 0.01
WADQ_MAX_POSITION_PCT = 0.25
WADQ_MIN_HISTORY = 80

# ---------------------------------------------------------------------
# 2. الأصول المراد تحليلها
# ---------------------------------------------------------------------

WADQ_TICKERS = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY",
    "2222.SR", "1180.SR", "2010.SR",
    "GC=F", "SI=F", "CL=F", "BZ=F",
    "BTC-USD"
]

# ---------------------------------------------------------------------
# 3. حساب RSI
# ---------------------------------------------------------------------

def wadq_rsi(series, period=14):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    rs = avg_gain / avg_loss.replace(0, np.nan)

    return 100 - (100 / (1 + rs))


# ---------------------------------------------------------------------
# 4. حساب ATR
# ---------------------------------------------------------------------

def wadq_atr(df, period=14):

    high = df["High"]
    low = df["Low"]
    close = df["Close"]

    prev_close = close.shift(1)

    tr = pd.concat([
        high - low,
        (high - prev_close).abs(),
        (low - prev_close).abs()
    ], axis=1).max(axis=1)

    return tr.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()


# ---------------------------------------------------------------------
# 5. تحليل كل سهم
# ---------------------------------------------------------------------

def wadq_analyze_ticker(ticker):

    try:

        df = yf.download(
            ticker,
            period="1y",
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )

        if df is None or df.empty:

            return {
                "ticker": ticker,
                "status": "بيانات غير متاحة",
                "signal": "انتظار"
            }

        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        required = ["Open", "High", "Low", "Close", "Volume"]

        if not all(c in df.columns for c in required):

            return {
                "ticker": ticker,
                "status": "بيانات ناقصة",
                "signal": "انتظار"
            }

        df = df[required].copy()

        for col in required:
            df[col] = pd.to_numeric(df[col], errors="coerce")

        df = df.dropna(subset=["High", "Low", "Close"])

        if len(df) < WADQ_MIN_HISTORY:

            return {
                "ticker": ticker,
                "status": "تاريخ غير كافٍ",
                "signal": "انتظار"
            }

        # المؤشرات الفنية
        df["SMA20"] = df["Close"].rolling(20).mean()
        df["SMA50"] = df["Close"].rolling(50).mean()
        df["RSI14"] = wadq_rsi(df["Close"])

        ema12 = df["Close"].ewm(span=12, adjust=False).mean()
        ema26 = df["Close"].ewm(span=26, adjust=False).mean()

        df["MACD"] = ema12 - ema26

        df["MACD_SIGNAL"] = df["MACD"].ewm(
            span=9,
            adjust=False
        ).mean()

        df["ATR14"] = wadq_atr(df)

        last = df.iloc[-1]

        price = float(last["Close"])
        sma20 = float(last["SMA20"])
        sma50 = float(last["SMA50"])
        rsi = float(last["RSI14"])
        macd = float(last["MACD"])
        macd_signal = float(last["MACD_SIGNAL"])
        atr = float(last["ATR14"])

        if not all(np.isfinite(x) for x in [
            price, sma20, sma50, rsi, macd, macd_signal, atr
        ]):

            return {
                "ticker": ticker,
                "status": "مؤشرات ناقصة",
                "signal": "انتظار"
            }

        # -------------------------------------------------------------
        # 6. تحديد الاتجاه
        # -------------------------------------------------------------

        trend_up = price > sma20 > sma50
        trend_down = price < sma20 < sma50

        momentum_up = macd > macd_signal
        momentum_down = macd < macd_signal

        buy_conditions = (
            trend_up
            and momentum_up
            and 45 <= rsi <= 68
        )

        sell_conditions = (
            trend_down
            and momentum_down
            and rsi < 48
        )

        if buy_conditions:

            signal = "شراء محتمل"
            reason = "اتجاه صاعد وزخم إيجابي"

        elif sell_conditions:

            signal = "إشارة بيع فني"
            reason = "اتجاه هابط وزخم سلبي"

        else:

            signal = "انتظار"
            reason = "شروط التداول غير مكتملة"

        # -------------------------------------------------------------
        # 7. حساب مستويات المخاطر
        # -------------------------------------------------------------

        entry = price

        stop = price - (2 * atr)

        target1 = price + (2 * atr)

        target2 = price + (3 * atr)

        risk_per_share = max(entry - stop, 0)

        risk_budget = WADQ_CAPITAL_SAR * WADQ_RISK_PCT

        max_position_value = (
            WADQ_CAPITAL_SAR * WADQ_MAX_POSITION_PCT
        )

        if risk_per_share > 0:

            qty_by_risk = int(
                risk_budget // risk_per_share
            )

        else:

            qty_by_risk = 0

        qty_by_capital = int(
            max_position_value // entry
        )

        quantity = min(
            qty_by_risk,
            qty_by_capital
        )

        quantity = max(quantity, 0)

        if signal == "شراء محتمل" and quantity < 1:

            signal = "انتظار"

            reason = "رأس المال غير كافٍ للمخاطرة المحددة"

        # -------------------------------------------------------------
        # 8. إنشاء التقرير
        # -------------------------------------------------------------

        return {

            "ticker": ticker,
            "status": "سليم",
            "date": str(df.index[-1].date()),

            "price": round(price, 4),

            "change_pct": round(
                float(df["Close"].pct_change().iloc[-1] * 100),
                2
            ),

            "RSI14": round(rsi, 2),

            "SMA20": round(sma20, 4),

            "SMA50": round(sma50, 4),

            "MACD": round(macd, 4),

            "MACD_SIGNAL": round(macd_signal, 4),

            "ATR14": round(atr, 4),

            "signal": signal,

            "reason": reason,

            "entry_reference": round(entry, 4)
            if signal == "شراء محتمل" else np.nan,

            "stop_reference": round(stop, 4)
            if signal == "شراء محتمل" else np.nan,

            "target1_reference": round(target1, 4)
            if signal == "شراء محتمل" else np.nan,

            "target2_reference": round(target2, 4)
            if signal == "شراء محتمل" else np.nan,

            "risk_budget_SAR": round(risk_budget, 2),

            "theoretical_quantity": quantity
            if signal == "شراء محتمل" else 0,

            "theoretical_value": round(quantity * entry, 2)
            if signal == "شراء محتمل" else 0

        }

    except Exception as e:

        return {
            "ticker": ticker,
            "status": "خطأ",
            "signal": "انتظار",
            "reason": str(e)[:200]
        }


# ---------------------------------------------------------------------
# 9. تشغيل جميع الأصول
# ---------------------------------------------------------------------

print("=" * 60)
print("🌧️ الودق AI — المرحلة 79")
print("محرك التوصيات وإدارة المخاطر")
print("=" * 60)

results = []

for ticker in WADQ_TICKERS:

    print("تحليل:", ticker)

    result = wadq_analyze_ticker(ticker)

    results.append(result)

wadq_phase79_df = pd.DataFrame(results)

# ---------------------------------------------------------------------
# 10. استخراج الفرص
# ---------------------------------------------------------------------

if "signal" in wadq_phase79_df.columns:

    wadq_phase79_opportunities_df = wadq_phase79_df[
        wadq_phase79_df["signal"].isin([
            "شراء محتمل",
            "إشارة بيع فني"
        ])
    ].copy()

else:

    wadq_phase79_opportunities_df = pd.DataFrame()

print("\nالتقرير الكامل:")

display(wadq_phase79_df)

print("\nالفرص المحتملة:")

display(wadq_phase79_opportunities_df)

# ---------------------------------------------------------------------
# 11. حفظ التقارير
# ---------------------------------------------------------------------

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

csv_path = f"/content/wadq_phase79_{timestamp}.csv"

xlsx_path = f"/content/wadq_phase79_{timestamp}.xlsx"

wadq_phase79_df.to_csv(
    csv_path,
    index=False,
    encoding="utf-8-sig"
)

with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:

    wadq_phase79_df.to_excel(
        writer,
        sheet_name="التقرير الكامل",
        index=False
    )

    wadq_phase79_opportunities_df.to_excel(
        writer,
        sheet_name="الفرص",
        index=False
    )

print("\nتم إنشاء المرحلة 79")

print("ملف CSV:", csv_path)

print("ملف Excel:", xlsx_path)

print("\nعدد الأصول:", len(wadq_phase79_df))

print("\nعدد إشارات الشراء:",
      (wadq_phase79_df["signal"] == "شراء محتمل").sum())

print("\nعدد إشارات البيع الفني:",
      (wadq_phase79_df["signal"] == "إشارة بيع فني").sum())

print("\n⚠️ هذه توصيات فنية احتمالية وليست ضمانًا للربح.")
print("⚠️ لا يتم تنفيذ أوامر تداول حقيقية.")

============================================================
🌧️ الودق AI — المرحلة 79
محرك التوصيات وإدارة المخاطر
============================================================
تحليل: NVDA
تحليل: TSLA
تحليل: AAPL
تحليل: MSFT
تحليل: AMZN
تحليل: GOOGL
تحليل: META
تحليل: QQQ
تحليل: SPY
تحليل: 2222.SR
تحليل: 1180.SR
تحليل: 2010.SR
تحليل: GC=F
تحليل: SI=F
تحليل: CL=F
تحليل: BZ=F
تحليل: BTC-USD

التقرير الكامل:

,ticker,status,date,price,change_pct,RSI14,SMA20,SMA50,MACD,MACD_SIGNAL,ATR14,signal,reason,entry_reference,stop_reference,target1_reference,target2_reference,risk_budget_SAR,theoretical_quantity,theoretical_value
0,NVDA,سليم,2026-10-16,214.1300,-1.43,37.56,228.1770,222.9632,-0.1479,2.2177,5.9647,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
1,TSLA,سليم,2026-10-16,354.7200,-2.13,42.20,370.3335,359.4622,1.4147,3.5055,11.8480,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
2,AAPL,سليم,2026-10-16,343.4600,0.43,62.08,337.4240,325.6940,4.1388,3.9449,6.6977,انتظار,رأس المال غير كافٍ للمخاطرة المحددة,NaN,NaN,NaN,NaN,1.0,0,0
3,MSFT,سليم,2026-10-16,529.0500,-1.93,57.36,520.2205,505.3655,11.2531,10.9802,12.0071,انتظار,رأس المال غير كافٍ للمخاطرة المحددة,NaN,NaN,NaN,NaN,1.0,0,0
4,AMZN,سليم,2026-10-16,250.0000,-1.87,44.99,253.2260,257.0760,0.1857,0.0566,5.9497,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
5,GOOGL,سليم,2026-10-16,340.5900,-2.47,44.47,346.4140,344.4919,1.0220,1.1959,8.9050,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
6,META,سليم,2026-10-16,709.3300,-3.72,50.26,735.7750,654.9556,19.4757,25.5640,25.2982,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
7,QQQ,سليم,2026-10-16,709.8000,-2.50,35.14,742.5190,726.3260,1.6592,6.3254,10.5566,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
8,SPY,سليم,2026-10-16,763.2500,-1.11,44.19,771.1840,767.4000,2.0243,2.8850,6.9938,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
9,2222.SR,سليم,2026-10-15,25.2800,-0.39,38.45,25.5930,25.9011,-0.0965,-0.0989,0.2719,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
10,1180.SR,سليم,2026-10-15,37.1000,0.43,32.03,39.0960,40.7772,-1.0293,-0.8055,0.7559,إشارة بيع فني,اتجاه هابط وزخم سلبي,NaN,NaN,NaN,NaN,1.0,0,0
11,2010.SR,سليم,2026-10-15,44.5600,-0.31,29.02,46.5410,48.3770,-0.9887,-0.8653,0.7440,إشارة بيع فني,اتجاه هابط وزخم سلبي,NaN,NaN,NaN,NaN,1.0,0,0
12,GC=F,سليم,2026-10-16,4181.1001,0.26,43.49,4214.1100,4374.4140,-55.7101,-58.8535,83.7526,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0
13,SI=F,سليم,2026-10-16,56.9950,0.28,36.20,60.8441,63.9021,-1.8678,-1.4698,1.3931,إشارة بيع فني,اتجاه هابط وزخم سلبي,NaN,NaN,NaN,NaN,1.0,0,0
14,CL=F,سليم,2026-10-16,101.4100,3.51,66.43,92.9385,90.9826,1.2947,0.5660,4.1875,انتظار,رأس المال غير كافٍ للمخاطرة المحددة,NaN,NaN,NaN,NaN,1.0,0,0
15,BZ=F,سليم,2026-10-16,109.8600,3.72,65.87,103.6915,98.4150,2.2057,1.9972,4.1150,انتظار,رأس المال غير كافٍ للمخاطرة المحددة,NaN,NaN,NaN,NaN,1.0,0,0
16,BTC-USD,سليم,2026-10-17,81450.7109,-0.06,46.31,83411.0340,81324.2677,86.9773,609.3769,2090.7385,انتظار,شروط التداول غير مكتملة,NaN,NaN,NaN,NaN,1.0,0,0

الفرص المحتملة:

,ticker,status,date,price,change_pct,RSI14,SMA20,SMA50,MACD,MACD_SIGNAL,ATR14,signal,reason,entry_reference,stop_reference,target1_reference,target2_reference,risk_budget_SAR,theoretical_quantity,theoretical_value
10,1180.SR,سليم,2026-10-15,37.100,0.43,32.03,39.0960,40.7772,-1.0293,-0.8055,0.7559,إشارة بيع فني,اتجاه هابط وزخم سلبي,NaN,NaN,NaN,NaN,1.0,0,0
11,2010.SR,سليم,2026-10-15,44.560,-0.31,29.02,46.5410,48.3770,-0.9887,-0.8653,0.7440,إشارة بيع فني,اتجاه هابط وزخم سلبي,NaN,NaN,NaN,NaN,1.0,0,0
13,SI=F,سليم,2026-10-16,56.995,0.28,36.20,60.8441,63.9021,-1.8678,-1.4698,1.3931,إشارة بيع فني,اتجاه هابط وزخم سلبي,NaN,NaN,NaN,NaN,1.0,0,0

تم إنشاء المرحلة 79
ملف CSV: /content/wadq_phase79_20261017_144857.csv
ملف Excel: /content/wadq_phase79_20261017_144857.xlsx

عدد الأصول: 17

عدد إشارات الشراء: 0

عدد إشارات البيع الفني: 3

⚠️ هذه توصيات فنية احتمالية وليست ضمانًا للربح.
⚠️ لا يتم تنفيذ أوامر تداول حقيقية.

In [19]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 80
# محرك التوصيات الذكية + إدارة رأس المال + حماية المخاطر
# رأس المال: 10,000 ريال
# يعتمد على نتائج المرحلة 79 دون إعادة تشغيلها
# =====================================================================

import numpy as np
import pandas as pd
from datetime import datetime
from IPython.display import display

# ---------------------------------------------------------------------
# 1) إعدادات رأس المال والمخاطر
# ---------------------------------------------------------------------

WADQ_CAPITAL = 10000.0       # رأس المال الكلي بالريال

RISK_PER_TRADE = 0.005        # 0.5% مخاطرة لكل صفقة
MAX_TOTAL_RISK = 0.02          # 2% أقصى مخاطرة للصفقات الجديدة

RISK_AMOUNT = WADQ_CAPITAL * RISK_PER_TRADE
MAX_RISK_AMOUNT = WADQ_CAPITAL * MAX_TOTAL_RISK

MAX_POSITION_PCT = 0.20         # أقصى تخصيص 20% من رأس المال للأصل الواحد
MAX_POSITION_VALUE = WADQ_CAPITAL * MAX_POSITION_PCT

# وقف الخسارة = 2 × ATR
ATR_MULTIPLIER = 2.0

# الأهداف
TARGET1_R = 2.0
TARGET2_R = 3.0

# ---------------------------------------------------------------------
# 2) التأكد من وجود جدول المرحلة 79
# ---------------------------------------------------------------------

if "wadq_phase79_df" not in globals():

    raise ValueError(
        "لم يتم العثور على wadq_phase79_df. "
        "شغّلي خلية المرحلة 79 أولاً، ثم شغّلي المرحلة 80."
    )

df = wadq_phase79_df.copy()

required_columns = [
    "ticker",
    "status",
    "price",
    "RSI14",
    "SMA20",
    "SMA50",
    "MACD",
    "MACD_SIGNAL",
    "ATR14"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"أعمدة ناقصة في المرحلة 79: {missing_columns}"
    )

# ---------------------------------------------------------------------
# 3) تنظيف البيانات
# ---------------------------------------------------------------------

numeric_columns = [
    "price",
    "RSI14",
    "SMA20",
    "SMA50",
    "MACD",
    "MACD_SIGNAL",
    "ATR14"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.drop_duplicates(subset=["ticker"], keep="last")

df = df.replace([np.inf, -np.inf], np.nan)

# ---------------------------------------------------------------------
# 4) تصنيف نوع الأصل
# ---------------------------------------------------------------------

def classify_asset(ticker):

    ticker = str(ticker)

    if ticker == "BTC-USD":
        return "crypto"

    if ticker.endswith(".SR"):
        return "saudi_stock"

    if ticker in ["GC=F", "SI=F", "CL=F", "BZ=F"]:
        return "future"

    if ticker in ["NVDA", "TSLA", "AAPL", "MSFT",
                  "AMZN", "GOOGL", "META", "QQQ", "SPY"]:
        return "us_stock"

    return "unknown"


df["asset_type"] = df["ticker"].apply(classify_asset)

# ---------------------------------------------------------------------
# 5) إنشاء شروط الاتجاه والزخم
# ---------------------------------------------------------------------

# اتجاه صاعد
df["trend_up"] = (
    (df["price"] > df["SMA20"]) &
    (df["SMA20"] > df["SMA50"])
)

# اتجاه هابط
df["trend_down"] = (
    (df["price"] < df["SMA20"]) &
    (df["SMA20"] < df["SMA50"])
)

# زخم إيجابي
df["momentum_up"] = (
    (df["MACD"] > df["MACD_SIGNAL"]) &
    (df["RSI14"] >= 50) &
    (df["RSI14"] <= 68)
)

# زخم سلبي
df["momentum_down"] = (
    (df["MACD"] < df["MACD_SIGNAL"]) &
    (df["RSI14"] < 50)
)

# ---------------------------------------------------------------------
# 6) فحص جودة البيانات
# ---------------------------------------------------------------------

df["data_quality_ok"] = (
    df["status"].astype(str).str.contains("سليم", na=False) &
    df["price"].notna() &
    df["RSI14"].between(0, 100) &
    df["SMA20"].notna() &
    df["SMA50"].notna() &
    df["MACD"].notna() &
    df["MACD_SIGNAL"].notna() &
    df["ATR14"].notna() &
    (df["price"] > 0) &
    (df["ATR14"] > 0)
)

# ---------------------------------------------------------------------
# 7) حساب إشارات الشراء والبيع
# ---------------------------------------------------------------------

df["buy_candidate"] = (
    df["data_quality_ok"] &
    df["trend_up"] &
    df["momentum_up"]
)

df["sell_candidate"] = (
    df["data_quality_ok"] &
    df["trend_down"] &
    df["momentum_down"]
)

# ---------------------------------------------------------------------
# 8) تحديد الإشارة النهائية
# ---------------------------------------------------------------------

def final_signal(row):

    if not row["data_quality_ok"]:
        return "انتظار - بيانات غير كافية"

    if row["buy_candidate"]:
        return "مرشح شراء للاختبار"

    if row["sell_candidate"]:
        return "إشارة ضعف فني"

    return "انتظار"


df["signal_phase80"] = df.apply(final_signal, axis=1)

# ---------------------------------------------------------------------
# 9) حساب وقف الخسارة والأهداف للمرشحين
# ---------------------------------------------------------------------

df["entry_reference"] = np.nan
df["stop_reference"] = np.nan
df["target1_reference"] = np.nan
df["target2_reference"] = np.nan
df["risk_per_unit"] = np.nan

# الدخول المرجعي = السعر الحالي
df.loc[df["buy_candidate"], "entry_reference"] = (
    df.loc[df["buy_candidate"], "price"]
)

# وقف الخسارة = السعر - ضعفي ATR
df.loc[df["buy_candidate"], "stop_reference"] = (
    df.loc[df["buy_candidate"], "price"] -
    ATR_MULTIPLIER * df.loc[df["buy_candidate"], "ATR14"]
)

# المخاطرة لكل وحدة
df.loc[df["buy_candidate"], "risk_per_unit"] = (
    df.loc[df["buy_candidate"], "entry_reference"] -
    df.loc[df["buy_candidate"], "stop_reference"]
)

# الهدف الأول = 2R
df.loc[df["buy_candidate"], "target1_reference"] = (
    df.loc[df["buy_candidate"], "entry_reference"] +
    TARGET1_R * df.loc[df["buy_candidate"], "risk_per_unit"]
)

# الهدف الثاني = 3R
df.loc[df["buy_candidate"], "target2_reference"] = (
    df.loc[df["buy_candidate"], "entry_reference"] +
    TARGET2_R * df.loc[df["buy_candidate"], "risk_per_unit"]
)

# ---------------------------------------------------------------------
# 10) حساب حجم الصفقة وفق رأس المال والمخاطرة
# ---------------------------------------------------------------------

df["risk_budget_SAR"] = 0.0
df["theoretical_quantity"] = 0.0
df["theoretical_value"] = 0.0

# تخصيص أولي للمخاطر
df.loc[df["buy_candidate"], "risk_budget_SAR"] = RISK_AMOUNT

# الأصول التي لا يمكن تحديد حجم عقدها من السعر وATR وحدهما
# مثل عقود الذهب والفضة والنفط الآجلة
df.loc[df["asset_type"] == "future", "signal_phase80"] = (
    "انتظار - يلزم تحديد مواصفات العقد"
)

# ---------------------------------------------------------------------
# 11) منع تخصيص ميزانية المخاطر للأصول غير المناسبة
# ---------------------------------------------------------------------

eligible = df[
    df["buy_candidate"] &
    (df["asset_type"] != "future")
].copy()

# ---------------------------------------------------------------------
# 12) ترتيب المرشحين حسب جودة الإشارة
# ---------------------------------------------------------------------

eligible["quality_score"] = 0

eligible["quality_score"] += (
    eligible["trend_up"].astype(int) * 2
)

eligible["quality_score"] += (
    eligible["momentum_up"].astype(int) * 2
)

eligible["quality_score"] += (
    (eligible["RSI14"] >= 52) &
    (eligible["RSI14"] <= 65)
).astype(int)

eligible = eligible.sort_values(
    "quality_score",
    ascending=False
)

# ---------------------------------------------------------------------
# 13) توزيع ميزانية المخاطر
# الحد الإجمالي للصفقات الجديدة = 200 ريال
# ---------------------------------------------------------------------

remaining_risk = MAX_RISK_AMOUNT

for idx, row in eligible.iterrows():

    price = row["price"]
    risk_per_unit = row["risk_per_unit"]

    if pd.isna(price) or pd.isna(risk_per_unit):
        continue

    if price <= 0 or risk_per_unit <= 0:
        continue

    # ميزانية المخاطرة المتاحة
    allocated_risk = min(
        RISK_AMOUNT,
        remaining_risk
    )

    if allocated_risk <= 0:
        df.loc[idx, "signal_phase80"] = (
            "انتظار - استنفدت ميزانية المخاطر"
        )
        continue

    # الكمية حسب المخاطرة
    quantity_by_risk = allocated_risk / risk_per_unit

    # الحد الأقصى لقيمة المركز
    quantity_by_capital = MAX_POSITION_VALUE / price

    # الأسهم والصنادييق: كمية صحيحة
    # البيتكوين: كمية كسرية
    if row["asset_type"] == "crypto":

        quantity = min(
            quantity_by_risk,
            quantity_by_capital
        )

    else:

        quantity = int(
            min(
                quantity_by_risk,
                quantity_by_capital
            )
        )

    position_value = quantity * price

    actual_risk = quantity * risk_per_unit

    if quantity <= 0:

        df.loc[idx, "signal_phase80"] = (
            "انتظار - رأس المال غير كافٍ"
        )

        continue

    df.loc[idx, "risk_budget_SAR"] = actual_risk

    df.loc[idx, "theoretical_quantity"] = quantity

    df.loc[idx, "theoretical_value"] = position_value

    remaining_risk -= actual_risk

    df.loc[idx, "signal_phase80"] = (
        "مرشح شراء - يحتاج اختبارًا وتأكيدًا"
    )

# ---------------------------------------------------------------------
# 14) إنشاء التقرير النهائي
# ---------------------------------------------------------------------

wadq_phase80_df = df.copy()

wadq_phase80_opportunities_df = wadq_phase80_df[
    wadq_phase80_df["signal_phase80"].str.contains(
        "مرشح شراء|إشارة ضعف",
        na=False
    )
].copy()

# ---------------------------------------------------------------------
# 15) عرض النتائج
# ---------------------------------------------------------------------

report_columns = [
    "ticker",
    "asset_type",
    "price",
    "RSI14",
    "SMA20",
    "SMA50",
    "MACD",
    "MACD_SIGNAL",
    "ATR14",
    "signal_phase80",
    "entry_reference",
    "stop_reference",
    "target1_reference",
    "target2_reference",
    "risk_budget_SAR",
    "theoretical_quantity",
    "theoretical_value"
]

report_columns = [
    col for col in report_columns
    if col in wadq_phase80_df.columns
]

print("=" * 75)
print("🌧️ الودق AI — المرحلة 80")
print("محرك التوصيات الذكية وإدارة رأس المال")
print("=" * 75)

print(f"رأس المال: {WADQ_CAPITAL:,.2f} ريال")
print(f"المخاطرة لكل صفقة: {RISK_AMOUNT:,.2f} ريال")
print(f"الحد الأقصى لمخاطر الصفقات الجديدة: {MAX_RISK_AMOUNT:,.2f} ريال")

print("\nالتقرير الكامل:")

display(
    wadq_phase80_df[report_columns]
)

print("\nالفرص المحتملة:")

display(
    wadq_phase80_opportunities_df[report_columns]
)

print("\nعدد الأصول:", len(wadq_phase80_df))

print(
    "عدد مرشحي الشراء:",
    (wadq_phase80_df["signal_phase80"].str.contains(
        "مرشح شراء", na=False
    )).sum()
)

print(
    "عدد إشارات الضعف الفني:",
    (wadq_phase80_df["signal_phase80"].str.contains(
        "إشارة ضعف", na=False
    )).sum()
)

# ---------------------------------------------------------------------
# 16) حفظ الملفات
# ---------------------------------------------------------------------

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

csv_path = f"/content/wadq_phase80_{timestamp}.csv"

excel_path = f"/content/wadq_phase80_{timestamp}.xlsx"

wadq_phase80_df.to_csv(
    csv_path,
    index=False,
    encoding="utf-8-sig"
)

wadq_phase80_df.to_excel(
    excel_path,
    index=False
)

print("\nتم إنشاء المرحلة 80")
print("ملف CSV:", csv_path)
print("ملف Excel:", excel_path)

print("\n⚠️ التوصيات احتمالية وليست ضمانًا للربح.")
print("⚠️ لا يتم تنفيذ أوامر تداول حقيقية.")
print("⚠️ يجب اختبار النظام تاريخيًا قبل استخدام رأس المال الحقيقي.")

===========================================================================
🌧️ الودق AI — المرحلة 80
محرك التوصيات الذكية وإدارة رأس المال
===========================================================================
رأس المال: 10,000.00 ريال
المخاطرة لكل صفقة: 50.00 ريال
الحد الأقصى لمخاطر الصفقات الجديدة: 200.00 ريال

التقرير الكامل:

,ticker,asset_type,price,RSI14,SMA20,SMA50,MACD,MACD_SIGNAL,ATR14,signal_phase80,entry_reference,stop_reference,target1_reference,target2_reference,risk_budget_SAR,theoretical_quantity,theoretical_value
0,NVDA,us_stock,214.1300,37.56,228.1770,222.9632,-0.1479,2.2177,5.9647,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
1,TSLA,us_stock,354.7200,42.20,370.3335,359.4622,1.4147,3.5055,11.8480,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
2,AAPL,us_stock,343.4600,62.08,337.4240,325.6940,4.1388,3.9449,6.6977,مرشح شراء - يحتاج اختبارًا وتأكيدًا,343.46,330.0646,370.2508,383.6462,40.1862,3.0,1030.38
3,MSFT,us_stock,529.0500,57.36,520.2205,505.3655,11.2531,10.9802,12.0071,مرشح شراء - يحتاج اختبارًا وتأكيدًا,529.05,505.0358,577.0784,601.0926,48.0284,2.0,1058.10
4,AMZN,us_stock,250.0000,44.99,253.2260,257.0760,0.1857,0.0566,5.9497,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
5,GOOGL,us_stock,340.5900,44.47,346.4140,344.4919,1.0220,1.1959,8.9050,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
6,META,us_stock,709.3300,50.26,735.7750,654.9556,19.4757,25.5640,25.2982,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
7,QQQ,us_stock,709.8000,35.14,742.5190,726.3260,1.6592,6.3254,10.5566,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
8,SPY,us_stock,763.2500,44.19,771.1840,767.4000,2.0243,2.8850,6.9938,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
9,2222.SR,saudi_stock,25.2800,38.45,25.5930,25.9011,-0.0965,-0.0989,0.2719,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
10,1180.SR,saudi_stock,37.1000,32.03,39.0960,40.7772,-1.0293,-0.8055,0.7559,إشارة ضعف فني,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
11,2010.SR,saudi_stock,44.5600,29.02,46.5410,48.3770,-0.9887,-0.8653,0.7440,إشارة ضعف فني,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
12,GC=F,future,4181.1001,43.49,4214.1100,4374.4140,-55.7101,-58.8535,83.7526,انتظار - يلزم تحديد مواصفات العقد,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
13,SI=F,future,56.9950,36.20,60.8441,63.9021,-1.8678,-1.4698,1.3931,انتظار - يلزم تحديد مواصفات العقد,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
14,CL=F,future,101.4100,66.43,92.9385,90.9826,1.2947,0.5660,4.1875,انتظار - يلزم تحديد مواصفات العقد,101.41,93.0350,118.1600,126.5350,50.0000,0.0,0.00
15,BZ=F,future,109.8600,65.87,103.6915,98.4150,2.2057,1.9972,4.1150,انتظار - يلزم تحديد مواصفات العقد,109.86,101.6300,126.3200,134.5500,50.0000,0.0,0.00
16,BTC-USD,crypto,81450.7109,46.31,83411.0340,81324.2677,86.9773,609.3769,2090.7385,انتظار,NaN,NaN,NaN,NaN,0.0000,0.0,0.00

الفرص المحتملة:

,ticker,asset_type,price,RSI14,SMA20,SMA50,MACD,MACD_SIGNAL,ATR14,signal_phase80,entry_reference,stop_reference,target1_reference,target2_reference,risk_budget_SAR,theoretical_quantity,theoretical_value
2,AAPL,us_stock,343.46,62.08,337.4240,325.6940,4.1388,3.9449,6.6977,مرشح شراء - يحتاج اختبارًا وتأكيدًا,343.46,330.0646,370.2508,383.6462,40.1862,3.0,1030.38
3,MSFT,us_stock,529.05,57.36,520.2205,505.3655,11.2531,10.9802,12.0071,مرشح شراء - يحتاج اختبارًا وتأكيدًا,529.05,505.0358,577.0784,601.0926,48.0284,2.0,1058.10
10,1180.SR,saudi_stock,37.10,32.03,39.0960,40.7772,-1.0293,-0.8055,0.7559,إشارة ضعف فني,NaN,NaN,NaN,NaN,0.0000,0.0,0.00
11,2010.SR,saudi_stock,44.56,29.02,46.5410,48.3770,-0.9887,-0.8653,0.7440,إشارة ضعف فني,NaN,NaN,NaN,NaN,0.0000,0.0,0.00

عدد الأصول: 17
عدد مرشحي الشراء: 2
عدد إشارات الضعف الفني: 2

تم إنشاء المرحلة 80
ملف CSV: /content/wadq_phase80_20261017_150458.csv
ملف Excel: /content/wadq_phase80_20261017_150458.xlsx

⚠️ التوصيات احتمالية وليست ضمانًا للربح.
⚠️ لا يتم تنفيذ أوامر تداول حقيقية.
⚠️ يجب اختبار النظام تاريخيًا قبل استخدام رأس المال الحقيقي.

In [20]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 81
# تصحيح حساب العملات + حجم الصفقة + ميزانية المخاطر
# يعتمد على نتائج المرحلة 80
# =====================================================================

import numpy as np
import pandas as pd
from datetime import datetime
from IPython.display import display

# ---------------------------------------------------------
# 1) إعداد رأس المال
# ---------------------------------------------------------

CAPITAL_SAR = 10000.0

RISK_PER_TRADE_SAR = 50.0
MAX_TOTAL_RISK_SAR = 200.0

MAX_POSITION_PCT = 0.20
MAX_POSITION_SAR = CAPITAL_SAR * MAX_POSITION_PCT

# الدولار الأمريكي مقابل الريال السعودي
USD_TO_SAR = 3.75

# عمولة وانزلاق تقديري لكل جانب من الصفقة
# عدلي القيم حسب رسوم وسيطك الفعلية
COST_RATE_PER_SIDE = 0.001

# لا يسمح بالأسهم الكسرية افتراضيًا
ALLOW_FRACTIONAL_SHARES = False

# ---------------------------------------------------------
# 2) التأكد من جدول المرحلة 80
# ---------------------------------------------------------

if "wadq_phase80_df" not in globals():
    raise ValueError(
        "لم يتم العثور على جدول المرحلة 80. "
        "شغّلي المرحلة 80 أولًا."
    )

df81 = wadq_phase80_df.copy()

# ---------------------------------------------------------
# 3) تحديد عملة الأصل
# ---------------------------------------------------------

def get_currency(ticker, asset_type):

    ticker = str(ticker)

    if ticker.endswith(".SR"):
        return "SAR"

    if asset_type in ["us_stock", "crypto"]:
        return "USD"

    return "UNKNOWN"


df81["currency"] = df81.apply(
    lambda row: get_currency(
        row["ticker"],
        row["asset_type"]
    ),
    axis=1
)

# ---------------------------------------------------------
# 4) تحويل الأسعار إلى الريال السعودي
# ---------------------------------------------------------

def convert_to_sar(value, currency):

    if pd.isna(value):
        return np.nan

    if currency == "SAR":
        return float(value)

    if currency == "USD":
        return float(value) * USD_TO_SAR

    return np.nan


df81["price_SAR"] = df81.apply(
    lambda row: convert_to_sar(
        row["price"],
        row["currency"]
    ),
    axis=1
)

# ---------------------------------------------------------
# 5) إعادة حساب وقف الخسارة والمخاطرة
# ---------------------------------------------------------

df81["entry_SAR"] = np.nan
df81["stop_SAR"] = np.nan
df81["target1_SAR"] = np.nan
df81["target2_SAR"] = np.nan

df81["risk_per_unit_SAR"] = np.nan
df81["risk_budget_SAR_corrected"] = 0.0

df81["quantity_corrected"] = 0.0
df81["position_value_SAR"] = 0.0

df81["signal_phase81"] = "انتظار"

# ---------------------------------------------------------
# 6) تحديد المرشحين
# ---------------------------------------------------------

if "buy_candidate" not in df81.columns:

    raise ValueError(
        "لم يتم العثور على عمود buy_candidate."
    )

# نسمح فقط بالأصول ذات مواصفات واضحة
eligible_types = ["us_stock", "saudi_stock", "crypto"]

buy_candidates = df81[
    df81["buy_candidate"] &
    df81["asset_type"].isin(eligible_types)
].copy()

# ---------------------------------------------------------
# 7) إعداد حساب المخاطرة لكل مرشح
# ---------------------------------------------------------

remaining_risk_SAR = MAX_TOTAL_RISK_SAR

# ترتيب المرشحين حسب جودة الإشارة
if "quality_score" in buy_candidates.columns:

    buy_candidates = buy_candidates.sort_values(
        "quality_score",
        ascending=False
    )

for idx, row in buy_candidates.iterrows():

    ticker = row["ticker"]
    asset_type = row["asset_type"]
    price = row["price"]
    atr = row["ATR14"]
    currency = row["currency"]

    # التأكد من البيانات
    if (
        pd.isna(price) or
        pd.isna(atr) or
        price <= 0 or
        atr <= 0
    ):

        df81.loc[idx, "signal_phase81"] = (
            "انتظار - بيانات غير صالحة"
        )

        continue

    # -----------------------------------------------------
    # تحويل ATR إلى الريال
    # -----------------------------------------------------

    atr_SAR = convert_to_sar(
        atr,
        currency
    )

    price_SAR = row["price_SAR"]

    if pd.isna(atr_SAR) or pd.isna(price_SAR):

        df81.loc[idx, "signal_phase81"] = (
            "انتظار - تعذر تحويل العملة"
        )

        continue

    # -----------------------------------------------------
    # وقف الخسارة
    # -----------------------------------------------------

    entry_SAR = price_SAR

    stop_SAR = entry_SAR - (2.0 * atr_SAR)

    risk_per_unit_SAR = entry_SAR - stop_SAR

    # حساب الأهداف
    target1_SAR = entry_SAR + (
        2.0 * risk_per_unit_SAR
    )

    target2_SAR = entry_SAR + (
        3.0 * risk_per_unit_SAR
    )

    # -----------------------------------------------------
    # ميزانية المخاطرة
    # -----------------------------------------------------

    allocated_risk_SAR = min(
        RISK_PER_TRADE_SAR,
        remaining_risk_SAR
    )

    if allocated_risk_SAR <= 0:

        df81.loc[idx, "signal_phase81"] = (
            "انتظار - انتهت ميزانية المخاطر"
        )

        continue

    # -----------------------------------------------------
    # الكمية حسب المخاطرة
    # -----------------------------------------------------

    quantity_by_risk = (
        allocated_risk_SAR / risk_per_unit_SAR
    )

    # -----------------------------------------------------
    # الحد الأقصى لقيمة المركز
    # -----------------------------------------------------

    quantity_by_capital = (
        MAX_POSITION_SAR / price_SAR
    )

    # -----------------------------------------------------
    # تحديد الكمية
    # -----------------------------------------------------

    quantity = min(
        quantity_by_risk,
        quantity_by_capital
    )

    # الأسهم السعودية والأمريكية:
    # لا يسمح بالكسور افتراضيًا
    if asset_type in ["us_stock", "saudi_stock"]:

        if not ALLOW_FRACTIONAL_SHARES:

            quantity = int(np.floor(quantity))

    # العملات الرقمية تسمح بكمية كسرية
    if asset_type == "crypto":

        quantity = float(quantity)

    if quantity <= 0:

        df81.loc[idx, "signal_phase81"] = (
            "انتظار - المخاطرة لا تسمح بوحدة واحدة"
        )

        continue

    # -----------------------------------------------------
    # حساب القيمة الفعلية والمخاطرة
    # -----------------------------------------------------

    position_value_SAR = quantity * price_SAR

    # المخاطرة السعرية حتى وقف الخسارة
    raw_risk_SAR = (
        quantity * risk_per_unit_SAR
    )

    # تكلفة الدخول والخروج تقديريًا
    transaction_cost_SAR = (
        position_value_SAR *
        COST_RATE_PER_SIDE *
        2
    )

    # إجمالي الخسارة المقدرة
    total_risk_SAR = (
        raw_risk_SAR +
        transaction_cost_SAR
    )

    # لا نقبل الصفقة إذا تجاوزت ميزانية المخاطر
    if total_risk_SAR > allocated_risk_SAR:

        df81.loc[idx, "signal_phase81"] = (
            "انتظار - المخاطرة تتجاوز الميزانية"
        )

        continue

    if total_risk_SAR > remaining_risk_SAR:

        df81.loc[idx, "signal_phase81"] = (
            "انتظار - تجاوز حد المخاطر الإجمالي"
        )

        continue

    # -----------------------------------------------------
    # حفظ النتائج
    # -----------------------------------------------------

    df81.loc[idx, "entry_SAR"] = entry_SAR
    df81.loc[idx, "stop_SAR"] = stop_SAR

    df81.loc[idx, "target1_SAR"] = target1_SAR
    df81.loc[idx, "target2_SAR"] = target2_SAR

    df81.loc[idx, "risk_per_unit_SAR"] = (
        risk_per_unit_SAR
    )

    df81.loc[idx, "risk_budget_SAR_corrected"] = (
        total_risk_SAR
    )

    df81.loc[idx, "quantity_corrected"] = quantity

    df81.loc[idx, "position_value_SAR"] = (
        position_value_SAR
    )

    df81.loc[idx, "signal_phase81"] = (
        "مرشح شراء - حساب المخاطر مصحح"
    )

    # خصم ميزانية المخاطر المستخدمة
    remaining_risk_SAR -= total_risk_SAR

# ---------------------------------------------------------
# 8) منع توصيات شراء للعقود الآجلة
# ---------------------------------------------------------

futures_mask = df81["asset_type"] == "future"

df81.loc[
    futures_mask,
    "signal_phase81"
] = "انتظار - يلزم تحديد مواصفات العقد والهامش"

# ---------------------------------------------------------
# 9) إنشاء التقرير النهائي
# ---------------------------------------------------------

wadq_phase81_df = df81.copy()

report_columns = [
    "ticker",
    "currency",
    "price",
    "price_SAR",
    "signal_phase81",
    "entry_SAR",
    "stop_SAR",
    "target1_SAR",
    "target2_SAR",
    "risk_budget_SAR_corrected",
    "quantity_corrected",
    "position_value_SAR"
]

report_columns = [
    col for col in report_columns
    if col in wadq_phase81_df.columns
]

print("=" * 75)
print("🌧️ الودق AI — المرحلة 81")
print("تصحيح العملات والمخاطر")
print("=" * 75)

print(f"رأس المال: {CAPITAL_SAR:,.2f} ريال")
print(f"المخاطرة لكل صفقة: {RISK_PER_TRADE_SAR:,.2f} ريال")
print(f"الحد الأقصى للمخاطر: {MAX_TOTAL_RISK_SAR:,.2f} ريال")

display(
    wadq_phase81_df[report_columns]
)

print("\nإجمالي المخاطر المحسوبة:")

print(
    wadq_phase81_df[
        "risk_budget_SAR_corrected"
    ].sum()
)

print("\nإجمالي قيمة المراكز:")

print(
    wadq_phase81_df[
        "position_value_SAR"
    ].sum()
)

# ---------------------------------------------------------
# 10) حفظ النتائج
# ---------------------------------------------------------

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

csv_path = f"/content/wadq_phase81_{timestamp}.csv"

excel_path = f"/content/wadq_phase81_{timestamp}.xlsx"

wadq_phase81_df.to_csv(
    csv_path,
    index=False,
    encoding="utf-8-sig"
)

wadq_phase81_df.to_excel(
    excel_path,
    index=False
)

print("\nتم إنشاء المرحلة 81")
print("ملف CSV:", csv_path)
print("ملف Excel:", excel_path)

print("\n⚠️ هذه حسابات نظرية وليست أوامر تداول.")
print("⚠️ يجب اختبار الاستراتيجية تاريخيًا قبل التداول الحقيقي.")

===========================================================================
🌧️ الودق AI — المرحلة 81
تصحيح العملات والمخاطر
===========================================================================
رأس المال: 10,000.00 ريال
المخاطرة لكل صفقة: 50.00 ريال
الحد الأقصى للمخاطر: 200.00 ريال

,ticker,currency,price,price_SAR,signal_phase81,entry_SAR,stop_SAR,target1_SAR,target2_SAR,risk_budget_SAR_corrected,quantity_corrected,position_value_SAR
0,NVDA,USD,214.1300,802.987500,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1,TSLA,USD,354.7200,1330.200000,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,AAPL,USD,343.4600,1287.975000,انتظار - المخاطرة لا تسمح بوحدة واحدة,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,MSFT,USD,529.0500,1983.937500,انتظار - المخاطرة لا تسمح بوحدة واحدة,NaN,NaN,NaN,NaN,0.0,0.0,0.0
4,AMZN,USD,250.0000,937.500000,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
5,GOOGL,USD,340.5900,1277.212500,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
6,META,USD,709.3300,2659.987500,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
7,QQQ,USD,709.8000,2661.750000,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
8,SPY,USD,763.2500,2862.187500,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
9,2222.SR,SAR,25.2800,25.280000,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
10,1180.SR,SAR,37.1000,37.100000,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
11,2010.SR,SAR,44.5600,44.560000,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0
12,GC=F,UNKNOWN,4181.1001,NaN,انتظار - يلزم تحديد مواصفات العقد والهامش,NaN,NaN,NaN,NaN,0.0,0.0,0.0
13,SI=F,UNKNOWN,56.9950,NaN,انتظار - يلزم تحديد مواصفات العقد والهامش,NaN,NaN,NaN,NaN,0.0,0.0,0.0
14,CL=F,UNKNOWN,101.4100,NaN,انتظار - يلزم تحديد مواصفات العقد والهامش,NaN,NaN,NaN,NaN,0.0,0.0,0.0
15,BZ=F,UNKNOWN,109.8600,NaN,انتظار - يلزم تحديد مواصفات العقد والهامش,NaN,NaN,NaN,NaN,0.0,0.0,0.0
16,BTC-USD,USD,81450.7109,305440.165875,انتظار,NaN,NaN,NaN,NaN,0.0,0.0,0.0

إجمالي المخاطر المحسوبة:
0.0

إجمالي قيمة المراكز:
0.0

تم إنشاء المرحلة 81
ملف CSV: /content/wadq_phase81_20261017_151558.csv
ملف Excel: /content/wadq_phase81_20261017_151558.xlsx

⚠️ هذه حسابات نظرية وليست أوامر تداول.
⚠️ يجب اختبار الاستراتيجية تاريخيًا قبل التداول الحقيقي.

In [21]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 82
# تدقيق التوصيات النهائية وأسباب الانتظار
# يعتمد على ملف المرحلة 81
# رأس المال: 10,000 ريال
# المخاطرة لكل صفقة: 50 ريال
# الحد الأقصى للمخاطر: 200 ريال
# =====================================================================

import os
import glob
import numpy as np
import pandas as pd
from datetime import datetime
from IPython.display import display

print("=" * 75)
print("🌧️ الودق AI — المرحلة 82")
print("تدقيق التوصيات وأسباب الانتظار")
print("=" * 75)

# ---------------------------------------------------------------------
# 1) إعداد ميزانية المخاطر
# ---------------------------------------------------------------------

WADQ_CAPITAL_82 = 10000.0
WADQ_RISK_PER_TRADE_82 = 50.0
WADQ_MAX_TOTAL_RISK_82 = 200.0

# ---------------------------------------------------------------------
# 2) البحث عن ملف المرحلة 81
# ---------------------------------------------------------------------

phase81_files = glob.glob("/content/wadq_phase81_*.csv")

if not phase81_files:
    raise FileNotFoundError(
        "لم يتم العثور على ملف المرحلة 81 في /content. "
        "تأكدي من وجود ملف wadq_phase81_*.csv"
    )

# اختيار أحدث ملف
phase81_file = max(phase81_files, key=os.path.getmtime)

print(f"\n📂 ملف المصدر: {phase81_file}")

# قراءة الجدول
wadq_phase81_audit_source = pd.read_csv(phase81_file)

print(f"عدد الأصول في المرحلة 81: {len(wadq_phase81_audit_source)}")

# ---------------------------------------------------------------------
# 3) التأكد من الأعمدة الأساسية
# ---------------------------------------------------------------------

required_columns = [
    "ticker",
    "currency",
    "price",
    "price_SAR",
    "signal_phase81",
    "entry_SAR",
    "stop_SAR",
    "target1_SAR",
    "target2_SAR",
    "risk_budget_SAR_corrected",
    "quantity_corrected",
    "position_value_SAR"
]

missing_columns = [
    col for col in required_columns
    if col not in wadq_phase81_audit_source.columns
]

if missing_columns:
    raise ValueError(
        f"الأعمدة المفقودة من المرحلة 81: {missing_columns}"
    )

# ---------------------------------------------------------------------
# 4) إنشاء نسخة تدقيق دون تعديل المصدر
# ---------------------------------------------------------------------

wadq_phase82_audit_df = wadq_phase81_audit_source.copy()

# ---------------------------------------------------------------------
# 5) تصنيف أسباب الانتظار
# ---------------------------------------------------------------------

def wadq_phase82_check(row):

    ticker = str(row["ticker"])
    currency = str(row["currency"]).upper()
    signal = str(row["signal_phase81"])

    price = pd.to_numeric(row["price"], errors="coerce")
    price_sar = pd.to_numeric(row["price_SAR"], errors="coerce")

    entry = pd.to_numeric(row["entry_SAR"], errors="coerce")
    stop = pd.to_numeric(row["stop_SAR"], errors="coerce")
    target1 = pd.to_numeric(row["target1_SAR"], errors="coerce")
    target2 = pd.to_numeric(row["target2_SAR"], errors="coerce")

    quantity = pd.to_numeric(
        row["quantity_corrected"], errors="coerce"
    )

    risk = pd.to_numeric(
        row["risk_budget_SAR_corrected"], errors="coerce"
    )

    # الأصول التي لا نعرف مواصفات العقد والهامش لها
    if currency == "UNKNOWN":
        return "انتظار - يلزم تحديد مواصفات العقد والهامش"

    # فحص الأسعار
    if pd.isna(price) or price <= 0:
        return "انتظار - السعر غير صالح"

    if currency in ["USD", "SAR"] and (
        pd.isna(price_sar) or price_sar <= 0
    ):
        return "انتظار - سعر التحويل إلى الريال غير صالح"

    # فحص وجود إشارة تداول
    if "شراء" not in signal and "بيع" not in signal:
        return "انتظار - لا توجد إشارة تداول مؤكدة"

    # فحص مستويات الدخول ووقف الخسارة والأهداف
    levels = [entry, stop, target1, target2]

    if any(pd.isna(x) or x <= 0 for x in levels):
        return "انتظار - مستويات الدخول والوقف والأهداف غير مكتملة"

    # فحص حجم الصفقة
    if pd.isna(quantity) or quantity <= 0:
        return "انتظار - حجم الصفقة غير صالح"

    # فحص المخاطرة
    if pd.isna(risk) or risk <= 0:
        return "انتظار - ميزانية المخاطر غير صالحة"

    if risk > WADQ_RISK_PER_TRADE_82:
        return "انتظار - المخاطرة تتجاوز 50 ريال"

    # التحقق من اتجاه الصفقة
    if "شراء" in signal:

        if stop >= entry:
            return "انتظار - وقف الخسارة غير صحيح للشراء"

        if target1 <= entry or target2 <= entry:
            return "انتظار - الأهداف غير صحيحة للشراء"

    elif "بيع" in signal:

        if stop <= entry:
            return "انتظار - وقف الخسارة غير صحيح للبيع"

        if target1 >= entry or target2 >= entry:
            return "انتظار - الأهداف غير صحيحة للبيع"

    return "اجتاز الفحص الأولي - يحتاج مراجعة قبل التداول"


wadq_phase82_audit_df["audit_phase82"] = (
    wadq_phase82_audit_df.apply(
        wadq_phase82_check,
        axis=1
    )
)

# ---------------------------------------------------------------------
# 6) تحديد حالة كل أصل
# ---------------------------------------------------------------------

wadq_phase82_audit_df["status_phase82"] = np.where(
    wadq_phase82_audit_df["audit_phase82"].str.startswith(
        "اجتاز الفحص"
    ),
    "مراجعة بشرية مطلوبة",
    "انتظار"
)

# ---------------------------------------------------------------------
# 7) حساب ملخص التدقيق
# ---------------------------------------------------------------------

total_assets = len(wadq_phase82_audit_df)

waiting_assets = (
    wadq_phase82_audit_df["status_phase82"] == "انتظار"
).sum()

review_assets = (
    wadq_phase82_audit_df["status_phase82"] == "مراجعة بشرية مطلوبة"
).sum()

print("\n" + "=" * 75)
print("📊 ملخص المرحلة 82")
print("=" * 75)

print(f"إجمالي الأصول: {total_assets}")
print(f"الأصول في حالة انتظار: {waiting_assets}")
print(f"الأصول التي تحتاج مراجعة بشرية: {review_assets}")

print(f"\nرأس المال: {WADQ_CAPITAL_82:,.2f} ريال")
print(f"المخاطرة لكل صفقة: {WADQ_RISK_PER_TRADE_82:,.2f} ريال")
print(f"الحد الأقصى للمخاطر: {WADQ_MAX_TOTAL_RISK_82:,.2f} ريال")

# ---------------------------------------------------------------------
# 8) عرض نتائج التدقيق
# ---------------------------------------------------------------------

display(
    wadq_phase82_audit_df[
        [
            "ticker",
            "currency",
            "price",
            "price_SAR",
            "signal_phase81",
            "audit_phase82",
            "status_phase82"
        ]
    ]
)

# ---------------------------------------------------------------------
# 9) حفظ النتائج
# ---------------------------------------------------------------------

timestamp82 = datetime.now().strftime("%Y%m%d_%H%M%S")

csv_path82 = f"/content/wadq_phase82_{timestamp82}.csv"
excel_path82 = f"/content/wadq_phase82_{timestamp82}.xlsx"

wadq_phase82_audit_df.to_csv(
    csv_path82,
    index=False,
    encoding="utf-8-sig"
)

wadq_phase82_audit_df.to_excel(
    excel_path82,
    index=False
)

# ---------------------------------------------------------------------
# 10) تسجيل النتائج في متغيرات المشروع
# ---------------------------------------------------------------------

wadq_phase82_completed = True

print("\n" + "=" * 75)
print("✅ تم إنشاء المرحلة 82")
print("=" * 75)

print(f"📄 CSV: {csv_path82}")
print(f"📊 Excel: {excel_path82}")

print("\n⚠️ اجتياز الفحص لا يعني توصية شراء أو بيع.")
print("⚠️ لا يتم تنفيذ أي صفقة تلقائيًا.")
print("⚠️ يجب مراجعة البيانات والاستراتيجية قبل التداول الحقيقي.")

===========================================================================
🌧️ الودق AI — المرحلة 82
تدقيق التوصيات وأسباب الانتظار
===========================================================================

📂 ملف المصدر: /content/wadq_phase81_20261017_151558.csv
عدد الأصول في المرحلة 81: 17

===========================================================================
📊 ملخص المرحلة 82
===========================================================================
إجمالي الأصول: 17
الأصول في حالة انتظار: 17
الأصول التي تحتاج مراجعة بشرية: 0

رأس المال: 10,000.00 ريال
المخاطرة لكل صفقة: 50.00 ريال
الحد الأقصى للمخاطر: 200.00 ريال

,ticker,currency,price,price_SAR,signal_phase81,audit_phase82,status_phase82
0,NVDA,USD,214.1300,802.987500,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
1,TSLA,USD,354.7200,1330.200000,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
2,AAPL,USD,343.4600,1287.975000,انتظار - المخاطرة لا تسمح بوحدة واحدة,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
3,MSFT,USD,529.0500,1983.937500,انتظار - المخاطرة لا تسمح بوحدة واحدة,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
4,AMZN,USD,250.0000,937.500000,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
5,GOOGL,USD,340.5900,1277.212500,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
6,META,USD,709.3300,2659.987500,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
7,QQQ,USD,709.8000,2661.750000,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
8,SPY,USD,763.2500,2862.187500,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
9,2222.SR,SAR,25.2800,25.280000,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
10,1180.SR,SAR,37.1000,37.100000,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
11,2010.SR,SAR,44.5600,44.560000,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار
12,GC=F,UNKNOWN,4181.1001,NaN,انتظار - يلزم تحديد مواصفات العقد والهامش,انتظار - يلزم تحديد مواصفات العقد والهامش,انتظار
13,SI=F,UNKNOWN,56.9950,NaN,انتظار - يلزم تحديد مواصفات العقد والهامش,انتظار - يلزم تحديد مواصفات العقد والهامش,انتظار
14,CL=F,UNKNOWN,101.4100,NaN,انتظار - يلزم تحديد مواصفات العقد والهامش,انتظار - يلزم تحديد مواصفات العقد والهامش,انتظار
15,BZ=F,UNKNOWN,109.8600,NaN,انتظار - يلزم تحديد مواصفات العقد والهامش,انتظار - يلزم تحديد مواصفات العقد والهامش,انتظار
16,BTC-USD,USD,81450.7109,305440.165875,انتظار,انتظار - لا توجد إشارة تداول مؤكدة,انتظار

===========================================================================
✅ تم إنشاء المرحلة 82
===========================================================================
📄 CSV: /content/wadq_phase82_20261017_152315.csv
📊 Excel: /content/wadq_phase82_20261017_152315.xlsx

⚠️ اجتياز الفحص لا يعني توصية شراء أو بيع.
⚠️ لا يتم تنفيذ أي صفقة تلقائيًا.
⚠️ يجب مراجعة البيانات والاستراتيجية قبل التداول الحقيقي.

In [22]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 83
# التجميع النهائي + التحليل الفني + إشارات تجريبية + إدارة المخاطر
#
# رأس المال: 10,000 ريال
# المخاطرة المستهدفة: 50 ريال لكل صفقة
# الحد الأقصى للمخاطر المفتوحة: 200 ريال
#
# لا ينفذ أوامر تداول حقيقية
# =====================================================================

!pip -q install yfinance openpyxl

import os
import warnings
import numpy as np
import pandas as pd
import yfinance as yf

from datetime import datetime
from IPython.display import display

warnings.filterwarnings("ignore")

# =====================================================================
# 1) إعداد المشروع
# =====================================================================

WADQ_CAPITAL_83 = 10000.0
WADQ_RISK_PER_TRADE_83 = 50.0
WADQ_MAX_RISK_83 = 200.0

WADQ_USD_SAR_83 = 3.75

WADQ_NOW_83 = datetime.now()

print("=" * 75)
print("🌧️ الودق AI — المرحلة 83")
print("التجميع النهائي والتحليل الفني")
print("=" * 75)

print(f"رأس المال: {WADQ_CAPITAL_83:,.2f} ريال")
print(f"المخاطرة لكل صفقة: {WADQ_RISK_PER_TRADE_83:,.2f} ريال")
print(f"الحد الأقصى للمخاطر: {WADQ_MAX_RISK_83:,.2f} ريال")

# =====================================================================
# 2) قائمة الأصول
# =====================================================================

wadq_assets_83 = {
    "NVDA": "USD",
    "TSLA": "USD",
    "AAPL": "USD",
    "MSFT": "USD",
    "AMZN": "USD",
    "GOOGL": "USD",
    "META": "USD",
    "QQQ": "USD",
    "SPY": "USD",

    "2222.SR": "SAR",
    "1180.SR": "SAR",
    "2010.SR": "SAR",

    "BTC-USD": "USD"
}

# العقود الآجلة لا تدخل في هذا النموذج
wadq_excluded_83 = [
    "GC=F",
    "SI=F",
    "CL=F",
    "BZ=F",
    "NG=F"
]

# =====================================================================
# 3) دوال التحليل الفني
# =====================================================================

def wadq_rsi_83(series, period=14):

    delta = series.diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    rs = avg_gain / avg_loss.replace(0, np.nan)

    rsi = 100 - (100 / (1 + rs))

    return rsi


def wadq_analyze_asset_83(ticker, currency):

    try:

        # تحميل بيانات تاريخية يومية
        data = yf.download(
            ticker,
            period="1y",
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )

        if data is None or data.empty:
            return {
                "ticker": ticker,
                "currency": currency,
                "status": "انتظار - لا توجد بيانات سعرية",
            }

        # معالجة الأعمدة متعددة المستويات
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.get_level_values(0)

        required = ["Close", "High", "Low"]

        if not all(col in data.columns for col in required):
            return {
                "ticker": ticker,
                "currency": currency,
                "status": "انتظار - الأعمدة الفنية غير مكتملة",
            }

        data = data.copy()

        data = data.dropna(subset=required)

        if len(data) < 60:
            return {
                "ticker": ticker,
                "currency": currency,
                "status": "انتظار - التاريخ السعري غير كافٍ",
            }

        close = data["Close"]
        high = data["High"]
        low = data["Low"]

        # -------------------------------------------------------------
        # المؤشرات
        # -------------------------------------------------------------

        data["SMA20"] = close.rolling(20).mean()
        data["SMA50"] = close.rolling(50).mean()

        data["RSI14"] = wadq_rsi_83(close, 14)

        ema12 = close.ewm(span=12, adjust=False).mean()
        ema26 = close.ewm(span=26, adjust=False).mean()

        data["MACD"] = ema12 - ema26

        data["MACD_SIGNAL"] = data["MACD"].ewm(
            span=9,
            adjust=False
        ).mean()

        # -------------------------------------------------------------
        # ATR لحساب وقف الخسارة
        # -------------------------------------------------------------

        previous_close = close.shift(1)

        tr1 = high - low
        tr2 = (high - previous_close).abs()
        tr3 = (low - previous_close).abs()

        true_range = pd.concat(
            [tr1, tr2, tr3],
            axis=1
        ).max(axis=1)

        data["ATR14"] = true_range.rolling(14).mean()

        latest = data.iloc[-1]

        price = float(latest["Close"])
        sma20 = float(latest["SMA20"])
        sma50 = float(latest["SMA50"])
        rsi = float(latest["RSI14"])
        macd = float(latest["MACD"])
        macd_signal = float(latest["MACD_SIGNAL"])
        atr = float(latest["ATR14"])

        date_price = data.index[-1]

        # -------------------------------------------------------------
        # تحويل السعر إلى الريال
        # -------------------------------------------------------------

        if currency == "USD":
            price_sar = price * WADQ_USD_SAR_83
        elif currency == "SAR":
            price_sar = price
        else:
            price_sar = np.nan

        # -------------------------------------------------------------
        # شروط استراتيجية تجريبية أولية
        # -------------------------------------------------------------

        buy_condition = (
            price > sma20
            and sma20 > sma50
            and 50 <= rsi <= 70
            and macd > macd_signal
        )

        # -------------------------------------------------------------
        # مستويات الصفقة
        # -------------------------------------------------------------

        if buy_condition and atr > 0:

            entry_sar = price_sar

            # وقف خسارة بمقدار 1.5 ATR
            stop_sar = (
                entry_sar - (1.5 * atr *
                (WADQ_USD_SAR_83 if currency == "USD" else 1))
            )

            risk_per_unit = entry_sar - stop_sar

            # الهدف الأول: 2R
            target1_sar = entry_sar + (2 * risk_per_unit)

            # الهدف الثاني: 3R
            target2_sar = entry_sar + (3 * risk_per_unit)

            signal = "مرشح شراء تجريبي"

        else:

            entry_sar = np.nan
            stop_sar = np.nan
            target1_sar = np.nan
            target2_sar = np.nan

            signal = "انتظار"

        return {
            "ticker": ticker,
            "currency": currency,
            "price": price,
            "price_SAR": price_sar,
            "price_date": str(date_price),
            "SMA20": sma20,
            "SMA50": sma50,
            "RSI14": rsi,
            "MACD": macd,
            "MACD_SIGNAL": macd_signal,
            "ATR14": atr,
            "signal": signal,
            "entry_SAR": entry_sar,
            "stop_SAR": stop_sar,
            "target1_SAR": target1_sar,
            "target2_SAR": target2_sar,
            "status": "تم التحليل"
        }

    except Exception as e:

        return {
            "ticker": ticker,
            "currency": currency,
            "status": f"خطأ في التحليل: {str(e)[:150]}"
        }

# =====================================================================
# 4) تحليل جميع الأصول
# =====================================================================

wadq_results_83 = []

for ticker, currency in wadq_assets_83.items():

    print(f"🔎 تحليل {ticker}")

    result = wadq_analyze_asset_83(
        ticker,
        currency
    )

    wadq_results_83.append(result)

wadq_final_technical_83 = pd.DataFrame(wadq_results_83)

# =====================================================================
# 5) حساب حجم الصفقة وإدارة المخاطر
# =====================================================================

wadq_final_technical_83["risk_per_unit_SAR"] = (
    wadq_final_technical_83["entry_SAR"]
    - wadq_final_technical_83["stop_SAR"]
)

wadq_final_technical_83["quantity"] = 0

wadq_final_technical_83["risk_SAR"] = 0.0

wadq_final_technical_83["position_value_SAR"] = 0.0

remaining_risk = WADQ_MAX_RISK_83
remaining_capital = WADQ_CAPITAL_83

# ترتيب المرشحين حسب RSI الأقرب إلى 60
candidate_mask = (
    wadq_final_technical_83["signal"]
    == "مرشح شراء تجريبي"
)

candidates = wadq_final_technical_83.loc[
    candidate_mask
].copy()

if not candidates.empty:

    candidates["priority"] = (
        60 - candidates["RSI14"]
    ).abs()

    candidates = candidates.sort_values(
        "priority"
    )

    for idx, row in candidates.iterrows():

        entry = row["entry_SAR"]
        stop = row["stop_SAR"]

        if pd.isna(entry) or pd.isna(stop):
            continue

        risk_per_unit = entry - stop

        if risk_per_unit <= 0:
            continue

        # حساب كمية الأسهم وفق المخاطرة
        qty_by_risk = int(
            WADQ_RISK_PER_TRADE_83 / risk_per_unit
        )

        # حساب الكمية وفق رأس المال المتبقي
        qty_by_capital = int(
            remaining_capital / entry
        )

        quantity = min(
            qty_by_risk,
            qty_by_capital
        )

        if quantity <= 0:
            wadq_final_technical_83.loc[
                idx, "signal"
            ] = "انتظار - رأس المال لا يسمح بوحدة واحدة"
            continue

        actual_risk = quantity * risk_per_unit

        # التحقق من الحد الأقصى للمخاطر
        if actual_risk > remaining_risk:
            wadq_final_technical_83.loc[
                idx, "signal"
            ] = "انتظار - تجاوز حد المخاطر"
            continue

        # تخصيص الصفقة
        position_value = quantity * entry

        wadq_final_technical_83.loc[
            idx, "quantity"
        ] = quantity

        wadq_final_technical_83.loc[
            idx, "risk_SAR"
        ] = actual_risk

        wadq_final_technical_83.loc[
            idx, "position_value_SAR"
        ] = position_value

        remaining_risk -= actual_risk
        remaining_capital -= position_value

# =====================================================================
# 6) التدقيق النهائي
# =====================================================================

wadq_final_technical_83["final_status"] = np.where(
    wadq_final_technical_83["quantity"] > 0,
    "مرشح للتداول التجريبي",
    "انتظار"
)

# =====================================================================
# 7) ملخص المشروع
# =====================================================================

total_assets = len(wadq_final_technical_83)

total_candidates = (
    wadq_final_technical_83["final_status"]
    == "مرشح للتداول التجريبي"
).sum()

total_risk = wadq_final_technical_83["risk_SAR"].sum()

total_position = (
    wadq_final_technical_83["position_value_SAR"].sum()
)

print("\n" + "=" * 75)
print("📊 التقرير النهائي — المرحلة 83")
print("=" * 75)

print(f"عدد الأصول: {total_assets}")
print(f"عدد المرشحين التجريبيين: {total_candidates}")
print(f"إجمالي المخاطر المحسوبة: {total_risk:,.2f} ريال")
print(f"إجمالي قيمة المراكز النظرية: {total_position:,.2f} ريال")
print(f"رأس المال المتبقي نظريًا: {remaining_capital:,.2f} ريال")

# =====================================================================
# 8) عرض التقرير
# =====================================================================

display(
    wadq_final_technical_83[
        [
            "ticker",
            "currency",
            "price",
            "price_SAR",
            "price_date",
            "SMA20",
            "SMA50",
            "RSI14",
            "MACD",
            "MACD_SIGNAL",
            "signal",
            "entry_SAR",
            "stop_SAR",
            "target1_SAR",
            "target2_SAR",
            "quantity",
            "risk_SAR",
            "position_value_SAR",
            "final_status"
        ]
    ]
)

# =====================================================================
# 9) حفظ الملفات
# =====================================================================

timestamp83 = datetime.now().strftime("%Y%m%d_%H%M%S")

csv_path83 = f"/content/wadq_phase83_{timestamp83}.csv"
excel_path83 = f"/content/wadq_phase83_{timestamp83}.xlsx"

wadq_final_technical_83.to_csv(
    csv_path83,
    index=False,
    encoding="utf-8-sig"
)

wadq_final_technical_83.to_excel(
    excel_path83,
    index=False
)

# =====================================================================
# 10) تسجيل المرحلة
# =====================================================================

wadq_phase83_completed = True

print("\n" + "=" * 75)
print("✅ تم إنشاء المرحلة 83")
print("=" * 75)

print(f"📄 CSV: {csv_path83}")
print(f"📊 Excel: {excel_path83}")

print("\n⚠️ هذه توصيات تجريبية وليست أوامر تداول.")
print("⚠️ لا توجد ضمانات للربح.")
print("⚠️ يجب اختبار الاستراتيجية تاريخيًا قبل التداول الحقيقي.")

===========================================================================
🌧️ الودق AI — المرحلة 83
التجميع النهائي والتحليل الفني
===========================================================================
رأس المال: 10,000.00 ريال
المخاطرة لكل صفقة: 50.00 ريال
الحد الأقصى للمخاطر: 200.00 ريال
🔎 تحليل NVDA
🔎 تحليل TSLA
🔎 تحليل AAPL
🔎 تحليل MSFT
🔎 تحليل AMZN
🔎 تحليل GOOGL
🔎 تحليل META
🔎 تحليل QQQ
🔎 تحليل SPY
🔎 تحليل 2222.SR
🔎 تحليل 1180.SR
🔎 تحليل 2010.SR
🔎 تحليل BTC-USD

===========================================================================
📊 التقرير النهائي — المرحلة 83
===========================================================================
عدد الأصول: 13
عدد المرشحين التجريبيين: 1
إجمالي المخاطر المحسوبة: 37.63 ريال
إجمالي قيمة المراكز النظرية: 1,287.97 ريال
رأس المال المتبقي نظريًا: 8,712.03 ريال

,ticker,currency,price,price_SAR,price_date,SMA20,SMA50,RSI14,MACD,MACD_SIGNAL,signal,entry_SAR,stop_SAR,target1_SAR,target2_SAR,quantity,risk_SAR,position_value_SAR,final_status
0,NVDA,USD,214.130005,802.987518,2026-10-16 00:00:00,228.177001,222.963153,37.558177,-0.147866,2.217692,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
1,TSLA,USD,354.720001,1330.200005,2026-10-16 00:00:00,370.333499,359.462198,42.203875,1.414684,3.505525,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
2,AAPL,USD,343.459991,1287.974968,2026-10-16 00:00:00,337.424002,325.694000,62.082319,4.138792,3.944912,مرشح شراء تجريبي,1287.974968,1250.343704,1363.237495,1400.868759,1,37.631264,1287.974968,مرشح للتداول التجريبي
3,MSFT,USD,529.049988,1983.937454,2026-10-16 00:00:00,520.220500,505.365515,57.358140,11.253144,10.980207,انتظار - رأس المال لا يسمح بوحدة واحدة,1983.937454,1917.895914,2116.020535,2182.062075,0,0.000000,0.000000,انتظار
4,AMZN,USD,250.000000,937.500000,2026-10-16 00:00:00,253.225999,257.075999,44.993070,0.185668,0.056647,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
5,GOOGL,USD,340.589996,1277.212486,2026-10-16 00:00:00,346.414000,344.491907,44.465854,1.021960,1.195935,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
6,META,USD,709.330017,2659.987564,2026-10-16 00:00:00,735.774997,654.955577,50.258922,19.475681,25.564046,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
7,QQQ,USD,709.799988,2661.749954,2026-10-16 00:00:00,742.519003,726.326044,35.136131,1.659163,6.325403,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
8,SPY,USD,763.250000,2862.187500,2026-10-16 00:00:00,771.183997,767.400020,44.185450,2.024268,2.884984,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
9,2222.SR,SAR,25.280001,25.280001,2026-10-15 00:00:00,25.593000,25.901139,38.451218,-0.096482,-0.098893,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
10,1180.SR,SAR,37.099998,37.099998,2026-10-15 00:00:00,39.096000,40.777200,32.033944,-1.029261,-0.805507,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
11,2010.SR,SAR,44.560001,44.560001,2026-10-15 00:00:00,46.541000,48.376987,29.020408,-0.988667,-0.865296,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار
12,BTC-USD,USD,81383.289062,305187.333984,2026-10-17 00:00:00,83407.662891,81322.919219,46.069356,81.598924,608.301195,انتظار,NaN,NaN,NaN,NaN,0,0.000000,0.000000,انتظار

===========================================================================
✅ تم إنشاء المرحلة 83
===========================================================================
📄 CSV: /content/wadq_phase83_20261017_152758.csv
📊 Excel: /content/wadq_phase83_20261017_152758.xlsx

⚠️ هذه توصيات تجريبية وليست أوامر تداول.
⚠️ لا توجد ضمانات للربح.
⚠️ يجب اختبار الاستراتيجية تاريخيًا قبل التداول الحقيقي.

In [23]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 84
# الاختبار التاريخي لاستراتيجية الشراء
# =====================================================================

!pip -q install yfinance openpyxl

import warnings
import numpy as np
import pandas as pd
import yfinance as yf

from datetime import datetime
from IPython.display import display

warnings.filterwarnings("ignore")

# =====================================================================
# 1) إعداد رأس المال والمخاطر
# =====================================================================

INITIAL_CAPITAL = 10000.0
RISK_PER_TRADE = 50.0
MAX_TOTAL_RISK = 200.0

# تكلفة افتراضية لكل عملية شراء أو بيع
COMMISSION_RATE = 0.001
SLIPPAGE_RATE = 0.0005

# =====================================================================
# 2) الأصول المراد اختبارها
# =====================================================================

assets = {
    "NVDA": "USD",
    "TSLA": "USD",
    "AAPL": "USD",
    "MSFT": "USD",
    "AMZN": "USD",
    "GOOGL": "USD",
    "META": "USD",
    "QQQ": "USD",
    "SPY": "USD",
    "2222.SR": "SAR",
    "1180.SR": "SAR",
    "2010.SR": "SAR",
    "BTC-USD": "USD"
}

USD_SAR = 3.75

# =====================================================================
# 3) حساب المؤشرات الفنية
# =====================================================================

def calculate_indicators(df):

    df = df.copy()

    close = df["Close"]

    df["SMA20"] = close.rolling(20).mean()
    df["SMA50"] = close.rolling(50).mean()

    delta = close.diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1/14,
        min_periods=14,
        adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1/14,
        min_periods=14,
        adjust=False
    ).mean()

    rs = avg_gain / avg_loss.replace(0, np.nan)

    df["RSI14"] = 100 - (100 / (1 + rs))

    ema12 = close.ewm(
        span=12,
        adjust=False
    ).mean()

    ema26 = close.ewm(
        span=26,
        adjust=False
    ).mean()

    df["MACD"] = ema12 - ema26

    df["MACD_SIGNAL"] = df["MACD"].ewm(
        span=9,
        adjust=False
    ).mean()

    previous_close = close.shift(1)

    tr1 = df["High"] - df["Low"]
    tr2 = (df["High"] - previous_close).abs()
    tr3 = (df["Low"] - previous_close).abs()

    true_range = pd.concat(
        [tr1, tr2, tr3],
        axis=1
    ).max(axis=1)

    df["ATR14"] = true_range.rolling(14).mean()

    # إشارة الشراء في نهاية اليوم
    df["BUY_SIGNAL"] = (
        (df["Close"] > df["SMA20"]) &
        (df["SMA20"] > df["SMA50"]) &
        (df["RSI14"] >= 50) &
        (df["RSI14"] <= 70) &
        (df["MACD"] > df["MACD_SIGNAL"])
    )

    return df

# =====================================================================
# 4) اختبار أصل واحد
# =====================================================================

def backtest_asset(ticker, currency):

    try:

        df = yf.download(
            ticker,
            period="5y",
            interval="1d",
            auto_adjust=True,
            progress=False
        )

        if df is None or df.empty:
            return [], {
                "ticker": ticker,
                "status": "لا توجد بيانات"
            }

        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        required = ["Open", "High", "Low", "Close"]

        if not all(c in df.columns for c in required):
            return [], {
                "ticker": ticker,
                "status": "بيانات غير مكتملة"
            }

        df = calculate_indicators(df)

        trades = []

        position = None

        # نبدأ بعد اكتمال المؤشرات
        for i in range(60, len(df) - 1):

            current = df.iloc[i]
            next_day = df.iloc[i + 1]

            # ---------------------------------------------------------
            # إدارة الصفقة المفتوحة
            # ---------------------------------------------------------

            if position is not None:

                exit_price = None
                exit_reason = None

                # فحص وقف الخسارة والهدف باستخدام بيانات اليوم
                stop_hit = current["Low"] <= position["stop"]
                target_hit = current["High"] >= position["target"]

                # إذا لمس السعر الوقف والهدف في اليوم نفسه،
                # نفترض الوقف أولًا بشكل محافظ
                if stop_hit:

                    exit_price = position["stop"]
                    exit_reason = "وقف خسارة"

                elif target_hit:

                    exit_price = position["target"]
                    exit_reason = "هدف"

                # خروج بعد 20 يوم تداول
                elif i - position["entry_index"] >= 20:

                    exit_price = current["Close"]
                    exit_reason = "خروج زمني"

                if exit_price is not None:

                    # تكلفة الانزلاق عند البيع
                    actual_exit = exit_price * (
                        1 - SLIPPAGE_RATE
                    )

                    gross_pnl = (
                        actual_exit - position["entry"]
                    ) * position["quantity"]

                    entry_cost = (
                        position["entry"] *
                        position["quantity"] *
                        COMMISSION_RATE
                    )

                    exit_cost = (
                        actual_exit *
                        position["quantity"] *
                        COMMISSION_RATE
                    )

                    net_pnl = (
                        gross_pnl -
                        entry_cost -
                        exit_cost
                    )

                    trades.append({
                        "ticker": ticker,
                        "entry_date": position["entry_date"],
                        "exit_date": df.index[i],
                        "entry_price": position["entry"],
                        "exit_price": actual_exit,
                        "quantity": position["quantity"],
                        "risk_SAR": position["risk"],
                        "pnl_SAR": net_pnl,
                        "exit_reason": exit_reason
                    })

                    position = None

            # ---------------------------------------------------------
            # البحث عن فرصة جديدة
            # ---------------------------------------------------------

            if position is None:

                if not bool(current["BUY_SIGNAL"]):
                    continue

                atr = current["ATR14"]

                if pd.isna(atr) or atr <= 0:
                    continue

                # الدخول في افتتاح اليوم التالي
                raw_entry = next_day["Open"]

                if pd.isna(raw_entry) or raw_entry <= 0:
                    continue

                # تكلفة الانزلاق عند الشراء
                entry_price = raw_entry * (
                    1 + SLIPPAGE_RATE
                )

                stop_price = entry_price - (1.5 * atr)

                risk_per_share = entry_price - stop_price

                if risk_per_share <= 0:
                    continue

                target_price = (
                    entry_price +
                    2 * risk_per_share
                )

                # تحويل العملة
                if currency == "USD":
                    entry_sar = entry_price * USD_SAR
                    stop_sar = stop_price * USD_SAR
                else:
                    entry_sar = entry_price
                    stop_sar = stop_price

                risk_per_share_sar = (
                    entry_sar - stop_sar
                )

                if risk_per_share_sar <= 0:
                    continue

                # تحديد كمية الأسهم
                quantity = int(
                    RISK_PER_TRADE /
                    risk_per_share_sar
                )

                # لا نسمح بصفقة تتجاوز رأس المال
                quantity_capital = int(
                    INITIAL_CAPITAL /
                    entry_sar
                )

                quantity = min(
                    quantity,
                    quantity_capital
                )

                if quantity <= 0:
                    continue

                actual_risk = (
                    quantity *
                    risk_per_share_sar
                )

                # لا نتجاوز المخاطرة المحددة
                if actual_risk > RISK_PER_TRADE:
                    continue

                position = {
                    "entry": entry_price,
                    "stop": stop_price,
                    "target": target_price,
                    "quantity": quantity,
                    "risk": actual_risk,
                    "entry_date": df.index[i + 1],
                    "entry_index": i + 1
                }

        # -------------------------------------------------------------
        # إغلاق أي صفقة متبقية في نهاية الاختبار
        # -------------------------------------------------------------

        if position is not None:

            last = df.iloc[-1]

            exit_price = last["Close"] * (
                1 - SLIPPAGE_RATE
            )

            gross_pnl = (
                exit_price - position["entry"]
            ) * position["quantity"]

            entry_cost = (
                position["entry"] *
                position["quantity"] *
                COMMISSION_RATE
            )

            exit_cost = (
                exit_price *
                position["quantity"] *
                COMMISSION_RATE
            )

            net_pnl = (
                gross_pnl -
                entry_cost -
                exit_cost
            )

            trades.append({
                "ticker": ticker,
                "entry_date": position["entry_date"],
                "exit_date": df.index[-1],
                "entry_price": position["entry"],
                "exit_price": exit_price,
                "quantity": position["quantity"],
                "risk_SAR": position["risk"],
                "pnl_SAR": net_pnl,
                "exit_reason": "نهاية الاختبار"
            })

        return trades, {
            "ticker": ticker,
            "status": "تم الاختبار",
            "عدد_البيانات": len(df),
            "تاريخ_البداية": str(df.index[0]),
            "تاريخ_النهاية": str(df.index[-1])
        }

    except Exception as e:

        return [], {
            "ticker": ticker,
            "status": f"خطأ: {str(e)[:120]}"
        }

# =====================================================================
# 5) تنفيذ الاختبار التاريخي
# =====================================================================

all_trades = []
asset_status = []

for ticker, currency in assets.items():

    print(f"🔎 اختبار {ticker}")

    trades, status = backtest_asset(
        ticker,
        currency
    )

    all_trades.extend(trades)
    asset_status.append(status)

trades_df = pd.DataFrame(all_trades)
status_df = pd.DataFrame(asset_status)

# =====================================================================
# 6) تحليل النتائج
# =====================================================================

if trades_df.empty:

    print("\n⚠️ لم يتم العثور على صفقات تاريخية.")

    summary_df = pd.DataFrame([{
        "عدد_الصفقات": 0,
        "إجمالي_الربح_والخسارة": 0,
        "نسبة_النجاح": 0,
        "متوسط_الصفقة": 0,
        "رسالة": "لا توجد صفقات كافية لتقييم الاستراتيجية"
    }])

else:

    trades_df = trades_df.sort_values(
        "exit_date"
    ).reset_index(drop=True)

    trades_df["cumulative_pnl"] = (
        trades_df["pnl_SAR"].cumsum()
    )

    trades_df["equity"] = (
        INITIAL_CAPITAL +
        trades_df["cumulative_pnl"]
    )

    trades_df["peak_equity"] = (
        trades_df["equity"].cummax()
    )

    trades_df["drawdown"] = (
        trades_df["equity"] -
        trades_df["peak_equity"]
    )

    total_trades = len(trades_df)

    wins = (
        trades_df["pnl_SAR"] > 0
    ).sum()

    losses = (
        trades_df["pnl_SAR"] <= 0
    ).sum()

    win_rate = (
        wins / total_trades * 100
    )

    total_pnl = trades_df["pnl_SAR"].sum()

    average_trade = (
        trades_df["pnl_SAR"].mean()
    )

    gross_profit = trades_df.loc[
        trades_df["pnl_SAR"] > 0,
        "pnl_SAR"
    ].sum()

    gross_loss = abs(
        trades_df.loc[
            trades_df["pnl_SAR"] < 0,
            "pnl_SAR"
        ].sum()
    )

    profit_factor = (
        gross_profit / gross_loss
        if gross_loss > 0
        else np.nan
    )

    max_drawdown = (
        trades_df["drawdown"].min()
    )

    final_equity = (
        INITIAL_CAPITAL +
        total_pnl
    )

    summary_df = pd.DataFrame([{
        "عدد_الصفقات": total_trades,
        "الصفقات_الرابحة": wins,
        "الصفقات_الخاسرة": losses,
        "نسبة_النجاح": round(win_rate, 2),
        "إجمالي_الربح_والخسارة": round(total_pnl, 2),
        "متوسط_الصفقة": round(average_trade, 2),
        "عامل_الربح": round(profit_factor, 2)
            if pd.notna(profit_factor) else np.nan,
        "أكبر_تراجع": round(max_drawdown, 2),
        "رأس_المال_النهائي": round(final_equity, 2)
    }])

# =====================================================================
# 7) عرض التقرير
# =====================================================================

print("\n" + "=" * 75)
print("🌧️ التقرير النهائي — المرحلة 84")
print("=" * 75)

print(f"رأس المال الابتدائي: {INITIAL_CAPITAL:,.2f} ريال")
print(f"المخاطرة المستهدفة: {RISK_PER_TRADE:,.2f} ريال")

display(summary_df)

print("\n📊 نتائج الأصول:")
display(status_df)

if not trades_df.empty:

    print("\n📋 سجل الصفقات:")
    display(trades_df)

# =====================================================================
# 8) حفظ النتائج
# =====================================================================

timestamp84 = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

csv_path84 = f"/content/wadq_phase84_trades_{timestamp84}.csv"

excel_path84 = f"/content/wadq_phase84_report_{timestamp84}.xlsx"

if not trades_df.empty:
    trades_df.to_csv(
        csv_path84,
        index=False,
        encoding="utf-8-sig"
    )

with pd.ExcelWriter(
    excel_path84,
    engine="openpyxl"
) as writer:

    summary_df.to_excel(
        writer,
        sheet_name="ملخص الاختبار",
        index=False
    )

    status_df.to_excel(
        writer,
        sheet_name="حالة الأصول",
        index=False
    )

    if not trades_df.empty:
        trades_df.to_excel(
            writer,
            sheet_name="سجل الصفقات",
            index=False
        )

print("\n" + "=" * 75)
print("✅ تم إنشاء المرحلة 84")
print("=" * 75)

print(f"📊 Excel: {excel_path84}")

if not trades_df.empty:
    print(f"📄 CSV: {csv_path84}")

print("\n⚠️ الاختبار التاريخي لا يضمن الأرباح المستقبلية.")
print("⚠️ لا يتم تنفيذ أي أوامر تداول حقيقية.")
print("⚠️ نتائج الأصول مستقلة وليست محاكاة محفظة مشتركة.")

🔎 اختبار NVDA
🔎 اختبار TSLA
🔎 اختبار AAPL
🔎 اختبار MSFT
🔎 اختبار AMZN
🔎 اختبار GOOGL
🔎 اختبار META
🔎 اختبار QQQ
🔎 اختبار SPY
🔎 اختبار 2222.SR
🔎 اختبار 1180.SR
🔎 اختبار 2010.SR
🔎 اختبار BTC-USD

===========================================================================
🌧️ التقرير النهائي — المرحلة 84
===========================================================================
رأس المال الابتدائي: 10,000.00 ريال
المخاطرة المستهدفة: 50.00 ريال

,عدد_الصفقات,الصفقات_الرابحة,الصفقات_الخاسرة,نسبة_النجاح,إجمالي_الربح_والخسارة,متوسط_الصفقة,عامل_الربح,أكبر_تراجع,رأس_المال_النهائي
0,396,163,233,41.16,-747.65,-1.89,0.86,-796.71,9252.35

📊 نتائج الأصول:

,ticker,status,عدد_البيانات,تاريخ_البداية,تاريخ_النهاية
0,NVDA,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
1,TSLA,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
2,AAPL,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
3,MSFT,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
4,AMZN,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
5,GOOGL,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
6,META,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
7,QQQ,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
8,SPY,تم الاختبار,1255,2021-10-18 00:00:00,2026-10-16 00:00:00
9,2222.SR,تم الاختبار,1247,2021-10-17 00:00:00,2026-10-15 00:00:00
10,1180.SR,تم الاختبار,1246,2021-10-17 00:00:00,2026-10-15 00:00:00
11,2010.SR,تم الاختبار,1246,2021-10-17 00:00:00,2026-10-15 00:00:00
12,BTC-USD,تم الاختبار,1827,2021-10-17 00:00:00,2026-10-17 00:00:00

📋 سجل الصفقات:

,ticker,entry_date,exit_date,entry_price,exit_price,quantity,risk_SAR,pnl_SAR,exit_reason,cumulative_pnl,equity,peak_equity,drawdown
0,2222.SR,2022-01-18,2022-01-24,24.281126,23.927388,146,49.898121,-58.684137,وقف خسارة,-58.684137,9941.315863,9941.315863,0.000000
1,2222.SR,2022-01-25,2022-01-30,23.853408,24.489458,154,49.919174,90.506915,هدف,31.822778,10031.822778,10031.822778,0.000000
2,2010.SR,2022-01-18,2022-02-03,99.201516,97.131050,24,48.525036,-54.403173,وقف خسارة,-22.580395,9977.419605,10031.822778,-54.403173
3,2222.SR,2022-01-31,2022-02-06,24.445629,24.081245,141,49.679499,-58.220366,وقف خسارة,-80.800761,9919.199239,10031.822778,-112.623539
4,1180.SR,2022-01-25,2022-02-13,42.410112,41.003464,36,49.900895,-53.642215,وقف خسارة,-134.442976,9865.557024,10031.822778,-166.265754
...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,GOOGL,2026-10-13,2026-10-15,356.408126,344.091351,1,45.542413,-13.017275,وقف خسارة,-716.266734,9283.733266,10049.061196,-765.327930
392,NVDA,2026-09-23,2026-10-15,228.144014,219.197054,1,33.139899,-9.394301,وقف خسارة,-725.661034,9274.338966,10049.061196,-774.722230
393,AAPL,2026-10-15,2026-10-16,347.123487,343.288261,1,37.020542,-4.525638,نهاية الاختبار,-730.186672,9269.813328,10049.061196,-779.247868
394,SPY,2026-10-05,2026-10-16,770.074847,762.868375,1,40.031910,-8.739416,نهاية الاختبار,-738.926088,9261.073912,10049.061196,-787.987284
395,GOOGL,2026-10-16,2026-10-16,348.454139,340.419701,1,47.503117,-8.723311,نهاية الاختبار,-747.649399,9252.350601,10049.061196,-796.710595

===========================================================================
✅ تم إنشاء المرحلة 84
===========================================================================
📊 Excel: /content/wadq_phase84_report_20261017_153245.xlsx
📄 CSV: /content/wadq_phase84_trades_20261017_153245.csv

⚠️ الاختبار التاريخي لا يضمن الأرباح المستقبلية.
⚠️ لا يتم تنفيذ أي أوامر تداول حقيقية.
⚠️ نتائج الأصول مستقلة وليست محاكاة محفظة مشتركة.

In [25]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 85B
# تدقيق نتائج المرحلة 85
# =====================================================================

import pandas as pd
import numpy as np
import os

# ملفات المرحلة 85 التي ظهرت في نتيجتك
TRADES_FILE = "/content/wadq_phase85_trades_20261017_154243.csv"
DAILY_FILE = "/content/wadq_phase85_daily_20261017_154243.csv"
SUMMARY_FILE = "/content/wadq_phase85_summary_20261017_154243.csv"

print("=" * 65)
print("🌧️ الودق AI — المرحلة 85B")
print("تدقيق الربح والخسارة وقيمة المحفظة")
print("=" * 65)

# ------------------------------------------------------------
# 1) التأكد من وجود الملفات
# ------------------------------------------------------------

for file in [TRADES_FILE, DAILY_FILE, SUMMARY_FILE]:

    if not os.path.exists(file):
        raise FileNotFoundError(
            f"لم يتم العثور على الملف:\n{file}"
        )

# ------------------------------------------------------------
# 2) قراءة الملفات
# ------------------------------------------------------------

trades = pd.read_csv(TRADES_FILE)
daily = pd.read_csv(DAILY_FILE)
summary = pd.read_csv(SUMMARY_FILE)

# ------------------------------------------------------------
# 3) فحص سجل الصفقات
# ------------------------------------------------------------

trades["pnl_sar"] = pd.to_numeric(
    trades["pnl_sar"], errors="coerce"
)

trade_pnl = trades["pnl_sar"].sum()

winning = trades[trades["pnl_sar"] > 0]
losing = trades[trades["pnl_sar"] < 0]

gross_profit = winning["pnl_sar"].sum()
gross_loss = abs(losing["pnl_sar"].sum())

profit_factor = (
    gross_profit / gross_loss
    if gross_loss > 0
    else np.nan
)

print("\n--- تدقيق الصفقات ---")
print("عدد الصفقات:", len(trades))
print(f"إجمالي الربح من الصفقات: {gross_profit:,.2f} ريال")
print(f"إجمالي الخسائر من الصفقات: {gross_loss:,.2f} ريال")
print(f"صافي الصفقات: {trade_pnl:,.2f} ريال")
print(f"Profit Factor المعاد حسابه: {profit_factor:.4f}")

# ------------------------------------------------------------
# 4) فحص الأداء اليومي
# ------------------------------------------------------------

daily["equity_sar"] = pd.to_numeric(
    daily["equity_sar"], errors="coerce"
)

daily["cash_sar"] = pd.to_numeric(
    daily["cash_sar"], errors="coerce"
)

daily["market_value_sar"] = pd.to_numeric(
    daily["market_value_sar"], errors="coerce"
)

daily = daily.dropna(subset=["equity_sar"])

daily = daily.sort_values("date").reset_index(drop=True)

daily["peak_equity_corrected"] = (
    daily["equity_sar"].cummax()
)

daily["drawdown_corrected"] = (
    daily["equity_sar"] -
    daily["peak_equity_corrected"]
)

min_equity = daily["equity_sar"].min()
max_equity = daily["equity_sar"].max()

corrected_max_drawdown = daily["drawdown_corrected"].min()

last_daily_equity = daily["equity_sar"].iloc[-1]

print("\n--- تدقيق الأداء اليومي ---")
print(f"أعلى قيمة للمحفظة: {max_equity:,.2f} ريال")
print(f"أقل قيمة للمحفظة: {min_equity:,.2f} ريال")
print(f"قيمة آخر يوم: {last_daily_equity:,.2f} ريال")
print(f"أقصى تراجع بعد إعادة الحساب: {corrected_max_drawdown:,.2f} ريال")

# ------------------------------------------------------------
# 5) مقارنة التقرير الأصلي
# ------------------------------------------------------------

reported_final = float(
    summary["final_equity_sar"].iloc[0]
)

reported_pnl = float(
    summary["total_pnl_sar"].iloc[0]
)

initial_capital = float(
    summary["initial_capital_sar"].iloc[0]
)

print("\n--- مقارنة التقرير ---")
print(f"رأس المال الأولي: {initial_capital:,.2f} ريال")
print(f"الربح المعلن: {reported_pnl:,.2f} ريال")
print(f"قيمة المحفظة المعلنة: {reported_final:,.2f} ريال")

print(
    "الربح المتوقع من قيمة المحفظة:",
    f"{reported_final - initial_capital:,.2f} ريال"
)

print(
    "الفرق بين ربح الصفقات وربح المحفظة:",
    f"{trade_pnl - (reported_final - initial_capital):,.2f} ريال"
)

# ------------------------------------------------------------
# 6) اختبارات التناقض
# ------------------------------------------------------------

checks = []

checks.append({
    "test": "الربح يطابق تغير رأس المال",
    "result": abs(
        reported_pnl -
        (reported_final - initial_capital)
    ) < 1.0
})

checks.append({
    "test": "التراجع لا يتجاوز رأس المال بشكل مستحيل",
    "result": corrected_max_drawdown >= -initial_capital
})

checks.append({
    "test": "قيمة المحفظة موجبة",
    "result": min_equity > 0
})

checks_df = pd.DataFrame(checks)

print("\n--- اختبارات التدقيق ---")
display(checks_df)

print("\n--- آخر 10 أيام من المحفظة ---")
display(daily.tail(10))

print("\n--- آخر 10 صفقات ---")
display(trades.tail(10))

print("\n" + "=" * 65)
if checks_df["result"].all():
    print("اجتازت النتائج الاختبارات الأولية.")
    print("لكن هذا لا يعني السماح بالتداول الحقيقي.")
else:
    print("⚠️ توجد تناقضات تحتاج إلى تصحيح.")
    print("لا تبدئي التداول الحقيقي.")339
print("=" * 65)

=================================================================
🌧️ الودق AI — المرحلة 85B
تدقيق الربح والخسارة وقيمة المحفظة
=================================================================

--- تدقيق الصفقات ---
عدد الصفقات: 502
إجمالي الربح من الصفقات: 12,072.98 ريال
إجمالي الخسائر من الصفقات: 11,791.35 ريال
صافي الصفقات: 281.63 ريال
Profit Factor المعاد حسابه: 1.0239

--- تدقيق الأداء اليومي ---
أعلى قيمة للمحفظة: 11,504.22 ريال
أقل قيمة للمحفظة: 10.93 ريال
قيمة آخر يوم: 8,987.40 ريال
أقصى تراجع بعد إعادة الحساب: -10,192.88 ريال

--- مقارنة التقرير ---
رأس المال الأولي: 10,000.00 ريال
الربح المعلن: 281.63 ريال
قيمة المحفظة المعلنة: 8,987.40 ريال
الربح المتوقع من قيمة المحفظة: -1,012.60 ريال
الفرق بين ربح الصفقات وربح المحفظة: 1,294.23 ريال

--- اختبارات التدقيق ---

                                      test  result
0               الربح يطابق تغير رأس المال   False
1  التراجع لا يتجاوز رأس المال بشكل مستحيل   False
2                       قيمة المحفظة موجبة    True

--- آخر 10 أيام من المحفظة ---

,date,cash_sar,market_value_sar,equity_sar,unrealized_pnl_sar,open_positions,open_risk_sar,peak_equity,drawdown_sar,peak_equity_corrected,drawdown_corrected
2057,2026-10-08,5381.643130,5043.112507,10424.755636,78.481354,3,126.833163,11504.215406,-1079.459770,11504.215406,-1079.459770
2058,2026-10-09,5381.643130,5041.837578,10423.480707,77.206425,3,126.833163,11504.215406,-1080.734699,11504.215406,-1080.734699
2059,2026-10-10,5381.643130,0.000000,5381.643130,0.000000,3,126.833163,11504.215406,-6122.572277,11504.215406,-6122.572277
2060,2026-10-11,5381.643130,0.000000,5381.643130,0.000000,3,126.833163,11504.215406,-6122.572277,11504.215406,-6122.572277
2061,2026-10-12,5336.908500,5089.274940,10426.183441,43.153173,3,130.756643,11504.215406,-1078.031966,11504.215406,-1078.031966
2062,2026-10-13,5336.908500,5101.162548,10438.071048,55.040780,3,130.756643,11504.215406,-1066.144358,11504.215406,-1066.144358
2063,2026-10-14,4042.681978,6305.624943,10348.306920,-33.430414,4,170.864478,11504.215406,-1155.908486,11504.215406,-1155.908486
2064,2026-10-15,4857.503811,5486.287422,10343.791234,-1.655068,3,134.129947,11504.215406,-1160.424173,11504.215406,-1160.424173
2065,2026-10-16,8987.404190,1287.974968,10275.379158,-4.958621,1,40.107834,11504.215406,-1228.836248,11504.215406,-1228.836248
2066,2026-10-17,8987.404190,0.000000,8987.404190,0.000000,1,40.107834,11504.215406,-2516.811216,11504.215406,-2516.811216

--- آخر 10 صفقات ---

,ticker,entry_date,exit_date,quantity,entry_price_local,exit_price_local,entry_value_sar,exit_value_sar,entry_fee_sar,exit_fee_sar,pnl_sar,exit_reason,holding_days
492,1180.SR,2026-08-11,2026-08-24,47,41.020500,42.930784,1927.963500,2017.746853,1.927963,2.017747,85.837643,هدف,10
493,AMZN,2026-08-14,2026-09-01,1,265.012445,252.623605,993.796668,947.338520,0.993797,0.947339,-48.399284,وقف خسارة,13
494,2222.SR,2026-08-20,2026-09-01,28,26.373181,26.021045,738.449057,728.589255,0.738449,0.728589,-11.326841,وقف خسارة,9
495,1180.SR,2026-09-01,2026-09-02,49,43.221601,42.279435,2117.858437,2071.692326,2.117858,2.071692,-50.355662,وقف خسارة,2
496,SPY,2026-08-18,2026-09-10,1,767.179313,755.977309,2876.922423,2834.914909,2.876922,2.834915,-47.719352,وقف خسارة,17
497,NVDA,2026-09-03,2026-09-14,1,225.880263,214.590938,847.050988,804.716016,0.847051,0.804716,-43.986738,وقف خسارة,7
498,AAPL,2026-09-15,2026-10-12,1,330.305085,340.799516,1238.644067,1277.998186,1.238644,1.277998,36.837476,خروج زمني,20
499,NVDA,2026-09-22,2026-10-15,1,226.963431,217.503326,851.112867,815.637471,0.851113,0.815637,-37.142146,وقف خسارة,18
500,SPY,2026-09-21,2026-10-16,1,766.633125,762.868375,2874.874219,2860.756406,2.874874,2.860756,-19.853443,خروج زمني,20
501,GOOGL,2026-10-12,2026-10-16,1,352.035915,339.540802,1320.134683,1273.278007,1.320135,1.273278,-49.450088,وقف خسارة,5

=================================================================
⚠️ توجد تناقضات تحتاج إلى تصحيح.
لا تبدئي التداول الحقيقي.
=================================================================

In [32]:
 # =====================================================================
# 🌧️ الودق AI — المرحلة 85C
# محاكاة محفظة موحدة وتصحيح حسابات المخاطر
# =====================================================================

!pip -q install yfinance

import pandas as pd
import numpy as np
import yfinance as yf
import math
import os
import warnings
from datetime import datetime

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------
# 1) إعداد المحفظة
# ---------------------------------------------------------------------

INITIAL_CAPITAL = 10000.0       # رأس المال بالريال
RISK_PER_TRADE = 50.0          # المخاطرة القصوى لكل صفقة
MAX_OPEN_RISK = 200.0           # أقصى مخاطر مفتوحة
FX_USD_SAR = 3.75              # تحويل الدولار إلى ريال
FEE_RATE = 0.001                # رسوم افتراضية 0.1%
SLIPPAGE = 0.0005               # انزلاق سعري 0.05%

START_DATE = "2021-01-01"

TICKERS = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY",
    "2222.SR", "1180.SR", "2010.SR",
    "BTC-USD"
]

# ---------------------------------------------------------------------
# 2) تحديد العملات
# ---------------------------------------------------------------------

def get_fx(ticker):
    if ticker.endswith(".SR"):
        return 1.0
    return FX_USD_SAR

# ---------------------------------------------------------------------
# 3) تحميل البيانات وحساب المؤشرات
# ---------------------------------------------------------------------

data = {}

print("=" * 70)
print("🌧️ المرحلة 85C — تحميل الأسعار والمؤشرات")
print("=" * 70)

for ticker in TICKERS:

    try:
        print("تحميل:", ticker)

        df = yf.download(
            ticker,
            start=START_DATE,
            auto_adjust=True,
            progress=False
        )

        if df.empty:
            print("⚠️ لا توجد بيانات:", ticker)
            continue

        # معالجة أعمدة Yahoo Finance
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        required = ["Open", "High", "Low", "Close"]

        if not all(c in df.columns for c in required):
            print("⚠️ أعمدة الأسعار غير مكتملة:", ticker)
            continue

        df = df[required].copy()

        df = df.dropna()
        df = df[~df.index.duplicated(keep="last")]
        df = df.sort_index()

        # المؤشرات الفنية
        df["SMA20"] = df["Close"].rolling(20).mean()
        df["SMA50"] = df["Close"].rolling(50).mean()

        delta = df["Close"].diff()

        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.rolling(14).mean()
        avg_loss = loss.rolling(14).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)

        df["RSI"] = 100 - (100 / (1 + rs))

        # MACD
        ema12 = df["Close"].ewm(span=12, adjust=False).mean()
        ema26 = df["Close"].ewm(span=26, adjust=False).mean()

        df["MACD"] = ema12 - ema26
        df["MACD_SIGNAL"] = df["MACD"].ewm(
            span=9, adjust=False
        ).mean()

        # ATR
        previous_close = df["Close"].shift(1)

        tr1 = df["High"] - df["Low"]
        tr2 = (df["High"] - previous_close).abs()
        tr3 = (df["Low"] - previous_close).abs()

        df["TR"] = pd.concat(
            [tr1, tr2, tr3], axis=1
        ).max(axis=1)

        df["ATR"] = df["TR"].rolling(14).mean()

        # إشارة الشراء
        df["BUY_SIGNAL"] = (
            (df["Close"] > df["SMA20"]) &
            (df["SMA20"] > df["SMA50"]) &
            (df["RSI"] >= 50) &
            (df["RSI"] <= 70) &
            (df["MACD"] > df["MACD_SIGNAL"])
        )

        df = df.dropna()

        if len(df) > 30:
            data[ticker] = df

    except Exception as e:
        print("⚠️ تعذر تحميل", ticker, ":", str(e))

if not data:
    raise ValueError("لم يتم تحميل أي بيانات صالحة.")

print("\nعدد الأصول المحملة:", len(data))

# ---------------------------------------------------------------------
# 4) تجهيز أيام التداول
# ---------------------------------------------------------------------

all_dates = sorted(
    set().union(*[set(df.index) for df in data.values()])
)

# توحيد التاريخ إلى تاريخ فقط
all_dates = sorted(
    set(pd.Timestamp(d).normalize() for d in all_dates)
)

# ---------------------------------------------------------------------
# 5) محاكاة المحفظة
# ---------------------------------------------------------------------

cash = INITIAL_CAPITAL

positions = {}
trades = []
daily_results = []

last_prices = {}

# ---------------------------------------------------------------------
# 6) حساب قيمة المراكز المفتوحة
# ---------------------------------------------------------------------

def current_market_value(date):

    total = 0.0

    for ticker, pos in positions.items():

        df = data[ticker]

        available = df.loc[df.index <= date]

        if available.empty:
            continue

        close_price = float(available["Close"].iloc[-1])

        fx = get_fx(ticker)

        total += (
            pos["quantity"] *
            close_price *
            fx
        )

    return total

# ---------------------------------------------------------------------
# 7) حساب المخاطر المفتوحة
# ---------------------------------------------------------------------

def current_open_risk():

    total = 0.0

    for ticker, pos in positions.items():

        fx = get_fx(ticker)

        risk = (
            pos["quantity"] *
            abs(pos["entry_price"] - pos["stop_price"]) *
            fx
        )

        total += risk

    return total

# ---------------------------------------------------------------------
# 8) المحاكاة اليومية
# ---------------------------------------------------------------------

print("\nبدء المحاكاة التاريخية...")

for i, date in enumerate(all_dates):

    # -------------------------------------------------------------
    # أ) إدارة الصفقات المفتوحة
    # -------------------------------------------------------------

    to_close = []

    for ticker, pos in list(positions.items()):

        df = data[ticker]

        if date not in df.index:
            continue

        row = df.loc[date]

        if isinstance(row, pd.DataFrame):
            row = row.iloc[-1]

        open_price = float(row["Open"])
        high_price = float(row["High"])
        low_price = float(row["Low"])
        close_price = float(row["Close"])

        exit_price = None
        exit_reason = None

        stop = pos["stop_price"]
        target = pos["target_price"]

        # إذا لمس الوقف والهدف في اليوم نفسه:
        # نفترض الوقف أولًا بصورة محافظة
        if low_price <= stop and high_price >= target:

            exit_price = stop * (1 - SLIPPAGE)
            exit_reason = "وقف خسارة - افتراض محافظ"

        elif low_price <= stop:

            exit_price = stop * (1 - SLIPPAGE)
            exit_reason = "وقف خسارة"

        elif high_price >= target:

            exit_price = target * (1 - SLIPPAGE)
            exit_reason = "هدف"

        else:

            pos["holding_days"] += 1

            # الخروج الزمني بعد 20 يوم تداول
            if pos["holding_days"] >= 20:

                exit_price = close_price * (1 - SLIPPAGE)
                exit_reason = "خروج زمني"

        # ---------------------------------------------------------
        # تنفيذ الخروج
        # ---------------------------------------------------------

        if exit_price is not None:

            quantity = pos["quantity"]
            fx = get_fx(ticker)

            entry_price = pos["entry_price"]

            entry_value_sar = (
                quantity * entry_price * fx
            )

            exit_value_sar = (
                quantity * exit_price * fx
            )

            entry_fee_sar = entry_value_sar * FEE_RATE
            exit_fee_sar = exit_value_sar * FEE_RATE

            pnl_sar = (
                exit_value_sar
                - entry_value_sar
                - entry_fee_sar
                - exit_fee_sar
            )

            # إعادة الأموال إلى النقد
            cash += exit_value_sar - exit_fee_sar

            trades.append({
                "ticker": ticker,
                "entry_date": pos["entry_date"],
                "exit_date": date,
                "quantity": quantity,
                "entry_price_local": entry_price,
                "exit_price_local": exit_price,
                "entry_value_sar": entry_value_sar,
                "exit_value_sar": exit_value_sar,
                "entry_fee_sar": entry_fee_sar,
                "exit_fee_sar": exit_fee_sar,
                "pnl_sar": pnl_sar,
                "exit_reason": exit_reason,
                "holding_days": pos["holding_days"]
            })

            to_close.append(ticker)

    # حذف المراكز المغلقة
    for ticker in to_close:
        del positions[ticker]

    # -------------------------------------------------------------
    # ب) فتح صفقات جديدة
    # -------------------------------------------------------------

    if i > 0:

        previous_date = all_dates[i - 1]

        # ترتيب ثابت للأصول لتجنب العشوائية
        for ticker in sorted(data.keys()):

            if ticker in positions:
                continue

            df = data[ticker]

            if date not in df.index:
                continue

            # نأخذ إشارة اليوم السابق فقط
            previous_data = df.loc[df.index <= previous_date]

            if previous_data.empty:
                continue

            prev_row = previous_data.iloc[-1]

            if not bool(prev_row["BUY_SIGNAL"]):
                continue

            row = df.loc[date]

            if isinstance(row, pd.DataFrame):
                row = row.iloc[-1]

            raw_open = float(row["Open"])

            if not np.isfinite(raw_open) or raw_open <= 0:
                continue

            fx = get_fx(ticker)

            # سعر الدخول مع الانزلاق
            entry_price = raw_open * (1 + SLIPPAGE)

            atr = float(prev_row["ATR"])

            if not np.isfinite(atr) or atr <= 0:
                continue

            # الوقف والهدف
            stop_price = entry_price - (1.5 * atr)

            risk_per_share_sar = (
                (entry_price - stop_price) * fx
            )

            if risk_per_share_sar <= 0:
                continue

            target_price = entry_price + (
                2 * (entry_price - stop_price)
            )

            # المخاطرة المتبقية
            open_risk = current_open_risk()

            remaining_risk = (
                MAX_OPEN_RISK - open_risk
            )

            if remaining_risk <= 0:
                continue

            # أقصى عدد أسهم حسب المخاطرة
            qty_by_risk = math.floor(
                min(
                    RISK_PER_TRADE,
                    remaining_risk
                ) / risk_per_share_sar
            )

            # أقصى عدد أسهم حسب النقد المتاح
            entry_value_per_share_sar = (
                entry_price * fx
            )

            cash_per_share = (
                entry_value_per_share_sar *
                (1 + FEE_RATE)
            )

            qty_by_cash = math.floor(
                cash / cash_per_share
            )

            quantity = min(
                qty_by_risk,
                qty_by_cash
            )

            if quantity <= 0:
                continue

            entry_value_sar = (
                quantity * entry_price * fx
            )

            entry_fee_sar = (
                entry_value_sar * FEE_RATE
            )

            required_cash = (
                entry_value_sar + entry_fee_sar
            )

            if required_cash > cash:
                continue

            # تنفيذ الشراء
            cash -= required_cash

            positions[ticker] = {
                "entry_date": date,
                "entry_price": entry_price,
                "stop_price": stop_price,
                "target_price": target_price,
                "quantity": quantity,
                "holding_days": 0
            }

            # ---------------------------------------------------------
            # ج) فحص الوقف والهدف في يوم الدخول
            # ---------------------------------------------------------

            high_price = float(row["High"])
            low_price = float(row["Low"])

            same_day_exit = None
            same_day_reason = None

            if low_price <= stop_price and high_price >= target_price:

                same_day_exit = stop_price * (1 - SLIPPAGE)
                same_day_reason = "وقف خسارة - افتراض محافظ"

            elif low_price <= stop_price:

                same_day_exit = stop_price * (1 - SLIPPAGE)
                same_day_reason = "وقف خسارة"

            elif high_price >= target_price:

                same_day_exit = target_price * (1 - SLIPPAGE)
                same_day_reason = "هدف"

            if same_day_exit is not None:

                pos = positions[ticker]

                exit_value_sar = (
                    quantity * same_day_exit * fx
                )

                exit_fee_sar = (
                    exit_value_sar * FEE_RATE
                )

                pnl_sar = (
                    exit_value_sar
                    - entry_value_sar
                    - entry_fee_sar
                    - exit_fee_sar
                )

                cash += (
                    exit_value_sar - exit_fee_sar
                )

                trades.append({
                    "ticker": ticker,
                    "entry_date": date,
                    "exit_date": date,
                    "quantity": quantity,
                    "entry_price_local": entry_price,
                    "exit_price_local": same_day_exit,
                    "entry_value_sar": entry_value_sar,
                    "exit_value_sar": exit_value_sar,
                    "entry_fee_sar": entry_fee_sar,
                    "exit_fee_sar": exit_fee_sar,
                    "pnl_sar": pnl_sar,
                    "exit_reason": same_day_reason,
                    "holding_days": 0
                })

                del positions[ticker]

    # -------------------------------------------------------------
    # د) حساب قيمة المحفظة نهاية اليوم
    # -------------------------------------------------------------

    market_value = current_market_value(date)

    equity = cash + market_value

    open_risk = current_open_risk()

    daily_results.append({
        "date": date,
        "cash_sar": cash,
        "market_value_sar": market_value,
        "equity_sar": equity,
        "open_positions": len(positions),
        "open_risk_sar": open_risk
    })

# ---------------------------------------------------------------------
# 9) إغلاق المراكز المفتوحة في نهاية الاختبار
# ---------------------------------------------------------------------

if len(all_dates) > 0:

    final_date = all_dates[-1]

    for ticker, pos in list(positions.items()):

        df = data[ticker]

        available = df.loc[df.index <= final_date]

        if available.empty:
            continue

        final_price = float(
            available["Close"].iloc[-1]
        )

        fx = get_fx(ticker)

        quantity = pos["quantity"]

        exit_price = final_price * (1 - SLIPPAGE)

        entry_value_sar = (
            quantity * pos["entry_price"] * fx
        )

        exit_value_sar = (
            quantity * exit_price * fx
        )

        entry_fee_sar = entry_value_sar * FEE_RATE
        exit_fee_sar = exit_value_sar * FEE_RATE

        pnl_sar = (
            exit_value_sar
            - entry_value_sar
            - entry_fee_sar
            - exit_fee_sar
        )

        cash += exit_value_sar - exit_fee_sar

        trades.append({
            "ticker": ticker,
            "entry_date": pos["entry_date"],
            "exit_date": final_date,
            "quantity": quantity,
            "entry_price_local": pos["entry_price"],
            "exit_price_local": exit_price,
            "entry_value_sar": entry_value_sar,
            "exit_value_sar": exit_value_sar,
            "entry_fee_sar": entry_fee_sar,
            "exit_fee_sar": exit_fee_sar,
            "pnl_sar": pnl_sar,
            "exit_reason": "نهاية الاختبار",
            "holding_days": pos["holding_days"]
        })

    positions.clear()

# ---------------------------------------------------------------------
# 10) بناء النتائج
# ---------------------------------------------------------------------

trades_df = pd.DataFrame(trades)
daily_df = pd.DataFrame(daily_results)

if daily_df.empty:
    raise ValueError("لم يتم إنشاء بيانات الأداء اليومي.")

daily_df["peak_equity"] = (
    daily_df["equity_sar"].cummax()
)

daily_df["drawdown_sar"] = (
    daily_df["equity_sar"] -
    daily_df["peak_equity"]
)

# ---------------------------------------------------------------------
# 11) حساب الأداء
# ---------------------------------------------------------------------

final_equity = float(cash)

total_pnl = final_equity - INITIAL_CAPITAL

if not trades_df.empty:

    winning_trades = trades_df[
        trades_df["pnl_sar"] > 0
    ]

    losing_trades = trades_df[
        trades_df["pnl_sar"] < 0
    ]

    gross_profit = winning_trades["pnl_sar"].sum()

    gross_loss = abs(
        losing_trades["pnl_sar"].sum()
    )

    profit_factor = (
        gross_profit / gross_loss
        if gross_loss > 0
        else np.nan
    )

    win_rate = (
        len(winning_trades) / len(trades_df)
    ) * 100

else:

    gross_profit = 0.0
    gross_loss = 0.0
    profit_factor = np.nan
    win_rate = 0.0

max_drawdown = float(
    daily_df["drawdown_sar"].min()
)

# ---------------------------------------------------------------------
# 12) حفظ الملفات
# ---------------------------------------------------------------------

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

trades_file = (
    f"/content/wadq_phase85C_trades_{timestamp}.csv"
)

daily_file = (
    f"/content/wadq_phase85C_daily_{timestamp}.csv"
)

summary_file = (
    f"/content/wadq_phase85C_summary_{timestamp}.csv"
)

trades_df.to_csv(
    trades_file,
    index=False,
    encoding="utf-8-sig"
)

daily_df.to_csv(
    daily_file,
    index=False,
    encoding="utf-8-sig"
)

summary_df = pd.DataFrame([{
    "initial_capital_sar": INITIAL_CAPITAL,
    "final_equity_sar": final_equity,
    "total_pnl_sar": total_pnl,
    "total_trades": len(trades_df),
    "win_rate_pct": win_rate,
    "gross_profit_sar": gross_profit,
    "gross_loss_sar": gross_loss,
    "profit_factor": profit_factor,
    "max_drawdown_sar": max_drawdown
}])

summary_df.to_csv(
    summary_file,
    index=False,
    encoding="utf-8-sig"
)

# ---------------------------------------------------------------------
# 13) عرض التقرير
# ---------------------------------------------------------------------

print("\n" + "=" * 70)
print("🌧️ الودق AI — المرحلة 85C")
print("تقرير المحفظة التاريخية")
print("=" * 70)

print(f"رأس المال الأولي: {INITIAL_CAPITAL:,.2f} ريال")
print(f"قيمة المحفظة النهائية: {final_equity:,.2f} ريال")
print(f"صافي الربح/الخسارة: {total_pnl:,.2f} ريال")
print(f"عدد الصفقات: {len(trades_df)}")
print(f"نسبة الصفقات الرابحة: {win_rate:.2f}%")
print(f"Profit Factor: {profit_factor:.4f}")
print(f"أقصى تراجع: {max_drawdown:,.2f} ريال")

print("\nملف الصفقات:")
print(trades_file)

print("\nملف الأداء اليومي:")
print(daily_file)

print("\nملف الملخص:")
print(summary_file)

print("\n⚠️ هذه محاكاة تاريخية وليست توصية بشراء أو بيع.")
print("⚠️ لا تبدئي التداول الحقيقي قبل مراجعة النتائج واختبارها على بيانات منفصلة.")

======================================================================
🌧️ المرحلة 85C — تحميل الأسعار والمؤشرات
======================================================================
تحميل: NVDA
تحميل: TSLA
تحميل: AAPL
تحميل: MSFT
تحميل: AMZN
تحميل: GOOGL
تحميل: META
تحميل: QQQ
تحميل: SPY
تحميل: 2222.SR
تحميل: 1180.SR
تحميل: 2010.SR
تحميل: BTC-USD

عدد الأصول المحملة: 13

بدء المحاكاة التاريخية...

======================================================================
🌧️ الودق AI — المرحلة 85C
تقرير المحفظة التاريخية
======================================================================
رأس المال الأولي: 10,000.00 ريال
قيمة المحفظة النهائية: 10,198.21 ريال
صافي الربح/الخسارة: 198.21 ريال
عدد الصفقات: 461
نسبة الصفقات الرابحة: 39.05%
Profit Factor: 1.0168
أقصى تراجع: -1,885.55 ريال

ملف الصفقات:
/content/wadq_phase85C_trades_20261017_162536.csv

ملف الأداء اليومي:
/content/wadq_phase85C_daily_20261017_162536.csv

ملف الملخص:
/content/wadq_phase85C_summary_20261017_162536.csv

⚠️ هذه محاكاة تاريخية وليست توصية بشراء أو بيع.
⚠️ لا تبدئي التداول الحقيقي قبل مراجعة النتائج واختبارها على بيانات منفصلة.

In [3]:
# 🌧️ الودق AI — المرحلة 85C
# فحص ملفات المرحلة 85

import os
import glob

print("=" * 60)
print("🌧️ المرحلة 85C — فحص ملفات المحاكاة")
print("=" * 60)

files = glob.glob("/content/wadq_phase85_*")

if files:
    for f in files:
        print(f"📄 {os.path.basename(f)}")
        print(f"   الحجم: {os.path.getsize(f):,} bytes")
else:
    print("⚠️ لم يتم العثور على ملفات المرحلة 85")

============================================================
🌧️ المرحلة 85C — فحص ملفات المحاكاة
============================================================
⚠️ لم يتم العثور على ملفات المرحلة 85

In [27]:
# 🌧️ الودق AI — المرحلة 85C
# فحص البيانات المحملة قبل إعادة بناء المحفظة

print("=" * 60)
print("🌧️ الودق AI — المرحلة 85C")
print("=" * 60)

if "data" not in globals():

    print("⚠️ بيانات الأسعار غير موجودة في الذاكرة.")
    print("سنحتاج إلى إعادة تحميل البيانات التاريخية.")

else:

    print("عدد الأصول المحملة:", len(data))

    for ticker, df in data.items():

        print(
            ticker,
            "| عدد الصفوف:", len(df),
            "| بداية البيانات:", df.index.min(),
            "| نهاية البيانات:", df.index.max()
        )

    print("\nتم الفحص.")

============================================================
🌧️ الودق AI — المرحلة 85C
============================================================
عدد الأصول المحملة: 13
NVDA | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
TSLA | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
AAPL | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
MSFT | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
AMZN | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
GOOGL | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
META | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
QQQ | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
SPY | عدد الصفوف: 1405 | بداية البيانات: 2021-03-16 00:00:00 | نهاية البيانات: 2026-10-16 00:00:00
2222.SR | عدد الصفوف: 1393 | بداية البيانات: 2021-03-11 00:00:00 | نهاية البيانات: 2026-10-15 00:00:00
1180.SR | عدد الصفوف: 1392 | بداية البيانات: 2021-03-11 00:00:00 | نهاية البيانات: 2026-10-15 00:00:00
2010.SR | عدد الصفوف: 1392 | بداية البيانات: 2021-03-11 00:00:00 | نهاية البيانات: 2026-10-15 00:00:00
BTC-USD | عدد الصفوف: 2067 | بداية البيانات: 2021-02-19 00:00:00 | نهاية البيانات: 2026-10-17 00:00:00

تم الفحص.

In [ ]:
# WADQ AI - Excel File Search

import os
from google.colab import drive

drive.mount('/content/drive')

search_path = '/content/drive/MyDrive'

excel_files = []

for root, dirs, files in os.walk(search_path):
    for file in files:
        if file.lower().endswith(('.xlsx', '.xls')):
            excel_files.append(os.path.join(root, file))

print("=" * 60)
print("WADQ AI - Excel Files")
print("=" * 60)

if excel_files:
    print("Excel files found:", len(excel_files))

    for i, path in enumerate(excel_files, 1):
        print(f"\n{i}. {os.path.basename(path)}")
        print(path)
else:
    print("No Excel files found in Google Drive.")

Mounted at /content/drive
============================================================
WADQ AI - Excel Files
============================================================
No Excel files found in Google Drive.

In [5]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 85C
# محاكاة محفظة تاريخية مستقلة
# تصحيح حساب الأرباح والمخاطر وحفظ النتائج
# =====================================================================

!pip -q install yfinance

import pandas as pd
import numpy as np
import yfinance as yf
import math
import os
import warnings
from datetime import datetime
from google.colab import drive

warnings.filterwarnings("ignore")

# =====================================================================
# 1) ربط Google Drive
# =====================================================================

drive.mount("/content/drive")

# مجلد مستقل، لا يحذف ملفات المشروع القديمة
PHASE85C_FOLDER = (
    "/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C"
)

os.makedirs(PHASE85C_FOLDER, exist_ok=True)

# =====================================================================
# 2) إعداد المحفظة
# =====================================================================

PHASE85C_INITIAL_CAPITAL = 10000.0
PHASE85C_RISK_PER_TRADE = 50.0
PHASE85C_MAX_OPEN_RISK = 200.0

PHASE85C_FX_USD_SAR = 3.75
PHASE85C_FEE_RATE = 0.001
PHASE85C_SLIPPAGE = 0.0005

PHASE85C_START_DATE = "2021-01-01"

# الأسهم الأصلية + الأسهم الجديدة
PHASE85C_TICKERS = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY",
    "2222.SR", "1180.SR", "2010.SR",
    "BTC-USD",

    # الأسهم الإضافية
    "XYZ", "AEO", "WRD", "INMB",
    "LCID", "TOST", "INO"
]

# إزالة التكرار
PHASE85C_TICKERS = list(
    dict.fromkeys(PHASE85C_TICKERS)
)

def phase85c_fx(ticker):
    if ticker.endswith(".SR"):
        return 1.0
    return PHASE85C_FX_USD_SAR

print("=" * 70)
print("🌧️ الودق AI — المرحلة 85C")
print("محاكاة مستقلة")
print("=" * 70)

print("رأس المال:", PHASE85C_INITIAL_CAPITAL)
print("عدد الأسهم المطلوب:", len(PHASE85C_TICKERS))

# =====================================================================
# 3) تحميل البيانات
# =====================================================================

phase85c_data = {}

for ticker in PHASE85C_TICKERS:

    try:

        print("تحميل:", ticker)

        df = yf.download(
            ticker,
            start=PHASE85C_START_DATE,
            auto_adjust=True,
            progress=False
        )

        if df.empty:
            print("⚠️ لا توجد بيانات:", ticker)
            continue

        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        required = ["Open", "High", "Low", "Close"]

        if not all(c in df.columns for c in required):
            print("⚠️ أعمدة الأسعار غير مكتملة:", ticker)
            continue

        df = df[required].copy()

        df = df.dropna()
        df = df[~df.index.duplicated(keep="last")]
        df = df.sort_index()

        # توحيد التاريخ
        df.index = pd.to_datetime(df.index).normalize()

        # المؤشرات الفنية
        df["SMA20"] = df["Close"].rolling(20).mean()
        df["SMA50"] = df["Close"].rolling(50).mean()

        delta = df["Close"].diff()

        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.rolling(14).mean()
        avg_loss = loss.rolling(14).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)

        df["RSI"] = 100 - (100 / (1 + rs))

        # MACD
        ema12 = df["Close"].ewm(
            span=12, adjust=False
        ).mean()

        ema26 = df["Close"].ewm(
            span=26, adjust=False
        ).mean()

        df["MACD"] = ema12 - ema26

        df["MACD_SIGNAL"] = df["MACD"].ewm(
            span=9, adjust=False
        ).mean()

        # ATR
        previous_close = df["Close"].shift(1)

        tr1 = df["High"] - df["Low"]
        tr2 = (df["High"] - previous_close).abs()
        tr3 = (df["Low"] - previous_close).abs()

        df["TR"] = pd.concat(
            [tr1, tr2, tr3], axis=1
        ).max(axis=1)

        df["ATR"] = df["TR"].rolling(14).mean()

        # إشارة الشراء
        df["BUY_SIGNAL"] = (
            (df["Close"] > df["SMA20"]) &
            (df["SMA20"] > df["SMA50"]) &
            (df["RSI"] >= 50) &
            (df["RSI"] <= 70) &
            (df["MACD"] > df["MACD_SIGNAL"])
        )

        df = df.dropna()

        if len(df) > 30:
            phase85c_data[ticker] = df

    except Exception as e:

        print("⚠️ تعذر تحميل:", ticker)
        print(str(e))

if not phase85c_data:
    raise ValueError("لم يتم تحميل أي بيانات صالحة.")

print("\nعدد الأصول المحملة:", len(phase85c_data))

print("\nالأصول التي تم تحميلها:")
print(list(phase85c_data.keys()))

# =====================================================================
# 4) تجهيز أيام التداول
# =====================================================================

phase85c_dates = sorted(
    set().union(
        *[set(df.index) for df in phase85c_data.values()]
    )
)

phase85c_dates = sorted(
    set(pd.Timestamp(d).normalize() for d in phase85c_dates)
)

# =====================================================================
# 5) إنشاء محفظة مستقلة
# =====================================================================

phase85c_cash = PHASE85C_INITIAL_CAPITAL

phase85c_positions = {}
phase85c_trades = []
phase85c_daily = []

# =====================================================================
# 6) قيمة المراكز المفتوحة
# =====================================================================

def phase85c_market_value(date):

    total = 0.0

    for ticker, pos in phase85c_positions.items():

        df = phase85c_data[ticker]

        available = df.loc[df.index <= date]

        if available.empty:
            continue

        close_price = float(
            available["Close"].iloc[-1]
        )

        total += (
            pos["quantity"] *
            close_price *
            phase85c_fx(ticker)
        )

    return total

# =====================================================================
# 7) حساب المخاطر المفتوحة
# =====================================================================

def phase85c_open_risk():

    total = 0.0

    for ticker, pos in phase85c_positions.items():

        fx = phase85c_fx(ticker)

        risk = (
            pos["quantity"] *
            abs(pos["entry_price"] - pos["stop_price"]) *
            fx
        )

        total += risk

    return total

# =====================================================================
# 8) دالة إغلاق الصفقة
# =====================================================================

def phase85c_close_trade(
    ticker,
    pos,
    date,
    exit_price,
    exit_reason
):

    global phase85c_cash

    fx = phase85c_fx(ticker)

    quantity = pos["quantity"]

    entry_value = (
        quantity *
        pos["entry_price"] *
        fx
    )

    exit_value = (
        quantity *
        exit_price *
        fx
    )

    entry_fee = entry_value * PHASE85C_FEE_RATE
    exit_fee = exit_value * PHASE85C_FEE_RATE

    pnl = (
        exit_value
        - entry_value
        - entry_fee
        - exit_fee
    )

    # إضافة حصيلة البيع بعد رسوم الخروج
    phase85c_cash += exit_value - exit_fee

    phase85c_trades.append({

        "ticker": ticker,

        "entry_date": pos["entry_date"],
        "exit_date": date,

        "quantity": quantity,

        "entry_price_local": pos["entry_price"],
        "exit_price_local": exit_price,

        "entry_value_sar": entry_value,
        "exit_value_sar": exit_value,

        "entry_fee_sar": entry_fee,
        "exit_fee_sar": exit_fee,

        "pnl_sar": pnl,

        "exit_reason": exit_reason,

        "holding_days": pos["holding_days"]

    })

# =====================================================================
# 9) المحاكاة اليومية
# =====================================================================

print("\nبدء المحاكاة التاريخية...")

for i, date in enumerate(phase85c_dates):

    # ---------------------------------------------------------------
    # أ) إدارة الصفقات المفتوحة
    # ---------------------------------------------------------------

    to_close = []

    for ticker, pos in list(phase85c_positions.items()):

        df = phase85c_data[ticker]

        if date not in df.index:
            continue

        row = df.loc[date]

        if isinstance(row, pd.DataFrame):
            row = row.iloc[-1]

        high_price = float(row["High"])
        low_price = float(row["Low"])
        close_price = float(row["Close"])

        stop = pos["stop_price"]
        target = pos["target_price"]

        exit_price = None
        exit_reason = None

        # إذا لمس الوقف والهدف في اليوم نفسه:
        # افتراض الوقف أولًا بصورة محافظة
        if low_price <= stop and high_price >= target:

            exit_price = stop * (
                1 - PHASE85C_SLIPPAGE
            )

            exit_reason = "وقف خسارة - افتراض محافظ"

        elif low_price <= stop:

            exit_price = stop * (
                1 - PHASE85C_SLIPPAGE
            )

            exit_reason = "وقف خسارة"

        elif high_price >= target:

            exit_price = target * (
                1 - PHASE85C_SLIPPAGE
            )

            exit_reason = "هدف"

        else:

            pos["holding_days"] += 1

            if pos["holding_days"] >= 20:

                exit_price = close_price * (
                    1 - PHASE85C_SLIPPAGE
                )

                exit_reason = "خروج زمني"

        # تنفيذ الخروج
        if exit_price is not None:

            phase85c_close_trade(
                ticker,
                pos,
                date,
                exit_price,
                exit_reason
            )

            to_close.append(ticker)

    # حذف المراكز المغلقة
    for ticker in to_close:
        del phase85c_positions[ticker]

    # ---------------------------------------------------------------
    # ب) فتح صفقات جديدة
    # ---------------------------------------------------------------

    if i > 0:

        previous_date = phase85c_dates[i - 1]

        for ticker in sorted(phase85c_data.keys()):

            if ticker in phase85c_positions:
                continue

            df = phase85c_data[ticker]

            if date not in df.index:
                continue

            previous_data = df.loc[
                df.index <= previous_date
            ]

            if previous_data.empty:
                continue

            prev_row = previous_data.iloc[-1]

            # إشارة اليوم السابق فقط
            if not bool(prev_row["BUY_SIGNAL"]):
                continue

            row = df.loc[date]

            if isinstance(row, pd.DataFrame):
                row = row.iloc[-1]

            raw_open = float(row["Open"])

            if not np.isfinite(raw_open) or raw_open <= 0:
                continue

            fx = phase85c_fx(ticker)

            entry_price = raw_open * (
                1 + PHASE85C_SLIPPAGE
            )

            atr = float(prev_row["ATR"])

            if not np.isfinite(atr) or atr <= 0:
                continue

            # الوقف والهدف
            stop_price = entry_price - (1.5 * atr)

            risk_per_share = (
                (entry_price - stop_price) * fx
            )

            if risk_per_share <= 0:
                continue

            target_price = entry_price + (
                2 * (entry_price - stop_price)
            )

            # ميزانية المخاطر المتبقية
            open_risk = phase85c_open_risk()

            remaining_risk = (
                PHASE85C_MAX_OPEN_RISK - open_risk
            )

            if remaining_risk <= 0:
                continue

            risk_budget = min(
                PHASE85C_RISK_PER_TRADE,
                remaining_risk
            )

            qty_by_risk = math.floor(
                risk_budget / risk_per_share
            )

            # حساب الكمية حسب النقد المتاح
            cash_per_share = (
                entry_price * fx *
                (1 + PHASE85C_FEE_RATE)
            )

            qty_by_cash = math.floor(
                phase85c_cash / cash_per_share
            )

            quantity = min(
                qty_by_risk,
                qty_by_cash
            )

            if quantity <= 0:
                continue

            entry_value = (
                quantity * entry_price * fx
            )

            entry_fee = (
                entry_value * PHASE85C_FEE_RATE
            )

            required_cash = entry_value + entry_fee

            if required_cash > phase85c_cash:
                continue

            # تنفيذ الشراء
            phase85c_cash -= required_cash

            phase85c_positions[ticker] = {

                "entry_date": date,
                "entry_price": entry_price,

                "stop_price": stop_price,
                "target_price": target_price,

                "quantity": quantity,

                "holding_days": 0

            }

            # -----------------------------------------------------------
            # ج) فحص الوقف والهدف في يوم الدخول
            # -----------------------------------------------------------

            high_price = float(row["High"])
            low_price = float(row["Low"])

            same_day_exit = None
            same_day_reason = None

            if low_price <= stop_price and high_price >= target_price:

                same_day_exit = stop_price * (
                    1 - PHASE85C_SLIPPAGE
                )

                same_day_reason = "وقف خسارة - افتراض محافظ"

            elif low_price <= stop_price:

                same_day_exit = stop_price * (
                    1 - PHASE85C_SLIPPAGE
                )

                same_day_reason = "وقف خسارة"

            elif high_price >= target_price:

                same_day_exit = target_price * (
                    1 - PHASE85C_SLIPPAGE
                )

                same_day_reason = "هدف"

            if same_day_exit is not None:

                pos = phase85c_positions[ticker]

                phase85c_close_trade(
                    ticker,
                    pos,
                    date,
                    same_day_exit,
                    same_day_reason
                )

                del phase85c_positions[ticker]

    # ---------------------------------------------------------------
    # د) تسجيل قيمة المحفظة نهاية اليوم
    # ---------------------------------------------------------------

    market_value = phase85c_market_value(date)

    equity = phase85c_cash + market_value

    phase85c_daily.append({

        "date": date,

        "cash_sar": phase85c_cash,

        "market_value_sar": market_value,

        "equity_sar": equity,

        "open_positions": len(phase85c_positions),

        "open_risk_sar": phase85c_open_risk()

    })

# =====================================================================
# 10) إغلاق المراكز المفتوحة في نهاية الاختبار
# =====================================================================

if len(phase85c_dates) > 0:

    final_date = phase85c_dates[-1]

    for ticker, pos in list(phase85c_positions.items()):

        df = phase85c_data[ticker]

        available = df.loc[df.index <= final_date]

        if available.empty:
            continue

        final_price = float(
            available["Close"].iloc[-1]
        )

        exit_price = final_price * (
            1 - PHASE85C_SLIPPAGE
        )

        phase85c_close_trade(
            ticker,
            pos,
            final_date,
            exit_price,
            "نهاية الاختبار"
        )

    phase85c_positions.clear()

# =====================================================================
# 11) بناء النتائج
# =====================================================================

phase85c_trades_df = pd.DataFrame(
    phase85c_trades
)

phase85c_daily_df = pd.DataFrame(
    phase85c_daily
)

if phase85c_daily_df.empty:
    raise ValueError("لم يتم إنشاء بيانات الأداء اليومي.")

# تحديث آخر يوم بعد إغلاق المراكز
phase85c_daily_df.loc[
    phase85c_daily_df.index[-1],
    "cash_sar"
] = phase85c_cash

phase85c_daily_df.loc[
    phase85c_daily_df.index[-1],
    "market_value_sar"
] = 0.0

phase85c_daily_df.loc[
    phase85c_daily_df.index[-1],
    "equity_sar"
] = phase85c_cash

# حساب التراجع
phase85c_daily_df["peak_equity"] = (
    phase85c_daily_df["equity_sar"].cummax()
)

phase85c_daily_df["drawdown_sar"] = (
    phase85c_daily_df["equity_sar"]
    - phase85c_daily_df["peak_equity"]
)

# =====================================================================
# 12) حساب الأداء
# =====================================================================

phase85c_final_equity = float(
    phase85c_cash
)

phase85c_total_pnl = (
    phase85c_final_equity
    - PHASE85C_INITIAL_CAPITAL
)

if not phase85c_trades_df.empty:

    winners = phase85c_trades_df[
        phase85c_trades_df["pnl_sar"] > 0
    ]

    losers = phase85c_trades_df[
        phase85c_trades_df["pnl_sar"] < 0
    ]

    phase85c_gross_profit = float(
        winners["pnl_sar"].sum()
    )

    phase85c_gross_loss = abs(
        float(losers["pnl_sar"].sum())
    )

    phase85c_profit_factor = (
        phase85c_gross_profit / phase85c_gross_loss
        if phase85c_gross_loss > 0
        else np.nan
    )

    phase85c_win_rate = (
        len(winners) / len(phase85c_trades_df)
    ) * 100

else:

    phase85c_gross_profit = 0.0
    phase85c_gross_loss = 0.0

    phase85c_profit_factor = np.nan

    phase85c_win_rate = 0.0

phase85c_max_drawdown = float(
    phase85c_daily_df["drawdown_sar"].min()
)

# =====================================================================
# 13) حفظ الملفات في Google Drive
# =====================================================================

phase85c_timestamp = datetime.now().strftime(
    "%Y%m%d_%H%M%S"
)

phase85c_trades_file = os.path.join(
    PHASE85C_FOLDER,
    f"wadq_85C_trades_{phase85c_timestamp}.csv"
)

phase85c_daily_file = os.path.join(
    PHASE85C_FOLDER,
    f"wadq_85C_daily_{phase85c_timestamp}.csv"
)

phase85c_summary_file = os.path.join(
    PHASE85C_FOLDER,
    f"wadq_85C_summary_{phase85c_timestamp}.csv"
)

phase85c_trades_df.to_csv(
    phase85c_trades_file,
    index=False,
    encoding="utf-8-sig"
)

phase85c_daily_df.to_csv(
    phase85c_daily_file,
    index=False,
    encoding="utf-8-sig"
)

phase85c_summary_df = pd.DataFrame([{

    "initial_capital_sar": PHASE85C_INITIAL_CAPITAL,

    "final_equity_sar": phase85c_final_equity,

    "total_pnl_sar": phase85c_total_pnl,

    "total_trades": len(phase85c_trades_df),

    "win_rate_pct": phase85c_win_rate,

    "gross_profit_sar": phase85c_gross_profit,

    "gross_loss_sar": phase85c_gross_loss,

    "profit_factor": phase85c_profit_factor,

    "max_drawdown_sar": phase85c_max_drawdown

}])

phase85c_summary_df.to_csv(
    phase85c_summary_file,
    index=False,
    encoding="utf-8-sig"
)

# =====================================================================
# 14) التقرير النهائي
# =====================================================================

print("\n" + "=" * 70)
print("🌧️ الودق AI — المرحلة 85C")
print("تقرير المحاكاة التاريخية")
print("=" * 70)

print(
    f"رأس المال الأولي: "
    f"{PHASE85C_INITIAL_CAPITAL:,.2f} ريال"
)

print(
    f"قيمة المحفظة النهائية: "
    f"{phase85c_final_equity:,.2f} ريال"
)

print(
    f"صافي الربح/الخسارة: "
    f"{phase85c_total_pnl:,.2f} ريال"
)

print(
    f"عدد الصفقات: "
    f"{len(phase85c_trades_df)}"
)

print(
    f"نسبة الصفقات الرابحة: "
    f"{phase85c_win_rate:.2f}%"
)

print(
    f"Profit Factor: "
    f"{phase85c_profit_factor}"
)

print(
    f"أقصى تراجع: "
    f"{phase85c_max_drawdown:,.2f} ريال"
)

print("\n📁 تم حفظ النتائج في:")
print(PHASE85C_FOLDER)

print("\nملف الصفقات:")
print(phase85c_trades_file)

print("\nملف الأداء اليومي:")
print(phase85c_daily_file)

print("\nملف الملخص:")
print(phase85c_summary_file)

print("\n⚠️ هذه محاكاة تاريخية وليست توصية بشراء أو بيع.")

Mounted at /content/drive
======================================================================
🌧️ الودق AI — المرحلة 85C
محاكاة مستقلة
======================================================================
رأس المال: 10000.0
عدد الأسهم المطلوب: 20
تحميل: NVDA
تحميل: TSLA
تحميل: AAPL
تحميل: MSFT
تحميل: AMZN
تحميل: GOOGL
تحميل: META
تحميل: QQQ
تحميل: SPY
تحميل: 2222.SR
تحميل: 1180.SR
تحميل: 2010.SR
تحميل: BTC-USD
تحميل: XYZ
تحميل: AEO
تحميل: WRD
تحميل: INMB
تحميل: LCID
تحميل: TOST
تحميل: INO

عدد الأصول المحملة: 20

الأصول التي تم تحميلها:
['NVDA', 'TSLA', 'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'QQQ', 'SPY', '2222.SR', '1180.SR', '2010.SR', 'BTC-USD', 'XYZ', 'AEO', 'WRD', 'INMB', 'LCID', 'TOST', 'INO']

بدء المحاكاة التاريخية...

======================================================================
🌧️ الودق AI — المرحلة 85C
تقرير المحاكاة التاريخية
======================================================================
رأس المال الأولي: 10,000.00 ريال
قيمة المحفظة النهائية: 8,659.76 ريال
صافي الربح/الخسارة: -1,340.24 ريال
عدد الصفقات: 612
نسبة الصفقات الرابحة: 36.27%
Profit Factor: 0.9146741129530881
أقصى تراجع: -2,838.03 ريال

📁 تم حفظ النتائج في:
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C

ملف الصفقات:
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_trades_20261017_213918.csv

ملف الأداء اليومي:
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_daily_20261017_213918.csv

ملف الملخص:
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_summary_20261017_213918.csv

⚠️ هذه محاكاة تاريخية وليست توصية بشراء أو بيع.

In [7]:
from getpass import getpass

TELEGRAM_BOT_TOKEN = getpass("أدخلي رمز بوت الودق الجديد: ")

KeyboardInterrupt: Interrupted by user

In [1]:
import requests
from getpass import getpass

TELEGRAM_BOT_TOKEN = getpass("أدخلي رمز البوت الجديد: ")

url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"
response = requests.get(url, timeout=30)

print(response.json())

أدخلي رمز البوت الجديد: ··········
{'ok': False, 'error_code': 401, 'description': 'Unauthorized'}

In [5]:
TELEGRAM_BOT_TOKEN = getpass("أدخلي رمز بوت الودق الجديد: ")

أدخلي رمز بوت الودق الجديد: ··········

In [6]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

url = f"https://api.telegram.org/bot{token}/getMe"

try:
    response = requests.get(url, timeout=20)
    print(response.status_code)
    print(response.json())
except Exception as e:
    print("خطأ في الاتصال:", e)

أدخلي رمز البوت الجديد: ··········
404
{'ok': False, 'error_code': 404, 'description': 'Not Found'}

In [11]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

url = f"https://api.telegram.org/bot{token}/getMe"

try:
    response = requests.get(url, timeout=20)
    print(response.status_code)
    print(response.json())
except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت الجديد: ··········
200
{'ok': True, 'result': {'id': 8658801654, 'is_bot': True, 'first_name': 'الودق اي اي لتوصيات', 'username': 'NajlaHadi1414_bot', 'can_join_groups': True, 'can_read_all_group_messages': False, 'supports_inline_queries': False, 'supports_guest_queries': False, 'can_connect_to_business': False, 'has_main_web_app': False, 'has_topics_enabled': False, 'allows_users_to_create_topics': False, 'can_manage_bots': False, 'supports_join_request_queries': False}}

In [12]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

url = f"https://api.telegram.org/bot{token}/getMe"

try:
    response = requests.get(url, timeout=20)
    print(response.status_code)
    print(response.json())
except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت الجديد: ··········
200
{'ok': True, 'result': {'id': 8658801654, 'is_bot': True, 'first_name': 'الودق اي اي لتوصيات', 'username': 'NajlaHadi1414_bot', 'can_join_groups': True, 'can_read_all_group_messages': False, 'supports_inline_queries': False, 'supports_guest_queries': False, 'can_connect_to_business': False, 'has_main_web_app': False, 'has_topics_enabled': False, 'allows_users_to_create_topics': False, 'can_manage_bots': False, 'supports_join_request_queries': False}}

In [13]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

url = f"https://api.telegram.org/bot{token}/getUpdates"
response = requests.get(url, timeout=20)
data = response.json()

if data.get("ok"):
    for update in data.get("result", []):
        message = update.get("message", {})
        chat = message.get("chat", {})
        print("Chat ID:", chat.get("id"))
        print("الرسالة:", message.get("text"))
else:
    print("خطأ:", data)

أدخلي رمز البوت الجديد: ··········
Chat ID: 410906720
الرسالة: الو

In [ ]:
import os

base = "/content/drive/MyDrive"

print("=== WADQ AI BACKUP FILES ===")

for root, dirs, files in os.walk(base):

    folder_name = os.path.basename(root)

    if "احتياطية" in folder_name or "نسخة" in folder_name:

        print("\nBACKUP FOLDER:")
        print(root)

        for file in files:
            path = os.path.join(root, file)
            size = os.path.getsize(path)

            print(f"FILE: {file}")
            print(f"SIZE: {size} bytes")
            print("-" * 40)

=== WADQ AI BACKUP FILES ===

BACKUP FOLDER:
/content/drive/MyDrive/الودق_AI_نسخة_احتياطية

In [14]:
import requests
from getpass import getpass

# أدخلي رمز البوت الجديد
token = getpass("أدخلي رمز بوت الودق: ").strip()

# رقم المحادثة الذي ظهر لك في كولاب
chat_id = 4109066720

# رسالة اختبار
message = "🌧️ الودق AI\nتم الاتصال بنجاح، وجاهز لإرسال التوصيات."

url = f"https://api.telegram.org/bot{token}/sendMessage"

response = requests.post(
    url,
    data={
        "chat_id": chat_id,
        "text": message
    },
    timeout=20
)

print(response.status_code)
print(response.json())

أدخلي رمز بوت الودق: ··········
400
{'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'}

In [15]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

url = f"https://api.telegram.org/bot{token}/getUpdates"

response = requests.get(url, timeout=20)
data = response.json()

print("حالة الاتصال:", response.status_code)

if data.get("ok"):
    for update in data.get("result", []):
        message = update.get("message", {})
        chat = message.get("chat", {})

        print("Chat ID:", chat.get("id"))
        print("الرسالة:", message.get("text"))
else:
    print("تفاصيل الخطأ:", data)

أدخلي رمز البوت الجديد: ··········
حالة الاتصال: 200
Chat ID: 410906720
الرسالة: الو

In [16]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

url = f"https://api.telegram.org/bot{token}/getWebhookInfo"

try:
    response = requests.get(url, timeout=20)
    print("حالة الاتصال:", response.status_code)
    print(response.json())
except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت الجديد: ··········
حالة الاتصال: 200
{'ok': True, 'result': {'url': '', 'has_custom_certificate': False, 'pending_update_count': 1}}

In [17]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()
chat_id = "4109066720"

url = f"https://api.telegram.org/bot{token}/sendMessage"

response = requests.post(
    url,
    data={
        "chat_id": chat_id,
        "text": "🌧️ اختبار إرسال من الودق AI\nإذا وصلتك هذه الرسالة، فالاتصال يعمل بنجاح."
    },
    timeout=20
)

print("حالة الإرسال:", response.status_code)
print(response.json())import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()
chat_id = "4109066720"

url = f"https://api.telegram.org/bot{token}/sendMessage"

response = requests.post(
    url,
    data={
        "chat_id": chat_id,
        "text": "🌧️ اختبار إرسال من الودق AI\nإذا وصلتك هذه الرسالة، فالاتصال يعمل بنجاح."
    },
    timeout=20
)

print("حالة الإرسال:", response.status_code)
print(response.json())

SyntaxError: invalid syntax (2981169993.py, line 19)

In [18]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()
chat_id = "4109066720"

url = f"https://api.telegram.org/bot{token}/sendMessage"

try:
    response = requests.post(
        url,
        data={
            "chat_id": chat_id,
            "text": "🌧️ اختبار إرسال من الودق AI\nإذا وصلتك هذه الرسالة، فالاتصال يعمل بنجاح."
        },
        timeout=20
    )

    print("حالة الإرسال:", response.status_code)
    print(response.json())

except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت الجديد: ··········
حالة الإرسال: 400
{'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'}

In [11]:
import os

ROOT = "/content/drive/MyDrive"

print("=" * 60)
print("🌧️ الودق AI — البحث عن ملف المرحلة 69")
print("=" * 60)

target = "الودق_AI_المرحلة_69.xlsx"

found = []

for root, dirs, files in os.walk(ROOT):

    if target in files:
        found.append(os.path.join(root, target))

if found:

    print("\n✅ تم العثور على الملف:")

    for path in found:
        print(path)

else:

    print("\n⚠️ لم يتم العثور على ملف المرحلة 69 بالاسم المحدد.")

    print("\nملفات Excel الموجودة في Google Drive:")

    count = 0

    for root, dirs, files in os.walk(ROOT):

        for file in files:

            if file.endswith((".xlsx", ".xls")):

                print(os.path.join(root, file))
                count += 1

    if count == 0:
        print("لم يتم العثور على أي ملف Excel.")

============================================================
🌧️ الودق AI — البحث عن ملف المرحلة 69
============================================================

✅ تم العثور على الملف:
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_69.xlsx

In [ ]:
import os

backup_path = "/content/drive/MyDrive/نسخة احتياطية - الودق AI"

print("=== BACKUP CONTENTS ===")

if os.path.exists(backup_path):
    items = os.listdir(backup_path)

    if items:
        for item in items:
            full_path = os.path.join(backup_path, item)

            if os.path.isfile(full_path):
                size = os.path.getsize(full_path)
                print(f"FILE: {item} | SIZE: {size} bytes")
            else:
                print(f"FOLDER: {item}")
    else:
        print("BACKUP FOLDER IS EMPTY")
else:
    print("BACKUP PATH NOT FOUND")

=== BACKUP CONTENTS ===
BACKUP PATH NOT FOUND

In [ ]:
import os

base = "/content/drive/MyDrive"

print("=" * 60)
print("WADQ AI - SEARCH BACKUP FOLDERS")
print("=" * 60)

for root, dirs, files in os.walk(base):

    for folder in dirs:

        if "الودق" in folder or "احتياط" in folder or "نسخة" in folder:

            full_path = os.path.join(root, folder)

            print("\nFOLDER FOUND:")
            print(full_path)

            try:
                contents = os.listdir(full_path)

                if contents:
                    for item in contents:
                        print("  -", item)
                else:
                    print("  EMPTY FOLDER")

            except Exception as e:
                print("  ERROR:", e)

============================================================
WADQ AI - SEARCH BACKUP FOLDERS
============================================================

FOLDER FOUND:
/content/drive/MyDrive/الودق AI - سجل المشروع
  - سجل_الودق_AI.txt
  - سجل_الاستئناف.txt
  - سجل_الودق_AI.gdoc

FOLDER FOUND:
/content/drive/MyDrive/الودق_AI_نسخة_احتياطية
  EMPTY FOLDER

In [1]:
import requests
from getpass import getpass

# إدخال رمز البوت دون إظهاره
token = getpass("أدخلي رمز البوت الجديد: ").strip()

# رقم المحادثة
chat_id = "4109066720"

url = f"https://api.telegram.org/bot{token}/sendMessage"

# رسالة اختبار بسيطة بدون رموز أو تنسيق خاص
test_message = "اختبار الودق AI - Telegram"

try:
    response = requests.post(
        url,
        data={
            "chat_id": chat_id,
            "text": test_message
        },
        timeout=20
    )

    print("حالة الإرسال:", response.status_code)
    print("نتيجة تيليجرام:")
    print(response.text)

except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت الجديد: ··········
حالة الإرسال: 400
نتيجة تيليجرام:
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}

In [2]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

url = f"https://api.telegram.org/bot{token}/getChat"

try:
    response = requests.get(
        url,
        params={"chat_id": "4109066720"},
        timeout=20
    )

    print("حالة الفحص:", response.status_code)
    print("نتيجة تيليجرام:")
    print(response.text)

except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت الجديد: ··········
حالة الفحص: 400
نتيجة تيليجرام:
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}

In [3]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت: ").strip()

url = f"https://api.telegram.org/bot{token}/getUpdates"

response = requests.get(url, timeout=20)

print("حالة الفحص:", response.status_code)
print(response.text)

أدخلي رمز البوت: ··········
حالة الفحص: 200
{"ok":true,"result":[{"update_id":90666561,
"message":{"message_id":3,"from":{"id":410906720,"is_bot":false,"first_name":"Najlaa","language_code":"ar"},"chat":{"id":410906720,"first_name":"Najlaa","type":"private"},"date":1792277148,"text":"\u0627\u0644\u0648"}},{"update_id":90666562,
"message":{"message_id":4,"from":{"id":410906720,"is_bot":false,"first_name":"Najlaa","language_code":"ar"},"chat":{"id":410906720,"first_name":"Najlaa","type":"private"},"date":1792347370,"text":"\u0647"}},{"update_id":90666563,
"message":{"message_id":5,"from":{"id":410906720,"is_bot":false,"first_name":"Najlaa","language_code":"ar"},"chat":{"id":410906720,"first_name":"Najlaa","type":"private"},"date":1792347854,"text":"\u0645\u0631\u062d\u0628\u0627"}}]}

In [4]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

chat_id = "4109066720"

url = f"https://api.telegram.org/bot{token}/sendMessage"

try:
    response = requests.post(
        url,
        data={
            "chat_id": chat_id,
            "text": "🌧️ الودق AI\nتم إصلاح الاتصال بتيليجرام. هذا اختبار إرسال."
        },
        timeout=20
    )

    print("حالة الإرسال:", response.status_code)
    print("نتيجة تيليجرام:")
    print(response.text)

except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت الجديد: ··········
حالة الإرسال: 400
نتيجة تيليجرام:
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}

In [5]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت الجديد: ").strip()

url = f"https://api.telegram.org/bot{token}/getMe"

response = requests.get(url, timeout=20)

print("حالة الفحص:", response.status_code)

data = response.json()

if data.get("ok"):
    print("اسم البوت:", data["result"].get("first_name"))
    print("معرّف البوت:", data["result"].get("id"))
    print("اسم المستخدم:", data["result"].get("username"))
else:
    print("رسالة الخطأ:", data.get("description"))

أدخلي رمز البوت الجديد: ··········
حالة الفحص: 200
اسم البوت: الودق اي اي لتوصيات
معرّف البوت: 8658801654
اسم المستخدم: NajlaHadi1414_bot

In [6]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت: ").strip()

url = f"https://api.telegram.org/bot{token}/getUpdates"

response = requests.get(url, timeout=20)
data = response.json()

print("حالة الفحص:", response.status_code)

if data.get("ok"):
    updates = data.get("result", [])

    if not updates:
        print("لا توجد رسائل جديدة مسجلة للبوت.")
        print("أرسلي رسالة جديدة للبوت من تيليجرام ثم أعيدي تشغيل هذه الخلية.")
    else:
        for update in updates:
            message = update.get("message") or update.get("channel_post")

            if message:
                chat = message.get("chat", {})
                print("نوع المحادثة:", chat.get("type"))
                print("اسم المحادثة:", chat.get("title") or chat.get("first_name"))
                print("رقم المحادثة:", chat.get("id"))
                print("-" * 30)
else:
    print("رسالة الخطأ:", data.get("description"))

أدخلي رمز البوت: ··········
حالة الفحص: 200
نوع المحادثة: private
اسم المحادثة: Najlaa
رقم المحادثة: 410906720
------------------------------
نوع المحادثة: private
اسم المحادثة: Najlaa
رقم المحادثة: 410906720
------------------------------
نوع المحادثة: private
اسم المحادثة: Najlaa
رقم المحادثة: 410906720
------------------------------

In [7]:
import requests
from getpass import getpass

# إدخال رمز البوت الجديد بأمان
token = getpass("أدخلي رمز البوت الجديد: ").strip()

# رقم المحادثة
chat_id = "4109066720"

# رابط إرسال الرسالة
url = f"https://api.telegram.org/bot{token}/sendMessage"

# رسالة اختبار
test_message = "اختبار الودق AI - Telegram"

try:
    response = requests.post(
        url,
        data={
            "chat_id": chat_id,
            "text": test_message
        },
        timeout=20
    )

    print("حالة الإرسال:", response.status_code)
    print("نتيجة تيليجرام:")
    print(response.text)

except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت الجديد: ··········
حالة الإرسال: 400
نتيجة تيليجرام:
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}

In [8]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت: ").strip()

url = f"https://api.telegram.org/bot{token}/getUpdates"

response = requests.get(url, timeout=20)
data = response.json()

print("نتيجة تيليجرام:")

if data.get("ok"):
    for update in data.get("result", []):
        message = update.get("message", {})
        chat = message.get("chat", {})

        if chat:
            print("رقم المحادثة:", chat.get("id"))
            print("اسم المحادثة:", chat.get("first_name", chat.get("title", "")))
else:
    print(data)

أدخلي رمز البوت: ··········
نتيجة تيليجرام:
رقم المحادثة: 410906720
اسم المحادثة: Najlaa
رقم المحادثة: 410906720
اسم المحادثة: Najlaa
رقم المحادثة: 410906720
اسم المحادثة: Najlaa

In [9]:
import requests
from getpass import getpass

# رمز البوت
token = getpass("أدخلي رمز البوت: ").strip()

# رقم المحادثة الذي تأكدنا منه
chat_id = "4109066720"

# رسالة اختبار
message = "🌧️ الودق AI — تم الاتصال بنجاح!"

url = f"https://api.telegram.org/bot{token}/sendMessage"

try:
    response = requests.post(
        url,
        data={
            "chat_id": chat_id,
            "text": message
        },
        timeout=20
    )

    result = response.json()
    print("نتيجة الإرسال:")
    print(result)

except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت: ··········
نتيجة الإرسال:
{'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'}

In [10]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت: ").strip()

url = f"https://api.telegram.org/bot{token}/getMe"

try:
    response = requests.get(url, timeout=20)
    data = response.json()

    print("نتيجة التحقق:")

    if data.get("ok"):
        bot = data["result"]
        print("اسم البوت:", bot.get("first_name"))
        print("اسم المستخدم:", bot.get("username"))
    else:
        print(data)

except Exception as e:
    print("حدث خطأ:", e)ر

SyntaxError: invalid syntax (1301835787.py, line 22)

In [11]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت: ").strip()

url = f"https://api.telegram.org/bot{token}/getMe"

try:
    response = requests.get(url, timeout=20)
    data = response.json()

    if data.get("ok"):
        bot = data["result"]
        print("اسم البوت:", bot.get("first_name"))
        print("اسم المستخدم:", bot.get("username"))
    else:
        print("خطأ من تيليجرام:")
        print(data)

except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت: ··········
اسم البوت: الودق اي اي لتوصيات
اسم المستخدم: NajlaHadi1414_bot

In [ ]:
import os

base = "/content/drive/MyDrive"

print("=== WADQ AI PROJECT LOG ===")

for root, dirs, files in os.walk(base):

    for file in files:

        if file.endswith(".txt") and "سجل" in file:

            path = os.path.join(root, file)

            print("\nFILE FOUND:")
            print(path)

            try:
                with open(path, "r", encoding="utf-8") as f:
                    content = f.read()

                print("\n=== LOG CONTENT ===")
                print(content[-10000:])

            except Exception as e:
                print("ERROR:", e)

=== WADQ AI PROJECT LOG ===

FILE FOUND:
/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt

=== LOG CONTENT ===

============================================================
🌧️ مشروع الودق AI — سجل التقدم
============================================================
تاريخ آخر تحديث: 2026-10-14
اسم ملف المشروع:
Copy of الودق AI
آخر مرحلة مكتملة:
المرحلة 67 — التدقيق الشامل لجودة البيانات والمخاطر
المراحل المكتملة:
- المرحلة 59: تحديث الأسعار
- المرحلة 60: فحص جودة البيانات
- المرحلة 61: تقييم الفرص الفنية
- المرحلة 62: مستويات فنية استرشادية
- المرحلة 63: إدارة المخاطر
- المرحلة 64: التقرير الموحد
- المرحلة 65: اختبارات الجودة
- المرحلة 66: إنشاء التقرير النهائي
- المرحلة 67: التدقيق الشامل
عدد الأصول:
26 أصلًا
نتائج المرحلة 67:
- 26 سعرًا صالحًا رقميًا
- 26 تاريخًا صالحًا وغير مستقبلي
- 12 أصلًا اجتاز الفحوص الأولية
- 14 أصلًا يحتاج إلى مراجعة
- 14 أصلًا لديه مستويات غير مكتملة أو تحتاج إلى مراجعة
- 14 أصلًا لديه كميات غير محسوبة أو غير صالحة
الجداول الأصلية لم تُعدّل عمدًا.
الجداول التي أنشأتها المرحلة 67:
1. wadq_stage67_audit_df
2. wadq_stage67_review_df
3. wadq_stage67_passed_df
4. wadq_stage67_summary_df
5. wadq_stage67_log_df
الخطوة التالية:
المرحلة 68A — فحص مصادر الأسعار التاريخية
ومعرفة الجداول المتاحة وأعمدتها قبل إصلاح البيانات.
بعد المرحلة 68A:
تحديد مصدر الأسعار التاريخية الصحيح،
ثم إصلاح المستويات الفنية وحسابات المخاطر.
تعليمات مهمة عند العودة:
1. لا تحذف أي خلية سابقة.
2. لا تضغط Run all.
3. لا تعيدي تشغيل المراحل السابقة دون حاجة.
4. افتحي ملف Copy of الودق AI نفسه.
5. تحققي من آخر مرحلة مكتملة قبل المتابعة.
6. إذا اختفت الجداول، افحصي المصادر المتاحة أولًا.
7. أضيفي المراحل الجديدة أسفل آخر خلية.
8. لا تعتمدي على كمية تداول نظرية قبل التحقق
   من العملة والعقد والعمولات وشروط الوسيط.
ملاحظة:
هذا السجل يحفظ وصف حالة المشروع، وليس الجداول
الموجودة في ذاكرة جلسة Colab.
============================================================


FILE FOUND:
/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الاستئناف.txt

=== LOG CONTENT ===

وقت الحفظ: 2026-10-14 00:16:40
آخر مرحلة مكتملة: 67
الخطوة التالية: 68A
ملف المشروع: Copy of الودق AI
----------------------------------------

In [12]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت: ").strip()

# رقم المحادثة الصحيح
chat_id = "4109066720"

# التحقق من البوت
check_url = f"https://api.telegram.org/bot{token}/getMe"
check = requests.get(check_url, timeout=20).json()

if not check.get("ok"):
    print("رمز البوت غير صحيح")
else:
    print("تم التحقق من البوت:", check["result"]["username"])

    # محاولة إرسال رسالة
    send_url = f"https://api.telegram.org/bot{token}/sendMessage"

    result = requests.post(
        send_url,
        data={
            "chat_id": chat_id,
            "text": "🌧️ اختبار الودق AI — هل وصلت الرسالة؟"
        },
        timeout=20
    ).json()

    print("نتيجة الإرسال:")
    print(result)

أدخلي رمز البوت: ··········
تم التحقق من البوت: NajlaHadi1414_bot
نتيجة الإرسال:
{'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'}

In [13]:
import requests
from getpass import getpass

token = getpass("أدخلي رمز البوت: ").strip()

base_url = f"https://api.telegram.org/bot{token}"

# استخراج آخر الرسائل التي وصلت لهذا البوت
updates = requests.get(
    f"{base_url}/getUpdates",
    timeout=20
).json()

if not updates.get("ok"):
    print("خطأ في قراءة تحديثات البوت:")
    print(updates)

else:
    found_chats = {}

    for update in updates.get("result", []):
        msg = update.get("message") or update.get("channel_post") or {}
        chat = msg.get("chat") or {}

        if chat.get("id"):
            found_chats[chat["id"]] = chat

    if not found_chats:
        print("لم تصل رسائل جديدة إلى البوت.")
        print("أرسلي /start إلى البوت ثم شغّلي الخلية مرة أخرى.")

    else:
        print("المحادثات التي وجدها البوت:")

        for chat_id, chat in found_chats.items():
            print("رقم المحادثة:", chat_id)
            print("النوع:", chat.get("type"))
            print("الاسم:", chat.get("first_name") or chat.get("title"))

            # إرسال رسالة اختبار إلى المحادثة المكتشفة
            result = requests.post(
                f"{base_url}/sendMessage",
                data={
                    "chat_id": chat_id,
                    "text": "🌧️ اختبار الودق AI — تم الاتصال بنجاح!"
                },
                timeout=20
            ).json()

            print("نتيجة الإرسال:", result)

أدخلي رمز البوت: ··········
خطأ في قراءة تحديثات البوت:
{'ok': False, 'error_code': 404, 'description': 'Not Found'}

In [15]:
import requests
from getpass import getpass

# إدخال رمز البوت
token = getpass("أدخلي رمز البوت: ").strip()

# رقم المحادثة
chat_id = "4109066720"

# رابط تيليجرام الصحيح
url = f"https://api.telegram.org/bot{token}/sendMessage"

# إرسال رسالة اختبار
try:
    response = requests.post(
        url,
        data={
            "chat_id": chat_id,
            "text": "🌧️ الودق AI — تم الاتصال بنجاح!"
        },
        timeout=20
    )

    result = response.json()
    print("نتيجة الإرسال:", result)

    if result.get("ok"):
        print("✅ نجح الاتصال ووصلت الرسالة إلى تيليجرام")
    else:
        print("❌ لم ينجح الإرسال، راجعي تفاصيل الخطأ أعلاه")

except Exception as e:
    print("حدث خطأ:", e)

أدخلي رمز البوت: ··········
نتيجة الإرسال: {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'}
❌ لم ينجح الإرسال، راجعي تفاصيل الخطأ أعلاه

In [16]:
# ============================================================
# 🌧️ الودق AI — تصحيح اتصال تيليجرام بالكامل
# فحص البوت + فحص المحادثة + إرسال رسالة اختبار
# ============================================================

import requests
from getpass import getpass

# ------------------------------------------------------------
# 1) إدخال رمز البوت
# ------------------------------------------------------------

token = getpass("أدخلي رمز البوت من BotFather: ").strip()

# رقم المحادثة الذي استخدمناه سابقاً
chat_id = "4109066720"

# ------------------------------------------------------------
# 2) تجهيز رابط تيليجرام
# ------------------------------------------------------------

base_url = f"https://api.telegram.org/bot{token}"

session = requests.Session()

try:

    # --------------------------------------------------------
    # 3) فحص رمز البوت
    # --------------------------------------------------------

    print("\n🔎 جاري فحص رمز البوت...")

    bot_response = session.get(
        f"{base_url}/getMe",
        timeout=20
    )

    bot_data = bot_response.json()

    if not bot_data.get("ok"):
        print("❌ رمز البوت غير صحيح أو غير صالح.")
        print("تفاصيل الخطأ:", bot_data)
        raise Exception("توقف الفحص بسبب مشكلة في رمز البوت.")

    bot_name = bot_data["result"].get("first_name", "البوت")

    print("✅ رمز البوت صحيح.")
    print("اسم البوت:", bot_name)

    # --------------------------------------------------------
    # 4) فحص رقم المحادثة
    # --------------------------------------------------------

    print("\n🔎 جاري فحص المحادثة...")

    chat_response = session.get(
        f"{base_url}/getChat",
        params={"chat_id": chat_id},
        timeout=20
    )

    chat_data = chat_response.json()

    if not chat_data.get("ok"):
        print("❌ تعذر الوصول إلى المحادثة.")
        print("تفاصيل الخطأ:", chat_data.get("description"))
        print("\nتأكدي من:")
        print("1- أن رقم المحادثة صحيح.")
        print("2- أنك بدأتِ المحادثة مع البوت بالضغط على Start.")
        print("3- أنك تستخدمين رقم محادثتك الشخصية الصحيح.")
        raise Exception("توقف الفحص بسبب مشكلة في المحادثة.")

    print("✅ المحادثة صحيحة.")

    # --------------------------------------------------------
    # 5) إرسال رسالة اختبار
    # --------------------------------------------------------

    print("\n📨 جاري إرسال رسالة اختبار...")

    message = (
        "🌧️ الودق AI\n"
        "تم الاتصال بنجاح!\n"
        "البوت جاهز لاستقبال الرسائل."
    )

    send_response = session.post(
        f"{base_url}/sendMessage",
        data={
            "chat_id": chat_id,
            "text": message
        },
        timeout=20
    )

    send_data = send_response.json()

    if send_data.get("ok"):

        print("\n" + "=" * 50)
        print("✅ نجح الاتصال والإرسال!")
        print("🌧️ وصلت رسالة الاختبار إلى تيليجرام.")
        print("=" * 50)

    else:

        print("\n❌ فشل إرسال الرسالة.")
        print("رمز الخطأ:", send_data.get("error_code"))
        print("سبب الخطأ:", send_data.get("description"))

        print("\nراجعي سبب الخطأ أعلاه.")

except requests.exceptions.Timeout:
    print("\n❌ انتهت مهلة الاتصال. أعيدي المحاولة.")

except requests.exceptions.RequestException as e:
    print("\n❌ مشكلة في الاتصال بالإنترنت:")
    print(e)

except Exception as e:
    print("\n⚠️ توقّف الفحص:")
    print(e)

finally:
    session.close()

أدخلي رمز البوت من BotFather: ··········

🔎 جاري فحص رمز البوت...
✅ رمز البوت صحيح.
اسم البوت: الودق اي اي لتوصيات

🔎 جاري فحص المحادثة...
❌ تعذر الوصول إلى المحادثة.
تفاصيل الخطأ: Bad Request: chat not found

تأكدي من:
1- أن رقم المحادثة صحيح.
2- أنك بدأتِ المحادثة مع البوت بالضغط على Start.
3- أنك تستخدمين رقم محادثتك الشخصية الصحيح.

⚠️ توقّف الفحص:
توقف الفحص بسبب مشكلة في المحادثة.

In [17]:
# ============================================================
# 🌧️ الودق AI — استخراج رقم المحادثة الصحيح وإرسال رسالة
# ============================================================

import requests
from getpass import getpass

# إدخال رمز البوت
token = getpass("أدخلي رمز البوت: ").strip()

base_url = f"https://api.telegram.org/bot{token}"

try:

    # 1- قراءة آخر الرسائل التي وصلت إلى البوت
    print("🔎 جاري البحث عن محادثتك مع البوت...")

    response = requests.get(
        f"{base_url}/getUpdates",
        timeout=20
    )

    data = response.json()

    if not data.get("ok"):
        print("❌ تعذر قراءة الرسائل:")
        print(data)
        raise Exception("فشل فحص الرسائل")

    updates = data.get("result", [])

    # 2- استخراج رقم المحادثة
    chat_id = None

    for update in reversed(updates):

        message = update.get("message") or update.get("edited_message")

        if message and message.get("chat"):

            chat = message["chat"]

            if chat.get("type") == "private":
                chat_id = chat["id"]
                break

    if chat_id is None:

        print("❌ لم أجد محادثة جديدة مع البوت.")
        print("افتحي تيليجرام وأرسلي للبوت كلمة مرحبا.")
        print("ثم شغّلي هذه الخلية مرة أخرى.")

    else:

        print("✅ تم العثور على رقم المحادثة الصحيح.")
        print("رقم المحادثة:", chat_id)

        # 3- إرسال رسالة الاختبار
        send = requests.post(
            f"{base_url}/sendMessage",
            data={
                "chat_id": chat_id,
                "text": "🌧️ الودق AI — تم الاتصال بنجاح!"
            },
            timeout=20
        )

        result = send.json()

        if result.get("ok"):

            print("✅ نجح الاتصال!")
            print("📨 تم إرسال رسالة الاختبار إلى تيليجرام.")

        else:

            print("❌ فشل إرسال الرسالة.")
            print("تفاصيل الخطأ:", result)

except Exception as e:

    print("⚠️ حدث خطأ:", e)

أدخلي رمز البوت: ··········
🔎 جاري البحث عن محادثتك مع البوت...
✅ تم العثور على رقم المحادثة الصحيح.
رقم المحادثة: 410906720
✅ نجح الاتصال!
📨 تم إرسال رسالة الاختبار إلى تيليجرام.

In [18]:
# 🌧️ الودق AI — البحث عن جداول التقارير النهائية

import pandas as pd

print("=" * 60)
print("الجداول المتاحة في مشروع الودق AI")
print("=" * 60)

for name, obj in globals().copy().items():

    if isinstance(obj, pd.DataFrame):

        if any(word in name.lower() for word in [
            "final", "report", "decision", "master", "unified"
        ]):

            print(f"\n📊 اسم الجدول: {name}")
            print(f"عدد الصفوف: {len(obj)}")
            print(f"عدد الأعمدة: {len(obj.columns)}")
            print("أهم الأعمدة:", list(obj.columns[:10]))

============================================================
الجداول المتاحة في مشروع الودق AI
============================================================

In [19]:
# ============================================================
# 🌧️ الودق AI — كشف جميع الجداول الموجودة
# ============================================================

import pandas as pd

print("=" * 65)
print("🌧️ الودق AI — فحص جميع الجداول")
print("=" * 65)

tables_found = 0

for name, obj in list(globals().items()):

    if isinstance(obj, pd.DataFrame):

        tables_found += 1

        print("\n" + "-" * 50)
        print(f"📊 اسم الجدول: {name}")
        print(f"عدد الصفوف: {obj.shape[0]}")
        print(f"عدد الأعمدة: {obj.shape[1]}")
        print("الأعمدة:")

        for col in obj.columns:
            print(" -", col)

print("\n" + "=" * 65)

if tables_found == 0:
    print("⚠️ لم يتم العثور على جداول DataFrame في الذاكرة.")
    print("قد تحتاجين إلى إعادة الاتصال ببيئة التشغيل.")
else:
    print(f"✅ تم العثور على {tables_found} جدولًا.")
    print("انتهى الفحص دون تعديل أي جدول.")

=================================================================
🌧️ الودق AI — فحص جميع الجداول
=================================================================

=================================================================
⚠️ لم يتم العثور على جداول DataFrame في الذاكرة.
قد تحتاجين إلى إعادة الاتصال ببيئة التشغيل.

In [20]:
# ============================================================
# 🌧️ الودق AI — كشف جميع الجداول الموجودة
# ============================================================

import pandas as pd

print("=" * 65)
print("🌧️ الودق AI — فحص جميع الجداول")
print("=" * 65)

tables_found = 0

for name, obj in list(globals().items()):

    if isinstance(obj, pd.DataFrame):

        tables_found += 1

        print("\n" + "-" * 50)
        print(f"📊 اسم الجدول: {name}")
        print(f"عدد الصفوف: {obj.shape[0]}")
        print(f"عدد الأعمدة: {obj.shape[1]}")
        print("الأعمدة:")

        for col in obj.columns:
            print(" -", col)

print("\n" + "=" * 65)

if tables_found == 0:
    print("⚠️ لم يتم العثور على جداول DataFrame في الذاكرة.")
    print("قد تحتاجين إلى إعادة الاتصال ببيئة التشغيل.")
else:
    print(f"✅ تم العثور على {tables_found} جدولًا.")
    print("انتهى الفحص دون تعديل أي جدول.")

=================================================================
🌧️ الودق AI — فحص جميع الجداول
=================================================================

=================================================================
⚠️ لم يتم العثور على جداول DataFrame في الذاكرة.
قد تحتاجين إلى إعادة الاتصال ببيئة التشغيل.

In [21]:
# 🌧️ الودق AI — فحص الملفات المحفوظة في Google Drive

import os

base = "/content/drive/MyDrive"

print("🔎 البحث عن ملفات الودق AI المحفوظة...")

if not os.path.exists(base):
    print("⚠️ Google Drive غير متصل.")
    print("لا تعيدي تشغيل بيئة التشغيل الآن.")
else:
    found = 0

    for root, dirs, files in os.walk(base):

        for file in files:

            if any(word in file.lower() for word in [
                "ودق", "wadq", "report", "trade", "stock"
            ]):

                print(os.path.join(root, file))
                found += 1

    print("\nعدد الملفات التي عُثر عليها:", found)

🔎 البحث عن ملفات الودق AI المحفوظة...
⚠️ Google Drive غير متصل.
لا تعيدي تشغيل بيئة التشغيل الآن.

In [22]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [23]:
# 🌧️ الودق AI — البحث عن ملفات المشروع المحفوظة

import os

base = "/content/drive/MyDrive"

print("🔎 جاري البحث عن ملفات الودق AI...")

found = 0

for root, dirs, files in os.walk(base):

    # تجاهل مجلدات غير مهمة لتسريع البحث
    dirs[:] = [
        d for d in dirs
        if d not in [".ipynb_checkpoints", "_pycache_"]
    ]

    for file in files:

        if any(word in file.lower() for word in [
            "ودق", "wadq", "report", "trade", "stock"
        ]):

            print(os.path.join(root, file))
            found += 1

print("\n" + "=" * 50)
print("عدد الملفات التي تم العثور عليها:", found)# 🌧️ الودق AI — البحث عن ملفات المشروع المحفوظة

import os

base = "/content/drive/MyDrive"

print("🔎 جاري البحث عن ملفات الودق AI...")

found = 0

for root, dirs, files in os.walk(base):

    # تجاهل مجلدات غير مهمة لتسريع البحث
    dirs[:] = [
        d for d in dirs
        if d not in [".ipynb_checkpoints", "_pycache_"]
    ]

    for file in files:

        if any(word in file.lower() for word in [
            "ودق", "wadq", "report", "trade", "stock"
        ]):

            print(os.path.join(root, file))
            found += 1

print("\n" + "=" * 50)
print("عدد الملفات التي تم العثور عليها:", found)

🔎 جاري البحث عن ملفات الودق AI...
/content/drive/MyDrive/Colab Notebooks/Copy of الودقAI
/content/drive/MyDrive/Colab Notebooks/Yet another copy of الودقAI
/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt
/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.gdoc
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_الجداول_المستعادة.xlsx
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_68.xlsx
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_69.xlsx
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_ai_final_report.xlsx
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_price_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_technical_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_evaluation_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_risk_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_final_ai_report.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_decision_board_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_quality_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_global_master_report_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_saudi_report_df.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.xlsx
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.xlsx
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_trades_20261017_213918.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_daily_20261017_213918.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_summary_20261017_213918.csv

==================================================
عدد الملفات التي تم العثور عليها: 24
🔎 جاري البحث عن ملفات الودق AI...
/content/drive/MyDrive/Colab Notebooks/Copy of الودقAI
/content/drive/MyDrive/Colab Notebooks/Yet another copy of الودقAI
/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt
/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.gdoc
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_الجداول_المستعادة.xlsx
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_68.xlsx
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_69.xlsx
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_ai_final_report.xlsx
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_price_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_technical_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_evaluation_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_risk_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_final_ai_report.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_decision_board_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_quality_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_global_master_report_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_saudi_report_df.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.xlsx
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.xlsx
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_trades_20261017_213918.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_daily_20261017_213918.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_summary_20261017_213918.csv

==================================================
عدد الملفات التي تم العثور عليها: 24

In [24]:
# =====================================================================
# 🌧️ الودق AI — استعادة الجداول المحفوظة
# استعادة التقارير والجداول من Google Drive إلى ذاكرة Colab
# لا يحذف الملفات ولا ينفذ صفقات ولا يعيد تحديث الأسعار
# =====================================================================

import os
import glob
import pandas as pd
from IPython.display import display

print("=" * 70)
print("🌧️ الودق AI — استعادة الجداول المحفوظة")
print("=" * 70)

# ---------------------------------------------------------
# 1) التأكد من اتصال Google Drive
# ---------------------------------------------------------

BASE = "/content/drive/MyDrive"

if not os.path.exists(BASE):
    try:
        from google.colab import drive
        drive.mount("/content/drive")
    except Exception as e:
        print("❌ تعذر الاتصال بـ Google Drive")
        print("تفاصيل الخطأ:", e)

if not os.path.exists(BASE):
    raise RuntimeError(
        "Google Drive غير متصل. "
        "اتصلي به ثم أعيدي تشغيل هذه الخلية."
    )

print("✅ Google Drive متصل")


# ---------------------------------------------------------
# 2) البحث عن أحدث مجلد نتائج إعادة البناء
# ---------------------------------------------------------

report_pattern = os.path.join(
    BASE,
    "الودق AI - نتائج إعادة البناء",
    "تقرير_*"
)

report_folders = glob.glob(report_pattern)

if report_folders:
    REPORT_DIR = max(
        report_folders,
        key=os.path.getmtime
    )
else:
    REPORT_DIR = os.path.join(
        BASE,
        "الودق AI - نتائج إعادة البناء",
        "تقرير_20261017_140449"
    )

print("\n📁 مجلد التقارير:")
print(REPORT_DIR)


# ---------------------------------------------------------
# 3) استعادة الجداول الأساسية
# ---------------------------------------------------------

files_to_restore = {
    "wadq_price_df": "wadq_price_df.csv",
    "wadq_technical_df": "wadq_technical_df.csv",
    "wadq_evaluation_df": "wadq_evaluation_df.csv",
    "wadq_risk_df": "wadq_risk_df.csv",
    "wadq_final_ai_report": "wadq_final_ai_report.csv",
    "wadq_decision_board_df": "wadq_decision_board_df.csv",
    "wadq_quality_df": "wadq_quality_df.csv",
    "wadq_global_master_report_df": "wadq_global_master_report_df.csv",
    "wadq_saudi_report_df": "wadq_saudi_report_df.csv",
}

restored = []
missing = []

for variable_name, filename in files_to_restore.items():

    filepath = os.path.join(REPORT_DIR, filename)

    if os.path.exists(filepath):

        try:
            df = pd.read_csv(filepath)

            # استعادة الجدول إلى ذاكرة Colab
            globals()[variable_name] = df

            restored.append(variable_name)

            print(
                f"✅ {variable_name}: "
                f"{len(df)} صف × {len(df.columns)} عمود"
            )

        except Exception as e:
            missing.append(filename)
            print(f"⚠️ تعذر قراءة {filename}: {e}")

    else:
        missing.append(filename)
        print(f"⚠️ الملف غير موجود: {filename}")


# ---------------------------------------------------------
# 4) استعادة نتائج المرحلة 76
# ---------------------------------------------------------

phase76_dir = os.path.join(
    BASE,
    "الودق AI - نتائج المرحلة 76"
)

phase76_files = glob.glob(
    os.path.join(phase76_dir, "*.csv")
)

for filepath in phase76_files:

    filename = os.path.basename(filepath)

    try:
        df = pd.read_csv(filepath)

        if "wadq76_report" in filename:
            globals()["wadq76_report"] = df

        elif "wadq77_trade_plan" in filename:
            globals()["wadq77_trade_plan"] = df

        print(
            f"✅ استعادة {filename}: "
            f"{len(df)} صف"
        )

    except Exception as e:
        print(f"⚠️ تعذر قراءة {filename}: {e}")


# ---------------------------------------------------------
# 5) استعادة ملفات المرحلة 85C
# ---------------------------------------------------------

phase85_dir = os.path.join(
    BASE,
    "الودق AI - نتائج المرحلة 85C"
)

phase85_files = glob.glob(
    os.path.join(phase85_dir, "*.csv")
)

for filepath in phase85_files:

    filename = os.path.basename(filepath)

    try:
        df = pd.read_csv(filepath)

        if "trades" in filename:
            globals()["wadq_85C_trades"] = df

        elif "daily" in filename:
            globals()["wadq_85C_daily"] = df

        elif "summary" in filename:
            globals()["wadq_85C_summary"] = df

        print(
            f"✅ استعادة {filename}: "
            f"{len(df)} صف"
        )

    except Exception as e:
        print(f"⚠️ تعذر قراءة {filename}: {e}")


# ---------------------------------------------------------
# 6) فحص الجداول المستعادة
# ---------------------------------------------------------

print("\n" + "=" * 70)
print("📊 ملخص استعادة الجداول")
print("=" * 70)

print("عدد الجداول الأساسية المستعادة:", len(restored))

if restored:

    print("\nأسماء الجداول المستعادة:")
    for name in restored:
        print("•", name)

    print("\n📋 معاينة التقرير النهائي:")

    if "wadq_final_ai_report" in globals():

        display(
            wadq_final_ai_report.head(10)
        )

    elif "wadq_ai_final_report" in globals():

        display(
            wadq_ai_final_report.head(10)
        )

else:
    print("⚠️ لم تتم استعادة الجداول الأساسية.")

print("\n" + "=" * 70)
print("🌧️ انتهت عملية الاستعادة")
print("=" * 70)

print("⚠️ هذه العملية تستعيد البيانات المحفوظة فقط.")
print("لا تعتبر تحديثًا للأسعار أو توصيات تداول جديدة.")

======================================================================
🌧️ الودق AI — استعادة الجداول المحفوظة
======================================================================
✅ Google Drive متصل

📁 مجلد التقارير:
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449
✅ wadq_price_df: 26 صف × 9 عمود
✅ wadq_technical_df: 26 صف × 10 عمود
✅ wadq_evaluation_df: 26 صف × 9 عمود
✅ wadq_risk_df: 26 صف × 9 عمود
✅ wadq_final_ai_report: 26 صف × 17 عمود
✅ wadq_decision_board_df: 26 صف × 9 عمود
✅ wadq_quality_df: 26 صف × 5 عمود
✅ wadq_global_master_report_df: 14 صف × 17 عمود
✅ wadq_saudi_report_df: 3 صف × 17 عمود
✅ استعادة wadq76_report_20261017_142233.csv: 41 صف
✅ استعادة wadq77_trade_plan_20261017_143605.csv: 41 صف
✅ استعادة wadq_85C_trades_20261017_213918.csv: 612 صف
✅ استعادة wadq_85C_daily_20261017_213918.csv: 2067 صف
✅ استعادة wadq_85C_summary_20261017_213918.csv: 1 صف

======================================================================
📊 ملخص استعادة الجداول
======================================================================
عدد الجداول الأساسية المستعادة: 9

أسماء الجداول المستعادة:
• wadq_price_df
• wadq_technical_df
• wadq_evaluation_df
• wadq_risk_df
• wadq_final_ai_report
• wadq_decision_board_df
• wadq_quality_df
• wadq_global_master_report_df
• wadq_saudi_report_df

📋 معاينة التقرير النهائي:

,ticker,asset,market,latest_close,daily_change_pct,RSI,trend,technical_score,evaluation,latest_close_risk,stop_loss_guide,target_1_guide,target_2_guide,risk_budget_sar,theoretical_quantity,theoretical_position_value,risk_calculation_status
0,BZ=F,Brent Oil,COMMODITY,109.860001,3.719791,61.840742,صاعد,4,إيجابي فنيًا,109.860001,104.367001,115.353001,120.846001,1.0,0.182050,20.0,نظري
1,CL=F,US Oil,COMMODITY,101.410004,3.511281,68.016356,صاعد,3,إيجابي فنيًا,101.410004,96.339503,106.480504,111.551004,1.0,0.197219,20.0,نظري
2,^N225,Nikkei 225,INDEX,65324.289062,1.394376,46.423099,متذبذب,2,محايد,65324.289062,62058.074609,68590.503516,71856.717969,1.0,0.000306,20.0,نظري
3,^GDAXI,DAX Germany,INDEX,25622.609375,0.945490,54.987914,متذبذب,3,إيجابي فنيًا,25622.609375,24341.478906,26903.739844,28184.870313,1.0,0.000781,20.0,نظري
4,^HSI,Hang Seng,INDEX,24186.830078,0.515774,44.124949,هابط,2,محايد,24186.830078,22977.488574,25396.171582,26605.513086,1.0,0.000827,20.0,نظري
5,AAPL,Apple,US,343.459991,0.426898,56.398594,صاعد,4,إيجابي فنيًا,343.459991,326.286992,360.632991,377.805991,1.0,0.058231,20.0,نظري
6,^FTSE,FTSE 100 UK,INDEX,10881.900391,0.382827,60.678637,متذبذب,3,إيجابي فنيًا,10881.900391,10337.805371,11425.995410,11970.090430,1.0,0.001838,20.0,نظري
7,SI=F,Silver,COMMODITY,56.994999,0.277983,34.870715,هابط,0,ضعيف فنيًا,56.994999,54.145249,59.844749,62.694499,1.0,0.350908,20.0,نظري
8,^FCHI,CAC 40 France,INDEX,7956.700195,0.277263,42.112703,متذبذب,3,إيجابي فنيًا,7956.700195,7558.865186,8354.535205,8752.370215,1.0,0.002514,20.0,نظري
9,GC=F,Gold,COMMODITY,4181.100098,0.263783,51.536439,هابط,2,محايد,4181.100098,3972.045093,4390.155103,4599.210107,1.0,0.004783,20.0,نظري

======================================================================
🌧️ انتهت عملية الاستعادة
======================================================================
⚠️ هذه العملية تستعيد البيانات المحفوظة فقط.
لا تعتبر تحديثًا للأسعار أو توصيات تداول جديدة.

In [25]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 86
# فحص سلامة الجداول المستعادة ومطابقة نتائج التداول
# لا يحذف أي بيانات ولا ينفذ أي صفقة
# =====================================================================

import pandas as pd
import numpy as np

print("=" * 65)
print("🌧️ الودق AI — المرحلة 86")
print("فحص سلامة البيانات")
print("=" * 65)

# ---------------------------------------------------------
# 1) فحص الجداول الأساسية
# ---------------------------------------------------------

core_tables = [
    "wadq_price_df",
    "wadq_technical_df",
    "wadq_evaluation_df",
    "wadq_risk_df",
    "wadq_final_ai_report",
    "wadq_decision_board_df",
    "wadq_quality_df",
    "wadq_global_master_report_df",
    "wadq_saudi_report_df"
]

results = []

for name in core_tables:

    if name not in globals():

        results.append({
            "الجدول": name,
            "الصفوف": 0,
            "الأعمدة": 0,
            "القيم المفقودة": None,
            "الحالة": "غير موجود"
        })

        continue

    df = globals()[name]

    results.append({
        "الجدول": name,
        "الصفوف": len(df),
        "الأعمدة": len(df.columns),
        "القيم المفقودة": int(df.isna().sum().sum()),
        "الحالة": "موجود"
    })

core_check_df = pd.DataFrame(results)

print("\n📊 فحص الجداول الأساسية:")
display(core_check_df)


# ---------------------------------------------------------
# 2) فحص سجل الصفقات
# ---------------------------------------------------------

if "wadq_85C_trades" in globals():

    trades = wadq_85C_trades.copy()

    print("\n📈 فحص سجل الصفقات")
    print("عدد السجلات:", len(trades))
    print("عدد الأعمدة:", len(trades.columns))

    print("\nأسماء الأعمدة:")
    print(list(trades.columns))

    # فحص التكرار الكامل فقط
    duplicated_rows = trades.duplicated().sum()

    print("\nعدد الصفوف المتطابقة بالكامل:", duplicated_rows)

    # عرض معاينة الصفقات
    display(trades.head(10))

else:

    print("\n⚠️ جدول الصفقات غير موجود في الذاكرة")


# ---------------------------------------------------------
# 3) فحص التقرير النهائي
# ---------------------------------------------------------

if "wadq_final_ai_report" in globals():

    final_report = wadq_final_ai_report.copy()

    print("\n📋 التقرير النهائي")
    print("عدد الأصول:", len(final_report))

    if "ticker" in final_report.columns:

        print(
            "عدد الرموز المختلفة:",
            final_report["ticker"].nunique()
        )

        print(
            "الرموز المكررة:",
            final_report[
                final_report["ticker"].duplicated()
            ]["ticker"].tolist()
        )

    display(final_report.head(10))


# ---------------------------------------------------------
# 4) ملخص الفحص
# ---------------------------------------------------------

print("\n" + "=" * 65)
print("🌧️ انتهى الفحص")
print("=" * 65)

print("تم فحص البيانات دون تعديل الجداول الأصلية.")
print("لم يتم تحديث الأسعار أو تنفيذ أي تداول.")

=================================================================
🌧️ الودق AI — المرحلة 86
فحص سلامة البيانات
=================================================================

📊 فحص الجداول الأساسية:

                         الجدول  الصفوف  الأعمدة  القيم المفقودة الحالة
0                 wadq_price_df      26        9               0  موجود
1             wadq_technical_df      26       10               0  موجود
2            wadq_evaluation_df      26        9               0  موجود
3                  wadq_risk_df      26        9               0  موجود
4          wadq_final_ai_report      26       17               0  موجود
5        wadq_decision_board_df      26        9               0  موجود
6               wadq_quality_df      26        5               0  موجود
7  wadq_global_master_report_df      14       17               0  موجود
8          wadq_saudi_report_df       3       17               0  موجود

📈 فحص سجل الصفقات
عدد السجلات: 612
عدد الأعمدة: 13

أسماء الأعمدة:
['ticker', 'entry_date', 'exit_date', 'quantity', 'entry_price_local', 'exit_price_local', 'entry_value_sar', 'exit_value_sar', 'entry_fee_sar', 'exit_fee_sar', 'pnl_sar', 'exit_reason', 'holding_days']

عدد الصفوف المتطابقة بالكامل: 0

,ticker,entry_date,exit_date,quantity,entry_price_local,exit_price_local,entry_value_sar,exit_value_sar,entry_fee_sar,exit_fee_sar,pnl_sar,exit_reason,holding_days
0,AEO,2021-03-17,2021-03-23,7,25.689037,23.850993,674.337225,626.088558,0.674337,0.626089,-49.549093,وقف خسارة,3
1,2010.SR,2021-03-14,2021-03-24,19,85.656905,83.113618,1627.481186,1579.158736,1.627481,1.579159,-51.529090,وقف خسارة,7
2,1180.SR,2021-03-21,2021-03-25,34,29.072060,28.018199,988.450044,952.618774,0.988450,0.952619,-37.772339,وقف خسارة,3
3,1180.SR,2021-04-04,2021-04-04,48,32.037413,34.087596,1537.795800,1636.204628,1.537796,1.636205,95.234827,هدف,0
4,MSFT,2021-03-17,2021-04-08,1,225.798262,242.615058,846.743484,909.806466,0.846743,0.909806,61.306433,هدف,14
5,1180.SR,2021-04-06,2021-04-13,5,32.444425,31.052809,162.222125,155.264046,0.162222,0.155264,-7.275565,وقف خسارة,4
6,SPY,2021-03-17,2021-04-15,1,365.612927,384.873449,1371.048476,1443.275435,1.371048,1.443275,69.412635,هدف,19
7,GOOGL,2021-04-05,2021-04-15,2,106.398716,112.879087,797.990369,846.593154,0.797990,0.846593,46.958202,هدف,7
8,AEO,2021-04-08,2021-04-19,4,26.562463,30.158550,398.436948,452.378255,0.398437,0.452378,53.090492,هدف,6
9,2010.SR,2021-04-04,2021-04-28,18,89.706129,95.162291,1614.710325,1712.921243,1.614710,1.712921,94.883287,هدف,17

📋 التقرير النهائي
عدد الأصول: 26
عدد الرموز المختلفة: 26
الرموز المكررة: []

,ticker,asset,market,latest_close,daily_change_pct,RSI,trend,technical_score,evaluation,latest_close_risk,stop_loss_guide,target_1_guide,target_2_guide,risk_budget_sar,theoretical_quantity,theoretical_position_value,risk_calculation_status
0,BZ=F,Brent Oil,COMMODITY,109.860001,3.719791,61.840742,صاعد,4,إيجابي فنيًا,109.860001,104.367001,115.353001,120.846001,1.0,0.182050,20.0,نظري
1,CL=F,US Oil,COMMODITY,101.410004,3.511281,68.016356,صاعد,3,إيجابي فنيًا,101.410004,96.339503,106.480504,111.551004,1.0,0.197219,20.0,نظري
2,^N225,Nikkei 225,INDEX,65324.289062,1.394376,46.423099,متذبذب,2,محايد,65324.289062,62058.074609,68590.503516,71856.717969,1.0,0.000306,20.0,نظري
3,^GDAXI,DAX Germany,INDEX,25622.609375,0.945490,54.987914,متذبذب,3,إيجابي فنيًا,25622.609375,24341.478906,26903.739844,28184.870313,1.0,0.000781,20.0,نظري
4,^HSI,Hang Seng,INDEX,24186.830078,0.515774,44.124949,هابط,2,محايد,24186.830078,22977.488574,25396.171582,26605.513086,1.0,0.000827,20.0,نظري
5,AAPL,Apple,US,343.459991,0.426898,56.398594,صاعد,4,إيجابي فنيًا,343.459991,326.286992,360.632991,377.805991,1.0,0.058231,20.0,نظري
6,^FTSE,FTSE 100 UK,INDEX,10881.900391,0.382827,60.678637,متذبذب,3,إيجابي فنيًا,10881.900391,10337.805371,11425.995410,11970.090430,1.0,0.001838,20.0,نظري
7,SI=F,Silver,COMMODITY,56.994999,0.277983,34.870715,هابط,0,ضعيف فنيًا,56.994999,54.145249,59.844749,62.694499,1.0,0.350908,20.0,نظري
8,^FCHI,CAC 40 France,INDEX,7956.700195,0.277263,42.112703,متذبذب,3,إيجابي فنيًا,7956.700195,7558.865186,8354.535205,8752.370215,1.0,0.002514,20.0,نظري
9,GC=F,Gold,COMMODITY,4181.100098,0.263783,51.536439,هابط,2,محايد,4181.100098,3972.045093,4390.155103,4599.210107,1.0,0.004783,20.0,نظري

=================================================================
🌧️ انتهى الفحص
=================================================================
تم فحص البيانات دون تعديل الجداول الأصلية.
لم يتم تحديث الأسعار أو تنفيذ أي تداول.

In [26]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 87
# محرك التوصيات الشامل
# تحديث الأسعار + التحليل الفني + التقييم + إدارة المخاطر
#
# رأس المال: 10,000 ريال
# الحد الأقصى للمخاطرة في الصفقة: 1% = 100 ريال
# الحد الأقصى لقيمة الصفقة الواحدة: 20% = 2,000 ريال
#
# لا ينفذ أي تداول حقيقي ولا يعدل الجداول السابقة.
# =====================================================================

import sys
import subprocess
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------
# 1. تجهيز المكتبات
# ---------------------------------------------------------------------

try:
    import yfinance as yf
except ImportError:
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-q", "yfinance"]
    )
    import yfinance as yf

import numpy as np
import pandas as pd
from datetime import datetime

print("=" * 70)
print("🌧️ الودق AI — المرحلة 87")
print("محرك التوصيات الشامل")
print("=" * 70)


# ---------------------------------------------------------------------
# 2. إعداد رأس المال وإدارة المخاطر
# ---------------------------------------------------------------------

CAPITAL_SAR = 10000

RISK_PER_TRADE = 0.01
MAX_POSITION_PCT = 0.20

RISK_BUDGET_SAR = CAPITAL_SAR * RISK_PER_TRADE
MAX_POSITION_SAR = CAPITAL_SAR * MAX_POSITION_PCT

USD_TO_SAR = 3.75

print(f"رأس المال: {CAPITAL_SAR:,.0f} ريال")
print(f"ميزانية المخاطرة للصفقة: {RISK_BUDGET_SAR:,.0f} ريال")
print(f"الحد الأقصى لقيمة الصفقة: {MAX_POSITION_SAR:,.0f} ريال")


# ---------------------------------------------------------------------
# 3. تحديد الأصول الموجودة في المشروع
# ---------------------------------------------------------------------

source_tables = [
    "wadq_final_ai_report",
    "wadq_price_df",
    "wadq_decision_board_df",
]

existing_tickers = []

for table_name in source_tables:

    if table_name in globals():

        df_source = globals()[table_name]

        if isinstance(df_source, pd.DataFrame):

            if "ticker" in df_source.columns:

                existing_tickers.extend(
                    df_source["ticker"]
                    .dropna()
                    .astype(str)
                    .str.strip()
                    .tolist()
                )


# الأسهم الأمريكية التي أضيفت مؤخرًا إلى المشروع
extra_us_tickers = [
    "ARAY",
    "SLXN",
    "SOAR",
    "GPRO",
    "ARBE",
    "WKHS",
    "HIMX",
    "GRYP",
    "OPEN",
    "BBAI",
]

existing_tickers.extend(extra_us_tickers)

existing_tickers = list(dict.fromkeys(existing_tickers))


# ---------------------------------------------------------------------
# 4. استبعاد المؤشرات والسلع والعملات الرقمية
# ---------------------------------------------------------------------

def is_stock_ticker(ticker):

    ticker = str(ticker).strip()

    if not ticker:
        return False

    # المؤشرات
    if ticker.startswith("^"):
        return False

    # السلع
    if "=F" in ticker:
        return False

    # العملات الرقمية
    if "-USD" in ticker:
        return False

    # العملات الأجنبية
    if "=X" in ticker:
        return False

    return True


stock_tickers = [
    ticker
    for ticker in existing_tickers
    if is_stock_ticker(ticker)
]

print("\nعدد الأسهم المراد تحليلها:", len(stock_tickers))

if len(stock_tickers) == 0:

    raise ValueError(
        "لم يتم العثور على رموز الأسهم في الجداول السابقة."
    )


# ---------------------------------------------------------------------
# 5. تحديث الأسعار من Yahoo Finance
# ---------------------------------------------------------------------

print("\n🔄 تحديث الأسعار والبيانات التاريخية...")

raw_data = yf.download(
    tickers=stock_tickers,
    period="1y",
    interval="1d",
    auto_adjust=True,
    group_by="ticker",
    threads=True,
    progress=False
)


# استخراج بيانات كل سهم من البيانات المجمعة

def extract_ticker_data(raw, ticker, ticker_list):

    if raw is None or raw.empty:
        return pd.DataFrame()

    if isinstance(raw.columns, pd.MultiIndex):

        level0 = raw.columns.get_level_values(0)
        level1 = raw.columns.get_level_values(1)

        if ticker in level0:

            result = raw[ticker].copy()

        elif ticker in level1:

            result = raw.xs(
                ticker,
                axis=1,
                level=1
            ).copy()

        else:

            return pd.DataFrame()

    else:

        if len(ticker_list) == 1:

            result = raw.copy()

        else:

            return pd.DataFrame()

    result.columns = [
        str(c).strip().title()
        for c in result.columns
    ]

    result = result.loc[:, ~result.columns.duplicated()]

    required_columns = ["Close", "High", "Low"]

    if not all(c in result.columns for c in required_columns):

        return pd.DataFrame()

    result = result.dropna(
        subset=["Close", "High", "Low"]
    )

    return result


# ---------------------------------------------------------------------
# 6. حساب المؤشرات الفنية
# ---------------------------------------------------------------------

def calculate_rsi(series, period=14):

    delta = series.diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1/period,
        min_periods=period,
        adjust=False
    ).mean()

    rs = avg_gain / avg_loss.replace(0, np.nan)

    rsi = 100 - (100 / (1 + rs))

    return rsi


def calculate_indicators(df):

    df = df.copy()

    if len(df) < 200:

        return None

    df["SMA20"] = df["Close"].rolling(20).mean()
    df["SMA50"] = df["Close"].rolling(50).mean()
    df["SMA200"] = df["Close"].rolling(200).mean()

    df["RSI14"] = calculate_rsi(df["Close"], 14)

    ema12 = df["Close"].ewm(
        span=12,
        adjust=False
    ).mean()

    ema26 = df["Close"].ewm(
        span=26,
        adjust=False
    ).mean()

    df["MACD"] = ema12 - ema26

    df["MACD_SIGNAL"] = df["MACD"].ewm(
        span=9,
        adjust=False
    ).mean()

    # متوسط المدى الحقيقي ATR
    previous_close = df["Close"].shift(1)

    tr1 = df["High"] - df["Low"]

    tr2 = (df["High"] - previous_close).abs()

    tr3 = (df["Low"] - previous_close).abs()

    df["TR"] = pd.concat(
        [tr1, tr2, tr3],
        axis=1
    ).max(axis=1)

    df["ATR14"] = df["TR"].rolling(14).mean()

    # نسبة حجم التداول
    if "Volume" in df.columns:

        df["VOLUME_AVG20"] = df["Volume"].rolling(20).mean()

        df["VOLUME_RATIO"] = (
            df["Volume"] /
            df["VOLUME_AVG20"].replace(0, np.nan)
        )

    else:

        df["VOLUME_RATIO"] = np.nan

    # التغير اليومي
    df["DAILY_CHANGE_PCT"] = (
        df["Close"].pct_change() * 100
    )

    return df


# ---------------------------------------------------------------------
# 7. تحليل كل سهم
# ---------------------------------------------------------------------

analysis_results = []

print("\n🔍 بدء التحليل الفني...")

for ticker in stock_tickers:

    try:

        df = extract_ticker_data(
            raw_data,
            ticker,
            stock_tickers
        )

        if df.empty:

            print(f"⚠️ {ticker}: لا توجد بيانات")

            continue

        df = calculate_indicators(df)

        if df is None:

            print(f"⚠️ {ticker}: البيانات التاريخية غير كافية")

            continue

        df = df.dropna(
            subset=[
                "SMA20",
                "SMA50",
                "SMA200",
                "RSI14",
                "MACD",
                "MACD_SIGNAL",
                "ATR14"
            ]
        )

        if df.empty:

            continue

        last = df.iloc[-1]

        previous = df.iloc[-2]

        latest_date = pd.Timestamp(df.index[-1])

        if latest_date.tzinfo is not None:

            latest_date = latest_date.tz_localize(None)

        current_date = pd.Timestamp.today().normalize()

        age_days = (
            current_date - latest_date.normalize()
        ).days

        # لا نستخدم بيانات قديمة لإصدار توصية شراء
        data_fresh = age_days <= 5

        price = float(last["Close"])

        rsi = float(last["RSI14"])

        atr = float(last["ATR14"])

        sma20 = float(last["SMA20"])

        sma50 = float(last["SMA50"])

        sma200 = float(last["SMA200"])

        macd = float(last["MACD"])

        macd_signal = float(last["MACD_SIGNAL"])

        daily_change = float(
            last["DAILY_CHANGE_PCT"]
        )

        volume_ratio = last.get(
            "VOLUME_RATIO",
            np.nan
        )

        # -------------------------------------------------------------
        # 8. احتساب الدرجة الفنية
        # -------------------------------------------------------------

        score = 0

        # الاتجاه قصير المدى
        if price > sma20:
            score += 15

        # الاتجاه المتوسط
        if sma20 > sma50:
            score += 15

        # الاتجاه طويل المدى
        if sma50 > sma200:
            score += 15

        # تقاطع MACD
        if macd > macd_signal:
            score += 15

        # مؤشر القوة النسبية
        if 50 <= rsi <= 68:
            score += 15

        elif 40 <= rsi < 50:
            score += 5

        # حجم التداول
        if pd.notna(volume_ratio):

            if volume_ratio >= 1.2:
                score += 10

        # حركة السعر اليومية
        if daily_change > 0:
            score += 5

        score = min(score, 100)

        # -------------------------------------------------------------
        # 9. تحديد الاتجاه
        # -------------------------------------------------------------

        if price > sma20 and sma20 > sma50:

            trend = "صاعد"

        elif price < sma20 and sma20 < sma50:

            trend = "هابط"

        else:

            trend = "متذبذب"

        # -------------------------------------------------------------
        # 10. مستويات المخاطرة والأهداف
        # -------------------------------------------------------------

        stop_loss = price - (2 * atr)

        target1 = price + (2 * atr)

        target2 = price + (3 * atr)

        # -------------------------------------------------------------
        # 11. تحديد العملة
        # -------------------------------------------------------------

        if ticker.endswith(".SR"):

            currency_rate = 1.0

            market = "السوق السعودي"

        else:

            currency_rate = USD_TO_SAR

            market = "السوق الأمريكي"

        price_sar = price * currency_rate

        stop_distance_sar = (
            price - stop_loss
        ) * currency_rate

        # -------------------------------------------------------------
        # 12. حساب الكمية النظرية
        # -------------------------------------------------------------

        if stop_distance_sar > 0:

            qty_by_risk = int(
                RISK_BUDGET_SAR /
                stop_distance_sar
            )

        else:

            qty_by_risk = 0

        qty_by_position = int(
            MAX_POSITION_SAR /
            price_sar
        ) if price_sar > 0 else 0

        theoretical_quantity = max(
            0,
            min(
                qty_by_risk,
                qty_by_position
            )
        )

        theoretical_position_sar = (
            theoretical_quantity * price_sar
        )

        theoretical_risk_sar = (
            theoretical_quantity *
            stop_distance_sar
        )

        # -------------------------------------------------------------
        # 13. تحديد الإشارة الفنية
        # -------------------------------------------------------------

        if not data_fresh:

            recommendation = "بيانات قديمة - لا توصية"

        elif (
            score >= 75
            and price > sma20
            and 50 <= rsi <= 68
            and macd > macd_signal
            and theoretical_quantity > 0
        ):

            recommendation = "مرشح شراء - انتظار التأكيد"

        elif score >= 50:

            recommendation = "مراقبة - لا شراء الآن"

        else:

            recommendation = "تجنب الدخول"

        analysis_results.append({

            "ticker": ticker,

            "market": market,

            "latest_close": round(price, 4),

            "latest_date": latest_date.strftime(
                "%Y-%m-%d"
            ),

            "data_age_days": age_days,

            "data_fresh": data_fresh,

            "daily_change_pct": round(
                daily_change,
                2
            ),

            "RSI14": round(rsi, 2),

            "SMA20": round(sma20, 4),

            "SMA50": round(sma50, 4),

            "SMA200": round(sma200, 4),

            "MACD": round(macd, 4),

            "MACD_SIGNAL": round(
                macd_signal,
                4
            ),

            "ATR14": round(atr, 4),

            "trend": trend,

            "technical_score": score,

            "recommendation": recommendation,

            "stop_loss": round(
                stop_loss,
                4
            ),

            "target1": round(
                target1,
                4
            ),

            "target2": round(
                target2,
                4
            ),

            "quantity_before_portfolio_limit": (
                theoretical_quantity
            ),

            "position_value_sar": round(
                theoretical_position_sar,
                2
            ),

            "risk_sar": round(
                theoretical_risk_sar,
                2
            ),

            "currency_rate": currency_rate,

        })

        print(
            f"✅ {ticker}: "
            f"الدرجة {score}/100 | "
            f"{recommendation}"
        )

    except Exception as e:

        print(
            f"⚠️ خطأ في تحليل {ticker}: "
            f"{str(e)[:150]}"
        )


# ---------------------------------------------------------------------
# 14. إنشاء التقرير النهائي
# ---------------------------------------------------------------------

wadq_phase87_df = pd.DataFrame(
    analysis_results
)

if wadq_phase87_df.empty:

    raise ValueError(
        "لم يتم إنشاء التقرير. "
        "تحققي من اتصال الإنترنت وتوفر بيانات الأسهم."
    )


# ---------------------------------------------------------------------
# 15. تطبيق حد رأس المال الإجمالي
# ---------------------------------------------------------------------

wadq_phase87_df = wadq_phase87_df.sort_values(
    by="technical_score",
    ascending=False
).reset_index(drop=True)

wadq_phase87_df["recommended_quantity"] = 0

wadq_phase87_df["recommended_position_sar"] = 0.0

wadq_phase87_df["recommended_risk_sar"] = 0.0

remaining_capital = CAPITAL_SAR

for i, row in wadq_phase87_df.iterrows():

    if row["recommendation"] != "مرشح شراء - انتظار التأكيد":

        continue

    if remaining_capital <= 0:

        break

    price_sar = (
        row["latest_close"] *
        row["currency_rate"]
    )

    stop_distance_sar = (
        row["latest_close"] -
        row["stop_loss"]
    ) * row["currency_rate"]

    if price_sar <= 0 or stop_distance_sar <= 0:

        continue

    qty_by_risk = int(
        RISK_BUDGET_SAR /
        stop_distance_sar
    )

    qty_by_position = int(
        MAX_POSITION_SAR /
        price_sar
    )

    qty_by_remaining = int(
        remaining_capital /
        price_sar
    )

    quantity = max(
        0,
        min(
            qty_by_risk,
            qty_by_position,
            qty_by_remaining
        )
    )

    position_value = quantity * price_sar

    risk_value = (
        quantity *
        stop_distance_sar
    )

    if quantity > 0:

        wadq_phase87_df.loc[
            i,
            "recommended_quantity"
        ] = quantity

        wadq_phase87_df.loc[
            i,
            "recommended_position_sar"
        ] = round(position_value, 2)

        wadq_phase87_df.loc[
            i,
            "recommended_risk_sar"
        ] = round(risk_value, 2)

        remaining_capital -= position_value


# ---------------------------------------------------------------------
# 16. إنشاء قائمة الفرص
# ---------------------------------------------------------------------

wadq_phase87_opportunities_df = (
    wadq_phase87_df[
        wadq_phase87_df["recommendation"]
        == "مرشح شراء - انتظار التأكيد"
    ].copy()
)

wadq_phase87_watchlist_df = (
    wadq_phase87_df[
        wadq_phase87_df["recommendation"]
        == "مراقبة - لا شراء الآن"
    ].copy()
)

wadq_phase87_avoid_df = (
    wadq_phase87_df[
        wadq_phase87_df["recommendation"]
        == "تجنب الدخول"
    ].copy()
)


# ---------------------------------------------------------------------
# 17. التقرير النهائي
# ---------------------------------------------------------------------

print("\n" + "=" * 70)
print("🌧️ الودق AI — التقرير النهائي للمرحلة 87")
print("=" * 70)

print(
    "\nعدد الأسهم التي تم تحليلها:",
    len(wadq_phase87_df)
)

print(
    "عدد مرشحي الشراء:",
    len(wadq_phase87_opportunities_df)
)

print(
    "عدد الأسهم للمراقبة:",
    len(wadq_phase87_watchlist_df)
)

print(
    "عدد الأسهم التي تم تجنبها:",
    len(wadq_phase87_avoid_df)
)

print(
    "\nقيمة رأس المال:",
    f"{CAPITAL_SAR:,.2f} ريال"
)

print(
    "قيمة التوصيات النظرية:",
    f"{wadq_phase87_df['recommended_position_sar'].sum():,.2f} ريال"
)

print(
    "إجمالي المخاطر النظرية:",
    f"{wadq_phase87_df['recommended_risk_sar'].sum():,.2f} ريال"
)


# ---------------------------------------------------------------------
# 18. عرض جدول التوصيات
# ---------------------------------------------------------------------

display_columns = [

    "ticker",

    "market",

    "latest_close",

    "latest_date",

    "daily_change_pct",

    "RSI14",

    "trend",

    "technical_score",

    "recommendation",

    "stop_loss",

    "target1",

    "target2",

    "recommended_quantity",

    "recommended_position_sar",

    "recommended_risk_sar",

    "data_fresh"

]

print("\n📊 جدول التوصيات:")

display(
    wadq_phase87_df[
        display_columns
    ].sort_values(
        "technical_score",
        ascending=False
    )
)


# ---------------------------------------------------------------------
# 19. عرض مرشحي الشراء
# ---------------------------------------------------------------------

print("\n" + "=" * 70)
print("🎯 مرشحو الشراء - انتظار التأكيد")
print("=" * 70)

if not wadq_phase87_opportunities_df.empty:

    display(
        wadq_phase87_opportunities_df[
            display_columns
        ]
    )

else:

    print(
        "لا توجد أسهم استوفت شروط الشراء حاليًا. "
        "عدم وجود توصيات أفضل من إصدار توصيات غير مستوفية للشروط."
    )


# ---------------------------------------------------------------------
# 20. حفظ النتائج في متغيرات جديدة
# ---------------------------------------------------------------------

wadq_phase87_summary_df = pd.DataFrame([{

    "execution_time": datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    ),

    "assets_analyzed": len(
        wadq_phase87_df
    ),

    "buy_candidates": len(
        wadq_phase87_opportunities_df
    ),

    "watchlist_count": len(
        wadq_phase87_watchlist_df
    ),

    "avoid_count": len(
        wadq_phase87_avoid_df
    ),

    "capital_sar": CAPITAL_SAR,

    "total_recommended_position_sar": round(
        wadq_phase87_df[
            "recommended_position_sar"
        ].sum(),
        2
    ),

    "total_theoretical_risk_sar": round(
        wadq_phase87_df[
            "recommended_risk_sar"
        ].sum(),
        2
    ),

    "live_trading_executed": False

}])


print("\n" + "=" * 70)
print("✅ انتهت المرحلة 87")
print("=" * 70)

print("تم إنشاء الجداول الجديدة:")

print("1. wadq_phase87_df")
print("2. wadq_phase87_opportunities_df")
print("3. wadq_phase87_watchlist_df")
print("4. wadq_phase87_avoid_df")
print("5. wadq_phase87_summary_df")

print("\nلم يتم تعديل الجداول الأصلية.")
print("لم يتم تنفيذ أي تداول حقيقي.")
print("التوصيات نظرية وتعتمد على البيانات المتاحة من Yahoo Finance.")

======================================================================
🌧️ الودق AI — المرحلة 87
محرك التوصيات الشامل
======================================================================
رأس المال: 10,000 ريال
ميزانية المخاطرة للصفقة: 100 ريال
الحد الأقصى لقيمة الصفقة: 2,000 ريال

عدد الأسهم المراد تحليلها: 22

🔄 تحديث الأسعار والبيانات التاريخية...

ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: GRYP"}}}
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['GRYP']: YFPricesMissingError('possibly delisted; no price data found  (period=1y) (Yahoo error = "No data found, symbol may be delisted")')

🔍 بدء التحليل الفني...
✅ AAPL: الدرجة 90/100 | مرشح شراء - انتظار التأكيد
✅ 1120.SR: الدرجة 5/100 | تجنب الدخول
✅ 2010.SR: الدرجة 20/100 | تجنب الدخول
✅ 2222.SR: الدرجة 65/100 | مراقبة - لا شراء الآن
✅ SPY: الدرجة 45/100 | تجنب الدخول
✅ NVDA: الدرجة 30/100 | تجنب الدخول
✅ AMZN: الدرجة 35/100 | تجنب الدخول
✅ MSFT: الدرجة 75/100 | مرشح شراء - انتظار التأكيد
✅ TSLA: الدرجة 30/100 | تجنب الدخول
✅ GOOGL: الدرجة 35/100 | تجنب الدخول
✅ QQQ: الدرجة 40/100 | تجنب الدخول
✅ META: الدرجة 45/100 | تجنب الدخول
✅ ARAY: الدرجة 0/100 | تجنب الدخول
✅ SLXN: الدرجة 15/100 | تجنب الدخول
✅ SOAR: الدرجة 20/100 | تجنب الدخول
✅ GPRO: الدرجة 30/100 | تجنب الدخول
✅ ARBE: الدرجة 0/100 | تجنب الدخول
✅ WKHS: الدرجة 10/100 | تجنب الدخول
✅ HIMX: الدرجة 15/100 | تجنب الدخول
⚠️ GRYP: لا توجد بيانات
✅ OPEN: الدرجة 25/100 | تجنب الدخول
✅ BBAI: الدرجة 0/100 | تجنب الدخول

======================================================================
🌧️ الودق AI — التقرير النهائي للمرحلة 87
======================================================================

عدد الأسهم التي تم تحليلها: 21
عدد مرشحي الشراء: 2
عدد الأسهم للمراقبة: 1
عدد الأسهم التي تم تجنبها: 18

قيمة رأس المال: 10,000.00 ريال
قيمة التوصيات النظرية: 3,271.91 ريال
إجمالي المخاطر النظرية: 138.23 ريال

📊 جدول التوصيات:

,ticker,market,latest_close,latest_date,daily_change_pct,RSI14,trend,technical_score,recommendation,stop_loss,target1,target2,recommended_quantity,recommended_position_sar,recommended_risk_sar,data_fresh
0,AAPL,السوق الأمريكي,343.460,2026-10-16,0.43,62.08,صاعد,90,مرشح شراء - انتظار التأكيد,330.0800,356.8400,363.5300,1,1287.97,50.17,True
1,MSFT,السوق الأمريكي,529.050,2026-10-16,-1.93,57.36,صاعد,75,مرشح شراء - انتظار التأكيد,505.5686,552.5314,564.2721,1,1983.94,88.06,True
2,2222.SR,السوق السعودي,25.800,2026-10-18,2.06,52.58,متذبذب,65,مراقبة - لا شراء الآن,25.1943,26.4057,26.7086,0,0.00,0.00,True
3,META,السوق الأمريكي,709.330,2026-10-16,-3.72,50.26,متذبذب,45,تجنب الدخول,665.1014,753.5586,775.6729,0,0.00,0.00,True
4,SPY,السوق الأمريكي,763.250,2026-10-16,-1.11,44.19,متذبذب,45,تجنب الدخول,749.4771,777.0229,783.9093,0,0.00,0.00,True
5,QQQ,السوق الأمريكي,709.800,2026-10-16,-2.50,35.14,متذبذب,40,تجنب الدخول,689.6414,729.9585,740.0378,0,0.00,0.00,True
6,AMZN,السوق الأمريكي,250.000,2026-10-16,-1.87,44.99,هابط,35,تجنب الدخول,238.1957,261.8043,267.7064,0,0.00,0.00,True
7,GOOGL,السوق الأمريكي,340.590,2026-10-16,-2.47,44.47,متذبذب,35,تجنب الدخول,322.6686,358.5114,367.4721,0,0.00,0.00,True
8,NVDA,السوق الأمريكي,214.130,2026-10-16,-1.43,37.56,متذبذب,30,تجنب الدخول,202.6071,225.6529,231.4143,0,0.00,0.00,True
9,TSLA,السوق الأمريكي,354.720,2026-10-16,-2.13,42.20,متذبذب,30,تجنب الدخول,333.0057,376.4343,387.2914,0,0.00,0.00,True
10,GPRO,السوق الأمريكي,1.050,2026-10-16,-8.70,37.45,متذبذب,30,تجنب الدخول,0.9239,1.1761,1.2392,0,0.00,0.00,True
11,OPEN,السوق الأمريكي,2.115,2026-10-16,-8.84,35.98,هابط,25,تجنب الدخول,1.7866,2.4434,2.6076,0,0.00,0.00,True
12,2010.SR,السوق السعودي,45.720,2026-10-18,2.60,41.08,هابط,20,تجنب الدخول,43.9914,47.4486,48.3129,0,0.00,0.00,True
13,SOAR,السوق الأمريكي,0.232,2026-10-16,-0.43,47.32,متذبذب,20,تجنب الدخول,0.1310,0.3330,0.3835,0,0.00,0.00,True
14,HIMX,السوق الأمريكي,11.650,2026-10-16,-3.80,32.00,هابط,15,تجنب الدخول,10.3557,12.9443,13.5914,0,0.00,0.00,True
15,SLXN,السوق الأمريكي,0.153,2026-10-16,-19.05,29.55,هابط,15,تجنب الدخول,0.0733,0.2327,0.2726,0,0.00,0.00,True
16,WKHS,السوق الأمريكي,2.640,2026-10-16,-8.97,31.75,هابط,10,تجنب الدخول,2.3824,2.8976,3.0264,0,0.00,0.00,True
17,1120.SR,السوق السعودي,61.150,2026-10-18,0.25,35.53,هابط,5,تجنب الدخول,59.5143,62.7857,63.6036,0,0.00,0.00,True
18,ARAY,السوق الأمريكي,0.160,2026-10-16,-5.88,29.58,هابط,0,تجنب الدخول,0.0957,0.2243,0.2564,0,0.00,0.00,True
19,ARBE,السوق الأمريكي,0.460,2026-10-16,-5.54,23.53,هابط,0,تجنب الدخول,0.3863,0.5337,0.5706,0,0.00,0.00,True
20,BBAI,السوق الأمريكي,2.160,2026-10-16,-7.30,30.74,هابط,0,تجنب الدخول,1.8367,2.4833,2.6449,0,0.00,0.00,True

======================================================================
🎯 مرشحو الشراء - انتظار التأكيد
======================================================================

,ticker,market,latest_close,latest_date,daily_change_pct,RSI14,trend,technical_score,recommendation,stop_loss,target1,target2,recommended_quantity,recommended_position_sar,recommended_risk_sar,data_fresh
0,AAPL,السوق الأمريكي,343.46,2026-10-16,0.43,62.08,صاعد,90,مرشح شراء - انتظار التأكيد,330.0800,356.8400,363.5300,1,1287.97,50.17,True
1,MSFT,السوق الأمريكي,529.05,2026-10-16,-1.93,57.36,صاعد,75,مرشح شراء - انتظار التأكيد,505.5686,552.5314,564.2721,1,1983.94,88.06,True

======================================================================
✅ انتهت المرحلة 87
======================================================================
تم إنشاء الجداول الجديدة:
1. wadq_phase87_df
2. wadq_phase87_opportunities_df
3. wadq_phase87_watchlist_df
4. wadq_phase87_avoid_df
5. wadq_phase87_summary_df

لم يتم تعديل الجداول الأصلية.
لم يتم تنفيذ أي تداول حقيقي.
التوصيات نظرية وتعتمد على البيانات المتاحة من Yahoo Finance.

In [ ]:
import os

base = "/content/drive/MyDrive/colab Notebooks"

for root, dirs, files in os.walk(base):
    for file in files:
        if file.endswith(".ipynb"):
            print(os.path.join(root, file))

In [28]:
# =====================================================================
# 🌧️ الودق AI — المرحلة 89 (نسخة مصححة)
# رأس مال مرن + إدارة المخاطر + العملات
# =====================================================================

import math
from datetime import datetime

print("=" * 60)
print("🌧️ الودق AI — المرحلة 89")
print("إعداد رأس المال وإدارة المخاطر")
print("=" * 60)

# ------------------------------------------------------------
# 1. إدخال رأس المال
# ------------------------------------------------------------

capital_sar = float(
    input("أدخلي رأس المال المتاح بالريال السعودي: ")
)

if capital_sar <= 0:
    raise ValueError("رأس المال يجب أن يكون أكبر من صفر.")

# ------------------------------------------------------------
# 2. إدخال نسبة المخاطرة (الحد الأقصى 5%)
# ------------------------------------------------------------

risk_input = input(
    "نسبة المخاطرة % (الافتراضي 5، الحد الأقصى 5): "
).strip()

risk_pct = float(risk_input) if risk_input else 5.0

if risk_pct <= 0 or risk_pct > 5:
    raise ValueError("المخاطرة يجب أن تكون أكبر من صفر ولا تتجاوز 5%.")

# ------------------------------------------------------------
# 3. الحد الأقصى لقيمة الصفقة = 100% من رأس المال
# ------------------------------------------------------------

max_position_pct = 100.0

# ------------------------------------------------------------
# 4. سعر صرف الدولار مقابل الريال
# ------------------------------------------------------------

usd_sar_input = input(
    "سعر الدولار مقابل الريال (الافتراضي 3.75): "
).strip()

usd_sar = float(usd_sar_input) if usd_sar_input else 3.75

if usd_sar <= 0:
    raise ValueError("سعر الصرف يجب أن يكون أكبر من صفر.")

# ------------------------------------------------------------
# 5. حساب الميزانية
# ------------------------------------------------------------

risk_budget_sar = capital_sar * risk_pct / 100
max_position_sar = capital_sar * max_position_pct / 100

print("\n" + "=" * 60)
print("✅ إعدادات رأس المال")
print("=" * 60)

print(f"رأس المال: {capital_sar:,.2f} SAR")
print(f"نسبة المخاطرة: {risk_pct:.2f}%")
print(f"أقصى مخاطرة للصفقة: {risk_budget_sar:,.2f} SAR")
print(f"أقصى قيمة للصفقة: {max_position_sar:,.2f} SAR")
print(f"سعر الدولار: {usd_sar:.4f} SAR")

# ------------------------------------------------------------
# 6. دالة حساب كمية الأسهم
# ------------------------------------------------------------

def wadq_calculate_position(entry_price, stop_price, market="US"):

    entry_price = float(entry_price)
    stop_price = float(stop_price)
    market = market.upper()

    if entry_price <= 0 or stop_price <= 0:
        raise ValueError("سعر الدخول ووقف الخسارة يجب أن يكونا أكبر من صفر.")

    if entry_price == stop_price:
        raise ValueError("سعر الدخول يجب أن يختلف عن وقف الخسارة.")

    if market == "US":
        capital_market = capital_sar / usd_sar
        risk_budget_market = risk_budget_sar / usd_sar
        currency = "USD"

    elif market == "SA":
        capital_market = capital_sar
        risk_budget_market = risk_budget_sar
        currency = "SAR"

    else:
        raise ValueError("السوق يجب أن يكون US أو SA.")

    # مقدار الخسارة المحتملة لكل سهم
    risk_per_share = abs(entry_price - stop_price)

    # عدد الأسهم حسب ميزانية المخاطرة
    qty_by_risk = math.floor(
        risk_budget_market / risk_per_share
    )

    # عدد الأسهم حسب رأس المال المتاح
    max_position_value = capital_market * max_position_pct / 100

    qty_by_capital = math.floor(
        max_position_value / entry_price
    )

    # الكمية النهائية
    quantity = max(
        0,
        min(qty_by_risk, qty_by_capital)
    )

    position_value = quantity * entry_price
    expected_risk = quantity * risk_per_share

    print("\n" + "=" * 60)
    print("🌧️ نتيجة حساب الصفقة")
    print("=" * 60)

    print(f"السوق: {market}")
    print(f"العملة: {currency}")
    print(f"سعر الدخول: {entry_price:,.2f} {currency}")
    print(f"وقف الخسارة: {stop_price:,.2f} {currency}")
    print(f"كمية الأسهم: {quantity}")
    print(f"قيمة الصفقة: {position_value:,.2f} {currency}")
    print(f"المخاطرة المحسوبة: {expected_risk:,.2f} {currency}")

    return {
        "market": market,
        "currency": currency,
        "entry_price": entry_price,
        "stop_price": stop_price,
        "quantity": quantity,
        "position_value": position_value,
        "expected_risk": expected_risk
    }

# ------------------------------------------------------------
# 7. حفظ إعدادات المرحلة
# ------------------------------------------------------------

wadq_phase89_config = {
    "capital_sar": capital_sar,
    "risk_pct": risk_pct,
    "risk_budget_sar": risk_budget_sar,
    "max_position_pct": max_position_pct,
    "max_position_sar": max_position_sar,
    "usd_sar": usd_sar,
    "created_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
}

print("\n" + "=" * 60)
print("✅ المرحلة 89 جاهزة")
print("=" * 60)

print("لحساب صفقة أمريكية:")
print('wadq_calculate_position(50, 48, market="US")')

print("\nلحساب صفقة سعودية:")
print('wadq_calculate_position(30, 28, market="SA")')

============================================================
🌧️ الودق AI — المرحلة 89
إعداد رأس المال وإدارة المخاطر
============================================================
أدخلي رأس المال المتاح بالريال السعودي: 1000000
نسبة المخاطرة % (الافتراضي 5، الحد الأقصى 5): 5
سعر الدولار مقابل الريال (الافتراضي 3.75): 1

============================================================
✅ إعدادات رأس المال
============================================================
رأس المال: 1,000,000.00 SAR
نسبة المخاطرة: 5.00%
أقصى مخاطرة للصفقة: 50,000.00 SAR
أقصى قيمة للصفقة: 1,000,000.00 SAR
سعر الدولار: 1.0000 SAR

============================================================
✅ المرحلة 89 جاهزة
============================================================
لحساب صفقة أمريكية:
wadq_calculate_position(50, 48, market="US")

لحساب صفقة سعودية:
wadq_calculate_position(30, 28, market="SA")

In [29]:
usd_sar = 3.75
wadq_phase89_config["usd_sar"] = usd_sar

print("✅ تم تصحيح سعر الدولار")
print(f"1 USD = {usd_sar} SAR")

✅ تم تصحيح سعر الدولار
1 USD = 3.75 SAR

In [31]:
# 🌧️ الودق AI — المرحلة 90
# فحص الاتصال ومكتبة بيانات الأسهم

import importlib.util

print("=" * 50)
print("🌧️ الودق AI — المرحلة 90")
print("=" * 50)

# فحص مكتبة yfinance
yf_available = importlib.util.find_spec("yfinance") is not None

print("مكتبة yfinance متاحة:", yf_available)

# فحص اتصال الإنترنت
import requests

try:
    response = requests.get(
        "https://query1.finance.yahoo.com",
        timeout=10
    )
    print("اتصال Yahoo Finance:", response.status_code)
except Exception as e:
    print("تعذر الاتصال:", str(e))

print("=" * 50)

==================================================
🌧️ الودق AI — المرحلة 90
==================================================
مكتبة yfinance متاحة: True
اتصال Yahoo Finance: 429
==================================================

In [32]:
# 🌧️ الودق AI — اختبار اتصال Massive
import requests
from getpass import getpass

# أدخلي مفتاح Massive في الخانة المخفية
MASSIVE_API_KEY = getpass("أدخلي مفتاح Massive API (لن يظهر أثناء الكتابة): ").strip()

url = "https://api.massive.com/v2/aggs/ticker/AAPL/prev"

try:
    response = requests.get(
        url,
        params={"apiKey": MASSIVE_API_KEY},
        timeout=20
    )

    print("رمز الاستجابة:", response.status_code)

    if response.status_code == 200:
        data = response.json()
        print("اتصال Massive ناجح")
        print("عدد النتائج:", len(data.get("results", [])))
        print("حالة البيانات:", data.get("status"))
    else:
        print("تعذر الحصول على البيانات.")
        print("رسالة الخطأ:", response.text[:300])

except Exception as e:
    print("حدث خطأ في الاتصال:", str(e))

أدخلي مفتاح Massive API (لن يظهر أثناء الكتابة): ··········
رمز الاستجابة: 200
اتصال Massive ناجح
عدد النتائج: 1
حالة البيانات: OK

In [ ]:
import os

path = "/content/drive/MyDrive/colab Notebooks"

print("Folder exists:", os.path.exists(path))

if os.path.exists(path):
    print("Files:")
    print(os.listdir(path))

Folder exists: False

In [ ]:
import os

print("Current location:")
print(os.listdir("/content"))

print("\nDrive location:")
if os.path.exists("/content/drive"):
    print(os.listdir("/content/drive"))
else:
    print("Drive is not mounted")

Current location:
['.config', 'drive', 'sample_data']

Drive location:
['.shortcut-targets-by-id', 'MyDrive', '.Trash-0', '.Encrypted']

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# البحث الشامل عن ملفات المشروع والجداول المحفوظة
# الكود للفحص فقط: لا يحذف أو يعدل أي ملف
# ============================================================

import os
import glob
import pandas as pd

print("=" * 70)
print("🌧️ الودق AI — البحث الشامل عن الملفات والجداول")
print("=" * 70)

# ------------------------------------------------------------
# 1) التأكد من اتصال Google Drive
# ------------------------------------------------------------

try:
    from google.colab import drive

    if not os.path.exists("/content/drive/MyDrive"):
        drive.mount("/content/drive")

except Exception as e:
    print("تنبيه اتصال Drive:", e)

# ------------------------------------------------------------
# 2) تجربة جميع المسارات المحتملة
# ------------------------------------------------------------

possible_paths = [
    "/content/drive/MyDrive",
    "/content/drive/My Drive",
    "/content/drive",
    "/content",
    "/content/drive/MyDrive/colab Notebooks",
    "/content/drive/MyDrive/Colab Notebooks",
    "/content/drive/MyDrive/الودق AI",
    "/content/drive/MyDrive/الودق_AI",
    "/content/drive/MyDrive/Copy of الودق AI",
    "/content/drive/MyDrive/سجل المشروع - الودق AI",
    "/content/drive/MyDrive/نسخة احتياطية الودق AI",
]

print("\n📁 فحص المسارات المحتملة:")

for path in possible_paths:
    if os.path.exists(path):
        print("✅ موجود:", path)
    else:
        print("❌ غير موجود:", path)

# ------------------------------------------------------------
# 3) البحث في Google Drive بالكامل
# ------------------------------------------------------------

search_root = "/content/drive/MyDrive"

project_keywords = [
    "wadq",
    "الودق",
    "سجل المشروع",
    "نسخة احتياطية",
    "backup",
    "colab",
]

excel_extensions = (".xlsx", ".xls", ".xlsm")
data_extensions = (".csv", ".pkl", ".pickle", ".parquet")
notebook_extension = ".ipynb"

found_excel = []
found_data = []
found_notebooks = []
found_project_folders = []

if os.path.exists(search_root):

    for root, dirs, files in os.walk(search_root):

        # البحث عن مجلدات المشروع
        for folder in dirs:
            folder_lower = folder.lower()

            if any(keyword.lower() in folder_lower
                   for keyword in project_keywords):

                found_project_folders.append(
                    os.path.join(root, folder)
                )

        # البحث عن الملفات
        for file in files:

            file_lower = file.lower()
            full_path = os.path.join(root, file)

            if file_lower.endswith(excel_extensions):
                found_excel.append(full_path)

            elif file_lower.endswith(data_extensions):
                found_data.append(full_path)

            elif file_lower.endswith(notebook_extension):
                if any(keyword.lower() in file_lower
                       for keyword in project_keywords):

                    found_notebooks.append(full_path)

else:
    print("\n⚠️ لم يتم العثور على MyDrive.")
    print("تحققي من اتصال Google Drive.")

# ------------------------------------------------------------
# 4) عرض مجلدات المشروع
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("📁 مجلدات المشروع المحتملة")
print("=" * 70)

if found_project_folders:
    for folder in sorted(set(found_project_folders)):
        print("\n📂", folder)

else:
    print("لم يعثر على مجلدات تحمل أسماء المشروع.")

# ------------------------------------------------------------
# 5) عرض ملفات Excel
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("📊 ملفات Excel المكتشفة")
print("=" * 70)

if found_excel:

    for i, path in enumerate(sorted(set(found_excel)), 1):

        try:
            size_mb = os.path.getsize(path) / (1024 * 1024)

            print(f"\n{i}. {os.path.basename(path)}")
            print("المسار:", path)
            print(f"الحجم: {size_mb:.2f} MB")

        except Exception:
            print("\n", path)

else:
    print("⚠️ لم يتم العثور على ملفات Excel.")

# ------------------------------------------------------------
# 6) عرض ملفات البيانات الأخرى
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("📄 ملفات CSV و Pickle و Parquet")
print("=" * 70)

if found_data:

    for i, path in enumerate(sorted(set(found_data)), 1):

        print(f"\n{i}. {os.path.basename(path)}")
        print("المسار:", path)

else:
    print("لم يعثر على ملفات بيانات بهذه الامتدادات.")

# ------------------------------------------------------------
# 7) البحث عن دفاتر المشروع
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("📓 دفاتر Google Colab المحتملة")
print("=" * 70)

if found_notebooks:

    for i, path in enumerate(sorted(set(found_notebooks)), 1):

        print(f"\n{i}. {os.path.basename(path)}")
        print("المسار:", path)

else:
    print("لم يعثر على دفاتر بأسماء المشروع.")

# ------------------------------------------------------------
# 8) البحث عن الجداول الموجودة حاليًا في ذاكرة Colab
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("📈 الجداول الموجودة حاليًا في ذاكرة المشروع")
print("=" * 70)

table_names = [
    "wadq_stage67_audit_df",
    "wadq_stage67_review_df",
    "wadq_stage67_passed_df",
    "wadq_stage67_summary_df",
    "wadq_stage67_log_df",
    "wadq_stage66_final_report_df",
    "wadq_final_ai_report",
    "wadq_smart_report",
    "wadq_evaluation_df",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_unified_report_df",
]

for name in table_names:

    if name in globals():

        obj = globals()[name]

        if isinstance(obj, pd.DataFrame):

            print(
                f"✅ {name} | "
                f"الصفوف: {obj.shape[0]} | "
                f"الأعمدة: {obj.shape[1]}"
            )

        else:
            print(f"⚠️ {name} موجود ولكنه ليس DataFrame.")

    else:
        print(f"❌ {name} غير موجود في الذاكرة الحالية.")

# ------------------------------------------------------------
# 9) البحث عن جميع الجداول DataFrame في الذاكرة
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("🔍 جميع الجداول الموجودة في الذاكرة")
print("=" * 70)

all_tables = []

for name, obj in list(globals().items()):

    try:

        if isinstance(obj, pd.DataFrame):

            all_tables.append({
                "اسم الجدول": name,
                "عدد الصفوف": obj.shape[0],
                "عدد الأعمدة": obj.shape[1],
                "أسماء الأعمدة": list(obj.columns),
            })

    except Exception:
        pass

if all_tables:

    for table in all_tables:

        print(
            f"\n📊 {table['اسم الجدول']}"
            f"\nالصفوف: {table['عدد الصفوف']}"
            f"\nالأعمدة: {table['عدد الأعمدة']}"
        )

else:
    print("لا توجد جداول DataFrame في ذاكرة Colab.")

# ------------------------------------------------------------
# 10) التقرير النهائي
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("🌧️ انتهى البحث الشامل")
print("=" * 70)

print("عدد ملفات Excel:", len(set(found_excel)))
print("عدد ملفات البيانات:", len(set(found_data)))
print("عدد دفاتر المشروع:", len(set(found_notebooks)))
print("عدد مجلدات المشروع:", len(set(found_project_folders)))
print("عدد الجداول الموجودة في الذاكرة:", len(all_tables))

print("\n📌 أرسلي لي صورة نتيجة هذا الكود.")
print("سنحدد منها مكان ملف Excel وسجل المشروع،")
print("ثم نستعيد الجداول المفقودة من المصدر الصحيح.")

======================================================================
🌧️ الودق AI — البحث الشامل عن الملفات والجداول
======================================================================

📁 فحص المسارات المحتملة:
✅ موجود: /content/drive/MyDrive
✅ موجود: /content/drive/My Drive
✅ موجود: /content/drive
✅ موجود: /content
❌ غير موجود: /content/drive/MyDrive/colab Notebooks
✅ موجود: /content/drive/MyDrive/Colab Notebooks
❌ غير موجود: /content/drive/MyDrive/الودق AI
❌ غير موجود: /content/drive/MyDrive/الودق_AI
❌ غير موجود: /content/drive/MyDrive/Copy of الودق AI
❌ غير موجود: /content/drive/MyDrive/سجل المشروع - الودق AI
❌ غير موجود: /content/drive/MyDrive/نسخة احتياطية الودق AI

======================================================================
📁 مجلدات المشروع المحتملة
======================================================================

📂 /content/drive/MyDrive/Colab Notebooks

📂 /content/drive/MyDrive/الودق AI - سجل المشروع

📂 /content/drive/MyDrive/الودق_AI_نسخة_احتياطية

======================================================================
📊 ملفات Excel المكتشفة
======================================================================
⚠️ لم يتم العثور على ملفات Excel.

======================================================================
📄 ملفات CSV و Pickle و Parquet
======================================================================
لم يعثر على ملفات بيانات بهذه الامتدادات.

======================================================================
📓 دفاتر Google Colab المحتملة
======================================================================
لم يعثر على دفاتر بأسماء المشروع.

======================================================================
📈 الجداول الموجودة حاليًا في ذاكرة المشروع
======================================================================
❌ wadq_stage67_audit_df غير موجود في الذاكرة الحالية.
❌ wadq_stage67_review_df غير موجود في الذاكرة الحالية.
❌ wadq_stage67_passed_df غير موجود في الذاكرة الحالية.
❌ wadq_stage67_summary_df غير موجود في الذاكرة الحالية.
❌ wadq_stage67_log_df غير موجود في الذاكرة الحالية.
❌ wadq_stage66_final_report_df غير موجود في الذاكرة الحالية.
❌ wadq_final_ai_report غير موجود في الذاكرة الحالية.
❌ wadq_smart_report غير موجود في الذاكرة الحالية.
❌ wadq_evaluation_df غير موجود في الذاكرة الحالية.
❌ wadq_global_master_report_df غير موجود في الذاكرة الحالية.
❌ wadq_global_integrated_df غير موجود في الذاكرة الحالية.
❌ wadq_global_alerts_df غير موجود في الذاكرة الحالية.
❌ wadq_stage66_unified_report_df غير موجود في الذاكرة الحالية.

======================================================================
🔍 جميع الجداول الموجودة في الذاكرة
======================================================================
لا توجد جداول DataFrame في ذاكرة Colab.

======================================================================
🌧️ انتهى البحث الشامل
======================================================================
عدد ملفات Excel: 0
عدد ملفات البيانات: 0
عدد دفاتر المشروع: 0
عدد مجلدات المشروع: 3
عدد الجداول الموجودة في الذاكرة: 0

📌 أرسلي لي صورة نتيجة هذا الكود.
سنحدد منها مكان ملف Excel وسجل المشروع،
ثم نستعيد الجداول المفقودة من المصدر الصحيح.

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68B
# فحص محتويات مجلدات المشروع والنسخ الاحتياطية
# ============================================================

import os

base = "/content/drive/MyDrive"

folders_to_check = [
    os.path.join(base, "الودق AI - سجل المشروع"),
    os.path.join(base, "الودق_AI_نسخة_احتياطية"),
    os.path.join(base, "Colab Notebooks"),
]

for folder in folders_to_check:

    print("\n" + "=" * 70)
    print("📂 المجلد:", folder)
    print("=" * 70)

    if not os.path.exists(folder):
        print("❌ المجلد غير موجود")
        continue

    count = 0

    for root, dirs, files in os.walk(folder):

        # عرض الملفات الموجودة
        for file in files:

            full_path = os.path.join(root, file)

            try:
                size = os.path.getsize(full_path)
            size_kb = size / 1024

            print("\n📄 الملف:", file)
            print("📍 المسار:", full_path)
            print(f"📦 الحجم: {size_kb:.2f} KB")

            count += 1

        # عرض المجلدات الفرعية
        for directory in dirs:
            print("\n📁 مجلد فرعي:", directory)

    if count == 0:
        print("⚠️ لا توجد ملفات داخل هذا المجلد")

    print("\nإجمالي الملفات:", count)

print("\n" + "=" * 70)
print("🌧️ انتهى فحص مجلدات المشروع")
print("=" * 70)# ============================================================
# 🌧️ الودق AI — المرحلة 68B
# فحص محتويات مجلدات المشروع والنسخ الاحتياطية
# ============================================================

import os

base = "/content/drive/MyDrive"

folders_to_check = [
    os.path.join(base, "الودق AI - سجل المشروع"),
    os.path.join(base, "الودق_AI_نسخة_احتياطية"),
    os.path.join(base, "Colab Notebooks"),
]

for folder in folders_to_check:

    print("\n" + "=" * 70)
    print("📂 المجلد:", folder)
    print("=" * 70)

    if not os.path.exists(folder):
        print("❌ المجلد غير موجود")
        continue

    count = 0

    for root, dirs, files in os.walk(folder):

        # عرض الملفات الموجودة
        for file in files:

            full_path = os.path.join(root, file)

            try:
                size = os.path.getsize(full_path)
            size_kb = size / 1024

            print("\n📄 الملف:", file)
            print("📍 المسار:", full_path)
            print(f"📦 الحجم: {size_kb:.2f} KB")

            count += 1

        # عرض المجلدات الفرعية
        for directory in dirs:
            print("\n📁 مجلد فرعي:", directory)

    if count == 0:
        print("⚠️ لا توجد ملفات داخل هذا المجلد")

    print("\nإجمالي الملفات:", count)

print("\n" + "=" * 70)
print("🌧️ انتهى فحص مجلدات المشروع")
print("=" * 70)

SyntaxError: expected 'except' or 'finally' block (2977621071.py, line 37)

In [ ]:
import os

base = "/content/drive/MyDrive"

folders = [
    base + "/الودق AI - سجل المشروع",
    base + "/الودق_AI_نسخة_احتياطية",
    base + "/Colab Notebooks"
]

print("=" * 60)
print("🌧️ الودق AI — فحص الملفات")
print("=" * 60)

for folder in folders:

    print("\n📂 المجلد:")
    print(folder)

    if not os.path.exists(folder):
        print("❌ المجلد غير موجود")
        continue

    count = 0

    for root, dirs, files in os.walk(folder):

        for file in files:

            full_path = os.path.join(root, file)
            size = os.path.getsize(full_path)
            size_kb = size / 1024

            print("\n📄 اسم الملف:", file)
            print("📍 المسار:", full_path)
            print("📦 الحجم:", round(size_kb, 2), "KB")

            count += 1

    print("\nإجمالي الملفات:", count)

print("\n" + "=" * 60)
print("انتهى الفحص")
print("=" * 60)

============================================================
🌧️ الودق AI — فحص الملفات
============================================================

📂 المجلد:
/content/drive/MyDrive/الودق AI - سجل المشروع

📄 اسم الملف: سجل_الودق_AI.txt
📍 المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt
📦 الحجم: 2.75 KB

📄 اسم الملف: سجل_الاستئناف.txt
📍 المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الاستئناف.txt
📦 الحجم: 0.19 KB

📄 اسم الملف: سجل_الودق_AI.gdoc
📍 المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.gdoc
📦 الحجم: 0.17 KB

إجمالي الملفات: 3

📂 المجلد:
/content/drive/MyDrive/الودق_AI_نسخة_احتياطية

إجمالي الملفات: 0

📂 المجلد:
/content/drive/MyDrive/Colab Notebooks

📄 اسم الملف: Copy of الودقAI
📍 المسار: /content/drive/MyDrive/Colab Notebooks/Copy of الودقAI
📦 الحجم: 4224.79 KB

إجمالي الملفات: 1

============================================================
انتهى الفحص
============================================================

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68C
# قراءة السجلات وفحص دفتر المشروع
# ============================================================

import os
import json

base = "/content/drive/MyDrive"

# ------------------------------------------------------------
# 1) قراءة سجل المشروع وسجل الاستئناف
# ------------------------------------------------------------

log_files = [
    base + "/الودق AI - سجل المشروع/سجل_الودق_AI.txt",
    base + "/الودق AI - سجل المشروع/سجل_الاستئناف.txt"
]

for path in log_files:

    print("\n" + "=" * 70)
    print("📄 قراءة الملف:", os.path.basename(path))
    print("=" * 70)

    if os.path.isfile(path):

        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        print(content)

    else:
        print("⚠️ الملف غير موجود")

# ------------------------------------------------------------
# 2) فحص دفتر المشروع
# ------------------------------------------------------------

notebook_path = (
    base + "/Colab Notebooks/Copy of الودقAI"
)

print("\n" + "=" * 70)
print("📓 فحص دفتر المشروع")
print("=" * 70)

if os.path.isfile(notebook_path):

    print("✅ دفتر المشروع موجود")
    print("الحجم:", round(os.path.getsize(notebook_path) / 1024, 2), "KB")

    with open(notebook_path, "r", encoding="utf-8") as f:
        notebook_text = f.read()

    print("\nبداية محتوى الملف:")
    print(notebook_text[:500])

    # --------------------------------------------------------
    # 3) محاولة قراءة الدفتر كملف JSON
    # --------------------------------------------------------

    try:

        notebook = json.loads(notebook_text)

        print("\n✅ تمت قراءة دفتر المشروع كـ JSON")

        cells = notebook.get("cells", [])

        print("عدد الخلايا:", len(cells))

        keywords = [
            "to_excel",
            "to_csv",
            "pickle",
            "joblib",
            "wadq_stage67",
            "wadq_stage66",
            "backup",
            "save",
            "ExcelWriter"
        ]

        print("\n" + "=" * 70)
        print("🔍 البحث عن أكواد الحفظ والاستعادة")
        print("=" * 70)

        found_count = 0

        for i, cell in enumerate(cells, 1):

            source = "".join(cell.get("source", []))

            if any(word.lower() in source.lower() for word in keywords):

                found_count += 1

                print("\n" + "-" * 60)
                print("📌 الخلية رقم:", i)
                print("-" * 60)
                print(source[:2500])

        print("\nعدد الخلايا التي تحتوي على كلمات الحفظ:",
              found_count)

    except Exception as e:

        print("\n⚠️ لم نتمكن من قراءة الملف كدفتر JSON.")
        print("قد يكون الملف اختصار Google Drive أو ملفًا بصيغة أخرى.")
        print("تفاصيل:", str(e)[:300])

else:

    print("❌ دفتر المشروع غير موجود في المسار المحدد")

print("\n" + "=" * 70)
print("🌧️ انتهى فحص المرحلة 68C")
print("=" * 70)

======================================================================
📄 قراءة الملف: سجل_الودق_AI.txt
======================================================================

============================================================
🌧️ مشروع الودق AI — سجل التقدم
============================================================
تاريخ آخر تحديث: 2026-10-14
اسم ملف المشروع:
Copy of الودق AI
آخر مرحلة مكتملة:
المرحلة 67 — التدقيق الشامل لجودة البيانات والمخاطر
المراحل المكتملة:
- المرحلة 59: تحديث الأسعار
- المرحلة 60: فحص جودة البيانات
- المرحلة 61: تقييم الفرص الفنية
- المرحلة 62: مستويات فنية استرشادية
- المرحلة 63: إدارة المخاطر
- المرحلة 64: التقرير الموحد
- المرحلة 65: اختبارات الجودة
- المرحلة 66: إنشاء التقرير النهائي
- المرحلة 67: التدقيق الشامل
عدد الأصول:
26 أصلًا
نتائج المرحلة 67:
- 26 سعرًا صالحًا رقميًا
- 26 تاريخًا صالحًا وغير مستقبلي
- 12 أصلًا اجتاز الفحوص الأولية
- 14 أصلًا يحتاج إلى مراجعة
- 14 أصلًا لديه مستويات غير مكتملة أو تحتاج إلى مراجعة
- 14 أصلًا لديه كميات غير محسوبة أو غير صالحة
الجداول الأصلية لم تُعدّل عمدًا.
الجداول التي أنشأتها المرحلة 67:
1. wadq_stage67_audit_df
2. wadq_stage67_review_df
3. wadq_stage67_passed_df
4. wadq_stage67_summary_df
5. wadq_stage67_log_df
الخطوة التالية:
المرحلة 68A — فحص مصادر الأسعار التاريخية
ومعرفة الجداول المتاحة وأعمدتها قبل إصلاح البيانات.
بعد المرحلة 68A:
تحديد مصدر الأسعار التاريخية الصحيح،
ثم إصلاح المستويات الفنية وحسابات المخاطر.
تعليمات مهمة عند العودة:
1. لا تحذف أي خلية سابقة.
2. لا تضغط Run all.
3. لا تعيدي تشغيل المراحل السابقة دون حاجة.
4. افتحي ملف Copy of الودق AI نفسه.
5. تحققي من آخر مرحلة مكتملة قبل المتابعة.
6. إذا اختفت الجداول، افحصي المصادر المتاحة أولًا.
7. أضيفي المراحل الجديدة أسفل آخر خلية.
8. لا تعتمدي على كمية تداول نظرية قبل التحقق
   من العملة والعقد والعمولات وشروط الوسيط.
ملاحظة:
هذا السجل يحفظ وصف حالة المشروع، وليس الجداول
الموجودة في ذاكرة جلسة Colab.
============================================================


======================================================================
📄 قراءة الملف: سجل_الاستئناف.txt
======================================================================

وقت الحفظ: 2026-10-14 00:16:40
آخر مرحلة مكتملة: 67
الخطوة التالية: 68A
ملف المشروع: Copy of الودق AI
----------------------------------------


======================================================================
📓 فحص دفتر المشروع
======================================================================
✅ دفتر المشروع موجود
الحجم: 4227.84 KB

بداية محتوى الملف:
{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[{"file_id":"1XQ-HSTb3QEASGCN0rhIm4IcrXi3PB7Cv","timestamp":1791680552924}],"authorship_tag":"ABX9TyOhVUs6woVrZ86SXteqlQF8"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"widgets":{"application/vnd.jupyter.widget-state+json":{"version_major":2,"version_minor":0,"state":{"cae06c2e8c314129b99d9cf5f2d55fec":{"model_module":"@jupyter-widgets/controls","model_name":"HTMLModel","model_modu

✅ تمت قراءة دفتر المشروع كـ JSON
عدد الخلايا: 241

======================================================================
🔍 البحث عن أكواد الحفظ والاستعادة
======================================================================

------------------------------------------------------------
📌 الخلية رقم: 1
------------------------------------------------------------
[١:١٠ ص, ١٧‏/١٠‏/٢٠٢٦] نجلاء: # ============================================================
# 🌧️ الودق AI — استعادة الجداول المفقودة
# المرحلة 68A — استعادة آمنة دون حذف أو تحديث الأسعار
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — استعادة الجداول المفقودة")
print("=" * 65)

# ------------------------------------------------------------
# 1. الجداول المطلوبة
# ------------------------------------------------------------

required_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df"
]

# ------------------------------------------------------------
# 2. مصادر بديلة معروفة لاستعادة الجداول
#    لن يتم استبدال أي جدول موجود
# ------------------------------------------------------------

recovery_sources = {
    "wadq_stage66_final_report_df": [
        "wadq_stage65_final_report_df",
        "wadq_stage65_unified_report_df",
        "wadq_final_ai_report"
    ],

    "wadq_stage67_final_report_df": [
        "wadq_stage67_audit_df",
        "wadq_stage67_review_df",
        "wadq_stage66_final_report_df"
    ],

    "wadq_final_ai_report": [
        "wadq_stage66_final_report_df",
        "wadq_stage67_final_report_df",
        "wadq_stage65_final_report_df"
    ],

    "wadq_global_master_report_df": [
        "wadq_global_integrated_df",
        "wadq_global_market_df"
    ],

    "wadq_global_integrated_df": [
        "wadq_global_master_report_df",
        "wadq_global_market_df"
    ],

    "wadq_global_alerts_df": [
        "wadq_global_master_report_df",
        "wadq_global_integrated_df"
    ],

    "wadq_stage66_price_check_df": [
        "wadq_stage65_price_check_df",
        "price_check_df"
    ],

    "wadq_stage66_price_update_df": [
        "wadq_stage65_price_update_df",
        "price_update_df"
    ],

    "wadq_stage66_quality_check_df": [
        "wadq_stage65_quality_check_df",
        "quality_check_df"
    ],

    "wadq_stage66_decision_board_df": [
        "wadq_stage65_decision_board_df",
        "wadq_decision_board_df"
    ]
}

# ------------------------------------------------------------
# 3. فحص الجداول واستعادة المتاح منها
# --

------------------------------------------------------------
📌 الخلية رقم: 4
------------------------------------------------------------
import os

base = "/content/drive/MyDrive"

print("=== WADQ AI BACKUP FILES ===")

for root, dirs, files in os.walk(base):

    folder_name = os.path.basename(root)

    if "احتياطية" in folder_name or "نسخة" in folder_name:

        print("\nBACKUP FOLDER:")
        print(root)

        for file in files:
            path = os.path.join(root, file)
            size = os.path.getsize(path)

            print(f"FILE: {file}")
            print(f"SIZE: {size} bytes")
            print("-" * 40)

------------------------------------------------------------
📌 الخلية رقم: 5
------------------------------------------------------------
import os

backup_path = "/content/drive/MyDrive/نسخة احتياطية - الودق AI"

print("=== BACKUP CONTENTS ===")

if os.path.exists(backup_path):
    items = os.listdir(backup_path)

    if items:
        for item in items:
            full_path = os.path.join(backup_path, item)

            if os.path.isfile(full_path):
                size = os.path.getsize(full_path)
                print(f"FILE: {item} | SIZE: {size} bytes")
            else:
                print(f"FOLDER: {item}")
    else:
        print("BACKUP FOLDER IS EMPTY")
else:
    print("BACKUP PATH NOT FOUND")

------------------------------------------------------------
📌 الخلية رقم: 6
------------------------------------------------------------
import os

base = "/content/drive/MyDrive"

print("=" * 60)
print("WADQ AI - SEARCH BACKUP FOLDERS")
print("=" * 60)

for root, dirs, files in os.walk(base):

    for folder in dirs:

        if "الودق" in folder or "احتياط" in folder or "نسخة" in folder:

            full_path = os.path.join(root, folder)

            print("\nFOLDER FOUND:")
            print(full_path)

            try:
                contents = os.listdir(full_path)

                if contents:
                    for item in contents:
                        print("  -", item)
                else:
                    print("  EMPTY FOLDER")

            except Exception as e:
                print("  ERROR:", e)

------------------------------------------------------------
📌 الخلية رقم: 8
------------------------------------------------------------
import os
import json

base = "/content/drive/MyDrive/colab Notebooks"

print("=== WADQ AI - SAVING CODE SEARCH ===")

for root, dirs, files in os.walk(base):
    for file in files:

        if file.endswith(".ipynb") and "الودق" in file:

            path = os.path.join(root, file)

            print("\nPROJECT NOTEBOOK:")
            print(path)

            with open(path, "r", encoding="utf-8") as f:
                notebook = json.load(f)

            keywords = [
                "to_excel",
                "to_csv",
                "pickle",
                "joblib",
                "save",
                "backup",
                "wadq_stage67"
            ]

            for i, cell in enumerate(notebook.get("cells", [])):
                source = "".join(cell.get("source", []))

                if any(word in source.lower() for word in keywords):
                    print(f"\n--- CELL {i+1} ---")
                    print(source[:1500])import os
import json

base = "/content/drive/MyDrive/colab Notebooks"

print("=== WADQ AI - SAVING CODE SEARCH ===")

for root, dirs, files in os.walk(base):
    for file in files:

        if file.endswith(".ipynb") and "الودق" in file:

            path = os.path.join(root, file)

            print("\nPROJECT NOTEBOOK:")
            print(path)

            with open(path, "r", encoding="utf-8") as f:
                notebook = json.load(f)

            keywords = [
                "to_excel",
                "to_csv",
                "pickle",
                "joblib",
                "save",
                "backup",
                "wadq_stage67"
            ]

            for i, cell in enumerate(notebook.get("cells", [])):
                source = "".join(cell.get("source", []))

                if any(word in source.lower() for word in keywords):
                    print(f"\n--- CELL {i+1} ---")
                    print(source[:1500])

------------------------------------------------------------
📌 الخلية رقم: 12
------------------------------------------------------------
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# البحث الشامل عن ملفات المشروع والجداول المحفوظة
# الكود للفحص فقط: لا يحذف أو يعدل أي ملف
# ============================================================

import os
import glob
import pandas as pd

print("=" * 70)
print("🌧️ الودق AI — البحث الشامل عن الملفات والجداول")
print("=" * 70)

# ------------------------------------------------------------
# 1) التأكد من اتصال Google Drive
# ------------------------------------------------------------

try:
    from google.colab import drive

    if not os.path.exists("/content/drive/MyDrive"):
        drive.mount("/content/drive")

except Exception as e:
    print("تنبيه اتصال Drive:", e)

# ------------------------------------------------------------
# 2) تجربة جميع المسارات المحتملة
# ------------------------------------------------------------

possible_paths = [
    "/content/drive/MyDrive",
    "/content/drive/My Drive",
    "/content/drive",
    "/content",
    "/content/drive/MyDrive/colab Notebooks",
    "/content/drive/MyDrive/Colab Notebooks",
    "/content/drive/MyDrive/الودق AI",
    "/content/drive/MyDrive/الودق_AI",
    "/content/drive/MyDrive/Copy of الودق AI",
    "/content/drive/MyDrive/سجل المشروع - الودق AI",
    "/content/drive/MyDrive/نسخة احتياطية الودق AI",
]

print("\n📁 فحص المسارات المحتملة:")

for path in possible_paths:
    if os.path.exists(path):
        print("✅ موجود:", path)
    else:
        print("❌ غير موجود:", path)

# ------------------------------------------------------------
# 3) البحث في Google Drive بالكامل
# ------------------------------------------------------------

search_root = "/content/drive/MyDrive"

project_keywords = [
    "wadq",
    "الودق",
    "سجل المشروع",
    "نسخة احتياطية",
    "backup",
    "colab",
]

excel_extensions = (".xlsx", ".xls", ".xlsm")
data_extensions = (".csv", ".pkl", ".pickle", ".parquet")
notebook_extension = ".ipynb"

found_excel = []
found_data = []
found_notebooks = []
found_project_folders = []

if os.path.exists(search_root):

    for root, dirs, files in os.walk(search_root):

        # البحث عن مجلدات المشروع
        for folder in dirs:
            folder_lower = folder.lower()

            if any(keyword.lower() in folder_lower
                   for keyword in project_keywords):

                found_project_folders.append(
                    os.path.join(root, folder)
                )

        # البحث عن الملفات
        for file in f

------------------------------------------------------------
📌 الخلية رقم: 15
------------------------------------------------------------
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص الجداول والأسعار والمؤشرات الموجودة
# فحص فقط — دون تعديل أو حذف أي بيانات
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 75)
print("🌧️ الودق AI — المرحلة 68A: الفحص الأولي")
print("=" * 75)

print("📅 وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("🔒 الوضع: فحص فقط — لا تحديث — لا حذف — لا إصلاح")
print("-" * 75)

# ------------------------------------------------------------
# 1. فحص الجداول الرئيسية المتوقعة من المرحلة 67
# ------------------------------------------------------------

expected_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df",
]

print("\n📋 أولاً: الجداول الرئيسية")
print("-" * 75)

for table_name in expected_tables:

    if table_name in globals():

        obj = globals()[table_name]

        if isinstance(obj, pd.DataFrame):

            print(f"✅ {table_name}")
            print(f"   عدد الصفوف: {obj.shape[0]}")
            print(f"   عدد الأعمدة: {obj.shape[1]}")
            print(f"   الأعمدة: {list(obj.columns)}")

        else:
            print(f"⚠️ {table_name} موجود، لكنه ليس DataFrame")

    else:
        print(f"❌ {table_name} غير موجود في الذاكرة الحالية")

# ------------------------------------------------------------
# 2. البحث عن جميع الجداول الموجودة دون تعديلها
# ------------------------------------------------------------

print("\n📊 ثانياً: جميع جداول DataFrame الموجودة")
print("-" * 75)

all_dataframes = {}

for name, obj in list(globals().items()):

    if isinstance(obj, pd.DataFrame):

        all_dataframes[name] = obj

        print(
            f"📌 {name} | "
            f"الصفوف: {obj.shape[0]} | "
            f"الأعمدة: {obj.shape[1]}"
        )

print("\nإجمالي الجداول المكتشفة:", len(all_dataframes))

# ------------------------------------------------------------
# 3. فحص الأسعار والتواريخ في الجداول ذات الصلة
# ------------------------------------------------------------

print("\n💰 ثالثاً: فحص أعمدة الأسعار والتواريخ")
print("-" * 75)

price_keywords = [
    "price", "close", "latest", "last", "السعر",
    "سعر", "

------------------------------------------------------------
📌 الخلية رقم: 16
------------------------------------------------------------
# ============================================================
# 🌧️ الودق AI — استعادة الجداول المفقودة
# المرحلة 68A — استعادة آمنة دون حذف أو تحديث الأسعار
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — استعادة الجداول المفقودة")
print("=" * 65)

# ------------------------------------------------------------
# 1. الجداول المطلوبة
# ------------------------------------------------------------

required_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df"
]

# ------------------------------------------------------------
# 2. مصادر بديلة معروفة لاستعادة الجداول
#    لن يتم استبدال أي جدول موجود
# ------------------------------------------------------------

recovery_sources = {
    "wadq_stage66_final_report_df": [
        "wadq_stage65_final_report_df",
        "wadq_stage65_unified_report_df",
        "wadq_final_ai_report"
    ],

    "wadq_stage67_final_report_df": [
        "wadq_stage67_audit_df",
        "wadq_stage67_review_df",
        "wadq_stage66_final_report_df"
    ],

    "wadq_final_ai_report": [
        "wadq_stage66_final_report_df",
        "wadq_stage67_final_report_df",
        "wadq_stage65_final_report_df"
    ],

    "wadq_global_master_report_df": [
        "wadq_global_integrated_df",
        "wadq_global_market_df"
    ],

    "wadq_global_integrated_df": [
        "wadq_global_master_report_df",
        "wadq_global_market_df"
    ],

    "wadq_global_alerts_df": [
        "wadq_global_master_report_df",
        "wadq_global_integrated_df"
    ],

    "wadq_stage66_price_check_df": [
        "wadq_stage65_price_check_df",
        "price_check_df"
    ],

    "wadq_stage66_price_update_df": [
        "wadq_stage65_price_update_df",
        "price_update_df"
    ],

    "wadq_stage66_quality_check_df": [
        "wadq_stage65_quality_check_df",
        "quality_check_df"
    ],

    "wadq_stage66_decision_board_df": [
        "wadq_stage65_decision_board_df",
        "wadq_decision_board_df"
    ]
}

# ------------------------------------------------------------
# 3. فحص الجداول واستعادة المتاح منها
# --------------------------------

------------------------------------------------------------
📌 الخلية رقم: 17
------------------------------------------------------------
 # ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص الجداول والأسعار والمؤشرات المتاحة
# ============================================================
import pandas as pd
from datetime import datetime
print("=" * 75)
print("🌧️ الودق AI — المرحلة 68A: الفحص الشامل")
print("=" * 75)
print("\n📅 وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("🔒 وضع التشغيل: فحص فقط — دون تعديل أو حذف أي بيانات")
# ------------------------------------------------------------
# 1. فحص جداول المرحلة 67
# ------------------------------------------------------------
stage67_tables = [غف
    "wadq_stage66_final_report_df",
    "wadq_stage67_audit_df",
    "wadq_stage67_review_df",
    "wadq_stage67_passed_df",
    "wadq_stage67_summary_df",
    "wadq_stage67_log_df"
]
print("\n" + "=" * 75)
print("1️⃣ فحص جداول المرحلة 67")
print("=" * 75)
for name in stage67_tables:
    obj = globals().get(name)
    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name}: {obj.shape[0]} صف × {obj.shape[1]} عمود")
        print("   الأعمدة:", list(obj.columns))
    else:
        print(f"⚠️ {name}: غير موجود في ذاكرة الجلسة الحالية")
# ------------------------------------------------------------
# 2. البحث عن الجداول المتعلقة بالأسعار والمؤشرات والتقارير
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("2️⃣ البحث عن الجداول المتاحة")
print("=" * 75)
keywords = [
    "price", "technical", "indicator", "rsi", "macd",
    "report", "audit", "review", "passed",
    "evaluation", "decision", "risk", "stage",
    "master", "unified", "alert", "market"
]
available_tables = []
for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        if any(word in name.lower() for word in keywords):

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص الجداول والأسعار والمؤشرات الموجودة
# فحص فقط — دون تعديل أو حذف أي بيانات
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 75)
print("🌧️ الودق AI — المرحلة 68A: الفحص الأولي")
print("=" * 75)

print("📅 وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("🔒 الوضع: فحص فقط — لا تحديث — لا حذف — لا إصلاح")
print("-" * 75)

# ------------------------------------------------------------
# 1. فحص الجداول الرئيسية المتوقعة من المرحلة 67
# ------------------------------------------------------------

expected_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df",
]

print("\n📋 أولاً: الجداول الرئيسية")
print("-" * 75)

for table_name in expected_tables:

    if table_name in globals():

        obj = globals()[table_name]

        if isinstance(obj, pd.DataFrame):

            print(f"✅ {table_name}")
            print(f"   عدد الصفوف: {obj.shape[0]}")
            print(f"   عدد الأعمدة: {obj.shape[1]}")
            print(f"   الأعمدة: {list(obj.columns)}")

        else:
            print(f"⚠️ {table_name} موجود، لكنه ليس DataFrame")

    else:
        print(f"❌ {table_name} غير موجود في الذاكرة الحالية")

# ------------------------------------------------------------
# 2. البحث عن جميع الجداول الموجودة دون تعديلها
# ------------------------------------------------------------

print("\n📊 ثانياً: جميع جداول DataFrame الموجودة")
print("-" * 75)

all_dataframes = {}

for name, obj in list(globals().items()):

    if isinstance(obj, pd.DataFrame):

        all_dataframes[name] = obj

        print(
            f"📌 {name} | "
            f"الصفوف: {obj.shape[0]} | "
            f"الأعمدة: {obj.shape[1]}"
        )

print("\nإجمالي الجداول المكتشفة:", len(all_dataframes))

# ------------------------------------------------------------
# 3. فحص الأسعار والتواريخ في الجداول ذات الصلة
# ------------------------------------------------------------

print("\n💰 ثالثاً: فحص أعمدة الأسعار والتواريخ")
print("-" * 75)

price_keywords = [
    "price", "close", "latest", "last", "السعر",
    "سعر", "إغلاق", "اغلاق"
]

date_keywords = [
    "date", "time", "timestamp", "التاريخ"
]

indicator_keywords = [
    "rsi", "macd", "sma", "ema", "trend",
    "technical", "مؤشر", "اتجاه"
]

for name, df in all_dataframes.items():

    relevant_columns = [
        col for col in df.columns
        if any(
            keyword in str(col).lower()
            for keyword in price_keywords + date_keywords + indicator_keywords
        )
    ]

    if relevant_columns:

        print(f"\n📌 الجدول: {name}")

        for col in relevant_columns:

            print(f"\n   العمود: {col}")

            try:
                print("   نوع البيانات:", df[col].dtype)
                print("   عدد القيم:", df[col].count())
                print("   عدد القيم المفقودة:", df[col].isna().sum())

                print("   آخر 5 قيم:")
                print(df[col].tail(5).to_string(index=False))

            except Exception as e:
                print("   تعذر عرض العمود:", str(e))

# ------------------------------------------------------------
# 4. فحص عدد الصفوف المكررة في الجداول
# ------------------------------------------------------------

print("\n🔎 رابعاً: فحص الصفوف المكررة")
print("-" * 75)

for name, df in all_dataframes.items():

    try:
        duplicates = df.duplicated().sum()

        if duplicates > 0:
            print(f"⚠️ {name}: يوجد {duplicates} صف مكرر")
        else:
            print(f"✅ {name}: لا توجد صفوف مكررة")

    except Exception:
        print(f"⚠️ تعذر فحص التكرار في {name}")

# ------------------------------------------------------------
# 5. نهاية الفحص
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("✅ انتهت المرحلة 68A")
print("🔒 لم يتم حذف أو تعديل أي جدول")
print("⏸️ توقف هنا وانتظر مراجعة النتائج قبل المرحلة 68B")
print("=" * 75)# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص الجداول والأسعار والمؤشرات الموجودة
# فحص فقط — دون تعديل أو حذف أي بيانات
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 75)
print("🌧️ الودق AI — المرحلة 68A: الفحص الأولي")
print("=" * 75)

print("📅 وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("🔒 الوضع: فحص فقط — لا تحديث — لا حذف — لا إصلاح")
print("-" * 75)

# ------------------------------------------------------------
# 1. فحص الجداول الرئيسية المتوقعة من المرحلة 67
# ------------------------------------------------------------

expected_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df",
]

print("\n📋 أولاً: الجداول الرئيسية")
print("-" * 75)

for table_name in expected_tables:

    if table_name in globals():

        obj = globals()[table_name]

        if isinstance(obj, pd.DataFrame):

            print(f"✅ {table_name}")
            print(f"   عدد الصفوف: {obj.shape[0]}")
            print(f"   عدد الأعمدة: {obj.shape[1]}")
            print(f"   الأعمدة: {list(obj.columns)}")

        else:
            print(f"⚠️ {table_name} موجود، لكنه ليس DataFrame")

    else:
        print(f"❌ {table_name} غير موجود في الذاكرة الحالية")

# ------------------------------------------------------------
# 2. البحث عن جميع الجداول الموجودة دون تعديلها
# ------------------------------------------------------------

print("\n📊 ثانياً: جميع جداول DataFrame الموجودة")
print("-" * 75)

all_dataframes = {}

for name, obj in list(globals().items()):

    if isinstance(obj, pd.DataFrame):

        all_dataframes[name] = obj

        print(
            f"📌 {name} | "
            f"الصفوف: {obj.shape[0]} | "
            f"الأعمدة: {obj.shape[1]}"
        )

print("\nإجمالي الجداول المكتشفة:", len(all_dataframes))

# ------------------------------------------------------------
# 3. فحص الأسعار والتواريخ في الجداول ذات الصلة
# ------------------------------------------------------------

print("\n💰 ثالثاً: فحص أعمدة الأسعار والتواريخ")
print("-" * 75)

price_keywords = [
    "price", "close", "latest", "last", "السعر",
    "سعر", "إغلاق", "اغلاق"
]

date_keywords = [
    "date", "time", "timestamp", "التاريخ"
]

indicator_keywords = [
    "rsi", "macd", "sma", "ema", "trend",
    "technical", "مؤشر", "اتجاه"
]

for name, df in all_dataframes.items():

    relevant_columns = [
        col for col in df.columns
        if any(
            keyword in str(col).lower()
            for keyword in price_keywords + date_keywords + indicator_keywords
        )
    ]

    if relevant_columns:

        print(f"\n📌 الجدول: {name}")

        for col in relevant_columns:

            print(f"\n   العمود: {col}")

            try:
                print("   نوع البيانات:", df[col].dtype)
                print("   عدد القيم:", df[col].count())
                print("   عدد القيم المفقودة:", df[col].isna().sum())

                print("   آخر 5 قيم:")
                print(df[col].tail(5).to_string(index=False))

            except Exception as e:
                print("   تعذر عرض العمود:", str(e))

# ------------------------------------------------------------
# 4. فحص عدد الصفوف المكررة في الجداول
# ------------------------------------------------------------

print("\n🔎 رابعاً: فحص الصفوف المكررة")
print("-" * 75)

for name, df in all_dataframes.items():

    try:
        duplicates = df.duplicated().sum()

        if duplicates > 0:
            print(f"⚠️ {name}: يوجد {duplicates} صف مكرر")
        else:
            print(f"✅ {name}: لا توجد صفوف مكررة")

    except Exception:
        print(f"⚠️ تعذر فحص التكرار في {name}")

# ------------------------------------------------------------
# 5. نهاية الفحص
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("✅ انتهت المرحلة 68A")
print("🔒 لم يتم حذف أو تعديل أي جدول")
print("⏸️ توقف هنا وانتظر مراجعة النتائج قبل المرحلة 68B")
print("=" * 75)

===========================================================================
🌧️ الودق AI — المرحلة 68A: الفحص الأولي
===========================================================================
📅 وقت الفحص: 2026-10-16 21:28:06
🔒 الوضع: فحص فقط — لا تحديث — لا حذف — لا إصلاح
---------------------------------------------------------------------------

📋 أولاً: الجداول الرئيسية
---------------------------------------------------------------------------
❌ wadq_stage66_final_report_df غير موجود في الذاكرة الحالية
❌ wadq_stage67_final_report_df غير موجود في الذاكرة الحالية
❌ wadq_final_ai_report غير موجود في الذاكرة الحالية
❌ wadq_global_master_report_df غير موجود في الذاكرة الحالية
❌ wadq_global_integrated_df غير موجود في الذاكرة الحالية
❌ wadq_global_alerts_df غير موجود في الذاكرة الحالية
❌ wadq_stage66_price_check_df غير موجود في الذاكرة الحالية
❌ wadq_stage66_price_update_df غير موجود في الذاكرة الحالية
❌ wadq_stage66_quality_check_df غير موجود في الذاكرة الحالية
❌ wadq_stage66_decision_board_df غير موجود في الذاكرة الحالية

📊 ثانياً: جميع جداول DataFrame الموجودة
---------------------------------------------------------------------------

إجمالي الجداول المكتشفة: 0

💰 ثالثاً: فحص أعمدة الأسعار والتواريخ
---------------------------------------------------------------------------

🔎 رابعاً: فحص الصفوف المكررة
---------------------------------------------------------------------------

===========================================================================
✅ انتهت المرحلة 68A
🔒 لم يتم حذف أو تعديل أي جدول
⏸️ توقف هنا وانتظر مراجعة النتائج قبل المرحلة 68B
===========================================================================
===========================================================================
🌧️ الودق AI — المرحلة 68A: الفحص الأولي
===========================================================================
📅 وقت الفحص: 2026-10-16 21:28:06
🔒 الوضع: فحص فقط — لا تحديث — لا حذف — لا إصلاح
---------------------------------------------------------------------------

📋 أولاً: الجداول الرئيسية
---------------------------------------------------------------------------
❌ wadq_stage66_final_report_df غير موجود في الذاكرة الحالية
❌ wadq_stage67_final_report_df غير موجود في الذاكرة الحالية
❌ wadq_final_ai_report غير موجود في الذاكرة الحالية
❌ wadq_global_master_report_df غير موجود في الذاكرة الحالية
❌ wadq_global_integrated_df غير موجود في الذاكرة الحالية
❌ wadq_global_alerts_df غير موجود في الذاكرة الحالية
❌ wadq_stage66_price_check_df غير موجود في الذاكرة الحالية
❌ wadq_stage66_price_update_df غير موجود في الذاكرة الحالية
❌ wadq_stage66_quality_check_df غير موجود في الذاكرة الحالية
❌ wadq_stage66_decision_board_df غير موجود في الذاكرة الحالية

📊 ثانياً: جميع جداول DataFrame الموجودة
---------------------------------------------------------------------------

إجمالي الجداول المكتشفة: 0

💰 ثالثاً: فحص أعمدة الأسعار والتواريخ
---------------------------------------------------------------------------

🔎 رابعاً: فحص الصفوف المكررة
---------------------------------------------------------------------------

===========================================================================
✅ انتهت المرحلة 68A
🔒 لم يتم حذف أو تعديل أي جدول
⏸️ توقف هنا وانتظر مراجعة النتائج قبل المرحلة 68B
===========================================================================

In [ ]:
print("انتهى الفحص. لم يتم تشغيل أي مرحلة تحليلية.")

انتهى الفحص. لم يتم تشغيل أي مرحلة تحليلية.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

print("🔍 البحث عن ملفات الودق والنسخ الاحتياطية...\n")

root = "/content/drive/MyDrive"

for folder, dirs, files in os.walk(root):
    dirs[:] = [d for d in dirs if d not in [".ipynb_checkpoints"]]

    for file in files:
        name = file.lower()

        if ("wadq" in name or "backup" in name or "نسخة" in name):
            print(os.path.join(folder, file))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
🔍 البحث عن ملفات الودق والنسخ الاحتياطية...

In [ ]:
import os

root = "/content/drive/MyDrive"

print("🔍 البحث عن ملفات مشروع الودق AI...\n")

matches = []

for folder, dirs, files in os.walk(root):
    # تجاهل المجلدات المخفية
    dirs[:] = [d for d in dirs if not d.startswith(".")]

    for file in files:
        if "الودق" in file or "wadq" in file.lower():
            path = os.path.join(folder, file)
            matches.append(path)

if matches:
    print("✅ الملفات التي عثرنا عليها:")
    for path in matches:
        print(path)
else:
    print("⚠️ لم نعثر على ملفات تحمل اسم الودق أو wadq.")

🔍 البحث عن ملفات مشروع الودق AI...

✅ الملفات التي عثرنا عليها:
/content/drive/MyDrive/Colab Notebooks/Copy of الودقAI
/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt
/content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.gdoc

In [ ]:
import os
import json

folder = "/content/drive/MyDrive/Colab Notebooks"
matches = [
    os.path.join(folder, f)
    for f in os.listdir(folder)
    if f.startswith("Copy of الودقAI")
]

if not matches:
    print("لم أجد دفتر المشروع في المجلد المحدد.")
else:
    notebook_path = matches[0]
    print("📘 دفتر المشروع:", notebook_path)

    try:
        with open(notebook_path, "r", encoding="utf-8") as f:
            notebook = json.load(f)

        keywords = [
            "pickle", "backup", "to_pickle", "read_pickle",
            "wadq_ai_tables", "wadq_stage67", "wadq_stage66",
            "save", "نسخة احتياطية", "استعادة"
        ]

        print("\n🔎 الخلايا التي قد تساعد في استعادة الجداول:\n")
        found = False

        for i, cell in enumerate(notebook.get("cells", [])):
            source = "".join(cell.get("source", []))

            if any(word.lower() in source.lower() for word in keywords):
                found = True
                print(f"\n--- الخلية رقم {i} ---")
                print(source[:1800])

        if not found:
            print("لم تظهر خلايا حفظ أو استعادة مطابقة للكلمات المحددة.")

    except Exception as e:
        print("تعذر فحص الدفتر:", e)

📘 دفتر المشروع: /content/drive/MyDrive/Colab Notebooks/Copy of الودقAI

🔎 الخلايا التي قد تساعد في استعادة الجداول:


--- الخلية رقم 0 ---
[١:١٠ ص, ١٧‏/١٠‏/٢٠٢٦] نجلاء: # ============================================================
# 🌧️ الودق AI — استعادة الجداول المفقودة
# المرحلة 68A — استعادة آمنة دون حذف أو تحديث الأسعار
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — استعادة الجداول المفقودة")
print("=" * 65)

# ------------------------------------------------------------
# 1. الجداول المطلوبة
# ------------------------------------------------------------

required_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df"
]

# ------------------------------------------------------------
# 2. مصادر بديلة معروفة لاستعادة الجداول
#    لن يتم استبدال أي جدول موجود
# ------------------------------------------------------------

recovery_sources = {
    "wadq_stage66_final_report_df": [
        "wadq_stage65_final_report_df",
        "wadq_stage65_unified_report_df",
        "wadq_final_ai_report"
    ],

    "wadq_stage67_final_report_df": [
        "wadq_stage67_audit_df",
        "wadq_stage67_review_df",
        "wadq_stage66_final_report_df"
    ],

    "wadq_final_ai_report": [
        "wadq_stage66_final_report_df",
        "wadq_stage67_final_report_df",
        "wadq_stage65_final_report_df"
    ],

    "wadq_global_master_report_df": [
        "wadq_global_integrated_df",
        "wadq_global_market_df"
    ],

    "wadq_global_integrated_df": [
        "wadq_global_master_report_df",
        "wadq_global

--- الخلية رقم 3 ---
import os

base = "/content/drive/MyDrive"

print("=== WADQ AI BACKUP FILES ===")

for root, dirs, files in os.walk(base):

    folder_name = os.path.basename(root)

    if "احتياطية" in folder_name or "نسخة" in folder_name:

        print("\nBACKUP FOLDER:")
        print(root)

        for file in files:
            path = os.path.join(root, file)
            size = os.path.getsize(path)

            print(f"FILE: {file}")
            print(f"SIZE: {size} bytes")
            print("-" * 40)

--- الخلية رقم 4 ---
import os

backup_path = "/content/drive/MyDrive/نسخة احتياطية - الودق AI"

print("=== BACKUP CONTENTS ===")

if os.path.exists(backup_path):
    items = os.listdir(backup_path)

    if items:
        for item in items:
            full_path = os.path.join(backup_path, item)

            if os.path.isfile(full_path):
                size = os.path.getsize(full_path)
                print(f"FILE: {item} | SIZE: {size} bytes")
            else:
                print(f"FOLDER: {item}")
    else:
        print("BACKUP FOLDER IS EMPTY")
else:
    print("BACKUP PATH NOT FOUND")

--- الخلية رقم 5 ---
import os

base = "/content/drive/MyDrive"

print("=" * 60)
print("WADQ AI - SEARCH BACKUP FOLDERS")
print("=" * 60)

for root, dirs, files in os.walk(base):

    for folder in dirs:

        if "الودق" in folder or "احتياط" in folder or "نسخة" in folder:

            full_path = os.path.join(root, folder)

            print("\nFOLDER FOUND:")
            print(full_path)

            try:
                contents = os.listdir(full_path)

                if contents:
                    for item in contents:
                        print("  -", item)
                else:
                    print("  EMPTY FOLDER")

            except Exception as e:
                print("  ERROR:", e)

--- الخلية رقم 7 ---
import os
import json

base = "/content/drive/MyDrive/colab Notebooks"

print("=== WADQ AI - SAVING CODE SEARCH ===")

for root, dirs, files in os.walk(base):
    for file in files:

        if file.endswith(".ipynb") and "الودق" in file:

            path = os.path.join(root, file)

            print("\nPROJECT NOTEBOOK:")
            print(path)

            with open(path, "r", encoding="utf-8") as f:
                notebook = json.load(f)

            keywords = [
                "to_excel",
                "to_csv",
                "pickle",
                "joblib",
                "save",
                "backup",
                "wadq_stage67"
            ]

            for i, cell in enumerate(notebook.get("cells", [])):
                source = "".join(cell.get("source", []))

                if any(word in source.lower() for word in keywords):
                    print(f"\n--- CELL {i+1} ---")
                    print(source[:1500])import os
import json

base = "/content/drive/MyDrive/colab Notebooks"

print("=== WADQ AI - SAVING CODE SEARCH ===")

for root, dirs, files in os.walk(base):
    for file in files:

        if file.endswith(".ipynb") and "الودق" in file:

            path = os.path.join(root, file)

            print("\nPROJECT NOTEBOOK:")
            print(path)

            with open(path, "r", encoding="utf-8") as f:
                notebook = json.load(f)

            keywords = [
                "to_excel",
                "to_csv",
                "pickle",
                "joblib",
                "save",
                "backup",
                "wadq_stage67"
            ]

            for i, cell in enumerate(notebook.get("cells", [])):
                source = "".join(cell.get("source", []))

                if any(word in source.lowe

--- الخلية رقم 11 ---
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# البحث الشامل عن ملفات المشروع والجداول المحفوظة
# الكود للفحص فقط: لا يحذف أو يعدل أي ملف
# ============================================================

import os
import glob
import pandas as pd

print("=" * 70)
print("🌧️ الودق AI — البحث الشامل عن الملفات والجداول")
print("=" * 70)

# ------------------------------------------------------------
# 1) التأكد من اتصال Google Drive
# ------------------------------------------------------------

try:
    from google.colab import drive

    if not os.path.exists("/content/drive/MyDrive"):
        drive.mount("/content/drive")

except Exception as e:
    print("تنبيه اتصال Drive:", e)

# ------------------------------------------------------------
# 2) تجربة جميع المسارات المحتملة
# ------------------------------------------------------------

possible_paths = [
    "/content/drive/MyDrive",
    "/content/drive/My Drive",
    "/content/drive",
    "/content",
    "/content/drive/MyDrive/colab Notebooks",
    "/content/drive/MyDrive/Colab Notebooks",
    "/content/drive/MyDrive/الودق AI",
    "/content/drive/MyDrive/الودق_AI",
    "/content/drive/MyDrive/Copy of الودق AI",
    "/content/drive/MyDrive/سجل المشروع - الودق AI",
    "/content/drive/MyDrive/نسخة احتياطية الودق AI",
]

print("\n📁 فحص المسارات المحتملة:")

for path in possible_paths:
    if os.path.exists(path):
        print("✅ موجود:", path)
    else:
        print("❌ غير موجود:", path)

# ------------------------------------------------------------
# 3) البحث في Google Drive بالكامل
# ------------------------------------------------------------

search_root = "/content/drive/MyDrive"

project_keywords = [
    "wadq",
    "الودق",
    "سجل المشروع",
    "نسخة احتياطية",


--- الخلية رقم 14 ---
# ============================================================
# 🌧️ الودق AI — المرحلة 68C
# قراءة السجلات وفحص دفتر المشروع
# ============================================================

import os
import json

base = "/content/drive/MyDrive"

# ------------------------------------------------------------
# 1) قراءة سجل المشروع وسجل الاستئناف
# ------------------------------------------------------------

log_files = [
    base + "/الودق AI - سجل المشروع/سجل_الودق_AI.txt",
    base + "/الودق AI - سجل المشروع/سجل_الاستئناف.txt"
]

for path in log_files:

    print("\n" + "=" * 70)
    print("📄 قراءة الملف:", os.path.basename(path))
    print("=" * 70)

    if os.path.isfile(path):

        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        print(content)

    else:
        print("⚠️ الملف غير موجود")

# ------------------------------------------------------------
# 2) فحص دفتر المشروع
# ------------------------------------------------------------

notebook_path = (
    base + "/Colab Notebooks/Copy of الودقAI"
)

print("\n" + "=" * 70)
print("📓 فحص دفتر المشروع")
print("=" * 70)

if os.path.isfile(notebook_path):

    print("✅ دفتر المشروع موجود")
    print("الحجم:", round(os.path.getsize(notebook_path) / 1024, 2), "KB")

    with open(notebook_path, "r", encoding="utf-8") as f:
        notebook_text = f.read()

    print("\nبداية محتوى الملف:")
    print(notebook_text[:500])

    # --------------------------------------------------------
    # 3) محاولة قراءة الدفتر كملف JSON
    # --------------------------------------------------------

    try:

        notebook = json.loads(notebook_text)

        print("\n✅ تمت قراءة دفتر المشروع كـ JSON")

        cells = notebook.get("cells", [])

        print("عدد الخلايا:", len(cells))



--- الخلية رقم 15 ---
# ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص الجداول والأسعار والمؤشرات الموجودة
# فحص فقط — دون تعديل أو حذف أي بيانات
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 75)
print("🌧️ الودق AI — المرحلة 68A: الفحص الأولي")
print("=" * 75)

print("📅 وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("🔒 الوضع: فحص فقط — لا تحديث — لا حذف — لا إصلاح")
print("-" * 75)

# ------------------------------------------------------------
# 1. فحص الجداول الرئيسية المتوقعة من المرحلة 67
# ------------------------------------------------------------

expected_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df",
]

print("\n📋 أولاً: الجداول الرئيسية")
print("-" * 75)

for table_name in expected_tables:

    if table_name in globals():

        obj = globals()[table_name]

        if isinstance(obj, pd.DataFrame):

            print(f"✅ {table_name}")
            print(f"   عدد الصفوف: {obj.shape[0]}")
            print(f"   عدد الأعمدة: {obj.shape[1]}")
            print(f"   الأعمدة: {list(obj.columns)}")

        else:
            print(f"⚠️ {table_name} موجود، لكنه ليس DataFrame")

    else:
        print(f"❌ {table_name} غير موجود في الذاكرة الحالية")

# ------------------------------------------------------------
# 2. البحث عن جميع الجداول الموجودة دون تعديلها
# ------------------------------------------------------------

print("\n📊 ثانياً:

--- الخلية رقم 17 ---
from google.colab import drive
drive.mount('/content/drive')

import os

print("🔍 البحث عن ملفات الودق والنسخ الاحتياطية...\n")

root = "/content/drive/MyDrive"

for folder, dirs, files in os.walk(root):
    dirs[:] = [d for d in dirs if d not in [".ipynb_checkpoints"]]

    for file in files:
        name = file.lower()

        if ("wadq" in name or "backup" in name or "نسخة" in name):
            print(os.path.join(folder, file))

--- الخلية رقم 20 ---
# ============================================================
# 🌧️ الودق AI — استعادة الجداول المفقودة
# المرحلة 68A — استعادة آمنة دون حذف أو تحديث الأسعار
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — استعادة الجداول المفقودة")
print("=" * 65)

# ------------------------------------------------------------
# 1. الجداول المطلوبة
# ------------------------------------------------------------

required_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df"
]

# ------------------------------------------------------------
# 2. مصادر بديلة معروفة لاستعادة الجداول
#    لن يتم استبدال أي جدول موجود
# ------------------------------------------------------------

recovery_sources = {
    "wadq_stage66_final_report_df": [
        "wadq_stage65_final_report_df",
        "wadq_stage65_unified_report_df",
        "wadq_final_ai_report"
    ],

    "wadq_stage67_final_report_df": [
        "wadq_stage67_audit_df",
        "wadq_stage67_review_df",
        "wadq_stage66_final_report_df"
    ],

    "wadq_final_ai_report": [
        "wadq_stage66_final_report_df",
        "wadq_stage67_final_report_df",
        "wadq_stage65_final_report_df"
    ],

    "wadq_global_master_report_df": [
        "wadq_global_integrated_df",
        "wadq_global_market_df"
    ],

    "wadq_global_integrated_df": [
        "wadq_global_master_report_df",
        "wadq_global_market_df"
    ],

    "wadq_

--- الخلية رقم 21 ---
 # ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص الجداول والأسعار والمؤشرات المتاحة
# ============================================================
import pandas as pd
from datetime import datetime
print("=" * 75)
print("🌧️ الودق AI — المرحلة 68A: الفحص الشامل")
print("=" * 75)
print("\n📅 وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("🔒 وضع التشغيل: فحص فقط — دون تعديل أو حذف أي بيانات")
# ------------------------------------------------------------
# 1. فحص جداول المرحلة 67
# ------------------------------------------------------------
stage67_tables = [غف
    "wadq_stage66_final_report_df",
    "wadq_stage67_audit_df",
    "wadq_stage67_review_df",
    "wadq_stage67_passed_df",
    "wadq_stage67_summary_df",
    "wadq_stage67_log_df"
]
print("\n" + "=" * 75)
print("1️⃣ فحص جداول المرحلة 67")
print("=" * 75)
for name in stage67_tables:
    obj = globals().get(name)
    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name}: {obj.shape[0]} صف × {obj.shape[1]} عمود")
        print("   الأعمدة:", list(obj.columns))
    else:
        print(f"⚠️ {name}: غير موجود في ذاكرة الجلسة الحالية")
# ------------------------------------------------------------
# 2. البحث عن الجداول المتعلقة بالأسعار والمؤشرات والتقارير
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("2️⃣ البحث عن الجداول المتاحة")
print("=" * 75)
keywords = [
    "price", "technical", "indicator", "rsi", "macd",
    "report", "audit", "review", "passed",
    "evaluation", "decision", "risk", "stage",
    "master", "unified", "alert", "market"
]
available_tables = []
for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        if any(word in name.lower() for word in keywords):


--- الخلية رقم 25 ---
# 🌧️ الودق AI — فحص جداول المرحلة 40 لاستعادة المرحلة 41

import pandas as
pd

print("🔎 فحص جداول مشروع الودق AI")
print("=" * 50)

for name in [
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v3_df",
]:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name} | الصفوف: {len(obj)} | الأعمدة: {len(obj.columns)}")
    else:
        print(f"⚠️ {name} غير موجود في الذاكرة الحالية")

--- الخلية رقم 33 ---
# 🌧️ الودق AI — المرحلة 39
# إنشاء لوحة ذكية لترتيب أولويات المتابعة
# دون تعديل الجداول السابقة

import pandas as pd

print("🌧️ الودق AI — المرحلة 39")
print("=" * 60)

# التحقق من وجود جدول المرحلة 38
if "wadq_global_us_unified_df" not in globals():

    print("⚠️ جدول المرحلة 38 غير موجود في جلسة التشغيل.")
    print("نحتاج إلى استعادة الجدول قبل متابعة العمل.")

else:

    # إنشاء نسخة مستقلة لحماية الجدول الأصلي
    priority_df = wadq_global_us_unified_df.copy()

    # ترتيب فئات الأولوية من الأعلى إلى الأدنى
    priority_order = {
        "أولوية متابعة أعلى": 1,
        "تنبيه فني — مراجعة الزخم": 2,
        "متابعة بحذر شديد": 3,
        "مراقبة عادية": 4
    }

    # تحديد ترتيب كل أصل
    priority_df["ترتيب الأولوية"] = (
        priority_df["أولوية المتابعة"]
        .map(priority_order)
        .fillna(5)
        .astype(int)
        if "أولوية المتابعة" in priority_df.columns
        else 5
    )

    # وصف الأولوية للأصول التي لا تملك تصنيف متابعة أمريكيًا
    if "أولوية المتابعة" in priority_df.columns:
        priority_df["فئة المتابعة"] = (
            priority_df["أولوية المتابعة"].fillna(
                "لا توجد مطابقة في لوحة المتابعة الأمريكية"
            )
        )
    else:
        priority_df["فئة المتابعة"] = (
            "لا توجد مطابقة في لوحة المتابعة الأمريكية"
        )

    # ترتيب الأصول حسب الأولوية
    wadq_global_priority_df = (
        priority_df
        .sort_values(
            by=["ترتيب الأولوية", "الأصل"],
            ascending=[True, True],
            kind="stable"
        )
        .reset_index(drop=True)
    )

    # عرض الأعمدة الأساسية المتاحة
    display_columns = [
        "ترتيب الأولوية",
        "نوع الأصل",
        "الأصل",
        "الرمز",
        "الإشارة المدمجة",
        "فئة المتابعة",
        "حالة بيانات ا

--- الخلية رقم 34 ---
# 🌧️ الودق AI — فحص الجداول المطلوبة للاستعادة

import pandas as pd

required_tables = [
    "wadq_global_market_df",
    "wadq_global_us_unified_df",
    "wadq_global_priority_df",
    "wadq_executive_summary_df",
    "wadq_stage41_decision_df"
]

print("🌧️ الودق AI — فحص الجداول")
print("=" * 55)

for name in required_tables:
    if name in globals() and isinstance(globals()[name], pd.DataFrame):
        df = globals()[name]
        print(f"✅ {name}: موجود")
        print(f"   الصفوف: {len(df)} | الأعمدة: {len(df.columns)}")
    else:
        print(f"⚠️ {name}: غير موجود في الذاكرة")

print("=" * 55)
print("✅ انتهى الفحص دون تعديل أي جدول.")

--- الخلية رقم 38 ---
# 🌧️ الودق AI — فحص ذاكرة المشروع
import pandas as pd

print("🌧️ فحص ذاكرة مشروع الودق AI")
print("=" * 50)

found = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        found.append((name, len(obj), len(obj.columns)))

if found:
    print("✅ تم العثور على الجداول التالية:")
    for name, rows, cols in found:
        print(f"📊 {name} | الأصول: {rows} | الأعمدة: {cols}")
else:
    print("⚠️ لم يتم العثور على أي جداول DataFrame في الذاكرة.")
    print("نحتاج إلى التحقق من حالة الجلسة قبل استعادة المشروع.")

--- الخلية رقم 98 ---
# ☔ الودق AI — فحص الجداول وحفظ نسخة احتياطية منها
import pandas as pd

print("☔ الودق AI — فحص الجداول وحمايتها")
print("=" * 55)

table_names = [
    "wadq_news_df",
    "wadq_ticker_news_df",
    "wadq_impact_news_df",
    "wadq_global_news_df",
    "wadq_global_news_analysis_df",
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_master_report_v3_df",
    "us_technical_df",
    "wadq_us_monitoring_df",
    "wadq_global_us_unified_df",
    "wadq_global_priority_df",
    "wadq_stage41_decision_df",
    "wadq_executive_summary_df"
]

backup_tables = {}

for name in table_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        backup_tables[name] = obj.copy()
        print(f"✅ {name}: {len(obj)} صف × {len(obj.columns)} عمود")
    else:
        print(f"⚠️ {name}: غير موجود في الذاكرة")

print("=" * 55)
print(f"📦 عدد الجداول المحفوظة في النسخة الاحتياطية: {len(backup_tables)}")

--- الخلية رقم 99 ---
# ☔ الودق AI — استعادة جدول الأخبار المؤثرة
# إنشاء جدول مستقل دون تعديل الجداول الأصلية

import pandas as pd
from IPython.display import display


In [ ]:
# 🌧️ الودق AI — المرحلة 68B
# فحص النسخة الاحتياطية دون تعديل البيانات

import os
import pickle
import pandas as pd

backup_root = "/content/drive/MyDrive"

print("=" * 65)
print("🌧️ الودق AI — فحص ملفات النسخ الاحتياطية")
print("=" * 65)

backup_files = []

for root, dirs, files in os.walk(backup_root):
    dirs[:] = [d for d in dirs if not d.startswith(".")]

    for file in files:
        if file.lower() == "wadq_ai_tables_backup.pkl":
            backup_files.append(os.path.join(root, file))

if not backup_files:
    print("\n⚠️ لم يتم العثور على ملف النسخة الاحتياطية.")
else:
    for path in backup_files:
        print("\n📦 الملف:", path)
        print("📏 الحجم:", os.path.getsize(path), "بايت")

        try:
            with open(path, "rb") as f:
                saved_tables = pickle.load(f)

            if isinstance(saved_tables, dict):
                print("✅ الملف قابل للقراءة")
                print("📊 عدد الجداول:", len(saved_tables))

                for name, df in saved_tables.items():
                    if isinstance(df, pd.DataFrame):
                        print(f"• {name}: {df.shape}")

            else:
                print("⚠️ محتوى الملف ليس قاموس جداول.")

        except Exception as e:
            print("❌ تعذر قراءة الملف:", e)

print("\n🔒 انتهى الفحص دون استعادة أو تعديل أي جدول.")

=================================================================
🌧️ الودق AI — فحص ملفات النسخ الاحتياطية
=================================================================

⚠️ لم يتم العثور على ملف النسخة الاحتياطية.

🔒 انتهى الفحص دون استعادة أو تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — الفحص الشامل للنسخ الاحتياطية والجداول
# فحص فقط: لا حذف، لا تعديل، لا تحديث أسعار

import os
import pickle
import pandas as pd

print("=" * 65)
print("🌧️ الودق AI — فحص النسخ الاحتياطية والجداول")
print("=" * 65)

# 1) فحص الجداول الموجودة في ذاكرة Colab
print("\n📊 الجداول الموجودة في الذاكرة:")

found = 0

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name} | {obj.shape[0]} صف × {obj.shape[1]} عمود")
        found += 1

print(f"\nإجمالي الجداول الموجودة: {found}")

# 2) البحث عن ملفات النسخ الاحتياطية
print("\n🔍 البحث عن ملفات النسخ الاحتياطية:")

backup_files = []

search_root = "/content/drive/MyDrive"

if os.path.exists(search_root):
    for root, dirs, files in os.walk(search_root):
        dirs[:] = [d for d in dirs if d != ".ipynb_checkpoints"]

        for file in files:
            if file.lower().endswith((".pkl", ".pickle")):
                path = os.path.join(root, file)

                if "wadq" in file.lower() or "الودق" in file:
                    backup_files.append(path)

if not backup_files:
    print("⚠️ لم يتم العثور على ملفات نسخ احتياطية باسم الودق.")
else:
    for path in backup_files:
        print("\n📁 الملف:", path)
        print("📦 الحجم:", os.path.getsize(path), "بايت")

        try:
            with open(path, "rb") as f:
                saved_tables = pickle.load(f)

            if isinstance(saved_tables, dict):
                print("✅ عدد العناصر المحفوظة:", len(saved_tables))

                for name, df in saved_tables.items():
                    if isinstance(df, pd.DataFrame):
                        print(f"  📊 {name}: {df.shape}")

            else:
                print("⚠️ الملف ليس قاموس جداول.")

        except Exception as e:
            print("⚠️ تعذرت قراءة الملف:", e)

print("\n🔒 انتهى الفحص دون استعادة أو تعديل أي جدول.")

=================================================================
🌧️ الودق AI — فحص النسخ الاحتياطية والجداول
=================================================================

📊 الجداول الموجودة في الذاكرة:

إجمالي الجداول الموجودة: 0

🔍 البحث عن ملفات النسخ الاحتياطية:
⚠️ لم يتم العثور على ملفات نسخ احتياطية باسم الودق.

🔒 انتهى الفحص دون استعادة أو تعديل أي جدول.

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68B
# استعادة الجداول المفقودة من مصادر موجودة
# دون تحديث أسعار أو حذف الجداول الأصلية
# ============================================================

import os
import pickle
import pandas as pd
from IPython.display import display

print("=" * 65)
print("🌧️ الودق AI — استعادة الجداول")
print("=" * 65)

# ------------------------------------------------------------
# 1) البحث عن النسخة الاحتياطية
# ------------------------------------------------------------

backup_paths = [
    "/content/drive/MyDrive/الودق_AI_نسخة_احتياطية/wadq_ai_tables_backup.pkl",
    "/content/drive/MyDrive/الودق AI - سجل المشروع/wadq_ai_tables_backup.pkl",
    "/content/drive/MyDrive/نسخة احتياطية - الودق AI/wadq_ai_tables_backup.pkl",
]

saved_tables = {}

for path in backup_paths:
    if os.path.isfile(path):
        try:
            with open(path, "rb") as f:
                data = pickle.load(f)

            if isinstance(data, dict):
                saved_tables.update(data)
                print("✅ تم العثور على نسخة احتياطية:", path)
                break

        except Exception as e:
            print("⚠️ تعذرت قراءة النسخة:", e)

# ------------------------------------------------------------
# 2) مصادر الجداول المتاحة في الذاكرة
# ------------------------------------------------------------

sources = {}

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        sources[name] = obj.copy(deep=True)

# إضافة الجداول من النسخة الاحتياطية
for name, obj in saved_tables.items():
    if isinstance(obj, pd.DataFrame):
        sources[name] = obj.copy(deep=True)

print("\n📊 عدد الجداول المصدرية المتاحة:", len(sources))

# ------------------------------------------------------------
# 3) الجداول المطلوب استعادتها
# ------------------------------------------------------------

required_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df",
    "wadq_stage67_audit_df",
    "wadq_stage67_review_df",
    "wadq_stage67_passed_df",
    "wadq_stage67_summary_df",
    "wadq_stage67_log_df",
]

# ------------------------------------------------------------
# 4) الاستعادة المباشرة فقط
# ------------------------------------------------------------

restored = []
missing = []

for name in required_tables:

    # عدم استبدال جدول موجود
    if isinstance(globals().get(name), pd.DataFrame):
        print(f"⏭️ موجود مسبقًا: {name}")
        continue

    # استعادة الجدول بالاسم نفسه فقط
    if name in sources and isinstance(sources[name], pd.DataFrame):
        globals()[name] = sources[name].copy(deep=True)
        restored.append(name)

        print(f"✅ تمت استعادة: {name}")
        print("   الحجم:", globals()[name].shape)

    else:
        missing.append(name)
        print(f"⚠️ لم يتوفر مصدر مطابق: {name}")

# ------------------------------------------------------------
# 5) التقرير النهائي
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("📋 نتيجة الاستعادة")
print("=" * 65)

print("✅ الجداول المستعادة:", len(restored))
print("⚠️ الجداول التي لم يتوفر مصدر مطابق لها:", len(missing))

if restored:
    print("\nالجداول المستعادة:")
    for name in restored:
        print("-", name)

if missing:
    print("\nالجداول التي تحتاج مصدرًا إضافيًا:")
    for name in missing:
        print("-", name)

print("\n🔒 انتهى الكود دون حذف أو تحديث أسعار.")

=================================================================
🌧️ الودق AI — استعادة الجداول
=================================================================

📊 عدد الجداول المصدرية المتاحة: 0
⚠️ لم يتوفر مصدر مطابق: wadq_stage66_final_report_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage67_final_report_df
⚠️ لم يتوفر مصدر مطابق: wadq_final_ai_report
⚠️ لم يتوفر مصدر مطابق: wadq_global_master_report_df
⚠️ لم يتوفر مصدر مطابق: wadq_global_integrated_df
⚠️ لم يتوفر مصدر مطابق: wadq_global_alerts_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage66_price_check_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage66_price_update_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage66_quality_check_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage66_decision_board_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage67_audit_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage67_review_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage67_passed_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage67_summary_df
⚠️ لم يتوفر مصدر مطابق: wadq_stage67_log_df

=================================================================
📋 نتيجة الاستعادة
=================================================================
✅ الجداول المستعادة: 0
⚠️ الجداول التي لم يتوفر مصدر مطابق لها: 15

الجداول التي تحتاج مصدرًا إضافيًا:
- wadq_stage66_final_report_df
- wadq_stage67_final_report_df
- wadq_final_ai_report
- wadq_global_master_report_df
- wadq_global_integrated_df
- wadq_global_alerts_df
- wadq_stage66_price_check_df
- wadq_stage66_price_update_df
- wadq_stage66_quality_check_df
- wadq_stage66_decision_board_df
- wadq_stage67_audit_df
- wadq_stage67_review_df
- wadq_stage67_passed_df
- wadq_stage67_summary_df
- wadq_stage67_log_df

🔒 انتهى الكود دون حذف أو تحديث أسعار.

In [ ]:
# 🌧️ الودق AI — استخراج أكواد إنشاء الجداول القديمة
# فحص فقط: لا تشغيل للمراحل ولا تحديث للأسعار

import os
import json

root = "/content/drive/MyDrive/Colab Notebooks"

print("=" * 65)
print("🌧️ الودق AI — استخراج أكواد الجداول")
print("=" * 65)

# البحث عن دفتر المشروع
notebook_path = None

for folder, dirs, files in os.walk(root):
    for file in files:
        if file.endswith(".ipynb") and "الودق" in file:
            if "Copy" in file:
                notebook_path = os.path.join(folder, file)
                break
    if notebook_path:
        break

if not notebook_path:
    raise FileNotFoundError(
        "لم يتم العثور على دفتر Copy of الودق AI في المسار المحدد."
    )

print("✅ دفتر المشروع:", notebook_path)

# قراءة الدفتر
with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

cells = notebook.get("cells", [])

# الجداول التي نريد البحث عن أكواد إنشائها
target_names = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df",
    "wadq_stage67_audit_df",
    "wadq_stage67_review_df",
    "wadq_stage67_passed_df",
    "wadq_stage67_summary_df",
    "wadq_stage67_log_df",
]

# استخراج الخلايا التي تحتوي على إنشاء الجداول المطلوبة
matched_cells = []

for i, cell in enumerate(cells):

    if cell.get("cell_type") != "code":
        continue

    source = "".join(cell.get("source", []))

    if any(name in source for name in target_names):
        matched_cells.append((i, source))

# إضافة خلايا المراحل 59 إلى 67 التي قد تكون مصادر للجداول
for i, cell in enumerate(cells):

    if cell.get("cell_type") != "code":
        continue

    source = "".join(cell.get("source", []))

    if any(
        f"المرحلة {stage}" in source
        or f"مرحلة {stage}" in source
        for stage in range(59, 68)
    ):
        if not any(old_i == i for old_i, _ in matched_cells):
            matched_cells.append((i, source))

# ترتيب الخلايا بحسب موقعها في الدفتر
matched_cells.sort(key=lambda x: x[0])

# حفظ الأكواد المستخرجة في ملف نصي
output_path = (
    "/content/drive/MyDrive/"
    "wadq_recovered_table_codes.txt"
)

with open(output_path, "w", encoding="utf-8") as f:

    f.write("🌧️ الودق AI — أكواد إنشاء الجداول المستخرجة\n\n")

    for cell_number, source in matched_cells:

        f.write("\n" + "=" * 70 + "\n")
        f.write(f"رقم الخلية في الدفتر: {cell_number}\n")
        f.write("=" * 70 + "\n")
        f.write(source)
        f.write("\n")

print("\n" + "=" * 65)
print("📋 نتيجة استخراج الأكواد")
print("=" * 65)

print("عدد الخلايا المستخرجة:", len(matched_cells))

for cell_number, source in matched_cells:
    print(f"✅ الخلية {cell_number} | {len(source)} حرف")

print("\n📄 تم حفظ الأكواد في:")
print(output_path)

print("\n🔒 لم يتم تشغيل أي كود قديم أو تعديل أي جدول.")

=================================================================
🌧️ الودق AI — استخراج أكواد الجداول
=================================================================

FileNotFoundError: لم يتم العثور على دفتر Copy of الودق AI في المسار المحدد.

In [ ]:
# 🌧️ الودق AI — العثور على دفتر المشروع
# بحث فقط، دون تعديل أي ملف

import os

from google.colab import drive

drive.mount("/content/drive")

root = "/content/drive/MyDrive"

print("=" * 60)
print("🔍 البحث عن دفتر الودق AI")
print("=" * 60)

found = []

for folder, dirs, files in os.walk(root):

    dirs[:] = [
        d for d in dirs
        if d not in [".ipynb_checkpoints"]
    ]

    for file in files:

        if file.lower().endswith(".ipynb"):

            if "الودق" in file.lower() or "wadq" in file.lower():

                path = os.path.join(folder, file)
                found.append(path)

                print("\n✅ دفتر محتمل:")
                print(path)

print("\n" + "=" * 60)

if found:
    print("📊 عدد الدفاتر التي عُثر عليها:", len(found))
    print("\n📌 أرسلي لي المسار الذي يبدأ بـ:")
    print("/content/drive/MyDrive/")
else:
    print("⚠️ لم يُعثر على دفتر باسم الودق أو wadq.")
    print("تحققي من اتصال Google Drive.")

print("\n🔒 انتهى البحث دون تعديل أي ملف.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
============================================================
🔍 البحث عن دفتر الودق AI
============================================================

============================================================
⚠️ لم يُعثر على دفتر باسم الودق أو wadq.
تحققي من اتصال Google Drive.

🔒 انتهى البحث دون تعديل أي ملف.

In [ ]:
# ============================================================
# 🌧️ الودق AI — استعادة الجداول المفقودة
# المرحلة 68A — استعادة آمنة دون حذف أو تحديث الأسعار
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 65)
print("🌧️ الودق AI — استعادة الجداول المفقودة")
print("=" * 65)

# ------------------------------------------------------------
# 1. الجداول المطلوبة
# ------------------------------------------------------------

required_tables = [
    "wadq_stage66_final_report_df",
    "wadq_stage67_final_report_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_integrated_df",
    "wadq_global_alerts_df",
    "wadq_stage66_price_check_df",
    "wadq_stage66_price_update_df",
    "wadq_stage66_quality_check_df",
    "wadq_stage66_decision_board_df"
]

# ------------------------------------------------------------
# 2. مصادر بديلة معروفة لاستعادة الجداول
#    لن يتم استبدال أي جدول موجود
# ------------------------------------------------------------

recovery_sources = {
    "wadq_stage66_final_report_df": [
        "wadq_stage65_final_report_df",
        "wadq_stage65_unified_report_df",
        "wadq_final_ai_report"
    ],

    "wadq_stage67_final_report_df": [
        "wadq_stage67_audit_df",
        "wadq_stage67_review_df",
        "wadq_stage66_final_report_df"
    ],

    "wadq_final_ai_report": [
        "wadq_stage66_final_report_df",
        "wadq_stage67_final_report_df",
        "wadq_stage65_final_report_df"
    ],

    "wadq_global_master_report_df": [
        "wadq_global_integrated_df",
        "wadq_global_market_df"
    ],

    "wadq_global_integrated_df": [
        "wadq_global_master_report_df",
        "wadq_global_market_df"
    ],

    "wadq_global_alerts_df": [
        "wadq_global_master_report_df",
        "wadq_global_integrated_df"
    ],

    "wadq_stage66_price_check_df": [
        "wadq_stage65_price_check_df",
        "price_check_df"
    ],

    "wadq_stage66_price_update_df": [
        "wadq_stage65_price_update_df",
        "price_update_df"
    ],

    "wadq_stage66_quality_check_df": [
        "wadq_stage65_quality_check_df",
        "quality_check_df"
    ],

    "wadq_stage66_decision_board_df": [
        "wadq_stage65_decision_board_df",
        "wadq_decision_board_df"
    ]
}

# ------------------------------------------------------------
# 3. فحص الجداول واستعادة المتاح منها
# ------------------------------------------------------------

restored_tables = []
existing_tables = []
missing_tables = []

for table_name in required_tables:

    # إذا كان الجدول موجودًا، لا نلمسه
    if table_name in globals():
        obj = globals()[table_name]

        if isinstance(obj, pd.DataFrame):
            existing_tables.append(table_name)
            print(f"✅ موجود: {table_name} — {obj.shape}")
            continue

    # البحث عن مصدر بديل موجود
    recovered = False

    for source_name in recovery_sources.get(table_name, []):

        if source_name not in globals():
            continue

        source_obj = globals()[source_name]

        if not isinstance(source_obj, pd.DataFrame):
            continue

        # نسخ الجدول دون تعديل المصدر
        globals()[table_name] = source_obj.copy()

        restored_tables.append(table_name)
        recovered = True

        print(
            f"♻️ تمت استعادة: {table_name} "
            f"من: {source_name} — {source_obj.shape}"
        )

        break

    if not recovered:
        missing_tables.append(table_name)
        print(f"⚠️ لم يُعثر على مصدر لاستعادة: {table_name}")

# ------------------------------------------------------------
# 4. تقرير الاستعادة
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("📊 النتيجة النهائية")
print("=" * 65)

print(f"📅 وقت الفحص: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print(f"✅ الجداول الموجودة: {len(existing_tables)}")
print(f"♻️ الجداول المستعادة: {len(restored_tables)}")
print(f"⚠️ الجداول التي تحتاج إلى مصدر: {len(missing_tables)}")

if restored_tables:
    print("\nالجداول التي تمت استعادتها:")
    for name in restored_tables:
        print(f"  - {name}")

if missing_tables:
    print("\nالجداول التي لم يتوفر مصدر لاستعادتها:")
    for name in missing_tables:
        print(f"  - {name}")

# ------------------------------------------------------------
# 5. فحص نهائي دون تعديل البيانات
# ------------------------------------------------------------

print("\n🔍 فحص الجداول المطلوبة:")

for table_name in required_tables:

    obj = globals().get(table_name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {table_name}: {obj.shape}")
    else:
        print(f"❌ {table_name}: غير متوفر")

print("\n🌧️ انتهى الفحص.")
print("لم يتم حذف أو تحديث أي أسعار أو تشغيل مراحل التحليل.")
print("=" * 65)

=================================================================
🌧️ الودق AI — استعادة الجداول المفقودة
=================================================================
⚠️ لم يُعثر على مصدر لاستعادة: wadq_stage66_final_report_df
⚠️ لم يُعثر على مصدر لاستعادة: wadq_stage67_final_report_df
⚠️ لم يُعثر على مصدر لاستعادة: wadq_final_ai_report
⚠️ لم يُعثر على مصدر لاستعادة: wadq_global_master_report_df
⚠️ لم يُعثر على مصدر لاستعادة: wadq_global_integrated_df
⚠️ لم يُعثر على مصدر لاستعادة: wadq_global_alerts_df
⚠️ لم يُعثر على مصدر لاستعادة: wadq_stage66_price_check_df
⚠️ لم يُعثر على مصدر لاستعادة: wadq_stage66_price_update_df
⚠️ لم يُعثر على مصدر لاستعادة: wadq_stage66_quality_check_df
⚠️ لم يُعثر على مصدر لاستعادة: wadq_stage66_decision_board_df

=================================================================
📊 النتيجة النهائية
=================================================================
📅 وقت الفحص: 2026-10-16 22:12:25
✅ الجداول الموجودة: 0
♻️ الجداول المستعادة: 0
⚠️ الجداول التي تحتاج إلى مصدر: 10

الجداول التي لم يتوفر مصدر لاستعادتها:
  - wadq_stage66_final_report_df
  - wadq_stage67_final_report_df
  - wadq_final_ai_report
  - wadq_global_master_report_df
  - wadq_global_integrated_df
  - wadq_global_alerts_df
  - wadq_stage66_price_check_df
  - wadq_stage66_price_update_df
  - wadq_stage66_quality_check_df
  - wadq_stage66_decision_board_df

🔍 فحص الجداول المطلوبة:
❌ wadq_stage66_final_report_df: غير متوفر
❌ wadq_stage67_final_report_df: غير متوفر
❌ wadq_final_ai_report: غير متوفر
❌ wadq_global_master_report_df: غير متوفر
❌ wadq_global_integrated_df: غير متوفر
❌ wadq_global_alerts_df: غير متوفر
❌ wadq_stage66_price_check_df: غير متوفر
❌ wadq_stage66_price_update_df: غير متوفر
❌ wadq_stage66_quality_check_df: غير متوفر
❌ wadq_stage66_decision_board_df: غير متوفر

🌧️ انتهى الفحص.
لم يتم حذف أو تحديث أي أسعار أو تشغيل مراحل التحليل.
=================================================================

In [ ]:
 # ============================================================
# 🌧️ الودق AI — المرحلة 68A
# فحص الجداول والأسعار والمؤشرات المتاحة
# ============================================================
import pandas as pd
from datetime import datetime
print("=" * 75)
print("🌧️ الودق AI — المرحلة 68A: الفحص الشامل")
print("=" * 75)
print("\n📅 وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("🔒 وضع التشغيل: فحص فقط — دون تعديل أو حذف أي بيانات")
# ------------------------------------------------------------
# 1. فحص جداول المرحلة 67
# ------------------------------------------------------------
stage67_tables = [غف
    "wadq_stage66_final_report_df",
    "wadq_stage67_audit_df",
    "wadq_stage67_review_df",
    "wadq_stage67_passed_df",
    "wadq_stage67_summary_df",
    "wadq_stage67_log_df"
]
print("\n" + "=" * 75)
print("1️⃣ فحص جداول المرحلة 67")
print("=" * 75)
for name in stage67_tables:
    obj = globals().get(name)
    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name}: {obj.shape[0]} صف × {obj.shape[1]} عمود")
        print("   الأعمدة:", list(obj.columns))
    else:
        print(f"⚠️ {name}: غير موجود في ذاكرة الجلسة الحالية")
# ------------------------------------------------------------
# 2. البحث عن الجداول المتعلقة بالأسعار والمؤشرات والتقارير
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("2️⃣ البحث عن الجداول المتاحة")
print("=" * 75)
keywords = [
    "price", "technical", "indicator", "rsi", "macd",
    "report", "audit", "review", "passed",
    "evaluation", "decision", "risk", "stage",
    "master", "unified", "alert", "market"
]
available_tables = []
for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        if any(word in name.lower() for word in keywords):
            available_tables.append((name, obj))
if available_tables:
    for name, df in sorted(available_tables, key=lambda x: x[0].lower()):
        print(f"📊 {name}: {df.shape[0]} صف × {df.shape[1]} عمود")
else:
    print("⚠️ لم يُعثر على جداول تطابق كلمات البحث.")
# ------------------------------------------------------------
# 3. فحص التقرير النهائي للمرحلة 66
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("3️⃣ فحص التقرير النهائي السابق")
print("=" * 75)
source = globals().get("wadq_stage66_final_report_df")
if isinstance(source, pd.DataFrame):
    print("✅ التقرير موجود.")
    print("عدد الصفوف:", len(source))
    print("عدد الأعمدة:", len(source.columns))
    print("\nأسماء الأعمدة:")
    print(list(source.columns))
    # عرض عينة للقراءة فقط
    print("\n📋 عينة من أول 5 صفوف:")
    display(source.head())
else:
    print("⚠️ التقرير wadq_stage66_final_report_df غير موجود في الذاكرة الحالية.")
    print("لن تتم استعادة التقرير أو تشغيل أي مرحلة سابقة تلقائيًا.")
# ------------------------------------------------------------
# 4. فحص مؤشرات التحليل الفني الموجودة
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("4️⃣ البحث عن مؤشرات التحليل الفني")
print("=" * 75)
indicator_words = [
    "rsi", "macd", "sma", "ema", "ma20", "ma50",
    "trend", "technical", "latest close",
    "latest_price", "السعر", "التغير اليومي",
    "حالة السعر", "مؤشر"
]
indicator_tables_found = 0
for name, df in sorted(available_tables, key=lambda x: x[0].lower()):
    matching_columns = [
        col for col in df.columns
        if any(word in str(col).lower() for word in indicator_words)
    ]
    if matching_columns:
        indicator_tables_found += 1
        print(f"\n📈 الجدول: {name}")
        print("الأعمدة المتعلقة بالأسعار والمؤشرات:")
        print(matching_columns)
if indicator_tables_found == 0:
    print("⚠️ لم يُعثر على أعمدة مطابقة في الجداول التي تم فحصها.")
# ------------------------------------------------------------
# 5. ملخص الفحص
# ------------------------------------------------------------
print("\n" + "=" * 75)
print("5️⃣ ملخص المرحلة 68A")
print("=" * 75)
print("📊 عدد جداول المرحلة 67 المفحوصة:", len(stage67_tables))
print("📊 عدد جداول البيانات المطابقة لكلمات البحث:", len(available_tables))
print("📈 عدد الجداول التي تحتوي على أعمدة أسعار أو مؤشرات:", indicator_tables_found)
print("\n🔒 انتهى الفحص دون تعديل أو حذف أي جدول.")
print("⏸️ لن يبدأ أي إصلاح قبل مراجعة النتائج.")
print("=" * 75)

SyntaxError: invalid syntax (2836395637.py, line 16)

In [ ]:
# ============================================================
# 🌧️ الودق AI — استخراج أكواد المراحل المتقدمة من Google Drive
# لا يحذف الملفات ولا يشغّل الأكواد المستخرجة
# ============================================================

import os
import json
import re
from pathlib import Path
from datetime import datetime

# 1) التأكد من اتصال Google Drive
from google.colab import drive

if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")

ROOT = Path("/content/drive/MyDrive")

# 2) البحث عن جميع دفاتر الودق في Drive
notebooks = []

for path in ROOT.rglob("*.ipynb"):
    name = path.name.lower()

    if "wadq" in name or "الودق" in name:
        notebooks.append(path)

print("=" * 65)
print("🌧️ البحث عن دفاتر الودق AI")
print("=" * 65)
print("عدد الدفاتر المكتشفة:", len(notebooks))

for i, path in enumerate(notebooks, 1):
    print(f"{i}. {path}")

if not notebooks:
    print("لم يتم العثور على دفتر باسم الودق أو wadq.")
    print("لم يتم إنشاء ملف أكواد.")
    raise SystemExit

# 3) استخراج الأكواد من الخلايا التي تشير إلى مراحل متقدمة
all_codes = []
seen_codes = set()

for notebook_path in notebooks:

    print("\n📘 قراءة:", notebook_path.name)

    try:
        with open(notebook_path, "r", encoding="utf-8") as f:
            notebook = json.load(f)
    except Exception as e:
        print("تعذر قراءة الدفتر:", e)
        continue

    for cell_number, cell in enumerate(
        notebook.get("cells", []), start=1
    ):

        source = cell.get("source", [])

        if isinstance(source, list):
            code = "".join(source)
        else:
            code = str(source)

        if not code.strip():
            continue

        # تحديد المراحل المتقدمة
        has_advanced_stage = re.search(
            r"(?:المرحلة|مرحلة|stage)\s*[-_:]?\s*(?:6[5-9]|[7-9]\d|\d{3,})",
            code,
            flags=re.IGNORECASE
        )

        # البحث عن أسماء الجداول المتقدمة
        has_advanced_table = re.search(
            r"wadq_stage(?:6[5-9]|[7-9]\d|\d{3,})",
            code,
            flags=re.IGNORECASE
        )

        if has_advanced_stage or has_advanced_table:

            signature = (
                notebook_path.name,
                cell_number,
                code
            )

            if signature not in seen_codes:
                seen_codes.add(signature)

                all_codes.append({
                    "notebook": str(notebook_path),
                    "cell_number": cell_number,
                    "code": code
                })

            print(
                f"✅ كود متقدم: {notebook_path.name}"
                f" | الخلية {cell_number}"
            )

# 4) حفظ الأكواد المستخرجة في ملف واحد
output_dir = ROOT / "الودق_AI_الأكواد_المستخرجة"
output_dir.mkdir(parents=True, exist_ok=True)

json_path = output_dir / "wadq_advanced_codes.json"
txt_path = output_dir / "wadq_advanced_codes.txt"

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(all_codes, f, ensure_ascii=False, indent=2)

with open(txt_path, "w", encoding="utf-8") as f:

    f.write("🌧️ الودق AI — الأكواد المستخرجة\n")
    f.write("=" * 65 + "\n")
    f.write("تاريخ الاستخراج: " + str(datetime.now()) + "\n")
    f.write("عدد الأكواد: " + str(len(all_codes)) + "\n\n")

    for item in all_codes:
        f.write("=" * 65 + "\n")
        f.write("الدفتر: " + item["notebook"] + "\n")
        f.write("رقم الخلية: " + str(item["cell_number"]) + "\n")
        f.write("=" * 65 + "\n")
        f.write(item["code"] + "\n\n")

# 5) عرض النتيجة
print("\n" + "=" * 65)
print("🌧️ انتهى استخراج الأكواد")
print("=" * 65)
print("عدد الأكواد المستخرجة:", len(all_codes))
print("ملف الأكواد النصي:", txt_path)
print("ملف الأكواد JSON:", json_path)

if len(all_codes) == 0:
    print("\n⚠️ لم يتم العثور على أكواد مراحل متقدمة.")
    print("هذا لا يعني أن الجداول غير موجودة؛")
    print("قد تكون الأكواد مكتوبة بطريقة مختلفة.")

=================================================================
🌧️ البحث عن دفاتر الودق AI
=================================================================
عدد الدفاتر المكتشفة: 0
لم يتم العثور على دفتر باسم الودق أو wadq.
لم يتم إنشاء ملف أكواد.

SystemExit:

/usr/local/lib/python3.13/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
# تثبيت مكتبة قراءة الأخبار أولاً
!pip -q install feedparser
[]
# 🌧️ الوَدْق AI — جالب الأخبار العالمية عبر RSS

import feedparser
from datetime import datetime

news_sources = {
    "أخبار Google الاقتصادية":
        "https://news.google.com/rss/search?q=global+economy+markets&hl=en-US&gl=US&ceid=US:en",
    "أخبار الذهب والنفط":
        "https://news.google.com/rss/search?q=gold+oil+prices&hl=en-US&gl=US&ceid=US:en",
    "أخبار السوق السعودي":
        "https://news.google.com/rss/search?q=Saudi+stock+market&hl=en-US&gl=SA&ceid=SA:en"
}

print("🌧️ الوَدْق AI")
print("وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("=" * 50)

for category, url in news_sources.items():
    print(f"\n📰 {category}")
    feed = feedparser.parse(url)

    if not feed.entries:
        print("لم تصل أخبار. تحققي من اتصال الإنترنت أو المصدر.")
        continue

    for item in feed.entries[:5]:
        print("•", item.get("title", "عنوان غير متاح"))
        print("  المصدر:", item.get("link", "لا يوجد رابط"))

🌧️ الوَدْق AI
وقت الفحص: 2026-10-10 22:00
==================================================

📰 أخبار Google الاقتصادية
• Global growth remains solid in a challenging environment - Peterson Institute for International Economics
  المصدر: https://news.google.com/rss/articles/CBMipAFBVV95cUxQU0NqejZ2Zzh2ek5sUE5DUkRVSXBrZFVGVzZKODJBOXhGdFlEcFRVOFgxVUhIT3FSZWNhOUMydGRiR0pYY2d0NnRSaG45c2Vybk9neWJWNVp3UEFXem1TNFN3M2tmZjdrTWJ1QnRfdzZrM0M0bGxEcGFBbFg0aEwxVXdidkRtTEdjd3RWR3g4S0RVVktxcFNZbTRQMk5xOFFUek1YUQ?oc=5
• World economic growth to slow to 2.6% in 2026, UN trade body says - Yahoo Finance
  المصدر: https://news.google.com/rss/articles/CBMijwFBVV95cUxPbmszdmlXR21SempqTS1yalpxY25vbHp0MWZZNUg4bk1qZzJrTkZaRThRRXplT1YxbGVNd0JyRF9fSk1DN2hPVkh2eWlncTM4WUNtTmxhUG5kMzhDZWlsWS1vUWN1c1FyRncxbmRiVjdJM3RKNjNjVjg5YzhtOXZqb2NOQzgzWVhiTXdzd2p2Yw?oc=5
• The global economy has been resilient — so far - World Bank Blogs
  المصدر: https://news.google.com/rss/articles/CBMimAFBVV95cUxOT3g4RmxxVWF1bWtXR1JiUTAwUUFjajMyR0NEN0kxQk9rc0F6cnMwRHk5Z1ljSVowNmlsTHpRaF9ROV9KRFh6WjEtWldaS2tkZjRUYjZlMTB2ejktenN1WFl3OE5RclZOWGwzaFlvZ080UVh5SnVUZ1JjajFzRFpHM05tSXlobm5heDJ1dWJTSGNUNnV6VElLYw?oc=5
• What’s happening this week in economics? - Deloitte
  المصدر: https://news.google.com/rss/articles/CBMiowFBVV95cUxPakZIT0JxM3JJV25jVHR1SjVUTkdCQThCNkRXOWN6T1ctQWN1RUp4MEctbWVEYVRsX3Y2UmZfS2Zhcmg0LUFUaVVadUNsYXJLWHEtRFR2Zm5aYmc2US1jcVd1YnRqTjdURksyZGdiVVRRNTFGRVFrX2l2WkxvX1JHWlFXYXVKcjNYQnNiWkJGSkRBVVlqYmRUcjc1QU55dEVUaWVR?oc=5
• Annual meetings 2026: Storms lurk behind resilience - OMFIF
  المصدر: https://news.google.com/rss/articles/CBMiiAFBVV95cUxNQV82RDkyVmtQcE9mdVJwRFIxNXd6WlYyU2tTeHpWS0RCVU5Fa29va3lsdmR3ZUZtQ0lYak8wcnRGQ3hhRkhteVRYbUFUdTQ1LWk2akgwNkt4Ulktc00wSXN5Sk9sRjM4c2hVT2JHN2xrTTJ5aUQ1T3hGU01IeGxUdXlfNjYtR3RK?oc=5

📰 أخبار الذهب والنفط
• Gold rises as oil prices drop, investors eye Fed rate trajectory - Yahoo Finance
  المصدر: https://news.google.com/rss/articles/CBMimgFBVV95cUxPUFhmZTdwSU1EMERRbWF3dFFrbHdtQkFhbzNkVWNpeklHVnpkOER2eHNYcnJCYjdNUUNldmxjQUIwUmstU2VFMmMycTJCZDBhTFY2MHg5amRZTnplNUJMT0VNLWVpdnlZR284Sk1XeG00N2VkcHNUQXVOY1Zhb09TUDhKVjkzclBadXl2OU0xUjhqdDJFTGNQZmFR?oc=5
• Gold adds over 1% on easing oil prices, softer dollar - Kitco
  المصدر: https://news.google.com/rss/articles/CBMioAFBVV95cUxQX1dlRXFfSjJ5QVNKdjRMb0ZNNUVmb20xa1hac1NVREpPYTczdEs4X1NqUlhNa0o1YnhaWU9KWG5MN05sYTVET01MaGxyYnlWcnU3blN5QWtXVTVwTDlNZGNFUDIwbVVNeVRTX1ZDemNKaVBnTXh0YjBTMjF4bnBuRzJPcGZ0Zm12UmNKZVN6MWV2MkY4NUxFSEZoWUdyUnlB?oc=5
• Gold hits one-week high, heads for weekly gain on bargain-hunting - Reuters
  المصدر: https://news.google.com/rss/articles/CBMipwFBVV95cUxQVl80MTVLVXR1WWd1MGxyNFRNN1VaNlJ2WFNIeGlrLS1HTGwzc1pZZ3FqaFZyOFBZcDk0VGRnMzVvSUtiSGFyR3c2Z29Fa25XZk1xX0JlWGpJZVlNaEJhWXhoenc3enFGZGZ3QnVUaGg1U2ZTNE9GZGxfTDIyb3hoMl9ycTNsOHpHeWdKRXk1VmdZZ1VITnhMR29NQ3JYUmV4TXJpemVRaw?oc=5
• Gold adds over 1% on easing oil prices, softer dollar - marketscreener.com
  المصدر: https://news.google.com/rss/articles/CBMipwFBVV95cUxNczU5YXFRcjdiWFFPUld0aFM5MWpVRDhiRHBkNG81ejMyeHJuRGZ3MHM1clBUd3MzM1Y3VUZXNGVmMXdIb09sSElEbXFHVjF6VC1lWE9DdGlyMzc2UVVRa240b2pMWHFQTGZic25CNzJQdmJyWHk3Nzg4Y3JTZ1ZWV3R4aXR5QXBvZWVQSm80RG9LdmtHbjVuc3VKWFcwZlpSR2s0dlNNYw?oc=5
• Confidence Fell. Gold and Silver Rose. Same Reason. - GoldSilver
  المصدر: https://news.google.com/rss/articles/CBMiowFBVV95cUxNZnlwZnJwVGRuVm51WkgyRXRjS1p5Q2VLVEpmY0R5ZFhNT1hKMU10Z3pFcENJMXNLXzFTVEc5NThxOVRqRWVHTHlHS2g5WHYyOW1raGhOMEFTaTZIZllQSGlFYWZlYVJVVDZvQS1IQU5Mc09ocko0cHowU1RxOXEteXl1Y2Q5UXIzb1FraWNGQVpVaTRzRE0yb3JOOFVLWTJCV08w?oc=5

📰 أخبار السوق السعودي
• Gulf Stock Markets Lower as Saudi-Houthi Tensions Intensify - Marine Link
  المصدر: https://news.google.com/rss/articles/CBMigAFBVV95cUxPTWxoa0lTSGhEeG4zSldqc2s2Zk54UFNOT0FkaklNbkpoM2RDWWhOdmFINWRZS0hnTm5fN2M4T1NRckR6LW5SckxVRWNVeGtTNGN2d3pkR0xfT29MeXZuSkNLcDJSMmV3SWhlb2EtZjdsWW8zVkNXb00yT1luU0dZQQ?oc=5
• Saudi stocks hit wartime low as Aramco slides, Gulf oil exports rebound - Al-Monitor
  المصدر: https://news.google.com/rss/articles/CBMisgFBVV95cUxNYVRyMWV2U0tSM2FpNDJmcGQxeTJ0NzY3THZ4dnpvT1VNTTJaXzJ2SjFFcHZlYWo3aUJ3QmFOU04zSllDUXlIbVZaVlRudHdKTVhZNFZLOEp3TG5pa1VSS3g4NTdtWkwtcTBwOEZiQmdOd0tKaFRaS0s3WXQtZk9iR1pLTndzWGhCdWxFdFRxb293Z25rQmM3OTdLQzl0WjVjckwtc2NMcnBWbUdxS3AxYlZ3?oc=5
• View / More IPOs won’t be enough to fix the Saudi market - Semafor
  المصدر: https://news.google.com/rss/articles/CBMilgFBVV95cUxPb2NXM3NRQnNYdGZSdzN3Z1dqTGxTc1J4bF9LSEE3VGEtOUx2MDFJOURZeDlnRGxFV0dpZGpOOWY2S2RRdVlUUDcta0lPYnZOeHctOUgwM2ZBbzdzcGxnYmVjRzBJbWlRUzNBZFZBM2NZX3BPZ0t0XzNiV2dhcEdwT2R3S2VrYnpxZ0ZWdnNQODQ1TUlPUHc?oc=5
• 18 Private Deals Executed on the Saudi Stock Market Worth SAR 158 Million - صحيفة مال
  المصدر: https://news.google.com/rss/articles/CBMib0FVX3lxTFB3S0pBYndlMHh5d2RWRUJ3eTRwRF9jQVBnbjVwQ0U4ZHhZQTJYU2l0NG0zTXBjTGJYNkxmVlFIS3VyMUxlUFl4d003dEJyT1JXV0tkVnFkTFFUZmFwb2V6Q0RNNDVmNFhzZXBTaUtQTQ?oc=5
• Saudi stock market in the week ahead - ارقام : اخبار ومعلومات سوق الأسهم السعودي - تاسي
  المصدر: https://news.google.com/rss/articles/CBMiakFVX3lxTFBrazZZUnVEdklYRHVWUXo5T2VyM0dwWTJ6LWNlVEZSaUhBbmRfRHlBZTYwNnhPOGZzeGVpQy1YdllNY1BsNUI4VV9sZXdRM0dUV25rYWJraE0wc3JCMko2QmhUYXhNUG5UbUE?oc=5

In [ ]:
# 🌧️ الودق AI — المرحلة 40
# إنشاء الملخص التنفيذي الذكي
# دون تعديل الجداول السابقة

import pandas as pd

print("🌧️ الودق AI — المرحلة 40")
print("=" * 55)

# التحقق من وجود جدول الأولويات
if "wadq_global_priority_df" not in globals():

    print("⚠️ جدول المرحلة 39 غير موجود.")
    print("تأكدي من تشغيل المرحلة 39 أولًا.")

else:

    # نسخة مستقلة من جدول الأولويات
    priority_df = wadq_global_priority_df.copy()

    # إنشاء الملخص التنفيذي
    total_assets = len(priority_df)

    if "فئة المتابعة" in priority_df.columns:
        categories = priority_df["فئة المتابعة"].fillna(
            "غير مصنف"
        )
    else:
        categories = pd.Series(
            ["غير مصنف"] * total_assets,
            index=priority_df.index
        )

    summary_items = [
        {
            "المؤشر": "إجمالي الأصول",
            "العدد": total_assets
        },
        {
            "المؤشر": "أولوية متابعة أعلى",
            "العدد": int(
                (categories == "أولوية متابعة أعلى").sum()
            )
        },
        {
            "المؤشر": "تنبيهات فنية",
            "العدد": int(
                (categories == "تنبيه فني — مراجعة الزخم").sum()
            )
        },
        {
            "المؤشر": "متابعة بحذر شديد",
            "العدد": int(
                (categories == "متابعة بحذر شديد").sum()
            )
        },
        {
            "المؤشر": "مراقبة عادية",
            "العدد": int(
                (categories == "مراقبة عادية").sum()
            )
        },
        {
            "المؤشر": "أصول دون مطابقة أمريكية",
            "العدد": int(
                categories.str.contains(
                    "لا توجد مطابقة",
                    na=False
                ).sum()
            )
        }
    ]

    wadq_executive_summary_df = pd.DataFrame(
        summary_items
    )

    print("✅ تم إنشاء الملخص التنفيذي.")
    print("\n📊 ملخص الودق AI:")
    display(wadq_executive_summary_df)

    print("\nاسم الجدول الجديد:")
    print("wadq_executive_summary_df")

    print("\n🌧️ انتهت المرحلة 40 بنجاح.")

🌧️ الودق AI — المرحلة 40
=======================================================
⚠️ جدول المرحلة 39 غير موجود.
تأكدي من تشغيل المرحلة 39 أولًا.

In [ ]:
# 🌧️ الودق AI — فحص جداول المرحلة 40 لاستعادة المرحلة 41

import pandas as
pd

print("🔎 فحص جداول مشروع الودق AI")
print("=" * 50)

for name in [
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v3_df",
]:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name} | الصفوف: {len(obj)} | الأعمدة: {len(obj.columns)}")
    else:
        print(f"⚠️ {name} غير موجود في الذاكرة الحالية")

🔎 فحص جداول مشروع الودق AI
==================================================
⚠️ wadq_global_us_unified_df غير موجود في الذاكرة الحالية
⚠️ wadq_executive_summary_df غير موجود في الذاكرة الحالية
⚠️ wadq_global_master_report_df غير موجود في الذاكرة الحالية
⚠️ wadq_global_master_report_v3_df غير موجود في الذاكرة الحالية

In [ ]:
# ============================================================
# 🌧️ الودق AI — استخراج أكواد المراحل المتقدمة من Google Drive
# لا يحذف الملفات ولا يشغّل الأكواد المستخرجة
# ============================================================

import os
import json
import re
from pathlib import Path
from datetime import datetime

# 1) التأكد من اتصال Google Drive
from google.colab import drive

if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")

ROOT = Path("/content/drive/MyDrive")

# 2) البحث عن جميع دفاتر الودق في Drive
notebooks = []

for path in ROOT.rglob("*.ipynb"):
    name = path.name.lower()

    if "wadq" in name or "الودق" in name:
        notebooks.append(path)

print("=" * 65)
print("🌧️ البحث عن دفاتر الودق AI")
print("=" * 65)
print("عدد الدفاتر المكتشفة:", len(notebooks))

for i, path in enumerate(notebooks, 1):
    print(f"{i}. {path}")

if not notebooks:
    print("لم يتم العثور على دفتر باسم الودق أو wadq.")
    print("لم يتم إنشاء ملف أكواد.")
    raise SystemExit

# 3) استخراج الأكواد من الخلايا التي تشير إلى مراحل متقدمة
all_codes = []
seen_codes = set()

for notebook_path in notebooks:

    print("\n📘 قراءة:", notebook_path.name)

    try:
        with open(notebook_path, "r", encoding="utf-8") as f:
            notebook = json.load(f)
    except Exception as e:
        print("تعذر قراءة الدفتر:", e)
        continue

    for cell_number, cell in enumerate(
        notebook.get("cells", []), start=1
    ):

        source = cell.get("source", [])

        if isinstance(source, list):
            code = "".join(source)
        else:
            code = str(source)

        if not code.strip():
            continue

        # تحديد المراحل المتقدمة
        has_advanced_stage = re.search(
            r"(?:المرحلة|مرحلة|stage)\s*[-_:]?\s*(?:6[5-9]|[7-9]\d|\d{3,})",
            code,
            flags=re.IGNORECASE
        )

        # البحث عن أسماء الجداول المتقدمة
        has_advanced_table = re.search(
            r"wadq_stage(?:6[5-9]|[7-9]\d|\d{3,})",
            code,
            flags=re.IGNORECASE
        )

        if has_advanced_stage or has_advanced_table:

            signature = (
                notebook_path.name,
                cell_number,
                code
            )

            if signature not in seen_codes:
                seen_codes.add(signature)

                all_codes.append({
                    "notebook": str(notebook_path),
                    "cell_number": cell_number,
                    "code": code
                })

            print(
                f"✅ كود متقدم: {notebook_path.name}"
                f" | الخلية {cell_number}"
            )

# 4) حفظ الأكواد المستخرجة في ملف واحد
output_dir = ROOT / "الودق_AI_الأكواد_المستخرجة"
output_dir.mkdir(parents=True, exist_ok=True)

json_path = output_dir / "wadq_advanced_codes.json"
txt_path = output_dir / "wadq_advanced_codes.txt"

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(all_codes, f, ensure_ascii=False, indent=2)

with open(txt_path, "w", encoding="utf-8") as f:

    f.write("🌧️ الودق AI — الأكواد المستخرجة\n")
    f.write("=" * 65 + "\n")
    f.write("تاريخ الاستخراج: " + str(datetime.now()) + "\n")
    f.write("عدد الأكواد: " + str(len(all_codes)) + "\n\n")

    for item in all_codes:
        f.write("=" * 65 + "\n")
        f.write("الدفتر: " + item["notebook"] + "\n")
        f.write("رقم الخلية: " + str(item["cell_number"]) + "\n")
        f.write("=" * 65 + "\n")
        f.write(item["code"] + "\n\n")

# 5) عرض النتيجة
print("\n" + "=" * 65)
print("🌧️ انتهى استخراج الأكواد")
print("=" * 65)
print("عدد الأكواد المستخرجة:", len(all_codes))
print("ملف الأكواد النصي:", txt_path)
print("ملف الأكواد JSON:", json_path)

if len(all_codes) == 0:
    print("\n⚠️ لم يتم العثور على أكواد مراحل متقدمة.")
    print("هذا لا يعني أن الجداول غير موجودة؛")
    print("قد تكون الأكواد مكتوبة بطريقة مختلفة.")

=================================================================
🌧️ البحث عن دفاتر الودق AI
=================================================================
عدد الدفاتر المكتشفة: 0
لم يتم العثور على دفتر باسم الودق أو wadq.
لم يتم إنشاء ملف أكواد.

SystemExit:

In [ ]:
from pathlib import Path

ROOT = Path("/content/drive/MyDrive")

print("🔍 البحث عن جميع دفاتر Google Colab")
print("=" * 60)

count = 0

for folder in [
    ROOT / "Colab Notebooks",
    ROOT
]:
    if not folder.exists():
        continue

    for path in folder.rglob("*.ipynb"):
        count += 1
        print(f"{count}. {path}")

        if count >= 300:
            print("توقف العرض عند 300 دفتر.")
            break

    if count >= 300:
        break

print("=" * 60)
print("عدد الدفاتر التي ظهرت:", count)

🔍 البحث عن جميع دفاتر Google Colab
============================================================
============================================================
عدد الدفاتر التي ظهرت: 0

In [ ]:
from google.colab import drive
import os

drive.mount('/content/drive', force_remount=True)

print("هل MyDrive موجود؟")
print(os.path.exists('/content/drive/MyDrive'))

print("\nمحتويات Google Drive:")
if os.path.exists('/content/drive/MyDrive'):
    print(os.listdir('/content/drive/MyDrive')[:50])

Mounted at /content/drive
هل MyDrive موجود؟
True

محتويات Google Drive:
['سيرتي .jpg', '3E1C050F-5055-4F40-A028-C730E9DF4930.jpeg', 'سيرة نجلاء الذاتية.pdf', 'Colab Notebooks', 'الودق AI - سجل المشروع', 'الودق_AI_نسخة_احتياطية']

In [ ]:
from pathlib import Path

ROOT = Path("/content/drive/MyDrive")

folders = [
    ROOT / "الودق_AI_نسخة_احتياطية",
    ROOT / "الودق AI - سجل المشروع"
]

print("🌧️ فحص ملفات الودق والسجلات")
print("=" * 60)

for folder in folders:
    print(f"\n📁 المجلد: {folder.name}")

    if not folder.exists():
        print("المجلد غير موجود")
        continue

    files = [p for p in folder.rglob("*") if p.is_file()]

    if not files:
        print("لا توجد ملفات داخله")
        continue

    for p in files:
        size_kb = p.stat().st_size / 1024
        print(f"📄 {p.name} | الحجم: {size_kb:.1f} KB")
        print(f"   المسار: {p}")

print("\nانتهى الفحص.")

🌧️ فحص ملفات الودق والسجلات
============================================================

📁 المجلد: الودق_AI_نسخة_احتياطية
لا توجد ملفات داخله

📁 المجلد: الودق AI - سجل المشروع
📄 سجل_الودق_AI.txt | الحجم: 2.8 KB
   المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.txt
📄 سجل_الاستئناف.txt | الحجم: 0.2 KB
   المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الاستئناف.txt
📄 سجل_الودق_AI.gdoc | الحجم: 0.2 KB
   المسار: /content/drive/MyDrive/الودق AI - سجل المشروع/سجل_الودق_AI.gdoc

انتهى الفحص.

In [ ]:
# 🌧️ الودق AI — استعادة الجداول المفقودة مباشرة

import os
import pickle
import pandas as pd
from pathlib import Path
from IPython.display import display

backup_dir = Path("/content/drive/MyDrive/الودق_AI_نسخة_احتياطية")
backup_file = backup_dir / "wadq_ai_tables_backup.pkl"

# البحث عن ملف النسخة الاحتياطية
if not backup_file.exists():
    print("❌ لم أجد ملف wadq_ai_tables_backup.pkl")
    print("أرسلي أسماء الملفات الموجودة في مجلد النسخة الاحتياطية.")
else:
    # قراءة النسخة الاحتياطية
    with open(backup_file, "rb") as f:
        backup_data = pickle.load(f)

    # استعادة الجداول إلى مساحة عمل جديدة
    wadq_recovered_tables = {}

    if isinstance(backup_data, dict):
        wadq_recovered_tables = {
            name: table.copy() if isinstance(table, pd.DataFrame) else table
            for name, table in backup_data.items()
        }

    # عرض الجداول المستعادة
    recovered_summary = []

    for name, table in wadq_recovered_tables.items():
        if isinstance(table, pd.DataFrame):
            recovered_summary.append({
                "اسم الجدول": name,
                "عدد الصفوف": len(table),
                "عدد الأعمدة": len(table.columns)
            })

    wadq_recovered_summary_df = pd.DataFrame(recovered_summary)

    print("🌧️ نتيجة استعادة الجداول")
    print("عدد الجداول المستعادة:", len(wadq_recovered_tables))

    display(wadq_recovered_summary_df)

❌ لم أجد ملف wadq_ai_tables_backup.pkl
أرسلي أسماء الملفات الموجودة في مجلد النسخة الاحتياطية.

In [ ]:
# ============================================================
# 🌧️ الودق AI — فحص واستعادة الجداول المفقودة
# بعد المرحلة 67
# ============================================================

import pandas as pd

print("=" * 65)
print("🌧️ الودق AI — فحص الجداول واستعادتها")
print("=" * 65)

# الجداول المطلوبة
required_tables = [
    "wadq_evaluation_df",
    "wadq_smart_report",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "wadq_global_alerts_df",
    "wadq_global_integrated_df",
    "wadq_global_market_df",
    "wadq_ticker_news_df",
    "wadq_global_news_df",
    "wadq_global_news_analysis_df"
]

# مصادر بديلة لاستعادة الجداول
sources = {
    "wadq_evaluation_df": [
        "wadq_evaluation_source_df",
        "wadq_final_ai_report"
    ],
    "wadq_smart_report": [
        "wadq_smart_report_source_df",
        "wadq_final_ai_report"
    ],
    "wadq_final_ai_report": [
        "wadq_final_report_source_df",
        "wadq_evaluation_df",
        "wadq_smart_report"
    ],
    "wadq_global_master_report_df": [
        "wadq_global_master_source_df",
        "wadq_global_integrated_df"
    ],
    "wadq_global_alerts_df": [
        "wadq_global_alerts_source_df",
        "wadq_global_market_df"
    ],
    "wadq_global_integrated_df": [
        "wadq_global_integrated_source_df",
        "wadq_global_master_report_df"
    ],
    "wadq_global_market_df": [
        "wadq_global_market_source_df",
        "wadq_global_alerts_df"
    ],
    "wadq_ticker_news_df": [
        "wadq_ticker_news_source_df"
    ],
    "wadq_global_news_df": [
        "wadq_global_news_source_df"
    ],
    "wadq_global_news_analysis_df": [
        "wadq_global_news_analysis_source_df"
    ]
}

# فحص الجداول واستعادة المفقود فقط
restored = []
existing = []
missing = []

for table_name in required_tables:

    # إذا كان الجدول موجودًا، لا نلمسه
    current_table = globals().get(table_name)

    if isinstance(current_table, pd.DataFrame):
        existing.append(table_name)
        print(f"✅ موجود: {table_name} | {current_table.shape}")
        continue

    # البحث عن مصدر بديل
    recovered = False

    for source_name in sources.get(table_name, []):

        source_obj = globals().get(source_name)

        if isinstance(source_obj, pd.DataFrame):

            # نسخ المصدر دون تعديل الأصل
            globals()[table_name] = source_obj.copy()

            restored.append(table_name)

            print(
                f"♻️ استُعيد: {table_name} "
                f"من {source_name} | {source_obj.shape}"
            )

            recovered = True
            break

    if not recovered:
        missing.append(table_name)
        print(f"⚠️ لم يُعثر على مصدر: {table_name}")

# التقرير النهائي
print("\n" + "=" * 65)
print("📊 نتيجة الفحص والاستعادة")
print("=" * 65)

print(f"الجداول الموجودة: {len(existing)}")
print(f"الجداول المستعادة: {len(restored)}")
print(f"الجداول غير المتاحة: {len(missing)}")

if missing:
    print("\nالجداول التي تحتاج إلى استعادة:")
    for name in missing:
        print(" -", name)

print("\n✅ انتهى الفحص دون حذف أي جدول موجود.")
print("⚠️ لم يتم تحديث الأسعار أو إعادة تنفيذ المراحل السابقة.")

=================================================================
🌧️ الودق AI — فحص الجداول واستعادتها
=================================================================
⚠️ لم يُعثر على مصدر: wadq_evaluation_df
⚠️ لم يُعثر على مصدر: wadq_smart_report
⚠️ لم يُعثر على مصدر: wadq_final_ai_report
⚠️ لم يُعثر على مصدر: wadq_global_master_report_df
⚠️ لم يُعثر على مصدر: wadq_global_alerts_df
⚠️ لم يُعثر على مصدر: wadq_global_integrated_df
⚠️ لم يُعثر على مصدر: wadq_global_market_df
⚠️ لم يُعثر على مصدر: wadq_ticker_news_df
⚠️ لم يُعثر على مصدر: wadq_global_news_df
⚠️ لم يُعثر على مصدر: wadq_global_news_analysis_df

=================================================================
📊 نتيجة الفحص والاستعادة
=================================================================
الجداول الموجودة: 0
الجداول المستعادة: 0
الجداول غير المتاحة: 10

الجداول التي تحتاج إلى استعادة:
 - wadq_evaluation_df
 - wadq_smart_report
 - wadq_final_ai_report
 - wadq_global_master_report_df
 - wadq_global_alerts_df
 - wadq_global_integrated_df
 - wadq_global_market_df
 - wadq_ticker_news_df
 - wadq_global_news_df
 - wadq_global_news_analysis_df

✅ انتهى الفحص دون حذف أي جدول موجود.
⚠️ لم يتم تحديث الأسعار أو إعادة تنفيذ المراحل السابقة.

In [ ]:
# =========================================================
# 🌧️ الودق AI — فحص الجداول بعد المرحلة 40
# فحص فقط دون تعديل أو حذف أي جدول
# =========================================================

import pandas as pd

print("🌧️ الودق AI — فحص الجداول")
print("=" * 60)

table_names = [
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_global_news_analysis_df",
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v3_df",
    "wadq_stage41_decision_df",
]

found_count = 0

for name in table_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        found_count += 1
        print(
            f"✅ {name} | "
            f"الصفوف: {len(obj)} | "
            f"الأعمدة: {len(obj.columns)}"
        )
    else:
        print(f"⚠️ {name} | غير موجود في الذاكرة")

print("=" * 60)
print("إجمالي الجداول التي عُثر عليها:", found_count)
print("انتهى الفحص دون تعديل الجداول.")

🌧️ الودق AI — فحص الجداول
============================================================
⚠️ wadq_global_market_df | غير موجود في الذاكرة
⚠️ wadq_global_alerts_df | غير موجود في الذاكرة
⚠️ wadq_global_news_analysis_df | غير موجود في الذاكرة
⚠️ wadq_global_us_unified_df | غير موجود في الذاكرة
⚠️ wadq_executive_summary_df | غير موجود في الذاكرة
⚠️ wadq_global_master_report_df | غير موجود في الذاكرة
⚠️ wadq_global_master_report_v3_df | غير موجود في الذاكرة
⚠️ wadq_stage41_decision_df | غير موجود في الذاكرة
============================================================
إجمالي الجداول التي عُثر عليها: 0
انتهى الفحص دون تعديل الجداول.

In [ ]:
# 🌧️ الودق AI — التحقق من بيانات المرحلة 40

import pandas as pd

table_name = "wadq_global_us_unified_df"

if table_name in globals():
    df = globals()[table_name]
    print("✅ جدول المرحلة 40 موجود.")
    print("اسم الجدول:", table_name)
    print("عدد الأصول:", len(df))
    print("عدد الأعمدة:", len(df.columns))
    display(df.head())
else:
    print("⚠️ جدول المرحلة 40 غير موجود في الذاكرة الحالية.")
    print("سنحدد كيفية استعادته قبل تشغيل المرحلة 41.")

⚠️ جدول المرحلة 40 غير موجود في الذاكرة الحالية.
سنحدد كيفية استعادته قبل تشغيل المرحلة 41.

In [ ]:
# =========================================================
# 🌧️ الودق AI — المرحلة 42
# تصنيف حركة الأصول وإعداد ملخص السوق
# =========================================================

import pandas as pd
import numpy as np

# التأكد من وجود جدول المرحلة 41
if 'wadq_stage41_decision_df' not in globals():
    print("⚠️ لم يتم العثور على جدول المرحلة 41 في الذاكرة الحالية.")
else:
    # إنشاء نسخة مستقلة للعمل دون تعديل الجدول السابق
    wadq_stage42_market_df = wadq_stage41_decision_df.copy()

    # التحقق من الأعمدة المطلوبة
    required_columns = ['الأصل', 'الرمز', 'التغير اليومي %']

    missing_columns = [
        col for col in required_columns
        if col not in wadq_stage42_market_df.columns
    ]

    if missing_columns:
        print(f"⚠️ الأعمدة التالية غير موجودة: {missing_columns}")

⚠️ لم يتم العثور على جدول المرحلة 41 في الذاكرة الحالية.

In [ ]:
# 🌧️ الودق AI — فحص الذاكرة بعد الاتصال

import pandas as pd

print("🔍 فحص جداول مشروع الودق AI\n")

tables_found = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        tables_found.append((name, len(obj)))

if tables_found:
    for name, rows in tables_found:
        print(f"✅ {name} | عدد الصفوف: {rows}")
else:
    print("⚠️ لا توجد جداول بيانات في الذاكرة الحالية.")
    print("سنستعيد الجداول من الخلايا السابقة عند الحاجة.")

🔍 فحص جداول مشروع الودق AI

⚠️ لا توجد جداول بيانات في الذاكرة الحالية.
سنستعيد الجداول من الخلايا السابقة عند الحاجة.

In [ ]:
# =========================================================
# 🌧️ الودق AI — المرحلة 42
# تصنيف حركة الأصول وإعداد ملخص السوق
# =========================================================

import pandas as pd
import numpy as np

# التأكد من وجود جدول المرحلة 41
if 'wadq_stage41_decision_df' not in globals():
    raise NameError(
        "لم يتم العثور على جدول المرحلة 41: "
        "wadq_stage41_decision_df"
    )

# إنشاء نسخة مستقلة للعمل دون تعديل الجدول السابق
wadq_stage42_market_df = wadq_stage41_decision_df.copy()

# التحقق من الأعمدة المطلوبة
required_columns = ['الأصل', 'الرمز', 'التغير اليومي %']

missing_columns = [
    col for col in required_columns
    if col not in wadq_stage42_market_df.columns
]

if missing_columns:
    raise ValueError(
        f"الأعمدة التالية غير موجودة: {missing_columns}"
    )

# تحويل نسبة التغير إلى أرقام
wadq_stage42_market_df['التغير اليومي %'] = pd.to_numeric(
    wadq_stage42_market_df['التغير اليومي %']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip(),
    errors='coerce'
)

# تصنيف حركة الأصول
def wadq_classify_movement(change):
    if pd.isna(change):
        return 'غير متاح'
    elif change >= 1:
        return 'ارتفاع ملحوظ'
    elif change <= -1:
        return 'انخفاض ملحوظ'
    else:
        return 'حركة محدودة'

wadq_stage42_market_df['تصنيف الحركة'] = (
    wadq_stage42_market_df['التغير اليومي %']
    .apply(wadq_classify_movement)
)

# ترتيب الأصول من أعلى تغير إلى أدنى تغير
wadq_stage42_market_df = (
    wadq_stage42_market_df
    .sort_values(
        by='التغير اليومي %',
        ascending=False,
        na_position='last'
    )
    .reset_index(drop=True)
)

# إنشاء ملخص السوق
wadq_stage42_summary_df = (
    wadq_stage42_market_df['تصنيف الحركة']
    .value_counts()
    .reindex(
        [
            'ارتفاع ملحوظ',
            'انخفاض ملحوظ',
            'حركة محدودة',
            'غير متاح'
        ],
        fill_value=0
    )
    .rename_axis('تصنيف الحركة')
    .reset_index(name='عدد الأصول')
)

# عرض النتائج
print("🌧️ الودق AI — المرحلة 42")
print("=" * 50)

print("✅ تم إنشاء جدول تصنيف حركة الأصول.")
print("📊 إجمالي الأصول:", len(wadq_stage42_market_df))
print("📋 إجمالي الأعمدة:", len(wadq_stage42_market_df.columns))

print("\n📊 ملخص حركة السوق:")
display(wadq_stage42_summary_df)

print("\n📈 تفاصيل تصنيف الأصول:")
display(wadq_stage42_market_df)

NameError: لم يتم العثور على جدول المرحلة 41: wadq_stage41_decision_df

In [ ]:
# 🌧️ الودق AI — فحص جداول المرحلة 41

print("🔍 البحث عن جداول المرحلة 41...\n")

for name in sorted(globals()):
    if 'stage41' in name.lower() or 'stage_41' in name.lower():
        obj = globals()[name]

        if isinstance(obj, pd.DataFrame):
            print(f"✅ اسم الجدول: {name}")
            print(f"📊 عدد الصفوف: {len(obj)}")
            print(f"📋 الأعمدة: {list(obj.columns)}")
            print("-" * 50)

🔍 البحث عن جداول المرحلة 41...

In [ ]:
# 🌧️ الودق AI — فحص الجداول الموجودة في الذاكرة

print("🔍 الجداول الموجودة حاليًا:\n")

found = False

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(f"📊 {name} | عدد الصفوف: {len(obj)}")
        found = True

if not found:
    print("⚠️ لم يتم العثور على جداول في الذاكرة.")

🔍 الجداول الموجودة حاليًا:

⚠️ لم يتم العثور على جداول في الذاكرة.

In [ ]:
# 🌧️ الودق AI — المرحلة 39
# إنشاء لوحة ذكية لترتيب أولويات المتابعة
# دون تعديل الجداول السابقة

import pandas as pd

print("🌧️ الودق AI — المرحلة 39")
print("=" * 60)

# التحقق من وجود جدول المرحلة 38
if "wadq_global_us_unified_df" not in globals():

    print("⚠️ جدول المرحلة 38 غير موجود في جلسة التشغيل.")
    print("نحتاج إلى استعادة الجدول قبل متابعة العمل.")

else:

    # إنشاء نسخة مستقلة لحماية الجدول الأصلي
    priority_df = wadq_global_us_unified_df.copy()

    # ترتيب فئات الأولوية من الأعلى إلى الأدنى
    priority_order = {
        "أولوية متابعة أعلى": 1,
        "تنبيه فني — مراجعة الزخم": 2,
        "متابعة بحذر شديد": 3,
        "مراقبة عادية": 4
    }

    # تحديد ترتيب كل أصل
    priority_df["ترتيب الأولوية"] = (
        priority_df["أولوية المتابعة"]
        .map(priority_order)
        .fillna(5)
        .astype(int)
        if "أولوية المتابعة" in priority_df.columns
        else 5
    )

    # وصف الأولوية للأصول التي لا تملك تصنيف متابعة أمريكيًا
    if "أولوية المتابعة" in priority_df.columns:
        priority_df["فئة المتابعة"] = (
            priority_df["أولوية المتابعة"].fillna(
                "لا توجد مطابقة في لوحة المتابعة الأمريكية"
            )
        )
    else:
        priority_df["فئة المتابعة"] = (
            "لا توجد مطابقة في لوحة المتابعة الأمريكية"
        )

    # ترتيب الأصول حسب الأولوية
    wadq_global_priority_df = (
        priority_df
        .sort_values(
            by=["ترتيب الأولوية", "الأصل"],
            ascending=[True, True],
            kind="stable"
        )
        .reset_index(drop=True)
    )

    # عرض الأعمدة الأساسية المتاحة
    display_columns = [
        "ترتيب الأولوية",
        "نوع الأصل",
        "الأصل",
        "الرمز",
        "الإشارة المدمجة",
        "فئة المتابعة",
        "حالة بيانات المتابعة"
    ]

    display_columns = [
        col for col in display_columns
        if col in wadq_global_priority_df.columns
    ]

    print("✅ تم إنشاء لوحة ترتيب الأولويات.")
    print("عدد الأصول:", len(wadq_global_priority_df))
    print("عدد الأعمدة في اللوحة الأصلية:",
          len(wadq_global_us_unified_df.columns))

    print("\n📊 لوحة ترتيب الأولويات:")
    display(wadq_global_priority_df[display_columns])

    print("\n📌 ملخص فئات المتابعة:")
    display(
        wadq_global_priority_df["فئة المتابعة"]
        .value_counts()
        .rename_axis("فئة المتابعة")
        .reset_index(name="عدد الأصول")
    )

    print("\nاسم الجدول الجديد:")
    print("wadq_global_priority_df")

    print("\n🌧️ انتهت المرحلة 39 بنجاح.")

🌧️ الودق AI — المرحلة 39
============================================================
⚠️ جدول المرحلة 38 غير موجود في جلسة التشغيل.
نحتاج إلى استعادة الجدول قبل متابعة العمل.

In [ ]:
# 🌧️ الودق AI — فحص الجداول المطلوبة للاستعادة

import pandas as pd

required_tables = [
    "wadq_global_market_df",
    "wadq_global_us_unified_df",
    "wadq_global_priority_df",
    "wadq_executive_summary_df",
    "wadq_stage41_decision_df"
]

print("🌧️ الودق AI — فحص الجداول")
print("=" * 55)

for name in required_tables:
    if name in globals() and isinstance(globals()[name], pd.DataFrame):
        df = globals()[name]
        print(f"✅ {name}: موجود")
        print(f"   الصفوف: {len(df)} | الأعمدة: {len(df.columns)}")
    else:
        print(f"⚠️ {name}: غير موجود في الذاكرة")

print("=" * 55)
print("✅ انتهى الفحص دون تعديل أي جدول.")

🌧️ الودق AI — فحص الجداول
=======================================================
✅ wadq_global_market_df: موجود
   الصفوف: 17 | الأعمدة: 6
⚠️ wadq_global_us_unified_df: غير موجود في الذاكرة
⚠️ wadq_global_priority_df: غير موجود في الذاكرة
⚠️ wadq_executive_summary_df: غير موجود في الذاكرة
⚠️ wadq_stage41_decision_df: غير موجود في الذاكرة
=======================================================
✅ انتهى الفحص دون تعديل أي جدول.

In [ ]:
# @title Default title text
# الوَدْق AI - تجهيز تحليل الأسواق

!pip -q install yfinance pandas numpy

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime

print("🌧️ الوَدْق AI")
print("تجهيز نظام تحليل الأسواق")
print("وقت التشغيل:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("تم تجهيز المكتبات الأولية.")

🌧️ الوَدْق AI
تجهيز نظام تحليل الأسواق
وقت التشغيل: 2026-10-10 22:08
تم تجهيز المكتبات الأولية.

In [ ]:
# الوَدْق AI - التحليل الفني الأول للذهب

import yfinance as yf
import pandas as pd
import numpy as np

# جلب بيانات الذهب
gold = yf.download(
    "GC=F",
    period="3mo",
    interval="1d",
    auto_adjust=True,
    progress=False
)

if gold.empty:
    print("لم تصل بيانات الذهب. تحققي من الاتصال بالإنترنت وحاولي لاحقًا.")
else:
    close = gold["Close"]

    # التعامل مع اختلاف شكل البيانات
    if isinstance(close, pd.DataFrame):
        close = close.iloc[:, 0]

    # حساب المتوسطات المتحركة
    gold["MA20"] = close.rolling(20).mean()
    gold["MA50"] = close.rolling(50).mean()

    # حساب RSI
    delta = close.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1/14, min_periods=14, adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1/14, min_periods=14, adjust=False
    ).mean()

    rs = avg_gain / avg_loss.replace(0, np.nan)
    gold["RSI"] = 100 - (100 / (1 + rs))

    # حساب MACD
    ema12 = close.ewm(span=12, adjust=False).mean()
    ema26 = close.ewm(span=26, adjust=False).mean()

    gold["MACD"] = ema12 - ema26
    gold["Signal"] = gold["MACD"].ewm(
        span=9, adjust=False
    ).mean()

    # استخراج آخر القيم بشكل آمن كقيم رقمية مفردة
    latest_close = float(close.iloc[-1])
    latest_rsi = float(gold["RSI"].iloc[-1])
    latest_macd = float(gold["MACD"].iloc[-1])
    latest_signal = float(gold["Signal"].iloc[-1])
    latest_ma20 = float(gold["MA20"].iloc[-1])
    latest_ma50 = float(gold["MA50"].iloc[-1])

    print("🌧️ الوَدْق AI — تحليل الذهب")
    print("-" * 35)
    print("آخر تاريخ متاح:", gold.index[-1].date())
    print(f"سعر الذهب: {latest_close:.2f} دولار للأونصة")
    print(f"RSI: {latest_rsi:.2f}")
    print(f"MACD: {latest_macd:.3f}")
    print(f"خط الإشارة: {latest_signal:.3f}")

    if pd.notna(latest_ma20) and pd.notna(latest_ma50):
        if latest_ma20 > latest_ma50:
            print("الاتجاه وفق المتوسطات: إيجابي")
        else:
            print("الاتجاه وفق المتوسطات: سلبي")

    print("\nهذه قراءة فنية تعليمية وليست توصية شراء أو بيع.")

🌧️ الوَدْق AI — تحليل الذهب
-----------------------------------
آخر تاريخ متاح: 2026-10-09
سعر الذهب: 4216.30 دولار للأونصة
RSI: 42.47
MACD: -63.657
خط الإشارة: -56.951
الاتجاه وفق المتوسطات: سلبي

هذه قراءة فنية تعليمية وليست توصية شراء أو بيع.

In [ ]:
# =========================================================
# 🌧️ الودق AI — المرحلة 41
# إعادة إنشاء جدول القرار دون تعديل الجداول السابقة
# =========================================================

import pandas as pd

print("🌧️ الودق AI — المرحلة 41")
print("=" * 60)

# البحث عن الجدول الأساسي
source_df = None
source_name = None

for name in [
    "wadq_global_us_unified_df",
    "wadq_global_priority_df",
    "wadq_global_master_report_v3_df",
    "wadq_global_master_report_df"
]:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        source_df = obj.copy()
        source_name = name
        break

# التحقق من وجود البيانات
if source_df is None:

    print("⚠️ لم يتم العثور على الجدول الأساسي في الذاكرة.")
    print("أرسلي لي صورة لهذه الرسالة قبل تنفيذ أي خطوة أخرى.")

else:

    # التأكد من الأعمدة الأساسية المطلوبة
    required_columns = [
        "نوع الأصل",
        "الأصل",
        "الرمز",
        "السعر",
        "التغير اليومي %"
    ]

    missing_columns = [
        col for col in required_columns
        if col not in source_df.columns
    ]

    if missing_columns:

        print("⚠️ توجد أعمدة مطلوبة غير متاحة:")
        print(missing_columns)
        print("الجدول المستخدم:", source_name)

    else:

        # إنشاء نسخة مستقلة للمرحلة 41
        wadq_stage41_decision_df = source_df.copy()

        print("✅ تم إنشاء جدول المرحلة 41 بنجاح.")
        print("الجدول المصدر:", source_name)
        print("اسم الجدول الجديد: wadq_stage41_decision_df")
        print("عدد الأصول:", len(wadq_stage41_decision_df))
        print("عدد الأعمدة:", len(wadq_stage41_decision_df.columns))

        print("\n📊 معاينة جدول القرار:")

        display(
            wadq_stage41_decision_df[
                required_columns
            ].head(10)
        )

        print("\n🌧️ انتهت المرحلة 41.")
        print("يمكننا بعد التحقق الانتقال إلى المرحلة 42.")

🌧️ الودق AI — المرحلة 41
============================================================
⚠️ لم يتم العثور على الجدول الأساسي في الذاكرة.
أرسلي لي صورة لهذه الرسالة قبل تنفيذ أي خطوة أخرى.

In [ ]:
# 🌧️ الودق AI — فحص ذاكرة المشروع
import pandas as pd

print("🌧️ فحص ذاكرة مشروع الودق AI")
print("=" * 50)

found = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        found.append((name, len(obj), len(obj.columns)))

if found:
    print("✅ تم العثور على الجداول التالية:")
    for name, rows, cols in found:
        print(f"📊 {name} | الأصول: {rows} | الأعمدة: {cols}")
else:
    print("⚠️ لم يتم العثور على أي جداول DataFrame في الذاكرة.")
    print("نحتاج إلى التحقق من حالة الجلسة قبل استعادة المشروع.")

🌧️ فحص ذاكرة مشروع الودق AI
==================================================
⚠️ لم يتم العثور على أي جداول DataFrame في الذاكرة.
نحتاج إلى التحقق من حالة الجلسة قبل استعادة المشروع.

In [ ]:
# 🇸🇦 الوَدْق AI — ماسح أولي للأسهم السعودية

!pip -q install yfinance

import yfinance as yf
import pandas as pd
from datetime import datetime

stocks = {
    "أرامكو": "2222.SR",
    "مصرف الراجحي": "1120.SR",
    "الأهلي السعودي": "1180.SR",
    "سابك": "2010.SR",
    "معادن": "1211.SR",
    "الاتصالات السعودية": "7010.SR",
    "كهرباء السعودية": "5110.SR",
    "مصرف الإنماء": "1150.SR",
    "دار الأركان": "4300.SR",
    "جرير": "4190.SR",
    "المراعي": "2280.SR",
    "أكوا باور": "2082.SR",
    "stc": "7010.SR",
}

print("🇸🇦 الوَدْق AI — فحص الأسهم السعودية")
print("وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("=" * 55)

results = []

for name, ticker in stocks.items():
    try:
        data = yf.download(
            ticker,
            period="3mo",
            interval="1d",
            auto_adjust=True,
            progress=False
        )

        if data.empty or len(data) < 20:
            print(f"⚠️ {name}: لا توجد بيانات كافية")
            continue

        close = data["Close"]

        if isinstance(close, pd.DataFrame):
            close = close.iloc[:, 0]

        close = close.dropna()

        price = float(close.iloc[-1])
        previous = float(close.iloc[-2])
        change = ((price - previous) / previous) * 100

        ma20 = float(close.rolling(20).mean().iloc[-1])

        if price > ma20:
            trend = "فوق متوسط 20 يومًا"
        elif price < ma20:
            trend = "تحت متوسط 20 يومًا"
        else:
            trend = "قرب متوسط 20 يومًا"

        results.append({
            "الشركة": name,
            "الرمز": ticker,
            "السعر": round(price, 2),
            "التغير اليومي %": round(change, 2),
            "الاتجاه الفني": trend
        })

    except Exception as e:
        print(f"⚠️ تعذّر فحص {name}: {str(e)[:100]}")

if results:
    report = pd.DataFrame(results)
    report = report.sort_values(
        "التغير اليومي %",
        ascending=False
    )

    display(report)

    print("\nتنبيه: هذه عينة أولية وليست جميع شركات السوق السعودي.")
    print("البيانات من Yahoo Finance وقد تكون متأخرة أو غير متاحة.")
    print("النتائج تعليمية وليست توصية شراء أو بيع.")
else:
    print("لم تصل بيانات الأسهم. تحققي من الاتصال ومصدر البيانات.")

🇸🇦 الوَدْق AI — فحص الأسهم السعودية
وقت الفحص: 2026-10-10 22:23
=======================================================

                الشركة    الرمز   السعر  التغير اليومي %       الاتجاه الفني
0               أرامكو  2222.SR   25.74            -0.39  فوق متوسط 20 يومًا
12                 stc  7010.SR   42.60            -0.93  تحت متوسط 20 يومًا
5   الاتصالات السعودية  7010.SR   42.60            -0.93  تحت متوسط 20 يومًا
4                معادن  1211.SR   62.40            -0.95  تحت متوسط 20 يومًا
1         مصرف الراجحي  1120.SR   62.30            -1.42  تحت متوسط 20 يومًا
3                 سابك  2010.SR   45.80            -1.63  تحت متوسط 20 يومًا
10             المراعي  2280.SR   44.44            -1.86  تحت متوسط 20 يومًا
6      كهرباء السعودية  5110.SR   15.27            -1.93  تحت متوسط 20 يومًا
7         مصرف الإنماء  1150.SR   23.85            -2.09  تحت متوسط 20 يومًا
9                 جرير  4190.SR   16.00            -2.32  تحت متوسط 20 يومًا
8          دار الأركان  4300.SR   18.67            -3.11  تحت متوسط 20 يومًا
2       الأهلي السعودي  1180.SR   37.86            -3.12  تحت متوسط 20 يومًا
11           أكوا باور  2082.SR  164.90            -3.62  تحت متوسط 20 يومًا

تنبيه: هذه عينة أولية وليست جميع شركات السوق السعودي.
البيانات من Yahoo Finance وقد تكون متأخرة أو غير متاحة.
النتائج تعليمية وليست توصية شراء أو بيع.

In [ ]:
# 🇸🇦 الوَدْق AI — ماسح موسّع للسوق السعودي

!pip -q install yfinance requests pandas numpy

import yfinance as yf
import pandas as pd
import numpy as np
import requests
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

print("🇸🇦 الوَدْق AI — الماسح الموسّع")
print("وقت التشغيل:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("=" * 60)

# قائمة أولية احتياطية إذا تعذّر الحصول على قائمة موسّعة
fallback_stocks = {
    "أرامكو": "2222.SR",
    "الراجحي": "1120.SR",
    "الأهلي السعودي": "1180.SR",
    "سابك": "2010.SR",
    "معادن": "1211.SR",
    "الاتصالات السعودية": "7010.SR",
    "كهرباء السعودية": "5110.SR",
    "مصرف الإنماء": "1150.SR",
    "دار الأركان": "4300.SR",
    "جرير": "4190.SR",
    "المراعي": "2280.SR",
    "أكوا باور": "2082.SR",
}

# نحاول تحميل قائمة رموز موسعة من ملف عام.
# إذا لم يتوفر الملف أو لم تكن بنيته مناسبة، نستخدم القائمة الاحتياطية.
stocks = fallback_stocks.copy()

candidate_urls = [
    "https://raw.githubusercontent.com/datasets/"
    "saudi-arabia-stock-market/main/data/stocks.csv"
]

for url in candidate_urls:
    try:
        response = requests.get(url, timeout=10)
        if response.ok and response.text.strip():
            from io import StringIO
            candidate = pd.read_csv(StringIO(response.text))

            print("تم العثور على ملف بيانات عام، جارٍ فحص أعمدته.")
            print("الأعمدة المتاحة:", list(candidate.columns))
            print("لم يتم اعتماد الملف تلقائيًا؛ نحتاج إلى التحقق من بنيته.")
            break
    except Exception:
        pass

print(f"\nعدد الأسهم في القائمة الحالية: {len(stocks)}")
print("ملاحظة: القائمة الاحتياطية ليست جميع الشركات المدرجة.")
print("\nبدء فحص بيانات الأسعار...\n")

def analyze_stock(item):
    name, ticker = item

    try:
        data = yf.download(
            ticker,
            period="3mo",
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )

        if data.empty or len(data) < 30:
            return None

        close = data["Close"]

        if isinstance(close, pd.DataFrame):
            close = close.iloc[:, 0]

        close = pd.to_numeric(close, errors="coerce").dropna()

        if len(close) < 30:
            return None

        price = float(close.iloc[-1])
        previous = float(close.iloc[-2])

        if previous == 0:
            return None

        change = (price - previous) / previous * 100
        ma20 = float(close.rolling(20).mean().iloc[-1])
        ma50 = float(close.rolling(50).mean().iloc[-1])

        delta = close.diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.ewm(
            alpha=1/14, min_periods=14, adjust=False
        ).mean()

        avg_loss = loss.ewm(
            alpha=1/14, min_periods=14, adjust=False
        ).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)
        rsi_series = 100 - (100 / (1 + rs))
        rsi_value = rsi_series.iloc[-1]

        if pd.isna(rsi_value):
            rsi_value = np.nan
        else:
            rsi_value = float(rsi_value)

        if price > ma20 and ma20 > ma50:
            trend = "اتجاه إيجابي وفق المتوسطات"
        elif price < ma20 and ma20 < ma50:
            trend = "اتجاه سلبي وفق المتوسطات"
        else:
            trend = "اتجاه مختلط"

        return {
            "الشركة": name,
            "الرمز": ticker,
            "السعر": round(price, 2),
            "التغير اليومي %": round(change, 2),
            "RSI": round(rsi_value, 2) if not np.isnan(rsi_value) else None,
            "الاتجاه الفني": trend,
            "تاريخ آخر بيانات": str(close.index[-1].date())
        }

    except Exception:
        return None

results = []

with ThreadPoolExecutor(max_workers=3) as executor:
    futures = [
        executor.submit(analyze_stock, item)
        for item in stocks.items()
    ]

    for future in as_completed(futures):
        result = future.result()
        if result is not None:
            results.append(result)

if results:
    report = pd.DataFrame(results)
    report = report.sort_values(
        "التغير اليومي %",
        ascending=False
    ).reset_index(drop=True)

    print("📊 نتائج الأسهم التي توفرت بياناتها:")
    display(report)

    print("\n📈 أعلى الأسهم تغيرًا في العينة:")
    display(report.head(5))

    print("\n📉 أقل الأسهم تغيرًا في العينة:")
    display(report.tail(5))

    report.to_csv(
        "alwadq_saudi_market_scan.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("\nتم حفظ النتائج في ملف CSV داخل جلسة Colab.")
else:
    print("لم تتوفر بيانات كافية.")
    print("تحققي من الاتصال بالإنترنت أو توافر الرموز في مصدر البيانات.")

print("\nتنبيه: النتائج تعتمد على البيانات المتاحة، وقد تكون متأخرة.")
print("هذا ماسح تعليمي وليس توصية استثمارية.")

🇸🇦 الوَدْق AI — الماسح الموسّع
وقت التشغيل: 2026-10-10 22:29
============================================================

عدد الأسهم في القائمة الحالية: 12
ملاحظة: القائمة الاحتياطية ليست جميع الشركات المدرجة.

بدء فحص بيانات الأسعار...

📊 نتائج الأسهم التي توفرت بياناتها:

,الشركة,الرمز,السعر,التغير اليومي %,RSI,الاتجاه الفني,تاريخ آخر بيانات
0,أرامكو,2222.SR,25.74,-0.39,49.64,اتجاه مختلط,2026-10-08
1,الاتصالات السعودية,7010.SR,42.60,-0.93,36.39,اتجاه سلبي وفق المتوسطات,2026-10-08
2,معادن,1211.SR,62.40,-0.95,46.15,اتجاه سلبي وفق المتوسطات,2026-10-08
3,الراجحي,1120.SR,62.30,-1.42,39.15,اتجاه سلبي وفق المتوسطات,2026-10-08
4,الأهلي السعودي,1180.SR,62.30,-1.42,39.15,اتجاه سلبي وفق المتوسطات,2026-10-08
5,سابك,2010.SR,45.80,-1.63,31.42,اتجاه سلبي وفق المتوسطات,2026-10-08
6,المراعي,2280.SR,44.44,-1.86,44.48,اتجاه سلبي وفق المتوسطات,2026-10-08
7,كهرباء السعودية,5110.SR,15.27,-1.93,32.79,اتجاه سلبي وفق المتوسطات,2026-10-08
8,مصرف الإنماء,1150.SR,23.85,-2.09,38.37,اتجاه سلبي وفق المتوسطات,2026-10-08
9,جرير,4190.SR,16.00,-2.32,42.37,اتجاه سلبي وفق المتوسطات,2026-10-08
10,دار الأركان,4300.SR,18.67,-3.11,42.52,اتجاه سلبي وفق المتوسطات,2026-10-08
11,أكوا باور,2082.SR,164.90,-3.62,35.93,اتجاه سلبي وفق المتوسطات,2026-10-08

📈 أعلى الأسهم تغيرًا في العينة:

,الشركة,الرمز,السعر,التغير اليومي %,RSI,الاتجاه الفني,تاريخ آخر بيانات
0,أرامكو,2222.SR,25.74,-0.39,49.64,اتجاه مختلط,2026-10-08
1,الاتصالات السعودية,7010.SR,42.60,-0.93,36.39,اتجاه سلبي وفق المتوسطات,2026-10-08
2,معادن,1211.SR,62.40,-0.95,46.15,اتجاه سلبي وفق المتوسطات,2026-10-08
3,الراجحي,1120.SR,62.30,-1.42,39.15,اتجاه سلبي وفق المتوسطات,2026-10-08
4,الأهلي السعودي,1180.SR,62.30,-1.42,39.15,اتجاه سلبي وفق المتوسطات,2026-10-08

📉 أقل الأسهم تغيرًا في العينة:

,الشركة,الرمز,السعر,التغير اليومي %,RSI,الاتجاه الفني,تاريخ آخر بيانات
7,كهرباء السعودية,5110.SR,15.27,-1.93,32.79,اتجاه سلبي وفق المتوسطات,2026-10-08
8,مصرف الإنماء,1150.SR,23.85,-2.09,38.37,اتجاه سلبي وفق المتوسطات,2026-10-08
9,جرير,4190.SR,16.00,-2.32,42.37,اتجاه سلبي وفق المتوسطات,2026-10-08
10,دار الأركان,4300.SR,18.67,-3.11,42.52,اتجاه سلبي وفق المتوسطات,2026-10-08
11,أكوا باور,2082.SR,164.90,-3.62,35.93,اتجاه سلبي وفق المتوسطات,2026-10-08

تم حفظ النتائج في ملف CSV داخل جلسة Colab.

تنبيه: النتائج تعتمد على البيانات المتاحة، وقد تكون متأخرة.
هذا ماسح تعليمي وليس توصية استثمارية.

In [ ]:
# ==========================================
# الوَدْق AI - تحليل الأسهم السعودية
# ==========================================

!pip -q install yfinance pandas numpy

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime

print("=" * 65)
print("🌧️ الوَدْق AI | محلل الأسهم السعودية")
print("وقت التحليل:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("=" * 65)

# قائمة أولية من الأسهم السعودية
# يمكن توسيعها لاحقاً لتشمل جميع الشركات المدرجة

stocks = {
    "2222.SR": "أرامكو السعودية",
    "1120.SR": "مصرف الراجحي",
    "1180.SR": "البنك الأهلي السعودي",
    "2010.SR": "سابك",
    "2030.SR": "المراعي",
    "2082.SR": "أكوا باور",
    "2280.SR": "المراعي",
    "4190.SR": "جرير",
    "4300.SR": "دار الأركان",
    "4001.SR": "أسواق العثيم",
    "4002.SR": "المواساة",
    "4003.SR": "إكسترا",
    "4004.SR": "دله الصحية",
    "4005.SR": "رعاية",
    "4006.SR": "المستشفى السعودي الألماني",
    "4007.SR": "الحمادي",
    "4008.SR": "ساكو",
    "4013.SR": "درب السعودية",
    "4015.SR": "جمجوم فارما",
    "4017.SR": "فقيه الطبية",
    "4030.SR": "البحري",
    "4031.SR": "الخدمات الأرضية",
    "4050.SR": "ساسكو",
    "4061.SR": "أنعام القابضة",
    "4070.SR": "تهامة",
    "4080.SR": "سناد القابضة",
    "4090.SR": "طيبة",
    "4100.SR": "مكة",
    "4150.SR": "التصنيع",
    "4160.SR": "ثمار",
    "4170.SR": "شمس",
    "4191.SR": "أبو معطي",
    "4200.SR": "الدريس",
    "4210.SR": "الأبحاث والإعلام",
    "4220.SR": "إعمار",
    "4230.SR": "البحر الأحمر",
    "4240.SR": "سينومي ريتيل",
    "4260.SR": "بدجت السعودية",
    "4261.SR": "ذيب",
    "4262.SR": "لومي",
    "4263.SR": "سال",
    "4320.SR": "الأندلس",
    "5110.SR": "كهرباء السعودية",
    "7010.SR": "الاتصالات السعودية",
    "7020.SR": "إس تي سي",
    "7030.SR": "زين السعودية",
    "7200.SR": "أم آي إس",
    "7201.SR": "بحر العرب",
    "7202.SR": "سلوشنز",
    "7203.SR": "علم",
    "7204.SR": "توبي",
    "8010.SR": "التعاونية",
    "8012.SR": "جزيرة تكافل",
    "8020.SR": "ملاذ للتأمين",
    "8030.SR": "ميدغلف",
    "8040.SR": "أليانز السعودي الفرنسي",
    "8050.SR": "سلامة",
    "8060.SR": "ولاء",
    "8070.SR": "الدرع العربي",
    "8100.SR": "سايكو",
    "8120.SR": "اتحاد الخليج الأهلية",
    "8150.SR": "أسيج",
    "8160.SR": "التأمين العربية",
    "8170.SR": "الاتحاد",
    "8180.SR": "الصقر للتأمين",
    "8190.SR": "المتحدة للتأمين",
    "8200.SR": "الإعادة السعودية",
    "8210.SR": "بوبا العربية",
    "8230.SR": "تكافل الراجحي",
    "8240.SR": "أكسا التعاونية",
    "8250.SR": "جي آي جي",
    "8260.SR": "الخليجية العامة",
    "8300.SR": "الوطنية للتأمين"
}

results = []

print("\n⏳ جاري جلب البيانات وتحليل الأسهم...")
print("قد تستغرق العملية عدة دقائق.\n")

for ticker, company in stocks.items():
    try:
        data = yf.download(
            ticker,
            period="6mo",
            interval="1d",
            auto_adjust=True,
            progress=False
        )

        if data.empty or len(data) < 30:
            print("⚠️ لا توجد بيانات كافية:", company)
            continue

        # استخراج أسعار الإغلاق
        close = data["Close"]

        if isinstance(close, pd.DataFrame):
            close = close.iloc[:, 0]

        close = close.dropna()

        if len(close) < 30:
            continue

        # المؤشرات الفنية
        delta = close.diff()

        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.ewm(
            alpha=1/14, min_periods=14, adjust=False
        ).mean()

        avg_loss = loss.ewm(
            alpha=1/14, min_periods=14, adjust=False
        ).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)
        rsi = 100 - (100 / (1 + rs))

        ema12 = close.ewm(span=12, adjust=False).mean()
        ema26 = close.ewm(span=26, adjust=False).mean()

        macd = ema12 - ema26
        signal = macd.ewm(span=9, adjust=False).mean()

        ma20 = close.rolling(20).mean()
        ma50 = close.rolling(50).mean()

        price = float(close.iloc[-1])
        previous = float(close.iloc[-2])

        change_pct = (
            (price - previous) / previous * 100
            if previous else np.nan
        )

        latest_rsi = float(rsi.iloc[-1])
        latest_macd = float(macd.iloc[-1])
        latest_signal = float(signal.iloc[-1])

        latest_ma20 = (
            float(ma20.iloc[-1])
            if pd.notna(ma20.iloc[-1]) else np.nan
        )

        latest_ma50 = (
            float(ma50.iloc[-1])
            if pd.notna(ma50.iloc[-1]) else np.nan
        )

        # تصنيف فني أولي
        if (
            latest_rsi < 30
            and latest_macd > latest_signal
        ):
            assessment = "ارتداد محتمل - تحقق من التأكيد"

        elif (
            latest_rsi > 70
            and latest_macd < latest_signal
        ):
            assessment = "ضعف محتمل بعد ارتفاع"

        elif (
            pd.notna(latest_ma20)
            and pd.notna(latest_ma50)
            and latest_ma20 > latest_ma50
            and latest_macd > latest_signal
        ):
            assessment = "إشارات فنية إيجابية"

        elif (
            pd.notna(latest_ma20)
            and pd.notna(latest_ma50)
            and latest_ma20 < latest_ma50
            and latest_macd < latest_signal
        ):
            assessment = "إشارات فنية سلبية"

        else:
            assessment = "إشارات مختلطة"

        results.append({
            "الشركة": company,
            "الرمز": ticker,
            "السعر": round(price, 2),
            "التغير اليومي %": round(change_pct, 2),
            "RSI": round(latest_rsi, 2),
            "MACD": round(latest_macd, 4),
            "خط الإشارة": round(latest_signal, 4),
            "متوسط 20 يوم": round(latest_ma20, 2)
                if pd.notna(latest_ma20) else np.nan,
            "متوسط 50 يوم": round(latest_ma50, 2)
                if pd.notna(latest_ma50) else np.nan,
            "القراءة الفنية": assessment,
            "آخر تاريخ للبيانات": str(close.index[-1].date())
        })

        print("✅", company)

    except Exception as e:
        print("⚠️ تعذر تحليل", company, "-", str(e)[:100])

# عرض النتائج
if results:
    df = pd.DataFrame(results)

    df = df.sort_values(
        by="التغير اليومي %",
        ascending=False
    ).reset_index(drop=True)

    print("\n" + "=" * 65)
    print("🌧️ نتائج تحليل الوَدْق AI")
    print("=" * 65)

    display(df)

    # حفظ النتائج في ملف CSV
    filename = "alwadq_ai_saudi_stocks.csv"

    df.to_csv(
        filename,
        index=False,
        encoding="utf-8-sig"
    )

    print("\n✅ تم حفظ النتائج في:", filename)
    print("عدد الأسهم التي نجح تحليلها:", len(df))
    print("تنبيه: النتائج تحليل فني تعليمي وليست توصية استثمارية.")

else:
    print("\n❌ لم تُسترجع بيانات.")
    print("تحققي من اتصال الإنترنت وتوفر بيانات الأسهم.")

=================================================================
🌧️ الوَدْق AI | محلل الأسهم السعودية
وقت التحليل: 2026-10-10 22:34
=================================================================

⏳ جاري جلب البيانات وتحليل الأسهم...
قد تستغرق العملية عدة دقائق.

✅ أرامكو السعودية
✅ مصرف الراجحي
✅ البنك الأهلي السعودي
✅ سابك
✅ المراعي
✅ أكوا باور
✅ المراعي
✅ جرير
✅ دار الأركان
✅ أسواق العثيم
✅ المواساة
✅ إكسترا
✅ دله الصحية
✅ رعاية
✅ المستشفى السعودي الألماني
✅ الحمادي
✅ ساكو
✅ درب السعودية
✅ جمجوم فارما
✅ فقيه الطبية
✅ البحري
✅ الخدمات الأرضية
✅ ساسكو
✅ أنعام القابضة
✅ تهامة
✅ سناد القابضة
✅ طيبة
✅ مكة
✅ التصنيع
✅ ثمار
✅ شمس
✅ أبو معطي
✅ الدريس
✅ الأبحاث والإعلام
✅ إعمار
✅ البحر الأحمر
✅ سينومي ريتيل
✅ بدجت السعودية
✅ ذيب
✅ لومي
✅ سال
✅ الأندلس
✅ كهرباء السعودية
✅ الاتصالات السعودية
✅ إس تي سي
✅ زين السعودية
✅ أم آي إس
✅ بحر العرب
✅ سلوشنز
✅ علم
✅ توبي
✅ التعاونية
✅ جزيرة تكافل
✅ ملاذ للتأمين
✅ ميدغلف
✅ أليانز السعودي الفرنسي
✅ سلامة
✅ ولاء
✅ الدرع العربي
✅ سايكو
✅ اتحاد الخليج الأهلية
✅ أسيج
✅ التأمين العربية
✅ الاتحاد
✅ الصقر للتأمين
✅ المتحدة للتأمين
✅ الإعادة السعودية
✅ بوبا العربية
✅ تكافل الراجحي
✅ أكسا التعاونية
✅ جي آي جي
✅ الخليجية العامة
✅ الوطنية للتأمين

=================================================================
🌧️ نتائج تحليل الوَدْق AI
=================================================================

,الشركة,الرمز,السعر,التغير اليومي %,RSI,MACD,خط الإشارة,متوسط 20 يوم,متوسط 50 يوم,القراءة الفنية,آخر تاريخ للبيانات
0,رعاية,4005.SR,108.90,1.59,42.21,-3.4942,-3.2364,111.90,118.53,إشارات فنية سلبية,2026-10-08
1,درب السعودية,4013.SR,228.70,0.26,51.33,-1.1402,-1.5951,227.28,231.73,إشارات مختلطة,2026-10-08
2,التأمين العربية,8160.SR,8.03,0.12,38.18,-0.1292,-0.1290,8.14,8.38,إشارات فنية سلبية,2026-10-08
3,تهامة,4070.SR,19.60,0.05,52.95,-0.0586,-0.0794,19.35,19.44,إشارات مختلطة,2026-10-08
4,المتحدة للتأمين,8190.SR,3.38,0.00,47.40,-0.0052,-0.0039,3.38,3.39,إشارات فنية سلبية,2026-10-08
...,...,...,...,...,...,...,...,...,...,...,...
68,لومي,4262.SR,23.52,-4.39,21.23,-0.8753,-0.8037,25.43,26.84,إشارات فنية سلبية,2026-10-08
69,البحر الأحمر,4230.SR,20.12,-4.64,31.94,-0.7144,-0.6385,21.71,22.79,إشارات فنية سلبية,2026-10-08
70,توبي,7204.SR,4.94,-4.82,16.24,-0.3473,-0.3009,5.68,6.21,إشارات فنية سلبية,2026-10-08
71,بدجت السعودية,4260.SR,25.36,-4.95,16.60,-1.0333,-0.6573,28.80,29.37,إشارات فنية سلبية,2026-10-08
72,إكسترا,4003.SR,53.70,-8.05,17.24,-2.6142,-1.8103,62.66,64.49,إشارات فنية سلبية,2026-10-08

✅ تم حفظ النتائج في: alwadq_ai_saudi_stocks.csv
عدد الأسهم التي نجح تحليلها: 73
تنبيه: النتائج تحليل فني تعليمي وليست توصية استثمارية.

In [ ]:
# ==========================================
# الوَدْق AI - ترتيب الأسهم السعودية
# ==========================================

import pandas as pd
import numpy as np

# التأكد من وجود نتائج التحليل السابقة
if "df" not in globals() or df.empty:
    print("لم يتم العثور على نتائج التحليل السابقة.")
    print("شغّلي خلية تحليل الأسهم أولاً.")
else:
    ranked = df.copy()

    # تحويل الأعمدة الرقمية إلى أرقام
    numeric_cols = [
        "التغير اليومي %",
        "RSI",
        "MACD",
        "خط الإشارة",
        "متوسط 20 يوم",
        "متوسط 50 يوم",
        "السعر"
    ]

    for col in numeric_cols:
        if col in ranked.columns:
            ranked[col] = pd.to_numeric(
                ranked[col], errors="coerce"
            )

    # حساب نقاط فنية مبدئية
    ranked["النقاط الفنية"] = 0

    # الزخم
    ranked.loc[
        ranked["RSI"].between(50, 70),
        "النقاط الفنية"
    ] += 1

    # تقاطع MACD
    ranked.loc[
        ranked["MACD"] > ranked["خط الإشارة"],
        "النقاط الفنية"
    ] += 1

    # السعر فوق المتوسطات
    ranked.loc[
        ranked["السعر"] > ranked["متوسط 20 يوم"],
        "النقاط الفنية"
    ] += 1

    ranked.loc[
        ranked["متوسط 20 يوم"] > ranked["متوسط 50 يوم"],
        "النقاط الفنية"
    ] += 1

    # تصنيف تعليمي أولي
    conditions = [
        ranked["النقاط الفنية"] >= 3,
        ranked["النقاط الفنية"] == 2,
        ranked["النقاط الفنية"] <= 1
    ]

    labels = [
        "إشارات إيجابية للدراسة",
        "إشارات مختلطة",
        "حذر: الإشارات ضعيفة"
    ]

    ranked["التقييم الفني"] = np.select(
        conditions,
        labels,
        default="غير مكتمل"
    )

    # ترتيب الأسهم حسب النقاط الفنية
    ranked = ranked.sort_values(
        by=["النقاط الفنية", "التغير اليومي %"],
        ascending=[False, False]
    ).reset_index(drop=True)

    print("=" * 55)
    print("🌧️ الوَدْق AI - ترتيب الأسهم السعودية")
    print("=" * 55)

    display(
        ranked[
            [
                "الشركة",
                "الرمز",
                "السعر",
                "التغير اليومي %",
                "RSI",
                "النقاط الفنية",
                "التقييم الفني"
            ]
        ]
    )

    # حفظ التقرير
    ranked.to_csv(
        "alwadq_ai_ranked_stocks.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("\nتم حفظ التقرير في:")
    print("alwadq_ai_ranked_stocks.csv")
    print("\nمهم: الترتيب تعليمي، ولا يمثل توصية شراء أو بيع.")

=======================================================
🌧️ الوَدْق AI - ترتيب الأسهم السعودية
=======================================================

,الشركة,الرمز,السعر,التغير اليومي %,RSI,النقاط الفنية,التقييم الفني
0,أم آي إس,7200.SR,302.00,-0.33,54.60,4,إشارات إيجابية للدراسة
1,سال,4263.SR,174.00,-1.14,56.85,4,إشارات إيجابية للدراسة
2,الإعادة السعودية,8200.SR,28.32,-1.32,60.11,4,إشارات إيجابية للدراسة
3,بحر العرب,7201.SR,4.04,-2.65,65.33,4,إشارات إيجابية للدراسة
4,درب السعودية,4013.SR,228.70,0.26,51.33,3,إشارات إيجابية للدراسة
...,...,...,...,...,...,...,...
68,لومي,4262.SR,23.52,-4.39,21.23,0,حذر: الإشارات ضعيفة
69,البحر الأحمر,4230.SR,20.12,-4.64,31.94,0,حذر: الإشارات ضعيفة
70,توبي,7204.SR,4.94,-4.82,16.24,0,حذر: الإشارات ضعيفة
71,بدجت السعودية,4260.SR,25.36,-4.95,16.60,0,حذر: الإشارات ضعيفة
72,إكسترا,4003.SR,53.70,-8.05,17.24,0,حذر: الإشارات ضعيفة

تم حفظ التقرير في:
alwadq_ai_ranked_stocks.csv

مهم: الترتيب تعليمي، ولا يمثل توصية شراء أو بيع.

In [ ]:
# ==========================================
# الوَدْق AI - تحليل الأسواق العالمية والأمريكية
# ==========================================

!pip -q install yfinance pandas numpy

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime

print("=" * 65)
print("🌍 الوَدْق AI - محلل الأسواق العالمية والأمريكية")
print("وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("=" * 65)

# المؤشرات والأسواق والأصول العالمية
markets = {
    "S&P 500 - السوق الأمريكي": "^GSPC",
    "Nasdaq - شركات التكنولوجيا الأمريكية": "^IXIC",
    "Dow Jones - السوق الأمريكي": "^DJI",
    "Russell 2000 - الشركات الأمريكية الصغيرة": "^RUT",
    "FTSE 100 - بريطانيا": "^FTSE",
    "DAX - ألمانيا": "^GDAXI",
    "Nikkei 225 - اليابان": "^N225",
    "Hang Seng - هونغ كونغ": "^HSI",
    "Euro Stoxx 50 - أوروبا": "^STOXX50E",
    "الذهب العالمي": "GC=F",
    "الفضة العالمية": "SI=F",
    "النفط الأمريكي": "CL=F",
    "النفط برنت": "BZ=F",
    "الدولار مقابل الين": "JPY=X",
    "اليورو مقابل الدولار": "EURUSD=X",
    "الدولار الأسترالي مقابل الدولار": "AUDUSD=X",
    "صندوق الأسواق الناشئة": "EEM",
    "صندوق الأسواق العالمية": "VT",
}

results = []

for name, ticker in markets.items():
    try:
        df = yf.download(
            ticker,
            period="6mo",
            interval="1d",
            progress=False,
            auto_adjust=True,
            threads=False
        )

        if df.empty or len(df) < 30:
            print(f"⚠️ لا توجد بيانات كافية: {name}")
            continue

        # التعامل مع اختلاف شكل الأعمدة
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        close = pd.to_numeric(
            df["Close"], errors="coerce"
        ).dropna()

        if len(close) < 30:
            continue

        price = float(close.iloc[-1])
        previous = float(close.iloc[-2])

        change = (
            (price - previous) / previous * 100
            if previous != 0 else np.nan
        )

        ma20 = float(close.rolling(20).mean().iloc[-1])
        ma50 = float(close.rolling(50).mean().iloc[-1])

        # مؤشر القوة النسبية RSI
        delta = close.diff()
        gains = delta.clip(lower=0)
        losses = -delta.clip(upper=0)

        avg_gain = gains.ewm(
            alpha=1/14, min_periods=14, adjust=False
        ).mean()

        avg_loss = losses.ewm(
            alpha=1/14, min_periods=14, adjust=False
        ).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)
        rsi = 100 - (100 / (1 + rs))
        latest_rsi = float(rsi.iloc[-1])

        if pd.isna(latest_rsi):
            latest_rsi = np.nan

        # تحديد الاتجاه
        if price > ma20 and ma20 > ma50:
            trend = "صاعد وفق المتوسطات"
        elif price < ma20 and ma20 < ma50:
            trend = "هابط وفق المتوسطات"
        else:
            trend = "متذبذب أو مختلط"

        # قراءة RSI التعليمية
        if pd.notna(latest_rsi) and latest_rsi >= 70:
            rsi_note = "تشبع شرائي محتمل"
        elif pd.notna(latest_rsi) and latest_rsi <= 30:
            rsi_note = "تشبع بيعي محتمل"
        else:
            rsi_note = "منطقة RSI متوسطة"

        results.append({
            "السوق أو الأصل": name,
            "الرمز": ticker,
            "آخر سعر": round(price, 4),
            "التغير اليومي %": round(change, 2),
            "RSI": round(latest_rsi, 2)
                if pd.notna(latest_rsi) else np.nan,
            "المتوسط 20": round(ma20, 4),
            "المتوسط 50": round(ma50, 4),
            "الاتجاه": trend,
            "قراءة RSI": rsi_note,
            "تاريخ البيانات": str(close.index[-1].date())
        })

    except Exception as e:
        print(f"⚠️ تعذر تحليل {name}: {str(e)[:100]}")

# عرض النتائج
if results:
    report = pd.DataFrame(results)

    report = report.sort_values(
        by="التغير اليومي %",
        ascending=False
    ).reset_index(drop=True)

    print("\n📊 تقرير الأسواق العالمية والأمريكية")
    display(report)

    # حفظ التقرير في ملف CSV
    filename = "alwadq_ai_global_markets.csv"
    report.to_csv(
        filename,
        index=False,
        encoding="utf-8-sig"
    )

    print("\n✅ تم حفظ التقرير في:", filename)
    print("عدد الأسواق والأصول التي جرى تحليلها:", len(report))

    print("\n📈 أكبر 5 ارتفاعات في التغير اليومي:")
    display(
        report.nlargest(5, "التغير اليومي %")[
            ["السوق أو الأصل", "آخر سعر", "التغير اليومي %", "الاتجاه"]
        ]
    )

    print("\n📉 أكبر 5 انخفاضات في التغير اليومي:")
    display(
        report.nsmallest(5, "التغير اليومي %")[
            ["السوق أو الأصل", "آخر سعر", "التغير اليومي %", "الاتجاه"]
        ]
    )

    print(
        "\nتنبيه: هذا تحليل فني تعليمي، وليس توصية شراء أو بيع."
    )
    print(
        "قد تتأخر البيانات أو تختلف أوقات تحديث الأسواق."
    )

else:
    print(
        "❌ لم تُسترجع بيانات. تحققي من اتصال الإنترنت "
        "ثم أعيدي تشغيل الخلية."
    )

=================================================================
🌍 الوَدْق AI - محلل الأسواق العالمية والأمريكية
وقت الفحص: 2026-10-10 22:42
=================================================================

📊 تقرير الأسواق العالمية والأمريكية

,السوق أو الأصل,الرمز,آخر سعر,التغير اليومي %,RSI,المتوسط 20,المتوسط 50,الاتجاه,قراءة RSI,تاريخ البيانات
0,الفضة العالمية,SI=F,60.6700,2.72,43.01,62.5631,64.1055,هابط وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
1,Hang Seng - هونغ كونغ,^HSI,24211.3496,1.79,42.28,24544.7648,25145.8238,هابط وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
2,الذهب العالمي,GC=F,4216.2998,1.43,43.52,4267.6000,4376.9720,هابط وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
3,DAX - ألمانيا,^GDAXI,25087.2695,1.13,43.40,25324.3320,25799.4805,هابط وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
4,صندوق الأسواق الناشئة,EEM,66.8000,1.06,47.73,67.2710,66.8722,متذبذب أو مختلط,منطقة RSI متوسطة,2026-10-09
5,FTSE 100 - بريطانيا,^FTSE,10552.0996,1.06,45.11,10617.8499,10728.9139,هابط وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
6,Dow Jones - السوق الأمريكي,^DJI,51654.9492,0.83,47.96,51536.8121,52633.5348,متذبذب أو مختلط,منطقة RSI متوسطة,2026-10-09
7,Euro Stoxx 50 - أوروبا,^STOXX50E,6173.3701,0.76,40.86,6256.9905,6370.4808,هابط وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
8,صندوق الأسواق العالمية,VT,159.8300,0.69,52.31,159.0953,159.6682,متذبذب أو مختلط,منطقة RSI متوسطة,2026-10-09
9,Nasdaq - شركات التكنولوجيا الأمريكية,^IXIC,27366.1699,0.64,60.26,26905.7243,26562.9795,صاعد وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
10,S&P 500 - السوق الأمريكي,^GSPC,7811.5400,0.59,59.93,7704.7740,7696.9186,صاعد وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
11,Russell 2000 - الشركات الأمريكية الصغيرة,^RUT,2806.9800,0.46,38.23,2838.3700,2931.0102,هابط وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
12,النفط برنت,BZ=F,104.7200,0.42,58.11,103.4300,96.0352,صاعد وفق المتوسطات,منطقة RSI متوسطة,2026-10-09
13,الدولار الأسترالي مقابل الدولار,AUDUSD=X,0.6988,0.41,40.90,0.7028,0.7088,هابط وفق المتوسطات,منطقة RSI متوسطة,2026-10-10
14,النفط الأمريكي,CL=F,91.8500,0.39,50.12,94.4140,89.2014,متذبذب أو مختلط,منطقة RSI متوسطة,2026-10-09
15,الدولار مقابل الين,JPY=X,158.2460,0.12,55.50,157.1093,157.6682,متذبذب أو مختلط,منطقة RSI متوسطة,2026-10-09
16,اليورو مقابل الدولار,EURUSD=X,1.1206,0.04,22.16,1.1379,1.1510,هابط وفق المتوسطات,تشبع بيعي محتمل,2026-10-09
17,Nikkei 225 - اليابان,^N225,69030.9219,-0.02,59.81,66523.8457,65990.1451,صاعد وفق المتوسطات,منطقة RSI متوسطة,2026-10-09

✅ تم حفظ التقرير في: alwadq_ai_global_markets.csv
عدد الأسواق والأصول التي جرى تحليلها: 18

📈 أكبر 5 ارتفاعات في التغير اليومي:

          السوق أو الأصل     آخر سعر  التغير اليومي %             الاتجاه
0         الفضة العالمية     60.6700             2.72  هابط وفق المتوسطات
1  Hang Seng - هونغ كونغ  24211.3496             1.79  هابط وفق المتوسطات
2          الذهب العالمي   4216.2998             1.43  هابط وفق المتوسطات
3          DAX - ألمانيا  25087.2695             1.13  هابط وفق المتوسطات
4  صندوق الأسواق الناشئة     66.8000             1.06     متذبذب أو مختلط

📉 أكبر 5 انخفاضات في التغير اليومي:

,السوق أو الأصل,آخر سعر,التغير اليومي %,الاتجاه
17,Nikkei 225 - اليابان,69030.9219,-0.02,صاعد وفق المتوسطات
16,اليورو مقابل الدولار,1.1206,0.04,هابط وفق المتوسطات
15,الدولار مقابل الين,158.2460,0.12,متذبذب أو مختلط
14,النفط الأمريكي,91.8500,0.39,متذبذب أو مختلط
13,الدولار الأسترالي مقابل الدولار,0.6988,0.41,هابط وفق المتوسطات

تنبيه: هذا تحليل فني تعليمي، وليس توصية شراء أو بيع.
قد تتأخر البيانات أو تختلف أوقات تحديث الأسواق.

In [ ]:
# ==========================================
# الوَدْق AI - تحليل أولي للأخبار الاقتصادية
# ==========================================

import pandas as pd
import os

filename = "alwadq_ai_economic_news.csv"

if os.path.exists(filename):
    news_df = pd.read_csv(filename)
elif "news_df" in globals():
    news_df = news_df.copy()
else:
    raise FileNotFoundError(
        "لم أجد ملف الأخبار. شغّلي كود جمع الأخبار أولاً."
    )

# كلمات مفتاحية للتصنيف الأولي
positive_words = [
    "rally", "surge", "rises", "rise", "gain",
    "growth", "record high", "beats expectations",
    "ارتفع", "ارتفاع", "نمو", "مكاسب", "صعود"
]

negative_words = [
    "fall", "falls", "drop", "drops", "crash",
    "decline", "loss", "recession", "selloff",
    "انخفاض", "هبوط", "تراجع", "خسائر", "ركود"
]

def classify_news(title):
    title = str(title).lower()

    positive = sum(word in title for word in positive_words)
    negative = sum(word in title for word in negative_words)

    if positive > negative:
        return "🟢 كلمات إيجابية"
    elif negative > positive:
        return "🔴 كلمات سلبية"
    else:
        return "🟡 محايد أو يحتاج إلى تحليل"

news_df["التصنيف الأولي"] = news_df["عنوان الخبر"].apply(
    classify_news
)

print("🌧️ الوَدْق AI - التقرير الأولي لتحليل الأخبار")
print("=" * 55)

display(
    news_df[
        ["التصنيف", "عنوان الخبر", "التصنيف الأولي", "الرابط"]
    ]
)

news_df.to_csv(
    "alwadq_ai_news_analysis.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\n✅ تم حفظ التقرير في alwadq_ai_news_analysis.csv")
print("⚠️ التصنيف يعتمد على كلمات العنوان فقط، وليس فهمًا كاملًا للخبر.")
print("⚠️ التصنيف لا يمثل توصية بالشراء أو البيع.")

🌧️ الوَدْق AI - التقرير الأولي لتحليل الأخبار
=======================================================

,التصنيف,عنوان الخبر,التصنيف الأولي,الرابط
0,أخبار الاقتصاد العالمي,Global growth remains solid in a challenging e...,🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMipAFBV...
1,أخبار الاقتصاد العالمي,"World economic growth to slow to 2.6% in 2026,...",🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMijwFBV...
2,أخبار الاقتصاد العالمي,What’s happening this week in economics? - Del...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMiowFBV...
3,أخبار الاقتصاد العالمي,The global economy has been resilient — so far...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMimAFBV...
4,أخبار الاقتصاد العالمي,The remarkable resilience of the global econom...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMihAFBV...
5,أخبار الأسهم الأمريكية,Dow rises 400 points on Friday as Wall Street ...,🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMid0FVX...
6,أخبار الأسهم الأمريكية,Trump purchased up to $5 million of SpaceX bon...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMigwFBV...
7,أخبار الأسهم الأمريكية,"Wall Street posts weekly gains with earnings, ...",🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMiugFBV...
8,أخبار الأسهم الأمريكية,"Stock market today: Dow, S&P 500, Nasdaq rally...",🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMiqwFBV...
9,أخبار الأسهم الأمريكية,"Stock Market News, Oct. 9, 2026: Dow, S&P 500 ...",🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMixAFBV...
10,أخبار السوق السعودي,Bloomberg: Nournet Considers IPO on Saudi Stoc...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMia0FVX...
11,أخبار السوق السعودي,Saudi Stocks Plunge and Fears of a Shortage of...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMiW0FVX...
12,أخبار السوق السعودي,تاسي يتراجع إلى 10480 نقطة رغم اتساع المكاسب -...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMiVEFVX...
13,أخبار السوق السعودي,Bank for International Settlements: Saudi Stoc...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMibEFVX...
14,أخبار السوق السعودي,مجموعة فقيه للرعاية الصحية تفوز بجائزة «برنامج...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMiUkFVX...
15,أخبار الذهب,Wall Street nears bullish majority after gold’...,🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMivAFBV...
16,أخبار الذهب,Gold snaps two-week losing streak; some analys...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMisAFBV...
17,أخبار الذهب,"Gold ticks up as investors weigh Fed path, mou...",🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMimAFBV...
18,أخبار الذهب,"Current price of gold as of October 9, 2026 - ...",🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMibkFVX...
19,أخبار الذهب,"Gold buying picks up after price correction, b...",🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMimgJBV...
20,أخبار النفط,Morgan Stanley Lowers Oil Price Forecasts Afte...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMipgFBV...
21,أخبار النفط,Crude oil prices and refinery margins generall...,🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMiY0FVX...
22,أخبار النفط,Oil prices jump as Iran steps up tanker attack...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMiekFVX...
23,أخبار النفط,Oil prices settle higher as more production sh...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMirAFBV...
24,أخبار النفط,Oil Prices Steady After Trump Appears to Rule ...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMixwFBV...
25,أخبار أسعار الفائدة,The Fed was unanimous about raising rates in S...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMi6gFBV...
26,أخبار أسعار الفائدة,U.S. Interest Rates Could Rise Over Next Six t...,🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMiwwFBV...
27,أخبار أسعار الفائدة,A Top Fed Official Casts Further Doubt on a Ra...,🟢 كلمات إيجابية,https://news.google.com/rss/articles/CBMikwFBV...
28,أخبار أسعار الفائدة,"Fed officials see another hike coming, but no ...",🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMirwFBV...
29,أخبار أسعار الفائدة,Fed Interest Rate Forecast for the Next 5 Year...,🟡 محايد أو يحتاج إلى تحليل,https://news.google.com/rss/articles/CBMioAFBV...

✅ تم حفظ التقرير في alwadq_ai_news_analysis.csv
⚠️ التصنيف يعتمد على كلمات العنوان فقط، وليس فهمًا كاملًا للخبر.
⚠️ التصنيف لا يمثل توصية بالشراء أو البيع.

In [ ]:
# ==========================================
# الوَدْق AI - المحلل الفني للأسواق العالمية
# ==========================================

%pip -q install yfinance pandas numpy

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime

# الأسواق والأسهم المراد تحليلها
assets = {
    "مؤشر السوق السعودي": "^TASI.SR",
    "أرامكو": "2222.SR",
    "مصرف الراجحي": "1120.SR",
    "سابك": "2010.SR",
    "الأهلي السعودي": "1180.SR",
    "STC": "7010.SR",
    "S&P 500": "^GSPC",
    "ناسداك": "^IXIC",
    "داو جونز": "^DJI",
    "الذهب": "GC=F",
    "النفط": "CL=F",
    "الفضة": "SI=F"
}

results = []

def get_close(data, ticker):
    if data.empty:
        return None

    if isinstance(data.columns, pd.MultiIndex):
        if ("Close", ticker) in data.columns:
            return data[("Close", ticker)].dropna()

        if (ticker, "Close") in data.columns:
            return data[(ticker, "Close")].dropna()

        return None

    if "Close" in data.columns:
        return data["Close"].dropna()

    return None


print("الوَدْق AI - بدء تحليل الأسواق")
print("وقت التحليل:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("-" * 65)

for name, ticker in assets.items():

    try:
        data = yf.download(
            ticker,
            period="6mo",
            interval="1d",
            auto_adjust=True,
            progress=False
        )

        close = get_close(data, ticker)

        if close is None or len(close) < 30:
            print(f"لا توجد بيانات كافية: {name} ({ticker})")
            continue

        close = close.astype(float)

        ma20 = close.rolling(20).mean()
        ma50 = close.rolling(50).mean()

        delta = close.diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.rolling(14).mean()
        avg_loss = loss.rolling(14).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)
        rsi = 100 - (100 / (1 + rs))

        ema12 = close.ewm(span=12, adjust=False).mean()
        ema26 = close.ewm(span=26, adjust=False).mean()

        macd = ema12 - ema26
        signal_line = macd.ewm(span=9, adjust=False).mean()

        price = float(close.iloc[-1])
        previous = float(close.iloc[-2])
        change = ((price / previous) - 1) * 100

        latest_rsi = float(rsi.iloc[-1])
        latest_macd = float(macd.iloc[-1])
        latest_signal = float(signal_line.iloc[-1])
        latest_ma20 = float(ma20.iloc[-1])
        latest_ma50 = float(ma50.iloc[-1])

        # تصنيف تعليمي أولي وليس توصية استثمارية
        if (
            price > latest_ma20 > latest_ma50
            and latest_macd > latest_signal
            and 50 < latest_rsi < 70
        ):
            trend = "إيجابي وفق الشروط"

        elif (
            price < latest_ma20 < latest_ma50
            and latest_macd < latest_signal
        ):
            trend = "سلبي وفق الشروط"

        else:
            trend = "محايد أو إشارات متضاربة"

        results.append({
            "الأصل": name,
            "الرمز": ticker,
            "آخر سعر": round(price, 3),
            "التغير اليومي %": round(change, 2),
            "RSI": round(latest_rsi, 2),
            "MACD": round(latest_macd, 3),
            "خط الإشارة": round(latest_signal, 3),
            "المتوسط 20": round(latest_ma20, 3),
            "المتوسط 50": round(latest_ma50, 3),
            "القراءة الفنية": trend,
            "تاريخ البيانات": str(close.index[-1].date())
        })

    except Exception as e:
        print(f"تعذر تحليل {name}: {str(e)[:100]}")

if results:
    report = pd.DataFrame(results)

    print("\nنتائج التحليل الفني:")
    display(report)

    report.to_csv(
        "alwadaq_ai_market_analysis.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("\nتم حفظ التقرير بنجاح.")
    print("اسم الملف: alwadaq_ai_market_analysis.csv")

else:
    print("لم نحصل على بيانات كافية.")
    print("تحققي من اتصال الإنترنت وتوافر بيانات Yahoo Finance.")

الوَدْق AI - بدء تحليل الأسواق
وقت التحليل: 2026-10-10 23:03
-----------------------------------------------------------------
لا توجد بيانات كافية: مؤشر السوق السعودي (^TASI.SR)

نتائج التحليل الفني:

,الأصل,الرمز,آخر سعر,التغير اليومي %,RSI,MACD,خط الإشارة,المتوسط 20,المتوسط 50,القراءة الفنية,تاريخ البيانات
0,أرامكو,2222.SR,25.740,-0.39,54.13,-0.096,-0.144,25.634,25.985,محايد أو إشارات متضاربة,2026-10-08
1,مصرف الراجحي,1120.SR,62.300,-1.42,37.06,-0.457,-0.301,63.994,64.223,سلبي وفق الشروط,2026-10-08
2,سابك,2010.SR,45.800,-1.63,32.37,-0.835,-0.790,47.406,48.791,سلبي وفق الشروط,2026-10-08
3,الأهلي السعودي,1180.SR,37.860,-3.12,32.94,-0.704,-0.486,40.040,41.026,سلبي وفق الشروط,2026-10-08
4,STC,7010.SR,42.600,-0.93,29.69,-0.263,-0.208,43.284,43.606,سلبي وفق الشروط,2026-10-08
5,S&P 500,^GSPC,7811.540,0.59,55.10,34.457,23.320,7704.774,7696.919,إيجابي وفق الشروط,2026-10-09
6,ناسداك,^IXIC,27366.170,0.64,55.51,276.930,242.963,26905.724,26562.979,إيجابي وفق الشروط,2026-10-09
7,داو جونز,^DJI,51654.949,0.83,44.42,-347.055,-401.884,51536.812,52633.535,محايد أو إشارات متضاربة,2026-10-09
8,الذهب,GC=F,4216.300,1.43,33.02,-64.386,-58.021,4267.600,4376.972,سلبي وفق الشروط,2026-10-09
9,النفط,CL=F,91.850,0.39,41.58,-0.281,0.453,94.414,89.201,محايد أو إشارات متضاربة,2026-10-09
10,الفضة,SI=F,60.670,2.72,31.31,-1.334,-1.050,62.563,64.106,سلبي وفق الشروط,2026-10-09

تم حفظ التقرير بنجاح.
اسم الملف: alwadaq_ai_market_analysis.csv

In [ ]:
from datetime import datetime

print("🌧️ مرحبًا بك في الوَدْق AI")
print("=" * 45)
print("نظام تحليل الأسواق والأخبار العالمية")
print("تاريخ التشغيل:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("=" * 45)

markets = [
    "المؤشرات الأمريكية",
    "الذهب والفضة",
    "النفط",
    "الدولار الأمريكي",
    "السوق السعودي",
    "الأخبار الاقتصادية العالمية"
]

print("\nالأسواق التي سنعمل على تحليلها:")

for market in markets:
    print("•", market)

print("\nالمرحلة الأولى جاهزة!")
print("الخطوة التالية: ربط مصادر الأخبار والبيانات.")

🌧️ مرحبًا بك في الوَدْق AI
=============================================
نظام تحليل الأسواق والأخبار العالمية
تاريخ التشغيل: 2026-10-10 21:59
=============================================

الأسواق التي سنعمل على تحليلها:
• المؤشرات الأمريكية
• الذهب والفضة
• النفط
• الدولار الأمريكي
• السوق السعودي
• الأخبار الاقتصادية العالمية

المرحلة الأولى جاهزة!
الخطوة التالية: ربط مصادر الأخبار والبيانات.

In [ ]:
# ==========================================
# الوَدْق AI - محلل الأخبار وتأثيرها على الأسواق
# المرحلة الثالثة
# ==========================================

import feedparser
import pandas as pd
from datetime import datetime

feeds = {
    "السوق السعودي":
        "https://news.google.com/rss/search?q=Saudi+stock+market+OR+Tadawul&hl=en&gl=SA&ceid=SA:en",

    "السوق الأمريكي":
        "https://news.google.com/rss/search?q=US+stock+market+OR+Nasdaq+OR+S%26P500&hl=en-US&gl=US&ceid=US:en",

    "السوق العالمي":
        "https://news.google.com/rss/search?q=global+stock+markets+OR+world+economy&hl=en-US&gl=US&ceid=US:en",

    "الذهب":
        "https://news.google.com/rss/search?q=gold+prices+OR+gold+market&hl=en-US&gl=US&ceid=US:en",

    "النفط":
        "https://news.google.com/rss/search?q=oil+prices+OR+crude+oil&hl=en-US&gl=US&ceid=US:en",

    "الفائدة والتضخم":
        "https://news.google.com/rss/search?q=Federal+Reserve+OR+interest+rates+OR+inflation&hl=en-US&gl=US&ceid=US:en"
}

# كلمات مفتاحية للتصنيف الأولي
positive_words = [
    "rises", "rally", "surge", "gains", "growth",
    "record high", "beats expectations", "upgrade",
    "bullish", "recovery", "profits rise",
    "يرتفع", "ارتفاع", "نمو", "أرباح", "انتعاش"
]

negative_words = [
    "falls", "drops", "plunges", "crash", "decline",
    "losses", "sell-off", "bearish", "downgrade",
    "recession", "war", "crisis", "misses expectations",
    "ينخفض", "هبوط", "خسائر", "أزمة", "تراجع"
]

def classify_news(title):
    text = title.lower()

    positive_score = sum(
        word in text for word in positive_words
    )

    negative_score = sum(
        word in text for word in negative_words
    )

    if positive_score > negative_score:
        return "إيجابي مبدئيًا"

    elif negative_score > positive_score:
        return "سلبي مبدئيًا"

    return "محايد أو يحتاج إلى تحليل"

# جمع الأخبار
rows = []

print("الوَدْق AI - بدء تحليل الأخبار")
print("وقت التشغيل:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("-" * 60)

for market, url in feeds.items():

    try:
        news = feedparser.parse(url)

        for item in news.entries[:10]:

            title = item.get("title", "")

            rows.append({
                "السوق": market,
                "عنوان الخبر": title,
                "التصنيف الأولي": classify_news(title),
                "تاريخ النشر": item.get("published", ""),
                "الرابط": item.get("link", "")
            })

        print(f"تم فحص مصدر: {market}")

    except Exception as error:
        print(f"تعذر جلب أخبار {market}: {error}")

# عرض النتائج وحفظها
news_analysis = pd.DataFrame(rows)

if not news_analysis.empty:

    print("\nنتائج تحليل الأخبار:")
    display(news_analysis)

    news_analysis.to_csv(
        "alwadaq_ai_news_sentiment.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("\nتم حفظ التقرير بنجاح.")
    print("اسم الملف: alwadaq_ai_news_sentiment.csv")

    print("\nملخص التصنيفات:")
    display(
        news_analysis["التصنيف الأولي"]
        .value_counts()
        .rename_axis("التصنيف")
        .reset_index(name="عدد الأخبار")
    )

else:
    print("لم تصل أخبار. تحققي من اتصال الإنترنت.")

الوَدْق AI - بدء تحليل الأخبار
وقت التشغيل: 2026-10-10 23:06
------------------------------------------------------------
تم فحص مصدر: السوق السعودي
تم فحص مصدر: السوق الأمريكي
تم فحص مصدر: السوق العالمي
تم فحص مصدر: الذهب
تم فحص مصدر: النفط
تم فحص مصدر: الفائدة والتضخم

نتائج تحليل الأخبار:

,السوق,عنوان الخبر,التصنيف الأولي,تاريخ النشر,الرابط
0,السوق السعودي,Oil prices fall as IEA members agree to priori...,محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 02:09:00 GMT",https://news.google.com/rss/articles/CBMiekFVX...
1,السوق السعودي,Saudi Arabia's market regulator proposes tight...,محايد أو يحتاج إلى تحليل,"Thu, 24 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMi0gFBV...
2,السوق السعودي,Saudi Arabia stocks lower at close of trade; T...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 13:30:50 GMT",https://news.google.com/rss/articles/CBMixgFBV...
3,السوق السعودي,Saudi stock market in the week ahead - ارقام,محايد أو يحتاج إلى تحليل,"Sat, 10 Oct 2026 11:33:47 GMT",https://news.google.com/rss/articles/CBMiakFVX...
4,السوق السعودي,"Saudi stocks hit wartime low as Aramco slides,...",سلبي مبدئيًا,"Tue, 29 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMisgFBV...
5,السوق السعودي,Saudis Deepen Capital Market Reforms With Deri...,محايد أو يحتاج إلى تحليل,"Wed, 26 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiswFBV...
6,السوق السعودي,View / More IPOs won’t be enough to fix the Sa...,محايد أو يحتاج إلى تحليل,"Mon, 28 Sep 2026 11:40:00 GMT",https://news.google.com/rss/articles/CBMilgFBV...
7,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 12:48:54 GMT",https://news.google.com/rss/articles/CBMib0FVX...
8,السوق السعودي,Saudi Arabia Rethinks IPO Rules as Investor Ap...,محايد أو يحتاج إلى تحليل,"Wed, 30 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMixAFBV...
9,السوق السعودي,Closing Bell: Saudi Arabia’s main index edges ...,محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 14:02:04 GMT",https://news.google.com/rss/articles/CBMirgFBV...
10,السوق الأمريكي,"Stock Market Today: S&P 500, Dow Jones, Nasdaq...",محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 13:21:00 GMT",https://news.google.com/rss/articles/CBMilwJBV...
11,السوق الأمريكي,"Stock Market Today: S&P 500, Dow Jones, Nasdaq...",سلبي مبدئيًا,"Thu, 08 Oct 2026 12:36:00 GMT",https://news.google.com/rss/articles/CBMimgJBV...
12,السوق الأمريكي,"S&P 500, Nasdaq reach record closing highs as ...",محايد أو يحتاج إلى تحليل,"Tue, 06 Oct 2026 10:27:00 GMT",https://news.google.com/rss/articles/CBMihwFBV...
13,السوق الأمريكي,S&P 500 and Nasdaq surge to record highs after...,إيجابي مبدئيًا,"Tue, 06 Oct 2026 20:38:00 GMT",https://news.google.com/rss/articles/CBMiiwFBV...
14,السوق الأمريكي,AI-centered US stock bull market nears four-ye...,محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 10:02:00 GMT",https://news.google.com/rss/articles/CBMitwFBV...
15,السوق الأمريكي,US stock market finishes out week on a high no...,محايد أو يحتاج إلى تحليل,"Sat, 10 Oct 2026 06:47:00 GMT",https://news.google.com/rss/articles/CBMingFBV...
16,السوق الأمريكي,US stock market hits all-time high as investor...,محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 06:34:37 GMT",https://news.google.com/rss/articles/CBMiqAFBV...
17,السوق الأمريكي,"U.S. Stocks Mixed as Oil Spikes, AI Profit Dou...",محايد أو يحتاج إلى تحليل,"Sat, 10 Oct 2026 15:39:17 GMT",https://news.google.com/rss/articles/CBMiogFBV...
18,السوق الأمريكي,"US stocks hit record high, shrugging off bond ...",إيجابي مبدئيًا,"Tue, 06 Oct 2026 14:25:46 GMT",https://news.google.com/rss/articles/CBMiZ0FVX...
19,السوق الأمريكي,The 10 Best and 10 Worst Months of All Time fo...,محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 11:05:05 GMT",https://news.google.com/rss/articles/CBMiiwFBV...
20,السوق العالمي,Are global stock markets heading for a crash? ...,سلبي مبدئيًا,"Sun, 20 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiqAFBV...
21,السوق العالمي,Five reasons India's stock market is sinking e...,محايد أو يحتاج إلى تحليل,"Mon, 05 Oct 2026 23:13:11 GMT",https://news.google.com/rss/articles/CBMiW0FVX...
22,السوق العالمي,The Best and Worst European Stock Markets in 2...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 05:13:17 GMT",https://news.google.com/rss/articles/CBMiigFBV...
23,السوق العالمي,FCA speech – Reforming UK capital markets to e...,محايد أو يحتاج إلى تحليل,"Mon, 05 Oct 2026 14:18:46 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
24,السوق العالمي,Global markets mixed amid AI profitability con...,محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 10:47:23 GMT",https://news.google.com/rss/articles/CBMiswFBV...
25,السوق العالمي,Global stocks head for best week since May; US...,محايد أو يحتاج إلى تحليل,"Fri, 03 Jul 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMie0FVX...
26,السوق العالمي,The global economy has been resilient — so far...,محايد أو يحتاج إلى تحليل,"Mon, 28 Sep 2026 12:44:57 GMT",https://news.google.com/rss/articles/CBMimAFBV...
27,السوق العالمي,"'AI boom' insulates global growth from shocks,...",إيجابي مبدئيًا,"Thu, 16 Jul 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMivAFBV...
28,السوق العالمي,"The world is crazy, but stocks are up? - Axios",محايد أو يحتاج إلى تحليل,"Thu, 23 Jul 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMic0FVX...
29,السوق العالمي,Global stocks mixed as markets weigh higher oi...,محايد أو يحتاج إلى تحليل,"Wed, 30 Sep 2026 21:24:20 GMT",https://news.google.com/rss/articles/CBMijwFBV...
30,الذهب,"Gold price holds critical $4,100 support, but ...",محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 23:15:00 GMT",https://news.google.com/rss/articles/CBMiugFBV...
31,الذهب,"Gold prices drop over 2%, slide to 2-month low...",محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 18:29:53 GMT",https://news.google.com/rss/articles/CBMi4wFBV...
32,الذهب,Why gold and silver prices have added $5 trill...,محايد أو يحتاج إلى تحليل,"Mon, 24 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMixAFBV...
33,الذهب,"Gold rebounds as bond jitters, debt fears and ...",محايد أو يحتاج إلى تحليل,"Fri, 21 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMicEFVX...
34,الذهب,"Natixis raises gold price target to $5,000 as ...",محايد أو يحتاج إلى تحليل,"Tue, 25 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiuwFBV...
35,الذهب,"Gold prices today, Monday, August 24, 2026: 'G...",محايد أو يحتاج إلى تحليل,"Mon, 24 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMi8wFBV...
36,الذهب,"Gold prices today, Tuesday, August 25, 2026: G...",محايد أو يحتاج إلى تحليل,"Tue, 25 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMi5wFBV...
37,الذهب,"Gold ticks up as investors weigh Fed path, mou...",محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 10:31:04 GMT",https://news.google.com/rss/articles/CBMimAFBV...
38,الذهب,Gold Market Commentary: Go with the flow - Wor...,محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 12:00:00 GMT",https://news.google.com/rss/articles/CBMigAFBV...
39,الذهب,"Current price of gold as of October 9, 2026 - ...",محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 13:03:00 GMT",https://news.google.com/rss/articles/CBMibkFVX...
40,النفط,"Oil rises 4% on revived Middle East worries, H...",إيجابي مبدئيًا,"Thu, 08 Oct 2026 01:30:25 GMT",https://news.google.com/rss/articles/CBMiuwFBV...
41,النفط,Oil Prices Steady After Trump Appears to Rule ...,محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 19:33:00 GMT",https://news.google.com/rss/articles/CBMixwFBV...
42,النفط,"Current price of oil as of October 8, 2026 - F...",محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 11:00:00 GMT",https://news.google.com/rss/articles/CBMiYkFVX...
43,النفط,"Current price of oil as of Oct. 9, 2026 - Fortune",محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 11:00:00 GMT",https://news.google.com/rss/articles/CBMiYkFVX...
44,النفط,Why are gas prices still high even as traffic ...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 18:33:49 GMT",https://news.google.com/rss/articles/CBMimgFBV...
45,النفط,"Crude Oil is Underpriced, Energy Aspects Says ...",محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 12:30:00 GMT",https://news.google.com/rss/articles/CBMiogFBV...
46,النفط,Stocks Push Higher as Crude Oil Prices Ease - ...,محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 14:01:27 GMT",https://news.google.com/rss/articles/CBMikAFBV...
47,النفط,World's Top Crude Trader Isn't Ruling Out $200...,محايد أو يحتاج إلى تحليل,"Fri, 09 Oct 2026 00:00:00 GMT",https://news.google.com/rss/articles/CBMiogFBV...
48,النفط,Oil and gas prices jump on Middle East shippin...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 06:51:00 GMT",https://news.google.com/rss/articles/CBMi4AFBV...
49,النفط,Stocks Pressured by Soaring Crude Oil Prices -...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 15:17:34 GMT",https://news.google.com/rss/articles/CBMikgFBV...
50,الفائدة والتضخم,A Top Fed Official Casts Further Doubt on a Ra...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 08:38:57 GMT",https://news.google.com/rss/articles/CBMikwFBV...
51,الفائدة والتضخم,Federal Reserve officials expect another rate ...,محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 18:37:29 GMT",https://news.google.com/rss/articles/CBMipgFBV...
52,الفائدة والتضخم,Trump calls for lower interest rates as Fed of...,محايد أو يحتاج إلى تحليل,"Thu, 20 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMitAFBV...
53,الفائدة والتضخم,Federal Reserve hikes key rate for 1st time in...,محايد أو يحتاج إلى تحليل,"Wed, 16 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMingFBV...
54,الفائدة والتضخم,US Federal Reserve raises interest rates for t...,محايد أو يحتاج إلى تحليل,"Wed, 16 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMijAFBV...
55,الفائدة والتضخم,U.S. Interest Rates Could Rise Over Next Six t...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 18:45:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...
56,الفائدة والتضخم,"Fed officials see another hike coming, but no ...",محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 18:00:37 GMT",https://news.google.com/rss/articles/CBMirwFBV...
57,الفائدة والتضخم,"Fed's Waller: More hikes needed, but there is ...",محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 15:33:03 GMT",https://news.google.com/rss/articles/CBMipgFBV...
58,الفائدة والتضخم,Fed officials view another rate hike as ‘likel...,محايد أو يحتاج إلى تحليل,"Wed, 07 Oct 2026 22:18:00 GMT",https://news.google.com/rss/articles/CBMiggFBV...
59,الفائدة والتضخم,How Fast Do Tariffs Pass Through into Consumer...,محايد أو يحتاج إلى تحليل,"Thu, 08 Oct 2026 23:25:40 GMT",https://news.google.com/rss/articles/CBMirAFBV...

تم حفظ التقرير بنجاح.
اسم الملف: alwadaq_ai_news_sentiment.csv

ملخص التصنيفات:

                    التصنيف  عدد الأخبار
0  محايد أو يحتاج إلى تحليل           53
1            إيجابي مبدئيًا            4
2              سلبي مبدئيًا            3

In [ ]:
# ==========================================
# الوَدْق AI - لوحة تحليل الأسواق المتكاملة
# المرحلة الرابعة
# ==========================================

import pandas as pd
from datetime import datetime

print("=" * 55)
print("       الوَدْق AI - لوحة تحليل الأسواق")
print("=" * 55)

print("وقت إعداد التقرير:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print()

# 1- تحليل الأخبار
if "news_analysis" in globals() and not news_analysis.empty:

    print("أولاً: ملخص الأخبار الاقتصادية")

    display(
        news_analysis.groupby(
            ["السوق", "التصنيف الأولي"]
        ).size().reset_index(name="عدد الأخبار")
    )

else:
    print("لم يتم العثور على بيانات الأخبار.")

# 2- تحليل بيانات الأسواق المتاحة
print("\nثانياً: بيانات الأسواق والمؤشرات الفنية")

market_variables = [
    "market_df",
    "stocks_df",
    "df",
    "gold_df"
]

found_market_data = False

for variable in market_variables:

    if variable in globals():

        data = globals()[variable]

        if isinstance(data, pd.DataFrame) and not data.empty:

            print(f"\nتم العثور على البيانات: {variable}")
            print("عدد الصفوف:", len(data))
            display(data.head(5))

            found_market_data = True

if not found_market_data:
    print(
        "لم يتم العثور على أسماء متغيرات بيانات الأسواق المعروفة."
    )
    print(
        "سنربطها في الخطوة التالية بأسمائها الصحيحة من دفتر العمل."
    )

print("\nانتهى إعداد التقرير.")
print("ملاحظة: النتائج للتحليل والتعلم وليست توصية استثمارية.")

=======================================================
       الوَدْق AI - لوحة تحليل الأسواق
=======================================================
وقت إعداد التقرير: 2026-10-10 23:08

أولاً: ملخص الأخبار الاقتصادية

              السوق            التصنيف الأولي  عدد الأخبار
0             الذهب  محايد أو يحتاج إلى تحليل           10
1    السوق الأمريكي            إيجابي مبدئيًا            2
2    السوق الأمريكي              سلبي مبدئيًا            1
3    السوق الأمريكي  محايد أو يحتاج إلى تحليل            7
4     السوق السعودي              سلبي مبدئيًا            1
5     السوق السعودي  محايد أو يحتاج إلى تحليل            9
6     السوق العالمي            إيجابي مبدئيًا            1
7     السوق العالمي              سلبي مبدئيًا            1
8     السوق العالمي  محايد أو يحتاج إلى تحليل            8
9   الفائدة والتضخم  محايد أو يحتاج إلى تحليل           10
10            النفط            إيجابي مبدئيًا            1
11            النفط  محايد أو يحتاج إلى تحليل            9

ثانياً: بيانات الأسواق والمؤشرات الفنية

تم العثور على البيانات: df
عدد الصفوف: 50

,السوق,الخبر,التاريخ,الرابط
0,السوق السعودي,Gulf Stock Markets Lower as Saudi-Houthi Tensi...,"Wed, 07 Oct 2026 17:49:42 GMT",https://news.google.com/rss/articles/CBMigAFBV...
1,السوق السعودي,Saudi stock market in the week ahead - ارقام,"Sat, 10 Oct 2026 11:33:47 GMT",https://news.google.com/rss/articles/CBMiakFVX...
2,السوق السعودي,"Saudi stocks hit wartime low as Aramco slides,...","Tue, 29 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMisgFBV...
3,السوق السعودي,View / More IPOs won’t be enough to fix the Sa...,"Mon, 28 Sep 2026 11:40:00 GMT",https://news.google.com/rss/articles/CBMilgFBV...
4,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,"Thu, 08 Oct 2026 12:48:54 GMT",https://news.google.com/rss/articles/CBMib0FVX...

انتهى إعداد التقرير.
ملاحظة: النتائج للتحليل والتعلم وليست توصية استثمارية.

In [ ]:
%pip install -q feedparser

In [ ]:
import feedparser
import pandas as pd
from datetime import datetime

feeds = {
    "السوق السعودي": "https://news.google.com/rss/search?q=Saudi+stock+market&hl=en&gl=SA&ceid=SA:en",
    "السوق الأمريكي": "https://news.google.com/rss/search?q=US+stock+market+Nasdaq+S%26P500&hl=en-US&gl=US&ceid=US:en",
    "السوق العالمي": "https://news.google.com/rss/search?q=global+stock+markets&hl=en-US&gl=US&ceid=US:en",
    "الذهب": "https://news.google.com/rss/search?q=gold+prices&hl=en-US&gl=US&ceid=US:en",
    "النفط": "https://news.google.com/rss/search?q=oil+prices&hl=en-US&gl=US&ceid=US:en"
}

results = []

for market, url in feeds.items():
    news = feedparser.parse(url)

    for item in news.entries[:10]:
        results.append({
            "السوق": market,
            "الخبر": item.get("title", ""),
            "التاريخ": item.get("published", ""),
            "الرابط": item.get("link", "")
        })

df = pd.DataFrame(results)

if not df.empty:
    display(df)
    df.to_csv(
        "alwadz_ai_global_markets.csv",
        index=False,
        encoding="utf-8-sig"
    )
    print("تم جمع الأخبار وحفظها بنجاح.")
else:
    print("لم تصل الأخبار. تحققي من اتصال الإنترنت.")

,السوق,الخبر,التاريخ,الرابط
0,السوق السعودي,Gulf Stock Markets Lower as Saudi-Houthi Tensi...,"Wed, 07 Oct 2026 17:49:42 GMT",https://news.google.com/rss/articles/CBMigAFBV...
1,السوق السعودي,Saudi stock market in the week ahead - ارقام,"Sat, 10 Oct 2026 11:33:47 GMT",https://news.google.com/rss/articles/CBMiakFVX...
2,السوق السعودي,"Saudi stocks hit wartime low as Aramco slides,...","Tue, 29 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMisgFBV...
3,السوق السعودي,View / More IPOs won’t be enough to fix the Sa...,"Mon, 28 Sep 2026 11:40:00 GMT",https://news.google.com/rss/articles/CBMilgFBV...
4,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,"Thu, 08 Oct 2026 12:48:54 GMT",https://news.google.com/rss/articles/CBMib0FVX...
5,السوق السعودي,Saudis Deepen Capital Market Reforms With Deri...,"Wed, 26 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiswFBV...
6,السوق السعودي,Saudi Arabia Rethinks IPO Rules as Investor Ap...,"Wed, 30 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMixAFBV...
7,السوق السعودي,Houthis claim new attack against airport in Sa...,"Thu, 08 Oct 2026 13:58:11 GMT",https://news.google.com/rss/articles/CBMivwFBV...
8,السوق السعودي,Opening the market: Saudi Arabia's amended for...,"Sun, 01 Feb 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMi2gFBV...
9,السوق السعودي,Closing Bell: Saudi stocks regain ground as TA...,"Mon, 05 Oct 2026 12:47:36 GMT",https://news.google.com/rss/articles/CBMiogFBV...
10,السوق الأمريكي,"Stock Market Today: S&P 500, Dow Jones, Nasdaq...","Fri, 09 Oct 2026 13:21:00 GMT",https://news.google.com/rss/articles/CBMilwJBV...
11,السوق الأمريكي,US Stock Market prediction for Friday: S&P 500...,"Fri, 09 Oct 2026 10:59:46 GMT",https://news.google.com/rss/articles/CBMi2wJBV...
12,السوق الأمريكي,"Stock Market Today: S&P 500, Dow Jones, Nasdaq...","Thu, 08 Oct 2026 12:36:00 GMT",https://news.google.com/rss/articles/CBMimgJBV...
13,السوق الأمريكي,"S&P 500, Nasdaq reach record closing highs as ...","Tue, 06 Oct 2026 10:27:00 GMT",https://news.google.com/rss/articles/CBMihwFBV...
14,السوق الأمريكي,S&P 500 and Nasdaq surge to record highs after...,"Tue, 06 Oct 2026 20:38:00 GMT",https://news.google.com/rss/articles/CBMiiwFBV...
15,السوق الأمريكي,Overnight U.S. Stocks | S&P 500 and Nasdaq Hit...,"Sat, 10 Oct 2026 09:14:52 GMT",https://news.google.com/rss/articles/CBMimAFBV...
16,السوق الأمريكي,U.S. stock market drops: S&P 500 and Nasdaq fa...,"Thu, 08 Oct 2026 15:04:08 GMT",https://news.google.com/rss/articles/CBMi2wFBV...
17,السوق الأمريكي,"Wall Street ends lower, off record highs, as T...","Wed, 07 Oct 2026 23:14:17 GMT",https://news.google.com/rss/articles/CBMipAFBV...
18,السوق الأمريكي,"The S&P 500 Hits a New Record High, Powered by...","Tue, 06 Oct 2026 21:33:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...
19,السوق الأمريكي,"S&P 500, Nasdaq end lower as crude prices jump...","Thu, 08 Oct 2026 23:09:38 GMT",https://news.google.com/rss/articles/CBMinAFBV...
20,السوق العالمي,"Stocks advance ahead of earnings, navigating s...","Fri, 09 Oct 2026 01:56:00 GMT",https://news.google.com/rss/articles/CBMie0FVX...
21,السوق العالمي,Should S&P Global Stock Holders Look At Interc...,"Thu, 08 Oct 2026 17:48:03 GMT",https://news.google.com/rss/articles/CBMilwFBV...
22,السوق العالمي,Are global stock markets heading for a crash? ...,"Sun, 20 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiqAFBV...
23,السوق العالمي,Weekly market commentary - BlackRock,"Sun, 04 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiogFBV...
24,السوق العالمي,Wall Street retreats from record as global sto...,"Thu, 08 Oct 2026 06:49:00 GMT",https://news.google.com/rss/articles/CBMinwFBV...
25,السوق العالمي,The world of one trade — AI - Financial Times,"Sat, 10 Oct 2026 06:36:04 GMT",https://news.google.com/rss/articles/CBMihAFBV...
26,السوق العالمي,"U.S. Stocks Slip, Oil Rises on Fresh Tanker At...","Thu, 08 Oct 2026 18:30:00 GMT",https://news.google.com/rss/articles/CBMirAFBV...
27,السوق العالمي,"The Global Stock Market Boom, by Country (2011...","Wed, 30 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMijgFBV...
28,السوق العالمي,Securitize Launches Global Onchain Trading of ...,"Thu, 08 Oct 2026 14:26:04 GMT",https://news.google.com/rss/articles/CBMijwFBV...
29,السوق العالمي,Global stocks rise as Trump says Russia to rel...,"Sat, 10 Oct 2026 18:00:00 GMT",https://news.google.com/rss/articles/CBMiugFBV...
30,الذهب,Wall Street nears bullish majority after gold’...,"Fri, 09 Oct 2026 18:27:00 GMT",https://news.google.com/rss/articles/CBMivAFBV...
31,الذهب,Gold snaps two-week losing streak; some analys...,"Fri, 09 Oct 2026 21:50:04 GMT",https://news.google.com/rss/articles/CBMisAFBV...
32,الذهب,"Gold ticks up as investors weigh Fed path, mou...","Thu, 08 Oct 2026 10:31:04 GMT",https://news.google.com/rss/articles/CBMimAFBV...
33,الذهب,"Current price of gold as of October 9, 2026 - ...","Fri, 09 Oct 2026 13:03:00 GMT",https://news.google.com/rss/articles/CBMibkFVX...
34,الذهب,"Gold buying picks up after price correction, b...","Sat, 10 Oct 2026 04:59:03 GMT",https://news.google.com/rss/articles/CBMimgJBV...
35,الذهب,Gold Prices Fall as Dollar Strengthens Ahead o...,"Wed, 07 Oct 2026 09:33:56 GMT",https://news.google.com/rss/articles/CBMiqAFBV...
36,الذهب,Gold prices climb - VnExpress International,"Fri, 09 Oct 2026 08:01:17 GMT",https://news.google.com/rss/articles/CBMiggFBV...
37,الذهب,Gold price trades near high after preliminary ...,"Fri, 09 Oct 2026 14:13:55 GMT",https://news.google.com/rss/articles/CBMivAFBV...
38,الذهب,"Gold’s next chapter is about more than $5,000 ...","Fri, 09 Oct 2026 21:06:56 GMT",https://news.google.com/rss/articles/CBMilAFBV...
39,الذهب,Peter Schiff says rising yields are 'the most ...,"Thu, 08 Oct 2026 18:05:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...
40,النفط,"If the Strait of Hormuz is open, why are gas a...","Fri, 09 Oct 2026 09:00:45 GMT",https://news.google.com/rss/articles/CBMifEFVX...
41,النفط,Boosting US oil supplies with Russian diesel u...,"Sat, 10 Oct 2026 00:15:00 GMT",https://news.google.com/rss/articles/CBMilwFBV...
42,النفط,Gas prices face new threat as Hurricane Isaias...,"Thu, 08 Oct 2026 18:33:35 GMT",https://news.google.com/rss/articles/CBMilAFBV...
43,النفط,"Current price of oil as of Oct. 9, 2026 - Fortune","Fri, 09 Oct 2026 11:00:00 GMT",https://news.google.com/rss/articles/CBMiYkFVX...
44,النفط,Sterling ticks higher as dollar dips on lower ...,"Fri, 09 Oct 2026 11:35:26 GMT",https://news.google.com/rss/articles/CBMimAFBV...
45,النفط,"In Maine Senate Race, Spiking Heating Oil Cost...","Thu, 08 Oct 2026 13:46:42 GMT",https://news.google.com/rss/articles/CBMigAFBV...
46,النفط,Oil prices settle higher as more production sh...,"Fri, 09 Oct 2026 20:19:51 GMT",https://news.google.com/rss/articles/CBMirAFBV...
47,النفط,"Russia, Germany Add Diesel Supply as Fuel Mark...","Fri, 09 Oct 2026 21:30:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...
48,النفط,Oil prices jump on tanker attacks and slowing ...,"Thu, 08 Oct 2026 10:46:10 GMT",https://news.google.com/rss/articles/CBMihAFBV...
49,النفط,Oil prices jump amid record tanker attacks in ...,"Thu, 08 Oct 2026 10:34:48 GMT",https://news.google.com/rss/articles/CBMijAFBV...

تم جمع الأخبار وحفظها بنجاح.

In [ ]:
# ==========================================
# الوَدْق AI - محلل الأخبار الاقتصادية
# ==========================================

!pip -q install feedparser

import feedparser
import pandas as pd
from datetime import datetime

news_sources = {
    "أخبار الاقتصاد العالمي":
        "https://news.google.com/rss/search?q=global+economy+markets&hl=en-US&gl=US&ceid=US:en",

    "أخبار الأسهم الأمريكية":
        "https://news.google.com/rss/search?q=US+stock+market&hl=en-US&gl=US&ceid=US:en",

    "أخبار السوق السعودي":
        "https://news.google.com/rss/search?q=Saudi+stock+market&hl=ar&gl=SA&ceid=SA:ar",

    "أخبار الذهب":
        "https://news.google.com/rss/search?q=gold+prices&hl=en-US&gl=US&ceid=US:en",

    "أخبار النفط":
        "https://news.google.com/rss/search?q=oil+prices+Brent+crude&hl=en-US&gl=US&ceid=US:en",

    "أخبار أسعار الفائدة":
        "https://news.google.com/rss/search?q=Federal+Reserve+interest+rates&hl=en-US&gl=US&ceid=US:en"
}

all_news = []

print("=" * 55)
print("🌧️ الوَدْق AI - الأخبار الاقتصادية")
print("وقت الفحص:", datetime.now().strftime("%Y-%m-%d %H:%M"))
print("=" * 55)

for category, url in news_sources.items():

    print("\n📰", category)

    try:
        feed = feedparser.parse(url)

        if not feed.entries:
            print("لم تصل أخبار من هذا المصدر.")
            continue

        for item in feed.entries[:5]:

            title = item.get("title", "بدون عنوان")
            link = item.get("link", "")
            published = item.get("published", "غير محدد")

            print("•", title)
            print("  التاريخ:", published)
            print("  الرابط:", link)

            all_news.append({
                "التصنيف": category,
                "عنوان الخبر": title,
                "تاريخ النشر": published,
                "الرابط": link
            })

    except Exception as e:
        print("تعذر جلب الأخبار:", str(e)[:100])

if all_news:

    news_df = pd.DataFrame(all_news)

    news_df.to_csv(
        "alwadq_ai_economic_news.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("\n✅ عدد الأخبار التي جُمعت:", len(news_df))
    print("✅ حُفظت الأخبار في alwadq_ai_economic_news.csv")

    display(news_df)

else:
    print("\n⚠️ لم يتم جلب أخبار.")
    print("تحققي من اتصال الإنترنت وحاولي مجددًا.")

=======================================================
🌧️ الوَدْق AI - الأخبار الاقتصادية
وقت الفحص: 2026-10-10 22:45
=======================================================

📰 أخبار الاقتصاد العالمي
• Global growth remains solid in a challenging environment - Peterson Institute for International Economics
  التاريخ: Tue, 06 Oct 2026 17:05:41 GMT
  الرابط: https://news.google.com/rss/articles/CBMipAFBVV95cUxQU0NqejZ2Zzh2ek5sUE5DUkRVSXBrZFVGVzZKODJBOXhGdFlEcFRVOFgxVUhIT3FSZWNhOUMydGRiR0pYY2d0NnRSaG45c2Vybk9neWJWNVp3UEFXem1TNFN3M2tmZjdrTWJ1QnRfdzZrM0M0bGxEcGFBbFg0aEwxVXdidkRtTEdjd3RWR3g4S0RVVktxcFNZbTRQMk5xOFFUek1YUQ?oc=5
• World economic growth to slow to 2.6% in 2026, UN trade body says - Yahoo Finance
  التاريخ: Fri, 09 Oct 2026 09:02:01 GMT
  الرابط: https://news.google.com/rss/articles/CBMijwFBVV95cUxPbmszdmlXR21SempqTS1yalpxY25vbHp0MWZZNUg4bk1qZzJrTkZaRThRRXplT1YxbGVNd0JyRF9fSk1DN2hPVkh2eWlncTM4WUNtTmxhUG5kMzhDZWlsWS1vUWN1c1FyRncxbmRiVjdJM3RKNjNjVjg5YzhtOXZqb2NOQzgzWVhiTXdzd2p2Yw?oc=5
• What’s happening this week in economics? - Deloitte
  التاريخ: Tue, 06 Oct 2026 07:00:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMiowFBVV95cUxPakZIT0JxM3JJV25jVHR1SjVUTkdCQThCNkRXOWN6T1ctQWN1RUp4MEctbWVEYVRsX3Y2UmZfS2Zhcmg0LUFUaVVadUNsYXJLWHEtRFR2Zm5aYmc2US1jcVd1YnRqTjdURksyZGdiVVRRNTFGRVFrX2l2WkxvX1JHWlFXYXVKcjNYQnNiWkJGSkRBVVlqYmRUcjc1QU55dEVUaWVR?oc=5
• The global economy has been resilient — so far - World Bank Blogs
  التاريخ: Mon, 28 Sep 2026 12:44:57 GMT
  الرابط: https://news.google.com/rss/articles/CBMimAFBVV95cUxOT3g4RmxxVWF1bWtXR1JiUTAwUUFjajMyR0NEN0kxQk9rc0F6cnMwRHk5Z1ljSVowNmlsTHpRaF9ROV9KRFh6WjEtWldaS2tkZjRUYjZlMTB2ejktenN1WFl3OE5RclZOWGwzaFlvZ080UVh5SnVUZ1JjajFzRFpHM05tSXlobm5heDJ1dWJTSGNUNnV6VElLYw?oc=5
• The remarkable resilience of the global economy - Financial Times
  التاريخ: Fri, 09 Oct 2026 17:39:56 GMT
  الرابط: https://news.google.com/rss/articles/CBMihAFBVV95cUxNMm9lTmdPZ1RMX3pkTnc5TUxORHZ0d2Rnd3RjU0pwaVcwUjJUOGJzTVNreUdYTUVwWkJRVlNpM0ozN2xUTnZUUXlaRmoxbW5ybzJHNk5QQmx0QkQ1b0o5cVBhbDNhcFZHQXFKMGFhcHN4Y3ZwNjFqTHc2M2dYTTJzNUJ1TlE?oc=5

📰 أخبار الأسهم الأمريكية
• Dow rises 400 points on Friday as Wall Street scores winning week: Live updates - CNBC
  التاريخ: Thu, 08 Oct 2026 22:07:27 GMT
  الرابط: https://news.google.com/rss/articles/CBMid0FVX3lxTE5nSVM4THI4YlFUdXYtTTJyX3ZJamZOSWdDa3owRkpVU3FHWEVzZ3NJcTBoSkt6YVluWW1jaFlGeVB0Q1pMdGk5Z2Y3UVpwZjJ0WjlHdFppQnBMQVRjT2lLTGFBTklzelhYSFVQdEJJejAxOHRpMGVn0gF8QVVfeXFMTThPS25hbl9MZ0p2cGw3Nm5Pby1vTml4OE5aUHo0N204RTVnOWN6Z24tX2FQVUhjY3hHN0xxUURlQ1dkSnh3bVE2NEM5SWRrQXFNUzlVUVl3UzdDVm1rQVJCaVVDSVFsSER1ZFlXUDRkRlNpeUloQzFsbHpQWA?oc=5
• Trump purchased up to $5 million of SpaceX bonds days before major space order - CNN
  التاريخ: Thu, 08 Oct 2026 20:51:01 GMT
  الرابط: https://news.google.com/rss/articles/CBMigwFBVV95cUxNLUhWUXRBZmpMeml1STFSTXFvZ2REc21ITXV5RkFQOVVjS2xLdE41SDlxakF5ak5iSVQtQUdUaHB2aFZpUmUtRWFqc1o0b3F4aWhNVHZ2cnUwbGZrWHgxZ0xvZlFvMFJmRzhIcWZFd0VzUTd5dlJJRnJiV0J0S3k0VU1DVQ?oc=5
• Wall Street posts weekly gains with earnings, inflation data on tap - Reuters
  التاريخ: Fri, 09 Oct 2026 23:33:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMiugFBVV95cUxNY0hWbFNBUlE5SFJjLVpMMnIwZzFpN2hVNEd2YkxlalYyVDRKTDZxcGJ0REJLUERXb0tlVVVreVZLMHFodlAtZlY0eDhuN2xiOHcybjM1c3gxMlBNTmZMWWdrdkhQOG9Pc2JRdTEwYXM5N181QmttRVEyRkdXTy1LT2J0ZVA4d2FXdjZZeGZwaGRaSUtDUXJUZXFjSU94cnprbTVUSXRpXzFtQzV2TWtpR1dNSjdaWVplUlE?oc=5
• Stock market today: Dow, S&P 500, Nasdaq rally to cap volatile week as earnings season nears - Yahoo Finance
  التاريخ: Fri, 09 Oct 2026 20:02:02 GMT
  الرابط: https://news.google.com/rss/articles/CBMiqwFBVV95cUxOdmNFVEJGaFByaVNnbUNON1BBd0MwM1JiR2x6SGJvYVJ4Qm9LdXhjbTRzcXpuZlhCQzBIY1hkSmxQTGJqYkc1ckhBR0tGbUYyRk9ybFAwRTZCbVRRS0QtWE03a2RzUEtwbGlYMHItc0xEd2RJTGJCSHI5Y2xUY2dObWxPWmgzN1M4dFM2dTdXNE45WDlJOTFBWEhObXNDOEg2LTh3NllkMGZFNjQ?oc=5
• Stock Market News, Oct. 9, 2026: Dow, S&P 500 finish higher as Nasdaq stretches weekly winning streak to four - MarketWatch
  التاريخ: Fri, 09 Oct 2026 21:52:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMixAFBVV95cUxOenJ2dkZDUnRBeENpdHNCVTJNeUc3OFc1WFBHUzl0M0RSdFZFR2E5dnI3c0taOFZ5Sjk1NTNYQ1hDaWZFblN5c3VDaGZwRHp2TkxxVERjUDZTaVZETTZlTGJNS0c1RVNvMTNxd3p3MnlTVWtKMVFiLVNCRlFLRURYWEw2WWxyUDBXdzhSNXMwWVZvTExKVDNCRzBCOFpjY0ZaTnJZLXFXd1NBYURLelB0d0I5MmR6VDJIV0haOGR4ek0wMDV6?oc=5

📰 أخبار السوق السعودي
• Bloomberg: Nournet Considers IPO on Saudi Stock Exchange - صحيفة مال
  التاريخ: Mon, 13 Jul 2026 07:00:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMia0FVX3lxTE9OcWRvLVN1c0hMVDhBUDl4Tm9iclZHLUFpcFhTcTVvZnBzV0tzRGQxeGtMellCRW40ZmlSVUY3UVk0LUw0LUQwVVFWNGFjYVhnTG1aWVpNZzVNOFYtZk5ieUpuTGZUVEJvVjdJ?oc=5
• Saudi Stocks Plunge and Fears of a Shortage of Exported Crude Escalate - الخبر اليمني
  التاريخ: Mon, 14 Sep 2026 07:00:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMiW0FVX3lxTE5XS09ob0NYZDJhd1JQdUFEN3d6Ylg2OERqYTRsZ1pVUkp6dDMxWmNqOFlWcFpKRjRkNjVGVGRYamFURVBqZG5YQnlJMVU1Mng1Qk50Y3Vwa1FoRWs?oc=5
• تاسي يتراجع إلى 10480 نقطة رغم اتساع المكاسب - جريدة الوطن السعودية
  التاريخ: Mon, 05 Oct 2026 14:42:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMiVEFVX3lxTE5aWGxMdXp6UkRiQ2tBcWV3WnFvS2JmZGJJem9XQ1Vsc3Q0UFh4aUt3NVVIVklwUXdZbXBrRHhKbnNVcHpnUzRLRFJLYVZkZFMxano5TtIBWEFVX3lxTE1oNkZ1VHdHTnpndDFKTEJRUXhZR1JoYUw0a0tJVlBiSTRHZ01FVEdvQXlqcFdWM0lZSkRRQlhscVJRZ01IS1NWcG5OcVA4QUxncVVicDQxRVE?oc=5
• Bank for International Settlements: Saudi Stock Market Ranked 13th Globally in 2025 - صحيفة مال
  التاريخ: Tue, 09 Jun 2026 07:00:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMibEFVX3lxTE9hQWg2aWNwTXdHYmVtN3FycVJvcGdqWldyVWU2eFJLcEN1NEF4cGxMTFFFSGpLNGxxSHE1WW81eVlma1g1a21PY240WXJlXzF4X1FTenRRNG5qRVhUX25pSUxSYkhZZkhrVzF2RA?oc=5
• مجموعة فقيه للرعاية الصحية تفوز بجائزة «برنامج الاستدامة لعام 2025» ضمن جوائز سوق المال السعودي - عكاظ
  التاريخ: Tue, 07 Jul 2026 07:00:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMiUkFVX3lxTE1pSmJPa2ZQc3dwbmxfM1FQMTJfajRFVmloTE40V1JmV0FjbnRsM0RsZkNPdWJadGZWRWE2dVVvVHRFV29vbF9JSVJENzBla2hDQ3fSAVRBVV95cUxOeEJHbjAzZkxxVU9iSV9wX1JDYW96a1g4QlJfR3ZsX2VSUFRfNnRMejFBZDlORmlpNXZsOVBKTDFRRUhibEdVdk9jQ2ZxclI3Ri01MTk?oc=5

📰 أخبار الذهب
• Wall Street nears bullish majority after gold’s late-week rally, Main Street fails to reclaim bullish bias as inflation data take center stage - Kitco
  التاريخ: Fri, 09 Oct 2026 18:27:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMivAFBVV95cUxQUG44Ynhha2xuQjluekdTRnlFQU9zcXJuYXJyZl9FMVFKV3VhY3lHSnM4My1jTURFRjVtc0F4eWx5cXZPOHVDU2lodkp3OUNNQXpZWkJGbzZYdnl6aVBLVDBBQXNxbDNJWURNc3FXU1hENmpTMWlJOV9uRUs4X1JaLUtjSVNKM0x2LVNIZ044QUJuN1A5dGFySVQ1SFF4S2Jsdzhvay1HZGw3TWpCTU9SSS1OaFg4UkIxQ3V0Rw?oc=5
• Gold snaps two-week losing streak; some analysts say may have found bottom (GLD:NYSEARCA) - Seeking Alpha
  التاريخ: Fri, 09 Oct 2026 21:50:04 GMT
  الرابط: https://news.google.com/rss/articles/CBMisAFBVV95cUxNRGxmY1ZQcFpWTmRQYnlOREZVTkVTSEVKckdWZVRXN3k4NW5KaUloc0MyRDBSd1BZbktVSlV4MkRSNGg1VW52YklhMEVXMnRSbjB0d0RCLXRlUkdoOGdYTjgzRl84Y1lNT29jZFhCc0JRdmF6YUI1dEd1RzAzY0JmTU94REN2b2FzMTFQMHZZTjZDNVYxT2RGN1VCVy04cE54SU52RGNwaC1UVWJGaGloVA?oc=5
• Gold ticks up as investors weigh Fed path, mounting debt concerns - Reuters
  التاريخ: Thu, 08 Oct 2026 10:31:04 GMT
  الرابط: https://news.google.com/rss/articles/CBMimAFBVV95cUxQaTl2VDRiV2EtanRNTGxRVGc4OEhQUUhZOEV1MXduVGNBOW1wa2V6N2lqaXJaX2hiVnpPdU5kSC05VGNVUV9ydExDbnVral9vVW1qTFlvYTZSMGY2cTFraXRJeEthaEZmMFRuVmtVYzc2azRkYlM5MVBvWG9nUGY0LUFBX2VmZHNWTkxHTVZGdUtvTWd2NGlJbg?oc=5
• Current price of gold as of October 9, 2026 - Fortune
  التاريخ: Fri, 09 Oct 2026 13:03:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMibkFVX3lxTE42OGtpVDBKVVBBUzg3a0xiMENQbXBZaTNHTGUyR2lJVzZhbEdtVVFXaG05V29YMm9iZWhUYk8wM1p3UHBocDE1eHRTdUtWdlYtNlA2Q1dtZUppTkFyVHQteGZTNXFfcnlzN0pTdTJn?oc=5
• Gold buying picks up after price correction, but shoppers prioritise affordability - The Economic Times
  التاريخ: Sat, 10 Oct 2026 04:59:03 GMT
  الرابط: https://news.google.com/rss/articles/CBMimgJBVV95cUxNcVk4bWVCMnNJTFN2b3ZpNXMwX2JOU2lNWGQwdjQtMU1uREJLNHBuRmo4Z2ZXekhtM2dCTWNCMWt6emt0WE5CaWdOTzlQdWtWb3hXRGdhNnE2SUVSUzFaSi1GdFdMTDAteXRFbjFUSElFekRsS05TbGMxZUxWbUlyTi1QNTE4U19FMS1qTVNDelRXUkpJSnV5QWk1VVhwS2NoTEdNaC1sT1g4M1d2UmlEMmlnM1diMGM3NXZjTm1TZkg4VHdOalpJNEU1eWhCaG1hRll1TURBMnM2azFzWU53SGp4dXI0OElnWmI1eEpXVGJhdkJJUTdYbnJuajM5RHlWMTNVQU1GeEF4c3ZyZEZJeDUwRUUzUFpQLVHSAZ8CQVVfeXFMTjZXb3JMZU55VzVNdUhhSE9waW9zSjhoMktSaXd0TUZfZWszRFppc2JSbDlKYTZic1ZjdU1pVVpHeEtpTncyNHljWjFBWTc1a2gycTJuWndnQzFnbmtFZEs0THR4VjJhNHlZQjlDVTduRTh4OUxMZG9KbkFSLU5mbDZOSmk2UVJqbDR1blU0bDJnekFabXY3LVp5bFhYWlBFem5wLTJRYmdhY3dzRXpyUHptYzBDclhJTUhYUWhPOEtLOWtYclVzUjlVb2dyMGg1ZWMzOE5GdlQ0eWJGcEZpWlA3VFJDaWwwZXZWSTh0akJISWc3TEJLU2E5RHVNenhHQXhoVDdVOEQxQzVmcFBQWTFSRVNlOGdWaHNOMXFxZFE?oc=5

📰 أخبار النفط
• Morgan Stanley Lowers Oil Price Forecasts After US-Iran Peace Deal - EnergyNow.com
  التاريخ: Fri, 09 Oct 2026 19:14:55 GMT
  الرابط: https://news.google.com/rss/articles/CBMipgFBVV95cUxPSVctRUFVM1l4Z3VNRnhLZVN0dV9KMENjZW1wWWo4eXJycklOLTdJSkJNSm9qbTB4WDB5OUFsaktnUDc0V2JheDl0eUZoZk43bVpCMjhSTEFJeXNpeWhlc1FhZnhvOXN3Q3B4R0ppbkM3ZmJreFpEbUd3Y3A3WmxTY2Jla1RzSXUwekdNV1l4bnlZOEw3bG85TUt2S08wRm9FNkNlajRR?oc=5
• Crude oil prices and refinery margins generally increased throughout the third quarter - U.S. Energy Information Administration (EIA) (.gov)
  التاريخ: Mon, 05 Oct 2026 13:04:29 GMT
  الرابط: https://news.google.com/rss/articles/CBMiY0FVX3lxTE5KRmxycVhJeUlHVmVsTnlsQXgtdFpsQ1BYaUxiUjF3bjZuYmFfUHlQY3JTdHBkMEJwVWJOUmpjM2hjNXl2X1BwVFJwQVlCUGlSXzBfWEVOZU9UQVVuN0xjdEJCVQ?oc=5
• Oil prices jump as Iran steps up tanker attacks, hurricane threatens U.S. Gulf production - CNBC
  التاريخ: Thu, 08 Oct 2026 01:46:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMiekFVX3lxTE9nV016TlVYUUlsNUNkSDVBaExxQnljQjE5N09hZDBZMlZ3SWpUUjlPWVRaYVk1VHNxeW1JdmxMVkFYMUNjXzNuSGFxcDB6Wm5rYWpoX3cwLUlFMkIzSE9Oamp4VTRHd3c2UWNoY0tMSGNpLWRWSEh4LXJR0gF_QVVfeXFMT1RHelpkMjVlSDdmLXk1OFV3Y1BvV2YwY0l6M01GLXYwNTRsQ3o2Z25qQU1ISE1NcnlnemxDN0hNaWM2aWVBd2FBZ016dWtGOWI0eGVucS1MbWh0VzVBQ0xlRktRZjRMQkdJSS1mR1lWOEZ0OGVSdkFPSmxCWl9rSQ?oc=5
• Oil prices settle higher as more production shut ahead of hurricane - Reuters
  التاريخ: Fri, 09 Oct 2026 20:19:51 GMT
  الرابط: https://news.google.com/rss/articles/CBMirAFBVV95cUxONW0wejJNQmpGTE9heFBmZG8wTWE5a010VFNMSDBqcThNXzBFTjZkbWF3NnpxSWxoVkRJSEhMcDk4VDh5OVp3bzlZNzdiS0pNTnd6aGkwQVZsU0JiOU9wb0k1ckN1V2ZUVl9sTFRuZnVhLXFlaDUwZGIxT2VxNW1RZUwyNlJ3c2ZxRkdONll5RVdtTnlfcDllN0pnLWE4VU1FblRvbHdkTkIwbHNk?oc=5
• Oil Prices Steady After Trump Appears to Rule Out Iran Strikes Before Midterms - WSJ
  التاريخ: Fri, 09 Oct 2026 19:51:58 GMT
  الرابط: https://news.google.com/rss/articles/CBMixwFBVV95cUxPenNnUDYybWpPV1NGRGZCVnRjbGxHNEZVRnBobXR4YUlfZ3FuVDFrZF95enJwZUF1cm1vZEFCYkFLVmxTU2RwRzg1dGQyWVE2dDE2bks5YkxRNzhlaEt6eUJSVHpJdFlYRVpaMGtmX3l4T2NyUzZiSkhCMnFMWkFETjlZdG9WbVhqMkNqU0NzV0hxSzFKRE0yQWNZOFZxMFJMVF9meW1aa3FsZk9HV0luU0VVZVp0RE0xYXQyTTk1SlFoUW9uMEZ3?oc=5

📰 أخبار أسعار الفائدة
• The Fed was unanimous about raising rates in September. Economic signals have since changed. - Yahoo Finance
  التاريخ: Wed, 07 Oct 2026 18:48:39 GMT
  الرابط: https://news.google.com/rss/articles/CBMi6gFBVV95cUxPQTlWVlVDb2E1VWpneHhHanhPR1l4MS1DWndsWXhiNGtNQlhmSkppSFhqMy1kZkItaFFTSGpyMXBlT3ZDMUpiQ0xqaVBEZUpIajhtSW02UE03cGJGQWNreFNVaU5UekVvWGtiOGZyYmg3SFJjUEVRakhQV1U2WklZOVFTQXNaSHFpRlFfWVBfeWZPLUVQcGdCNmEtbFpNc29heUE2VTdzclNQdjlqZWRBeVVYQzJ6TDRGVU1jMXo1azFwcjl1eGRZcHRQVVBIbmpzdGpVQllGZjFaTTB4b0NBM1o4YlVJZGlfY3c?oc=5
• U.S. Interest Rates Could Rise Over Next Six to Nine Months, Fed’s Musalem Says - WSJ
  التاريخ: Thu, 08 Oct 2026 18:45:00 GMT
  الرابط: https://news.google.com/rss/articles/CBMiwwFBVV95cUxOeHRyMnRQZ0p3RDBMZ2J3eDFvbXIwNFlMbWY0eE9GQnRMYVljeGZ0NlZKaVBGbkFnY090QzZHeE13c05hLUpTT3h6Rm9pcGtiOFBnUnI2RFcwVFlkUzk4MjNoY01PVlRLV0FMekNqVkdRRTFDZHVxNGFTQ0hLZEM4d1UzSHhBWF9scWh2d0txRW91emUzTzFIUEhKMVE2WUVpdmdlb0I3NGhHX0VCRV9yZTJlNmQyX3BRZVNuaDBVRjNtM2M?oc=5
• A Top Fed Official Casts Further Doubt on a Rate Rise This Month - The New York Times
  التاريخ: Thu, 08 Oct 2026 08:38:57 GMT
  الرابط: https://news.google.com/rss/articles/CBMikwFBVV95cUxNckNMd0xCc1RMemJpSlNXQVBEeVFKUktQWmFwTlBZWTFrM19DWTA1d1dtN3djS0tSbTY3VzhWYlp2NEdpQ1RIdUthT2xGMVhPNmxqRXFyUEloVVNRQWZ6S3VQeHlZaklEbGh2SWRmckNONnZXaV81TjItOTAwZlBPakZsTzRoVHpMUDVEYlFpbTJraXM?oc=5
• Fed officials see another hike coming, but no sign as to when, minutes show - CNBC
  التاريخ: Wed, 07 Oct 2026 18:00:37 GMT
  الرابط: https://news.google.com/rss/articles/CBMirwFBVV95cUxQUkc3RnFQUWZoam1MOFQ4MG85elpQcFIzb0VlajVQSlZXQXhFUHJlaHI3RGlXd1hOODRxRDNfV1YzZFNJakxNMzRiRzRNZkZqdWUxVG1WWWRVSUhMdUFZQ3BhUV9OR2cwdXFTVzhGc19XOGdBSWwxaUF3MEthSkxzRDlFTlRoVTBnLUQ3SlZVSEhYNWFEOE55TGN2djlkRG1JcWN5V3hNOV82eEVkaEJR0gG0AUFVX3lxTE9hS2JuRWZra2ZHZWc2YU9kMU9zYUN3a0FwcmtDbm9pclJiS2puN1I0Zkh6WVdQUmNEbFNDVmxPQ1ZFRURoZlRsVTh6aEl6bE5lUEc1ejNSM2hxdXdhVVNHVjU5eXhsTGx0UkI4Q3VGdXFLRVF5bXQzd1pUdmNBX09acGxwZDJEYk40X3ZzeEdvV3ViMlU1WmtaNHhvZzI2NDNpSmctZmNfdmtfcVVsdlIydnNXdA?oc=5
• Fed Interest Rate Forecast for the Next 5 Years: 2026 to 2031 - Norada Real Estate Investments
  التاريخ: Fri, 09 Oct 2026 19:39:43 GMT
  الرابط: https://news.google.com/rss/articles/CBMioAFBVV95cUxNVnFWOWJRSThWYmhuZmU3VWU2UVRiVUF1a3JQNGV2Z3NFXzRNTmoxRHFTVWFjYkJodnh3Z0RYeUFIWF9CeUdUWlNpMXEwZ0Z3S1RNRk1NNjRoWkFMaU9jMEdpdXpnbGFQNkQxUE8tNG9NZnI2dUJCSjNoUHhIZnB1Q0NTWjFudEhhSXViX2ZRU1hpSzhnWnlaZ2V1OGdBbWJh?oc=5

✅ عدد الأخبار التي جُمعت: 30
✅ حُفظت الأخبار في alwadq_ai_economic_news.csv

,التصنيف,عنوان الخبر,تاريخ النشر,الرابط
0,أخبار الاقتصاد العالمي,Global growth remains solid in a challenging e...,"Tue, 06 Oct 2026 17:05:41 GMT",https://news.google.com/rss/articles/CBMipAFBV...
1,أخبار الاقتصاد العالمي,"World economic growth to slow to 2.6% in 2026,...","Fri, 09 Oct 2026 09:02:01 GMT",https://news.google.com/rss/articles/CBMijwFBV...
2,أخبار الاقتصاد العالمي,What’s happening this week in economics? - Del...,"Tue, 06 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiowFBV...
3,أخبار الاقتصاد العالمي,The global economy has been resilient — so far...,"Mon, 28 Sep 2026 12:44:57 GMT",https://news.google.com/rss/articles/CBMimAFBV...
4,أخبار الاقتصاد العالمي,The remarkable resilience of the global econom...,"Fri, 09 Oct 2026 17:39:56 GMT",https://news.google.com/rss/articles/CBMihAFBV...
5,أخبار الأسهم الأمريكية,Dow rises 400 points on Friday as Wall Street ...,"Thu, 08 Oct 2026 22:07:27 GMT",https://news.google.com/rss/articles/CBMid0FVX...
6,أخبار الأسهم الأمريكية,Trump purchased up to $5 million of SpaceX bon...,"Thu, 08 Oct 2026 20:51:01 GMT",https://news.google.com/rss/articles/CBMigwFBV...
7,أخبار الأسهم الأمريكية,"Wall Street posts weekly gains with earnings, ...","Fri, 09 Oct 2026 23:33:00 GMT",https://news.google.com/rss/articles/CBMiugFBV...
8,أخبار الأسهم الأمريكية,"Stock market today: Dow, S&P 500, Nasdaq rally...","Fri, 09 Oct 2026 20:02:02 GMT",https://news.google.com/rss/articles/CBMiqwFBV...
9,أخبار الأسهم الأمريكية,"Stock Market News, Oct. 9, 2026: Dow, S&P 500 ...","Fri, 09 Oct 2026 21:52:00 GMT",https://news.google.com/rss/articles/CBMixAFBV...
10,أخبار السوق السعودي,Bloomberg: Nournet Considers IPO on Saudi Stoc...,"Mon, 13 Jul 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMia0FVX...
11,أخبار السوق السعودي,Saudi Stocks Plunge and Fears of a Shortage of...,"Mon, 14 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiW0FVX...
12,أخبار السوق السعودي,تاسي يتراجع إلى 10480 نقطة رغم اتساع المكاسب -...,"Mon, 05 Oct 2026 14:42:00 GMT",https://news.google.com/rss/articles/CBMiVEFVX...
13,أخبار السوق السعودي,Bank for International Settlements: Saudi Stoc...,"Tue, 09 Jun 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMibEFVX...
14,أخبار السوق السعودي,مجموعة فقيه للرعاية الصحية تفوز بجائزة «برنامج...,"Tue, 07 Jul 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiUkFVX...
15,أخبار الذهب,Wall Street nears bullish majority after gold’...,"Fri, 09 Oct 2026 18:27:00 GMT",https://news.google.com/rss/articles/CBMivAFBV...
16,أخبار الذهب,Gold snaps two-week losing streak; some analys...,"Fri, 09 Oct 2026 21:50:04 GMT",https://news.google.com/rss/articles/CBMisAFBV...
17,أخبار الذهب,"Gold ticks up as investors weigh Fed path, mou...","Thu, 08 Oct 2026 10:31:04 GMT",https://news.google.com/rss/articles/CBMimAFBV...
18,أخبار الذهب,"Current price of gold as of October 9, 2026 - ...","Fri, 09 Oct 2026 13:03:00 GMT",https://news.google.com/rss/articles/CBMibkFVX...
19,أخبار الذهب,"Gold buying picks up after price correction, b...","Sat, 10 Oct 2026 04:59:03 GMT",https://news.google.com/rss/articles/CBMimgJBV...
20,أخبار النفط,Morgan Stanley Lowers Oil Price Forecasts Afte...,"Fri, 09 Oct 2026 19:14:55 GMT",https://news.google.com/rss/articles/CBMipgFBV...
21,أخبار النفط,Crude oil prices and refinery margins generall...,"Mon, 05 Oct 2026 13:04:29 GMT",https://news.google.com/rss/articles/CBMiY0FVX...
22,أخبار النفط,Oil prices jump as Iran steps up tanker attack...,"Thu, 08 Oct 2026 01:46:00 GMT",https://news.google.com/rss/articles/CBMiekFVX...
23,أخبار النفط,Oil prices settle higher as more production sh...,"Fri, 09 Oct 2026 20:19:51 GMT",https://news.google.com/rss/articles/CBMirAFBV...
24,أخبار النفط,Oil Prices Steady After Trump Appears to Rule ...,"Fri, 09 Oct 2026 19:51:58 GMT",https://news.google.com/rss/articles/CBMixwFBV...
25,أخبار أسعار الفائدة,The Fed was unanimous about raising rates in S...,"Wed, 07 Oct 2026 18:48:39 GMT",https://news.google.com/rss/articles/CBMi6gFBV...
26,أخبار أسعار الفائدة,U.S. Interest Rates Could Rise Over Next Six t...,"Thu, 08 Oct 2026 18:45:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...
27,أخبار أسعار الفائدة,A Top Fed Official Casts Further Doubt on a Ra...,"Thu, 08 Oct 2026 08:38:57 GMT",https://news.google.com/rss/articles/CBMikwFBV...
28,أخبار أسعار الفائدة,"Fed officials see another hike coming, but no ...","Wed, 07 Oct 2026 18:00:37 GMT",https://news.google.com/rss/articles/CBMirwFBV...
29,أخبار أسعار الفائدة,Fed Interest Rate Forecast for the Next 5 Year...,"Fri, 09 Oct 2026 19:39:43 GMT",https://news.google.com/rss/articles/CBMioAFBV...

In [ ]:
import feedparser
import pandas as pd
from urllib.parse import quote

# مصادر الأخبار للأسواق العالمية والسعودية والأمريكية
queries = {
    "الأخبار العالمية": "global economy financial markets",
    "الذهب": "gold price market news",
    "النفط": "oil prices market news",
    "السوق السعودي": "Saudi stock market Tadawul",
    "السوق الأمريكي": "US stock market S&P 500 Nasdaq",
    "الدولار والفائدة": "US dollar Federal Reserve interest rates"
}

news = []

for category, query in queries.items():
    url = (
        "https://news.google.com/rss/search?q="
        + quote(query)
        + "&hl=ar&gl=SA&ceid=SA:ar"
    )

    feed = feedparser.parse(url)

    for entry in feed.entries[:5]:
        news.append({
            "التصنيف": category,
            "العنوان": entry.get("title", ""),
            "المصدر": entry.get("source", {}).get("title", ""),
            "الرابط": entry.get("link", ""),
            "تاريخ النشر": entry.get("published", "")
        })

df_news = pd.DataFrame(news)

print("عدد الأخبار التي تم جمعها:", len(df_news))
display(df_news)

عدد الأخبار التي تم جمعها: 30

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT"
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT"
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT"
3,الأخبار العالمية,مايسترو الأرقام يرحل بعد قرن من التأثير العالم...,عكاظ,https://news.google.com/rss/articles/CBMiVEFVX...,"Fri, 26 Jun 2026 07:00:00 GMT"
4,الأخبار العالمية,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT"
5,الذهب,اسعار الذهب في خطر الأسواق الصينية تغلق أبوابه...,YouTube,https://news.google.com/rss/articles/CBMiXEFVX...,"Mon, 05 Oct 2026 16:43:12 GMT"
6,الذهب,Gold prices in Jordan drop by 40 piasters per ...,خبرني - ننقل لك أخبار الأردن والعالم بموثوقية ...,https://news.google.com/rss/articles/CBMikAFBV...,"Thu, 08 Oct 2026 06:23:58 GMT"
7,الذهب,Gold rally takes a breather ahead of US inflat...,صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Wed, 26 Aug 2026 07:00:00 GMT"
8,الذهب,سعر الذهب في الهند اليوم: ارتفاع الذهب، وفقًا ...,tmgm.com,https://news.google.com/rss/articles/CBMixAFBV...,"Fri, 02 Oct 2026 05:00:33 GMT"
9,الذهب,https://www.markets.com/ar/news/bitcoin-btc-us...,Markets.com,https://news.google.com/rss/articles/CBMimwFBV...,"Wed, 23 Sep 2026 16:02:32 GMT"
10,النفط,UAE Fuel Price Increase September 2026 - سعودي...,سعودي اوتو,https://news.google.com/rss/articles/CBMia0FVX...,"Mon, 05 Oct 2026 00:15:53 GMT"
11,النفط,Oil: Prices supported by supply risks and Iran...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 07:07:50 GMT"
12,النفط,Oil prices fell as markets awaited development...,صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Wed, 27 May 2026 07:00:00 GMT"
13,النفط,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT"
14,النفط,First Light News: Oil continues to dominate se...,المتداول العربي,https://news.google.com/rss/articles/CBMi5AFBV...,"Tue, 17 Mar 2026 07:00:00 GMT"
15,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Thu, 08 Oct 2026 12:48:54 GMT"
16,السوق السعودي,13 private deals executed in the Saudi stock m...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Tue, 06 Oct 2026 13:27:11 GMT"
17,السوق السعودي,الأسهم السعودية تتراجع باليوم الأول لفتح السوق...,الجزيرة نت,https://news.google.com/rss/articles/CBMihAFBV...,"Sun, 01 Feb 2026 08:00:00 GMT"
18,السوق السعودي,12 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Mon, 05 Oct 2026 13:04:53 GMT"
19,السوق السعودي,13 Private Deals Executed on the Saudi Stock E...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Wed, 07 Oct 2026 13:27:17 GMT"
20,السوق الأمريكي,Global stocks mostly fall as oil prices and bo...,AFP.com,https://news.google.com/rss/articles/CBMiS0FVX...,"Thu, 24 Sep 2026 08:51:20 GMT"
21,السوق الأمريكي,Dow Jones futures rise due to easing Fed rate ...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Tue, 06 Oct 2026 08:39:59 GMT"
22,السوق الأمريكي,تداول مؤشرات VT Markets | S&P 500 | NASDAQ | F...,VT Markets,https://news.google.com/rss/articles/CBMiVEFVX...,"Tue, 23 Jun 2026 02:14:55 GMT"
23,السوق الأمريكي,Week Ahead: US PCE & NFP Keep the Fed in Focus...,tmgm.com,https://news.google.com/rss/articles/CBMingFBV...,"Mon, 28 Sep 2026 07:40:21 GMT"
24,السوق الأمريكي,S&P 500 fell 1.5% to close its fourth straight...,صحيفة مال,https://news.google.com/rss/articles/CBMiaEFVX...,"Sat, 21 Mar 2026 07:00:00 GMT"
25,الدولار والفائدة,"Gold inches lower as firmer dollar, higher yie...",صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Tue, 06 Oct 2026 08:15:24 GMT"
26,الدولار والفائدة,US Dollar: Fed cautious on further hikes – MUF...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 09:14:52 GMT"
27,الدولار والفائدة,New Zealand Dollar moves sideways as US Dollar...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 03:44:55 GMT"
28,الدولار والفائدة,Week Ahead: US PCE & NFP Keep the Fed in Focus...,tmgm.com,https://news.google.com/rss/articles/CBMingFBV...,"Mon, 28 Sep 2026 07:40:21 GMT"
29,الدولار والفائدة,Gold slips over 2% as dollar holds firm on Fed...,صحيفة مال,https://news.google.com/rss/articles/CBMia0FVX...,"Tue, 23 Jun 2026 07:00:00 GMT"

In [ ]:
# تحليل أولي للأخبار وتصنيفها حسب الكلمات المفتاحية

def classify_news(row):
    title = str(row["العنوان"]).lower()
    category = str(row["التصنيف"])

    if "الذهب" in category or "gold" in title:
        if any(word in title for word in [
            "surge", "rises", "rally", "jumps", "ارتفاع", "يصعد"
        ]):
            return "الذهب: خبر يشير إلى ارتفاع السعر"
        elif any(word in title for word in [
            "falls", "slips", "drops", "declines", "هبوط", "ينخفض"
        ]):
            return "الذهب: خبر يشير إلى انخفاض السعر"
        else:
            return "الذهب: يحتاج إلى تحليل إضافي"

    elif "السوق السعودي" in category:
        return "متابعة السوق السعودي"

    elif "السوق الأمريكي" in category:
        return "متابعة السوق الأمريكي"

    elif "النفط" in category:
        return "متابعة النفط"

    elif "الدولار" in category:
        return "متابعة الدولار والفائدة"

    else:
        return "أخبار عالمية"

df_news["التحليل الأولي"] = df_news.apply(classify_news, axis=1)

display(df_news[[
    "التصنيف",
    "العنوان",
    "التحليل الأولي"
]])

,التصنيف,العنوان,التحليل الأولي
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,أخبار عالمية
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,أخبار عالمية
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,أخبار عالمية
3,الأخبار العالمية,مايسترو الأرقام يرحل بعد قرن من التأثير العالم...,أخبار عالمية
4,الأخبار العالمية,Oil: Strait of Hormuz reopening steadies crude...,أخبار عالمية
5,الذهب,اسعار الذهب في خطر الأسواق الصينية تغلق أبوابه...,الذهب: يحتاج إلى تحليل إضافي
6,الذهب,Gold prices in Jordan drop by 40 piasters per ...,الذهب: يحتاج إلى تحليل إضافي
7,الذهب,Gold rally takes a breather ahead of US inflat...,الذهب: خبر يشير إلى ارتفاع السعر
8,الذهب,سعر الذهب في الهند اليوم: ارتفاع الذهب، وفقًا ...,الذهب: خبر يشير إلى ارتفاع السعر
9,الذهب,https://www.markets.com/ar/news/bitcoin-btc-us...,الذهب: يحتاج إلى تحليل إضافي
10,النفط,UAE Fuel Price Increase September 2026 - سعودي...,متابعة النفط
11,النفط,Oil: Prices supported by supply risks and Iran...,متابعة النفط
12,النفط,Oil prices fell as markets awaited development...,متابعة النفط
13,النفط,Oil: Strait of Hormuz reopening steadies crude...,متابعة النفط
14,النفط,First Light News: Oil continues to dominate se...,متابعة النفط
15,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,متابعة السوق السعودي
16,السوق السعودي,13 private deals executed in the Saudi stock m...,متابعة السوق السعودي
17,السوق السعودي,الأسهم السعودية تتراجع باليوم الأول لفتح السوق...,متابعة السوق السعودي
18,السوق السعودي,12 Private Deals Executed on the Saudi Stock M...,متابعة السوق السعودي
19,السوق السعودي,13 Private Deals Executed on the Saudi Stock E...,متابعة السوق السعودي
20,السوق الأمريكي,Global stocks mostly fall as oil prices and bo...,متابعة السوق الأمريكي
21,السوق الأمريكي,Dow Jones futures rise due to easing Fed rate ...,متابعة السوق الأمريكي
22,السوق الأمريكي,تداول مؤشرات VT Markets | S&P 500 | NASDAQ | F...,متابعة السوق الأمريكي
23,السوق الأمريكي,Week Ahead: US PCE & NFP Keep the Fed in Focus...,متابعة السوق الأمريكي
24,السوق الأمريكي,S&P 500 fell 1.5% to close its fourth straight...,متابعة السوق الأمريكي
25,الدولار والفائدة,"Gold inches lower as firmer dollar, higher yie...",الذهب: يحتاج إلى تحليل إضافي
26,الدولار والفائدة,US Dollar: Fed cautious on further hikes – MUF...,متابعة الدولار والفائدة
27,الدولار والفائدة,New Zealand Dollar moves sideways as US Dollar...,متابعة الدولار والفائدة
28,الدولار والفائدة,Week Ahead: US PCE & NFP Keep the Fed in Focus...,متابعة الدولار والفائدة
29,الدولار والفائدة,Gold slips over 2% as dollar holds firm on Fed...,الذهب: خبر يشير إلى انخفاض السعر

In [ ]:
import yfinance as yf
import pandas as pd

# رموز الأسواق العالمية
symbols = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط الخام": "CL=F",
    "مؤشر S&P 500": "^GSPC",
    "مؤشر ناسداك": "^IXIC",
    "الدولار مقابل الريال": "SAR=X",
    "أرامكو السعودية": "2222.SR"
}

market_data = []

for name, symbol in symbols.items():
    try:
        data = yf.Ticker(symbol).history(period="5d")

        if not data.empty:
            latest = data.iloc[-1]
            previous = data.iloc[-2] if len(data) > 1 else latest

            price = latest["Close"]
            old_price = previous["Close"]

            change = (
                ((price - old_price) / old_price) * 100
                if old_price != 0 else 0
            )

            market_data.append({
                "الأصل": name,
                "السعر الأخير": round(float(price), 4),
                "التغير %": round(float(change), 2),
                "تاريخ البيانات": str(data.index[-1])
            })
        else:
            print(f"لم تتوفر بيانات لـ {name}")

    except Exception as e:
        print(f"تعذر جلب بيانات {name}: {e}")

df_market = pd.DataFrame(market_data)

display(df_market)

                  الأصل  السعر الأخير  التغير %             تاريخ البيانات
0                 الذهب     4216.2998      1.43  2026-10-09 00:00:00-04:00
1                 الفضة       60.6700      2.72  2026-10-09 00:00:00-04:00
2           النفط الخام       91.8500      0.39  2026-10-09 00:00:00-04:00
3          مؤشر S&P 500     7811.5400      0.59  2026-10-09 00:00:00-04:00
4           مؤشر ناسداك    27366.1699      0.64  2026-10-09 00:00:00-04:00
5  الدولار مقابل الريال        3.7550      3.20  2026-10-10 00:00:00+01:00
6       أرامكو السعودية       25.7400     -0.39  2026-10-08 00:00:00+03:00

In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np

# الأصول التي سنحللها
assets = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط": "CL=F",
    "ناسداك": "^IXIC",
    "S&P 500": "^GSPC",
    "أرامكو": "2222.SR"
}

def analyze_asset(name, symbol):
    df = yf.download(
        symbol,
        period="6mo",
        interval="1d",
        progress=False,
        auto_adjust=True
    )

    if df.empty:
        print(f"لا توجد بيانات متاحة حاليًا: {name}")
        return None

    # استخراج أسعار الإغلاق
    close = df["Close"]

    # معالجة اختلاف شكل البيانات
    if isinstance(close, pd.DataFrame):
        close = close.iloc[:, 0]

    close = close.dropna()

    if len(close) < 50:
        print(f"بيانات غير كافية لتحليل {name}")
        return None

    # المتوسط المتحرك 50 جلسة
    ma50 = close.rolling(50).mean()

    # حساب RSI لفترة 14 جلسة
    delta = close.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1/14, min_periods=14, adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1/14, min_periods=14, adjust=False
    ).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))


    # حساب MACD
    ema12 = close.ewm(span=12, adjust=False).mean()
    ema26 = close.ewm(span=26, adjust=False).mean()

    macd = ema12 - ema26
    signal = macd.ewm(span=9, adjust=False).mean()

    price = float(close.iloc[-1])
    current_ma50 = float(ma50.iloc[-1])
    current_rsi = float(rsi.iloc[-1])
    current_macd = float(macd.iloc[-1])
    current_signal = float(signal.iloc[-1])

    if price > current_ma50:
        trend = "السعر فوق متوسط 50 جلسة"
    else:
        trend = "السعر تحت متوسط 50 جلسة"

    if current_rsi >= 70:
        momentum = "زخم مرتفع؛ قد يكون في منطقة تشبع شرائي"
    elif current_rsi <= 30:
        momentum = "زخم منخفض؛ قد يكون في منطقة تشبع بيعي"
    else:
        momentum = "زخم معتدل"

    return {
        "الأصل": name,
        "الرمز": symbol,
        "آخر سعر": round(price, 2),
        "متوسط 50 يوم": round(current_ma50, 2),
        "RSI": round(current_rsi, 2),
        "MACD": round(current_macd, 3),
        "خط الإشارة": round(current_signal, 3),
        "الاتجاه الفني": trend,
        "حالة الزخم": momentum,
        "تاريخ الإغلاق": str(close.index[-1].date())
    }

results = []
for name, symbol in assets.items():
    try:
        res = analyze_asset(name, symbol)
        if res:
            results.append(res)
    except Exception as e:
        print(f"⚠️ تعذر تحليل {name}: {e}")

if results:
    df_assets = pd.DataFrame(results)
    display(df_assets)
    df_assets.to_csv("alwadq_assets_analysis.csv", index=False, encoding="utf-8-sig")
    print("\n✅ تم حفظ التحليل الفني في alwadq_assets_analysis.csv")
else:
    print("❌ لم تكتمل عملية جلب وتحليل البيانات.")

,الأصل,الرمز,آخر سعر,متوسط 50 يوم,RSI,MACD,خط الإشارة,الاتجاه الفني,حالة الزخم,تاريخ الإغلاق
0,الذهب,GC=F,4216.30,4376.97,43.52,-64.386,-58.021,السعر تحت متوسط 50 جلسة,زخم معتدل,2026-10-09
1,الفضة,SI=F,60.67,64.11,43.01,-1.334,-1.050,السعر تحت متوسط 50 جلسة,زخم معتدل,2026-10-09
2,النفط,CL=F,91.85,89.20,50.12,-0.281,0.453,السعر فوق متوسط 50 جلسة,زخم معتدل,2026-10-09
3,ناسداك,^IXIC,27366.17,26562.98,60.26,276.930,242.963,السعر فوق متوسط 50 جلسة,زخم معتدل,2026-10-09
4,S&P 500,^GSPC,7811.54,7696.92,59.93,34.457,23.320,السعر فوق متوسط 50 جلسة,زخم معتدل,2026-10-09
5,أرامكو,2222.SR,25.74,25.99,50.07,-0.096,-0.144,السعر تحت متوسط 50 جلسة,زخم معتدل,2026-10-08

✅ تم حفظ التحليل الفني في alwadq_assets_analysis.csv

In [ ]:
# ==========================================
# الوَدْق AI 🌧️
# محرك التحليل الأولي للأخبار والأسواق
# ==========================================

import pandas as pd

def wadq_market_analysis(df):
    if "df_news" not in globals():
        print("⚠️ شغّلي كود جمع الأخبار أولاً.")
        return None

    if df is None or df.empty:
        print("⚠️ لا توجد أخبار لتحليلها.")
        return None

    results = df.copy()

    # تحديد السوق من عنوان الخبر ومحتواه
    def identify_market(row):
        text = str(row).lower()

        if any(x in text for x in ["gold", "الذهب", "xau"]):
            return "الذهب"
        elif any(x in text for x in ["silver", "الفضة"]):
            return "الفضة"
        elif any(x in text for x in ["oil", "النفط", "brent", "opec"]):
            return "النفط"
        elif any(x in text for x in ["tadawul", "تاسي", "السوق السعودي"]):
            return "السوق السعودي"
        elif any(x in text for x in ["nasdaq", "s&p 500", "dow jones"]):
            return "السوق الأمريكي"
        elif any(x in text for x in ["federal reserve", "fed ", "الفائدة", "inflation"]):
            return "الاقتصاد العالمي"
        else:
            return "أخبار عامة"

    # البحث عن عمود الأخبار
    possible_columns = [
        "title", "العنوان", "عنوان الخبر",
        "الخبر", "summary", "description"
    ]

    available_columns = [
        col for col in possible_columns if col in results.columns
    ]

    if available_columns:
        results["السوق"] = results[available_columns].fillna("").astype(str).agg(
            " ".join, axis=1
        ).apply(identify_market)
    else:
        print("⚠️ لم أجد عمود عنوان الخبر.")
        print("الأعمدة الموجودة:", list(results.columns))
        return None

    print("🌧️ الوَدْق AI — نتائج تحليل الأخبار")
    print("=" * 45)
    print(results["السوق"].value_counts().to_string())
    print("=" * 45)

    return results


# تشغيل التحليل
wadq_results = wadq_market_analysis(df_news)

if wadq_results is not None:
    display(wadq_results)

🌧️ الوَدْق AI — نتائج تحليل الأخبار
=============================================
السوق
أخبار عامة          12
النفط                6
الذهب                6
السوق الأمريكي       3
الاقتصاد العالمي     3
=============================================

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي,السوق
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT",أخبار عالمية,أخبار عامة
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT",أخبار عالمية,أخبار عامة
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT",أخبار عالمية,أخبار عامة
3,الأخبار العالمية,مايسترو الأرقام يرحل بعد قرن من التأثير العالم...,عكاظ,https://news.google.com/rss/articles/CBMiVEFVX...,"Fri, 26 Jun 2026 07:00:00 GMT",أخبار عالمية,أخبار عامة
4,الأخبار العالمية,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT",أخبار عالمية,النفط
5,الذهب,اسعار الذهب في خطر الأسواق الصينية تغلق أبوابه...,YouTube,https://news.google.com/rss/articles/CBMiXEFVX...,"Mon, 05 Oct 2026 16:43:12 GMT",الذهب: يحتاج إلى تحليل إضافي,الذهب
6,الذهب,Gold prices in Jordan drop by 40 piasters per ...,خبرني - ننقل لك أخبار الأردن والعالم بموثوقية ...,https://news.google.com/rss/articles/CBMikAFBV...,"Thu, 08 Oct 2026 06:23:58 GMT",الذهب: يحتاج إلى تحليل إضافي,الذهب
7,الذهب,Gold rally takes a breather ahead of US inflat...,صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Wed, 26 Aug 2026 07:00:00 GMT",الذهب: خبر يشير إلى ارتفاع السعر,الذهب
8,الذهب,سعر الذهب في الهند اليوم: ارتفاع الذهب، وفقًا ...,tmgm.com,https://news.google.com/rss/articles/CBMixAFBV...,"Fri, 02 Oct 2026 05:00:33 GMT",الذهب: خبر يشير إلى ارتفاع السعر,الذهب
9,الذهب,https://www.markets.com/ar/news/bitcoin-btc-us...,Markets.com,https://news.google.com/rss/articles/CBMimwFBV...,"Wed, 23 Sep 2026 16:02:32 GMT",الذهب: يحتاج إلى تحليل إضافي,أخبار عامة
10,النفط,UAE Fuel Price Increase September 2026 - سعودي...,سعودي اوتو,https://news.google.com/rss/articles/CBMia0FVX...,"Mon, 05 Oct 2026 00:15:53 GMT",متابعة النفط,أخبار عامة
11,النفط,Oil: Prices supported by supply risks and Iran...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 07:07:50 GMT",متابعة النفط,النفط
12,النفط,Oil prices fell as markets awaited development...,صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Wed, 27 May 2026 07:00:00 GMT",متابعة النفط,النفط
13,النفط,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT",متابعة النفط,النفط
14,النفط,First Light News: Oil continues to dominate se...,المتداول العربي,https://news.google.com/rss/articles/CBMi5AFBV...,"Tue, 17 Mar 2026 07:00:00 GMT",متابعة النفط,النفط
15,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Thu, 08 Oct 2026 12:48:54 GMT",متابعة السوق السعودي,أخبار عامة
16,السوق السعودي,13 private deals executed in the Saudi stock m...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Tue, 06 Oct 2026 13:27:11 GMT",متابعة السوق السعودي,أخبار عامة
17,السوق السعودي,الأسهم السعودية تتراجع باليوم الأول لفتح السوق...,الجزيرة نت,https://news.google.com/rss/articles/CBMihAFBV...,"Sun, 01 Feb 2026 08:00:00 GMT",متابعة السوق السعودي,أخبار عامة
18,السوق السعودي,12 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Mon, 05 Oct 2026 13:04:53 GMT",متابعة السوق السعودي,أخبار عامة
19,السوق السعودي,13 Private Deals Executed on the Saudi Stock E...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Wed, 07 Oct 2026 13:27:17 GMT",متابعة السوق السعودي,أخبار عامة
20,السوق الأمريكي,Global stocks mostly fall as oil prices and bo...,AFP.com,https://news.google.com/rss/articles/CBMiS0FVX...,"Thu, 24 Sep 2026 08:51:20 GMT",متابعة السوق الأمريكي,النفط
21,السوق الأمريكي,Dow Jones futures rise due to easing Fed rate ...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Tue, 06 Oct 2026 08:39:59 GMT",متابعة السوق الأمريكي,السوق الأمريكي
22,السوق الأمريكي,تداول مؤشرات VT Markets | S&P 500 | NASDAQ | F...,VT Markets,https://news.google.com/rss/articles/CBMiVEFVX...,"Tue, 23 Jun 2026 02:14:55 GMT",متابعة السوق الأمريكي,السوق الأمريكي
23,السوق الأمريكي,Week Ahead: US PCE & NFP Keep the Fed in Focus...,tmgm.com,https://news.google.com/rss/articles/CBMingFBV...,"Mon, 28 Sep 2026 07:40:21 GMT",متابعة السوق الأمريكي,الاقتصاد العالمي
24,السوق الأمريكي,S&P 500 fell 1.5% to close its fourth straight...,صحيفة مال,https://news.google.com/rss/articles/CBMiaEFVX...,"Sat, 21 Mar 2026 07:00:00 GMT",متابعة السوق الأمريكي,السوق الأمريكي
25,الدولار والفائدة,"Gold inches lower as firmer dollar, higher yie...",صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Tue, 06 Oct 2026 08:15:24 GMT",الذهب: يحتاج إلى تحليل إضافي,الذهب
26,الدولار والفائدة,US Dollar: Fed cautious on further hikes – MUF...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 09:14:52 GMT",متابعة الدولار والفائدة,الاقتصاد العالمي
27,الدولار والفائدة,New Zealand Dollar moves sideways as US Dollar...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 03:44:55 GMT",متابعة الدولار والفائدة,أخبار عامة
28,الدولار والفائدة,Week Ahead: US PCE & NFP Keep the Fed in Focus...,tmgm.com,https://news.google.com/rss/articles/CBMingFBV...,"Mon, 28 Sep 2026 07:40:21 GMT",متابعة الدولار والفائدة,الاقتصاد العالمي
29,الدولار والفائدة,Gold slips over 2% as dollar holds firm on Fed...,صحيفة مال,https://news.google.com/rss/articles/CBMia0FVX...,"Tue, 23 Jun 2026 07:00:00 GMT",الذهب: خبر يشير إلى انخفاض السعر,الذهب

In [ ]:
# ==========================================
# الوَدْق AI 🌧️
# المحلل الأولي لتأثير الأخبار
# ==========================================
import re
def analyze_news_impact(text):
    text = str(text).lower()
    positive_words = [
        "rise", "rises", "rising", "gain", "gains",
        "surge", "growth", "bullish", "ارتفاع",
        "صعود", "ارتفاعات", "نمو", "مكاسب",
        "زيادة الأرباح", "نتائج إيجابية"
    ]
    negative_words = [
        "fall", "falls", "falling", "drop", "drops",
        "decline", "crash", "loss", "bearish",
        "انخفاض", "هبوط", "تراجع", "خسائر",
        "أزمة", "نتائج سلبية"
    ]
    positive_count = sum(
        1 for word in positive_words if word in text
    )
    negative_count = sum(
        1 for word in negative_words if word in text
    )
    if positive_count > negative_count:
        return "🟢 نبرة إيجابية"
    elif negative_count > positive_count:
        return "🔴 نبرة سلبية"
    else:
        return "🟡 محايدة أو غير واضحة"
def wadq_analyze_dataframe(df):
    if df is None or df.empty:
        print("لا توجد أخبار للتحليل.")
        return None
    results = df.copy()
    text_columns = [
        col for col in [
            "title", "العنوان", "عنوان الخبر",
            "الخبر", "summary", "description"
        ]
        if col in results.columns
    ]
    if not text_columns:
        print("لم أجد عمودًا يحتوي على عناوين الأخبار.")
        print("الأعمدة المتاحة:", list(results.columns))
        return None
    results["نبرة الخبر"] = (
        results[text_columns]
        .fillna("")
        .astype(str)
        .agg(" ".join, axis=1)
        .apply(analyze_news_impact)
    )
    print("🌧️ الوَدْق AI — تحليل نبرة الأخبار")
    print("=" * 40)
    print(results["نبرة الخبر"].value_counts().to_string())
    return results
# استخدام الأخبار التي جمعناها سابقًا
if "df_news" in globals():
    wadq_impact_results = wadq_analyze_dataframe(df_news)
elif "wadq_results" in globals() and wadq_results is not None:
    wadq_impact_results = wadq_analyze_dataframe(wadq_results)
else:
    print("شغّلي كود جمع الأخبار أولًا.")

🌧️ الوَدْق AI — تحليل نبرة الأخبار
========================================
نبرة الخبر
🟡 محايدة أو غير واضحة    25
🟢 نبرة إيجابية            3
🔴 نبرة سلبية              2

In [ ]:
# ==========================================
# الوَدْق AI 🌧️
# جلب بيانات الأسواق العالمية
# ==========================================

!pip -q install yfinance

import yfinance as yf
import pandas as pd

markets = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط": "CL=F",
    "مؤشر S&P 500": "^GSPC",
    "مؤشر ناسداك": "^IXIC",
    "مؤشر داو جونز": "^DJI",
    "الدولار الأمريكي": "DX-Y.NYB"
}

market_data = []

for name, symbol in markets.items():
    try:
        data = yf.Ticker(symbol).history(period="5d")

        if data.empty or len(data) < 2:
            print(f"⚠️ لا توجد بيانات كافية: {name}")
            continue

        previous_close = float(data["Close"].iloc[-2])
        last_close = float(data["Close"].iloc[-1])

        change = (
            (last_close - previous_close) / previous_close
        ) * 100

        market_data.append({
            "السوق": name,
            "آخر سعر إغلاق متاح": round(last_close, 3),
            "التغير %": round(change, 2),
            "الحركة": (
                "🟢 ارتفاع"
                if change > 0
                else "🔴 انخفاض"
                if change < 0
                else "🟡 استقرار"
            )
        })

    except Exception as e:
        print(f"تعذر جلب بيانات {name}: {e}")

market_df = pd.DataFrame(market_data)

if not market_df.empty:
    display(market_df)
else:
    print("لم تُجلب البيانات. تحققي من الاتصال بالإنترنت.")

              السوق  آخر سعر إغلاق متاح  التغير %    الحركة
0             الذهب            4216.300      1.43  🟢 ارتفاع
1             الفضة              60.670      2.72  🟢 ارتفاع
2             النفط              91.850      0.39  🟢 ارتفاع
3      مؤشر S&P 500            7811.540      0.59  🟢 ارتفاع
4       مؤشر ناسداك           27366.170      0.64  🟢 ارتفاع
5     مؤشر داو جونز           51654.949      0.83  🟢 ارتفاع
6  الدولار الأمريكي             102.210      0.07  🟢 ارتفاع

In [ ]:
# ==========================================
# الوَدْق AI 🌧️
# متابعة السوق السعودي
# ==========================================

import yfinance as yf
import pandas as pd

saudi_stocks = {
    "مؤشر السوق السعودي تاسي": "^TASI.SR",
    "مصرف الراجحي": "1120.SR",
    "أرامكو السعودية": "2222.SR",
    "معادن": "1211.SR",
    "سابك": "2010.SR",
    "أكوا باور": "2082.SR"
}

saudi_results = []

for name, symbol in saudi_stocks.items():
    try:
        data = yf.Ticker(symbol).history(period="5d")

        if data.empty or len(data) < 2:
            print(f"لم تتوفر بيانات كافية لـ {name}")
            continue

        previous = float(data["Close"].iloc[-2])
        latest = float(data["Close"].iloc[-1])

        change = ((latest - previous) / previous) * 100

        saudi_results.append({
            "السهم أو المؤشر": name,
            "آخر إغلاق متاح": round(latest, 2),
            "التغير %": round(change, 2),
            "الاتجاه السابق": (
                "🟢 ارتفاع"
                if change > 0
                else "🔴 انخفاض"
                if change < 0
                else "🟡 مستقر"
            )
        })

    except Exception as e:
        print(f"تعذر جلب {name}: {e}")

saudi_df = pd.DataFrame(saudi_results)

if not saudi_df.empty:
    print("🌧️ الوَدْق AI — السوق السعودي")
    display(saudi_df)
else:
    print(
        "لم تصل بيانات السوق السعودي من المصدر الحالي. "
        "سنحتاج إلى تجربة مصدر بيانات آخر."
    )

لم تتوفر بيانات كافية لـ مؤشر السوق السعودي تاسي
🌧️ الوَدْق AI — السوق السعودي

   السهم أو المؤشر  آخر إغلاق متاح  التغير % الاتجاه السابق
0     مصرف الراجحي           62.30     -1.42       🔴 انخفاض
1  أرامكو السعودية           25.74     -0.39       🔴 انخفاض
2            معادن           62.40     -0.95       🔴 انخفاض
3             سابك           45.80     -1.63       🔴 انخفاض
4        أكوا باور          164.90     -3.62       🔴 انخفاض

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI
# التحليل الفني للأسهم السعودية
# ==========================================

import yfinance as yf
import pandas as pd

def wadq_technical_analysis(name, symbol):

    data = yf.Ticker(symbol).history(period="6mo")

    if data.empty or len(data) < 30:
        print(f"⚠️ البيانات غير كافية لتحليل {name}")
        return None

    close = data["Close"]

    # حساب RSI لمدة 14 فترة
    delta = close.diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1/14, min_periods=14, adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1/14, min_periods=14, adjust=False
    ).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))

    # المتوسطات المتحركة
    ma20 = close.rolling(20).mean()
    ma50 = close.rolling(50).mean()

    last_price = close.iloc[-1]
    last_rsi = rsi.iloc[-1]
    last_ma20 = ma20.iloc[-1]
    last_ma50 = ma50.iloc[-1]

    if pd.isna(last_rsi) or pd.isna(last_ma50):
        print(f"⚠️ البيانات غير كافية لحساب المؤشرات لـ {name}")
        return None

    if last_rsi >= 70:
        rsi_signal = "زخم مرتفع"
    elif last_rsi <= 30:
        rsi_signal = "زخم منخفض"
    else:
        rsi_signal = "زخم متوسط"

    if last_price > last_ma20 and last_ma20 > last_ma50:
        trend = "اتجاه صاعد وفق الشروط"
    elif last_price < last_ma20 and last_ma20 < last_ma50:
        trend = "اتجاه هابط وفق الشروط"
    else:
        trend = "اتجاه مختلط"

    return {
        "السهم": name,
        "آخر إغلاق": round(float(last_price), 2),
        "RSI": round(float(last_rsi), 2),
        "إشارة RSI": rsi_signal,
        "المتوسط 20": round(float(last_ma20), 2),
        "المتوسط 50": round(float(last_ma50), 2),
        "قراءة الاتجاه": trend
    }


stocks = {
    "مصرف الراجحي": "1120.SR",
    "أرامكو السعودية": "2222.SR",
    "معادن": "1211.SR",
    "سابك": "2010.SR",
    "أكوا باور": "2082.SR"
}

results = []

for name, symbol in stocks.items():
    try:
        result = wadq_technical_analysis(name, symbol)

        if result:
            results.append(result)

    except Exception as e:
        print(f"تعذر تحليل {name}: {e}")

technical_df = pd.DataFrame(results)

if not technical_df.empty:
    print("🌧️ نتائج التحليل الفني — الوَدْق AI")
    display(technical_df)
else:
    print("لم تتوفر بيانات كافية للتحليل.")

🌧️ نتائج التحليل الفني — الوَدْق AI

,السهم,آخر إغلاق,RSI,إشارة RSI,المتوسط 20,المتوسط 50,قراءة الاتجاه
0,مصرف الراجحي,62.30,39.27,زخم متوسط,63.99,64.22,اتجاه هابط وفق الشروط
1,أرامكو السعودية,25.74,50.07,زخم متوسط,25.63,25.99,اتجاه مختلط
2,معادن,62.40,46.39,زخم متوسط,62.56,63.98,اتجاه هابط وفق الشروط
3,سابك,45.80,32.09,زخم متوسط,47.41,48.79,اتجاه هابط وفق الشروط
4,أكوا باور,164.90,36.31,زخم متوسط,173.85,183.65,اتجاه هابط وفق الشروط

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI
# نظام الإشارات الفنية الأولي
# ==========================================

import pandas as pd

def wadq_signal(row):

    rsi = row["RSI"]
    trend = row["قراءة الاتجاه"]

    if pd.isna(rsi):
        return "⚪ بيانات غير كافية"

    if trend == "اتجاه صاعد وفق الشروط" and 50 <= rsi < 70:
        return "🟢 إشارات إيجابية متوافقة"

    elif trend == "اتجاه هابط وفق الشروط" and 30 < rsi < 50:
        return "🔴 إشارات سلبية متوافقة"

    elif rsi >= 70:
        return "🟡 زخم مرتفع — احذري من التسرع"

    elif rsi <= 30:
        return "🟡 زخم منخفض — يحتاج إلى تأكيد"

    else:
        return "⚪ إشارات مختلطة — انتظري التأكيد"


if "technical_df" in globals() and not technical_df.empty:

    signal_df = technical_df.copy()

    signal_df["إشارة الوَدْق"] = signal_df.apply(
        wadq_signal, axis=1
    )

    print("🌧️ الوَدْق AI — تقرير الإشارات الفنية")
    print("=" * 50)

    display(
        signal_df[
            [
                "السهم",
                "آخر إغلاق",
                "RSI",
                "قراءة الاتجاه",
                "إشارة الوَدْق"
            ]
        ]
    )

else:
    print("شغّلي كود التحليل الفني أولًا.")

🌧️ الوَدْق AI — تقرير الإشارات الفنية
==================================================

,السهم,آخر إغلاق,RSI,قراءة الاتجاه,إشارة الوَدْق
0,مصرف الراجحي,62.30,39.27,اتجاه هابط وفق الشروط,🔴 إشارات سلبية متوافقة
1,أرامكو السعودية,25.74,50.07,اتجاه مختلط,⚪ إشارات مختلطة — انتظري التأكيد
2,معادن,62.40,46.39,اتجاه هابط وفق الشروط,🔴 إشارات سلبية متوافقة
3,سابك,45.80,32.09,اتجاه هابط وفق الشروط,🔴 إشارات سلبية متوافقة
4,أكوا باور,164.90,36.31,اتجاه هابط وفق الشروط,🔴 إشارات سلبية متوافقة

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI
# لوحة متابعة الأسواق العالمية والسعودية
# ==========================================

import pandas as pd

# دمج بيانات الأسواق العالمية والسعودية
frames = []

if "market_df" in globals() and not market_df.empty:
    frames.append(
        market_df.rename(columns={
            "السوق": "الأصل",
            "آخر سعر إغلاق متاح": "آخر سعر",
            "الحركة": "الحركة السابقة"
        })
    )

if "saudi_df" in globals() and not saudi_df.empty:
    frames.append(
        saudi_df.rename(columns={
            "السهم أو المؤشر": "الأصل",
            "آخر إغلاق متاح": "آخر سعر",
            "الاتجاه السابق": "الحركة السابقة"
        })
    )

if frames:
    wadq_dashboard = pd.concat(
        frames,
        ignore_index=True,
        sort=False
    )

    print("🌧️ الوَدْق AI — لوحة الأسواق")
    print("=" * 50)

    display(wadq_dashboard)

    print("عدد الأصول المعروضة:", len(wadq_dashboard))

else:
    print(
        "لم أجد بيانات الأسواق في الذاكرة الحالية. "
        "شغّلي أكواد جلب البيانات السابقة أولًا."
    )

🌧️ الوَدْق AI — لوحة الأسواق
==================================================

               الأصل    آخر سعر  التغير % الحركة السابقة
0              الذهب   4216.300      1.43       🟢 ارتفاع
1              الفضة     60.670      2.72       🟢 ارتفاع
2              النفط     91.850      0.39       🟢 ارتفاع
3       مؤشر S&P 500   7811.540      0.59       🟢 ارتفاع
4        مؤشر ناسداك  27366.170      0.64       🟢 ارتفاع
5      مؤشر داو جونز  51654.949      0.83       🟢 ارتفاع
6   الدولار الأمريكي    102.210      0.07       🟢 ارتفاع
7       مصرف الراجحي     62.300     -1.42       🔴 انخفاض
8    أرامكو السعودية     25.740     -0.39       🔴 انخفاض
9              معادن     62.400     -0.95       🔴 انخفاض
10              سابك     45.800     -1.63       🔴 انخفاض
11         أكوا باور    164.900     -3.62       🔴 انخفاض

عدد الأصول المعروضة: 12

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI
# حساب الدعم والمقاومة
# ==========================================

import yfinance as yf
import pandas as pd

def wadq_support_resistance(name, symbol):

    data = yf.Ticker(symbol).history(period="3mo")

    if data.empty or len(data) < 20:
        print(f"لا توجد بيانات كافية لـ {name}")
        return None

    close = data["Close"]
    high = data["High"]
    low = data["Low"]

    price = float(close.iloc[-1])

    # أعلى وأدنى سعر خلال آخر 20 جلسة
    resistance = float(high.tail(20).max())
    support = float(low.tail(20).min())

    # متوسط المدى السعري
    avg_range = float((high - low).tail(14).mean())

    return {
        "الأصل": name,
        "آخر إغلاق": round(price, 3),
        "الدعم التقريبي": round(support, 3),
        "المقاومة التقريبية": round(resistance, 3),
        "متوسط المدى اليومي": round(avg_range, 3),
        "المسافة للدعم %": round(
            (price - support) / price * 100, 2
        ),
        "المسافة للمقاومة %": round(
            (resistance - price) / price * 100, 2
        )
    }


assets = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط": "CL=F",
    "مصرف الراجحي": "1120.SR",
    "أرامكو السعودية": "2222.SR",
    "معادن": "1211.SR",
    "سابك": "2010.SR",
    "أكوا باور": "2082.SR"
}

support_results = []

for name, symbol in assets.items():
    try:
        result = wadq_support_resistance(name, symbol)

        if result is not None:
            support_results.append(result)

    except Exception as e:
        print(f"تعذر تحليل {name}: {e}")

support_df = pd.DataFrame(support_results)

if not support_df.empty:
    print("🌧️ الوَدْق AI — مستويات الدعم والمقاومة")
    display(support_df)
else:
    print("لم تتوفر بيانات كافية لحساب المستويات.")# ==========================================
# 🌧️ الوَدْق AI
# حساب الدعم والمقاومة
# ==========================================

import yfinance as yf
import pandas as pd

def wadq_support_resistance(name, symbol):

    data = yf.Ticker(symbol).history(period="3mo")

    if data.empty or len(data) < 20:
        print(f"لا توجد بيانات كافية لـ {name}")
        return None

    close = data["Close"]
    high = data["High"]
    low = data["Low"]

    price = float(close.iloc[-1])

    # أعلى وأدنى سعر خلال آخر 20 جلسة
    resistance = float(high.tail(20).max())
    support = float(low.tail(20).min())

    # متوسط المدى السعري
    avg_range = float((high - low).tail(14).mean())

    return {
        "الأصل": name,
        "آخر إغلاق": round(price, 3),
        "الدعم التقريبي": round(support, 3),
        "المقاومة التقريبية": round(resistance, 3),
        "متوسط المدى اليومي": round(avg_range, 3),
        "المسافة للدعم %": round(
            (price - support) / price * 100, 2
        ),
        "المسافة للمقاومة %": round(
            (resistance - price) / price * 100, 2
        )
    }


assets = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط": "CL=F",
    "مصرف الراجحي": "1120.SR",
    "أرامكو السعودية": "2222.SR",
    "معادن": "1211.SR",
    "سابك": "2010.SR",
    "أكوا باور": "2082.SR"
}

support_results = []

for name, symbol in assets.items():
    try:
        result = wadq_support_resistance(name, symbol)

        if result is not None:
            support_results.append(result)

    except Exception as e:
        print(f"تعذر تحليل {name}: {e}")

support_df = pd.DataFrame(support_results)

if not support_df.empty:
    print("🌧️ الوَدْق AI — مستويات الدعم والمقاومة")
    display(support_df)
else:
    print("لم تتوفر بيانات كافية لحساب المستويات.")

🌧️ الوَدْق AI — مستويات الدعم والمقاومة

,الأصل,آخر إغلاق,الدعم التقريبي,المقاومة التقريبية,متوسط المدى اليومي,المسافة للدعم %,المسافة للمقاومة %
0,الذهب,4216.30,4091.200,4439.800,81.379,2.97,5.30
1,الفضة,60.67,58.915,66.940,0.715,2.89,10.33
2,النفط,91.85,86.860,106.750,4.219,5.43,16.22
3,مصرف الراجحي,62.30,62.150,65.771,0.806,0.24,5.57
4,أرامكو السعودية,25.74,25.120,26.180,0.279,2.41,1.71
5,معادن,62.40,59.850,66.900,1.371,4.09,7.21
6,سابك,45.80,45.700,50.050,0.689,0.22,9.28
7,أكوا باور,164.90,161.500,191.900,4.757,2.06,16.37

🌧️ الوَدْق AI — مستويات الدعم والمقاومة

,الأصل,آخر إغلاق,الدعم التقريبي,المقاومة التقريبية,متوسط المدى اليومي,المسافة للدعم %,المسافة للمقاومة %
0,الذهب,4216.30,4091.200,4439.800,81.379,2.97,5.30
1,الفضة,60.67,58.915,66.940,0.715,2.89,10.33
2,النفط,91.85,86.860,106.750,4.219,5.43,16.22
3,مصرف الراجحي,62.30,62.150,65.771,0.806,0.24,5.57
4,أرامكو السعودية,25.74,25.120,26.180,0.279,2.41,1.71
5,معادن,62.40,59.850,66.900,1.371,4.09,7.21
6,سابك,45.80,45.700,50.050,0.689,0.22,9.28
7,أكوا باور,164.90,161.500,191.900,4.757,2.06,16.37

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI
# التقرير الفني الموحد
# ==========================================

import pandas as pd

if (
    "technical_df" in globals()
    and "support_df" in globals()
    and not technical_df.empty
    and not support_df.empty
):

    report = pd.merge(
        technical_df,
        support_df,
        left_on="السهم",
        right_on="الأصل",
        how="inner"
    )

    def wadq_review(row):

        price = row["آخر إغلاق_x"]
        rsi = row["RSI"]
        support = row["الدعم التقريبي"]
        resistance = row["المقاومة التقريبية"]
        trend = row["قراءة الاتجاه"]

        if pd.isna(price) or pd.isna(rsi):
            return "⚪ بيانات غير كافية"

        if price <= support * 1.01:
            return "🟡 قريب من الدعم — راقبي تأكيد الارتداد"

        if price >= resistance * 0.99:
            return "🟡 قريب من المقاومة — راقبي الاختراق"

        if trend == "اتجاه صاعد وفق الشروط" and rsi >= 50:
            return "🟢 اتجاه إيجابي يحتاج إلى تأكيد"

        if trend == "اتجاه هابط وفق الشروط" and rsi < 50:
            return "🔴 اتجاه سلبي — تجنبي التسرع"

        return "⚪ إشارات مختلطة — انتظار"

    report["قراءة الوَدْق"] = report.apply(
        wadq_review, axis=1
    )

    print("🌧️ الوَدْق AI — التقرير الفني الموحد")
    display(report)

else:
    print(
        "شغّلي كود التحليل الفني وكود الدعم والمقاومة أولًا."
    )

🌧️ الوَدْق AI — التقرير الفني الموحد

,السهم,آخر إغلاق_x,RSI,إشارة RSI,المتوسط 20,المتوسط 50,قراءة الاتجاه,الأصل,آخر إغلاق_y,الدعم التقريبي,المقاومة التقريبية,متوسط المدى اليومي,المسافة للدعم %,المسافة للمقاومة %,قراءة الوَدْق
0,مصرف الراجحي,62.30,39.27,زخم متوسط,63.99,64.22,اتجاه هابط وفق الشروط,مصرف الراجحي,62.30,62.15,65.771,0.806,0.24,5.57,🟡 قريب من الدعم — راقبي تأكيد الارتداد
1,أرامكو السعودية,25.74,50.07,زخم متوسط,25.63,25.99,اتجاه مختلط,أرامكو السعودية,25.74,25.12,26.180,0.279,2.41,1.71,⚪ إشارات مختلطة — انتظار
2,معادن,62.40,46.39,زخم متوسط,62.56,63.98,اتجاه هابط وفق الشروط,معادن,62.40,59.85,66.900,1.371,4.09,7.21,🔴 اتجاه سلبي — تجنبي التسرع
3,سابك,45.80,32.09,زخم متوسط,47.41,48.79,اتجاه هابط وفق الشروط,سابك,45.80,45.70,50.050,0.689,0.22,9.28,🟡 قريب من الدعم — راقبي تأكيد الارتداد
4,أكوا باور,164.90,36.31,زخم متوسط,173.85,183.65,اتجاه هابط وفق الشروط,أكوا باور,164.90,161.50,191.900,4.757,2.06,16.37,🔴 اتجاه سلبي — تجنبي التسرع

In [ ]:
# 🌧️ الوَدْق AI — التقرير الفني الموحد

import pandas as pd

# التحقق من وجود بيانات التحليل الفني
if "technical_df" not in globals():
    print("شغّلي كود التحليل الفني أولًا.")

elif "support_df" not in globals():
    print("شغّلي كود الدعم والمقاومة أولًا.")

elif technical_df.empty or support_df.empty:
    print("لا توجد بيانات كافية لإعداد التقرير.")

else:
    # توحيد أسماء الأعمدة قبل الدمج
    tech = technical_df.copy()
    support = support_df.copy()

    tech = tech.rename(columns={
        "آخر إغلاق": "السعر الفني"
    })

    support = support.rename(columns={
        "آخر إغلاق": "سعر الدعم"
    })

    report = pd.merge(
        tech,
        support,
        left_on="السهم",
        right_on="الأصل",
        how="inner"
    )

    def wadq_review(row):
        price = row["السعر الفني"]
        rsi = row["RSI"]
        support_level = row["الدعم التقريبي"]
        resistance_level = row["المقاومة التقريبية"]
        trend = row["قراءة الاتجاه"]

        if pd.isna(price) or pd.isna(rsi):
            return "بيانات غير كافية"

        if price <= support_level * 1.01:
            return "قريب من الدعم — يحتاج إلى تأكيد"

        elif price >= resistance_level * 0.99:
            return "قريب من المقاومة — يحتاج إلى تأكيد"

        elif (
            trend == "اتجاه صاعد وفق الشروط"
            and rsi >= 50
        ):
            return "اتجاه إيجابي مبدئي"

        elif (
            trend == "اتجاه هابط وفق الشروط"
            and rsi < 50
        ):
            return "اتجاه سلبي مبدئي"

        else:
            return "إشارات مختلطة — انتظار"

    report["قراءة الوَدْق"] = report.apply(
        wadq_review,
        axis=1
    )

    print("🌧️ الوَدْق AI — التقرير الفني الموحد")

    display(report)

🌧️ الوَدْق AI — التقرير الفني الموحد

,السهم,السعر الفني,RSI,إشارة RSI,المتوسط 20,المتوسط 50,قراءة الاتجاه,الأصل,سعر الدعم,الدعم التقريبي,المقاومة التقريبية,متوسط المدى اليومي,المسافة للدعم %,المسافة للمقاومة %,قراءة الوَدْق
0,مصرف الراجحي,62.30,39.27,زخم متوسط,63.99,64.22,اتجاه هابط وفق الشروط,مصرف الراجحي,62.30,62.15,65.771,0.806,0.24,5.57,قريب من الدعم — يحتاج إلى تأكيد
1,أرامكو السعودية,25.74,50.07,زخم متوسط,25.63,25.99,اتجاه مختلط,أرامكو السعودية,25.74,25.12,26.180,0.279,2.41,1.71,إشارات مختلطة — انتظار
2,معادن,62.40,46.39,زخم متوسط,62.56,63.98,اتجاه هابط وفق الشروط,معادن,62.40,59.85,66.900,1.371,4.09,7.21,اتجاه سلبي مبدئي
3,سابك,45.80,32.09,زخم متوسط,47.41,48.79,اتجاه هابط وفق الشروط,سابك,45.80,45.70,50.050,0.689,0.22,9.28,قريب من الدعم — يحتاج إلى تأكيد
4,أكوا باور,164.90,36.31,زخم متوسط,173.85,183.65,اتجاه هابط وفق الشروط,أكوا باور,164.90,161.50,191.900,4.757,2.06,16.37,اتجاه سلبي مبدئي

In [ ]:
# 🌧️ الوَدْق AI — ملخص الدعم والمقاومة

import pandas as pd
from IPython.display import display

if "support_df" in globals() and not support_df.empty:

    summary = support_df.copy()

    print("🌧️ الوَدْق AI")
    print("=" * 40)
    print("تقرير مستويات الدعم والمقاومة")
    print("عدد الأصول التي جرى تحليلها:", len(summary))

    display(summary)

else:
    print("شغّلي كود الدعم والمقاومة أولًا.")

🌧️ الوَدْق AI
========================================
تقرير مستويات الدعم والمقاومة
عدد الأصول التي جرى تحليلها: 8

,الأصل,آخر إغلاق,الدعم التقريبي,المقاومة التقريبية,متوسط المدى اليومي,المسافة للدعم %,المسافة للمقاومة %
0,الذهب,4216.30,4091.200,4439.800,81.379,2.97,5.30
1,الفضة,60.67,58.915,66.940,0.715,2.89,10.33
2,النفط,91.85,86.860,106.750,4.219,5.43,16.22
3,مصرف الراجحي,62.30,62.150,65.771,0.806,0.24,5.57
4,أرامكو السعودية,25.74,25.120,26.180,0.279,2.41,1.71
5,معادن,62.40,59.850,66.900,1.371,4.09,7.21
6,سابك,45.80,45.700,50.050,0.689,0.22,9.28
7,أكوا باور,164.90,161.500,191.900,4.757,2.06,16.37

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI — لوحة التحكم التفاعلية
# ==========================================

!pip -q install ipywidgets

import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

title = widgets.HTML(
    value="""
    <div style="padding:15px; border-radius:10px;">
        <h2>🌧️ الوَدْق AI</h2>
        <h3>لوحة متابعة الأسواق والتحليل الفني</h3>
        <p>الذهب | الفضة | النفط | الأسهم السعودية</p>
    </div>
    """
)

market_selector = widgets.Dropdown(
    options=["جميع الأصول"] +
        (
            support_df["الأصل"].dropna().tolist()
            if "support_df" in globals()
            else []
        ),
    description="اختر الأصل:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="350px")
)

output = widgets.Output()

def show_market(change=None):
    with output:
        clear_output(wait=True)

        if "support_df" not in globals() or support_df.empty:
            print("لا توجد بيانات. شغّلي كود الدعم والمقاومة أولًا.")
            return

        df = support_df.copy()

        if market_selector.value != "جميع الأصول":
            df = df[df["الأصل"] == market_selector.value]

        display(df)

market_selector.observe(show_market, names="value")

display(title, market_selector, output)
show_market()

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 45.5 MB/s eta 0:00:00

HTML(value='\n    <div style="padding:15px; border-radius:10px;">\n        <h2>🌧️ الوَدْق AI</h2>\n        <h3…

Dropdown(description='اختر الأصل:', layout=Layout(width='350px'), options=('جميع الأصول', 'الذهب', 'الفضة', 'ا…

Output()

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI — لوحة اختيار الأسواق
# ==========================================

import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

# التحقق من وجود بيانات الدعم والمقاومة
if "support_df" in globals() and not support_df.empty:

    assets = support_df["الأصل"].dropna().tolist()

    selector = widgets.Dropdown(
        options=["جميع الأصول"] + assets,
        value="جميع الأصول",
        description="اختر الأصل:",
        style={"description_width": "initial"},
        layout=widgets.Layout(width="350px")
    )

    result_area = widgets.Output()

    def show_asset(change=None):
        with result_area:
            clear_output(wait=True)

            data = support_df.copy()

            if selector.value != "جميع الأصول":
                data = data[data["الأصل"] == selector.value]

            display(data)

    selector.observe(show_asset, names="value")

    print("🌧️ الوَدْق AI — لوحة متابعة الأسواق")
    print("اختاري الأصل الذي تريدين الاطلاع على بياناته.")

    display(selector, result_area)
    show_asset()

else:
    print(
        "لم أجد بيانات الدعم والمقاومة. "
        "شغّلي كود حساب الدعم والمقاومة أولًا."
    )# ==========================================
# 🌧️ الوَدْق AI — لوحة اختيار الأسواق
# ==========================================

import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

# التحقق من وجود بيانات الدعم والمقاومة
if "support_df" in globals() and not support_df.empty:

    assets = support_df["الأصل"].dropna().tolist()

    selector = widgets.Dropdown(
        options=["جميع الأصول"] + assets,
        value="جميع الأصول",
        description="اختر الأصل:",
        style={"description_width": "initial"},
        layout=widgets.Layout(width="350px")
    )

    result_area = widgets.Output()

    def show_asset(change=None):
        with result_area:
            clear_output(wait=True)

            data = support_df.copy()

            if selector.value != "جميع الأصول":
                data = data[data["الأصل"] == selector.value]

            display(data)

    selector.observe(show_asset, names="value")

    print("🌧️ الوَدْق AI — لوحة متابعة الأسواق")
    print("اختاري الأصل الذي تريدين الاطلاع على بياناته.")

    display(selector, result_area)
    show_asset()

else:
    print(
        "لم أجد بيانات الدعم والمقاومة. "
        "شغّلي كود حساب الدعم والمقاومة أولًا."
    )

🌧️ الوَدْق AI — لوحة متابعة الأسواق
اختاري الأصل الذي تريدين الاطلاع على بياناته.

Dropdown(description='اختر الأصل:', layout=Layout(width='350px'), options=('جميع الأصول', 'الذهب', 'الفضة', 'ا…

Output()

🌧️ الوَدْق AI — لوحة متابعة الأسواق
اختاري الأصل الذي تريدين الاطلاع على بياناته.

Dropdown(description='اختر الأصل:', layout=Layout(width='350px'), options=('جميع الأصول', 'الذهب', 'الفضة', 'ا…

Output()

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI — تحديث بيانات الأسواق
# ==========================================

import yfinance as yf
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

assets = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط": "CL=F",
    "مصرف الراجحي": "1120.SR",
    "أرامكو السعودية": "2222.SR",
    "معادن": "1211.SR",
    "سابك": "2010.SR",
    "أكوا باور": "2082.SR"
}

refresh_button = widgets.Button(
    description="🔄 تحديث بيانات الأسواق",
    button_style="success",
    layout=widgets.Layout(width="250px", height="45px")
)

refresh_output = widgets.Output()

def refresh_markets(button):
    with refresh_output:
        refresh_output.clear_output(wait=True)

        results = []

        print("🌧️ الوَدْق AI — جارٍ تحديث البيانات...")

        for name, symbol in assets.items():
            try:
                data = yf.Ticker(symbol).history(period="3mo")

                if data.empty or len(data) < 20:
                    print(f"لا توجد بيانات كافية لـ {name}")
                    continue

                close = data["Close"]
                high = data["High"]
                low = data["Low"]

                price = float(close.iloc[-1])
                support = float(low.tail(20).min())
                resistance = float(high.tail(20).max())

                results.append({
                    "الأصل": name,
                    "آخر إغلاق متاح": round(price, 3),
                    "الدعم التقريبي": round(support, 3),
                    "المقاومة التقريبية": round(resistance, 3)
                })

            except Exception as e:
                print(f"تعذر تحديث {name}: {e}")

        if results:
            global support_df
            support_df = pd.DataFrame(results)

            print("\nاكتمل التحديث:")
            display(support_df)

        else:
            print("تعذر جلب البيانات. تحققي من الاتصال بالإنترنت.")

refresh_button.on_click(refresh_markets)

display(refresh_button, refresh_output)

Button(button_style='success', description='🔄 تحديث بيانات الأسواق', layout=Layout(height='45px', width='250px…

Output()

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI — مقارنة حركة الأسعار
# ==========================================

import yfinance as yf
import pandas as pd
from IPython.display import display

assets = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط": "CL=F",
    "مصرف الراجحي": "1120.SR",
    "أرامكو السعودية": "2222.SR",
    "معادن": "1211.SR",
    "سابك": "2010.SR",
    "أكوا باور": "2082.SR"
}

price_results = []

for name, symbol in assets.items():
    try:
        data = yf.Ticker(symbol).history(period="5d")

        if data.empty or len(data) < 2:
            print(f"بيانات غير كافية: {name}")
            continue

        previous_close = float(data["Close"].iloc[-2])
        last_close = float(data["Close"].iloc[-1])

        change_pct = (
            (last_close - previous_close)
            / previous_close
        ) * 100

        if change_pct > 0:
            movement = "🟢 ارتفاع"
        elif change_pct < 0:
            movement = "🔴 انخفاض"
        else:
            movement = "🟡 دون تغير"

        price_results.append({
            "الأصل": name,
            "آخر إغلاق متاح": round(last_close, 3),
            "الإغلاق السابق": round(previous_close, 3),
            "التغير %": round(change_pct, 2),
            "الحركة": movement
        })

    except Exception as e:
        print(f"تعذر جلب بيانات {name}: {e}")

price_df = pd.DataFrame(price_results)

if not price_df.empty:
    print("🌧️ الوَدْق AI — مقارنة حركة الأسعار")
    display(price_df)
else:
    print("لم تتوفر بيانات كافية. تحققي من اتصال الإنترنت.")# ==========================================
# 🌧️ الوَدْق AI — مقارنة حركة الأسعار
# ==========================================

import yfinance as yf
import pandas as pd
from IPython.display import display

assets = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط": "CL=F",
    "مصرف الراجحي": "1120.SR",
    "أرامكو السعودية": "2222.SR",
    "معادن": "1211.SR",
    "سابك": "2010.SR",
    "أكوا باور": "2082.SR"
}

price_results = []

for name, symbol in assets.items():
    try:
        data = yf.Ticker(symbol).history(period="5d")

        if data.empty or len(data) < 2:
            print(f"بيانات غير كافية: {name}")
            continue

        previous_close = float(data["Close"].iloc[-2])
        last_close = float(data["Close"].iloc[-1])

        change_pct = (
            (last_close - previous_close)
            / previous_close
        ) * 100

        if change_pct > 0:
            movement = "🟢 ارتفاع"
        elif change_pct < 0:
            movement = "🔴 انخفاض"
        else:
            movement = "🟡 دون تغير"

        price_results.append({
            "الأصل": name,
            "آخر إغلاق متاح": round(last_close, 3),
            "الإغلاق السابق": round(previous_close, 3),
            "التغير %": round(change_pct, 2),
            "الحركة": movement
        })

    except Exception as e:
        print(f"تعذر جلب بيانات {name}: {e}")

price_df = pd.DataFrame(price_results)

if not price_df.empty:
    print("🌧️ الوَدْق AI — مقارنة حركة الأسعار")
    display(price_df)
else:
    print("لم تتوفر بيانات كافية. تحققي من اتصال الإنترنت.")

🌧️ الوَدْق AI — مقارنة حركة الأسعار

             الأصل  آخر إغلاق متاح  الإغلاق السابق  التغير %    الحركة
0            الذهب         4216.30        4157.000      1.43  🟢 ارتفاع
1            الفضة           60.67          59.064      2.72  🟢 ارتفاع
2            النفط           91.85          91.490      0.39  🟢 ارتفاع
3     مصرف الراجحي           62.30          63.200     -1.42  🔴 انخفاض
4  أرامكو السعودية           25.74          25.840     -0.39  🔴 انخفاض
5            معادن           62.40          63.000     -0.95  🔴 انخفاض
6             سابك           45.80          46.560     -1.63  🔴 انخفاض
7        أكوا باور          164.90         171.100     -3.62  🔴 انخفاض

🌧️ الوَدْق AI — مقارنة حركة الأسعار

             الأصل  آخر إغلاق متاح  الإغلاق السابق  التغير %    الحركة
0            الذهب         4216.30        4157.000      1.43  🟢 ارتفاع
1            الفضة           60.67          59.064      2.72  🟢 ارتفاع
2            النفط           91.85          91.490      0.39  🟢 ارتفاع
3     مصرف الراجحي           62.30          63.200     -1.42  🔴 انخفاض
4  أرامكو السعودية           25.74          25.840     -0.39  🔴 انخفاض
5            معادن           62.40          63.000     -0.95  🔴 انخفاض
6             سابك           45.80          46.560     -1.63  🔴 انخفاض
7        أكوا باور          164.90         171.100     -3.62  🔴 انخفاض

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI — ربط الأخبار بحركة الأسواق
# ==========================================

import pandas as pd

# تحديد كلمات مرتبطة بالأصول المالية
asset_keywords = {
    "الذهب": ["gold", "الذهب", "xau"],
    "الفضة": ["silver", "الفضة"],
    "النفط": ["oil", "crude", "brent", "النفط", "أوبك"],
    "السوق السعودي": [
        "tadawul", "saudi", "السعودية",
        "تاسي", "الراجحي", "أرامكو"
    ],
    "السوق الأمريكي": [
        "s&p 500", "nasdaq", "dow jones",
        "wall street", "الفيدرالي الأمريكي"
    ]
}

def classify_asset(text):
    text = str(text).lower()

    for asset, keywords in asset_keywords.items():
        if any(word in text for word in keywords):
            return asset

    return "أخبار عامة"


# استخدام جدول الأخبار الموجود في الذاكرة
if "df_news" in globals() and not df_news.empty:

    news_linked = df_news.copy()

    possible_columns = [
        "title", "العنوان", "عنوان الخبر",
        "الخبر", "summary", "description"
    ]

    text_columns = [
        col for col in possible_columns
        if col in news_linked.columns
    ]

    if text_columns:
        news_linked["نص الخبر"] = (
            news_linked[text_columns]
            .fillna("")
            .astype(str)
            .agg(" ".join, axis=1)
        )

        news_linked["السوق المرتبط"] = (
            news_linked["نص الخبر"].apply(classify_asset)
        )

        print("🌧️ الوَدْق AI — الأخبار المرتبطة بالأسواق")

        display(
            news_linked[
                ["نص الخبر", "السوق المرتبط"]
            ]
        )

    else:
        print(
            "لم أجد عمود عنوان الخبر. "
            "الأعمدة الموجودة:",
            list(news_linked.columns)
        )

else:
    print(
        "جدول الأخبار غير موجود في الذاكرة. "
        "شغّلي كود جمع الأخبار أولًا."
    )

🌧️ الوَدْق AI — الأخبار المرتبطة بالأسواق

                                             نص الخبر   السوق المرتبط
0   SAMA Governor: Saudi Economy Remains Resilient...   السوق السعودي
1   Azerbaijan’s Central Bank Governor addresses I...      أخبار عامة
2   تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...      أخبار عامة
3   مايسترو الأرقام يرحل بعد قرن من التأثير العالم...      أخبار عامة
4   Oil: Strait of Hormuz reopening steadies crude...           النفط
5   اسعار الذهب في خطر الأسواق الصينية تغلق أبوابه...           الذهب
6   Gold prices in Jordan drop by 40 piasters per ...           الذهب
7   Gold rally takes a breather ahead of US inflat...           الذهب
8   سعر الذهب في الهند اليوم: ارتفاع الذهب، وفقًا ...           الذهب
9   https://www.markets.com/ar/news/bitcoin-btc-us...      أخبار عامة
10  UAE Fuel Price Increase September 2026 - سعودي...      أخبار عامة
11  Oil: Prices supported by supply risks and Iran...           النفط
12  Oil prices fell as markets awaited development...           النفط
13  Oil: Strait of Hormuz reopening steadies crude...           النفط
14  First Light News: Oil continues to dominate se...           النفط
15  18 Private Deals Executed on the Saudi Stock M...   السوق السعودي
16  13 private deals executed in the Saudi stock m...   السوق السعودي
17  الأسهم السعودية تتراجع باليوم الأول لفتح السوق...   السوق السعودي
18  12 Private Deals Executed on the Saudi Stock M...   السوق السعودي
19  13 Private Deals Executed on the Saudi Stock E...   السوق السعودي
20  Global stocks mostly fall as oil prices and bo...           النفط
21  Dow Jones futures rise due to easing Fed rate ...  السوق الأمريكي
22  تداول مؤشرات VT Markets | S&P 500 | NASDAQ | F...  السوق الأمريكي
23  Week Ahead: US PCE & NFP Keep the Fed in Focus...      أخبار عامة
24  S&P 500 fell 1.5% to close its fourth straight...  السوق الأمريكي
25  Gold inches lower as firmer dollar, higher yie...           الذهب
26  US Dollar: Fed cautious on further hikes – MUF...      أخبار عامة
27  New Zealand Dollar moves sideways as US Dollar...      أخبار عامة
28  Week Ahead: US PCE & NFP Keep the Fed in Focus...      أخبار عامة
29  Gold slips over 2% as dollar holds firm on Fed...           الذهب

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI — تحليل تأثير الأخبار على الأسواق
# ==========================================

import pandas as pd

def analyze_news_impact(title, category=""):
    text = f"{title} {category}".lower()

    positive_words = [
        "rise", "rises", "rise due", "gain", "gains",
        "surge", "higher", "ارتفاع", "يرتفع",
        "صعود", "مكاسب"
    ]

    negative_words = [
        "fall", "falls", "fell", "drop", "drops",
        "lower", "decline", "slips", "selloff",
        "انخفاض", "تراجع", "هبوط", "خسائر"
    ]

    if any(word in text for word in positive_words):
        return "إشارة إيجابية محتملة"

    elif any(word in text for word in negative_words):
        return "إشارة سلبية محتملة"

    else:
        return "تأثير غير واضح — يحتاج تحليلًا إضافيًا"


# البحث عن جدول الأخبار الموجود
news_candidates = ["df_news", "news_df", "all_news"]

news_source = None

for variable in news_candidates:
    if variable in globals():
        obj = globals()[variable]

        if isinstance(obj, pd.DataFrame) and not obj.empty:
            news_source = obj.copy()
            print("تم العثور على جدول الأخبار:", variable)
            break


if news_source is not None:

    print("\n🌧️ تقرير الوَدْق AI لتحليل الأخبار")

    # اكتشاف عمود العنوان
    title_candidates = [
        "title", "العنوان", "عنوان الخبر",
        "الخبر", "headline"
    ]

    title_col = next(
        (c for c in title_candidates if c in news_source.columns),
        None
    )

    # اكتشاف عمود التصنيف
    category_candidates = [
        "category", "السوق", "التصنيف",
        "market", "source_category"
    ]

    category_col = next(
        (c for c in category_candidates if c in news_source.columns),
        None
    )

    if title_col:

        if category_col:
            news_source["تحليل الخبر"] = news_source.apply(
                lambda row: analyze_news_impact(
                    row[title_col],
                    row[category_col]
                ),
                axis=1
            )
        else:
            news_source["تحليل الخبر"] = news_source[title_col].apply(
                analyze_news_impact
            )

        display(news_source)

    else:
        print("لم أتعرف على عمود عناوين الأخبار.")
        print("الأعمدة المتاحة:", list(news_source.columns))

else:
    print(
        "لم أجد جدول الأخبار بالاسم المتوقع. "
        "أرسلي لي صورة كود جمع الأخبار لنربطه بالتحليل."
    )

تم العثور على جدول الأخبار: df_news

🌧️ تقرير الوَدْق AI لتحليل الأخبار

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي,تحليل الخبر
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا
3,الأخبار العالمية,مايسترو الأرقام يرحل بعد قرن من التأثير العالم...,عكاظ,https://news.google.com/rss/articles/CBMiVEFVX...,"Fri, 26 Jun 2026 07:00:00 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا
4,الأخبار العالمية,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا
5,الذهب,اسعار الذهب في خطر الأسواق الصينية تغلق أبوابه...,YouTube,https://news.google.com/rss/articles/CBMiXEFVX...,"Mon, 05 Oct 2026 16:43:12 GMT",الذهب: يحتاج إلى تحليل إضافي,إشارة إيجابية محتملة
6,الذهب,Gold prices in Jordan drop by 40 piasters per ...,خبرني - ننقل لك أخبار الأردن والعالم بموثوقية ...,https://news.google.com/rss/articles/CBMikAFBV...,"Thu, 08 Oct 2026 06:23:58 GMT",الذهب: يحتاج إلى تحليل إضافي,إشارة سلبية محتملة
7,الذهب,Gold rally takes a breather ahead of US inflat...,صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Wed, 26 Aug 2026 07:00:00 GMT",الذهب: خبر يشير إلى ارتفاع السعر,تأثير غير واضح — يحتاج تحليلًا إضافيًا
8,الذهب,سعر الذهب في الهند اليوم: ارتفاع الذهب، وفقًا ...,tmgm.com,https://news.google.com/rss/articles/CBMixAFBV...,"Fri, 02 Oct 2026 05:00:33 GMT",الذهب: خبر يشير إلى ارتفاع السعر,إشارة إيجابية محتملة
9,الذهب,https://www.markets.com/ar/news/bitcoin-btc-us...,Markets.com,https://news.google.com/rss/articles/CBMimwFBV...,"Wed, 23 Sep 2026 16:02:32 GMT",الذهب: يحتاج إلى تحليل إضافي,تأثير غير واضح — يحتاج تحليلًا إضافيًا
10,النفط,UAE Fuel Price Increase September 2026 - سعودي...,سعودي اوتو,https://news.google.com/rss/articles/CBMia0FVX...,"Mon, 05 Oct 2026 00:15:53 GMT",متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا
11,النفط,Oil: Prices supported by supply risks and Iran...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 07:07:50 GMT",متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا
12,النفط,Oil prices fell as markets awaited development...,صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Wed, 27 May 2026 07:00:00 GMT",متابعة النفط,إشارة سلبية محتملة
13,النفط,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT",متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا
14,النفط,First Light News: Oil continues to dominate se...,المتداول العربي,https://news.google.com/rss/articles/CBMi5AFBV...,"Tue, 17 Mar 2026 07:00:00 GMT",متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا
15,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Thu, 08 Oct 2026 12:48:54 GMT",متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا
16,السوق السعودي,13 private deals executed in the Saudi stock m...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Tue, 06 Oct 2026 13:27:11 GMT",متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا
17,السوق السعودي,الأسهم السعودية تتراجع باليوم الأول لفتح السوق...,الجزيرة نت,https://news.google.com/rss/articles/CBMihAFBV...,"Sun, 01 Feb 2026 08:00:00 GMT",متابعة السوق السعودي,إشارة سلبية محتملة
18,السوق السعودي,12 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Mon, 05 Oct 2026 13:04:53 GMT",متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا
19,السوق السعودي,13 Private Deals Executed on the Saudi Stock E...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Wed, 07 Oct 2026 13:27:17 GMT",متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا
20,السوق الأمريكي,Global stocks mostly fall as oil prices and bo...,AFP.com,https://news.google.com/rss/articles/CBMiS0FVX...,"Thu, 24 Sep 2026 08:51:20 GMT",متابعة السوق الأمريكي,إشارة إيجابية محتملة
21,السوق الأمريكي,Dow Jones futures rise due to easing Fed rate ...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Tue, 06 Oct 2026 08:39:59 GMT",متابعة السوق الأمريكي,إشارة إيجابية محتملة
22,السوق الأمريكي,تداول مؤشرات VT Markets | S&P 500 | NASDAQ | F...,VT Markets,https://news.google.com/rss/articles/CBMiVEFVX...,"Tue, 23 Jun 2026 02:14:55 GMT",متابعة السوق الأمريكي,تأثير غير واضح — يحتاج تحليلًا إضافيًا
23,السوق الأمريكي,Week Ahead: US PCE & NFP Keep the Fed in Focus...,tmgm.com,https://news.google.com/rss/articles/CBMingFBV...,"Mon, 28 Sep 2026 07:40:21 GMT",متابعة السوق الأمريكي,تأثير غير واضح — يحتاج تحليلًا إضافيًا
24,السوق الأمريكي,S&P 500 fell 1.5% to close its fourth straight...,صحيفة مال,https://news.google.com/rss/articles/CBMiaEFVX...,"Sat, 21 Mar 2026 07:00:00 GMT",متابعة السوق الأمريكي,إشارة سلبية محتملة
25,الدولار والفائدة,"Gold inches lower as firmer dollar, higher yie...",صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Tue, 06 Oct 2026 08:15:24 GMT",الذهب: يحتاج إلى تحليل إضافي,إشارة إيجابية محتملة
26,الدولار والفائدة,US Dollar: Fed cautious on further hikes – MUF...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 09:14:52 GMT",متابعة الدولار والفائدة,تأثير غير واضح — يحتاج تحليلًا إضافيًا
27,الدولار والفائدة,New Zealand Dollar moves sideways as US Dollar...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 03:44:55 GMT",متابعة الدولار والفائدة,تأثير غير واضح — يحتاج تحليلًا إضافيًا
28,الدولار والفائدة,Week Ahead: US PCE & NFP Keep the Fed in Focus...,tmgm.com,https://news.google.com/rss/articles/CBMingFBV...,"Mon, 28 Sep 2026 07:40:21 GMT",متابعة الدولار والفائدة,تأثير غير واضح — يحتاج تحليلًا إضافيًا
29,الدولار والفائدة,Gold slips over 2% as dollar holds firm on Fed...,صحيفة مال,https://news.google.com/rss/articles/CBMia0FVX...,"Tue, 23 Jun 2026 07:00:00 GMT",الذهب: خبر يشير إلى انخفاض السعر,إشارة سلبية محتملة

In [ ]:
# =========================================================
# 🌧️ الودق AI — فحص شامل للمشروع
# فحص فقط دون تعديل الجداول أو تشغيل المراحل السابقة
# =========================================================

import pandas as pd
import re

print("🌧️ الودق AI — تقرير فحص المشروع")
print("=" * 65)

# 1. فحص الجداول الموجودة في الذاكرة
print("\n📊 أولاً: الجداول الموجودة في الذاكرة")
print("-" * 65)

tables_found = 0

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        tables_found += 1
        print(f"✅ الجدول: {name}")
        print(f"   الصفوف: {len(obj)}")
        print(f"   الأعمدة: {len(obj.columns)}")
        print(f"   أسماء الأعمدة: {list(obj.columns)}")
        print("-" * 40)

if tables_found == 0:
    print("⚠️ لا توجد جداول DataFrame في الذاكرة الحالية.")

print(f"\nإجمالي الجداول الموجودة في الذاكرة: {tables_found}")

# 2. فحص متغيرات مشروع الودق المهمة
print("\n🔎 ثانياً: فحص الجداول المطلوبة للمشروع")
print("-" * 65)

important_tables = [
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_global_news_analysis_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v3_df",
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_stage41_decision_df",
    "wadq_final_ai_report",
    "us_technical_df",
    "wadq_ticker_news_df",
    "wadq_impact_news_df",
    "wadq_global_news_df"
]

for name in important_tables:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name}: موجود ({len(obj)} صف، {len(obj.columns)} عمود)")
    else:
        print(f"⚠️ {name}: غير موجود في الذاكرة الحالية")

# 3. فحص سجل تنفيذ الخلايا إن كان متاحاً
print("\n🧩 ثالثاً: فحص سجل الخلايا")
print("-" * 65)

ip = globals().get("In")

if isinstance(ip, list) and ip:
    stages = []

    for index, code in enumerate(ip):
        if isinstance(code, str):
            matches = re.findall(
                r"المرحلة\s*(\d+)",
                code
            )

            for stage in matches:
                stages.append((int(stage), index))

    if stages:
        unique_stages = sorted(set(stage for stage, _ in stages))
        print("أرقام المراحل الموجودة في سجل الخلايا:")
        print(unique_stages)
        print("أعلى رقم مرحلة في سجل الخلايا:", max(unique_stages))
    else:
        print("لم يتم العثور على أرقام مراحل في سجل الخلايا.")
else:
    print("سجل الخلايا غير متاح في الذاكرة الحالية.")

print("\n" + "=" * 65)
print("✅ انتهى الفحص دون تعديل أي جدول.")
print("⚠️ الفحص يعرض الذاكرة الحالية فقط، وليس جميع ملفات Google Drive.")

🌧️ الودق AI — تقرير فحص المشروع
=================================================================

📊 أولاً: الجداول الموجودة في الذاكرة
-----------------------------------------------------------------
✅ الجدول: data
   الصفوف: 5
   الأعمدة: 5
   أسماء الأعمدة: [('Close', 'ETH-USD'), ('High', 'ETH-USD'), ('Low', 'ETH-USD'), ('Open', 'ETH-USD'), ('Volume', 'ETH-USD')]
----------------------------------------
✅ الجدول: wadq_global_market_df
   الصفوف: 17
   الأعمدة: 6
   أسماء الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']
----------------------------------------

إجمالي الجداول الموجودة في الذاكرة: 2

🔎 ثانياً: فحص الجداول المطلوبة للمشروع
-----------------------------------------------------------------
✅ wadq_global_market_df: موجود (17 صف، 6 عمود)
⚠️ wadq_global_alerts_df: غير موجود في الذاكرة الحالية
⚠️ wadq_global_news_analysis_df: غير موجود في الذاكرة الحالية
⚠️ wadq_global_master_report_df: غير موجود في الذاكرة الحالية
⚠️ wadq_global_master_report_v3_df: غير موجود في الذاكرة الحالية
⚠️ wadq_global_us_unified_df: غير موجود في الذاكرة الحالية
⚠️ wadq_executive_summary_df: غير موجود في الذاكرة الحالية
⚠️ wadq_stage41_decision_df: غير موجود في الذاكرة الحالية
⚠️ wadq_final_ai_report: غير موجود في الذاكرة الحالية
⚠️ us_technical_df: غير موجود في الذاكرة الحالية
⚠️ wadq_ticker_news_df: غير موجود في الذاكرة الحالية
⚠️ wadq_impact_news_df: غير موجود في الذاكرة الحالية
⚠️ wadq_global_news_df: غير موجود في الذاكرة الحالية

🧩 ثالثاً: فحص سجل الخلايا
-----------------------------------------------------------------
أرقام المراحل الموجودة في سجل الخلايا:
[14, 40, 41, 42]
أعلى رقم مرحلة في سجل الخلايا: 42

=================================================================
✅ انتهى الفحص دون تعديل أي جدول.
⚠️ الفحص يعرض الذاكرة الحالية فقط، وليس جميع ملفات Google Drive.

In [ ]:
# 🌧️ الودق AI — البحث عن ملفات البيانات المحفوظة
import os

print("🌧️ البحث عن ملفات بيانات مشروع الودق")
print("=" * 55)

folders = ["/content", "/content/drive/MyDrive"]

for folder in folders:
    print(f"\n📁 المجلد: {folder}")

    if not os.path.exists(folder):
        print("⚠️ المجلد غير متاح حاليًا")
        continue

    found = 0

    for root, dirs, files in os.walk(folder):
        dirs[:] = [
            d for d in dirs
            if d not in [".config", "node_modules"]
        ]

        for filename in files:
            if filename.lower().endswith(
                (".csv", ".xlsx", ".xls", ".parquet", ".pkl")
            ):
                print(os.path.join(root, filename))
                found += 1

        if root.count(os.sep) - folder.count(os.sep) >= 4:
            dirs[:] = []

    if found == 0:
        print("لم يُعثر على ملفات بيانات بهذه الامتدادات.")

print("\n✅ انتهى البحث دون حذف أو تعديل أي ملف.")

🌧️ البحث عن ملفات بيانات مشروع الودق
=======================================================

📁 المجلد: /content
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_train.csv
/content/sample_data/california_housing_test.csv
/content/sample_data/mnist_test.csv

📁 المجلد: /content/drive/MyDrive
⚠️ المجلد غير متاح حاليًا

✅ انتهى البحث دون حذف أو تعديل أي ملف.

In [ ]:
# 🌧️ الودق AI — المرحلة 40
# التحقق من اتصال Google Drive

from google.colab import drive
import os

print("🌧️ الودق AI — فحص اتصال Google Drive")
print("=" * 50)

try:
    drive.mount('/content/drive')

    drive_path = "/content/drive/MyDrive"

    if os.path.exists(drive_path):
        print("✅ تم الاتصال بـ Google Drive بنجاح.")

        print("\n📁 المجلدات والملفات الموجودة في بداية Drive:")

        items = os.listdir(drive_path)

        for item in items[:30]:
            print("📄", item)

        print("\n✅ انتهى الفحص دون حذف أو تعديل أي ملف.")

    else:
        print("⚠️ لم يتم العثور على مجلد MyDrive.")

except Exception as e:
    print("⚠️ تعذر إكمال الفحص:", str(e))

🌧️ الودق AI — فحص اتصال Google Drive
==================================================
⚠️ تعذر إكمال الفحص: Error: credential propagation was unsuccessful

In [ ]:
# 🌧️ الوَدْق AI — تحليل الأخبار وربطها بالأسواق

import pandas as pd

# استخدام جدول الأخبار الموجود
if "news_source" in globals() and isinstance(news_source, pd.DataFrame):

    df = news_source.copy()

    # البحث عن عمود عنوان الخبر
    title_options = [
        "title", "Title", "العنوان",
        "عنوان الخبر", "headline", "الخبر"
    ]

    title_col = next(
        (c for c in title_options if c in df.columns),
        None
    )

    # البحث عن عمود تصنيف السوق
    category_options = [
        "category", "السوق", "التصنيف",
        "market", "السوق المرتبط"
    ]

    category_col = next(
        (c for c in category_options if c in df.columns),
        None
    )

    if title_col is not None:

        def analyze_market_news(row):
            title = str(row[title_col]).lower()

            category = (
                str(row[category_col]).lower()
                if category_col else ""
            )

            text = title + " " + category

            # الذهب
            if any(x in text for x in [
                "gold", "الذهب"
            ]):
                asset = "الذهب"

            # النفط
            elif any(x in text for x in [
                "oil", "crude", "brent", "النفط"
            ]):
                asset = "النفط"

            # السوق السعودي
            elif any(x in text for x in [
                "tadawul", "saudi stock",
                "السوق السعودي", "تاسي"
            ]):
                asset = "السوق السعودي"

            # السوق الأمريكي
            elif any(x in text for x in [
                "s&p 500", "nasdaq", "dow jones",
                "wall street", "السوق الأمريكي"
            ]):
                asset = "السوق الأمريكي"

            else:
                asset = "أصول أخرى أو خبر عام"

            # إشارة أولية من عنوان الخبر
            positive = [
                "rises", "rise", "surge", "gains",
                "ارتفاع", "يرتفع", "صعود"
            ]

            negative = [
                "falls", "fall", "fell", "drops",
                "slips", "decline", "انخفاض",
                "تراجع", "هبوط"
            ]

            if any(x in title for x in positive):
                signal = "إيجابية محتملة"

            elif any(x in title for x in negative):
                signal = "سلبية محتملة"

            else:
                signal = "غير واضحة"

            return pd.Series([asset, signal])

        df[["الأصل المرتبط", "الإشارة الأولية"]] = (
            df.apply(analyze_market_news, axis=1)
        )

        print("🌧️ تقرير الوَدْق AI — تحليل الأخبار")
        display(df)

    else:
        print("أسماء الأعمدة الموجودة:")
        print(list(df.columns))
        print("أرسلي لي صورة أسماء الأعمدة.")

else:
    print("جدول news_source غير موجود. أرسلي لي صورة خلية جمع الأخبار.")

🌧️ تقرير الوَدْق AI — تحليل الأخبار

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي,تحليل الخبر,الأصل المرتبط,الإشارة الأولية
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
3,الأخبار العالمية,مايسترو الأرقام يرحل بعد قرن من التأثير العالم...,عكاظ,https://news.google.com/rss/articles/CBMiVEFVX...,"Fri, 26 Jun 2026 07:00:00 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
4,الأخبار العالمية,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT",أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
5,الذهب,اسعار الذهب في خطر الأسواق الصينية تغلق أبوابه...,YouTube,https://news.google.com/rss/articles/CBMiXEFVX...,"Mon, 05 Oct 2026 16:43:12 GMT",الذهب: يحتاج إلى تحليل إضافي,إشارة إيجابية محتملة,الذهب,إيجابية محتملة
6,الذهب,Gold prices in Jordan drop by 40 piasters per ...,خبرني - ننقل لك أخبار الأردن والعالم بموثوقية ...,https://news.google.com/rss/articles/CBMikAFBV...,"Thu, 08 Oct 2026 06:23:58 GMT",الذهب: يحتاج إلى تحليل إضافي,إشارة سلبية محتملة,الذهب,غير واضحة
7,الذهب,Gold rally takes a breather ahead of US inflat...,صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Wed, 26 Aug 2026 07:00:00 GMT",الذهب: خبر يشير إلى ارتفاع السعر,تأثير غير واضح — يحتاج تحليلًا إضافيًا,الذهب,غير واضحة
8,الذهب,سعر الذهب في الهند اليوم: ارتفاع الذهب، وفقًا ...,tmgm.com,https://news.google.com/rss/articles/CBMixAFBV...,"Fri, 02 Oct 2026 05:00:33 GMT",الذهب: خبر يشير إلى ارتفاع السعر,إشارة إيجابية محتملة,الذهب,إيجابية محتملة
9,الذهب,https://www.markets.com/ar/news/bitcoin-btc-us...,Markets.com,https://news.google.com/rss/articles/CBMimwFBV...,"Wed, 23 Sep 2026 16:02:32 GMT",الذهب: يحتاج إلى تحليل إضافي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,الذهب,غير واضحة
10,النفط,UAE Fuel Price Increase September 2026 - سعودي...,سعودي اوتو,https://news.google.com/rss/articles/CBMia0FVX...,"Mon, 05 Oct 2026 00:15:53 GMT",متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
11,النفط,Oil: Prices supported by supply risks and Iran...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 07:07:50 GMT",متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
12,النفط,Oil prices fell as markets awaited development...,صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Wed, 27 May 2026 07:00:00 GMT",متابعة النفط,إشارة سلبية محتملة,النفط,سلبية محتملة
13,النفط,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT",متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
14,النفط,First Light News: Oil continues to dominate se...,المتداول العربي,https://news.google.com/rss/articles/CBMi5AFBV...,"Tue, 17 Mar 2026 07:00:00 GMT",متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
15,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Thu, 08 Oct 2026 12:48:54 GMT",متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
16,السوق السعودي,13 private deals executed in the Saudi stock m...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Tue, 06 Oct 2026 13:27:11 GMT",متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
17,السوق السعودي,الأسهم السعودية تتراجع باليوم الأول لفتح السوق...,الجزيرة نت,https://news.google.com/rss/articles/CBMihAFBV...,"Sun, 01 Feb 2026 08:00:00 GMT",متابعة السوق السعودي,إشارة سلبية محتملة,السوق السعودي,سلبية محتملة
18,السوق السعودي,12 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Mon, 05 Oct 2026 13:04:53 GMT",متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
19,السوق السعودي,13 Private Deals Executed on the Saudi Stock E...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,"Wed, 07 Oct 2026 13:27:17 GMT",متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
20,السوق الأمريكي,Global stocks mostly fall as oil prices and bo...,AFP.com,https://news.google.com/rss/articles/CBMiS0FVX...,"Thu, 24 Sep 2026 08:51:20 GMT",متابعة السوق الأمريكي,إشارة إيجابية محتملة,النفط,إيجابية محتملة
21,السوق الأمريكي,Dow Jones futures rise due to easing Fed rate ...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Tue, 06 Oct 2026 08:39:59 GMT",متابعة السوق الأمريكي,إشارة إيجابية محتملة,السوق الأمريكي,إيجابية محتملة
22,السوق الأمريكي,تداول مؤشرات VT Markets | S&P 500 | NASDAQ | F...,VT Markets,https://news.google.com/rss/articles/CBMiVEFVX...,"Tue, 23 Jun 2026 02:14:55 GMT",متابعة السوق الأمريكي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق الأمريكي,غير واضحة
23,السوق الأمريكي,Week Ahead: US PCE & NFP Keep the Fed in Focus...,tmgm.com,https://news.google.com/rss/articles/CBMingFBV...,"Mon, 28 Sep 2026 07:40:21 GMT",متابعة السوق الأمريكي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق الأمريكي,غير واضحة
24,السوق الأمريكي,S&P 500 fell 1.5% to close its fourth straight...,صحيفة مال,https://news.google.com/rss/articles/CBMiaEFVX...,"Sat, 21 Mar 2026 07:00:00 GMT",متابعة السوق الأمريكي,إشارة سلبية محتملة,السوق الأمريكي,سلبية محتملة
25,الدولار والفائدة,"Gold inches lower as firmer dollar, higher yie...",صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,"Tue, 06 Oct 2026 08:15:24 GMT",الذهب: يحتاج إلى تحليل إضافي,إشارة إيجابية محتملة,الذهب,غير واضحة
26,الدولار والفائدة,US Dollar: Fed cautious on further hikes – MUF...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 09:14:52 GMT",متابعة الدولار والفائدة,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
27,الدولار والفائدة,New Zealand Dollar moves sideways as US Dollar...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Thu, 08 Oct 2026 03:44:55 GMT",متابعة الدولار والفائدة,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
28,الدولار والفائدة,Week Ahead: US PCE & NFP Keep the Fed in Focus...,tmgm.com,https://news.google.com/rss/articles/CBMingFBV...,"Mon, 28 Sep 2026 07:40:21 GMT",متابعة الدولار والفائدة,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
29,الدولار والفائدة,Gold slips over 2% as dollar holds firm on Fed...,صحيفة مال,https://news.google.com/rss/articles/CBMia0FVX...,"Tue, 23 Jun 2026 07:00:00 GMT",الذهب: خبر يشير إلى انخفاض السعر,إشارة سلبية محتملة,الذهب,سلبية محتملة

In [ ]:
# 🌧️ الوَدْق AI — فلترة الأخبار الحديثة

import pandas as pd

# البحث عن جدول الأخبار المحلل
if "df" in globals() and isinstance(df, pd.DataFrame):

    recent_news = df.copy()

    # اكتشاف عمود التاريخ
    date_options = [
        "published", "published_at", "date",
        "التاريخ", "تاريخ الخبر", "published date"
    ]

    date_col = next(
        (c for c in date_options if c in recent_news.columns),
        None
    )

    if date_col:

        recent_news[date_col] = pd.to_datetime(
            recent_news[date_col],
            errors="coerce",
            utc=True
        )

        now = pd.Timestamp.now(tz="UTC")

        # عرض الأخبار المنشورة خلال آخر 7 أيام
        cutoff = now - pd.Timedelta(days=7)

        fresh_news = recent_news[
            (recent_news[date_col] >= cutoff) &
            (recent_news[date_col] <= now)
        ].copy()

        print("🌧️ تقرير الأخبار الحديثة — آخر 7 أيام")
        print("عدد الأخبار الحديثة:", len(fresh_news))

        display(fresh_news)

        if fresh_news.empty:
            print(
                "لم نجد أخبارًا خلال آخر 7 أيام. "
                "تحققي من تواريخ الأخبار ومصدرها."
            )

    else:
        print("لم أجد عمود التاريخ.")
        print("أسماء الأعمدة:", list(recent_news.columns))

else:
    print("جدول التحليل غير موجود. أرسلي صورة الخلية السابقة.")

لم أجد عمود التاريخ.
أسماء الأعمدة: ['التصنيف', 'العنوان', 'المصدر', 'الرابط', 'تاريخ النشر', 'التحليل الأولي', 'تحليل الخبر', 'الأصل المرتبط', 'الإشارة الأولية']

In [ ]:
# 🌧️ الوَدْق AI — فلترة الأخبار الحديثة

import pandas as pd

# البحث عن جدول الأخبار المحلل
if "df" in globals() and isinstance(df, pd.DataFrame):

    recent_news = df.copy()

    # اسم عمود التاريخ الصحيح
    date_col = "تاريخ النشر"

    if date_col in recent_news.columns:

        recent_news[date_col] = pd.to_datetime(
            recent_news[date_col],
            errors="coerce",
            utc=True
        )

        now = pd.Timestamp.now(tz="UTC")
        cutoff = now - pd.Timedelta(days=7)

        fresh_news = recent_news[
            (recent_news[date_col] >= cutoff) &
            (recent_news[date_col] <= now)
        ].copy()

        print("🌧️ الوَدْق AI — الأخبار خلال آخر 7 أيام")
        print("عدد الأخبار الحديثة:", len(fresh_news))

        display(fresh_news)

        if fresh_news.empty:
            print(
                "لم نجد أخبارًا حديثة خلال آخر 7 أيام. "
                "تحققي من تواريخ النشر."
            )

    else:
        print("لم أجد عمود تاريخ النشر.")
        print("الأعمدة المتاحة:", list(recent_news.columns))

else:
    print("جدول الأخبار غير موجود. أعيدي تشغيل خلية تحليل الأخبار أولًا.")

🌧️ الوَدْق AI — الأخبار خلال آخر 7 أيام
عدد الأخبار الحديثة: 15

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي,تحليل الخبر,الأصل المرتبط,الإشارة الأولية
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,2026-10-09 13:14:13+00:00,أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-09 08:32:38+00:00,أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,2026-10-06 00:25:50+00:00,أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
5,الذهب,اسعار الذهب في خطر الأسواق الصينية تغلق أبوابه...,YouTube,https://news.google.com/rss/articles/CBMiXEFVX...,2026-10-05 16:43:12+00:00,الذهب: يحتاج إلى تحليل إضافي,إشارة إيجابية محتملة,الذهب,إيجابية محتملة
6,الذهب,Gold prices in Jordan drop by 40 piasters per ...,خبرني - ننقل لك أخبار الأردن والعالم بموثوقية ...,https://news.google.com/rss/articles/CBMikAFBV...,2026-10-08 06:23:58+00:00,الذهب: يحتاج إلى تحليل إضافي,إشارة سلبية محتملة,الذهب,غير واضحة
10,النفط,UAE Fuel Price Increase September 2026 - سعودي...,سعودي اوتو,https://news.google.com/rss/articles/CBMia0FVX...,2026-10-05 00:15:53+00:00,متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
11,النفط,Oil: Prices supported by supply risks and Iran...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-08 07:07:50+00:00,متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
15,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-08 12:48:54+00:00,متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
16,السوق السعودي,13 private deals executed in the Saudi stock m...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-06 13:27:11+00:00,متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
18,السوق السعودي,12 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-05 13:04:53+00:00,متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
19,السوق السعودي,13 Private Deals Executed on the Saudi Stock E...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-07 13:27:17+00:00,متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
21,السوق الأمريكي,Dow Jones futures rise due to easing Fed rate ...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-06 08:39:59+00:00,متابعة السوق الأمريكي,إشارة إيجابية محتملة,السوق الأمريكي,إيجابية محتملة
25,الدولار والفائدة,"Gold inches lower as firmer dollar, higher yie...",صحيفة مال,https://news.google.com/rss/articles/CBMibEFVX...,2026-10-06 08:15:24+00:00,الذهب: يحتاج إلى تحليل إضافي,إشارة إيجابية محتملة,الذهب,غير واضحة
26,الدولار والفائدة,US Dollar: Fed cautious on further hikes – MUF...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-08 09:14:52+00:00,متابعة الدولار والفائدة,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
27,الدولار والفائدة,New Zealand Dollar moves sideways as US Dollar...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-08 03:44:55+00:00,متابعة الدولار والفائدة,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة

In [ ]:
# ==========================================
# 🌧️ الوَدْق AI — التقرير الموحد للأسواق
# ==========================================

import pandas as pd
from IPython.display import display, Markdown

print("🌧️ الوَدْق AI")
print("📊 التقرير الموحد للأسواق والأخبار")
print("=" * 45)

# أولًا: ملخص الأخبار الحديثة
if "fresh_news" in globals() and isinstance(fresh_news, pd.DataFrame):

    print("\n📰 الأخبار الحديثة")

    print("عدد الأخبار:", len(fresh_news))

    # عرض أهم الأخبار الحديثة
    title_columns = [
        "العنوان", "title", "Title",
        "عنوان الخبر", "headline"
    ]

    title_col = next(
        (c for c in title_columns if c in fresh_news.columns),
        None
    )

    if title_col:
        display(fresh_news.head(10))

    else:
        print("الأعمدة المتاحة:", list(fresh_news.columns))

else:
    print("\nلا يوجد جدول للأخبار الحديثة في الذاكرة.")

# ثانيًا: ملخص بيانات السوق
print("\n" + "=" * 45)
print("📈 بيانات الأسواق")

market_found = False

for variable in [
    "market_df",
    "wadq_dashboard",
    "price_df",
    "technical_df",
    "support_df"
]:
    if variable in globals():
        obj = globals()[variable]

        if isinstance(obj, pd.DataFrame) and not obj.empty:
            print(f"\nجدول البيانات: {variable}")
            display(obj.head(10))
            market_found = True

if not market_found:
    print("لم نعثر على جداول السوق بالأسماء المتوقعة.")

print("\n" + "=" * 45)
print("🌧️ انتهى التقرير.")
print("ملاحظة: البيانات المعروضة ليست توصية شراء أو بيع.")

🌧️ الوَدْق AI
📊 التقرير الموحد للأسواق والأخبار
=============================================

📰 الأخبار الحديثة
عدد الأخبار: 15

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي,تحليل الخبر,الأصل المرتبط,الإشارة الأولية
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,2026-10-09 13:14:13+00:00,أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-09 08:32:38+00:00,أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,2026-10-06 00:25:50+00:00,أخبار عالمية,تأثير غير واضح — يحتاج تحليلًا إضافيًا,أصول أخرى أو خبر عام,غير واضحة
5,الذهب,اسعار الذهب في خطر الأسواق الصينية تغلق أبوابه...,YouTube,https://news.google.com/rss/articles/CBMiXEFVX...,2026-10-05 16:43:12+00:00,الذهب: يحتاج إلى تحليل إضافي,إشارة إيجابية محتملة,الذهب,إيجابية محتملة
6,الذهب,Gold prices in Jordan drop by 40 piasters per ...,خبرني - ننقل لك أخبار الأردن والعالم بموثوقية ...,https://news.google.com/rss/articles/CBMikAFBV...,2026-10-08 06:23:58+00:00,الذهب: يحتاج إلى تحليل إضافي,إشارة سلبية محتملة,الذهب,غير واضحة
10,النفط,UAE Fuel Price Increase September 2026 - سعودي...,سعودي اوتو,https://news.google.com/rss/articles/CBMia0FVX...,2026-10-05 00:15:53+00:00,متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
11,النفط,Oil: Prices supported by supply risks and Iran...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-08 07:07:50+00:00,متابعة النفط,تأثير غير واضح — يحتاج تحليلًا إضافيًا,النفط,غير واضحة
15,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-08 12:48:54+00:00,متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
16,السوق السعودي,13 private deals executed in the Saudi stock m...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-06 13:27:11+00:00,متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة
18,السوق السعودي,12 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-05 13:04:53+00:00,متابعة السوق السعودي,تأثير غير واضح — يحتاج تحليلًا إضافيًا,السوق السعودي,غير واضحة

=============================================
📈 بيانات الأسواق

جدول البيانات: market_df

              السوق  آخر سعر إغلاق متاح  التغير %    الحركة
0             الذهب            4216.300      1.43  🟢 ارتفاع
1             الفضة              60.670      2.72  🟢 ارتفاع
2             النفط              91.850      0.39  🟢 ارتفاع
3      مؤشر S&P 500            7811.540      0.59  🟢 ارتفاع
4       مؤشر ناسداك           27366.170      0.64  🟢 ارتفاع
5     مؤشر داو جونز           51654.949      0.83  🟢 ارتفاع
6  الدولار الأمريكي             102.210      0.07  🟢 ارتفاع

جدول البيانات: wadq_dashboard

              الأصل    آخر سعر  التغير % الحركة السابقة
0             الذهب   4216.300      1.43       🟢 ارتفاع
1             الفضة     60.670      2.72       🟢 ارتفاع
2             النفط     91.850      0.39       🟢 ارتفاع
3      مؤشر S&P 500   7811.540      0.59       🟢 ارتفاع
4       مؤشر ناسداك  27366.170      0.64       🟢 ارتفاع
5     مؤشر داو جونز  51654.949      0.83       🟢 ارتفاع
6  الدولار الأمريكي    102.210      0.07       🟢 ارتفاع
7      مصرف الراجحي     62.300     -1.42       🔴 انخفاض
8   أرامكو السعودية     25.740     -0.39       🔴 انخفاض
9             معادن     62.400     -0.95       🔴 انخفاض

جدول البيانات: price_df

             الأصل  آخر إغلاق متاح  الإغلاق السابق  التغير %    الحركة
0            الذهب         4216.30        4157.000      1.43  🟢 ارتفاع
1            الفضة           60.67          59.064      2.72  🟢 ارتفاع
2            النفط           91.85          91.490      0.39  🟢 ارتفاع
3     مصرف الراجحي           62.30          63.200     -1.42  🔴 انخفاض
4  أرامكو السعودية           25.74          25.840     -0.39  🔴 انخفاض
5            معادن           62.40          63.000     -0.95  🔴 انخفاض
6             سابك           45.80          46.560     -1.63  🔴 انخفاض
7        أكوا باور          164.90         171.100     -3.62  🔴 انخفاض

جدول البيانات: technical_df

,السهم,آخر إغلاق,RSI,إشارة RSI,المتوسط 20,المتوسط 50,قراءة الاتجاه
0,مصرف الراجحي,62.30,39.27,زخم متوسط,63.99,64.22,اتجاه هابط وفق الشروط
1,أرامكو السعودية,25.74,50.07,زخم متوسط,25.63,25.99,اتجاه مختلط
2,معادن,62.40,46.39,زخم متوسط,62.56,63.98,اتجاه هابط وفق الشروط
3,سابك,45.80,32.09,زخم متوسط,47.41,48.79,اتجاه هابط وفق الشروط
4,أكوا باور,164.90,36.31,زخم متوسط,173.85,183.65,اتجاه هابط وفق الشروط

جدول البيانات: support_df

             الأصل  آخر إغلاق متاح  الدعم التقريبي  المقاومة التقريبية
0            الذهب         4216.30        4091.200            4439.800
1            الفضة           60.67          58.915              66.940
2            النفط           91.85          86.860             106.750
3     مصرف الراجحي           62.30          62.150              65.771
4  أرامكو السعودية           25.74          25.120              26.180
5            معادن           62.40          59.850              66.900
6             سابك           45.80          45.700              50.050
7        أكوا باور          164.90         161.500             191.900

=============================================
🌧️ انتهى التقرير.
ملاحظة: البيانات المعروضة ليست توصية شراء أو بيع.

In [ ]:
import pandas as pd
from IPython.display import display

print("🌧️ الوَدْق AI — محلل الأسواق الذكي")
print("=" * 50)

if "support_df" in globals() and not support_df.empty:

    df = support_df.copy()

    # عرض أسماء الأعمدة للتأكد من البيانات
    print("أعمدة البيانات:", list(df.columns))

    # تحويل الأعمدة الرقمية إلى أرقام
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="ignore")

    # تحليل البيانات إذا كانت تحتوي على:
    # الأصل، سعر الإغلاق، الدعم، المقاومة
    if len(df.columns) >= 4:

        asset_col = df.columns[0]
        numeric_cols = [
            c for c in df.columns[1:]
            if pd.api.types.is_numeric_dtype(df[c])
        ]

        if len(numeric_cols) >= 3:

            close_col = numeric_cols[0]
            support_col = numeric_cols[1]
            resistance_col = numeric_cols[2]

            results = []

            for _, row in df.iterrows():

                asset = row[asset_col]
                price = row[close_col]
                support = row[support_col]
                resistance = row[resistance_col]

                if pd.isna(price) or pd.isna(support) or pd.isna(resistance):
                    continue

                if price <= support:
                    signal = "قرب الدعم أو دونه"
                elif price >= resistance:
                    signal = "قرب المقاومة أو فوقها"
                else:
                    signal = "بين الدعم والمقاومة"

                results.append({
                    "الأصل": asset,
                    "السعر": price,
                    "الدعم": support,
                    "المقاومة": resistance,
                    "القراءة الأولية": signal
                })

            display(pd.DataFrame(results))

        else:
            print("نحتاج إلى ثلاثة أعمدة رقمية على الأقل للتحليل.")

    else:
        print("نحتاج إلى مراجعة أعمدة جدول الدعم والمقاومة.")

else:
    print("جدول الدعم غير موجود. شغّلي خلية تحديث بيانات السوق أولًا.")

print("\nتنبيه: هذه قراءة أولية وليست توصية شراء أو بيع.")

🌧️ الوَدْق AI — محلل الأسواق الذكي
==================================================
أعمدة البيانات: ['الأصل', 'آخر إغلاق متاح', 'الدعم التقريبي', 'المقاومة التقريبية']

/tmp/ipykernel_2488/2648172538.py:16: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

             الأصل    السعر     الدعم  المقاومة      القراءة الأولية
0            الذهب  4216.30  4091.200  4439.800  بين الدعم والمقاومة
1            الفضة    60.67    58.915    66.940  بين الدعم والمقاومة
2            النفط    91.85    86.860   106.750  بين الدعم والمقاومة
3     مصرف الراجحي    62.30    62.150    65.771  بين الدعم والمقاومة
4  أرامكو السعودية    25.74    25.120    26.180  بين الدعم والمقاومة
5            معادن    62.40    59.850    66.900  بين الدعم والمقاومة
6             سابك    45.80    45.700    50.050  بين الدعم والمقاومة
7        أكوا باور   164.90   161.500   191.900  بين الدعم والمقاومة

تنبيه: هذه قراءة أولية وليست توصية شراء أو بيع.

In [ ]:
# 🌧️ الوَدْق AI — مركز التحليل الفني

import yfinance as yf
import pandas as pd
from IPython.display import display

print("🌧️ الوَدْق AI")
print("=" * 45)

symbols = {
    "الذهب": "GC=F",
    "الفضة": "SI=F",
    "النفط": "CL=F",
    "أرامكو": "2222.SR",
    "مصرف الراجحي": "1120.SR",
    "سابك": "2010.SR",
    "معادن": "1211.SR",
    "أكوا باور": "2082.SR",
    "S&P 500": "^GSPC",
    "ناسداك": "^IXIC"
}

results = []

for name, symbol in symbols.items():
    try:
        data = yf.download(
            symbol,
            period="3mo",
            interval="1d",
            progress=False,
            auto_adjust=True
        )

        if data.empty or len(data) < 20:
            print(f"لم تتوفر بيانات كافية: {name}")
            continue

        close = data["Close"]

        if isinstance(close, pd.DataFrame):
            close = close.iloc[:, 0]

        price = float(close.iloc[-1])
        ma20 = float(close.rolling(20).mean().iloc[-1])
        ma50 = float(close.rolling(50).mean().iloc[-1]) if len(close) >= 50 else None

        delta = close.diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.rolling(14).mean()
        avg_loss = loss.rolling(14).mean()

        rs = avg_gain / avg_loss.replace(0, float("nan"))
        rsi = float((100 - (100 / (1 + rs))).iloc[-1])

        if price > ma20 and (ma50 is None or price > ma50):
            trend = "اتجاه صاعد مبدئي"
        elif price < ma20 and (ma50 is None or price < ma50):
            trend = "اتجاه هابط مبدئي"
        else:
            trend = "اتجاه مختلط"

        results.append({
            "الأصل": name,
            "السعر الأخير": round(price, 3),
            "المتوسط 20 يوم": round(ma20, 3),
            "المتوسط 50 يوم": round(ma50, 3) if ma50 is not None else None,
            "RSI": round(rsi, 2) if pd.notna(rsi) else None,
            "الاتجاه المبدئي": trend
        })

    except Exception as e:
        print(f"تعذر تحليل {name}: {e}")

if results:
    analysis_df = pd.DataFrame(results)
    display(analysis_df)
else:
    print("لم تصل بيانات الأسعار. تحققي من الاتصال بالإنترنت.")

print("\nتنبيه: التحليل الفني تقديري وليس توصية شراء أو بيع.")

🌧️ الوَدْق AI
=============================================

,الأصل,السعر الأخير,المتوسط 20 يوم,المتوسط 50 يوم,RSI,الاتجاه المبدئي
0,الذهب,4216.30,4267.600,4376.972,33.02,اتجاه هابط مبدئي
1,الفضة,60.67,62.563,64.106,31.31,اتجاه هابط مبدئي
2,النفط,91.85,94.414,89.201,41.58,اتجاه مختلط
3,أرامكو,25.74,25.634,25.985,54.13,اتجاه مختلط
4,مصرف الراجحي,62.30,63.994,64.223,37.06,اتجاه هابط مبدئي
5,سابك,45.80,47.406,48.791,32.37,اتجاه هابط مبدئي
6,معادن,62.40,62.558,63.981,51.98,اتجاه هابط مبدئي
7,أكوا باور,164.90,173.850,183.654,34.37,اتجاه هابط مبدئي
8,S&P 500,7811.54,7704.774,7696.919,55.10,اتجاه صاعد مبدئي
9,ناسداك,27366.17,26905.724,26562.979,55.51,اتجاه صاعد مبدئي

تنبيه: التحليل الفني تقديري وليس توصية شراء أو بيع.

In [ ]:
# 🌧️ الوَدْق AI — نظام تقييم الإشارات الفنية

import pandas as pd
from IPython.display import display

print("🌧️ الوَدْق AI | تقييم الأصول والأسواق")
print("=" * 55)

if "analysis_df" not in globals() or analysis_df.empty:
    print("لا توجد بيانات تحليل. شغّلي خلية التحليل الفني أولًا.")

else:
    ranked_df = analysis_df.copy()

    # تحويل الأعمدة الرقمية
    for col in [
        "السعر الأخير",
        "المتوسط 20 يوم",
        "المتوسط 50 يوم",
        "RSI"
    ]:
        if col in ranked_df.columns:
            ranked_df[col] = pd.to_numeric(
                ranked_df[col], errors="coerce"
            )

    scores = []
    explanations = []

    for _, row in ranked_df.iterrows():
        score = 0
        reasons = []

        price = row.get("السعر الأخير")
        ma20 = row.get("المتوسط 20 يوم")
        ma50 = row.get("المتوسط 50 يوم")
        rsi = row.get("RSI")

        # السعر مقارنة بالمتوسط المتحرك 20 يومًا
        if pd.notna(price) and pd.notna(ma20):
            if price > ma20:
                score += 1
                reasons.append("السعر فوق متوسط 20 يومًا")
            elif price < ma20:
                score -= 1
                reasons.append("السعر تحت متوسط 20 يومًا")

        # السعر مقارنة بالمتوسط المتحرك 50 يومًا
        if pd.notna(price) and pd.notna(ma50):
            if price > ma50:
                score += 1
                reasons.append("السعر فوق متوسط 50 يومًا")
            elif price < ma50:
                score -= 1
                reasons.append("السعر تحت متوسط 50 يومًا")

        # تقييم RSI
        if pd.notna(rsi):
            if 50 <= rsi < 70:
                score += 1
                reasons.append("زخم إيجابي")
            elif 30 <= rsi < 50:
                score -= 1
                reasons.append("زخم ضعيف")
            elif rsi >= 70:
                reasons.append("احتمال تشبع شرائي")
            elif rsi < 30:
                reasons.append("احتمال تشبع بيعي")

        if score >= 2:
            rating = "إيجابي فنيًا"
        elif score == 1:
            rating = "إيجابي بحذر"
        elif score == 0:
            rating = "محايد"
        elif score == -1:
            rating = "سلبي بحذر"
        else:
            rating = "سلبي فنيًا"

        scores.append(score)
        explanations.append("؛ ".join(reasons) if reasons else "بيانات غير كافية")

    ranked_df["النقاط الفنية"] = scores
    ranked_df["التقييم"] = [
        "إيجابي فنيًا" if s >= 2 else
        "إيجابي بحذر" if s == 1 else
        "محايد" if s == 0 else
        "سلبي بحذر" if s == -1 else
        "سلبي فنيًا"
        for s in scores
    ]
    ranked_df["أسباب التقييم"] = explanations

    ranked_df = ranked_df.sort_values(
        "النقاط الفنية", ascending=False
    )

    display(ranked_df)

    print("\nتنبيه:")
    print("هذا ترتيب فني أولي، وليس توصية شراء أو بيع.")
    print("لا يعتمد على الأخبار أو السيولة أو إدارة المخاطر.")

🌧️ الوَدْق AI | تقييم الأصول والأسواق
=======================================================

,الأصل,السعر الأخير,المتوسط 20 يوم,المتوسط 50 يوم,RSI,الاتجاه المبدئي,النقاط الفنية,التقييم,أسباب التقييم
9,ناسداك,27366.17,26905.724,26562.979,55.51,اتجاه صاعد مبدئي,3,إيجابي فنيًا,السعر فوق متوسط 20 يومًا؛ السعر فوق متوسط 50 ي...
8,S&P 500,7811.54,7704.774,7696.919,55.10,اتجاه صاعد مبدئي,3,إيجابي فنيًا,السعر فوق متوسط 20 يومًا؛ السعر فوق متوسط 50 ي...
3,أرامكو,25.74,25.634,25.985,54.13,اتجاه مختلط,1,إيجابي بحذر,السعر فوق متوسط 20 يومًا؛ السعر تحت متوسط 50 ي...
2,النفط,91.85,94.414,89.201,41.58,اتجاه مختلط,-1,سلبي بحذر,السعر تحت متوسط 20 يومًا؛ السعر فوق متوسط 50 ي...
6,معادن,62.40,62.558,63.981,51.98,اتجاه هابط مبدئي,-1,سلبي بحذر,السعر تحت متوسط 20 يومًا؛ السعر تحت متوسط 50 ي...
0,الذهب,4216.30,4267.600,4376.972,33.02,اتجاه هابط مبدئي,-3,سلبي فنيًا,السعر تحت متوسط 20 يومًا؛ السعر تحت متوسط 50 ي...
1,الفضة,60.67,62.563,64.106,31.31,اتجاه هابط مبدئي,-3,سلبي فنيًا,السعر تحت متوسط 20 يومًا؛ السعر تحت متوسط 50 ي...
4,مصرف الراجحي,62.30,63.994,64.223,37.06,اتجاه هابط مبدئي,-3,سلبي فنيًا,السعر تحت متوسط 20 يومًا؛ السعر تحت متوسط 50 ي...
5,سابك,45.80,47.406,48.791,32.37,اتجاه هابط مبدئي,-3,سلبي فنيًا,السعر تحت متوسط 20 يومًا؛ السعر تحت متوسط 50 ي...
7,أكوا باور,164.90,173.850,183.654,34.37,اتجاه هابط مبدئي,-3,سلبي فنيًا,السعر تحت متوسط 20 يومًا؛ السعر تحت متوسط 50 ي...

تنبيه:
هذا ترتيب فني أولي، وليس توصية شراء أو بيع.
لا يعتمد على الأخبار أو السيولة أو إدارة المخاطر.

In [ ]:
# الوَدْق AI - فحص البيانات المتوفرة
print("🌧️ الوَدْق AI")
print("=" * 40)

variables_to_check = [
    "df_news",
    "wadq_results",
    "wadq_impact_results",
    "technical_df",
    "market_df",
    "saudi_df"
]

for name in variables_to_check:
    if name in globals():
        print(f"✅ {name}: موجود")
    else:
        print(f"⚪ {name}: غير موجود")# الوَدْق AI - فحص البيانات المتوفرة
print("🌧️ الوَدْق AI")
print("=" * 40)

variables_to_check = [
    "df_news",
    "wadq_results",
    "wadq_impact_results",
    "technical_df",
    "market_df",
    "saudi_df"
]

for name in variables_to_check:
    if name in globals():
        print(f"✅ {name}: موجود")
    else:
        print(f"⚪ {name}: غير موجود")

🌧️ الوَدْق AI
========================================
✅ df_news: موجود
✅ wadq_results: موجود
✅ wadq_impact_results: موجود
✅ technical_df: موجود
✅ market_df: موجود
✅ saudi_df: موجود
🌧️ الوَدْق AI
========================================
✅ df_news: موجود
✅ wadq_results: موجود
✅ wadq_impact_results: موجود
✅ technical_df: موجود
✅ market_df: موجود
✅ saudi_df: موجود

In [ ]:
# 🌧️ الوَدْق AI - فحص بيانات الأخبار والأسواق

print("🌧️ تقرير حالة الوَدْق AI")
print("=" * 50)

dataframes = {
    "الأخبار": df_news,
    "نتائج الوَدْق": wadq_results,
    "تأثير الأخبار": wadq_impact_results,
    "المؤشرات الفنية": technical_df,
    "الأسواق العالمية": market_df,
    "الأسهم السعودية": saudi_df
}

for name, df in dataframes.items():
    print(f"\n📊 {name}")

    if df is None:
        print("لا توجد بيانات")
        continue

    print(f"عدد الصفوف: {len(df)}")
    print(f"الأعمدة: {list(df.columns)}")

    if len(df) > 0:
        display(df.head(3))
    else:
        print("الجدول فارغ")

🌧️ تقرير حالة الوَدْق AI
==================================================

📊 الأخبار
عدد الصفوف: 30
الأعمدة: ['التصنيف', 'العنوان', 'المصدر', 'الرابط', 'تاريخ النشر', 'التحليل الأولي']

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT",أخبار عالمية
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT",أخبار عالمية
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT",أخبار عالمية

📊 نتائج الوَدْق
عدد الصفوف: 30
الأعمدة: ['التصنيف', 'العنوان', 'المصدر', 'الرابط', 'تاريخ النشر', 'التحليل الأولي', 'السوق']

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي,السوق
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT",أخبار عالمية,أخبار عامة
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT",أخبار عالمية,أخبار عامة
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT",أخبار عالمية,أخبار عامة

📊 تأثير الأخبار
عدد الصفوف: 30
الأعمدة: ['التصنيف', 'العنوان', 'المصدر', 'الرابط', 'تاريخ النشر', 'التحليل الأولي', 'نبرة الخبر']

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي,نبرة الخبر
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT",أخبار عالمية,🟡 محايدة أو غير واضحة
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT",أخبار عالمية,🟡 محايدة أو غير واضحة
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT",أخبار عالمية,🟡 محايدة أو غير واضحة

📊 المؤشرات الفنية
عدد الصفوف: 5
الأعمدة: ['السهم', 'آخر إغلاق', 'RSI', 'إشارة RSI', 'المتوسط 20', 'المتوسط 50', 'قراءة الاتجاه']

,السهم,آخر إغلاق,RSI,إشارة RSI,المتوسط 20,المتوسط 50,قراءة الاتجاه
0,مصرف الراجحي,62.30,39.27,زخم متوسط,63.99,64.22,اتجاه هابط وفق الشروط
1,أرامكو السعودية,25.74,50.07,زخم متوسط,25.63,25.99,اتجاه مختلط
2,معادن,62.40,46.39,زخم متوسط,62.56,63.98,اتجاه هابط وفق الشروط

📊 الأسواق العالمية
عدد الصفوف: 7
الأعمدة: ['السوق', 'آخر سعر إغلاق متاح', 'التغير %', 'الحركة']

   السوق  آخر سعر إغلاق متاح  التغير %    الحركة
0  الذهب             4216.30      1.43  🟢 ارتفاع
1  الفضة               60.67      2.72  🟢 ارتفاع
2  النفط               91.85      0.39  🟢 ارتفاع

📊 الأسهم السعودية
عدد الصفوف: 5
الأعمدة: ['السهم أو المؤشر', 'آخر إغلاق متاح', 'التغير %', 'الاتجاه السابق']

   السهم أو المؤشر  آخر إغلاق متاح  التغير % الاتجاه السابق
0     مصرف الراجحي           62.30     -1.42       🔴 انخفاض
1  أرامكو السعودية           25.74     -0.39       🔴 انخفاض
2            معادن           62.40     -0.95       🔴 انخفاض

In [ ]:
# 🌧️ الوَدْق AI - فحص حداثة الأخبار

import pandas as pd

print("🌧️ تقرير حداثة الأخبار")
print("=" * 45)

if "df_news" in globals() and df_news is not None and len(df_news) > 0:

    print("عدد الأخبار:", len(df_news))
    print("\nأسماء الأعمدة:")
    print(list(df_news.columns))

    date_columns = [
        c for c in df_news.columns
        if any(word in str(c).lower()
               for word in ["date", "time", "published", "تاريخ", "وقت"])
    ]

    if date_columns:
        for col in date_columns:
            dates = pd.to_datetime(
                df_news[col], errors="coerce", utc=True
            )
            print(f"\n📅 العمود: {col}")
            print("أحدث تاريخ:", dates.max())
            print("أقدم تاريخ:", dates.min())
    else:
        print("\n⚠️ لم يُعثر على عمود واضح للتاريخ.")

    display(df_news.head(5))

else:
    print("⚠️ لا توجد أخبار متاحة للفحص.")

🌧️ تقرير حداثة الأخبار
=============================================
عدد الأخبار: 30

أسماء الأعمدة:
['التصنيف', 'العنوان', 'المصدر', 'الرابط', 'تاريخ النشر', 'التحليل الأولي']

📅 العمود: تاريخ النشر
أحدث تاريخ: 2026-10-09 13:14:13+00:00
أقدم تاريخ: 2026-02-01 08:00:00+00:00

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT",أخبار عالمية
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT",أخبار عالمية
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT",أخبار عالمية
3,الأخبار العالمية,مايسترو الأرقام يرحل بعد قرن من التأثير العالم...,عكاظ,https://news.google.com/rss/articles/CBMiVEFVX...,"Fri, 26 Jun 2026 07:00:00 GMT",أخبار عالمية
4,الأخبار العالمية,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT",أخبار عالمية

In [ ]:
# 🌧️ الوَدْق AI - فحص الأخبار

print("🌧️ فحص الأخبار في الوَدْق AI")
print("=" * 40)

if "df_news" in globals() and df_news is not None:
    print("عدد الأخبار:", len(df_news))
    print("أعمدة الأخبار:", list(df_news.columns))

    if len(df_news) > 0:
        display(df_news.head(5))
    else:
        print("⚠️ جدول الأخبار موجود لكنه فارغ.")
else:
    print("⚠️ بيانات الأخبار غير موجودة.")

🌧️ فحص الأخبار في الوَدْق AI
========================================
عدد الأخبار: 30
أعمدة الأخبار: ['التصنيف', 'العنوان', 'المصدر', 'الرابط', 'تاريخ النشر', 'التحليل الأولي']

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,"Fri, 09 Oct 2026 13:14:13 GMT",أخبار عالمية
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,"Fri, 09 Oct 2026 08:32:38 GMT",أخبار عالمية
2,الأخبار العالمية,تلفزيون الشرق بلومبرغ مباشر | Asharq Bloomberg...,Unisba Media,https://news.google.com/rss/articles/CBMiZkFVX...,"Tue, 06 Oct 2026 00:25:50 GMT",أخبار عالمية
3,الأخبار العالمية,مايسترو الأرقام يرحل بعد قرن من التأثير العالم...,عكاظ,https://news.google.com/rss/articles/CBMiVEFVX...,"Fri, 26 Jun 2026 07:00:00 GMT",أخبار عالمية
4,الأخبار العالمية,Oil: Strait of Hormuz reopening steadies crude...,tmgm.com,https://news.google.com/rss/articles/CBMivwFBV...,"Fri, 19 Jun 2026 07:00:00 GMT",أخبار عالمية

In [ ]:
# 🌧️ الوَدْق AI - ترتيب الأخبار الأحدث

import pandas as pd

if "df_news" in globals() and df_news is not None and len(df_news) > 0:

    news_sorted = df_news.copy()

    news_sorted["تاريخ النشر"] = pd.to_datetime(
        news_sorted["تاريخ النشر"],
        errors="coerce",
        utc=True
    )

    news_sorted = news_sorted.dropna(
        subset=["تاريخ النشر"]
    )

    news_sorted = news_sorted.sort_values(
        "تاريخ النشر",
        ascending=False
    )

    print("🌧️ أحدث 10 أخبار في الوَدْق AI")
    display(news_sorted.head(10))

else:
    print("لا توجد أخبار متاحة.")

🌧️ أحدث 10 أخبار في الوَدْق AI

,التصنيف,العنوان,المصدر,الرابط,تاريخ النشر,التحليل الأولي
0,الأخبار العالمية,SAMA Governor: Saudi Economy Remains Resilient...,صحيفة مال,https://news.google.com/rss/articles/CBMiS0FVX...,2026-10-09 13:14:13+00:00,أخبار عالمية
1,الأخبار العالمية,Azerbaijan’s Central Bank Governor addresses I...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-09 08:32:38+00:00,أخبار عالمية
15,السوق السعودي,18 Private Deals Executed on the Saudi Stock M...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-08 12:48:54+00:00,متابعة السوق السعودي
26,الدولار والفائدة,US Dollar: Fed cautious on further hikes – MUF...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-08 09:14:52+00:00,متابعة الدولار والفائدة
11,النفط,Oil: Prices supported by supply risks and Iran...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-08 07:07:50+00:00,متابعة النفط
6,الذهب,Gold prices in Jordan drop by 40 piasters per ...,خبرني - ننقل لك أخبار الأردن والعالم بموثوقية ...,https://news.google.com/rss/articles/CBMikAFBV...,2026-10-08 06:23:58+00:00,الذهب: يحتاج إلى تحليل إضافي
27,الدولار والفائدة,New Zealand Dollar moves sideways as US Dollar...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-08 03:44:55+00:00,متابعة الدولار والفائدة
19,السوق السعودي,13 Private Deals Executed on the Saudi Stock E...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-07 13:27:17+00:00,متابعة السوق السعودي
16,السوق السعودي,13 private deals executed in the Saudi stock m...,صحيفة مال,https://news.google.com/rss/articles/CBMib0FVX...,2026-10-06 13:27:11+00:00,متابعة السوق السعودي
21,السوق الأمريكي,Dow Jones futures rise due to easing Fed rate ...,شبكة تواصل الإخبارية,https://news.google.com/rss/articles/CBMiU0FVX...,2026-10-06 08:39:59+00:00,متابعة السوق الأمريكي

In [ ]:
# 🌧️ الوَدْق AI - تصنيف الأخبار حسب موضوعها

def classify_news(title):
    title = str(title).lower()

    if any(word in title for word in [
        "gold", "الذهب", "silver", "الفضة"
    ]):
        return "الذهب والمعادن"

    elif any(word in title for word in [
        "oil", "crude", " النفط", "نفط", "hormuz", "هرمز"
    ]):
        return "النفط والطاقة"

    elif any(word in title for word in [
        "saudi", "السعودية", "tadawul", "aramco",
        "الراجحي", "السوق السعودي"
    ]):
        return "السوق السعودي"

    elif any(word in title for word in [
        "s&p", "nasdaq", "dow jones", "fed",
        "federal reserve", "الاحتياطي الفيدرالي"
    ]):
        return "السوق الأمريكي"

    elif any(word in title for word in [
        "dollar", "currency", "forex",
        "الدولار", "العملات"
    ]):
        return "العملات"

    else:
        return "اقتصاد وأسواق عامة"


if "news_sorted" in globals() and len(news_sorted) > 0:

    news_analysis = news_sorted.copy()

    news_analysis["موضوع الخبر"] = (
        news_analysis["العنوان"]
        .apply(classify_news)
    )

    print("🌧️ تصنيف الأخبار حسب الموضوع")
    display(
        news_analysis[
            ["تاريخ النشر", "العنوان", "موضوع الخبر"]
        ].head(10)
    )

else:
    print("لم نعثر على جدول الأخبار المرتب.")# 🌧️ الوَدْق AI - تصنيف الأخبار حسب موضوعها

def classify_news(title):
    title = str(title).lower()

    if any(word in title for word in [
        "gold", "الذهب", "silver", "الفضة"
    ]):
        return "الذهب والمعادن"

    elif any(word in title for word in [
        "oil", "crude", " النفط", "نفط", "hormuz", "هرمز"
    ]):
        return "النفط والطاقة"

    elif any(word in title for word in [
        "saudi", "السعودية", "tadawul", "aramco",
        "الراجحي", "السوق السعودي"
    ]):
        return "السوق السعودي"

    elif any(word in title for word in [
        "s&p", "nasdaq", "dow jones", "fed",
        "federal reserve", "الاحتياطي الفيدرالي"
    ]):
        return "السوق الأمريكي"

    elif any(word in title for word in [
        "dollar", "currency", "forex",
        "الدولار", "العملات"
    ]):
        return "العملات"

    else:
        return "اقتصاد وأسواق عامة"


if "news_sorted" in globals() and len(news_sorted) > 0:

    news_analysis = news_sorted.copy()

    news_analysis["موضوع الخبر"] = (
        news_analysis["العنوان"]
        .apply(classify_news)
    )

    print("🌧️ تصنيف الأخبار حسب الموضوع")
    display(
        news_analysis[
            ["تاريخ النشر", "العنوان", "موضوع الخبر"]
        ].head(10)
    )

else:
    print("لم نعثر على جدول الأخبار المرتب.")

🌧️ تصنيف الأخبار حسب الموضوع

,تاريخ النشر,العنوان,موضوع الخبر
0,2026-10-09 13:14:13+00:00,SAMA Governor: Saudi Economy Remains Resilient...,السوق السعودي
1,2026-10-09 08:32:38+00:00,Azerbaijan’s Central Bank Governor addresses I...,اقتصاد وأسواق عامة
15,2026-10-08 12:48:54+00:00,18 Private Deals Executed on the Saudi Stock M...,السوق السعودي
26,2026-10-08 09:14:52+00:00,US Dollar: Fed cautious on further hikes – MUF...,السوق الأمريكي
11,2026-10-08 07:07:50+00:00,Oil: Prices supported by supply risks and Iran...,النفط والطاقة
6,2026-10-08 06:23:58+00:00,Gold prices in Jordan drop by 40 piasters per ...,الذهب والمعادن
27,2026-10-08 03:44:55+00:00,New Zealand Dollar moves sideways as US Dollar...,العملات
19,2026-10-07 13:27:17+00:00,13 Private Deals Executed on the Saudi Stock E...,السوق السعودي
16,2026-10-06 13:27:11+00:00,13 private deals executed in the Saudi stock m...,السوق السعودي
21,2026-10-06 08:39:59+00:00,Dow Jones futures rise due to easing Fed rate ...,السوق الأمريكي

🌧️ تصنيف الأخبار حسب الموضوع

,تاريخ النشر,العنوان,موضوع الخبر
0,2026-10-09 13:14:13+00:00,SAMA Governor: Saudi Economy Remains Resilient...,السوق السعودي
1,2026-10-09 08:32:38+00:00,Azerbaijan’s Central Bank Governor addresses I...,اقتصاد وأسواق عامة
15,2026-10-08 12:48:54+00:00,18 Private Deals Executed on the Saudi Stock M...,السوق السعودي
26,2026-10-08 09:14:52+00:00,US Dollar: Fed cautious on further hikes – MUF...,السوق الأمريكي
11,2026-10-08 07:07:50+00:00,Oil: Prices supported by supply risks and Iran...,النفط والطاقة
6,2026-10-08 06:23:58+00:00,Gold prices in Jordan drop by 40 piasters per ...,الذهب والمعادن
27,2026-10-08 03:44:55+00:00,New Zealand Dollar moves sideways as US Dollar...,العملات
19,2026-10-07 13:27:17+00:00,13 Private Deals Executed on the Saudi Stock E...,السوق السعودي
16,2026-10-06 13:27:11+00:00,13 private deals executed in the Saudi stock m...,السوق السعودي
21,2026-10-06 08:39:59+00:00,Dow Jones futures rise due to easing Fed rate ...,السوق الأمريكي

In [ ]:
# 🌧️ الوَدْق AI - تحليل أولي لاتجاه الأخبار

def analyze_news_direction(title):
    title = str(title).lower()

    positive_words = [
        "rise", "rises", "rising", "gain", "gains",
        "surge", "surges", "growth", "resilient",
        "ارتفاع", "يرتفع", "نمو", "مكاسب", "انتعاش"
    ]

    negative_words = [
        "drop", "drops", "fall", "falls", "decline",
        "declines", "loss", "losses", "crisis",
        "انخفاض", "يتراجع", "هبوط", "خسائر", "أزمة"
    ]

    positive = sum(word in title for word in positive_words)
    negative = sum(word in title for word in negative_words)

    if positive > negative:
        return "إشارات إيجابية في العنوان"
    elif negative > positive:
        return "إشارات سلبية في العنوان"
    else:
        return "غير واضح من العنوان"


if "news_analysis" in globals() and len(news_analysis) > 0:

    news_analysis["إشارة العنوان"] = (
        news_analysis["العنوان"].apply(analyze_news_direction)
    )

    print("🌧️ الوَدْق AI - تحليل أولي للأخبار")

    display(
        news_analysis[
            ["تاريخ النشر", "العنوان", "موضوع الخبر", "إشارة العنوان"]
        ].head(10)
    )

else:
    print("لم يُعثر على جدول الأخبار المصنفة.")

🌧️ الوَدْق AI - تحليل أولي للأخبار

,تاريخ النشر,العنوان,موضوع الخبر,إشارة العنوان
0,2026-10-09 13:14:13+00:00,SAMA Governor: Saudi Economy Remains Resilient...,السوق السعودي,إشارات إيجابية في العنوان
1,2026-10-09 08:32:38+00:00,Azerbaijan’s Central Bank Governor addresses I...,اقتصاد وأسواق عامة,غير واضح من العنوان
15,2026-10-08 12:48:54+00:00,18 Private Deals Executed on the Saudi Stock M...,السوق السعودي,غير واضح من العنوان
26,2026-10-08 09:14:52+00:00,US Dollar: Fed cautious on further hikes – MUF...,السوق الأمريكي,غير واضح من العنوان
11,2026-10-08 07:07:50+00:00,Oil: Prices supported by supply risks and Iran...,النفط والطاقة,غير واضح من العنوان
6,2026-10-08 06:23:58+00:00,Gold prices in Jordan drop by 40 piasters per ...,الذهب والمعادن,إشارات سلبية في العنوان
27,2026-10-08 03:44:55+00:00,New Zealand Dollar moves sideways as US Dollar...,العملات,إشارات إيجابية في العنوان
19,2026-10-07 13:27:17+00:00,13 Private Deals Executed on the Saudi Stock E...,السوق السعودي,غير واضح من العنوان
16,2026-10-06 13:27:11+00:00,13 private deals executed in the Saudi stock m...,السوق السعودي,غير واضح من العنوان
21,2026-10-06 08:39:59+00:00,Dow Jones futures rise due to easing Fed rate ...,السوق الأمريكي,إشارات إيجابية في العنوان

In [ ]:
# 🌧️ الوَدْق AI - ملخص الأخبار حسب السوق

if "news_analysis" in globals() and len(news_analysis) > 0:

    print("🌧️ ملخص الوَدْق AI حسب السوق")
    print("=" * 45)

    summary = (
        news_analysis
        .groupby("موضوع الخبر")["العنوان"]
        .count()
        .sort_values(ascending=False)
    )

    for topic, count in summary.items():
        print(f"📊 {topic}: {count} خبر")

    print("\n📰 أحدث خبر في كل موضوع:")

    latest_by_topic = (
        news_analysis
        .sort_values("تاريخ النشر", ascending=False)
        .groupby("موضوع الخبر")
        .head(1)
    )

    display(
        latest_by_topic[
            ["تاريخ النشر", "موضوع الخبر", "العنوان", "إشارة العنوان"]
        ]
    )

else:
    print("لم يُعثر على جدول الأخبار المصنفة.")

🌧️ ملخص الوَدْق AI حسب السوق
=============================================
📊 الذهب والمعادن: 6 خبر
📊 السوق الأمريكي: 6 خبر
📊 النفط والطاقة: 6 خبر
📊 السوق السعودي: 6 خبر
📊 اقتصاد وأسواق عامة: 5 خبر
📊 العملات: 1 خبر

📰 أحدث خبر في كل موضوع:

,تاريخ النشر,موضوع الخبر,العنوان,إشارة العنوان
0,2026-10-09 13:14:13+00:00,السوق السعودي,SAMA Governor: Saudi Economy Remains Resilient...,إشارات إيجابية في العنوان
1,2026-10-09 08:32:38+00:00,اقتصاد وأسواق عامة,Azerbaijan’s Central Bank Governor addresses I...,غير واضح من العنوان
26,2026-10-08 09:14:52+00:00,السوق الأمريكي,US Dollar: Fed cautious on further hikes – MUF...,غير واضح من العنوان
11,2026-10-08 07:07:50+00:00,النفط والطاقة,Oil: Prices supported by supply risks and Iran...,غير واضح من العنوان
6,2026-10-08 06:23:58+00:00,الذهب والمعادن,Gold prices in Jordan drop by 40 piasters per ...,إشارات سلبية في العنوان
27,2026-10-08 03:44:55+00:00,العملات,New Zealand Dollar moves sideways as US Dollar...,إشارات إيجابية في العنوان

In [ ]:
# 🌧️ الوَدْق AI - فحص جاهزية بيانات الأسواق

market_variables = {
    "الأسواق العالمية": "market_df",
    "الأسهم السعودية": "saudi_df",
    "المؤشرات الفنية": "technical_df",
    "نتائج التحليل": "wadq_results",
    "تأثير الأخبار": "wadq_impact_results",
}

for label, var_name in market_variables.items():
    value = globals().get(var_name)

    print(f"\n📊 {label}")

    if value is None:
        print("⚠️ البيانات غير متاحة")
    elif hasattr(value, "empty"):
        print("عدد الصفوف:", len(value))
        print("الأعمدة:", list(value.columns))
    else:
        print("البيانات موجودة")

📊 الأسواق العالمية
عدد الصفوف: 7
الأعمدة: ['السوق', 'آخر سعر إغلاق متاح', 'التغير %', 'الحركة']

📊 الأسهم السعودية
عدد الصفوف: 5
الأعمدة: ['السهم أو المؤشر', 'آخر إغلاق متاح', 'التغير %', 'الاتجاه السابق']

📊 المؤشرات الفنية
عدد الصفوف: 5
الأعمدة: ['السهم', 'آخر إغلاق', 'RSI', 'إشارة RSI', 'المتوسط 20', 'المتوسط 50', 'قراءة الاتجاه']

📊 نتائج التحليل
عدد الصفوف: 30
الأعمدة: ['التصنيف', 'العنوان', 'المصدر', 'الرابط', 'تاريخ النشر', 'التحليل الأولي', 'السوق']

📊 تأثير الأخبار
عدد الصفوف: 30
الأعمدة: ['التصنيف', 'العنوان', 'المصدر', 'الرابط', 'تاريخ النشر', 'التحليل الأولي', 'نبرة الخبر']

In [ ]:
# 🌧️ الوَدْق AI - فحص المؤشرات الفنية

if "technical_df" in globals() and technical_df is not None:

    print("🌧️ تقرير المؤشرات الفنية")
    print("=" * 40)

    print("عدد الأصول:", len(technical_df))
    print("الأعمدة المتاحة:")
    print(list(technical_df.columns))

    display(technical_df)

else:
    print("⚠️ بيانات المؤشرات الفنية غير متاحة.")

⚠️ بيانات المؤشرات الفنية غير متاحة.

In [ ]:
# 🌧️ الوَدْق AI - تقرير تفسير المؤشرات الفنية

import pandas as pd

if "technical_df" in globals() and technical_df is not None:

    df_report = technical_df.copy()

    print("🌧️ تقرير الوَدْق AI للتحليل الفني")
    print("=" * 55)

    for _, row in df_report.iterrows():

        stock = row.get("السهم", "أصل غير محدد")
        price = row.get("آخر إغلاق")
        rsi = row.get("RSI")
        ma20 = row.get("المتوسط 20")
        ma50 = row.get("المتوسط 50")
        trend = row.get("قراءة الاتجاه", "غير محدد")

        print(f"\n📊 الأصل: {stock}")
        print(f"💰 آخر إغلاق مسجل: {price}")
        print(f"📈 الاتجاه المحسوب: {trend}")

        if pd.notna(rsi):
            if rsi < 30:
                print("📉 RSI: منخفض جدًا؛ افحص احتمال التشبع البيعي.")
            elif rsi < 50:
                print("📉 RSI: الزخم أضعف من المستوى المتوسط.")
            elif rsi <= 70:
                print("📊 RSI: الزخم متوسط إلى مرتفع.")
            else:
                print("📈 RSI: مرتفع؛ افحص احتمال التشبع الشرائي.")

        if pd.notna(price) and pd.notna(ma20) and pd.notna(ma50):
            if price < ma20 and price < ma50:
                print("⚠️ السعر أقل من المتوسطين 20 و50.")
            elif price > ma20 and price > ma50:
                print("📈 السعر أعلى من المتوسطين 20 و50.")
            else:
                print("↔️ السعر بين المتوسطين أو يتقاطع مع أحدهما.")

        print("-" * 40)

else:
    print("⚠️ بيانات المؤشرات الفنية غير متاحة.")

🌧️ تقرير الوَدْق AI للتحليل الفني
=======================================================

📊 الأصل: مصرف الراجحي
💰 آخر إغلاق مسجل: 62.3
📈 الاتجاه المحسوب: اتجاه هابط وفق الشروط
📉 RSI: الزخم أضعف من المستوى المتوسط.
⚠️ السعر أقل من المتوسطين 20 و50.
----------------------------------------

📊 الأصل: أرامكو السعودية
💰 آخر إغلاق مسجل: 25.74
📈 الاتجاه المحسوب: اتجاه مختلط
📊 RSI: الزخم متوسط إلى مرتفع.
↔️ السعر بين المتوسطين أو يتقاطع مع أحدهما.
----------------------------------------

📊 الأصل: معادن
💰 آخر إغلاق مسجل: 62.4
📈 الاتجاه المحسوب: اتجاه هابط وفق الشروط
📉 RSI: الزخم أضعف من المستوى المتوسط.
⚠️ السعر أقل من المتوسطين 20 و50.
----------------------------------------

📊 الأصل: سابك
💰 آخر إغلاق مسجل: 45.8
📈 الاتجاه المحسوب: اتجاه هابط وفق الشروط
📉 RSI: الزخم أضعف من المستوى المتوسط.
⚠️ السعر أقل من المتوسطين 20 و50.
----------------------------------------

📊 الأصل: أكوا باور
💰 آخر إغلاق مسجل: 164.9
📈 الاتجاه المحسوب: اتجاه هابط وفق الشروط
📉 RSI: الزخم أضعف من المستوى المتوسط.
⚠️ السعر أقل من المتوسطين 20 و50.
----------------------------------------

In [ ]:
# 🇺🇸 الودق AI - تحليل الأسهم الأمريكية

import yfinance as yf
import pandas as pd
import numpy as np

# الأسهم والمؤشرات الأمريكية
us_stocks = {
    "إنفيديا": "NVDA",
    "تسلا": "TSLA",
    "آبل": "AAPL",
    "مايكروسوفت": "MSFT",
    "أمازون": "AMZN",
    "ألفابت": "GOOGL",
    "ميتا": "META",
    "ناسداك 100": "QQQ",
    "ستاندرد آند بورز 500": "SPY"
}

us_results = []

print("🌧️ الودق AI")
print("🇺🇸 تحليل الأسهم الأمريكية")
print("=" * 60)

for name, symbol in us_stocks.items():
    try:
        # جلب بيانات الأسعار
        data = yf.download(
            symbol,
            period="6mo",
            interval="1d",
            auto_adjust=True,
            progress=False
        )

        if data.empty:
            print(f"⚠️ لا توجد بيانات متاحة: {name}")
            continue

        # معالجة اختلاف شكل بيانات Yahoo Finance
        close_data = data["Close"]

        if isinstance(close_data, pd.DataFrame):
            close_data = close_data.iloc[:, 0]

        close = pd.to_numeric(
            close_data, errors="coerce"
        ).dropna()

        if len(close) < 50:
            print(f"⚠️ البيانات غير كافية: {name}")
            continue

        # المتوسطات المتحركة
        ma20 = close.rolling(20).mean()
        ma50 = close.rolling(50).mean()

        # مؤشر RSI
        delta = close.diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.ewm(
            alpha=1/14, min_periods=14, adjust=False
        ).mean()

        avg_loss = loss.ewm(
            alpha=1/14, min_periods=14, adjust=False
        ).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)
        rsi = 100 - (100 / (1 + rs))

        # مؤشر MACD
        ema12 = close.ewm(
            span=12, adjust=False
        ).mean()

        ema26 = close.ewm(
            span=26, adjust=False
        ).mean()

        macd = ema12 - ema26

        signal = macd.ewm(
            span=9, adjust=False
        ).mean()

        # أحدث القراءات
        price = float(close.iloc[-1])
        last_ma20 = float(ma20.iloc[-1])
        last_ma50 = float(ma50.iloc[-1])
        last_rsi = rsi.iloc[-1]
        last_macd = float(macd.iloc[-1])
        last_signal = float(signal.iloc[-1])

        # تحديد الاتجاه الفني
        if price > last_ma20 > last_ma50:
            trend = "صاعد"
        elif price < last_ma20 < last_ma50:
            trend = "هابط"
        else:
            trend = "مختلط"

        # قراءة RSI
        if pd.isna(last_rsi):
            rsi_status = "غير متاح"
        elif last_rsi >= 70:
            rsi_status = "تشبع شرائي محتمل"
        elif last_rsi <= 30:
            rsi_status = "تشبع بيعي محتمل"
        else:
            rsi_status = "ضمن النطاق المتوسط"

        # حفظ النتائج
        us_results.append({
            "السهم": name,
            "الرمز": symbol,
            "آخر إغلاق": round(price, 2),
            "المتوسط 20": round(last_ma20, 2),
            "المتوسط 50": round(last_ma50, 2),
            "RSI": (
                round(float(last_rsi), 2)
                if pd.notna(last_rsi) else np.nan
            ),
            "حالة RSI": rsi_status,
            "MACD": round(last_macd, 4),
            "إشارة MACD": round(last_signal, 4),
            "الاتجاه": trend
        })

        print(f"\n📊 {name} ({symbol})")
        print(f"💰 آخر سعر متاح: {price:.2f}")
        print(f"📈 الاتجاه الفني: {trend}")
        print(f"📉 RSI: {rsi_status}")

    except Exception as e:
        print(f"⚠️ تعذر تحليل {name}: {e}")

# حفظ نتائج الأسهم الأمريكية في جدول مستقل
us_technical_df = pd.DataFrame(us_results)

print("\n" + "=" * 60)
print("🌧️ ملخص تحليل الأسهم الأمريكية")
print("=" * 60)

if not us_technical_df.empty:
    display(us_technical_df)
    print("\n✅ اكتمل تحليل الأصول الأمريكية المتاحة.")
else:
    print("لم نحصل على بيانات. تحققي من اتصال الإنترنت.")

🌧️ الودق AI
🇺🇸 تحليل الأسهم الأمريكية
============================================================

📊 إنفيديا (NVDA)
💰 آخر سعر متاح: 228.52
📈 الاتجاه الفني: صاعد
📉 RSI: ضمن النطاق المتوسط

📊 تسلا (TSLA)
💰 آخر سعر متاح: 375.23
📈 الاتجاه الفني: صاعد
📉 RSI: ضمن النطاق المتوسط

📊 آبل (AAPL)
💰 آخر سعر متاح: 341.27
📈 الاتجاه الفني: صاعد
📉 RSI: ضمن النطاق المتوسط

📊 مايكروسوفت (MSFT)
💰 آخر سعر متاح: 543.45
📈 الاتجاه الفني: صاعد
📉 RSI: تشبع شرائي محتمل

📊 أمازون (AMZN)
💰 آخر سعر متاح: 258.58
📈 الاتجاه الفني: مختلط
📉 RSI: ضمن النطاق المتوسط

📊 ألفابت (GOOGL)
💰 آخر سعر متاح: 353.78
📈 الاتجاه الفني: صاعد
📉 RSI: ضمن النطاق المتوسط

📊 ميتا (META)
💰 آخر سعر متاح: 762.50
📈 الاتجاه الفني: صاعد
📉 RSI: ضمن النطاق المتوسط

📊 ناسداك 100 (QQQ)
💰 آخر سعر متاح: 743.57
📈 الاتجاه الفني: صاعد
📉 RSI: ضمن النطاق المتوسط

📊 ستاندرد آند بورز 500 (SPY)
💰 آخر سعر متاح: 778.01
📈 الاتجاه الفني: صاعد
📉 RSI: ضمن النطاق المتوسط

============================================================
🌧️ ملخص تحليل الأسهم الأمريكية
============================================================

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد
3,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد
4,أمازون,AMZN,258.58,252.83,258.35,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط
5,ألفابت,GOOGL,353.78,346.53,345.69,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد
6,ميتا,META,762.50,727.58,646.59,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد
7,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد
8,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد

✅ اكتمل تحليل الأصول الأمريكية المتاحة.

In [ ]:
import pandas as pd

print("🌧️ الودق AI — فحص الجداول")
print("=" * 55)

tables = [
    "us_technical_df",
    "wadq_global_news_df",
    "wadq_ticker_news_df",
    "wadq_impact_news_df",
    "wadq_global_market_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_master_report_v3_df",
    "wadq_global_us_unified_df",
    "wadq_global_priority_df",
    "wadq_us_monitoring_df",
    "wadq_stage41_decision_df",
    "wadq_executive_summary_df",
]

for name in tables:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name}: {len(obj)} صفوف × {len(obj.columns)} أعمدة")
    else:
        print(f"⚠️ {name}: غير موجود في الذاكرة")

🌧️ الودق AI — فحص الجداول
=======================================================
✅ us_technical_df: 9 صفوف × 10 أعمدة
⚠️ wadq_global_news_df: غير موجود في الذاكرة
⚠️ wadq_ticker_news_df: غير موجود في الذاكرة
⚠️ wadq_impact_news_df: غير موجود في الذاكرة
✅ wadq_global_market_df: 17 صفوف × 6 أعمدة
⚠️ wadq_global_master_report_df: غير موجود في الذاكرة
⚠️ wadq_global_master_report_v2_df: غير موجود في الذاكرة
⚠️ wadq_global_master_report_v3_df: غير موجود في الذاكرة
⚠️ wadq_global_us_unified_df: غير موجود في الذاكرة
⚠️ wadq_global_priority_df: غير موجود في الذاكرة
⚠️ wadq_us_monitoring_df: غير موجود في الذاكرة
⚠️ wadq_stage41_decision_df: غير موجود في الذاكرة
⚠️ wadq_executive_summary_df: غير موجود في الذاكرة

In [ ]:
# ==========================================
# 🌧️ الودق AI
# المرحلة: جمع الأخبار الاقتصادية العالمية والأمريكية
# خلية جديدة - لا تحذف الأكواد السابقة
# ==========================================

import pandas as pd
import requests
import xml.etree.ElementTree as ET
from urllib.parse import quote
from datetime import datetime, timezone
from IPython.display import display

# مصادر الأخبار
WADQ_NEWS_SOURCES = {
    "الأسواق الأمريكية":
        "https://news.google.com/rss/search?q="
        + quote("US stock market Wall Street Nasdaq S&P 500")
        + "&hl=en-US&gl=US&ceid=US:en",

    "الاقتصاد العالمي":
        "https://news.google.com/rss/search?q="
        + quote("global economy financial markets")
        + "&hl=en-US&gl=US&ceid=US:en",

    "الفائدة والتضخم":
        "https://news.google.com/rss/search?q="
        + quote("Federal Reserve interest rates inflation")
        + "&hl=en-US&gl=US&ceid=US:en",

    "الشركات الأمريكية":
        "https://news.google.com/rss/search?q="
        + quote("NVIDIA Tesla Apple Microsoft earnings")
        + "&hl=en-US&gl=US&ceid=US:en",

    "الذهب والنفط":
        "https://news.google.com/rss/search?q="
        + quote("gold oil prices OPEC")
        + "&hl=en-US&gl=US&ceid=US:en",

    "السوق السعودي":
        "https://news.google.com/rss/search?q="
        + quote("Saudi stock market Tadawul Saudi economy")
        + "&hl=ar&gl=SA&ceid=SA:ar",

    "الأخبار العالمية":
        "https://news.google.com/rss/search?q="
        + quote("world news geopolitics markets")
        + "&hl=en-US&gl=US&ceid=US:en"
}


def wadq_fetch_news():
    articles = []

    for category, url in WADQ_NEWS_SOURCES.items():
        try:
            response = requests.get(
                url,
                timeout=20,
                headers={"User-Agent": "Mozilla/5.0"}
            )
            response.raise_for_status()

            root = ET.fromstring(response.content)

            for item in root.findall(".//item"):
                title = item.findtext("title", "").strip()
                link = item.findtext("link", "").strip()
                published = item.findtext("pubDate", "").strip()

                if title and link:
                    articles.append({
                        "category": category,
                        "title": title,
                        "published": published,
                        "link": link,
                        "fetched_at_utc": datetime.now(
                            timezone.utc
                        ).isoformat()
                    })

        except Exception as error:
            print(f"تعذر جلب فئة {category}: {error}")

    columns = [
        "category", "title", "published",
        "link", "fetched_at_utc"
    ]

    news_df = pd.DataFrame(articles, columns=columns)

    if not news_df.empty:
        news_df = news_df.drop_duplicates(
            subset=["title", "link"]
        ).reset_index(drop=True)

    return news_df


# جلب الأخبار
wadq_news_df = wadq_fetch_news()

print("🌧️ تقرير أخبار الودق AI")
print("=" * 45)
print("عدد الأخبار:", len(wadq_news_df))

if not wadq_news_df.empty:
    display(
        wadq_news_df[
            ["category", "title", "published", "link"]
        ].head(25)
    )
else:
    print("لم تصل أخبار في هذه المحاولة.")
    print("تحققي من الاتصال بالإنترنت ثم أعيدي تشغيل هذه الخلية.")

🌧️ تقرير أخبار الودق AI
=============================================
عدد الأخبار: 565

,category,title,published,link
0,الأسواق الأمريكية,Nasdaq ends down as chipmakers fall and bank e...,"Tue, 13 Oct 2026 20:17:36 GMT",https://news.google.com/rss/articles/CBMivAFBV...
1,الأسواق الأمريكية,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...","Tue, 13 Oct 2026 21:10:57 GMT",https://news.google.com/rss/articles/CBMijwFBV...
2,الأسواق الأمريكية,US stocks hover near their latest record in mi...,"Mon, 12 Oct 2026 14:33:55 GMT",https://news.google.com/rss/articles/CBMixgFBV...
3,الأسواق الأمريكية,"Stock Market Today: Dow Jones, S&P 500 Futures...","Tue, 13 Oct 2026 09:55:18 GMT",https://news.google.com/rss/articles/CBMiqAJBV...
4,الأسواق الأمريكية,US stocks hover near their latest record in mi...,"Mon, 12 Oct 2026 19:26:36 GMT",https://news.google.com/rss/articles/CBMiggFBV...
5,الأسواق الأمريكية,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...","Mon, 12 Oct 2026 18:43:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...
6,الأسواق الأمريكية,"Nasdaq falls ahead of earnings, economic data ...","Mon, 12 Oct 2026 23:50:15 GMT",https://news.google.com/rss/articles/CBMipAFBV...
7,الأسواق الأمريكية,Stock Market: Will S&P 500 Open Up or Down Tod...,"Tue, 13 Oct 2026 05:48:41 GMT",https://news.google.com/rss/articles/CBMitwFBV...
8,الأسواق الأمريكية,"US Stock Futures Mixed as AI Concerns, LVMH Sa...","Tue, 13 Oct 2026 09:28:44 GMT",https://news.google.com/rss/articles/CBMilAFBV...
9,الأسواق الأمريكية,"S&P 500, Nasdaq end lower as crude prices jump...","Thu, 08 Oct 2026 23:09:38 GMT",https://news.google.com/rss/articles/CBMinAFBV...
10,الأسواق الأمريكية,"Stock Market Today: S&P 500, Dow Futures Gain,...","Mon, 12 Oct 2026 12:29:00 GMT",https://news.google.com/rss/articles/CBMikwJBV...
11,الأسواق الأمريكية,Wall Street ends marginally lower after softne...,"Tue, 13 Oct 2026 00:28:06 GMT",https://news.google.com/rss/articles/CBMiuAFBV...
12,الأسواق الأمريكية,"The S&P 500 Hits a New Record High, Powered by...","Tue, 06 Oct 2026 21:33:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...
13,الأسواق الأمريكية,Wall Street finishes its record-setting week w...,"Fri, 09 Oct 2026 05:03:10 GMT",https://news.google.com/rss/articles/CBMitAFBV...
14,الأسواق الأمريكية,Equities end slightly lower as bond yields hol...,"Tue, 29 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiqAFBV...
15,الأسواق الأمريكية,"S&P 500 dips, Nasdaq higher after data shows m...","Wed, 30 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMipwFBV...
16,الأسواق الأمريكية,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...","Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
17,الأسواق الأمريكية,"US Stock Market Today: Dow Jumps 369 Points, N...","Tue, 13 Oct 2026 13:37:46 GMT",https://news.google.com/rss/articles/CBMivwFBV...
18,الأسواق الأمريكية,US stock market hits all-time high as investor...,"Wed, 07 Oct 2026 06:34:37 GMT",https://news.google.com/rss/articles/CBMiqAFBV...
19,الأسواق الأمريكية,S&P 500 ends marginally lower as investors foc...,"Thu, 24 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMisgFBV...
20,الأسواق الأمريكية,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...","Wed, 07 Oct 2026 20:11:09 GMT",https://news.google.com/rss/articles/CBMiuAFBV...
21,الأسواق الأمريكية,Wall Street kicks off key week of bank earning...,"Mon, 12 Oct 2026 01:28:07 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
22,الأسواق الأمريكية,U.S. stock market drops: S&P 500 and Nasdaq fa...,"Thu, 08 Oct 2026 15:04:08 GMT",https://news.google.com/rss/articles/CBMi2wFBV...
23,الأسواق الأمريكية,【US Pre-Market】Memory Chip Sector Drops Across...,"Tue, 13 Oct 2026 12:05:40 GMT",https://news.google.com/rss/articles/CBMivwFBV...
24,الأسواق الأمريكية,S&P 500 and Nasdaq surge to record highs after...,"Tue, 06 Oct 2026 20:38:00 GMT",https://news.google.com/rss/articles/CBMiiwFBV...

In [ ]:
# ==========================================
# 🌧️ الودق AI
# المرحلة الثانية: تحليل الأخبار وربطها بالأسهم
# نحافظ على جميع الأكواد السابقة
# ==========================================

import pandas as pd
import re
from IPython.display import display

# التأكد من وجود الأخبار
if "wadq_news_df" not in globals():
    raise NameError(
        "لم يتم العثور على wadq_news_df. "
        "شغّلي خلية جمع الأخبار أولاً."
    )

if wadq_news_df.empty:
    print("لا توجد أخبار للتحليل. شغّلي خلية جمع الأخبار أولاً.")

else:
    # كلمات أولية لتقدير دلالة الخبر
    positive_words = [
        "surge", "soar", "rise", "gain", "growth",
        "profit", "beats estimates", "record high",
        "upgrade", "bullish", "approval", "strong results",
        "ارتفاع", "نمو", "أرباح", "صعود", "مكاسب",
        "نتائج إيجابية", "تجاوز التوقعات"
    ]

    negative_words = [
        "crash", "fall", "drop", "decline", "loss",
        "misses estimates", "downgrade", "bearish",
        "lawsuit", "warning", "recession", "selloff",
        "انخفاض", "هبوط", "خسائر", "تراجع", "تحذير",
        "ركود", "هبوط حاد", "نتائج سلبية"
    ]

    # رموز الأسهم وأسماء الشركات المرتبطة بها
    wadq_ticker_keywords = {
        "NVDA": ["nvidia", "نفيديا"],
        "TSLA": ["tesla", "تسلا"],
        "AAPL": ["apple inc", "apple stock", "آبل"],
        "MSFT": ["microsoft", "مايكروسوفت"],
        "AMZN": ["amazon", "أمازون"],
        "GOOGL": ["alphabet", "google", "جوجل"],
        "META": ["meta platforms", "facebook", "ميتا"],
        "QQQ": ["nasdaq 100", "nasdaq-100"],
        "SPY": ["s&p 500", "sp500", "s&p500"]
    }

    def wadq_classify_sentiment(text):
        text = str(text).lower()

        positive_count = sum(
            1 for word in positive_words if word in text
        )

        negative_count = sum(
            1 for word in negative_words if word in text
        )

        if positive_count > negative_count:
            return "إيجابي مبدئي"

        elif negative_count > positive_count:
            return "سلبي مبدئي"

        return "محايد أو غير واضح"

    def wadq_find_tickers(text):
        text = str(text).lower()
        found = []

        for ticker, keywords in wadq_ticker_keywords.items():
            for keyword in keywords:
                if keyword in text:
                    found.append(ticker)
                    break

        return found

    # إنشاء نسخة مستقلة للتحليل
    wadq_news_scored_df = wadq_news_df.copy()

    wadq_news_scored_df["sentiment"] = (
        wadq_news_scored_df["title"].apply(
            wadq_classify_sentiment
        )
    )

    wadq_news_scored_df["related_tickers"] = (
        wadq_news_scored_df["title"].apply(
            wadq_find_tickers
        )
    )

    # عدد الأسهم التي ارتبطت بأخبار
    wadq_news_scored_df["ticker_count"] = (
        wadq_news_scored_df["related_tickers"].apply(len)
    )

    print("🌧️ الودق AI - نتائج تحليل الأخبار")
    print("=" * 55)
    print("إجمالي الأخبار:", len(wadq_news_scored_df))
    print(
        "الأخبار المرتبطة بأسهم معروفة:",
        int((wadq_news_scored_df["ticker_count"] > 0).sum())
    )

    display(
        wadq_news_scored_df[
            [
                "category",
                "title",
                "sentiment",
                "related_tickers",
                "link"
            ]
        ].head(30)
    )

    # إنشاء جدول منفصل لكل سهم وخبر مرتبط به
    wadq_ticker_news_rows = []

    for _, row in wadq_news_scored_df.iterrows():
        for ticker in row["related_tickers"]:
            wadq_ticker_news_rows.append({
                "ticker": ticker,
                "news_title": row["title"],
                "sentiment": row["sentiment"],
                "category": row["category"],
                "published": row["published"],
                "link": row["link"]
            })

    wadq_ticker_news_df = pd.DataFrame(
        wadq_ticker_news_rows,
        columns=[
            "ticker", "news_title", "sentiment",
            "category", "published", "link"
        ]
    )

    print("\n📊 الأخبار المرتبطة بكل سهم")
    display(wadq_ticker_news_df.head(30))

🌧️ الودق AI - نتائج تحليل الأخبار
=======================================================
إجمالي الأخبار: 565
الأخبار المرتبطة بأسهم معروفة: 100

,category,title,sentiment,related_tickers,link
0,الأسواق الأمريكية,Nasdaq ends down as chipmakers fall and bank e...,سلبي مبدئي,[],https://news.google.com/rss/articles/CBMivAFBV...
1,الأسواق الأمريكية,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",سلبي مبدئي,[SPY],https://news.google.com/rss/articles/CBMijwFBV...
2,الأسواق الأمريكية,US stocks hover near their latest record in mi...,محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMixgFBV...
3,الأسواق الأمريكية,"Stock Market Today: Dow Jones, S&P 500 Futures...",محايد أو غير واضح,"[QQQ, SPY]",https://news.google.com/rss/articles/CBMiqAJBV...
4,الأسواق الأمريكية,US stocks hover near their latest record in mi...,محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMiggFBV...
5,الأسواق الأمريكية,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...",إيجابي مبدئي,[SPY],https://news.google.com/rss/articles/CBMiwwFBV...
6,الأسواق الأمريكية,"Nasdaq falls ahead of earnings, economic data ...",سلبي مبدئي,[],https://news.google.com/rss/articles/CBMipAFBV...
7,الأسواق الأمريكية,Stock Market: Will S&P 500 Open Up or Down Tod...,محايد أو غير واضح,[SPY],https://news.google.com/rss/articles/CBMitwFBV...
8,الأسواق الأمريكية,"US Stock Futures Mixed as AI Concerns, LVMH Sa...",محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMilAFBV...
9,الأسواق الأمريكية,"S&P 500, Nasdaq end lower as crude prices jump...",محايد أو غير واضح,[SPY],https://news.google.com/rss/articles/CBMinAFBV...
10,الأسواق الأمريكية,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,"[QQQ, SPY]",https://news.google.com/rss/articles/CBMikwJBV...
11,الأسواق الأمريكية,Wall Street ends marginally lower after softne...,محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMiuAFBV...
12,الأسواق الأمريكية,"The S&P 500 Hits a New Record High, Powered by...",إيجابي مبدئي,[SPY],https://news.google.com/rss/articles/CBMisAFBV...
13,الأسواق الأمريكية,Wall Street finishes its record-setting week w...,إيجابي مبدئي,[],https://news.google.com/rss/articles/CBMitAFBV...
14,الأسواق الأمريكية,Equities end slightly lower as bond yields hol...,محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMiqAFBV...
15,الأسواق الأمريكية,"S&P 500 dips, Nasdaq higher after data shows m...",إيجابي مبدئي,[SPY],https://news.google.com/rss/articles/CBMipwFBV...
16,الأسواق الأمريكية,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,"[QQQ, SPY]",https://news.google.com/rss/articles/CBMiwgFBV...
17,الأسواق الأمريكية,"US Stock Market Today: Dow Jumps 369 Points, N...",محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMivwFBV...
18,الأسواق الأمريكية,US stock market hits all-time high as investor...,محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMiqAFBV...
19,الأسواق الأمريكية,S&P 500 ends marginally lower as investors foc...,محايد أو غير واضح,[SPY],https://news.google.com/rss/articles/CBMisgFBV...
20,الأسواق الأمريكية,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...",محايد أو غير واضح,[SPY],https://news.google.com/rss/articles/CBMiuAFBV...
21,الأسواق الأمريكية,Wall Street kicks off key week of bank earning...,محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMiwgFBV...
22,الأسواق الأمريكية,U.S. stock market drops: S&P 500 and Nasdaq fa...,سلبي مبدئي,[SPY],https://news.google.com/rss/articles/CBMi2wFBV...
23,الأسواق الأمريكية,【US Pre-Market】Memory Chip Sector Drops Across...,سلبي مبدئي,[],https://news.google.com/rss/articles/CBMivwFBV...
24,الأسواق الأمريكية,S&P 500 and Nasdaq surge to record highs after...,إيجابي مبدئي,[SPY],https://news.google.com/rss/articles/CBMiiwFBV...
25,الأسواق الأمريكية,US stocks: Nasdaq ends down as chipmakers fall...,سلبي مبدئي,[],https://news.google.com/rss/articles/CBMingFBV...
26,الأسواق الأمريكية,"Wall Street ends lower, off record highs, as T...",إيجابي مبدئي,[],https://news.google.com/rss/articles/CBMiyAFBV...
27,الأسواق الأمريكية,"S&P 500, Nasdaq end down on tech stocks, inves...",محايد أو غير واضح,[SPY],https://news.google.com/rss/articles/CBMisAFBV...
28,الأسواق الأمريكية,Wall St rises on the day but falls for the wee...,محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMioAFBV...
29,الأسواق الأمريكية,Wall Street’s Nasdaq hits all-time high as AI ...,محايد أو غير واضح,[],https://news.google.com/rss/articles/CBMirAFBV...

📊 الأخبار المرتبطة بكل سهم

,ticker,news_title,sentiment,category,published,link
0,SPY,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",سلبي مبدئي,الأسواق الأمريكية,"Tue, 13 Oct 2026 21:10:57 GMT",https://news.google.com/rss/articles/CBMijwFBV...
1,QQQ,"Stock Market Today: Dow Jones, S&P 500 Futures...",محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 09:55:18 GMT",https://news.google.com/rss/articles/CBMiqAJBV...
2,SPY,"Stock Market Today: Dow Jones, S&P 500 Futures...",محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 09:55:18 GMT",https://news.google.com/rss/articles/CBMiqAJBV...
3,SPY,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...",إيجابي مبدئي,الأسواق الأمريكية,"Mon, 12 Oct 2026 18:43:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...
4,SPY,Stock Market: Will S&P 500 Open Up or Down Tod...,محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 05:48:41 GMT",https://news.google.com/rss/articles/CBMitwFBV...
5,SPY,"S&P 500, Nasdaq end lower as crude prices jump...",محايد أو غير واضح,الأسواق الأمريكية,"Thu, 08 Oct 2026 23:09:38 GMT",https://news.google.com/rss/articles/CBMinAFBV...
6,QQQ,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 12 Oct 2026 12:29:00 GMT",https://news.google.com/rss/articles/CBMikwJBV...
7,SPY,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 12 Oct 2026 12:29:00 GMT",https://news.google.com/rss/articles/CBMikwJBV...
8,SPY,"The S&P 500 Hits a New Record High, Powered by...",إيجابي مبدئي,الأسواق الأمريكية,"Tue, 06 Oct 2026 21:33:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...
9,SPY,"S&P 500 dips, Nasdaq higher after data shows m...",إيجابي مبدئي,الأسواق الأمريكية,"Wed, 30 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMipwFBV...
10,QQQ,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,الأسواق الأمريكية,"Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
11,SPY,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,الأسواق الأمريكية,"Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
12,SPY,S&P 500 ends marginally lower as investors foc...,محايد أو غير واضح,الأسواق الأمريكية,"Thu, 24 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMisgFBV...
13,SPY,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...",محايد أو غير واضح,الأسواق الأمريكية,"Wed, 07 Oct 2026 20:11:09 GMT",https://news.google.com/rss/articles/CBMiuAFBV...
14,SPY,U.S. stock market drops: S&P 500 and Nasdaq fa...,سلبي مبدئي,الأسواق الأمريكية,"Thu, 08 Oct 2026 15:04:08 GMT",https://news.google.com/rss/articles/CBMi2wFBV...
15,SPY,S&P 500 and Nasdaq surge to record highs after...,إيجابي مبدئي,الأسواق الأمريكية,"Tue, 06 Oct 2026 20:38:00 GMT",https://news.google.com/rss/articles/CBMiiwFBV...
16,SPY,"S&P 500, Nasdaq end down on tech stocks, inves...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 24 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...
17,SPY,"Stock Market Today: S&P 500, Dow, Nasdaq Futur...",سلبي مبدئي,الأسواق الأمريكية,"Wed, 07 Oct 2026 12:36:00 GMT",https://news.google.com/rss/articles/CBMingJBV...
18,SPY,US Stock Market Today: S&P 500 Futures Climb A...,محايد أو غير واضح,الأسواق الأمريكية,"Mon, 05 Oct 2026 08:56:27 GMT",https://news.google.com/rss/articles/CBMiyAFBV...
19,SPY,"Wall Street Today: Dow, S&P 500, Nasdaq Comp R...",إيجابي مبدئي,الأسواق الأمريكية,"Thu, 01 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMioAFBV...
20,SPY,S&P 500 ends higher as CoreWeave results fuel ...,محايد أو غير واضح,الأسواق الأمريكية,"Wed, 12 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiowFBV...
21,SPY,"Wall Street Today: DJIA, S&P 500, Nasdaq Comp ...",محايد أو غير واضح,الأسواق الأمريكية,"Tue, 29 Sep 2026 20:01:19 GMT",https://news.google.com/rss/articles/CBMiogFBV...
22,NVDA,Wall Street stocks end tad lower after hot inf...,محايد أو غير واضح,الأسواق الأمريكية,"Wed, 26 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiqwFBV...
23,SPY,"Wall Street Today: DJIA, S&P 500, Nasdaq Comp ...",سلبي مبدئي,الأسواق الأمريكية,"Mon, 28 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiogFBV...
24,SPY,S&P 500 Hits All-Time High on AI Bets as Oil D...,سلبي مبدئي,الأسواق الأمريكية,"Mon, 05 Oct 2026 23:13:44 GMT",https://news.google.com/rss/articles/CBMivgFBV...
25,SPY,"Dow, S&P 500 close at record on AI-linked earn...",محايد أو غير واضح,الأسواق الأمريكية,"Tue, 04 Aug 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMitAFBV...
26,SPY,"S&P 500 ends higher, Dow and Nasdaq mostly fla...",إيجابي مبدئي,الأسواق الأمريكية,"Thu, 01 Oct 2026 00:45:22 GMT",https://news.google.com/rss/articles/CBMisAFBV...
27,QQQ,"Stock Market Today: S&P 500, Nasdaq 100, Dow J...",إيجابي مبدئي,الأسواق الأمريكية,"Thu, 01 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMilAJBV...
28,SPY,"Stock Market Today: S&P 500, Nasdaq 100, Dow J...",إيجابي مبدئي,الأسواق الأمريكية,"Thu, 01 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMilAJBV...
29,SPY,S&P 500 and Nasdaq end higher on cool inflatio...,محايد أو غير واضح,الأسواق الأمريكية,"Tue, 14 Jul 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMivgFBV...

In [ ]:
# ☔ الودق AI — فحص الجداول وحفظ نسخة احتياطية منها
import pandas as pd

print("☔ الودق AI — فحص الجداول وحمايتها")
print("=" * 55)

table_names = [
    "wadq_news_df",
    "wadq_ticker_news_df",
    "wadq_impact_news_df",
    "wadq_global_news_df",
    "wadq_global_news_analysis_df",
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_master_report_v3_df",
    "us_technical_df",
    "wadq_us_monitoring_df",
    "wadq_global_us_unified_df",
    "wadq_global_priority_df",
    "wadq_stage41_decision_df",
    "wadq_executive_summary_df"
]

backup_tables = {}

for name in table_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        backup_tables[name] = obj.copy()
        print(f"✅ {name}: {len(obj)} صف × {len(obj.columns)} عمود")
    else:
        print(f"⚠️ {name}: غير موجود في الذاكرة")

print("=" * 55)
print(f"📦 عدد الجداول المحفوظة في النسخة الاحتياطية: {len(backup_tables)}")

☔ الودق AI — فحص الجداول وحمايتها
=======================================================
✅ wadq_news_df: 565 صف × 5 عمود
✅ wadq_ticker_news_df: 198 صف × 6 عمود
⚠️ wadq_impact_news_df: غير موجود في الذاكرة
⚠️ wadq_global_news_df: غير موجود في الذاكرة
⚠️ wadq_global_news_analysis_df: غير موجود في الذاكرة
✅ wadq_global_market_df: 17 صف × 6 عمود
⚠️ wadq_global_alerts_df: غير موجود في الذاكرة
⚠️ wadq_global_master_report_df: غير موجود في الذاكرة
⚠️ wadq_global_master_report_v2_df: غير موجود في الذاكرة
⚠️ wadq_global_master_report_v3_df: غير موجود في الذاكرة
✅ us_technical_df: 9 صف × 10 عمود
⚠️ wadq_us_monitoring_df: غير موجود في الذاكرة
⚠️ wadq_global_us_unified_df: غير موجود في الذاكرة
⚠️ wadq_global_priority_df: غير موجود في الذاكرة
⚠️ wadq_stage41_decision_df: غير موجود في الذاكرة
⚠️ wadq_executive_summary_df: غير موجود في الذاكرة
=======================================================
📦 عدد الجداول المحفوظة في النسخة الاحتياطية: 4

In [ ]:
# ☔ الودق AI — استعادة جدول الأخبار المؤثرة
# إنشاء جدول مستقل دون تعديل الجداول الأصلية

import pandas as pd
from IPython.display import display

print("☔ الودق AI — استعادة الأخبار المؤثرة")
print("=" * 50)

if "wadq_ticker_news_df" not in globals():
    print("⚠️ جدول الأخبار المرتبطة بالأسهم غير موجود.")

elif not isinstance(wadq_ticker_news_df, pd.DataFrame):
    print("⚠️ الجدول الموجود ليس DataFrame.")

else:
    # نسخة مستقلة للحفاظ على الجدول الأصلي
    wadq_impact_news_df = wadq_ticker_news_df.copy()

    # إزالة الصفوف المكررة إن وجدت
    if "ticker" in wadq_impact_news_df.columns and \
       "news_title" in wadq_impact_news_df.columns:

        wadq_impact_news_df = (
            wadq_impact_news_df
            .drop_duplicates(
                subset=["ticker", "news_title"]
            )
            .reset_index(drop=True)
        )

    print("✅ تمت استعادة جدول الأخبار المؤثرة.")
    print("عدد الصفوف:", len(wadq_impact_news_df))
    print("عدد الأعمدة:", len(wadq_impact_news_df.columns))

    display(wadq_impact_news_df.head(10))

☔ الودق AI — استعادة الأخبار المؤثرة
==================================================
✅ تمت استعادة جدول الأخبار المؤثرة.
عدد الصفوف: 198
عدد الأعمدة: 6

,ticker,news_title,sentiment,category,published,link
0,SPY,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",سلبي مبدئي,الأسواق الأمريكية,"Tue, 13 Oct 2026 21:10:57 GMT",https://news.google.com/rss/articles/CBMijwFBV...
1,QQQ,"Stock Market Today: Dow Jones, S&P 500 Futures...",محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 09:55:18 GMT",https://news.google.com/rss/articles/CBMiqAJBV...
2,SPY,"Stock Market Today: Dow Jones, S&P 500 Futures...",محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 09:55:18 GMT",https://news.google.com/rss/articles/CBMiqAJBV...
3,SPY,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...",إيجابي مبدئي,الأسواق الأمريكية,"Mon, 12 Oct 2026 18:43:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...
4,SPY,Stock Market: Will S&P 500 Open Up or Down Tod...,محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 05:48:41 GMT",https://news.google.com/rss/articles/CBMitwFBV...
5,SPY,"S&P 500, Nasdaq end lower as crude prices jump...",محايد أو غير واضح,الأسواق الأمريكية,"Thu, 08 Oct 2026 23:09:38 GMT",https://news.google.com/rss/articles/CBMinAFBV...
6,QQQ,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 12 Oct 2026 12:29:00 GMT",https://news.google.com/rss/articles/CBMikwJBV...
7,SPY,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 12 Oct 2026 12:29:00 GMT",https://news.google.com/rss/articles/CBMikwJBV...
8,SPY,"The S&P 500 Hits a New Record High, Powered by...",إيجابي مبدئي,الأسواق الأمريكية,"Tue, 06 Oct 2026 21:33:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...
9,SPY,"S&P 500 dips, Nasdaq higher after data shows m...",إيجابي مبدئي,الأسواق الأمريكية,"Wed, 30 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMipwFBV...

In [ ]:
# ☔ الودق AI — المرحلة التالية: استعادة الأخبار العالمية

import pandas as pd
from IPython.display import display

print("☔ الودق AI — استعادة جدول الأخبار العالمية")
print("=" * 55)

if "wadq_news_df" not in globals():
    print("⚠️ جدول الأخبار الأساسي غير موجود.")

elif not isinstance(wadq_news_df, pd.DataFrame):
    print("⚠️ جدول الأخبار الأساسي ليس DataFrame.")

elif wadq_news_df.empty:
    print("⚠️ جدول الأخبار الأساسي فارغ.")

else:
    # إنشاء نسخة مستقلة من الأخبار الأساسية
    wadq_global_news_df = wadq_news_df.copy()

    print("✅ تم إنشاء نسخة مستقلة من الأخبار العالمية.")
    print("عدد الأخبار:", len(wadq_global_news_df))
    print("عدد الأعمدة:", len(wadq_global_news_df.columns))
    print("أسماء الأعمدة:")
    print(wadq_global_news_df.columns.tolist())

    display(wadq_global_news_df.head(10))

☔ الودق AI — استعادة جدول الأخبار العالمية
=======================================================
✅ تم إنشاء نسخة مستقلة من الأخبار العالمية.
عدد الأخبار: 565
عدد الأعمدة: 5
أسماء الأعمدة:
['category', 'title', 'published', 'link', 'fetched_at_utc']

,category,title,published,link,fetched_at_utc
0,الأسواق الأمريكية,Nasdaq ends down as chipmakers fall and bank e...,"Tue, 13 Oct 2026 20:17:36 GMT",https://news.google.com/rss/articles/CBMivAFBV...,2026-10-13T22:10:48.887597+00:00
1,الأسواق الأمريكية,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...","Tue, 13 Oct 2026 21:10:57 GMT",https://news.google.com/rss/articles/CBMijwFBV...,2026-10-13T22:10:48.887630+00:00
2,الأسواق الأمريكية,US stocks hover near their latest record in mi...,"Mon, 12 Oct 2026 14:33:55 GMT",https://news.google.com/rss/articles/CBMixgFBV...,2026-10-13T22:10:48.887647+00:00
3,الأسواق الأمريكية,"Stock Market Today: Dow Jones, S&P 500 Futures...","Tue, 13 Oct 2026 09:55:18 GMT",https://news.google.com/rss/articles/CBMiqAJBV...,2026-10-13T22:10:48.887654+00:00
4,الأسواق الأمريكية,US stocks hover near their latest record in mi...,"Mon, 12 Oct 2026 19:26:36 GMT",https://news.google.com/rss/articles/CBMiggFBV...,2026-10-13T22:10:48.887661+00:00
5,الأسواق الأمريكية,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...","Mon, 12 Oct 2026 18:43:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...,2026-10-13T22:10:48.887668+00:00
6,الأسواق الأمريكية,"Nasdaq falls ahead of earnings, economic data ...","Mon, 12 Oct 2026 23:50:15 GMT",https://news.google.com/rss/articles/CBMipAFBV...,2026-10-13T22:10:48.887674+00:00
7,الأسواق الأمريكية,Stock Market: Will S&P 500 Open Up or Down Tod...,"Tue, 13 Oct 2026 05:48:41 GMT",https://news.google.com/rss/articles/CBMitwFBV...,2026-10-13T22:10:48.887681+00:00
8,الأسواق الأمريكية,"US Stock Futures Mixed as AI Concerns, LVMH Sa...","Tue, 13 Oct 2026 09:28:44 GMT",https://news.google.com/rss/articles/CBMilAFBV...,2026-10-13T22:10:48.887687+00:00
9,الأسواق الأمريكية,"S&P 500, Nasdaq end lower as crude prices jump...","Thu, 08 Oct 2026 23:09:38 GMT",https://news.google.com/rss/articles/CBMinAFBV...,2026-10-13T22:10:48.887698+00:00

In [ ]:
# ☔ الودق AI — استعادة تحليل الأخبار العالمية
# إنشاء جدول تحليل جديد دون تعديل الجداول السابقة

import pandas as pd
from IPython.display import display

print("☔ الودق AI — استعادة تحليل الأخبار العالمية")
print("=" * 55)

if (
    "wadq_global_news_df" not in globals()
    or not isinstance(wadq_global_news_df, pd.DataFrame)
):
    print("⚠️ جدول الأخبار العالمية غير موجود.")

elif wadq_global_news_df.empty:
    print("⚠️ جدول الأخبار العالمية فارغ.")

else:
    # إنشاء نسخة مستقلة من الأخبار للتحليل
    news = wadq_global_news_df.copy()

    # تصنيف أولي للأخبار حسب العنوان
    positive_words = [
        "rise", "rises", "gain", "gains", "surge",
        "soar", "record high", "growth", "rally",
        "ارتفاع", "صعود", "مكاسب", "نمو", "انتعاش"
    ]

    negative_words = [
        "fall", "falls", "drop", "drops", "crash",
        "decline", "loss", "selloff", "slip",
        "هبوط", "انخفاض", "تراجع", "خسائر", "تراجع حاد"
    ]

    def classify_news(title):
        text = str(title).lower()

        positive = sum(word in text for word in positive_words)
        negative = sum(word in text for word in negative_words)

        if positive > negative:
            return "إيجابي مبدئي"
        elif negative > positive:
            return "سلبي مبدئي"
        else:
            return "محايد أو غير واضح"

    news["sentiment"] = news["title"].apply(classify_news)

    # تحليل الأخبار بحسب التصنيف
    wadq_global_news_analysis_df = (
        news.groupby("category", dropna=False)
        .agg(
            عدد_الأخبار=("title", "count"),
            أخبار_إيجابية=("sentiment",
                lambda x: (x == "إيجابي مبدئي").sum()),
            أخبار_سلبية=("sentiment",
                lambda x: (x == "سلبي مبدئي").sum()),
            أخبار_محايدة=("sentiment",
                lambda x: (x == "محايد أو غير واضح").sum())
        )
        .reset_index()
    )

    print("✅ تم إنشاء جدول تحليل الأخبار العالمية.")
    print("عدد التصنيفات:", len(wadq_global_news_analysis_df))
    print("عدد الأعمدة:",
          len(wadq_global_news_analysis_df.columns))

    display(wadq_global_news_analysis_df)

    print("\n✅ تم الاحتفاظ بجدول الأخبار الأصلي دون تعديل.")
    print("⚠️ التصنيف مبدئي ويعتمد على كلمات العناوين.")

☔ الودق AI — استعادة تحليل الأخبار العالمية
=======================================================
✅ تم إنشاء جدول تحليل الأخبار العالمية.
عدد التصنيفات: 7
عدد الأعمدة: 5

            category  عدد_الأخبار  أخبار_إيجابية  أخبار_سلبية  أخبار_محايدة
0   الأخبار العالمية           75              8            5            62
1  الأسواق الأمريكية          100             20           25            55
2   الاقتصاد العالمي          100             10            4            86
3       الذهب والنفط           76             12           17            47
4      السوق السعودي           44              8            1            35
5  الشركات الأمريكية           70              9            1            60
6    الفائدة والتضخم          100              8            3            89

✅ تم الاحتفاظ بجدول الأخبار الأصلي دون تعديل.
⚠️ التصنيف مبدئي ويعتمد على كلمات العناوين.

In [ ]:
# ==========================================================
# ☔ الودق AI
# المرحلة التالية: دمج أخبار الأسهم مع التحليل الفني
# إنشاء جدول جديد دون حذف أو تعديل الجداول السابقة
# ==========================================================

import pandas as pd
from IPython.display import display

print("☔ الودق AI — دمج الأخبار مع التحليل الفني")
print("=" * 60)

# التأكد من وجود الجداول المطلوبة
required_tables = [
    "wadq_ticker_news_df",
    "us_technical_df"
]

missing_tables = [
    name for name in required_tables
    if name not in globals()
    or not isinstance(globals()[name], pd.DataFrame)
]

if missing_tables:
    print("⚠️ الجداول التالية غير متاحة:")
    for name in missing_tables:
        print("-", name)

else:
    # نسخ مستقلة للحفاظ على الجداول الأصلية
    news = wadq_ticker_news_df.copy()
    technical = us_technical_df.copy()

    # تحديد عمود الرمز في التحليل الفني
    possible_symbol_columns = [
        "الرمز", "ticker", "symbol", "Symbol", "Ticker"
    ]

    symbol_column = next(
        (col for col in possible_symbol_columns
         if col in technical.columns),
        None
    )

    if "ticker" not in news.columns:
        print("⚠️ لم يتم العثور على عمود ticker في جدول الأخبار.")

    elif symbol_column is None:
        print("⚠️ لم يتم العثور على عمود رموز الأسهم في التحليل الفني.")

    else:
        # توحيد الرموز قبل الدمج
        news["ticker"] = (
            news["ticker"].astype(str).str.strip().str.upper()
        )

        technical[symbol_column] = (
            technical[symbol_column]
            .astype(str).str.strip().str.upper()
        )

        # حذف أي تكرار للرمز في نسخة التحليل الفني فقط
        technical = technical.drop_duplicates(
            subset=[symbol_column],
            keep="last"
        )

        # الدمج مع الاحتفاظ بجميع أخبار الأسهم
        wadq_us_news_technical_df = news.merge(
            technical,
            left_on="ticker",
            right_on=symbol_column,
            how="left",
            suffixes=("_خبر", "_فني")
        )

        print("✅ تم إنشاء جدول دمج الأخبار والتحليل الفني.")
        print("📊 عدد الصفوف:", len(wadq_us_news_technical_df))
        print("📋 عدد الأعمدة:",
              len(wadq_us_news_technical_df.columns))
        print("📈 عدد رموز الأسهم:",
              wadq_us_news_technical_df["ticker"].nunique())

        # عرض النتيجة
        display(wadq_us_news_technical_df.head(15))

        print("\n✅ تم الاحتفاظ بالجداول الأصلية دون تعديل.")
        print("📌 اسم الجدول الجديد:")
        print("wadq_us_news_technical_df")

☔ الودق AI — دمج الأخبار مع التحليل الفني
============================================================
✅ تم إنشاء جدول دمج الأخبار والتحليل الفني.
📊 عدد الصفوف: 198
📋 عدد الأعمدة: 16
📈 عدد رموز الأسهم: 9

,ticker,news_title,sentiment,category,published,link,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,SPY,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",سلبي مبدئي,الأسواق الأمريكية,"Tue, 13 Oct 2026 21:10:57 GMT",https://news.google.com/rss/articles/CBMijwFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
1,QQQ,"Stock Market Today: Dow Jones, S&P 500 Futures...",محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 09:55:18 GMT",https://news.google.com/rss/articles/CBMiqAJBV...,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد
2,SPY,"Stock Market Today: Dow Jones, S&P 500 Futures...",محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 09:55:18 GMT",https://news.google.com/rss/articles/CBMiqAJBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
3,SPY,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...",إيجابي مبدئي,الأسواق الأمريكية,"Mon, 12 Oct 2026 18:43:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
4,SPY,Stock Market: Will S&P 500 Open Up or Down Tod...,محايد أو غير واضح,الأسواق الأمريكية,"Tue, 13 Oct 2026 05:48:41 GMT",https://news.google.com/rss/articles/CBMitwFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
5,SPY,"S&P 500, Nasdaq end lower as crude prices jump...",محايد أو غير واضح,الأسواق الأمريكية,"Thu, 08 Oct 2026 23:09:38 GMT",https://news.google.com/rss/articles/CBMinAFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
6,QQQ,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 12 Oct 2026 12:29:00 GMT",https://news.google.com/rss/articles/CBMikwJBV...,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد
7,SPY,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 12 Oct 2026 12:29:00 GMT",https://news.google.com/rss/articles/CBMikwJBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
8,SPY,"The S&P 500 Hits a New Record High, Powered by...",إيجابي مبدئي,الأسواق الأمريكية,"Tue, 06 Oct 2026 21:33:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
9,SPY,"S&P 500 dips, Nasdaq higher after data shows m...",إيجابي مبدئي,الأسواق الأمريكية,"Wed, 30 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMipwFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
10,QQQ,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,الأسواق الأمريكية,"Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد
11,SPY,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,الأسواق الأمريكية,"Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
12,SPY,S&P 500 ends marginally lower as investors foc...,محايد أو غير واضح,الأسواق الأمريكية,"Thu, 24 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMisgFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
13,SPY,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...",محايد أو غير واضح,الأسواق الأمريكية,"Wed, 07 Oct 2026 20:11:09 GMT",https://news.google.com/rss/articles/CBMiuAFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد
14,SPY,U.S. stock market drops: S&P 500 and Nasdaq fa...,سلبي مبدئي,الأسواق الأمريكية,"Thu, 08 Oct 2026 15:04:08 GMT",https://news.google.com/rss/articles/CBMi2wFBV...,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد

✅ تم الاحتفاظ بالجداول الأصلية دون تعديل.
📌 اسم الجدول الجديد:
wadq_us_news_technical_df

In [ ]:
# ==========================================================
# ☔ الودق AI — استعادة جدول مراقبة الأسهم الأمريكية
# إنشاء جدول جديد دون حذف أو تعديل الجداول السابقة
# ==========================================================

import pandas as pd
from IPython.display import display

print("☔ الودق AI — استعادة جدول مراقبة الأسهم الأمريكية")
print("=" * 60)

# التحقق من وجود الجداول المطلوبة
if (
    "us_technical_df" not in globals()
    or not isinstance(us_technical_df, pd.DataFrame)
):
    print("⚠️ جدول التحليل الفني غير موجود.")

elif (
    "wadq_us_news_technical_df" not in globals()
    or not isinstance(wadq_us_news_technical_df, pd.DataFrame)
):
    print("⚠️ جدول دمج الأخبار والتحليل الفني غير موجود.")

else:
    # نسخ مستقلة للحفاظ على الجداول الأصلية
    technical = us_technical_df.copy()
    news = wadq_us_news_technical_df.copy()

    # تحديد عمود الرمز في التحليل الفني
    symbol_candidates = [
        "الرمز", "ticker", "symbol", "Symbol", "Ticker"
    ]

    symbol_col = next(
        (c for c in symbol_candidates if c in technical.columns),
        None
    )

    if symbol_col is None or "ticker" not in news.columns:
        print("⚠️ تعذر تحديد عمود رمز السهم في أحد الجدولين.")
        print("أعمدة التحليل الفني:", technical.columns.tolist())
        print("أعمدة الأخبار:", news.columns.tolist())

    else:
        # توحيد الرموز في النسخ المستقلة
        technical[symbol_col] = (
            technical[symbol_col].astype(str).str.strip().str.upper()
        )

        news["ticker"] = (
            news["ticker"].astype(str).str.strip().str.upper()
        )

        # بناء ملخص الأخبار لكل سهم
        news_summary = (
            news.groupby("ticker")
            .agg(
                عدد_الأخبار=("news_title", "count"),
                ملخص_الأخبار=(
                    "news_title",
                    lambda x: " | ".join(
                        x.dropna().astype(str).head(3).tolist()
                    )
                )
            )
            .reset_index()
        )

        # دمج ملخص الأخبار مع التحليل الفني
        wadq_us_monitoring_df = technical.merge(
            news_summary,
            left_on=symbol_col,
            right_on="ticker",
            how="left",
            suffixes=("", "_news")
        )

        # معالجة الأسهم التي لا توجد لها أخبار مرتبطة
        wadq_us_monitoring_df["عدد_الأخبار"] = (
            wadq_us_monitoring_df["عدد_الأخبار"]
            .fillna(0)
            .astype(int)
        )

        wadq_us_monitoring_df["ملخص_الأخبار"] = (
            wadq_us_monitoring_df["ملخص_الأخبار"]
            .fillna("لا توجد أخبار مرتبطة في الجدول الحالي")
        )

        print("✅ تم إنشاء جدول مراقبة الأسهم الأمريكية.")
        print("📊 عدد الأسهم:", len(wadq_us_monitoring_df))
        print("📋 عدد الأعمدة:",
              len(wadq_us_monitoring_df.columns))
        print("📰 إجمالي الأخبار المرتبطة:",
              wadq_us_monitoring_df["عدد_الأخبار"].sum())

        display(wadq_us_monitoring_df)

        print("\n✅ الجداول الأصلية لم يتم تعديلها.")
        print("📌 اسم الجدول: wadq_us_monitoring_df")

☔ الودق AI — استعادة جدول مراقبة الأسهم الأمريكية
============================================================
✅ تم إنشاء جدول مراقبة الأسهم الأمريكية.
📊 عدد الأسهم: 9
📋 عدد الأعمدة: 13
📰 إجمالي الأخبار المرتبطة: 198

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,NVDA,47,Wall Street stocks end tad lower after hot inf...
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,TSLA,20,Zacks Investment Ideas feature highlights: App...
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد,AAPL,1,"Are Amazon, Apple stocks overpriced? Here are ..."
3,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,MSFT,35,Zacks Investment Ideas feature highlights: App...
4,أمازون,AMZN,258.58,252.83,258.35,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط,AMZN,17,Zacks Investment Ideas feature highlights: App...
5,ألفابت,GOOGL,353.78,346.53,345.69,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد,GOOGL,22,"S&P 500, Nasdaq close lower, dragged by Alphab..."
6,ميتا,META,762.50,727.58,646.59,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد,META,2,I Predicted That Oracle and Netflix Would Join...
7,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد,QQQ,4,"Stock Market Today: Dow Jones, S&P 500 Futures..."
8,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد,SPY,50,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ..."

✅ الجداول الأصلية لم يتم تعديلها.
📌 اسم الجدول: wadq_us_monitoring_df

In [ ]:
# =====================================================
# ☔ الودق AI — استعادة الجداول المفيدة قبل المرحلة 41
# خلية فحص آمنة: لا تحذف ولا تعدّل الجداول الأصلية
# =====================================================

import pandas as pd
from IPython.display import display

wadq_recovery_names = [
    "wadq_news_df",
    "wadq_ticker_news_df",
    "wadq_impact_news_df",
    "wadq_global_news_df",
    "wadq_global_news_analysis_df",
    "wadq_global_market_df",
    "us_technical_df",
    "wadq_us_news_technical_df",
    "wadq_us_monitoring_df",
    "wadq_global_priority_df",
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_stage41_decision_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_master_report_v3_df",
    "wadq_integrated_df",
]

print("☔ الودق AI — تقرير استعادة الجداول")
print("=" * 60)

wadq_recovery_available = {}

for name in wadq_recovery_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        wadq_recovery_available[name] = obj

        print(
            f"✅ {name} | "
            f"الصفوف: {len(obj)} | "
            f"الأعمدة: {len(obj.columns)}"
        )
    else:
        print(f"⚠️ {name}: غير موجود في ذاكرة التشغيل")

print("=" * 60)
print(f"إجمالي الجداول المفيدة الموجودة: {len(wadq_recovery_available)}")

print("\n📌 فحص جدول المرحلة 41:")

if "wadq_stage41_decision_df" in wadq_recovery_available:
    display(wadq_recovery_available["wadq_stage41_decision_df"].head(10))
else:
    print("لم يُعثر على جدول المرحلة 41 في الذاكرة الحالية.")
    print("سنحدد مصدر البيانات المناسب لإعادة بنائه دون حذف الجداول الأصلية.")

☔ الودق AI — تقرير استعادة الجداول
============================================================
✅ wadq_news_df | الصفوف: 565 | الأعمدة: 5
✅ wadq_ticker_news_df | الصفوف: 198 | الأعمدة: 6
✅ wadq_impact_news_df | الصفوف: 198 | الأعمدة: 6
✅ wadq_global_news_df | الصفوف: 565 | الأعمدة: 5
✅ wadq_global_news_analysis_df | الصفوف: 7 | الأعمدة: 5
✅ wadq_global_market_df | الصفوف: 17 | الأعمدة: 6
✅ us_technical_df | الصفوف: 9 | الأعمدة: 10
✅ wadq_us_news_technical_df | الصفوف: 198 | الأعمدة: 16
✅ wadq_us_monitoring_df | الصفوف: 9 | الأعمدة: 13
✅ wadq_global_priority_df | الصفوف: 9 | الأعمدة: 15
⚠️ wadq_global_us_unified_df: غير موجود في ذاكرة التشغيل
⚠️ wadq_executive_summary_df: غير موجود في ذاكرة التشغيل
⚠️ wadq_stage41_decision_df: غير موجود في ذاكرة التشغيل
⚠️ wadq_global_master_report_df: غير موجود في ذاكرة التشغيل
⚠️ wadq_global_master_report_v2_df: غير موجود في ذاكرة التشغيل
⚠️ wadq_global_master_report_v3_df: غير موجود في ذاكرة التشغيل
✅ wadq_integrated_df | الصفوف: 9 | الأعمدة: 15
============================================================
إجمالي الجداول المفيدة الموجودة: 11

📌 فحص جدول المرحلة 41:
لم يُعثر على جدول المرحلة 41 في الذاكرة الحالية.
سنحدد مصدر البيانات المناسب لإعادة بنائه دون حذف الجداول الأصلية.

In [ ]:
# ============================================================
# 🌧️ الودق AI
# استعادة الجداول المفقودة استعدادًا للمرحلة 41
# لا يحذف أي جدول موجود ولا يعدل الجداول الأصلية
# ============================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI — استعادة الجداول المفقودة")
print("=" * 65)

# ------------------------------------------------------------
# 1. فحص الجداول الموجودة
# ------------------------------------------------------------

source_names = [
    "wadq_news_df",
    "wadq_ticker_news_df",
    "wadq_global_news_df",
    "wadq_global_market_df",
    "us_technical_df",
    "wadq_us_news_technical_df",
    "wadq_us_monitoring_df",
    "wadq_global_priority_df",
    "wadq_integrated_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_master_report_v3_df",
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_stage41_decision_df",
]

print("\n📋 فحص الجداول:")
for name in source_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name}: {obj.shape[0]} صف × {obj.shape[1]} عمود")
    else:
        print(f"⚠️ {name}: غير موجود حاليًا")

# ------------------------------------------------------------
# 2. تحديد أعمدة الأصل والرمز والسعر
# ------------------------------------------------------------

def wadq_get_column(df, candidates):
    for col in candidates:
        if col in df.columns:
            return col
    return None


def wadq_standardize_asset_table(df, default_type="غير محدد"):
    """إنشاء نسخة مستقلة بأسماء الأعمدة الأساسية الموحدة."""

    if not isinstance(df, pd.DataFrame) or df.empty:
        return pd.DataFrame()

    result = df.copy()

    aliases = {
        "النوع": ["نوع الأصل", "نوع", "asset_type", "type"],
        "الأصل": ["الأصل", "اسم الأصل", "اسم السهم", "السهم",
                  "asset", "name", "company"],
        "الرمز": ["الرمز", "رمز السهم", "ticker", "symbol",
                  "Ticker", "Symbol"],
        "السعر": ["السعر", "أحدث سعر", "آخر إغلاق",
                  "latest_price", "price", "Close"],
        "التغير اليومي %": [
            "التغير اليومي %",
            "التغير %",
            "التغير",
            "daily_change_pct",
            "change_percent",
            "Change %"
        ],
    }

    for standard, candidates in aliases.items():
        if standard not in result.columns:
            found = wadq_get_column(result, candidates)

            if found is not None:
                result[standard] = result[found]

    if "الأصل" not in result.columns:
        result["الأصل"] = ""

    if "الرمز" not in result.columns:
        result["الرمز"] = ""

    if "نوع الأصل" not in result.columns:
        result["نوع الأصل"] = default_type

    # استخدام الرمز اسمًا للأصل عند غياب الاسم
    result["الأصل"] = (
        result["الأصل"].fillna("").astype(str)
    )

    result["الرمز"] = (
        result["الرمز"].fillna("").astype(str)
    )

    missing_name = (
        result["الأصل"].eq("")
        | result["الأصل"].eq("nan")
    )

    result.loc[missing_name, "الأصل"] = (
        result.loc[missing_name, "الرمز"]
    )

    return result


# ------------------------------------------------------------
# 3. استعادة التقرير العالمي الأساسي
# ------------------------------------------------------------

master_sources = [
    "wadq_global_master_report_df",
    "wadq_global_master_report_v3_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_market_df",
]

master_base = None

for name in master_sources:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame) and not obj.empty:
        master_base = obj.copy()
        print(f"\n📌 مصدر التقرير العالمي: {name}")
        break

if master_base is None:
    print("\n❌ لم يُعثر على مصدر مناسب للتقرير العالمي.")
    print("لن يتم إنشاء تقرير عالمي فارغ أو اختلاق بيانات.")
else:

    # إعادة إنشاء التقرير الأساسي عند فقدانه فقط
    if not isinstance(
        globals().get("wadq_global_master_report_df"),
        pd.DataFrame
    ):
        wadq_global_master_report_df = master_base.copy()

    # استعادة النسخة الثانية عند فقدانها
    if not isinstance(
        globals().get("wadq_global_master_report_v2_df"),
        pd.DataFrame
    ):
        wadq_global_master_report_v2_df = (
            wadq_global_master_report_df.copy()
        )

    # استعادة النسخة الثالثة عند فقدانها
    if not isinstance(
        globals().get("wadq_global_master_report_v3_df"),
        pd.DataFrame
    ):
        wadq_global_master_report_v3_df = (
            wadq_global_master_report_v2_df.copy()
        )

# ------------------------------------------------------------
# 4. إنشاء الجدول الموحد من المصادر المتاحة
# ------------------------------------------------------------

unified_existing = globals().get(
    "wadq_global_us_unified_df"
)

if not isinstance(unified_existing, pd.DataFrame):

    asset_tables = []

    global_table = globals().get("wadq_global_master_report_v3_df")

    if isinstance(global_table, pd.DataFrame) and not global_table.empty:
        temp = wadq_standardize_asset_table(
            global_table,
            default_type="أصل عالمي"
        )
        asset_tables.append(temp)

    us_table = globals().get("wadq_us_monitoring_df")

    if isinstance(us_table, pd.DataFrame) and not us_table.empty:
        temp = wadq_standardize_asset_table(
            us_table,
            default_type="سهم أمريكي"
        )
        asset_tables.append(temp)

    if asset_tables:
        wadq_global_us_unified_df = pd.concat(
            asset_tables,
            ignore_index=True,
            sort=False
        )

        # إزالة التكرار فقط عندما يتكرر الرمز نفسه
        if "الرمز" in wadq_global_us_unified_df.columns:
            wadq_global_us_unified_df = (
                wadq_global_us_unified_df.drop_duplicates(
                    subset=["الرمز"],
                    keep="first"
                ).reset_index(drop=True)
            )

        print("\n✅ تمت إعادة بناء الجدول الموحد من المصادر المتاحة.")
    else:
        print("\n⚠️ لم تتوفر مصادر كافية لإعادة بناء الجدول الموحد.")

# ------------------------------------------------------------
# 5. استعادة جدول قرار المرحلة 41
# ------------------------------------------------------------

unified_table = globals().get("wadq_global_us_unified_df")

if (
    not isinstance(
        globals().get("wadq_stage41_decision_df"),
        pd.DataFrame
    )
    and isinstance(unified_table, pd.DataFrame)
    and not unified_table.empty
):
    wadq_stage41_decision_df = unified_table.copy()

    print("✅ تمت استعادة جدول قرار المرحلة 41.")

# ------------------------------------------------------------
# 6. إنشاء ملخص تنفيذي عند فقدانه
# ------------------------------------------------------------

if not isinstance(
    globals().get("wadq_executive_summary_df"),
    pd.DataFrame
):
    summary_source = globals().get("wadq_stage41_decision_df")

    if not isinstance(summary_source, pd.DataFrame):
        summary_source = globals().get("wadq_global_us_unified_df")

    if isinstance(summary_source, pd.DataFrame) and not summary_source.empty:

        wadq_executive_summary_df = pd.DataFrame({
            "المؤشر": [
                "إجمالي الأصول",
                "عدد الأعمدة",
                "عدد الأسهم الأمريكية",
            ],
            "القيمة": [
                len(summary_source),
                len(summary_source.columns),
                (
                    summary_source["نوع الأصل"]
                    .astype(str)
                    .str.contains("أمريكي", na=False)
                    .sum()
                    if "نوع الأصل" in summary_source.columns
                    else "غير محدد"
                ),
            ]
        })

        print("✅ تمت استعادة الملخص التنفيذي الأولي.")

# ------------------------------------------------------------
# 7. تقرير نهائي عن الجداول الستة
# ------------------------------------------------------------

recovery_names = [
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_stage41_decision_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_master_report_v3_df",
]

print("\n" + "=" * 65)
print("🌧️ نتيجة استعادة الجداول")
print("=" * 65)

recovered_count = 0

for name in recovery_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(
            f"✅ {name}: "
            f"{obj.shape[0]} صف × {obj.shape[1]} عمود"
        )
        recovered_count += 1
    else:
        print(f"⚠️ {name}: يحتاج إلى استعادة إضافية")

print("-" * 65)
print(f"📊 الجداول الستة الموجودة الآن: {recovered_count} من 6")

if isinstance(
    globals().get("wadq_stage41_decision_df"),
    pd.DataFrame
):
    print("\n📌 معاينة جدول قرار المرحلة 41:")
    display(wadq_stage41_decision_df.head(10))

print("\n⚠️ هذه إعادة بناء أولية من البيانات المتاحة،")
print("وليست ضمانًا لاسترجاع جميع أعمدة التقارير الأصلية.")
print("🌧️ الودق AI — انتهى فحص الاستعادة.")

🌧️ الودق AI — استعادة الجداول المفقودة
=================================================================

📋 فحص الجداول:
✅ wadq_news_df: 565 صف × 5 عمود
✅ wadq_ticker_news_df: 198 صف × 6 عمود
✅ wadq_global_news_df: 565 صف × 5 عمود
✅ wadq_global_market_df: 17 صف × 6 عمود
✅ us_technical_df: 9 صف × 10 عمود
✅ wadq_us_news_technical_df: 198 صف × 16 عمود
✅ wadq_us_monitoring_df: 9 صف × 13 عمود
✅ wadq_global_priority_df: 9 صف × 15 عمود
✅ wadq_integrated_df: 9 صف × 15 عمود
⚠️ wadq_global_master_report_df: غير موجود حاليًا
⚠️ wadq_global_master_report_v2_df: غير موجود حاليًا
⚠️ wadq_global_master_report_v3_df: غير موجود حاليًا
⚠️ wadq_global_us_unified_df: غير موجود حاليًا
⚠️ wadq_executive_summary_df: غير موجود حاليًا
⚠️ wadq_stage41_decision_df: غير موجود حاليًا

📌 مصدر التقرير العالمي: wadq_global_market_df

✅ تمت إعادة بناء الجدول الموحد من المصادر المتاحة.
✅ تمت استعادة جدول قرار المرحلة 41.
✅ تمت استعادة الملخص التنفيذي الأولي.

=================================================================
🌧️ نتيجة استعادة الجداول
=================================================================
✅ wadq_global_us_unified_df: 26 صف × 20 عمود
✅ wadq_executive_summary_df: 3 صف × 2 عمود
✅ wadq_stage41_decision_df: 26 صف × 20 عمود
✅ wadq_global_master_report_df: 17 صف × 6 عمود
✅ wadq_global_master_report_v2_df: 17 صف × 6 عمود
✅ wadq_global_master_report_v3_df: 17 صف × 6 عمود
-----------------------------------------------------------------
📊 الجداول الستة الموجودة الآن: 6 من 6

📌 معاينة جدول قرار المرحلة 41:

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,نوع الأصل,السهم,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,السعر
0,^GSPC,S&P 500 - أمريكا,7805.450195,7807.240234,-0.022928,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,^IXIC,Nasdaq Composite - أمريكا,27204.380859,27245.900391,-0.152388,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,^DJI,Dow Jones - أمريكا,51670.101562,51850.550781,-0.348018,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,^GDAXI,DAX - ألمانيا,25259.900391,25277.679688,-0.070336,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,^FCHI,CAC 40 - فرنسا,7827.629883,7832.879883,-0.067025,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,^FTSE,FTSE 100 - بريطانيا,10650.330078,10656.299805,-0.056021,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,2026-10-09,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,^HSI,Hang Seng - هونغ كونغ,24271.199219,24211.349609,0.247197,2026-10-12,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,GC=F,الذهب,4183.000000,4190.600098,-0.181361,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,SI=F,الفضة,59.369999,60.140999,-1.281987,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

⚠️ هذه إعادة بناء أولية من البيانات المتاحة،
وليست ضمانًا لاسترجاع جميع أعمدة التقارير الأصلية.
🌧️ الودق AI — انتهى فحص الاستعادة.

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 42
# تصنيف حركة الأصول وإعداد ملخص السوق
# خلية جديدة — دون تعديل الجداول السابقة
# ============================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI — المرحلة 42: تحليل حركة السوق")
print("=" * 60)

# 1. التأكد من وجود جدول المرحلة 41
if (
    "wadq_stage41_decision_df" not in globals()
    or not isinstance(wadq_stage41_decision_df, pd.DataFrame)
    or wadq_stage41_decision_df.empty
):
    raise ValueError(
        "لم يتم العثور على جدول المرحلة 41 أو أنه فارغ. "
        "توقّف التنفيذ حفاظًا على البيانات."
    )

# 2. إنشاء نسخة مستقلة
wadq_stage42_market_df = wadq_stage41_decision_df.copy()

# 3. التأكد من وجود عمود التغير اليومي
if "التغير اليومي %" not in wadq_stage42_market_df.columns:
    raise ValueError(
        "عمود التغير اليومي % غير موجود. "
        "لن يتم إنشاء تصنيف غير موثوق."
    )

# 4. تحويل التغير اليومي إلى أرقام
wadq_stage42_market_df["التغير اليومي %"] = pd.to_numeric(
    wadq_stage42_market_df["التغير اليومي %"],
    errors="coerce"
)

# 5. تصنيف حركة كل أصل
def wadq_stage42_classify(change):
    if pd.isna(change):
        return "⚪ بيانات غير متاحة"
    elif change >= 1:
        return "🟢 ارتفاع ملحوظ"
    elif change <= -1:
        return "🔴 انخفاض ملحوظ"
    else:
        return "🟡 حركة محدودة"

wadq_stage42_market_df["تصنيف الحركة"] = (
    wadq_stage42_market_df["التغير اليومي %"]
    .apply(wadq_stage42_classify)
)

# 6. ترتيب الأصول من الأعلى تغيرًا إلى الأقل
wadq_stage42_market_df = (
    wadq_stage42_market_df
    .sort_values(
        by="التغير اليومي %",
        ascending=False,
        na_position="last"
    )
    .reset_index(drop=True)
)

# 7. إنشاء الملخص الإحصائي
movement_order = [
    "🟢 ارتفاع ملحوظ",
    "🔴 انخفاض ملحوظ",
    "🟡 حركة محدودة",
    "⚪ بيانات غير متاحة"
]

movement_counts = (
    wadq_stage42_market_df["تصنيف الحركة"]
    .value_counts()
    .reindex(movement_order, fill_value=0)
)

wadq_stage42_summary_df = pd.DataFrame({
    "تصنيف الحركة": movement_counts.index,
    "عدد الأصول": movement_counts.values
})

# 8. عرض النتائج
print("\n✅ اكتمل تحليل حركة الأصول.")
print("📊 عدد الأصول:", len(wadq_stage42_market_df))
print("📋 عدد أعمدة جدول التحليل:", len(wadq_stage42_market_df.columns))

print("\n📈 جدول المرحلة 42:")
display(wadq_stage42_market_df)

print("\n📊 ملخص حركة السوق:")
display(wadq_stage42_summary_df)

print("\n📌 أسماء الجداول الجديدة:")
print("1. wadq_stage42_market_df")
print("2. wadq_stage42_summary_df")

print("\n⚠️ هذا تصنيف لحركة الأسعار وليس توصية شراء أو بيع.")
print("🌧️ الودق AI — انتهت المرحلة 42.")

🌧️ الودق AI — المرحلة 42: تحليل حركة السوق
============================================================

✅ اكتمل تحليل حركة الأصول.
📊 عدد الأصول: 26
📋 عدد أعمدة جدول التحليل: 21

📈 جدول المرحلة 42:

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,نوع الأصل,السهم,آخر إغلاق,المتوسط 20,...,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,السعر,تصنيف الحركة
0,NG=F,الغاز الطبيعي,3.322000,3.167000,4.894221,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
1,ETH-USD,إيثيريوم,2507.969971,2444.357422,2.602424,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
2,BTC-USD,بيتكوين,83349.679688,81762.562500,1.941129,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
3,CL=F,النفط الأمريكي,94.809998,93.739998,1.141455,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
4,^HSI,Hang Seng - هونغ كونغ,24271.199219,24211.349609,0.247197,2026-10-12,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
5,JPY=X,الدولار مقابل الين,158.320999,158.203003,0.074585,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,2026-10-09,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
7,^GSPC,S&P 500 - أمريكا,7805.450195,7807.240234,-0.022928,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
8,EURUSD=X,اليورو مقابل الدولار,1.120072,1.120473,-0.035833,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
9,^FTSE,FTSE 100 - بريطانيا,10650.330078,10656.299805,-0.056021,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
10,^FCHI,CAC 40 - فرنسا,7827.629883,7832.879883,-0.067025,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
11,^GDAXI,DAX - ألمانيا,25259.900391,25277.679688,-0.070336,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
12,^IXIC,Nasdaq Composite - أمريكا,27204.380859,27245.900391,-0.152388,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
13,GC=F,الذهب,4183.000000,4190.600098,-0.181361,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
14,BZ=F,نفط برنت,106.370003,106.650002,-0.262540,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
15,^DJI,Dow Jones - أمريكا,51670.101562,51850.550781,-0.348018,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
16,SI=F,الفضة,59.369999,60.140999,-1.281987,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🔴 انخفاض ملحوظ
17,NVDA,إنفيديا,NaN,NaN,NaN,NaN,سهم أمريكي,إنفيديا,228.52,228.32,...,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,NVDA,47.0,Wall Street stocks end tad lower after hot inf...,228.52,⚪ بيانات غير متاحة
18,TSLA,تسلا,NaN,NaN,NaN,NaN,سهم أمريكي,تسلا,375.23,370.54,...,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,TSLA,20.0,Zacks Investment Ideas feature highlights: App...,375.23,⚪ بيانات غير متاحة
19,AAPL,آبل,NaN,NaN,NaN,NaN,سهم أمريكي,آبل,341.27,336.28,...,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد,AAPL,1.0,"Are Amazon, Apple stocks overpriced? Here are ...",341.27,⚪ بيانات غير متاحة
20,MSFT,مايكروسوفت,NaN,NaN,NaN,NaN,سهم أمريكي,مايكروسوفت,543.45,514.20,...,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,MSFT,35.0,Zacks Investment Ideas feature highlights: App...,543.45,⚪ بيانات غير متاحة
21,AMZN,أمازون,NaN,NaN,NaN,NaN,سهم أمريكي,أمازون,258.58,252.83,...,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط,AMZN,17.0,Zacks Investment Ideas feature highlights: App...,258.58,⚪ بيانات غير متاحة
22,GOOGL,ألفابت,NaN,NaN,NaN,NaN,سهم أمريكي,ألفابت,353.78,346.53,...,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد,GOOGL,22.0,"S&P 500, Nasdaq close lower, dragged by Alphab...",353.78,⚪ بيانات غير متاحة
23,META,ميتا,NaN,NaN,NaN,NaN,سهم أمريكي,ميتا,762.50,727.58,...,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد,META,2.0,I Predicted That Oracle and Netflix Would Join...,762.50,⚪ بيانات غير متاحة
24,QQQ,ناسداك 100,NaN,NaN,NaN,NaN,سهم أمريكي,ناسداك 100,743.57,741.22,...,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد,QQQ,4.0,"Stock Market Today: Dow Jones, S&P 500 Futures...",743.57,⚪ بيانات غير متاحة
25,SPY,ستاندرد آند بورز 500,NaN,NaN,NaN,NaN,سهم أمريكي,ستاندرد آند بورز 500,778.01,769.68,...,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد,SPY,50.0,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",778.01,⚪ بيانات غير متاحة

📊 ملخص حركة السوق:

         تصنيف الحركة  عدد الأصول
0      🟢 ارتفاع ملحوظ           4
1      🔴 انخفاض ملحوظ           1
2       🟡 حركة محدودة          12
3  ⚪ بيانات غير متاحة           9

📌 أسماء الجداول الجديدة:
1. wadq_stage42_market_df
2. wadq_stage42_summary_df

⚠️ هذا تصنيف لحركة الأسعار وليس توصية شراء أو بيع.
🌧️ الودق AI — انتهت المرحلة 42.

In [ ]:
# 🌧️ الودق AI — فحص بيانات المرحلة 42
import pandas as pd
from IPython.display import display

print("🔍 فحص مصادر البيانات قبل إصلاح المرحلة 42")
print("=" * 60)

tables_to_check = [
    "wadq_stage41_decision_df",
    "wadq_global_us_unified_df",
    "wadq_global_market_df",
    "wadq_us_monitoring_df",
    "us_technical_df",
    "wadq_stage42_market_df"
]

for name in tables_to_check:
    df = globals().get(name)

    print(f"\n📌 الجدول: {name}")

    if isinstance(df, pd.DataFrame):
        print("الحجم:", df.shape)
        print("الأعمدة:", df.columns.tolist())

        important_cols = [
            c for c in df.columns
            if any(word in str(c).lower() for word in [
                "تغير", "التغير", "change", "price",
                "السعر", "close", "الرمز", "ticker",
                "rsi", "macd"
            ])
        ]

        if important_cols:
            print("نسبة البيانات المتاحة:")
            print(
                (df[important_cols].notna().mean() * 100)
                .round(1)
                .astype(str)
                .add("%")
            )
    else:
        print("⚠️ الجدول غير موجود في الذاكرة الحالية")

print("\n✅ انتهى الفحص دون تعديل الجداول الأصلية.")

🔍 فحص مصادر البيانات قبل إصلاح المرحلة 42
============================================================

📌 الجدول: wadq_stage41_decision_df
الحجم: (26, 20)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر']
نسبة البيانات المتاحة:
الرمز              100.0%
السعر السابق        65.4%
التغير اليومي %     65.4%
RSI                 34.6%
حالة RSI            34.6%
MACD                34.6%
إشارة MACD          34.6%
ticker              34.6%
السعر               34.6%
dtype: object

📌 الجدول: wadq_global_us_unified_df
الحجم: (26, 20)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر']
نسبة البيانات المتاحة:
الرمز              100.0%
السعر السابق        65.4%
التغير اليومي %     65.4%
RSI                 34.6%
حالة RSI            34.6%
MACD                34.6%
إشارة MACD          34.6%
ticker              34.6%
السعر               34.6%
dtype: object

📌 الجدول: wadq_global_market_df
الحجم: (17, 6)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']
نسبة البيانات المتاحة:
الرمز              100.0%
السعر السابق       100.0%
التغير اليومي %    100.0%
dtype: object

📌 الجدول: wadq_us_monitoring_df
الحجم: (9, 13)
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار']
نسبة البيانات المتاحة:
الرمز         100.0%
RSI           100.0%
حالة RSI      100.0%
MACD          100.0%
إشارة MACD    100.0%
ticker        100.0%
dtype: object

📌 الجدول: us_technical_df
الحجم: (9, 10)
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']
نسبة البيانات المتاحة:
الرمز         100.0%
RSI           100.0%
حالة RSI      100.0%
MACD          100.0%
إشارة MACD    100.0%
dtype: object

📌 الجدول: wadq_stage42_market_df
الحجم: (26, 21)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة']
نسبة البيانات المتاحة:
الرمز              100.0%
السعر السابق        65.4%
التغير اليومي %     65.4%
RSI                 34.6%
حالة RSI            34.6%
MACD                34.6%
إشارة MACD          34.6%
ticker              34.6%
السعر               34.6%
dtype: object

✅ انتهى الفحص دون تعديل الجداول الأصلية.

In [ ]:
# 🌧️ الودق AI — المرحلة 42
# فحص الأصول والبيانات المفقودة دون تعديل الجداول الأصلية

import pandas as pd
from IPython.display import display

print("🌧️ فحص بيانات المرحلة 42")
print("=" * 60)

df = globals().get("wadq_stage42_market_df")

if isinstance(df, pd.DataFrame):

    print("عدد الصفوف:", len(df))
    print("عدد الأعمدة:", len(df.columns))

    print("\n📋 أسماء الأعمدة:")
    print(df.columns.tolist())

    print("\n📊 نسبة البيانات المتاحة لكل عمود:")
    availability = (
        df.notna().mean()
        .mul(100)
        .round(1)
        .sort_values()
    )
    display(availability.to_frame("نسبة البيانات المتاحة %"))

    print("\n🔍 الأصول التي تحتوي على بيانات مفقودة:")

    missing_rows = df[df.isna().any(axis=1)]

    print("عدد الصفوف التي تحتوي على بيانات مفقودة:",
          len(missing_rows))

    display(missing_rows)

else:
    print("⚠️ جدول المرحلة 42 غير موجود في الذاكرة الحالية.")

print("\n✅ انتهى الفحص دون تعديل الجداول الأصلية.")

🌧️ فحص بيانات المرحلة 42
============================================================
عدد الصفوف: 26
عدد الأعمدة: 21

📋 أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة']

📊 نسبة البيانات المتاحة لكل عمود:

                  نسبة البيانات المتاحة %
السهم                                34.6
إشارة MACD                           34.6
MACD                                 34.6
حالة RSI                             34.6
RSI                                  34.6
المتوسط 50                           34.6
المتوسط 20                           34.6
آخر إغلاق                            34.6
الاتجاه                              34.6
ملخص_الأخبار                         34.6
عدد_الأخبار                          34.6
ticker                               34.6
السعر                                34.6
أحدث سعر متاح                        65.4
السعر السابق                         65.4
التغير اليومي %                      65.4
تاريخ آخر بيانات                     65.4
الرمز                               100.0
نوع الأصل                           100.0
الأصل                               100.0
تصنيف الحركة                        100.0

🔍 الأصول التي تحتوي على بيانات مفقودة:
عدد الصفوف التي تحتوي على بيانات مفقودة: 26

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,نوع الأصل,السهم,آخر إغلاق,المتوسط 20,...,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,السعر,تصنيف الحركة
0,NG=F,الغاز الطبيعي,3.322000,3.167000,4.894221,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
1,ETH-USD,إيثيريوم,2507.969971,2444.357422,2.602424,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
2,BTC-USD,بيتكوين,83349.679688,81762.562500,1.941129,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
3,CL=F,النفط الأمريكي,94.809998,93.739998,1.141455,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
4,^HSI,Hang Seng - هونغ كونغ,24271.199219,24211.349609,0.247197,2026-10-12,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
5,JPY=X,الدولار مقابل الين,158.320999,158.203003,0.074585,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,2026-10-09,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
7,^GSPC,S&P 500 - أمريكا,7805.450195,7807.240234,-0.022928,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
8,EURUSD=X,اليورو مقابل الدولار,1.120072,1.120473,-0.035833,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
9,^FTSE,FTSE 100 - بريطانيا,10650.330078,10656.299805,-0.056021,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
10,^FCHI,CAC 40 - فرنسا,7827.629883,7832.879883,-0.067025,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
11,^GDAXI,DAX - ألمانيا,25259.900391,25277.679688,-0.070336,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
12,^IXIC,Nasdaq Composite - أمريكا,27204.380859,27245.900391,-0.152388,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
13,GC=F,الذهب,4183.000000,4190.600098,-0.181361,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
14,BZ=F,نفط برنت,106.370003,106.650002,-0.262540,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
15,^DJI,Dow Jones - أمريكا,51670.101562,51850.550781,-0.348018,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة
16,SI=F,الفضة,59.369999,60.140999,-1.281987,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🔴 انخفاض ملحوظ
17,NVDA,إنفيديا,NaN,NaN,NaN,NaN,سهم أمريكي,إنفيديا,228.52,228.32,...,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,NVDA,47.0,Wall Street stocks end tad lower after hot inf...,228.52,⚪ بيانات غير متاحة
18,TSLA,تسلا,NaN,NaN,NaN,NaN,سهم أمريكي,تسلا,375.23,370.54,...,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,TSLA,20.0,Zacks Investment Ideas feature highlights: App...,375.23,⚪ بيانات غير متاحة
19,AAPL,آبل,NaN,NaN,NaN,NaN,سهم أمريكي,آبل,341.27,336.28,...,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد,AAPL,1.0,"Are Amazon, Apple stocks overpriced? Here are ...",341.27,⚪ بيانات غير متاحة
20,MSFT,مايكروسوفت,NaN,NaN,NaN,NaN,سهم أمريكي,مايكروسوفت,543.45,514.20,...,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,MSFT,35.0,Zacks Investment Ideas feature highlights: App...,543.45,⚪ بيانات غير متاحة
21,AMZN,أمازون,NaN,NaN,NaN,NaN,سهم أمريكي,أمازون,258.58,252.83,...,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط,AMZN,17.0,Zacks Investment Ideas feature highlights: App...,258.58,⚪ بيانات غير متاحة
22,GOOGL,ألفابت,NaN,NaN,NaN,NaN,سهم أمريكي,ألفابت,353.78,346.53,...,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد,GOOGL,22.0,"S&P 500, Nasdaq close lower, dragged by Alphab...",353.78,⚪ بيانات غير متاحة
23,META,ميتا,NaN,NaN,NaN,NaN,سهم أمريكي,ميتا,762.50,727.58,...,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد,META,2.0,I Predicted That Oracle and Netflix Would Join...,762.50,⚪ بيانات غير متاحة
24,QQQ,ناسداك 100,NaN,NaN,NaN,NaN,سهم أمريكي,ناسداك 100,743.57,741.22,...,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد,QQQ,4.0,"Stock Market Today: Dow Jones, S&P 500 Futures...",743.57,⚪ بيانات غير متاحة
25,SPY,ستاندرد آند بورز 500,NaN,NaN,NaN,NaN,سهم أمريكي,ستاندرد آند بورز 500,778.01,769.68,...,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد,SPY,50.0,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",778.01,⚪ بيانات غير متاحة

✅ انتهى الفحص دون تعديل الجداول الأصلية.

In [ ]:
# 🌧️ الودق AI — فحص بيانات المرحلة 42
# فحص فقط، دون تعديل أي جدول أصلي

import pandas as pd
from IPython.display import display

df = wadq_stage42_market_df

print("🌧️ فحص جدول المرحلة 42")
print("=" * 50)

print("عدد الصفوف:", len(df))
print("عدد الأعمدة:", len(df.columns))

print("\n📋 أسماء الأعمدة:")
for i, col in enumerate(df.columns):
    print(i, repr(col))

print("\n🔎 آخر 10 صفوف:")
display(df.tail(10))

print("\n📊 عدد القيم المفقودة في كل عمود:")
missing = df.isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)

if len(missing):
    display(missing.to_frame("عدد القيم المفقودة"))
else:
    print("لا توجد قيم مفقودة.")

print("\n✅ انتهى الفحص دون تعديل البيانات.")

🌧️ فحص جدول المرحلة 42
==================================================
عدد الصفوف: 26
عدد الأعمدة: 21

📋 أسماء الأعمدة:
0 'الرمز'
1 'الأصل'
2 'أحدث سعر متاح'
3 'السعر السابق'
4 'التغير اليومي %'
5 'تاريخ آخر بيانات'
6 'نوع الأصل'
7 'السهم'
8 'آخر إغلاق'
9 'المتوسط 20'
10 'المتوسط 50'
11 'RSI'
12 'حالة RSI'
13 'MACD'
14 'إشارة MACD'
15 'الاتجاه'
16 'ticker'
17 'عدد_الأخبار'
18 'ملخص_الأخبار'
19 'السعر'
20 'تصنيف الحركة'

🔎 آخر 10 صفوف:

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,نوع الأصل,السهم,آخر إغلاق,المتوسط 20,...,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,السعر,تصنيف الحركة
16,SI=F,الفضة,59.369999,60.140999,-1.281987,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🔴 انخفاض ملحوظ
17,NVDA,إنفيديا,NaN,NaN,NaN,NaN,سهم أمريكي,إنفيديا,228.52,228.32,...,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,NVDA,47.0,Wall Street stocks end tad lower after hot inf...,228.52,⚪ بيانات غير متاحة
18,TSLA,تسلا,NaN,NaN,NaN,NaN,سهم أمريكي,تسلا,375.23,370.54,...,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,TSLA,20.0,Zacks Investment Ideas feature highlights: App...,375.23,⚪ بيانات غير متاحة
19,AAPL,آبل,NaN,NaN,NaN,NaN,سهم أمريكي,آبل,341.27,336.28,...,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد,AAPL,1.0,"Are Amazon, Apple stocks overpriced? Here are ...",341.27,⚪ بيانات غير متاحة
20,MSFT,مايكروسوفت,NaN,NaN,NaN,NaN,سهم أمريكي,مايكروسوفت,543.45,514.20,...,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,MSFT,35.0,Zacks Investment Ideas feature highlights: App...,543.45,⚪ بيانات غير متاحة
21,AMZN,أمازون,NaN,NaN,NaN,NaN,سهم أمريكي,أمازون,258.58,252.83,...,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط,AMZN,17.0,Zacks Investment Ideas feature highlights: App...,258.58,⚪ بيانات غير متاحة
22,GOOGL,ألفابت,NaN,NaN,NaN,NaN,سهم أمريكي,ألفابت,353.78,346.53,...,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد,GOOGL,22.0,"S&P 500, Nasdaq close lower, dragged by Alphab...",353.78,⚪ بيانات غير متاحة
23,META,ميتا,NaN,NaN,NaN,NaN,سهم أمريكي,ميتا,762.50,727.58,...,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد,META,2.0,I Predicted That Oracle and Netflix Would Join...,762.50,⚪ بيانات غير متاحة
24,QQQ,ناسداك 100,NaN,NaN,NaN,NaN,سهم أمريكي,ناسداك 100,743.57,741.22,...,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد,QQQ,4.0,"Stock Market Today: Dow Jones, S&P 500 Futures...",743.57,⚪ بيانات غير متاحة
25,SPY,ستاندرد آند بورز 500,NaN,NaN,NaN,NaN,سهم أمريكي,ستاندرد آند بورز 500,778.01,769.68,...,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد,SPY,50.0,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",778.01,⚪ بيانات غير متاحة

📊 عدد القيم المفقودة في كل عمود:

                  عدد القيم المفقودة
السهم                             17
ticker                            17
المتوسط 50                        17
المتوسط 20                        17
آخر إغلاق                         17
RSI                               17
إشارة MACD                        17
MACD                              17
حالة RSI                          17
السعر                             17
عدد_الأخبار                       17
ملخص_الأخبار                      17
الاتجاه                           17
أحدث سعر متاح                      9
التغير اليومي %                    9
تاريخ آخر بيانات                   9
السعر السابق                       9

✅ انتهى الفحص دون تعديل البيانات.

In [ ]:
# 🌧️ الودق AI — فحص ربط بيانات الأسهم
# فحص فقط دون تعديل الجداول الأصلية

import pandas as pd
from IPython.display import display

print("🌧️ فحص ربط بيانات المرحلة 42")
print("=" * 55)

# 1. التأكد من وجود الجدولين
if (
    "wadq_stage42_market_df" in globals()
    and "us_technical_df" in globals()
):

    market = wadq_stage42_market_df
    technical = us_technical_df

    print("\n📊 حجم جدول المرحلة 42:")
    print(market.shape)

    print("\n📊 حجم جدول التحليل الفني:")
    print(technical.shape)

    print("\n📋 أعمدة جدول المرحلة 42:")
    for col in market.columns:
        print(repr(col))

    print("\n📋 أعمدة جدول التحليل الفني:")
    for col in technical.columns:
        print(repr(col))

    # 2. فحص الأسهم الأمريكية
    print("\n🔎 الأسهم الأمريكية في جدول التحليل الفني:")
    display(technical)

    # 3. فحص صفوف QQQ وSPY وAMZN وGOOGL وMETA
    possible_columns = [
        "ticker", "symbol", "Symbol",
        "الرمز", "السهم"
    ]

    ticker_col = next(
        (c for c in possible_columns if c in market.columns),
        None
    )

    if ticker_col is not None:
        targets = ["QQQ", "SPY", "AMZN", "GOOGL", "META"]

        print("\n🔎 فحص الأسهم المطلوبة:")
        display(
            market[
                market[ticker_col]
                .astype(str)
                .str.upper()
                .isin(targets)
            ]
        )
    else:
        print(
            "\n⚠️ لم يُعثر على عمود واضح لرمز السهم."
            "\nسنراجع أسماء الأعمدة الظاهرة أعلاه."
        )

    print("\n✅ انتهى الفحص دون تعديل البيانات.")

else:
    print(
        "⚠️ أحد الجدولين غير موجود في الذاكرة الحالية."

_IncompleteInputError: incomplete input (2167796347.py, line 70)

In [ ]:
# ============================================================
# 🌧️ الودق AI — استعادة الجدولين المفقودين
# 1. wadq_global_alerts_df
# 2. wadq_global_news_analysis_df
# دون حذف أو تعديل الجداول الأصلية
# ============================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI — بدء استعادة الجدولين")
print("=" * 60)


# ------------------------------------------------------------
# 1. استعادة جدول تحليل الأخبار العالمية
# ------------------------------------------------------------

news_source = None

for name in ["wadq_global_news_df", "wadq_news_df"]:
    candidate = globals().get(name)

    if isinstance(candidate, pd.DataFrame) and not candidate.empty:
        news_source = candidate.copy()
        print(f"✅ مصدر الأخبار: {name}")
        break

if news_source is not None:

    # تحديد عمود التصنيف وعمود العنوان
    category_col = next(
        (
            c for c in ["category", "التصنيف", "الفئة"]
            if c in news_source.columns
        ),
        None
    )

    title_col = next(
        (
            c for c in ["title", "news_title", "العنوان", "عنوان الخبر"]
            if c in news_source.columns
        ),
        None
    )

    if category_col is not None:

        analysis_data = news_source.copy()

        # تصنيف أولي للكلمات الإيجابية والسلبية
        positive_words = [
            "surge", "gain", "rise", "rally", "record high",
            "growth", "profit", "beat estimates", "jump",
            "ارتفاع", "ارتفاعات", "مكاسب", "نمو",
            "أرباح", "صعود", "انتعاش", "إيجابي"
        ]

        negative_words = [
            "fall", "drop", "decline", "crash", "loss",
            "selloff", "slump", "miss estimates", "recession",
            "انخفاض", "هبوط", "خسائر", "تراجع",
            "هبوط حاد", "سلبي", "ركود", "أزمة"
        ]

        def classify_news(title):
            text = str(title).lower()

            positive = sum(word in text for word in positive_words)
            negative = sum(word in text for word in negative_words)

            if positive > negative:
                return "إيجابية"
            elif negative > positive:
                return "سلبية"
            else:
                return "محايدة"

        if title_col is not None:
            analysis_data["_sentiment"] = (
                analysis_data[title_col].apply(classify_news)
            )
        else:
            analysis_data["_sentiment"] = "محايدة"

        summary = (
            analysis_data.groupby(category_col)["_sentiment"]
            .value_counts()
            .unstack(fill_value=0)
        )

        for sentiment in ["محايدة", "سلبية", "إيجابية"]:
            if sentiment not in summary.columns:
                summary[sentiment] = 0

        wadq_global_news_analysis_df = pd.DataFrame({
            "category": summary.index,
            "عدد الأخبار": summary.sum(axis=1).values,
            "أخبار_محايدة": summary["محايدة"].values,
            "أخبار_سلبية": summary["سلبية"].values,
            "أخبار_إيجابية": summary["إيجابية"].values
        }).reset_index(drop=True)

        print("\n✅ تمت استعادة جدول تحليل الأخبار العالمية.")
        print("عدد التصنيفات:", len(wadq_global_news_analysis_df))
        display(wadq_global_news_analysis_df)

    else:
        print("⚠️ لم يُعثر على عمود تصنيف الأخبار.")
        print("أسماء الأعمدة:", news_source.columns.tolist())

else:
    print("⚠️ لم يُعثر على مصدر أخبار متاح.")


# ------------------------------------------------------------
# 2. استعادة جدول الإنذارات العالمية
# ------------------------------------------------------------

market_source = globals().get("wadq_global_market_df")

if isinstance(market_source, pd.DataFrame) and not market_source.empty:

    source = market_source.copy()

    def find_column(candidates):
        # البحث عن تطابق مباشر
        for col in candidates:
            if col in source.columns:
                return col

        # البحث عن تطابق جزئي
        for col in source.columns:
            for candidate in candidates:
                if candidate.lower() in str(col).lower():
                    return col

        return None

    asset_col = find_column([
        "الأصل", "اسم الأصل", "asset", "asset_name", "name"
    ])

    ticker_col = find_column([
        "الرمز", "رمز الأصل", "ticker", "symbol"
    ])

    price_col = find_column([
        "أحدث سعر متاح", "آخر سعر", "السعر الحالي",
        "السعر", "latest_price", "current_price", "price"
    ])

    change_col = find_column([
        "التغير اليومي %", "التغير اليومي",
        "نسبة التغير", "daily_change_pct",
        "change_pct", "daily_change"
    ])

    date_col = find_column([
        "تاريخ آخر بيانات", "تاريخ البيانات",
        "التاريخ", "date", "last_date"
    ])

    # بناء جدول مستقل من المصدر المتاح
    wadq_global_alerts_df = pd.DataFrame(index=source.index)

    wadq_global_alerts_df["الأصل"] = (
        source[asset_col] if asset_col is not None
        else "غير محدد"
    )

    wadq_global_alerts_df["الرمز"] = (
        source[ticker_col] if ticker_col is not None
        else ""
    )

    wadq_global_alerts_df["أحدث سعر متاح"] = (
        source[price_col] if price_col is not None
        else pd.NA
    )

    wadq_global_alerts_df["التغير اليومي %"] = (
        pd.to_numeric(source[change_col], errors="coerce")
        if change_col is not None
        else pd.NA
    )

    wadq_global_alerts_df["تاريخ آخر بيانات"] = (
        source[date_col] if date_col is not None
        else pd.NA
    )

    def movement_status(value):
        if pd.isna(value):
            return "بيانات غير مكتملة"
        elif value > 0:
            return "ارتفاع"
        elif value < 0:
            return "انخفاض"
        else:
            return "استقرار"

    wadq_global_alerts_df["حالة الحركة"] = (
        wadq_global_alerts_df["التغير اليومي %"]
        .apply(movement_status)
    )

    def movement_note(value):
        if pd.isna(value):
            return "يلزم التحقق من بيانات السعر والتغير."
        elif value >= 2:
            return "ارتفاع ملحوظ؛ يستحق المتابعة."
        elif value <= -2:
            return "انخفاض ملحوظ؛ يستحق المتابعة."
        else:
            return "متابعة الحركة دون اعتبارها توصية تداول."

    wadq_global_alerts_df["ملاحظة"] = (
        wadq_global_alerts_df["التغير اليومي %"]
        .apply(movement_note)
    )

    wadq_global_alerts_df = (
        wadq_global_alerts_df.reset_index(drop=True)
    )

    print("\n✅ تمت استعادة جدول الإنذارات العالمية.")
    print("عدد الأصول:", len(wadq_global_alerts_df))
    display(wadq_global_alerts_df)

else:
    print("\n⚠️ جدول wadq_global_market_df غير متاح.")
    print("لن ننشئ إنذارات بأسعار غير موجودة.")


# ------------------------------------------------------------
# 3. تقرير التحقق النهائي
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("🌧️ تقرير استعادة الجداول")
print("=" * 60)

for name in [
    "wadq_global_alerts_df",
    "wadq_global_news_analysis_df"
]:
    table = globals().get(name)

    if isinstance(table, pd.DataFrame):
        print(
            f"✅ {name}: "
            f"{len(table)} صف × {len(table.columns)} عمود"
        )
    else:
        print(f"⚠️ {name}: لم تتم استعادته")

print("\n✅ انتهت محاولة الاستعادة.")
print("📌 لم تُحذف أو تُعدّل الجداول الأصلية.")

🌧️ الودق AI — بدء استعادة الجدولين
============================================================
✅ مصدر الأخبار: wadq_global_news_df

✅ تمت استعادة جدول تحليل الأخبار العالمية.
عدد التصنيفات: 7

            category  عدد الأخبار  أخبار_محايدة  أخبار_سلبية  أخبار_إيجابية
0   الأخبار العالمية           75            65            3              7
1  الأسواق الأمريكية          100            55           21             24
2   الاقتصاد العالمي          100            87            4              9
3       الذهب والنفط           76            52           12             12
4      السوق السعودي           44            35            1              8
5  الشركات الأمريكية           70            58            1             11
6    الفائدة والتضخم          100            88            3              9

✅ تمت استعادة جدول الإنذارات العالمية.
عدد الأصول: 17

,الأصل,الرمز,أحدث سعر متاح,التغير اليومي %,تاريخ آخر بيانات,حالة الحركة,ملاحظة
0,S&P 500 - أمريكا,^GSPC,7805.450195,-0.022928,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
1,Nasdaq Composite - أمريكا,^IXIC,27204.380859,-0.152388,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
2,Dow Jones - أمريكا,^DJI,51670.101562,-0.348018,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
3,DAX - ألمانيا,^GDAXI,25259.900391,-0.070336,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
4,CAC 40 - فرنسا,^FCHI,7827.629883,-0.067025,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
5,FTSE 100 - بريطانيا,^FTSE,10650.330078,-0.056021,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
6,Nikkei 225 - اليابان,^N225,69030.921875,-0.016204,2026-10-09,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
7,Hang Seng - هونغ كونغ,^HSI,24271.199219,0.247197,2026-10-12,ارتفاع,متابعة الحركة دون اعتبارها توصية تداول.
8,الذهب,GC=F,4183.000000,-0.181361,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
9,الفضة,SI=F,59.369999,-1.281987,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
10,النفط الأمريكي,CL=F,94.809998,1.141455,2026-10-13,ارتفاع,متابعة الحركة دون اعتبارها توصية تداول.
11,نفط برنت,BZ=F,106.370003,-0.262540,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
12,الغاز الطبيعي,NG=F,3.322000,4.894221,2026-10-13,ارتفاع,ارتفاع ملحوظ؛ يستحق المتابعة.
13,اليورو مقابل الدولار,EURUSD=X,1.120072,-0.035833,2026-10-13,انخفاض,متابعة الحركة دون اعتبارها توصية تداول.
14,الدولار مقابل الين,JPY=X,158.320999,0.074585,2026-10-13,ارتفاع,متابعة الحركة دون اعتبارها توصية تداول.
15,بيتكوين,BTC-USD,83349.679688,1.941129,2026-10-13,ارتفاع,متابعة الحركة دون اعتبارها توصية تداول.
16,إيثيريوم,ETH-USD,2507.969971,2.602424,2026-10-13,ارتفاع,ارتفاع ملحوظ؛ يستحق المتابعة.

============================================================
🌧️ تقرير استعادة الجداول
============================================================
✅ wadq_global_alerts_df: 17 صف × 7 عمود
✅ wadq_global_news_analysis_df: 7 صف × 5 عمود

✅ انتهت محاولة الاستعادة.
📌 لم تُحذف أو تُعدّل الجداول الأصلية.

In [ ]:
# 🌧️ الودق AI — فحص المرحلة 42 قبل المتابعة

import pandas as pd
from IPython.display import display

print("🌧️ فحص جداول المرحلة 42")
print("=" * 55)

for name in [
    "wadq_stage42_market_df",
    "wadq_stage42_summary_df",
    "wadq_global_us_unified_df",
    "wadq_stage41_decision_df",
    "wadq_executive_summary_df"
]:
    df = globals().get(name)

    if isinstance(df, pd.DataFrame):
        print(f"\n✅ الجدول: {name}")
        print(f"عدد الصفوف: {len(df)}")
        print(f"عدد الأعمدة: {len(df.columns)}")
        print(f"القيم المفقودة: {df.isna().sum().sum()}")
        print("الأعمدة:", df.columns.tolist())

        if name == "wadq_stage42_market_df":
            display(df.head(5))

    else:
        print(f"\n⚠️ الجدول غير موجود: {name}")

print("\n✅ انتهى الفحص دون تعديل الجداول.")

🌧️ فحص جداول المرحلة 42
=======================================================

✅ الجدول: wadq_stage42_market_df
عدد الصفوف: 26
عدد الأعمدة: 21
القيم المفقودة: 257
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة']

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,نوع الأصل,السهم,آخر إغلاق,المتوسط 20,...,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,السعر,تصنيف الحركة
0,NG=F,الغاز الطبيعي,3.322000,3.167000,4.894221,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
1,ETH-USD,إيثيريوم,2507.969971,2444.357422,2.602424,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
2,BTC-USD,بيتكوين,83349.679688,81762.562500,1.941129,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
3,CL=F,النفط الأمريكي,94.809998,93.739998,1.141455,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
4,^HSI,Hang Seng - هونغ كونغ,24271.199219,24211.349609,0.247197,2026-10-12,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟡 حركة محدودة

✅ الجدول: wadq_stage42_summary_df
عدد الصفوف: 4
عدد الأعمدة: 2
القيم المفقودة: 0
الأعمدة: ['تصنيف الحركة', 'عدد الأصول']

✅ الجدول: wadq_global_us_unified_df
عدد الصفوف: 26
عدد الأعمدة: 20
القيم المفقودة: 257
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر']

✅ الجدول: wadq_stage41_decision_df
عدد الصفوف: 26
عدد الأعمدة: 20
القيم المفقودة: 257
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر']

✅ الجدول: wadq_executive_summary_df
عدد الصفوف: 3
عدد الأعمدة: 2
القيم المفقودة: 0
الأعمدة: ['المؤشر', 'القيمة']

✅ انتهى الفحص دون تعديل الجداول.

In [ ]:
# 🌧️ الودق AI — تشخيص البيانات الناقصة في المرحلة 42

import pandas as pd

print("🌧️ فحص بيانات المرحلة 42")
print("=" * 50)

for name in [
    "us_technical_df",
    "wadq_global_market_df",
    "wadq_global_priority_df",
    "wadq_stage42_market_df",
    "wadq_stage42_summary_df"
]:
    df = globals().get(name)

    print(f"\n📌 الجدول: {name}")

    if isinstance(df, pd.DataFrame):
        print("عدد الصفوف:", len(df))
        print("عدد الأعمدة:", len(df.columns))
        print("أسماء الأعمدة:")
        print(df.columns.tolist())

        print("\nعدد القيم المفقودة في كل عمود:")
        print(df.isna().sum().to_string())

        print("\nأول 3 صفوف:")
        display(df.head(3))
    else:
        print("⚠️ الجدول غير موجود في الذاكرة الحالية.")

print("\n✅ انتهى التشخيص دون تعديل أي جدول.")

🌧️ فحص بيانات المرحلة 42
==================================================

📌 الجدول: us_technical_df
عدد الصفوف: 9
عدد الأعمدة: 10
أسماء الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

عدد القيم المفقودة في كل عمود:
السهم         0
الرمز         0
آخر إغلاق     0
المتوسط 20    0
المتوسط 50    0
RSI           0
حالة RSI      0
MACD          0
إشارة MACD    0
الاتجاه       0

أول 3 صفوف:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد

📌 الجدول: wadq_global_market_df
عدد الصفوف: 17
عدد الأعمدة: 6
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

عدد القيم المفقودة في كل عمود:
الرمز               0
الأصل               0
أحدث سعر متاح       0
السعر السابق        0
التغير اليومي %     0
تاريخ آخر بيانات    0

أول 3 صفوف:

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات
0,^GSPC,S&P 500 - أمريكا,7805.450195,7807.240234,-0.022928,2026-10-13
1,^IXIC,Nasdaq Composite - أمريكا,27204.380859,27245.900391,-0.152388,2026-10-13
2,^DJI,Dow Jones - أمريكا,51670.101562,51850.550781,-0.348018,2026-10-13

📌 الجدول: wadq_global_priority_df
عدد الصفوف: 9
عدد الأعمدة: 15
أسماء الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'درجة_المتابعة', 'أولوية_المراجعة']

عدد القيم المفقودة في كل عمود:
السهم              0
الرمز              0
آخر إغلاق          0
المتوسط 20         0
المتوسط 50         0
RSI                0
حالة RSI           0
MACD               0
إشارة MACD         0
الاتجاه            0
ticker             0
عدد_الأخبار        0
ملخص_الأخبار       0
درجة_المتابعة      0
أولوية_المراجعة    0

أول 3 صفوف:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,درجة_المتابعة,أولوية_المراجعة
0,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,MSFT,35,Zacks Investment Ideas feature highlights: App...,5,مرتفعة للمراجعة
1,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,NVDA,47,Wall Street stocks end tad lower after hot inf...,3,متوسطة للمراجعة
2,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,TSLA,20,Zacks Investment Ideas feature highlights: App...,3,متوسطة للمراجعة

📌 الجدول: wadq_stage42_market_df
عدد الصفوف: 26
عدد الأعمدة: 21
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة']

عدد القيم المفقودة في كل عمود:
الرمز                0
الأصل                0
أحدث سعر متاح        9
السعر السابق         9
التغير اليومي %      9
تاريخ آخر بيانات     9
نوع الأصل            0
السهم               17
آخر إغلاق           17
المتوسط 20          17
المتوسط 50          17
RSI                 17
حالة RSI            17
MACD                17
إشارة MACD          17
الاتجاه             17
ticker              17
عدد_الأخبار         17
ملخص_الأخبار        17
السعر               17
تصنيف الحركة         0

أول 3 صفوف:

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,نوع الأصل,السهم,آخر إغلاق,المتوسط 20,...,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,السعر,تصنيف الحركة
0,NG=F,الغاز الطبيعي,3.322000,3.167000,4.894221,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
1,ETH-USD,إيثيريوم,2507.969971,2444.357422,2.602424,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
2,BTC-USD,بيتكوين,83349.679688,81762.562500,1.941129,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,🟢 ارتفاع ملحوظ

📌 الجدول: wadq_stage42_summary_df
عدد الصفوف: 4
عدد الأعمدة: 2
أسماء الأعمدة:
['تصنيف الحركة', 'عدد الأصول']

عدد القيم المفقودة في كل عمود:
تصنيف الحركة    0
عدد الأصول      0

أول 3 صفوف:

     تصنيف الحركة  عدد الأصول
0  🟢 ارتفاع ملحوظ           4
1  🔴 انخفاض ملحوظ           1
2   🟡 حركة محدودة          12

✅ انتهى التشخيص دون تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — فحص ربط الأسهم بالتحليل الفني
# فحص فقط دون تعديل الجداول الأصلية

import pandas as pd
from IPython.display import display

tables_to_check = [
    "us_technical_df",
    "wadq_global_priority_df",
    "wadq_global_market_df",
    "wadq_stage42_market_df"
]

for name in tables_to_check:
    df = globals().get(name)

    print("\n" + "=" * 60)
    print("📌 الجدول:", name)

    if isinstance(df, pd.DataFrame):
        print("الحجم:", df.shape)
        print("الأعمدة:", df.columns.tolist())

        ticker_cols = [
            c for c in df.columns
            if str(c).lower() in [
                "ticker", "symbol", "رمز", "الرمز"
            ]
        ]

        if ticker_cols:
            print("\nالرموز الموجودة:")
            display(df[ticker_cols].head(12))

        else:
            print("⚠️ لم يُعثر على عمود رمز واضح.")

    else:
        print("⚠️ الجدول غير موجود في الذاكرة الحالية.")

print("\n✅ انتهى الفحص دون تعديل البيانات.")

============================================================
📌 الجدول: us_technical_df
الحجم: (9, 10)
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

الرموز الموجودة:

   الرمز
0   NVDA
1   TSLA
2   AAPL
3   MSFT
4   AMZN
5  GOOGL
6   META
7    QQQ
8    SPY

============================================================
📌 الجدول: wadq_global_priority_df
الحجم: (9, 15)
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'درجة_المتابعة', 'أولوية_المراجعة']

الرموز الموجودة:

   الرمز ticker
0   MSFT   MSFT
1   NVDA   NVDA
2   TSLA   TSLA
3    SPY    SPY
4  GOOGL  GOOGL
5   META   META
6   AAPL   AAPL
7    QQQ    QQQ
8   AMZN   AMZN

============================================================
📌 الجدول: wadq_global_market_df
الحجم: (17, 6)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

الرموز الموجودة:

     الرمز
0    ^GSPC
1    ^IXIC
2     ^DJI
3   ^GDAXI
4    ^FCHI
5    ^FTSE
6    ^N225
7     ^HSI
8     GC=F
9     SI=F
10    CL=F
11    BZ=F

============================================================
📌 الجدول: wadq_stage42_market_df
الحجم: (26, 21)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة']

الرموز الموجودة:

       الرمز ticker
0       NG=F    NaN
1    ETH-USD    NaN
2    BTC-USD    NaN
3       CL=F    NaN
4       ^HSI    NaN
5      JPY=X    NaN
6      ^N225    NaN
7      ^GSPC    NaN
8   EURUSD=X    NaN
9      ^FTSE    NaN
10     ^FCHI    NaN
11    ^GDAXI    NaN

✅ انتهى الفحص دون تعديل البيانات.

In [ ]:
# 🌧️ الودق AI — المرحلة 42
# إصلاح عمود ticker في نسخة مستقلة دون تعديل الجدول الأصلي

import pandas as pd
from IPython.display import display

if "wadq_stage42_market_df" not in globals():
    print("⚠️ جدول المرحلة 42 غير موجود. لن يتم إجراء أي تعديل.")

else:
    # إنشاء نسخة احتياطية للعمل
    wadq_stage42_market_fixed_df = wadq_stage42_market_df.copy()

    # البحث عن عمود الرمز
    if "الرمز" in wadq_stage42_market_fixed_df.columns:

        # تعبئة ticker من عمود الرمز
        if "ticker" not in wadq_stage42_market_fixed_df.columns:
            wadq_stage42_market_fixed_df["ticker"] = (
                wadq_stage42_market_fixed_df["الرمز"]
                .astype("string")
                .str.strip()
            )
        else:
            missing_ticker = (
                wadq_stage42_market_fixed_df["ticker"].isna()
                | wadq_stage42_market_fixed_df["ticker"]
                    .astype("string").str.strip().eq("")
            )

            wadq_stage42_market_fixed_df.loc[
                missing_ticker, "ticker"
            ] = (
                wadq_stage42_market_fixed_df.loc[
                    missing_ticker, "الرمز"
                ].astype("string").str.strip()
            )

        print("✅ تم إصلاح عمود ticker في النسخة الجديدة.")
        print("📌 الجدول الأصلي لم يتغير.")
        print("عدد الصفوف:", len(wadq_stage42_market_fixed_df))
        print(
            "عدد الرموز الفارغة:",
            wadq_stage42_market_fixed_df["ticker"].isna().sum()
        )

        display(
            wadq_stage42_market_fixed_df[
                ["الرمز", "ticker"]
            ].head(15)
        )

    else:
        print("⚠️ لم يُعثر على عمود الرمز. لم يتم تعديل أي جدول.")

✅ تم إصلاح عمود ticker في النسخة الجديدة.
📌 الجدول الأصلي لم يتغير.
عدد الصفوف: 26
عدد الرموز الفارغة: 0

       الرمز    ticker
0       NG=F      NG=F
1    ETH-USD   ETH-USD
2    BTC-USD   BTC-USD
3       CL=F      CL=F
4       ^HSI      ^HSI
5      JPY=X     JPY=X
6      ^N225     ^N225
7      ^GSPC     ^GSPC
8   EURUSD=X  EURUSD=X
9      ^FTSE     ^FTSE
10     ^FCHI     ^FCHI
11    ^GDAXI    ^GDAXI
12     ^IXIC     ^IXIC
13      GC=F      GC=F
14      BZ=F      BZ=F

In [ ]:
# 🌧️ الودق AI — المرحلة 42
# فحص مصادر التحليل الفني قبل الربط

import pandas as pd
from IPython.display import display

print("🌧️ فحص مصادر التحليل الفني")
print("=" * 55)

for name in [
    "us_technical_df",
    "wadq_global_priority_df",
    "wadq_global_market_df",
    "wadq_stage42_market_fixed_df"
]:
    df = globals().get(name)

    print(f"\n📌 {name}")

    if isinstance(df, pd.DataFrame):
        print("الحجم:", df.shape)
        print("الأعمدة:", df.columns.tolist())

        if name == "us_technical_df":
            display(df.head(10))

        elif name == "wadq_global_priority_df":
            display(df.head(5))

    else:
        print("⚠️ الجدول غير موجود في الذاكرة الحالية.")

print("\n✅ انتهى الفحص دون تعديل أي جدول.")

🌧️ فحص مصادر التحليل الفني
=======================================================

📌 us_technical_df
الحجم: (9, 10)
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد
3,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد
4,أمازون,AMZN,258.58,252.83,258.35,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط
5,ألفابت,GOOGL,353.78,346.53,345.69,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد
6,ميتا,META,762.50,727.58,646.59,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد
7,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد
8,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد

📌 wadq_global_priority_df
الحجم: (9, 15)
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'درجة_المتابعة', 'أولوية_المراجعة']

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,درجة_المتابعة,أولوية_المراجعة
0,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,MSFT,35,Zacks Investment Ideas feature highlights: App...,5,مرتفعة للمراجعة
1,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,NVDA,47,Wall Street stocks end tad lower after hot inf...,3,متوسطة للمراجعة
2,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,TSLA,20,Zacks Investment Ideas feature highlights: App...,3,متوسطة للمراجعة
3,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد,SPY,50,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",3,متوسطة للمراجعة
4,ألفابت,GOOGL,353.78,346.53,345.69,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد,GOOGL,22,"S&P 500, Nasdaq close lower, dragged by Alphab...",3,متوسطة للمراجعة

📌 wadq_global_market_df
الحجم: (17, 6)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

📌 wadq_stage42_market_fixed_df
الحجم: (26, 21)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة']

✅ انتهى الفحص دون تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — تشخيص المرحلة 42
# فحص الجداول دون تعديل البيانات الأصلية

import pandas as pd
from IPython.display import display

print("🌧️ تقرير تشخيص الجداول")
print("=" * 60)

names = [
    "us_technical_df",
    "wadq_global_priority_df",
    "wadq_global_market_df",
    "wadq_stage42_market_fixed_df"
]

for name in names:
    df = globals().get(name)

    print(f"\n📌 الجدول: {name}")

    if not isinstance(df, pd.DataFrame):
        print("⚠️ الجدول غير موجود.")
        continue

    print("عدد الصفوف:", len(df))
    print("عدد الأعمدة:", len(df.columns))
    print("أسماء الأعمدة:")
    print(df.columns.tolist())

    # فحص الرموز
    symbol_cols = [
        c for c in df.columns
        if str(c).strip().lower() in [
            "ticker", "الرمز", "رمز", "symbol"
        ]
    ]

    if symbol_cols:
        col = symbol_cols[0]
        print(f"\nالرموز في العمود {col}:")
        display(df[[col]].head(10))

    # فحص القيم المفقودة
    print("\nالأعمدة الأكثر احتواءً على قيم مفقودة:")
    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)
    display(missing.head(15).to_frame("عدد القيم المفقودة"))

print("\n✅ انتهى التشخيص.")
print("📌 لم يتم تعديل أي جدول.")

🌧️ تقرير تشخيص الجداول
============================================================

📌 الجدول: us_technical_df
عدد الصفوف: 9
عدد الأعمدة: 10
أسماء الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

الرموز في العمود الرمز:

   الرمز
0   NVDA
1   TSLA
2   AAPL
3   MSFT
4   AMZN
5  GOOGL
6   META
7    QQQ
8    SPY

الأعمدة الأكثر احتواءً على قيم مفقودة:

Empty DataFrame
Columns: [عدد القيم المفقودة]
Index: []

📌 الجدول: wadq_global_priority_df
عدد الصفوف: 9
عدد الأعمدة: 15
أسماء الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'درجة_المتابعة', 'أولوية_المراجعة']

الرموز في العمود الرمز:

   الرمز
0   MSFT
1   NVDA
2   TSLA
3    SPY
4  GOOGL
5   META
6   AAPL
7    QQQ
8   AMZN

الأعمدة الأكثر احتواءً على قيم مفقودة:

Empty DataFrame
Columns: [عدد القيم المفقودة]
Index: []

📌 الجدول: wadq_global_market_df
عدد الصفوف: 17
عدد الأعمدة: 6
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

الرموز في العمود الرمز:

    الرمز
0   ^GSPC
1   ^IXIC
2    ^DJI
3  ^GDAXI
4   ^FCHI
5   ^FTSE
6   ^N225
7    ^HSI
8    GC=F
9    SI=F

الأعمدة الأكثر احتواءً على قيم مفقودة:

Empty DataFrame
Columns: [عدد القيم المفقودة]
Index: []

📌 الجدول: wadq_stage42_market_fixed_df
عدد الصفوف: 26
عدد الأعمدة: 21
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة']

الرموز في العمود الرمز:

      الرمز
0      NG=F
1   ETH-USD
2   BTC-USD
3      CL=F
4      ^HSI
5     JPY=X
6     ^N225
7     ^GSPC
8  EURUSD=X
9     ^FTSE

الأعمدة الأكثر احتواءً على قيم مفقودة:

                 عدد القيم المفقودة
المتوسط 50                       17
المتوسط 20                       17
آخر إغلاق                        17
السهم                            17
إشارة MACD                       17
MACD                             17
حالة RSI                         17
RSI                              17
الاتجاه                          17
عدد_الأخبار                      17
ملخص_الأخبار                     17
السعر                            17
أحدث سعر متاح                     9
السعر السابق                      9
التغير اليومي %                   9

✅ انتهى التشخيص.
📌 لم يتم تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — إصلاح ربط بيانات المرحلة 42
# لا يحذف الجداول الأصلية ولا يستبدل القيم الموجودة

import pandas as pd
from IPython.display import display

print("🌧️ بدء فحص وإصلاح ربط بيانات الودق AI")
print("=" * 55)

# 1. التحقق من وجود الجداول
required_tables = [
    "us_technical_df",
    "wadq_global_market_df",
    "wadq_stage42_market_fixed_df"
]

for name in required_tables:
    if not isinstance(globals().get(name), pd.DataFrame):
        raise ValueError(
            f"الجدول {name} غير موجود. "
            "توقّف الإصلاح للمحافظة على البيانات."
        )

# العمل على نسخة، دون تعديل الجدول الأصلي
fixed = wadq_stage42_market_fixed_df.copy()

def normalize_symbol(value):
    if pd.isna(value):
        return None
    return str(value).strip().upper()

# تحديد عمود الرمز في الجدول الهدف
target_symbol_col = next(
    (c for c in ["ticker", "الرمز", "رمز", "symbol"]
     if c in fixed.columns),
    None
)

if target_symbol_col is None:
    raise ValueError("لم أجد عمود رمز الأصل في الجدول الهدف.")

fixed["_wadq_key"] = fixed[target_symbol_col].map(normalize_symbol)

# 2. ربط المؤشرات الفنية للأسهم الأمريكية
technical = us_technical_df.copy()

tech_symbol_col = next(
    (c for c in ["ticker", "الرمز", "رمز", "symbol"]
     if c in technical.columns),
    None
)

if tech_symbol_col is None:
    raise ValueError("لم أجد عمود رمز السهم في الجدول الفني.")

technical["_wadq_key"] = technical[tech_symbol_col].map(
    normalize_symbol
)

technical = technical.drop_duplicates(
    subset="_wadq_key",
    keep="last"
).set_index("_wadq_key")

technical_columns = [
    "المتوسط 20",
    "المتوسط 50",
    "آخر إغلاق",
    "RSI",
    "حالة RSI",
    "MACD",
    "إشارة MACD",
    "الاتجاه"
]

for col in technical_columns:
    if col not in fixed.columns or col not in technical.columns:
        continue

    mapped = fixed["_wadq_key"].map(technical[col])

    # تعبئة القيم المفقودة فقط
    missing = fixed[col].isna()
    fixed.loc[missing, col] = mapped.loc[missing]

# 3. ربط أسعار الأسواق العالمية باستخدام الرمز
global_market = wadq_global_market_df.copy()

global_symbol_col = next(
    (c for c in ["الرمز", "ticker", "رمز", "symbol"]
     if c in global_market.columns),
    None
)

if global_symbol_col is not None:
    global_market["_wadq_key"] = global_market[
        global_symbol_col
    ].map(normalize_symbol)

    global_market = global_market.drop_duplicates(
        subset="_wadq_key",
        keep="last"
    ).set_index("_wadq_key")

    price_aliases = {
        "أحدث سعر متاح": [
            "أحدث سعر متاح", "السعر", "آخر إغلاق"
        ],
        "السعر السابق": [
            "السعر السابق", "السعر السابق "
        ],
        "% التغير اليومي": [
            "% التغير اليومي", "التغير اليومي %"
        ],
        "تاريخ آخر بيانات": [
            "تاريخ آخر بيانات", "التاريخ"
        ]
    }

    for target_col, alternatives in price_aliases.items():
        if target_col not in fixed.columns:
            continue

        source_col = next(
            (c for c in alternatives if c in global_market.columns),
            None
        )

        if source_col is None:
            continue

        mapped = fixed["_wadq_key"].map(
            global_market[source_col]
        )

        missing = fixed[target_col].isna()
        fixed.loc[missing, target_col] = mapped.loc[missing]

# 4. اعتماد النسخة بعد الإصلاح
fixed.drop(columns=["_wadq_key"], inplace=True)

wadq_stage42_market_fixed_df = fixed

print("\n✅ انتهى فحص وإصلاح ربط البيانات.")
print("📊 عدد الصفوف:", len(fixed))
print("📊 عدد الأعمدة:", len(fixed.columns))

print("\n📌 عينة من الجدول بعد الإصلاح:")
display(fixed.head(10))

print("\n📌 أكثر الأعمدة احتواءً على قيم مفقودة:")
missing_counts = fixed.isna().sum()
display(
    missing_counts[missing_counts > 0]
    .sort_values(ascending=False)
    .head(15)
    .to_frame("عدد القيم المفقودة")
)

print("\n📌 تم الحفاظ على الجداول الأصلية الأخرى.")

🌧️ بدء فحص وإصلاح ربط بيانات الودق AI
=======================================================

✅ انتهى فحص وإصلاح ربط البيانات.
📊 عدد الصفوف: 26
📊 عدد الأعمدة: 21

📌 عينة من الجدول بعد الإصلاح:

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,نوع الأصل,السهم,آخر إغلاق,المتوسط 20,...,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,السعر,تصنيف الحركة
0,NG=F,الغاز الطبيعي,3.322000,3.167000,4.894221,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NG=F,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
1,ETH-USD,إيثيريوم,2507.969971,2444.357422,2.602424,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ETH-USD,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
2,BTC-USD,بيتكوين,83349.679688,81762.562500,1.941129,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,BTC-USD,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
3,CL=F,النفط الأمريكي,94.809998,93.739998,1.141455,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,CL=F,NaN,NaN,NaN,🟢 ارتفاع ملحوظ
4,^HSI,Hang Seng - هونغ كونغ,24271.199219,24211.349609,0.247197,2026-10-12,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,^HSI,NaN,NaN,NaN,🟡 حركة محدودة
5,JPY=X,الدولار مقابل الين,158.320999,158.203003,0.074585,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,JPY=X,NaN,NaN,NaN,🟡 حركة محدودة
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,2026-10-09,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,^N225,NaN,NaN,NaN,🟡 حركة محدودة
7,^GSPC,S&P 500 - أمريكا,7805.450195,7807.240234,-0.022928,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,^GSPC,NaN,NaN,NaN,🟡 حركة محدودة
8,EURUSD=X,اليورو مقابل الدولار,1.120072,1.120473,-0.035833,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,EURUSD=X,NaN,NaN,NaN,🟡 حركة محدودة
9,^FTSE,FTSE 100 - بريطانيا,10650.330078,10656.299805,-0.056021,2026-10-13,أصل عالمي,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,^FTSE,NaN,NaN,NaN,🟡 حركة محدودة

📌 أكثر الأعمدة احتواءً على قيم مفقودة:

                 عدد القيم المفقودة
المتوسط 50                       17
المتوسط 20                       17
آخر إغلاق                        17
السهم                            17
إشارة MACD                       17
MACD                             17
حالة RSI                         17
RSI                              17
الاتجاه                          17
عدد_الأخبار                      17
ملخص_الأخبار                     17
السعر                            17
أحدث سعر متاح                     9
السعر السابق                      9
التغير اليومي %                   9

📌 تم الحفاظ على الجداول الأصلية الأخرى.

In [ ]:
# 🌧️ الودق AI — فحص تطابق الرموز بين الجداول
# فحص فقط، دون تعديل أي بيانات

import pandas as pd
from IPython.display import display

print("🌧️ فحص تطابق الرموز")
print("=" * 55)

tables_to_check = [
    "us_technical_df",
    "wadq_global_market_df",
    "wadq_stage42_market_fixed_df",
    "wadq_stage41_decision_df"
]

for name in tables_to_check:
    df = globals().get(name)

    print(f"\n📌 الجدول: {name}")

    if not isinstance(df, pd.DataFrame):
        print("⚠️ غير موجود في الذاكرة الحالية.")
        continue

    print("الحجم:", df.shape)
    print("الأعمدة:", df.columns.tolist())

    # البحث عن أعمدة الرموز
    symbol_cols = [
        c for c in df.columns
        if any(
            word in str(c).lower()
            for word in ["ticker", "symbol", "الرمز"]
        )
    ]

    if symbol_cols:
        print("الرموز الموجودة:")
        display(df[symbol_cols].head(30))

print("\n✅ انتهى الفحص دون تعديل الجداول.")

🌧️ فحص تطابق الرموز
=======================================================

📌 الجدول: us_technical_df
الحجم: (9, 10)
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']
الرموز الموجودة:

   الرمز
0   NVDA
1   TSLA
2   AAPL
3   MSFT
4   AMZN
5  GOOGL
6   META
7    QQQ
8    SPY

📌 الجدول: wadq_global_market_df
الحجم: (17, 6)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']
الرموز الموجودة:

       الرمز
0      ^GSPC
1      ^IXIC
2       ^DJI
3     ^GDAXI
4      ^FCHI
5      ^FTSE
6      ^N225
7       ^HSI
8       GC=F
9       SI=F
10      CL=F
11      BZ=F
12      NG=F
13  EURUSD=X
14     JPY=X
15   BTC-USD
16   ETH-USD

📌 الجدول: wadq_stage42_market_fixed_df
الحجم: (26, 21)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة']
الرموز الموجودة:

       الرمز    ticker
0       NG=F      NG=F
1    ETH-USD   ETH-USD
2    BTC-USD   BTC-USD
3       CL=F      CL=F
4       ^HSI      ^HSI
5      JPY=X     JPY=X
6      ^N225     ^N225
7      ^GSPC     ^GSPC
8   EURUSD=X  EURUSD=X
9      ^FTSE     ^FTSE
10     ^FCHI     ^FCHI
11    ^GDAXI    ^GDAXI
12     ^IXIC     ^IXIC
13      GC=F      GC=F
14      BZ=F      BZ=F
15      ^DJI      ^DJI
16      SI=F      SI=F
17      NVDA      NVDA
18      TSLA      TSLA
19      AAPL      AAPL
20      MSFT      MSFT
21      AMZN      AMZN
22     GOOGL     GOOGL
23      META      META
24       QQQ       QQQ
25       SPY       SPY

📌 الجدول: wadq_stage41_decision_df
الحجم: (26, 20)
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر']
الرموز الموجودة:

       الرمز ticker
0      ^GSPC    NaN
1      ^IXIC    NaN
2       ^DJI    NaN
3     ^GDAXI    NaN
4      ^FCHI    NaN
5      ^FTSE    NaN
6      ^N225    NaN
7       ^HSI    NaN
8       GC=F    NaN
9       SI=F    NaN
10      CL=F    NaN
11      BZ=F    NaN
12      NG=F    NaN
13  EURUSD=X    NaN
14     JPY=X    NaN
15   BTC-USD    NaN
16   ETH-USD    NaN
17      NVDA   NVDA
18      TSLA   TSLA
19      AAPL   AAPL
20      MSFT   MSFT
21      AMZN   AMZN
22     GOOGL  GOOGL
23      META   META
24       QQQ    QQQ
25       SPY    SPY

✅ انتهى الفحص دون تعديل الجداول.

In [ ]:
# 🌧️ الودق AI — المرحلة 42
# إصلاح رموز الأصول المفقودة في ticker

import pandas as pd
from IPython.display import display

print("🌧️ بدء إصلاح رموز الأصول")
print("=" * 50)

# التحقق من وجود الجدول
if "wadq_stage42_market_fixed_df" not in globals():
    raise ValueError("جدول المرحلة 42 غير موجود.")

# العمل على الجدول الحالي مع الحفاظ على بياناته
df = wadq_stage42_market_fixed_df.copy()

# التحقق من الأعمدة المطلوبة
if "الرمز" not in df.columns or "ticker" not in df.columns:
    print("⚠️ لم يتم العثور على عمودي الرمز وticker.")
    print("الأعمدة الموجودة:", df.columns.tolist())

else:
    # تعبئة الرموز الناقصة فقط
    missing_before = df["ticker"].isna().sum()

    df["ticker"] = df["ticker"].where(
        df["ticker"].notna(),
        df["الرمز"]
    )

    # تنظيف الرموز النصية
    df["ticker"] = df["ticker"].astype("string").str.strip()

    # حفظ النسخة المصححة
    wadq_stage42_market_fixed_df = df

    print("✅ اكتمل إصلاح عمود ticker.")
    print("عدد الصفوف:", len(df))
    print("عدد الرموز التي كانت مفقودة:", missing_before)
    print("عدد الرموز المفقودة الآن:", df["ticker"].isna().sum())

    print("\n📌 معاينة الرموز بعد الإصلاح:")
    display(df[["الرمز", "ticker"]].head(26))

    print("\n✅ لم نحذف أي صف أو عمود.")

🌧️ بدء إصلاح رموز الأصول
==================================================
✅ اكتمل إصلاح عمود ticker.
عدد الصفوف: 26
عدد الرموز التي كانت مفقودة: 0
عدد الرموز المفقودة الآن: 0

📌 معاينة الرموز بعد الإصلاح:

       الرمز    ticker
0       NG=F      NG=F
1    ETH-USD   ETH-USD
2    BTC-USD   BTC-USD
3       CL=F      CL=F
4       ^HSI      ^HSI
5      JPY=X     JPY=X
6      ^N225     ^N225
7      ^GSPC     ^GSPC
8   EURUSD=X  EURUSD=X
9      ^FTSE     ^FTSE
10     ^FCHI     ^FCHI
11    ^GDAXI    ^GDAXI
12     ^IXIC     ^IXIC
13      GC=F      GC=F
14      BZ=F      BZ=F
15      ^DJI      ^DJI
16      SI=F      SI=F
17      NVDA      NVDA
18      TSLA      TSLA
19      AAPL      AAPL
20      MSFT      MSFT
21      AMZN      AMZN
22     GOOGL     GOOGL
23      META      META
24       QQQ       QQQ
25       SPY       SPY

✅ لم نحذف أي صف أو عمود.

In [ ]:
# 🌧️ الودق AI — فحص جدول القرار قبل المرحلة 43

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI — فحص جدول القرار")
print("=" * 55)

# فحص الجداول المطلوبة دون تعديلها
tables_to_check = [
    "wadq_stage41_decision_df",
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_master_report_v3_df"
]

for name in tables_to_check:
    table = globals().get(name)

    if isinstance(table, pd.DataFrame):
        print(f"\n✅ {name}")
        print(f"عدد الصفوف: {len(table)}")
        print(f"عدد الأعمدة: {len(table.columns)}")
        print("أسماء الأعمدة:")
        print(table.columns.tolist())
    else:
        print(f"\n⚠️ الجدول غير موجود: {name}")

# عرض لوحة القرار إن كانت موجودة
if isinstance(
    globals().get("wadq_stage41_decision_df"),
    pd.DataFrame
):
    print("\n📊 معاينة جدول القرار — المرحلة 41")
    display(wadq_stage41_decision_df.head(10))

print("\n✅ انتهى الفحص دون تعديل الجداول.")

🌧️ الودق AI — فحص جدول القرار
=======================================================

✅ wadq_stage41_decision_df
عدد الصفوف: 26
عدد الأعمدة: 20
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر']

✅ wadq_global_us_unified_df
عدد الصفوف: 26
عدد الأعمدة: 20
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر']

✅ wadq_executive_summary_df
عدد الصفوف: 3
عدد الأعمدة: 2
أسماء الأعمدة:
['المؤشر', 'القيمة']

✅ wadq_global_master_report_df
عدد الصفوف: 17
عدد الأعمدة: 6
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

✅ wadq_global_master_report_v2_df
عدد الصفوف: 17
عدد الأعمدة: 6
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

✅ wadq_global_master_report_v3_df
عدد الصفوف: 17
عدد الأعمدة: 6
أسماء الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

📊 معاينة جدول القرار — المرحلة 41

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,نوع الأصل,السهم,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد_الأخبار,ملخص_الأخبار,السعر
0,^GSPC,S&P 500 - أمريكا,7805.450195,7807.240234,-0.022928,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,^IXIC,Nasdaq Composite - أمريكا,27204.380859,27245.900391,-0.152388,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,^DJI,Dow Jones - أمريكا,51670.101562,51850.550781,-0.348018,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,^GDAXI,DAX - ألمانيا,25259.900391,25277.679688,-0.070336,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,^FCHI,CAC 40 - فرنسا,7827.629883,7832.879883,-0.067025,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,^FTSE,FTSE 100 - بريطانيا,10650.330078,10656.299805,-0.056021,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,2026-10-09,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,^HSI,Hang Seng - هونغ كونغ,24271.199219,24211.349609,0.247197,2026-10-12,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,GC=F,الذهب,4183.000000,4190.600098,-0.181361,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,SI=F,الفضة,59.369999,60.140999,-1.281987,2026-10-13,أصل عالمي,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

✅ انتهى الفحص دون تعديل الجداول.

In [ ]:
# 🌧️ الودق AI — إصلاح مباشر للمرحلة 42
# إنشاء نسخة إصلاح دون تعديل الجداول الأصلية

import pandas as pd
import numpy as np
from IPython.display import display

print("🌧️ الودق AI — بدء الإصلاح المباشر")
print("=" * 55)

# 1) تحديد الجدول الأساسي المتاح
source_name = None
source_df = None

for name in [
    "wadq_global_us_unified_df",
    "wadq_stage41_decision_df",
    "wadq_global_priority_df",
    "wadq_global_master_report_v3_df",
    "wadq_global_master_report_df",
    "wadq_stage42_market_fixed_df",
    "wadq_stage42_market_df"
]:
    obj = globals().get(name)
    if isinstance(obj, pd.DataFrame) and not obj.empty:
        source_name = name
        source_df = obj.copy(deep=True)
        break

if source_df is None:
    print("⚠️ لم يُعثر على جدول أساسي في الذاكرة الحالية.")
    print("لا تشغّلي Run all؛ أرسلي لي صورة النتيجة.")
else:
    print(f"✅ الجدول الأساسي: {source_name}")
    print(f"عدد الصفوف: {len(source_df)}")

    # 2) إصلاح عمود الرمز في النسخة الجديدة فقط
    if "ticker" in source_df.columns and "الرمز" in source_df.columns:
        source_df["ticker"] = (
            source_df["ticker"]
            .replace(r"^\s*$", np.nan, regex=True)
            .fillna(source_df["الرمز"])
        )

    elif "الرمز" in source_df.columns:
        source_df["ticker"] = source_df["الرمز"]

    elif "ticker" not in source_df.columns:
        print("⚠️ لا يوجد عمود رمز معروف في الجدول.")

    # 3) توحيد أسماء أعمدة الأسعار والتغير اليومي
    aliases = {
        "السعر": ["أحدث سعر متاح", "أحدث سعر", "آخر إغلاق"],
        "التغير اليومي %": ["التغير اليومي %", "التغير اليومي"],
        "السعر السابق": ["السعر السابق", "السعر السابق "],
        "تاريخ آخر بيانات": ["تاريخ آخر بيانات", "تاريخ آخر بيانات "]
    }

    for target, candidates in aliases.items():
        if target not in source_df.columns:
            for candidate in candidates:
                if candidate in source_df.columns:
                    source_df[target] = source_df[candidate]
                    break

    # 4) إصلاح قيم السعر والتغير من الجداول المتاحة عند تطابق الرمز
    reference_names = [
        "wadq_global_market_df",
        "wadq_global_alerts_df",
        "wadq_global_master_report_v3_df",
        "wadq_global_master_report_df",
        "wadq_global_priority_df",
        "us_technical_df"
    ]

    for ref_name in reference_names:
        ref = globals().get(ref_name)

        if not isinstance(ref, pd.DataFrame) or ref.empty:
            continue

        ref = ref.copy()

        # تحديد عمود الرمز
        ref_ticker = next(
            (c for c in ["ticker", "الرمز", "رمز", "الأسهم"]
             if c in ref.columns),
            None
        )

        if ref_ticker is None:
            continue

        ref[ref_ticker] = ref[ref_ticker].astype("string").str.strip().str.upper()
        source_df["ticker"] = source_df["ticker"].astype("string").str.strip().str.upper()

        ref = ref.dropna(subset=[ref_ticker]).drop_duplicates(
            subset=[ref_ticker], keep="last"
        )

        ref = ref.set_index(ref_ticker)

        for target, candidates in {
            "السعر": ["السعر", "أحدث سعر متاح", "أحدث سعر", "آخر إغلاق", "السعر الحالي"],
            "التغير اليومي %": ["التغير اليومي %", "التغير اليومي"],
            "السعر السابق": ["السعر السابق", "السعر السابق "],
            "تاريخ آخر بيانات": ["تاريخ آخر بيانات"]
        }.items():

            ref_col = next(
                (c for c in candidates if c in ref.columns),
                None
            )

            if ref_col is None:
                continue

            if target not in source_df.columns:
                source_df[target] = np.nan

            mapped = source_df["ticker"].map(ref[ref_col])
            source_df[target] = source_df[target].where(
                source_df[target].notna(), mapped
            )

    # 5) حفظ النسخة الجديدة بأسماء مستقلة
    wadq_stage42_repaired_df = source_df.copy(deep=True)
    wadq_stage42_market_fixed_df = source_df.copy(deep=True)

    # 6) تقرير الإصلاح
    print("\n✅ اكتمل فحص وإصلاح النسخة الجديدة.")
    print("📌 الجداول الأصلية لم تُعدّل.")
    print(f"📊 عدد الصفوف: {len(wadq_stage42_repaired_df)}")
    print(f"📊 عدد الأعمدة: {len(wadq_stage42_repaired_df.columns)}")

    check_cols = [
        c for c in [
            "ticker", "السعر", "التغير اليومي %",
            "السعر السابق", "تاريخ آخر بيانات",
            "المتوسط 20", "المتوسط 50", "RSI", "MACD"
        ]
        if c in wadq_stage42_repaired_df.columns
    ]

    print("\n📋 معاينة النسخة بعد الإصلاح:")
    display(wadq_stage42_repaired_df[check_cols].head(10))

    print("\n📊 عدد القيم المفقودة:")
    display(
        wadq_stage42_repaired_df[check_cols]
        .isna()
        .sum()
        .rename("عدد القيم المفقودة")
        .to_frame()
    )

    print("\n✅ انتهى الإصلاح دون تعديل الجداول الأصلية.")

🌧️ الودق AI — بدء الإصلاح المباشر
=======================================================
✅ الجدول الأساسي: wadq_global_us_unified_df
عدد الصفوف: 26

✅ اكتمل فحص وإصلاح النسخة الجديدة.
📌 الجداول الأصلية لم تُعدّل.
📊 عدد الصفوف: 26
📊 عدد الأعمدة: 20

📋 معاينة النسخة بعد الإصلاح:

,ticker,السعر,التغير اليومي %,السعر السابق,تاريخ آخر بيانات,المتوسط 20,المتوسط 50,RSI,MACD
0,^GSPC,7805.450195,-0.022928,7807.240234,2026-10-13,NaN,NaN,NaN,NaN
1,^IXIC,27204.380859,-0.152388,27245.900391,2026-10-13,NaN,NaN,NaN,NaN
2,^DJI,51670.101562,-0.348018,51850.550781,2026-10-13,NaN,NaN,NaN,NaN
3,^GDAXI,25259.900391,-0.070336,25277.679688,2026-10-13,NaN,NaN,NaN,NaN
4,^FCHI,7827.629883,-0.067025,7832.879883,2026-10-13,NaN,NaN,NaN,NaN
5,^FTSE,10650.330078,-0.056021,10656.299805,2026-10-13,NaN,NaN,NaN,NaN
6,^N225,69030.921875,-0.016204,69042.109375,2026-10-09,NaN,NaN,NaN,NaN
7,^HSI,24271.199219,0.247197,24211.349609,2026-10-12,NaN,NaN,NaN,NaN
8,GC=F,4183.000000,-0.181361,4190.600098,2026-10-13,NaN,NaN,NaN,NaN
9,SI=F,59.369999,-1.281987,60.140999,2026-10-13,NaN,NaN,NaN,NaN

📊 عدد القيم المفقودة:

                  عدد القيم المفقودة
ticker                             0
السعر                              0
التغير اليومي %                    9
السعر السابق                       9
تاريخ آخر بيانات                   9
المتوسط 20                        17
المتوسط 50                        17
RSI                               17
MACD                              17

✅ انتهى الإصلاح دون تعديل الجداول الأصلية.

In [ ]:
# 🌧️ الودق AI — فحص مصادر المؤشرات الفنية وإصلاحها
# المرحلة 42 — دون تعديل الجداول الأصلية

import pandas as pd
import numpy as np
from IPython.display import display

print("🌧️ الودق AI — فحص المؤشرات الفنية")
print("=" * 55)

# الجداول التي قد تحتوي على المؤشرات الفنية
candidate_names = [
    "wadq_stage42_repaired_df",
    "wadq_global_us_unified_df",
    "wadq_stage42_market_fixed_df",
    "wadq_stage42_market_df",
    "us_technical_df",
    "technical_df"
]

found_tables = []

for name in candidate_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        found_tables.append((name, obj))

        print(f"\n✅ الجدول: {name}")
        print(f"الصفوف: {len(obj)} | الأعمدة: {len(obj.columns)}")

        # عرض أعمدة المؤشرات الفنية الموجودة فقط
        technical_cols = [
            c for c in obj.columns
            if any(word in str(c).lower() for word in [
                "المتوسط", "rsi", "macd", "ticker",
                "الرمز", "السهم", "السعر", "close"
            ])
        ]

        print("الأعمدة ذات الصلة:")
        print(technical_cols)

if not found_tables:
    print("⚠️ لم يتم العثور على جداول متاحة للفحص.")

# فحص مصدر البيانات الفنية الأمريكي
if isinstance(globals().get("us_technical_df"), pd.DataFrame):
    print("\n📊 معاينة المؤشرات الفنية الأمريكية:")
    display(us_technical_df.head(10))

print("\n✅ انتهى الفحص دون تعديل أي جدول.")

🌧️ الودق AI — فحص المؤشرات الفنية
=======================================================

✅ الجدول: wadq_stage42_repaired_df
الصفوف: 26 | الأعمدة: 20
الأعمدة ذات الصلة:
['الرمز', 'السعر السابق', 'السهم', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'ticker', 'السعر']

✅ الجدول: wadq_global_us_unified_df
الصفوف: 26 | الأعمدة: 20
الأعمدة ذات الصلة:
['الرمز', 'السعر السابق', 'السهم', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'ticker', 'السعر']

✅ الجدول: wadq_stage42_market_fixed_df
الصفوف: 26 | الأعمدة: 20
الأعمدة ذات الصلة:
['الرمز', 'السعر السابق', 'السهم', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'ticker', 'السعر']

✅ الجدول: wadq_stage42_market_df
الصفوف: 26 | الأعمدة: 21
الأعمدة ذات الصلة:
['الرمز', 'السعر السابق', 'السهم', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'ticker', 'السعر']

✅ الجدول: us_technical_df
الصفوف: 9 | الأعمدة: 10
الأعمدة ذات الصلة:
['السهم', 'الرمز', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD']

📊 معاينة المؤشرات الفنية الأمريكية:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد
3,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد
4,أمازون,AMZN,258.58,252.83,258.35,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط
5,ألفابت,GOOGL,353.78,346.53,345.69,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد
6,ميتا,META,762.50,727.58,646.59,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد
7,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد
8,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد

✅ انتهى الفحص دون تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — المرحلة 42
# إصلاح المؤشرات الفنية للأصول العالمية
# إنشاء نسخة جديدة مع الحفاظ على الجداول الأصلية

import pandas as pd
import numpy as np

print("🌧️ الودق AI — بدء إصلاح المؤشرات الفنية")
print("=" * 55)

# الرموز الموجودة في جدول السوق العالمي
if "wadq_stage42_market_df" not in globals():
    print("⚠️ جدول السوق العالمي غير موجود.")
else:
    market = wadq_stage42_market_df.copy(deep=True)

    # تحديد عمود الرمز
    ticker_col = next(
        (c for c in ["ticker", "الرمز"] if c in market.columns),
        None
    )

    if ticker_col is None:
        print("⚠️ لم يتم العثور على عمود الرموز.")
    else:
        # تثبيت مكتبة جلب الأسعار
        try:
            import yfinance as yf
        except ImportError:
            %pip -q install yfinance
            import yfinance as yf

        # تحديد الأعمدة
        aliases = {
            "المتوسط 20": ["المتوسط 20", "المتوسط المتحرك 20"],
            "المتوسط 50": ["المتوسط 50", "المتوسط المتحرك 50"],
            "RSI": ["RSI"],
            "MACD": ["MACD"],
            "إشارة MACD": ["إشارة MACD"]
        }

        repaired = market.copy(deep=True)

        for target in aliases:
            if target not in repaired.columns:
                repaired[target] = np.nan

        # تحميل التاريخ اللازم لحساب المتوسط 50 وRSI وMACD
        for idx, row in repaired.iterrows():
            ticker = str(row[ticker_col]).strip()

            if not ticker or ticker.lower() == "nan":
                continue

            try:
                hist = yf.Ticker(ticker).history(
                    period="6mo",
                    interval="1d",
                    auto_adjust=True
                )

                if hist.empty or "Close" not in hist.columns:
                    print(f"⚠️ لا توجد بيانات تاريخية: {ticker}")
                    continue

                close = pd.to_numeric(
                    hist["Close"], errors="coerce"
                ).dropna()

                if len(close) < 50:
                    print(f"⚠️ بيانات غير كافية لحساب المتوسط 50: {ticker}")
                    continue

                # المتوسطات المتحركة
                ma20 = close.rolling(20).mean().iloc[-1]
                ma50 = close.rolling(50).mean().iloc[-1]

                # RSI لمدة 14 يومًا
                delta = close.diff()
                gain = delta.clip(lower=0)
                loss = -delta.clip(upper=0)

                avg_gain = gain.ewm(
                    alpha=1/14, min_periods=14, adjust=False
                ).mean()

                avg_loss = loss.ewm(
                    alpha=1/14, min_periods=14, adjust=False
                ).mean()

                rs = avg_gain / avg_loss.replace(0, np.nan)
                rsi = 100 - (100 / (1 + rs))

                # MACD
                ema12 = close.ewm(
                    span=12, adjust=False
                ).mean()

                ema26 = close.ewm(
                    span=26, adjust=False
                ).mean()

                macd = ema12 - ema26

                signal = macd.ewm(
                    span=9, adjust=False
                ).mean()

                # تحديث النسخة الجديدة فقط
                repaired.at[idx, "المتوسط 20"] = round(
                    float(ma20), 4
                )

                repaired.at[idx, "المتوسط 50"] = round(
                    float(ma50), 4
                )

                repaired.at[idx, "RSI"] = round(
                    float(rsi.iloc[-1]), 2
                )

                repaired.at[idx, "MACD"] = round(
                    float(macd.iloc[-1]), 4
                )

                repaired.at[idx, "إشارة MACD"] = round(
                    float(signal.iloc[-1]), 4
                )

                print(f"✅ تم حساب المؤشرات: {ticker}")

            except Exception as e:
                print(f"⚠️ تعذر حساب {ticker}: {str(e)[:150]}")

        # حفظ النسخة دون تعديل الجدول الأصلي
        wadq_stage42_market_indicators_df = repaired

        print("\n" + "=" * 55)
        print("📊 انتهى حساب المؤشرات المتاحة")
        print("عدد الأصول:", len(repaired))

        display(
            repaired[
                [
                    c for c in [
                        ticker_col,
                        "المتوسط 20",
                        "المتوسط 50",
                        "RSI",
                        "MACD",
                        "إشارة MACD"
                    ]
                    if c in repaired.columns
                ]
            ]
        )

        print("\n📌 الجدول الأصلي محفوظ دون تعديل.")
        print("📌 اسم النسخة الجديدة: wadq_stage42_market_indicators_df")

🌧️ الودق AI — بدء إصلاح المؤشرات الفنية
=======================================================
✅ تم حساب المؤشرات: NVDA
✅ تم حساب المؤشرات: TSLA
✅ تم حساب المؤشرات: AAPL
✅ تم حساب المؤشرات: MSFT
✅ تم حساب المؤشرات: AMZN
✅ تم حساب المؤشرات: GOOGL
✅ تم حساب المؤشرات: META
✅ تم حساب المؤشرات: QQQ
✅ تم حساب المؤشرات: SPY

=======================================================
📊 انتهى حساب المؤشرات المتاحة
عدد الأصول: 26

   ticker  المتوسط 20  المتوسط 50    RSI     MACD  إشارة MACD
0     NaN         NaN         NaN    NaN      NaN         NaN
1     NaN         NaN         NaN    NaN      NaN         NaN
2     NaN         NaN         NaN    NaN      NaN         NaN
3     NaN         NaN         NaN    NaN      NaN         NaN
4     NaN         NaN         NaN    NaN      NaN         NaN
5     NaN         NaN         NaN    NaN      NaN         NaN
6     NaN         NaN         NaN    NaN      NaN         NaN
7     NaN         NaN         NaN    NaN      NaN         NaN
8     NaN         NaN         NaN    NaN      NaN         NaN
9     NaN         NaN         NaN    NaN      NaN         NaN
10    NaN         NaN         NaN    NaN      NaN         NaN
11    NaN         NaN         NaN    NaN      NaN         NaN
12    NaN         NaN         NaN    NaN      NaN         NaN
13    NaN         NaN         NaN    NaN      NaN         NaN
14    NaN         NaN         NaN    NaN      NaN         NaN
15    NaN         NaN         NaN    NaN      NaN         NaN
16    NaN         NaN         NaN    NaN      NaN         NaN
17   NVDA    228.3195    222.8984  52.03   2.9231      3.5905
18   TSLA    370.5450    357.1444  54.53   4.9187      4.3678
19   AAPL    336.2800    323.7653  60.50   3.7919      3.8268
20   MSFT    514.2030    502.8689  70.79  12.3949     10.2280
21   AMZN    252.8270    258.3458  54.44   0.9722     -0.3643
22  GOOGL    346.5285    345.6854  58.22   2.0625      0.9157
23   META    727.5843    646.5881  66.04  25.9815     28.9692
24    QQQ    741.2245    726.0622  54.74   8.1107      8.7652
25    SPY    769.6812    767.3864  59.80   3.9933      3.0564

📌 الجدول الأصلي محفوظ دون تعديل.
📌 اسم النسخة الجديدة: wadq_stage42_market_indicators_df

In [ ]:
# ============================================================
# 🌧️ الودق AI — الإصلاح الشامل قبل المرحلة 43
# المرحلة 42 — النسخة الموحدة النهائية للفحص
#
# إصلاح الرموز والأسعار والمؤشرات الفنية والاتجاهات
# الحفاظ على الجداول الأصلية دون تعديلها
# ============================================================

import pandas as pd
import numpy as np
import warnings

from IPython.display import display

warnings.filterwarnings("ignore")

print("🌧️ الودق AI — بدء الإصلاح الشامل")
print("=" * 65)

# ------------------------------------------------------------
# 1. التأكد من وجود جدول السوق
# ------------------------------------------------------------

source_candidates = [
    "wadq_stage42_market_df",
    "wadq_stage42_market_fixed_df",
    "wadq_global_us_unified_df"
]

source_name = None
source_df = None

for name in source_candidates:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame) and not obj.empty:
        source_name = name
        source_df = obj.copy(deep=True)
        break

if source_df is None:
    raise ValueError(
        "لم يتم العثور على جدول السوق. "
        "توقفي وأرسلي صورة النتيجة."
    )

print(f"✅ الجدول المستخدم: {source_name}")
print(f"📊 عدد الصفوف الأصلية: {len(source_df)}")


# ------------------------------------------------------------
# 2. إصلاح وتوحيد الرموز
# ------------------------------------------------------------

market = source_df.copy(deep=True)

# اختيار عمود الرمز
symbol_candidates = [
    "ticker",
    "الرمز",
    "رمز",
    "رمز الأصل"
]

symbol_columns = [
    c for c in symbol_candidates if c in market.columns
]

if not symbol_columns:
    raise ValueError(
        "لم يتم العثور على عمود يحتوي على رموز الأصول."
    )

# إنشاء عمود رمز موحد
market["ticker"] = pd.Series(
    [None] * len(market),
    index=market.index,
    dtype="object"
)

for col in symbol_columns:
    values = market[col].astype("string").str.strip()

    values = values.replace(
        ["", "nan", "None", "<NA>"],
        pd.NA
    )

    market["ticker"] = market["ticker"].fillna(values)

market["ticker"] = (
    market["ticker"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# إزالة الصفوف التي لا تحتوي على رمز صالح من النسخة الجديدة فقط
market = market[
    market["ticker"].notna()
    & (market["ticker"] != "")
].copy()

market = market.drop_duplicates(
    subset=["ticker"],
    keep="first"
).reset_index(drop=True)

print(f"✅ الأصول ذات الرموز الصالحة: {len(market)}")


# ------------------------------------------------------------
# 3. تجهيز الأعمدة المطلوبة
# ------------------------------------------------------------

required_columns = [
    "السعر",
    "السعر السابق",
    "التغير اليومي %",
    "تاريخ آخر بيانات",
    "المتوسط 20",
    "المتوسط 50",
    "RSI",
    "MACD",
    "إشارة MACD",
    "حالة RSI",
    "الاتجاه",
    "حالة البيانات"
]

for col in required_columns:
    if col not in market.columns:
        market[col] = np.nan


# ------------------------------------------------------------
# 4. تجهيز مصدر البيانات التاريخية
# ------------------------------------------------------------

try:
    import yfinance as yf

except ImportError:
    %pip -q install yfinance
    import yfinance as yf


# ------------------------------------------------------------
# 5. دوال حساب المؤشرات الفنية
# ------------------------------------------------------------

def calculate_indicators(history):

    if history is None or history.empty:
        return None

    if "Close" not in history.columns:
        return None

    close = pd.to_numeric(
        history["Close"],
        errors="coerce"
    ).dropna()

    close = close[close > 0]

    if len(close) < 2:
        return None

    result = {}

    # آخر سعر والسعر السابق
    result["السعر"] = float(close.iloc[-1])
    result["السعر السابق"] = float(close.iloc[-2])

    result["التغير اليومي %"] = (
        (close.iloc[-1] / close.iloc[-2]) - 1
    ) * 100

    # تاريخ آخر إغلاق متاح
    result["تاريخ آخر بيانات"] = str(
        pd.Timestamp(close.index[-1]).date()
    )

    # المتوسط المتحرك 20
    if len(close) >= 20:
        result["المتوسط 20"] = float(
            close.rolling(20).mean().iloc[-1]
        )
    else:
        result["المتوسط 20"] = np.nan

    # المتوسط المتحرك 50
    if len(close) >= 50:
        result["المتوسط 50"] = float(
            close.rolling(50).mean().iloc[-1]
        )
    else:
        result["المتوسط 50"] = np.nan

    # RSI لمدة 14 فترة
    if len(close) >= 15:

        delta = close.diff()

        gains = delta.clip(lower=0)
        losses = -delta.clip(upper=0)

        avg_gain = gains.ewm(
            alpha=1/14,
            min_periods=14,
            adjust=False
        ).mean()

        avg_loss = losses.ewm(
            alpha=1/14,
            min_periods=14,
            adjust=False
        ).mean()

        rs = avg_gain / avg_loss.replace(0, np.nan)

        rsi = 100 - (100 / (1 + rs))

        # معالجة حالات الارتفاع المستمر أو الثبات
        rsi = rsi.mask(
            (avg_loss == 0) & (avg_gain > 0),
            100
        )

        rsi = rsi.mask(
            (avg_gain == 0) & (avg_loss > 0),
            0
        )

        rsi = rsi.mask(
            (avg_gain == 0) & (avg_loss == 0),
            50
        )

        result["RSI"] = float(rsi.iloc[-1])

    else:
        result["RSI"] = np.nan

    # MACD وإشارة MACD
    if len(close) >= 35:

        ema12 = close.ewm(
            span=12,
            adjust=False
        ).mean()

        ema26 = close.ewm(
            span=26,
            adjust=False
        ).mean()

        macd = ema12 - ema26

        signal = macd.ewm(
            span=9,
            adjust=False
        ).mean()

        result["MACD"] = float(macd.iloc[-1])

        result["إشارة MACD"] = float(
            signal.iloc[-1]
        )

    else:
        result["MACD"] = np.nan
        result["إشارة MACD"] = np.nan

    return result


# ------------------------------------------------------------
# 6. جلب البيانات التاريخية وإصلاح جميع الأصول
# ------------------------------------------------------------

success_count = 0
failure_count = 0
results_log = []

print("\n📡 بدء فحص الأسعار والمؤشرات...")
print("-" * 65)

for idx, row in market.iterrows():

    ticker = str(row["ticker"]).strip().upper()

    try:

        history = yf.Ticker(ticker).history(
            period="6mo",
            interval="1d",
            auto_adjust=True,
            actions=False
        )

        indicators = calculate_indicators(history)

        if indicators is None:

            market.at[idx, "حالة البيانات"] = (
                "تعذر جلب بيانات كافية"
            )

            failure_count += 1

            results_log.append({
                "ticker": ticker,
                "النتيجة": "تعذر جلب البيانات"
            })

            print(f"⚠️ {ticker}: لم تتوفر بيانات كافية")

            continue

        # تحديث الأسعار والمؤشرات في النسخة الجديدة فقط
        for col, value in indicators.items():

            if pd.notna(value):
                market.at[idx, col] = value

        # تحديد حالة RSI
        rsi_value = indicators.get("RSI", np.nan)

        if pd.notna(rsi_value):

            if rsi_value >= 70:
                market.at[idx, "حالة RSI"] = (
                    "تشبع شرائي"
                )

            elif rsi_value <= 30:
                market.at[idx, "حالة RSI"] = (
                    "تشبع بيعي"
                )

            else:
                market.at[idx, "حالة RSI"] = (
                    "ضمن النطاق المتوسط"
                )

        # تحديد الاتجاه من المتوسطات وMACD
        ma20 = indicators.get("المتوسط 20", np.nan)
        ma50 = indicators.get("المتوسط 50", np.nan)
        macd_value = indicators.get("MACD", np.nan)
        signal_value = indicators.get(
            "إشارة MACD", np.nan
        )

        current_price = indicators.get("السعر", np.nan)

        if (
            pd.notna(ma20)
            and pd.notna(ma50)
            and pd.notna(macd_value)
            and pd.notna(signal_value)
        ):

            if (
                current_price > ma20 > ma50
                and macd_value > signal_value
            ):
                direction = "صاعد"

            elif (
                current_price < ma20 < ma50
                and macd_value < signal_value
            ):
                direction = "هابط"

            else:
                direction = "مختلط"

            market.at[idx, "الاتجاه"] = direction

        market.at[idx, "حالة البيانات"] = "تم التحديث"

        success_count += 1

        results_log.append({
            "ticker": ticker,
            "النتيجة": "تم التحديث"
        })

        print(f"✅ {ticker}: تم تحديث البيانات")

    except Exception as e:

        failure_count += 1

        market.at[idx, "حالة البيانات"] = (
            "تعذر التحديث"
        )

        results_log.append({
            "ticker": ticker,
            "النتيجة": "تعذر التحديث"
        })

        print(
            f"⚠️ {ticker}: "
            f"{str(e)[:100]}"
        )


# ------------------------------------------------------------
# 7. حفظ النسخة الجديدة دون المساس بالأصل
# ------------------------------------------------------------

wadq_stage42_repaired_df = market.copy(deep=True)

wadq_stage42_market_fixed_v2_df = market.copy(deep=True)

wadq_stage42_repair_log_df = pd.DataFrame(
    results_log
)


# ------------------------------------------------------------
# 8. فحص القيم المفقودة
# ------------------------------------------------------------

print("\n")
print("=" * 65)
print("📊 تقرير الإصلاح الشامل")
print("=" * 65)

print(f"📌 الجدول الأصلي: {source_name}")
print(f"📌 عدد الأصول المفحوصة: {len(market)}")
print(f"✅ الأصول التي تم تحديثها: {success_count}")
print(f"⚠️ الأصول التي تعذر تحديثها: {failure_count}")

important_columns = [
    "ticker",
    "السعر",
    "السعر السابق",
    "التغير اليومي %",
    "تاريخ آخر بيانات",
    "المتوسط 20",
    "المتوسط 50",
    "RSI",
    "MACD",
    "إشارة MACD",
    "حالة RSI",
    "الاتجاه",
    "حالة البيانات"
]

important_columns = [
    c for c in important_columns
    if c in market.columns
]

missing_report = (
    market[important_columns]
    .isna()
    .sum()
    .rename("عدد القيم المفقودة")
    .to_frame()
)

print("\n📋 عدد القيم المفقودة في الأعمدة المهمة:")
display(missing_report)

print("\n📋 معاينة أول 10 أصول بعد الإصلاح:")
display(
    market[important_columns].head(10)
)

print("\n📋 الأصول التي تعذر تحديثها:")
display(
    wadq_stage42_repair_log_df[
        wadq_stage42_repair_log_df["النتيجة"]
        != "تم التحديث"
    ]
)

print("\n" + "=" * 65)
print("🌧️ انتهى الإصلاح والفحص.")
print("📌 لم يتم تعديل الجداول الأصلية.")
print("📌 اسم النسخة الجديدة:")
print("wadq_stage42_repaired_df")
print("=" * 65)

🌧️ الودق AI — بدء الإصلاح الشامل
=================================================================
✅ الجدول المستخدم: wadq_stage42_market_df
📊 عدد الصفوف الأصلية: 26
✅ الأصول ذات الرموز الصالحة: 26

📡 بدء فحص الأسعار والمؤشرات...
-----------------------------------------------------------------
✅ NG=F: تم تحديث البيانات
✅ ETH-USD: تم تحديث البيانات
✅ BTC-USD: تم تحديث البيانات
✅ CL=F: تم تحديث البيانات
✅ ^HSI: تم تحديث البيانات
✅ JPY=X: تم تحديث البيانات
✅ ^N225: تم تحديث البيانات
✅ ^GSPC: تم تحديث البيانات
✅ EURUSD=X: تم تحديث البيانات
✅ ^FTSE: تم تحديث البيانات
✅ ^FCHI: تم تحديث البيانات
✅ ^GDAXI: تم تحديث البيانات
✅ ^IXIC: تم تحديث البيانات
✅ GC=F: تم تحديث البيانات
✅ BZ=F: تم تحديث البيانات
✅ ^DJI: تم تحديث البيانات
✅ SI=F: تم تحديث البيانات
✅ NVDA: تم تحديث البيانات
✅ TSLA: تم تحديث البيانات
✅ AAPL: تم تحديث البيانات
✅ MSFT: تم تحديث البيانات
✅ AMZN: تم تحديث البيانات
✅ GOOGL: تم تحديث البيانات
✅ META: تم تحديث البيانات
✅ QQQ: تم تحديث البيانات
✅ SPY: تم تحديث البيانات


=================================================================
📊 تقرير الإصلاح الشامل
=================================================================
📌 الجدول الأصلي: wadq_stage42_market_df
📌 عدد الأصول المفحوصة: 26
✅ الأصول التي تم تحديثها: 26
⚠️ الأصول التي تعذر تحديثها: 0

📋 عدد القيم المفقودة في الأعمدة المهمة:

                  عدد القيم المفقودة
ticker                             0
السعر                              0
السعر السابق                       0
التغير اليومي %                    0
تاريخ آخر بيانات                   0
المتوسط 20                         0
المتوسط 50                         0
RSI                                0
MACD                               0
إشارة MACD                         0
حالة RSI                           0
الاتجاه                            0
حالة البيانات                      0

📋 معاينة أول 10 أصول بعد الإصلاح:

,ticker,السعر,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,المتوسط 20,المتوسط 50,RSI,MACD,إشارة MACD,حالة RSI,الاتجاه,حالة البيانات
0,NG=F,3.319000,3.167000,4.799493,2026-10-13,3.065850,2.913800,65.119415,0.085483,0.066702,ضمن النطاق المتوسط,صاعد,تم التحديث
1,ETH-USD,2495.610107,2444.357422,2.096775,2026-10-13,2625.733044,2556.052612,43.005780,-18.036937,14.418809,ضمن النطاق المتوسط,مختلط,تم التحديث
2,BTC-USD,83150.796875,81762.562500,1.697885,2026-10-13,83944.970312,81105.876250,52.052178,630.834093,1152.459685,ضمن النطاق المتوسط,مختلط,تم التحديث
3,CL=F,94.580002,93.739998,0.896100,2026-10-13,93.469000,89.667601,55.306037,0.133551,0.302949,ضمن النطاق المتوسط,مختلط,تم التحديث
4,^HSI,24271.199219,24211.349609,0.247197,2026-10-12,24518.043262,25113.559180,43.506278,-280.766738,-257.746799,ضمن النطاق المتوسط,هابط,تم التحديث
5,JPY=X,158.335999,158.520004,-0.116077,2026-10-14,157.699301,157.709661,55.796084,0.258216,0.104473,ضمن النطاق المتوسط,مختلط,تم التحديث
6,^N225,69030.921875,69042.109375,-0.016204,2026-10-09,66523.845703,65990.145078,59.808360,1095.126103,679.323533,ضمن النطاق المتوسط,صاعد,تم التحديث
7,^GSPC,7807.240234,7811.540039,-0.055044,2026-10-12,7714.137036,7703.269023,59.424362,36.639431,25.972888,ضمن النطاق المتوسط,صاعد,تم التحديث
8,EURUSD=X,1.120072,1.116022,0.362908,2026-10-14,1.132343,1.149010,28.791812,-0.009201,-0.008266,تشبع بيعي,هابط,تم التحديث
9,^FTSE,10656.299805,10552.099609,0.987483,2026-10-12,10615.784912,10724.677949,52.163674,-54.872628,-56.410793,ضمن النطاق المتوسط,مختلط,تم التحديث

📋 الأصول التي تعذر تحديثها:

Empty DataFrame
Columns: [ticker, النتيجة]
Index: []

=================================================================
🌧️ انتهى الإصلاح والفحص.
📌 لم يتم تعديل الجداول الأصلية.
📌 اسم النسخة الجديدة:
wadq_stage42_repaired_df
=================================================================

In [ ]:
# ============================================================
# 🌧️ الودق AI — الفحص النهائي قبل المرحلة 43
# ============================================================

import pandas as pd

df = globals().get("wadq_stage42_repaired_df")

if not isinstance(df, pd.DataFrame):
    raise ValueError("جدول الإصلاح غير موجود.")

print("🌧️ الودق AI — تقرير الجاهزية للمرحلة 43")
print("=" * 55)

print(f"📊 إجمالي الأصول: {len(df)}")

# المؤشرات الأساسية المطلوبة
required_columns = [
    "ticker",
    "السعر",
    "السعر السابق",
    "التغير اليومي %",
    "المتوسط 20",
    "المتوسط 50",
    "RSI",
    "MACD",
    "إشارة MACD"
]

existing_columns = [
    col for col in required_columns
    if col in df.columns
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

print("\n✅ الأعمدة الموجودة:")
print(existing_columns)

if missing_columns:
    print("\n⚠️ الأعمدة غير الموجودة:")
    print(missing_columns)

# فحص القيم المفقودة
if existing_columns:
    print("\n📋 عدد القيم المفقودة:")
    print(df[existing_columns].isna().sum())

# فحص المؤشرات الرقمية
indicator_columns = [
    col for col in [
        "المتوسط 20",
        "المتوسط 50",
        "RSI",
        "MACD",
        "إشارة MACD"
    ]
    if col in df.columns
]

if indicator_columns:
    complete = df[indicator_columns].notna().all(axis=1)

    print("\n📊 اكتمال المؤشرات:")
    print(f"✅ أصول مكتملة المؤشرات: {int(complete.sum())}")
    print(f"⚠️ أصول تحتاج مراجعة: {int((~complete).sum())}")

    if (~complete).any():
        print("\n📌 الأصول التي تحتاج مراجعة:")
        display(
            df.loc[~complete, ["ticker"] + indicator_columns]
        )

print("\n" + "=" * 55)
print("📌 انتهى الفحص دون تعديل أي جدول.")

🌧️ الودق AI — تقرير الجاهزية للمرحلة 43
=======================================================
📊 إجمالي الأصول: 26

✅ الأعمدة الموجودة:
['ticker', 'السعر', 'السعر السابق', 'التغير اليومي %', 'المتوسط 20', 'المتوسط 50', 'RSI', 'MACD', 'إشارة MACD']

📋 عدد القيم المفقودة:
ticker             0
السعر              0
السعر السابق       0
التغير اليومي %    0
المتوسط 20         0
المتوسط 50         0
RSI                0
MACD               0
إشارة MACD         0
dtype: int64

📊 اكتمال المؤشرات:
✅ أصول مكتملة المؤشرات: 26
⚠️ أصول تحتاج مراجعة: 0

=======================================================
📌 انتهى الفحص دون تعديل أي جدول.

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 43
# لوحة التقييم الذكي للأصول الـ26
# دون تعديل الجداول الأصلية
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("🌧️ الودق AI — المرحلة 43")
print("=" * 60)

# 1. التأكد من وجود جدول الإصلاح
source = globals().get("wadq_stage42_repaired_df")

if not isinstance(source, pd.DataFrame) or source.empty:
    raise ValueError(
        "جدول الإصلاح غير موجود. "
        "توقفي وأرسلي لي النتيجة."
    )

# 2. إنشاء نسخة مستقلة
wadq_stage43_evaluation_df = source.copy(deep=True)

# 3. التأكد من الأعمدة المطلوبة
required = [
    "ticker",
    "السعر",
    "التغير اليومي %",
    "المتوسط 20",
    "المتوسط 50",
    "RSI",
    "MACD",
    "إشارة MACD"
]

missing = [
    col for col in required
    if col not in wadq_stage43_evaluation_df.columns
]

if missing:
    raise ValueError(f"الأعمدة التالية غير موجودة: {missing}")

# 4. تحويل المؤشرات الرقمية إلى أرقام
numeric_columns = [
    "السعر",
    "التغير اليومي %",
    "المتوسط 20",
    "المتوسط 50",
    "RSI",
    "MACD",
    "إشارة MACD"
]

for col in numeric_columns:
    wadq_stage43_evaluation_df[col] = pd.to_numeric(
        wadq_stage43_evaluation_df[col],
        errors="coerce"
    )

# 5. حساب نقاط فنية بسيطة
def evaluate_asset(row):

    values = [
        row["السعر"],
        row["المتوسط 20"],
        row["المتوسط 50"],
        row["RSI"],
        row["MACD"],
        row["إشارة MACD"],
        row["التغير اليومي %"]
    ]

    if any(pd.isna(value) for value in values):
        return pd.Series({
            "النقاط الفنية": np.nan,
            "التقييم الفني": "بيانات غير مكتملة",
            "أولوية المتابعة": "مراجعة البيانات"
        })

    score = 0

    # السعر بالنسبة إلى المتوسطات
    if row["السعر"] > row["المتوسط 20"]:
        score += 1

    if row["السعر"] > row["المتوسط 50"]:
        score += 1

    # مقارنة MACD بإشارته
    if row["MACD"] > row["إشارة MACD"]:
        score += 1

    # RSI ضمن نطاق متوسط
    if 50 <= row["RSI"] < 70:
        score += 1

    # حركة السعر اليومية
    if row["التغير اليومي %"] > 0:
        score += 1

    # تصنيف وصفي، وليس توصية تداول
    if score >= 4:
        assessment = "اتجاه فني إيجابي نسبيًا"
        priority = "متابعة مرتفعة"

    elif score >= 2:
        assessment = "اتجاه فني مختلط"
        priority = "متابعة متوسطة"

    else:
        assessment = "إشارات فنية ضعيفة نسبيًا"
        priority = "مراجعة إضافية"

    return pd.Series({
        "النقاط الفنية": score,
        "التقييم الفني": assessment,
        "أولوية المتابعة": priority
    })

# 6. تطبيق التقييم
evaluation = wadq_stage43_evaluation_df.apply(
    evaluate_asset,
    axis=1
)

wadq_stage43_evaluation_df = pd.concat(
    [
        wadq_stage43_evaluation_df,
        evaluation
    ],
    axis=1
)

# 7. ترتيب الأصول حسب النقاط الفنية
wadq_stage43_evaluation_df = (
    wadq_stage43_evaluation_df
    .sort_values(
        by=["النقاط الفنية", "التغير اليومي %"],
        ascending=[False, False],
        na_position="last"
    )
    .reset_index(drop=True)
)

# 8. إنشاء ملخص المرحلة
wadq_stage43_summary_df = (
    wadq_stage43_evaluation_df
    .groupby(
        ["التقييم الفني", "أولوية المتابعة"],
        dropna=False
    )
    .size()
    .reset_index(name="عدد الأصول")
)

# 9. عرض النتائج
print("✅ اكتملت المرحلة 43.")
print("📊 إجمالي الأصول:", len(wadq_stage43_evaluation_df))
print("📋 إجمالي الأعمدة:", len(wadq_stage43_evaluation_df.columns))

print("\n📈 لوحة التقييم الذكي:")
display(
    wadq_stage43_evaluation_df[
        [
            "ticker",
            "السعر",
            "التغير اليومي %",
            "RSI",
            "MACD",
            "إشارة MACD",
            "النقاط الفنية",
            "التقييم الفني",
            "أولوية المتابعة"
        ]
    ]
)

print("\n📊 ملخص التقييم:")
display(wadq_stage43_summary_df)

print("\n📌 أسماء الجداول الجديدة:")
print("1. wadq_stage43_evaluation_df")
print("2. wadq_stage43_summary_df")

print("\n⚠️ هذا تقييم فني أولي للمتابعة، وليس توصية شراء أو بيع.")
print("🌧️ الودق AI — انتهت المرحلة 43.")

🌧️ الودق AI — المرحلة 43
============================================================
✅ اكتملت المرحلة 43.
📊 إجمالي الأصول: 26
📋 إجمالي الأعمدة: 25

📈 لوحة التقييم الذكي:

,ticker,السعر,التغير اليومي %,RSI,MACD,إشارة MACD,النقاط الفنية,التقييم الفني,أولوية المتابعة
0,NG=F,3.319000,4.799493,65.119415,0.085483,0.066702,5,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
1,GOOGL,353.779999,0.300521,58.219514,2.062511,0.915670,5,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
2,META,762.500000,2.630017,66.039292,25.981541,28.969197,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
3,^FTSE,10656.299805,0.987483,52.163674,-54.872628,-56.410793,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
4,NVDA,228.520004,0.972074,52.030852,2.923070,3.590539,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
5,CL=F,94.580002,0.896100,55.306037,0.133551,0.302949,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
6,MSFT,543.450012,0.425019,70.793518,12.394873,10.227955,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
7,^DJI,51850.550781,0.378670,50.631063,-288.152033,-379.184547,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
8,AAPL,341.269989,0.087981,60.504202,3.791874,3.826761,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
9,SPY,778.010010,-0.011562,59.803635,3.993302,3.056401,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
10,^N225,69030.921875,-0.016204,59.808360,1095.126103,679.323533,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
11,^GSPC,7807.240234,-0.055044,59.424362,36.639431,25.972888,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
12,JPY=X,158.335999,-0.116077,55.796084,0.258216,0.104473,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
13,AMZN,258.579987,-0.366051,54.444562,0.972189,-0.364316,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
14,TSLA,375.230011,-0.740679,54.531118,4.918673,4.367764,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة
15,BTC-USD,83150.796875,1.697885,52.052178,630.834093,1152.459685,3,اتجاه فني مختلط,متابعة متوسطة
16,^IXIC,27204.380859,-0.152388,56.396250,245.477816,246.596794,3,اتجاه فني مختلط,متابعة متوسطة
17,QQQ,743.570007,-0.331078,54.743177,8.110666,8.765242,3,اتجاه فني مختلط,متابعة متوسطة
18,BZ=F,106.160004,-0.459445,60.033166,1.870070,1.979358,3,اتجاه فني مختلط,متابعة متوسطة
19,ETH-USD,2495.610107,2.096775,43.005780,-18.036937,14.418809,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية
20,^GDAXI,25277.679688,0.758991,47.543511,-167.336484,-167.226516,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية
21,^FCHI,7832.879883,0.378682,36.053026,-129.412695,-120.053194,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية
22,EURUSD=X,1.120072,0.362908,28.791812,-0.009201,-0.008266,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية
23,^HSI,24271.199219,0.247197,43.506278,-280.766738,-257.746799,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية
24,GC=F,4180.799805,-0.233864,40.556421,-59.162912,-58.790734,0,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية
25,SI=F,59.330002,-1.348493,39.020993,-1.355719,-1.154046,0,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية

📊 ملخص التقييم:

              التقييم الفني أولوية المتابعة  عدد الأصول
0  إشارات فنية ضعيفة نسبيًا   مراجعة إضافية           7
1   اتجاه فني إيجابي نسبيًا   متابعة مرتفعة          15
2           اتجاه فني مختلط   متابعة متوسطة           4

📌 أسماء الجداول الجديدة:
1. wadq_stage43_evaluation_df
2. wadq_stage43_summary_df

⚠️ هذا تقييم فني أولي للمتابعة، وليس توصية شراء أو بيع.
🌧️ الودق AI — انتهت المرحلة 43.

In [ ]:
# 🌧️ الودق AI — فحص ما قبل المرحلة 44

print("🌧️ الودق AI — فحص الجداول قبل المرحلة 44")
print("=" * 50)

for name in [
    "wadq_stage43_evaluation_df",
    "wadq_stage43_summary_df",
    "wadq_stage42_repaired_df"
]:
    if name in globals():
        df = globals()[name]
        print(f"\n✅ الجدول: {name}")
        print(f"عدد الصفوف: {len(df)}")
        print(f"عدد الأعمدة: {len(df.columns)}")
        print("الأعمدة:")
        print(list(df.columns))
    else:
        print(f"\n⚠️ الجدول غير موجود: {name}")

🌧️ الودق AI — فحص الجداول قبل المرحلة 44
==================================================

✅ الجدول: wadq_stage43_evaluation_df
عدد الصفوف: 26
عدد الأعمدة: 25
الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة', 'حالة البيانات', 'النقاط الفنية', 'التقييم الفني', 'أولوية المتابعة']

✅ الجدول: wadq_stage43_summary_df
عدد الصفوف: 3
عدد الأعمدة: 3
الأعمدة:
['التقييم الفني', 'أولوية المتابعة', 'عدد الأصول']

✅ الجدول: wadq_stage42_repaired_df
عدد الصفوف: 26
عدد الأعمدة: 22
الأعمدة:
['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات', 'نوع الأصل', 'السهم', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد_الأخبار', 'ملخص_الأخبار', 'السعر', 'تصنيف الحركة', 'حالة البيانات']

In [ ]:
# =========================================================
# 🌧️ الودق AI — المرحلة 44
# إنشاء لوحة القرار الذكي
# دون تعديل الجداول السابقة
# =========================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI — المرحلة 44")
print("=" * 55)

# التحقق من وجود جدول المرحلة 43
if "wadq_stage43_evaluation_df" not in globals():
    raise NameError(
        "جدول المرحلة 43 غير موجود. "
        "تأكدي من تشغيل المرحلة 43 أولًا."
    )

source_df = wadq_stage43_evaluation_df.copy()

# الأعمدة الأساسية المطلوبة
preferred_columns = [
    "نوع الأصل",
    "الأصل",
    "الرمز",
    "أحدث سعر متاح",
    "التغير اليومي %",
    "تاريخ آخر بيانات",
    "عدد_الأخبار",
    "ملخص_الأخبار",
    "النقاط الفنية",
    "التقييم الفني",
    "أولوية المتابعة",
    "الاتجاه",
    "حالة RSI",
    "حالة البيانات"
]

# استخدام الأعمدة الموجودة فعليًا فقط
selected_columns = [
    col for col in preferred_columns
    if col in source_df.columns
]

# إنشاء نسخة مستقلة للوحة القرار
wadq_stage44_decision_df = source_df[selected_columns].copy()

# ترتيب الأصول حسب النقاط الفنية، إن توفرت
if "النقاط الفنية" in wadq_stage44_decision_df.columns:
    wadq_stage44_decision_df = (
        wadq_stage44_decision_df.sort_values(
            by="النقاط الفنية",
            ascending=False,
            na_position="last"
        ).reset_index(drop=True)
    )

# إنشاء ملخص حسب التقييم الفني
if "التقييم الفني" in wadq_stage44_decision_df.columns:
    wadq_stage44_summary_df = (
        wadq_stage44_decision_df
        .groupby("التقييم الفني", dropna=False)
        .size()
        .reset_index(name="عدد الأصول")
    )
else:
    wadq_stage44_summary_df = pd.DataFrame({
        "ملاحظة": ["عمود التقييم الفني غير موجود"]
    })

print("✅ تم إنشاء لوحة القرار الذكي.")
print(f"📊 إجمالي الأصول: {len(wadq_stage44_decision_df)}")
print(f"📋 إجمالي الأعمدة: {len(wadq_stage44_decision_df.columns)}")

print("\n📌 لوحة القرار الذكي:")
display(wadq_stage44_decision_df)

print("\n📊 ملخص التقييم الفني:")
display(wadq_stage44_summary_df)

print("\n✅ المرحلة 44 اكتملت.")
print("🔒 الجداول السابقة لم يتم تعديلها.")

🌧️ الودق AI — المرحلة 44
=======================================================
✅ تم إنشاء لوحة القرار الذكي.
📊 إجمالي الأصول: 26
📋 إجمالي الأعمدة: 14

📌 لوحة القرار الذكي:

,نوع الأصل,الأصل,الرمز,أحدث سعر متاح,التغير اليومي %,تاريخ آخر بيانات,عدد_الأخبار,ملخص_الأخبار,النقاط الفنية,التقييم الفني,أولوية المتابعة,الاتجاه,حالة RSI,حالة البيانات
0,أصل عالمي,الغاز الطبيعي,NG=F,3.322000,4.799493,2026-10-13,NaN,NaN,5,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,صاعد,ضمن النطاق المتوسط,تم التحديث
1,سهم أمريكي,ألفابت,GOOGL,NaN,0.300521,2026-10-13,22.0,"S&P 500, Nasdaq close lower, dragged by Alphab...",5,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,صاعد,ضمن النطاق المتوسط,تم التحديث
2,سهم أمريكي,ميتا,META,NaN,2.630017,2026-10-13,2.0,I Predicted That Oracle and Netflix Would Join...,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,مختلط,ضمن النطاق المتوسط,تم التحديث
3,أصل عالمي,FTSE 100 - بريطانيا,^FTSE,10650.330078,0.987483,2026-10-12,NaN,NaN,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,مختلط,ضمن النطاق المتوسط,تم التحديث
4,سهم أمريكي,إنفيديا,NVDA,NaN,0.972074,2026-10-13,47.0,Wall Street stocks end tad lower after hot inf...,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,مختلط,ضمن النطاق المتوسط,تم التحديث
5,أصل عالمي,النفط الأمريكي,CL=F,94.809998,0.896100,2026-10-13,NaN,NaN,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,مختلط,ضمن النطاق المتوسط,تم التحديث
6,سهم أمريكي,مايكروسوفت,MSFT,NaN,0.425019,2026-10-13,35.0,Zacks Investment Ideas feature highlights: App...,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,صاعد,تشبع شرائي,تم التحديث
7,أصل عالمي,Dow Jones - أمريكا,^DJI,51670.101562,0.378670,2026-10-12,NaN,NaN,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,مختلط,ضمن النطاق المتوسط,تم التحديث
8,سهم أمريكي,آبل,AAPL,NaN,0.087981,2026-10-13,1.0,"Are Amazon, Apple stocks overpriced? Here are ...",4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,مختلط,ضمن النطاق المتوسط,تم التحديث
9,سهم أمريكي,ستاندرد آند بورز 500,SPY,NaN,-0.011562,2026-10-13,50.0,"Dow Drops 180, Nasdaq Falls 42, S&P 500 Slips ...",4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,صاعد,ضمن النطاق المتوسط,تم التحديث
10,أصل عالمي,Nikkei 225 - اليابان,^N225,69030.921875,-0.016204,2026-10-09,NaN,NaN,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,صاعد,ضمن النطاق المتوسط,تم التحديث
11,أصل عالمي,S&P 500 - أمريكا,^GSPC,7805.450195,-0.055044,2026-10-12,NaN,NaN,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,صاعد,ضمن النطاق المتوسط,تم التحديث
12,أصل عالمي,الدولار مقابل الين,JPY=X,158.320999,-0.116077,2026-10-14,NaN,NaN,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,مختلط,ضمن النطاق المتوسط,تم التحديث
13,سهم أمريكي,أمازون,AMZN,NaN,-0.366051,2026-10-13,17.0,Zacks Investment Ideas feature highlights: App...,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,مختلط,ضمن النطاق المتوسط,تم التحديث
14,سهم أمريكي,تسلا,TSLA,NaN,-0.740679,2026-10-13,20.0,Zacks Investment Ideas feature highlights: App...,4,اتجاه فني إيجابي نسبيًا,متابعة مرتفعة,صاعد,ضمن النطاق المتوسط,تم التحديث
15,أصل عالمي,بيتكوين,BTC-USD,83349.679688,1.697885,2026-10-13,NaN,NaN,3,اتجاه فني مختلط,متابعة متوسطة,مختلط,ضمن النطاق المتوسط,تم التحديث
16,أصل عالمي,Nasdaq Composite - أمريكا,^IXIC,27204.380859,-0.152388,2026-10-13,NaN,NaN,3,اتجاه فني مختلط,متابعة متوسطة,مختلط,ضمن النطاق المتوسط,تم التحديث
17,سهم أمريكي,ناسداك 100,QQQ,NaN,-0.331078,2026-10-13,4.0,"Stock Market Today: Dow Jones, S&P 500 Futures...",3,اتجاه فني مختلط,متابعة متوسطة,مختلط,ضمن النطاق المتوسط,تم التحديث
18,أصل عالمي,نفط برنت,BZ=F,106.370003,-0.459445,2026-10-13,NaN,NaN,3,اتجاه فني مختلط,متابعة متوسطة,مختلط,ضمن النطاق المتوسط,تم التحديث
19,أصل عالمي,إيثيريوم,ETH-USD,2507.969971,2.096775,2026-10-13,NaN,NaN,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية,مختلط,ضمن النطاق المتوسط,تم التحديث
20,أصل عالمي,DAX - ألمانيا,^GDAXI,25259.900391,0.758991,2026-10-12,NaN,NaN,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية,هابط,ضمن النطاق المتوسط,تم التحديث
21,أصل عالمي,CAC 40 - فرنسا,^FCHI,7827.629883,0.378682,2026-10-12,NaN,NaN,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية,هابط,ضمن النطاق المتوسط,تم التحديث
22,أصل عالمي,اليورو مقابل الدولار,EURUSD=X,1.120072,0.362908,2026-10-14,NaN,NaN,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية,هابط,تشبع بيعي,تم التحديث
23,أصل عالمي,Hang Seng - هونغ كونغ,^HSI,24271.199219,0.247197,2026-10-12,NaN,NaN,1,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية,هابط,ضمن النطاق المتوسط,تم التحديث
24,أصل عالمي,الذهب,GC=F,4183.000000,-0.233864,2026-10-13,NaN,NaN,0,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية,هابط,ضمن النطاق المتوسط,تم التحديث
25,أصل عالمي,الفضة,SI=F,59.369999,-1.348493,2026-10-13,NaN,NaN,0,إشارات فنية ضعيفة نسبيًا,مراجعة إضافية,هابط,ضمن النطاق المتوسط,تم التحديث

📊 ملخص التقييم الفني:

              التقييم الفني  عدد الأصول
0  إشارات فنية ضعيفة نسبيًا           7
1   اتجاه فني إيجابي نسبيًا          15
2           اتجاه فني مختلط           4

✅ المرحلة 44 اكتملت.
🔒 الجداول السابقة لم يتم تعديلها.

In [ ]:
# =========================================================
# 🌧️ الودق AI — المرحلة 45
# فحص جودة الأسعار والبيانات الناقصة
# الحفاظ على جميع الجداول السابقة
# =========================================================

import pandas as pd
import numpy as np

print("🌧️ الودق AI — المرحلة 45")
print("=" * 60)

# 1. تحديد مصدر البيانات
if "wadq_stage44_decision_df" not in globals():
    raise NameError(
        "لم يتم العثور على لوحة المرحلة 44. "
        "تأكدي من تشغيل المرحلة 44 أولًا."
    )

source_df = wadq_stage44_decision_df.copy()

# 2. إنشاء تقرير مستقل لفحص الأسعار
price_check_df = source_df.copy()

# 3. فحص السعر الأحدث
if "أحدث سعر متاح" in price_check_df.columns:
    price_check_df["حالة فحص السعر"] = np.where(
        pd.to_numeric(
            price_check_df["أحدث سعر متاح"],
            errors="coerce"
        ).isna(),
        "سعر مفقود",
        np.where(
            pd.to_numeric(
                price_check_df["أحدث سعر متاح"],
                errors="coerce"
            ) <= 0,
            "سعر غير صالح",
            "السعر موجود مبدئيًا"
        )
    )
else:
    price_check_df["حالة فحص السعر"] = "عمود السعر غير موجود"

# 4. فحص تاريخ آخر البيانات
if "تاريخ آخر بيانات" in price_check_df.columns:
    dates = pd.to_datetime(
        price_check_df["تاريخ آخر بيانات"],
        errors="coerce",
        utc=True
    )

    today_utc = pd.Timestamp.now(tz="UTC").normalize()

    price_check_df["عمر البيانات بالأيام"] = (
        today_utc - dates.dt.normalize()
    ).dt.days

    price_check_df["حالة حداثة البيانات"] = np.select(
        [
            dates.isna(),
            price_check_df["عمر البيانات بالأيام"] < 0,
            price_check_df["عمر البيانات بالأيام"] <= 3,
            price_check_df["عمر البيانات بالأيام"] <= 7
        ],
        [
            "تاريخ مفقود أو غير صالح",
            "تاريخ مستقبلي يحتاج تحققًا",
            "حديثة مبدئيًا",
            "تحتاج مراجعة الحداثة"
        ],
        default="بيانات قديمة تحتاج مراجعة"
    )
else:
    price_check_df["عمر البيانات بالأيام"] = np.nan
    price_check_df["حالة حداثة البيانات"] = "عمود التاريخ غير موجود"

# 5. فحص المؤشرات الفنية المتاحة
indicator_columns = [
    "المتوسط 20",
    "المتوسط 50",
    "RSI",
    "MACD",
    "إشارة MACD"
]

existing_indicators = [
    col for col in indicator_columns
    if col in price_check_df.columns
]

if existing_indicators:
    price_check_df["عدد المؤشرات المفقودة"] = (
        price_check_df[existing_indicators]
        .apply(pd.to_numeric, errors="coerce")
        .isna()
        .sum(axis=1)
    )
else:
    price_check_df["عدد المؤشرات المفقودة"] = np.nan

# 6. ملخص النتائج
print(f"📊 إجمالي الأصول المفحوصة: {len(price_check_df)}")

print("\n📌 حالة الأسعار:")
display(
    price_check_df["حالة فحص السعر"]
    .value_counts(dropna=False)
    .rename_axis("حالة فحص السعر")
    .reset_index(name="عدد الأصول")
)

print("\n📌 حداثة البيانات:")
display(
    price_check_df["حالة حداثة البيانات"]
    .value_counts(dropna=False)
    .rename_axis("حالة حداثة البيانات")
    .reset_index(name="عدد الأصول")
)

print("\n📌 الأصول التي تحتاج إلى مراجعة:")
review_columns = [
    col for col in [
        "نوع الأصل",
        "الأصل",
        "الرمز",
        "أحدث سعر متاح",
        "التغير اليومي %",
        "تاريخ آخر بيانات",
        "حالة فحص السعر",
        "عمر البيانات بالأيام",
        "حالة حداثة البيانات",
        "عدد المؤشرات المفقودة"
    ]
    if col in price_check_df.columns
]

review_df = price_check_df[
    (price_check_df["حالة فحص السعر"] != "السعر موجود مبدئيًا")
    | (
        price_check_df["حالة حداثة البيانات"]
        .astype(str)
        .str.contains("مراجعة|قديم|مفقود|مستقبلي", regex=True)
    )
].copy()

display(review_df[review_columns])

# 7. حفظ النتائج في جداول جديدة فقط
wadq_stage45_price_check_df = price_check_df.copy()
wadq_stage45_review_df = review_df.copy()

print("\n" + "=" * 60)
print("✅ انتهى فحص المرحلة 45.")
print(f"📊 عدد الأصول: {len(wadq_stage45_price_check_df)}")
print(f"🔎 عدد الأصول التي تحتاج مراجعة: {len(wadq_stage45_review_df)}")
print("🔒 لم يتم تعديل أو حذف أي جدول سابق.")
print("ℹ️ هذه المرحلة تفحص البيانات ولا تستبدل الأسعار المفقودة بقيم تقديرية.")

🌧️ الودق AI — المرحلة 45
============================================================
📊 إجمالي الأصول المفحوصة: 26

📌 حالة الأسعار:

        حالة فحص السعر  عدد الأصول
0  السعر موجود مبدئيًا          17
1            سعر مفقود           9

📌 حداثة البيانات:

          حالة حداثة البيانات  عدد الأصول
0               حديثة مبدئيًا          23
1  تاريخ مستقبلي يحتاج تحققًا           2
2        تحتاج مراجعة الحداثة           1

📌 الأصول التي تحتاج إلى مراجعة:

,نوع الأصل,الأصل,الرمز,أحدث سعر متاح,التغير اليومي %,تاريخ آخر بيانات,حالة فحص السعر,عمر البيانات بالأيام,حالة حداثة البيانات,عدد المؤشرات المفقودة
1,سهم أمريكي,ألفابت,GOOGL,NaN,0.300521,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
2,سهم أمريكي,ميتا,META,NaN,2.630017,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
4,سهم أمريكي,إنفيديا,NVDA,NaN,0.972074,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
6,سهم أمريكي,مايكروسوفت,MSFT,NaN,0.425019,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
8,سهم أمريكي,آبل,AAPL,NaN,0.087981,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
9,سهم أمريكي,ستاندرد آند بورز 500,SPY,NaN,-0.011562,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
10,أصل عالمي,Nikkei 225 - اليابان,^N225,69030.921875,-0.016204,2026-10-09,السعر موجود مبدئيًا,4,تحتاج مراجعة الحداثة,NaN
12,أصل عالمي,الدولار مقابل الين,JPY=X,158.320999,-0.116077,2026-10-14,السعر موجود مبدئيًا,-1,تاريخ مستقبلي يحتاج تحققًا,NaN
13,سهم أمريكي,أمازون,AMZN,NaN,-0.366051,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
14,سهم أمريكي,تسلا,TSLA,NaN,-0.740679,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
17,سهم أمريكي,ناسداك 100,QQQ,NaN,-0.331078,2026-10-13,سعر مفقود,0,حديثة مبدئيًا,NaN
22,أصل عالمي,اليورو مقابل الدولار,EURUSD=X,1.120072,0.362908,2026-10-14,السعر موجود مبدئيًا,-1,تاريخ مستقبلي يحتاج تحققًا,NaN

============================================================
✅ انتهى فحص المرحلة 45.
📊 عدد الأصول: 26
🔎 عدد الأصول التي تحتاج مراجعة: 12
🔒 لم يتم تعديل أو حذف أي جدول سابق.
ℹ️ هذه المرحلة تفحص البيانات ولا تستبدل الأسعار المفقودة بقيم تقديرية.

In [ ]:
# =========================================================
# 🌧️ الودق AI — المرحلة 46
# إعادة جلب الأسعار والتحقق من حداثة البيانات
# =========================================================

import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timezone

print("🌧️ الودق AI — المرحلة 46")
print("=" * 60)

# مصدر مستقل حتى لا نغيّر الجداول السابقة
if "wadq_stage45_price_check_df" not in globals():
    raise NameError(
        "جدول المرحلة 45 غير موجود. "
        "شغّلي المرحلة 45 أولًا."
    )

source_df = wadq_stage45_price_check_df.copy()

# الرموز الموجودة فعلًا في الجدول
symbol_col = "الرمز" if "الرمز" in source_df.columns else "ticker"

if symbol_col not in source_df.columns:
    raise KeyError("لم يتم العثور على عمود الرموز.")

# الاحتفاظ بالبيانات الأصلية وإضافة أعمدة الفحص الجديدة
results = []

print("⏳ جارٍ فحص الأسعار من Yahoo Finance...")
print("قد يستغرق ذلك بعض الوقت.\n")

for _, row in source_df.iterrows():
    symbol = str(row.get(symbol_col, "")).strip()

    result = row.to_dict()
    result["سعر التحديث"] = np.nan
    result["تاريخ التحديث"] = None
    result["حالة التحديث"] = "لم يبدأ"

    if not symbol or symbol.lower() == "nan":
        result["حالة التحديث"] = "رمز مفقود"
        results.append(result)
        continue

    try:
        data = yf.download(
            symbol,
            period="10d",
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )

        if data is None or data.empty:
            result["حالة التحديث"] = "لم تصل بيانات من المصدر"
        else:
            close = data["Close"]

            # التعامل مع اختلاف شكل الأعمدة في إصدارات yfinance
            if isinstance(close, pd.DataFrame):
                close = close.iloc[:, 0]

            close = pd.to_numeric(close, errors="coerce").dropna()

            if close.empty:
                result["حالة التحديث"] = "السعر غير متاح"
            else:
                latest_price = float(close.iloc[-1])
                latest_date = pd.Timestamp(close.index[-1])

                if latest_date.tzinfo is not None:
                    latest_date = latest_date.tz_localize(None)

                result["سعر التحديث"] = latest_price
                result["تاريخ التحديث"] = latest_date.strftime("%Y-%m-%d")

                # التحقق من السعر والتاريخ
                now_utc = datetime.now(timezone.utc)
                latest_date_utc = latest_date.tz_localize("UTC")

                if latest_price <= 0:
                    result["حالة التحديث"] = "سعر غير صالح"
                elif latest_date_utc > now_utc:
                    result["حالة التحديث"] = "تاريخ يحتاج تحققًا"
                else:
                    result["حالة التحديث"] = "تم جلب السعر"

    except Exception as e:
        result["حالة التحديث"] = (
            "تعذر التحديث: " + str(e)[:120]
        )

    results.append(result)

# حفظ النتيجة في جدول جديد فقط
wadq_stage46_price_update_df = pd.DataFrame(results)

# ملخص حالات التحديث
print("📊 ملخص نتائج التحديث:")
display(
    wadq_stage46_price_update_df["حالة التحديث"]
    .value_counts(dropna=False)
    .rename_axis("حالة التحديث")
    .reset_index(name="عدد الأصول")
)

# عرض نتائج الأسعار الجديدة
display_columns = [
    col for col in [
        "الأصل",
        symbol_col,
        "أحدث سعر متاح",
        "سعر التحديث",
        "تاريخ التحديث",
        "تاريخ آخر بيانات",
        "حالة التحديث"
    ]
    if col in wadq_stage46_price_update_df.columns
]

print("\n📋 تفاصيل تحديث الأسعار:")
display(wadq_stage46_price_update_df[display_columns])

print("\n" + "=" * 60)
print("✅ انتهت محاولة تحديث المرحلة 46.")
print("🔒 الجداول السابقة محفوظة دون تعديل.")
print("ℹ️ لم نستبدل الأسعار الأصلية؛ أضفنا نتائج التحديث في أعمدة مستقلة.")

🌧️ الودق AI — المرحلة 46
============================================================
⏳ جارٍ فحص الأسعار من Yahoo Finance...
قد يستغرق ذلك بعض الوقت.

📊 ملخص نتائج التحديث:

         حالة التحديث  عدد الأصول
0        تم جلب السعر          24
1  تاريخ يحتاج تحققًا           2

📋 تفاصيل تحديث الأسعار:

,الأصل,الرمز,أحدث سعر متاح,سعر التحديث,تاريخ التحديث,تاريخ آخر بيانات,حالة التحديث
0,الغاز الطبيعي,NG=F,3.322000,3.317000,2026-10-13,2026-10-13,تم جلب السعر
1,ألفابت,GOOGL,NaN,353.779999,2026-10-13,2026-10-13,تم جلب السعر
2,ميتا,META,NaN,762.500000,2026-10-13,2026-10-13,تم جلب السعر
3,FTSE 100 - بريطانيا,^FTSE,10650.330078,10656.299805,2026-10-12,2026-10-12,تم جلب السعر
4,إنفيديا,NVDA,NaN,228.520004,2026-10-13,2026-10-13,تم جلب السعر
5,النفط الأمريكي,CL=F,94.809998,94.660004,2026-10-13,2026-10-13,تم جلب السعر
6,مايكروسوفت,MSFT,NaN,543.450012,2026-10-13,2026-10-13,تم جلب السعر
7,Dow Jones - أمريكا,^DJI,51670.101562,51850.550781,2026-10-12,2026-10-12,تم جلب السعر
8,آبل,AAPL,NaN,341.269989,2026-10-13,2026-10-13,تم جلب السعر
9,ستاندرد آند بورز 500,SPY,NaN,778.010010,2026-10-13,2026-10-13,تم جلب السعر
10,Nikkei 225 - اليابان,^N225,69030.921875,69030.921875,2026-10-09,2026-10-09,تم جلب السعر
11,S&P 500 - أمريكا,^GSPC,7805.450195,7807.240234,2026-10-12,2026-10-12,تم جلب السعر
12,الدولار مقابل الين,JPY=X,158.320999,158.347000,2026-10-14,2026-10-14,تاريخ يحتاج تحققًا
13,أمازون,AMZN,NaN,258.579987,2026-10-13,2026-10-13,تم جلب السعر
14,تسلا,TSLA,NaN,375.230011,2026-10-13,2026-10-13,تم جلب السعر
15,بيتكوين,BTC-USD,83349.679688,83127.039062,2026-10-13,2026-10-13,تم جلب السعر
16,Nasdaq Composite - أمريكا,^IXIC,27204.380859,27204.380859,2026-10-13,2026-10-13,تم جلب السعر
17,ناسداك 100,QQQ,NaN,743.570007,2026-10-13,2026-10-13,تم جلب السعر
18,نفط برنت,BZ=F,106.370003,106.209999,2026-10-13,2026-10-13,تم جلب السعر
19,إيثيريوم,ETH-USD,2507.969971,2496.979980,2026-10-13,2026-10-13,تم جلب السعر
20,DAX - ألمانيا,^GDAXI,25259.900391,25277.679688,2026-10-12,2026-10-12,تم جلب السعر
21,CAC 40 - فرنسا,^FCHI,7827.629883,7832.879883,2026-10-12,2026-10-12,تم جلب السعر
22,اليورو مقابل الدولار,EURUSD=X,1.120072,1.120197,2026-10-14,2026-10-14,تاريخ يحتاج تحققًا
23,Hang Seng - هونغ كونغ,^HSI,24271.199219,24271.199219,2026-10-12,2026-10-12,تم جلب السعر
24,الذهب,GC=F,4183.000000,4178.799805,2026-10-13,2026-10-13,تم جلب السعر
25,الفضة,SI=F,59.369999,59.169998,2026-10-13,2026-10-13,تم جلب السعر

============================================================
✅ انتهت محاولة تحديث المرحلة 46.
🔒 الجداول السابقة محفوظة دون تعديل.
ℹ️ لم نستبدل الأسعار الأصلية؛ أضفنا نتائج التحديث في أعمدة مستقلة.

In [ ]:
# 🌧️ الودق AI — المرحلة 47
# فحص جودة الأسعار والتواريخ
import pandas as pd
from IPython.display import display
print("🌧️ الودق AI — المرحلة 47")
print("=" * 55)
# قراءة جدول المرحلة 46 دون تعديله
source_df = wadq_stage46_price_update_df.copy()
# إنشاء نسخة مستقلة للفحص
wadq_phase47_df = source_df.copy()
print("✅ تم العثور على جدول المرحلة 46.")
print(f"📊 إجمالي الأصول: {len(wadq_phase47_df)}")
print(f"📋 إجمالي الأعمدة الأصلية: {len(source_df.columns)}")
print("\n🔎 أعمدة جدول المصدر:")
print(source_df.columns.tolist())
# تحديد عمود السعر
price_col = "سعر التحديث"
if price_col in wadq_phase47_df.columns:
    prices = pd.to_numeric(
        wadq_phase47_df[price_col],
        errors="coerce"
    )
    wadq_phase47_df["نتيجة فحص السعر"] = prices.apply(
        lambda x: (
            "سعر صالح مبدئيًا"
            if pd.notna(x) and x > 0
            else "سعر مفقود أو غير صالح"
        )
    )
else:
    wadq_phase47_df["نتيجة فحص السعر"] = (
        "تعذر الفحص: عمود السعر غير موجود"
    )
# فحص تاريخ آخر البيانات
date_col = "تاريخ آخر بيانات"
if date_col in wadq_phase47_df.columns:
    dates = pd.to_datetime(
        wadq_phase47_df[date_col],
        errors="coerce"
    )
    today = pd.Timestamp.now().normalize()
    wadq_phase47_df["نتيجة فحص التاريخ"] = dates.apply(
        lambda x: (
            "تاريخ غير معروف"
            if pd.isna(x)
            else "تاريخ مستقبلي يحتاج تحققًا"
            if x.normalize() > today
            else "تاريخ متاح"
        )
    )
else:
    wadq_phase47_df["نتيجة فحص التاريخ"] = (
        "تعذر الفحص: عمود التاريخ غير موجود"
    )
# عرض ملخص الأسعار
print("\n📊 ملخص جودة الأسعار:")
display(
    wadq_phase47_df["نتيجة فحص السعر"]
    .value_counts()
    .rename_axis("حالة السعر")
    .reset_index(name="عدد الأصول")
)
# عرض ملخص التواريخ
print("\n📅 ملخص جودة التواريخ:")
display(
    wadq_phase47_df["نتيجة فحص التاريخ"]
    .value_counts()
    .rename_axis("حالة التاريخ")
    .reset_index(name="عدد الأصول")
)
# عرض الأصول التي تحتاج إلى مراجعة
print("\n⚠️ الأصول التي تحتاج إلى مراجعة:")
review_df = wadq_phase47_df[
    (wadq_phase47_df["نتيجة فحص السعر"] != "سعر صالح مبدئيًا")
    | (
        wadq_phase47_df["نتيجة فحص التاريخ"]
        != "تاريخ متاح"
    )
].copy()
display(review_df)
print("\n" + "=" * 55)
print("✅ اكتملت المرحلة 47.")
print("🔒 الجداول الأصلية لم تتغير.")
print("📌 جدول الفحص الجديد: wadq_phase47_df")
print(f"📊 عدد الأصول التي تحتاج إلى مراجعة: {len(review_df)}")

🌧️ الودق AI — المرحلة 47
=======================================================
✅ تم العثور على جدول المرحلة 46.
📊 إجمالي الأصول: 26
📋 إجمالي الأعمدة الأصلية: 21

🔎 أعمدة جدول المصدر:
['نوع الأصل', 'الأصل', 'الرمز', 'أحدث سعر متاح', 'التغير اليومي %', 'تاريخ آخر بيانات', 'عدد_الأخبار', 'ملخص_الأخبار', 'النقاط الفنية', 'التقييم الفني', 'أولوية المتابعة', 'الاتجاه', 'حالة RSI', 'حالة البيانات', 'حالة فحص السعر', 'عمر البيانات بالأيام', 'حالة حداثة البيانات', 'عدد المؤشرات المفقودة', 'سعر التحديث', 'تاريخ التحديث', 'حالة التحديث']

📊 ملخص جودة الأسعار:

         حالة السعر  عدد الأصول
0  سعر صالح مبدئيًا          26

📅 ملخص جودة التواريخ:

                 حالة التاريخ  عدد الأصول
0                  تاريخ متاح          24
1  تاريخ مستقبلي يحتاج تحققًا           2

⚠️ الأصول التي تحتاج إلى مراجعة:

,نوع الأصل,الأصل,الرمز,أحدث سعر متاح,التغير اليومي %,تاريخ آخر بيانات,عدد_الأخبار,ملخص_الأخبار,النقاط الفنية,التقييم الفني,...,حالة البيانات,حالة فحص السعر,عمر البيانات بالأيام,حالة حداثة البيانات,عدد المؤشرات المفقودة,سعر التحديث,تاريخ التحديث,حالة التحديث,نتيجة فحص السعر,نتيجة فحص التاريخ
12,أصل عالمي,الدولار مقابل الين,JPY=X,158.320999,-0.116077,2026-10-14,NaN,NaN,4,اتجاه فني إيجابي نسبيًا,...,تم التحديث,السعر موجود مبدئيًا,-1,تاريخ مستقبلي يحتاج تحققًا,NaN,158.347000,2026-10-14,تاريخ يحتاج تحققًا,سعر صالح مبدئيًا,تاريخ مستقبلي يحتاج تحققًا
22,أصل عالمي,اليورو مقابل الدولار,EURUSD=X,1.120072,0.362908,2026-10-14,NaN,NaN,1,إشارات فنية ضعيفة نسبيًا,...,تم التحديث,السعر موجود مبدئيًا,-1,تاريخ مستقبلي يحتاج تحققًا,NaN,1.120197,2026-10-14,تاريخ يحتاج تحققًا,سعر صالح مبدئيًا,تاريخ مستقبلي يحتاج تحققًا

=======================================================
✅ اكتملت المرحلة 47.
🔒 الجداول الأصلية لم تتغير.
📌 جدول الفحص الجديد: wadq_phase47_df
📊 عدد الأصول التي تحتاج إلى مراجعة: 2

In [ ]:
# 🌧️ الودق AI — المرحلة 48
# مراجعة التواريخ المستقبلية وتصحيح حساب عمر البيانات
# مع المحافظة على الجداول الأصلية دون تغيير
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo
print("🌧️ الودق AI — المرحلة 48")
print("=" * 65)
# 1) التأكد من وجود جدول المرحلة 47
if 'wadq_phase47_df' not in globals():
    raise NameError(
        "لم يُعثر على wadq_phase47_df. "
        "تأكدي من نجاح المرحلة 47 قبل المتابعة."
    )
# 2) إنشاء نسخة مستقلة للعمل
wadq_phase48_df = wadq_phase47_df.copy(deep=True)
# 3) تحديد التاريخ الحالي في السعودية
today_sa = pd.Timestamp(
    datetime.now(ZoneInfo("Asia/Riyadh")).date()
)
# 4) تحويل التواريخ إلى صيغة موحدة داخل النسخة الجديدة
date_col = 'تاريخ آخر بيانات'
if date_col not in wadq_phase48_df.columns:
    raise KeyError(f"العمود المطلوب غير موجود: {date_col}")
wadq_phase48_df['_تاريخ_الفحص'] = pd.to_datetime(
    wadq_phase48_df[date_col],
    errors='coerce'
).dt.tz_localize(None).dt.normalize()
# 5) حساب عمر البيانات من تاريخ اليوم
wadq_phase48_df['عمر البيانات بالأيام'] = (
    today_sa - wadq_phase48_df['_تاريخ_الفحص']
).dt.days
# 6) تصنيف التواريخ دون تغيير التاريخ الأصلي
def classify_date(row):
    date_value = row['_تاريخ_الفحص']
    if pd.isna(date_value):
        return 'تاريخ مفقود أو غير صالح'
    elif date_value > today_sa:
        return 'تاريخ مستقبلي يحتاج تحققًا'
    elif date_value == today_sa:
        return 'بيانات بتاريخ اليوم'
    else:
        return 'تاريخ سابق يحتاج تقييم الحداثة'
wadq_phase48_df['نتيجة مراجعة التاريخ'] = (
    wadq_phase48_df.apply(classify_date, axis=1)
)
# 7) عرض الأصول التي تحتاج إلى مراجعة
review_mask = wadq_phase48_df['نتيجة مراجعة التاريخ'].isin([
    'تاريخ مستقبلي يحتاج تحققًا',
    'تاريخ مفقود أو غير صالح'
])
review_columns = [
    col for col in [
        'نوع الأصل',
        'الأصل',
        'الرمز',
        'تاريخ آخر بيانات',
        'عمر البيانات بالأيام',
        'نتيجة مراجعة التاريخ'
    ]
    if col in wadq_phase48_df.columns
]
wadq_phase48_review_df = (
    wadq_phase48_df.loc[review_mask, review_columns]
    .copy()
)
# 8) حذف عمود الفحص الداخلي من الجدول النهائي
wadq_phase48_df.drop(
    columns=['_تاريخ_الفحص'],
    inplace=True
)
# 9) عرض النتائج
print(f"📊 إجمالي الأصول: {len(wadq_phase48_df)}")
print(f"📋 إجمالي الأعمدة: {len(wadq_phase48_df.columns)}")
print(f"📅 تاريخ الفحص في السعودية: {today_sa.date()}")
print()
print("📊 ملخص مراجعة التواريخ:")
display(
    wadq_phase48_df['نتيجة مراجعة التاريخ']
    .value_counts(dropna=False)
    .rename_axis('حالة التاريخ')
    .reset_index(name='عدد الأصول')
)
print()
print("🔎 الأصول التي تحتاج إلى مراجعة:")
if wadq_phase48_review_df.empty:
    print("✅ لا توجد تواريخ مستقبلية أو مفقودة تحتاج إلى مراجعة.")
else:
    display(wadq_phase48_review_df)
print()
print("✅ اكتملت المرحلة 48.")
print("📌 الجدول الجديد: wadq_phase48_df")
print("📌 جدول المراجعة: wadq_phase48_review_df")
print("🔒 لم يتم تعديل الجداول الأصلية.")
print("⚠️ لم يتم تغيير التواريخ الأصلية أو افتراض صحتها.")

🌧️ الودق AI — المرحلة 48
=================================================================
📊 إجمالي الأصول: 26
📋 إجمالي الأعمدة: 24
📅 تاريخ الفحص في السعودية: 2026-10-14

📊 ملخص مراجعة التواريخ:

                     حالة التاريخ  عدد الأصول
0  تاريخ سابق يحتاج تقييم الحداثة          24
1             بيانات بتاريخ اليوم           2

🔎 الأصول التي تحتاج إلى مراجعة:
✅ لا توجد تواريخ مستقبلية أو مفقودة تحتاج إلى مراجعة.

✅ اكتملت المرحلة 48.
📌 الجدول الجديد: wadq_phase48_df
📌 جدول المراجعة: wadq_phase48_review_df
🔒 لم يتم تعديل الجداول الأصلية.
⚠️ لم يتم تغيير التواريخ الأصلية أو افتراض صحتها.

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة الثالثة: دمج الأخبار مع التحليل الفني للأسهم
# خلية جديدة - دون حذف أو تعديل الأكواد السابقة
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ بدء دمج الأخبار مع التحليل الفني")
print("=" * 55)

# 1. التحقق من وجود بيانات التحليل الفني
if "us_technical_df" not in globals():
    print("لم يتم العثور على us_technical_df.")
    print("شغّلي خلية التحليل الفني الأمريكي أولاً.")

elif "wadq_ticker_news_df" not in globals():
    print("لم يتم العثور على جدول أخبار الأسهم.")
    print("شغّلي خلية تحليل الأخبار أولاً.")

else:
    # نسخ البيانات للحفاظ على الجداول الأصلية
    wadq_technical_copy = us_technical_df.copy()
    wadq_news_copy = wadq_ticker_news_df.copy()

    print("\nأعمدة التحليل الفني:")
    print(wadq_technical_copy.columns.tolist())

    # 2. التعرف على عمود رمز السهم
    possible_ticker_columns = [
    "ticker", "symbol", "Ticker", "Symbol",
    "stock", "Stock", "رمز السهم", "الرمز"
]

    ticker_column = next(
        (
            col for col in possible_ticker_columns
            if col in wadq_technical_copy.columns
        ),
        None
    )

    # إذا كان رمز السهم محفوظًا في الفهرس
    if ticker_column is None:
        index_name = wadq_technical_copy.index.name

        if index_name in possible_ticker_columns:
            wadq_technical_copy = (
                wadq_technical_copy.reset_index()
            )
            ticker_column = index_name

    if ticker_column is None:
        print("\nلم أتعرف تلقائيًا على عمود رموز الأسهم.")
        print("أرسلي لي أسماء الأعمدة التي ظهرت أعلاه.")
    else:
        # 3. توحيد رموز الأسهم
        wadq_technical_copy[ticker_column] = (
            wadq_technical_copy[ticker_column]
            .astype(str)
            .str.upper()
            .str.strip()
        )

        wadq_news_copy["ticker"] = (
            wadq_news_copy["ticker"]
            .astype(str)
            .str.upper()
            .str.strip()
        )

        # 4. تلخيص الأخبار لكل سهم
        if wadq_news_copy.empty:
            wadq_news_summary = pd.DataFrame(
                columns=[
                    "ticker",
                    "news_count",
                    "positive_news",
                    "negative_news",
                    "neutral_news"
                ]
            )
        else:
            wadq_news_summary = (
                wadq_news_copy.assign(
                    positive_news=lambda d:
                        d["sentiment"].eq("إيجابي مبدئي").astype(int),
                    negative_news=lambda d:
                        d["sentiment"].eq("سلبي مبدئي").astype(int),
                    neutral_news=lambda d:
                        d["sentiment"].eq("محايد أو غير واضح").astype(int)
                )
                .groupby("ticker", as_index=False)
                .agg(
                    news_count=("news_title", "count"),
                    positive_news=("positive_news", "sum"),
                    negative_news=("negative_news", "sum"),
                    neutral_news=("neutral_news", "sum")
                )
            )

        # 5. دمج الأخبار مع نسخة من التحليل الفني
        wadq_integrated_df = wadq_technical_copy.merge(
            wadq_news_summary,
            left_on=ticker_column,
            right_on="ticker",
            how="left"
        )

        # ملء الفراغات لمن لم نجد لهم أخبارًا
        news_count_columns = [
            "news_count",
            "positive_news",
            "negative_news",
            "neutral_news"
        ]

        for col in news_count_columns:
            if col in wadq_integrated_df.columns:
                wadq_integrated_df[col] = (
                    wadq_integrated_df[col]
                    .fillna(0)
                    .astype(int)
                )

        # 6. عرض التقرير الموحد
        print("\n✅ تم إنشاء التقرير الموحد")
        print("عدد صفوف التحليل الفني:",
              len(wadq_integrated_df))
        print("\nالأخبار المرتبطة بالأسهم:")

        display(wadq_integrated_df)

        # حفظ التقرير في متغير مستقل
        print("\n🌧️ اسم التقرير:")
        print("wadq_integrated_df")

🌧️ بدء دمج الأخبار مع التحليل الفني
=======================================================

أعمدة التحليل الفني:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

✅ تم إنشاء التقرير الموحد
عدد صفوف التحليل الفني: 9

الأخبار المرتبطة بالأسهم:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,news_count,positive_news,negative_news,neutral_news
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,NVDA,47,10,1,36
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,TSLA,20,2,0,18
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد,AAPL,1,0,0,1
3,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,MSFT,35,8,1,26
4,أمازون,AMZN,258.58,252.83,258.35,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط,AMZN,17,4,0,13
5,ألفابت,GOOGL,353.78,346.53,345.69,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد,GOOGL,22,6,0,16
6,ميتا,META,762.50,727.58,646.59,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد,META,2,1,0,1
7,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد,QQQ,4,1,0,3
8,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد,SPY,50,11,11,28

🌧️ اسم التقرير:
wadq_integrated_df

In [ ]:
# 🌧️ الودق AI - فحص جداول التحليل الموجودة
print("فحص جداول التحليل الفني")
print("=" * 40)

for name in ["technical_df", "us_technical_df"]:
    if name in globals():
        df = globals()[name]
        print(f"\n{name}: موجود")
        print("عدد الصفوف:", len(df))
        print("الأعمدة:", list(df.columns))
        display(df.head(3))
    else:
        print(f"\n{name}: غير موجود في الذاكرة الحالية")

فحص جداول التحليل الفني
========================================

technical_df: غير موجود في الذاكرة الحالية

us_technical_df: موجود
عدد الصفوف: 9
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد

In [ ]:
# 🌧️ الودق AI — التحقق من جداول التقييم السابقة
print("🌧️ فحص جداول الودق AI")
print("=" * 50)
check_tables = [
    'wadq_integrated_df',
    'wadq_evaluation_df',
    'wadq_smart_report',
    'wadq_final_ai_report',
    'wadq_global_master_report_df',
    'wadq_phase47_df',
    'wadq_phase48_df'
]
for name in check_tables:
    if name in globals():
        obj = globals()[name]
        if hasattr(obj, 'shape'):
            print(f"✅ {name}: {obj.shape}")
        else:
            print(f"✅ {name}: موجود")
    else:
        print(f"➖ {name}: غير موجود")

🌧️ فحص جداول الودق AI
==================================================
✅ wadq_integrated_df: (9, 15)
➖ wadq_evaluation_df: غير موجود
➖ wadq_smart_report: غير موجود
➖ wadq_final_ai_report: غير موجود
✅ wadq_global_master_report_df: (17, 6)
✅ wadq_phase47_df: (26, 23)
✅ wadq_phase48_df: (26, 24)

In [ ]:
# 🌧️ الودق AI — استعادة الجداول الثلاثة
# استعادة من البيانات الموجودة في الذاكرة دون إعادة جلب الأسعار أو الأخبار
import pandas as pd
import numpy as np
print("🌧️ الودق AI — استعادة الجداول الثلاثة")
print("=" * 65)
# =========================================================
# 1) التحقق من مصدر التحليل الفني والأخبار
# =========================================================
if 'wadq_integrated_df' not in globals():
    raise NameError(
        "❌ الجدول wadq_integrated_df غير موجود. "
        "لا يمكن استعادة التقارير قبل استعادة مصدر التحليل الموحد."
    )
source_df = wadq_integrated_df.copy(deep=True)
print(f"✅ مصدر التحليل الموحد: {source_df.shape}")
# =========================================================
# 2) استعادة جدول التقييم wadq_evaluation_df
# =========================================================
wadq_evaluation_df = source_df.copy(deep=True)
# تقييم RSI
if 'RSI' in wadq_evaluation_df.columns:
    rsi = pd.to_numeric(
        wadq_evaluation_df['RSI'], errors='coerce'
    )
    wadq_evaluation_df['تقييم RSI'] = np.select(
        [
            rsi < 30,
            rsi >= 70,
            rsi.notna()
        ],
        [
            'تشبع بيعي محتمل',
            'تشبع شرائي محتمل',
            'ضمن النطاق المتوسط'
        ],
        default='بيانات RSI غير متاحة'
    )
else:
    wadq_evaluation_df['تقييم RSI'] = 'بيانات RSI غير متاحة'
# تقييم الأخبار
positive_col = 'positive_news'
negative_col = 'negative_news'
neutral_col = 'neutral_news'
if all(
    col in wadq_evaluation_df.columns
    for col in [positive_col, negative_col, neutral_col]
):
    positive = pd.to_numeric(
        wadq_evaluation_df[positive_col], errors='coerce'
    ).fillna(0)
    negative = pd.to_numeric(
        wadq_evaluation_df[negative_col], errors='coerce'
    ).fillna(0)
    neutral = pd.to_numeric(
        wadq_evaluation_df[neutral_col], errors='coerce'
    ).fillna(0)
    wadq_evaluation_df['تقييم الأخبار'] = np.select(
        [
            (positive > negative) & (positive > 0),
            (negative > positive) & (negative > 0),
            (positive == 0) & (negative == 0) & (neutral > 0)
        ],
        [
            'أخبار إيجابية نسبيًا',
            'أخبار سلبية نسبيًا',
            'أخبار محايدة'
        ],
        default='أخبار غير كافية للتقييم'
    )
else:
    wadq_evaluation_df['تقييم الأخبار'] = (
        'بيانات تصنيف الأخبار غير متاحة'
    )
# التقييم العام الأولي
def evaluate_asset(row):
    points = 0
    trend = str(row.get('الاتجاه', '')).strip()
    rsi_status = str(row.get('تقييم RSI', ''))
    news_status = str(row.get('تقييم الأخبار', ''))
    if trend == 'صاعد':
        points += 1
    elif trend == 'هابط':
        points -= 1
    if news_status == 'أخبار إيجابية نسبيًا':
        points += 1
    elif news_status == 'أخبار سلبية نسبيًا':
        points -= 1
    if rsi_status == 'تشبع شرائي محتمل':
        points -= 1
    if points >= 2:
        return 'إيجابي نسبيًا'
    elif points <= -1:
        return 'حذر ومخاطر أعلى'
    else:
        return 'مختلط أو يحتاج متابعة'
wadq_evaluation_df['تقييم الودق'] = (
    wadq_evaluation_df.apply(evaluate_asset, axis=1)
)
print("✅ تمت استعادة wadq_evaluation_df")
# =========================================================
# 3) استعادة التقرير الذكي wadq_smart_report
# =========================================================
wadq_smart_report = source_df.copy(deep=True)
# إضافة ملخص قابل للقراءة لكل أصل
def make_summary(row):
    ticker = row.get('الرمز', row.get('ticker', 'غير معروف'))
    trend = row.get('الاتجاه', 'غير متاح')
    news_count = row.get('news_count', np.nan)
    positive = row.get('positive_news', np.nan)
    negative = row.get('negative_news', np.nan)
    parts = [
        f"الأصل: {ticker}",
        f"الاتجاه الفني: {trend}"
    ]
    if pd.notna(news_count):
        parts.append(f"عدد الأخبار: {int(news_count)}")
    if pd.notna(positive) and pd.notna(negative):
        parts.append(
            f"الأخبار الإيجابية: {int(positive)}، "
            f"السلبية: {int(negative)}"
        )
    return " | ".join(parts)
wadq_smart_report['ملخص الودق الذكي'] = (
    wadq_smart_report.apply(make_summary, axis=1)
)
# إضافة تقييم الودق إلى التقرير الذكي بحسب الرمز
if 'الرمز' in wadq_smart_report.columns and 'الرمز' in wadq_evaluation_df.columns:
    evaluation_columns = [
        col for col in ['الرمز', 'تقييم RSI', 'تقييم الأخبار', 'تقييم الودق']
        if col in wadq_evaluation_df.columns
    ]
    evaluation_unique = (
        wadq_evaluation_df[evaluation_columns]
        .drop_duplicates(subset=['الرمز'])
    )
    wadq_smart_report = wadq_smart_report.merge(
        evaluation_unique,
        on='الرمز',
        how='left',
        suffixes=('', '_تقييم')
    )
print("✅ تمت استعادة wadq_smart_report")
# =========================================================
# 4) استعادة التقرير النهائي wadq_final_ai_report
# =========================================================
# نبني التقرير النهائي من التقرير الذكي والتقييم،
# مع المحافظة على صف واحد لكل أصل وفق بيانات المصدر.
wadq_final_ai_report = wadq_smart_report.copy(deep=True)
# إضافة حالة توفر البيانات
required_market_columns = [
    col for col in ['آخر إغلاق', 'الرمز']
    if col in wadq_final_ai_report.columns
]
if 'آخر إغلاق' in wadq_final_ai_report.columns:
    close_price = pd.to_numeric(
        wadq_final_ai_report['آخر إغلاق'], errors='coerce'
    )
    wadq_final_ai_report['حالة توفر السعر'] = np.where(
        close_price.notna() & (close_price > 0),
        'سعر متاح مبدئيًا',
        'سعر يحتاج إلى مراجعة'
    )
elif 'أحدث سعر متاح' in wadq_final_ai_report.columns:
    latest_price = pd.to_numeric(
        wadq_final_ai_report['أحدث سعر متاح'], errors='coerce'
    )
    wadq_final_ai_report['حالة توفر السعر'] = np.where(
        latest_price.notna() & (latest_price > 0),
        'سعر متاح مبدئيًا',
        'سعر يحتاج إلى مراجعة'
    )
else:
    wadq_final_ai_report['حالة توفر السعر'] = (
        'لم يتوفر عمود سعر في مصدر التقرير'
    )
print("✅ تمت استعادة wadq_final_ai_report")
# =========================================================
# 5) ملخص التحقق النهائي
# =========================================================
print("\n" + "=" * 65)
print("📊 نتيجة استعادة الجداول")
print("=" * 65)
for table_name in [
    'wadq_evaluation_df',
    'wadq_smart_report',
    'wadq_final_ai_report'
]:
    table = globals()[table_name]
    print(f"✅ {table_name}: {table.shape[0]} صف × {table.shape[1]} عمود")
print("\n📌 معاينة التقرير النهائي:")
display(wadq_final_ai_report.head(10))
print("\n🌧️ انتهت عملية استعادة الجداول الثلاثة.")
print("🔒 لم يتم تعديل الجداول المصدرية.")
print("⚠️ التقارير أُعيد بناؤها من البيانات المتاحة حاليًا؛")
print("   وقد لا تطابق جميع تفاصيل النسخ السابقة حرفيًا.")

🌧️ الودق AI — استعادة الجداول الثلاثة
=================================================================
✅ مصدر التحليل الموحد: (9, 15)
✅ تمت استعادة wadq_evaluation_df
✅ تمت استعادة wadq_smart_report
✅ تمت استعادة wadq_final_ai_report

=================================================================
📊 نتيجة استعادة الجداول
=================================================================
✅ wadq_evaluation_df: 9 صف × 18 عمود
✅ wadq_smart_report: 9 صف × 19 عمود
✅ wadq_final_ai_report: 9 صف × 20 عمود

📌 معاينة التقرير النهائي:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,news_count,positive_news,negative_news,neutral_news,ملخص الودق الذكي,تقييم RSI,تقييم الأخبار,تقييم الودق,حالة توفر السعر
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,NVDA,47,10,1,36,الأصل: NVDA | الاتجاه الفني: صاعد | عدد الأخبا...,ضمن النطاق المتوسط,أخبار إيجابية نسبيًا,إيجابي نسبيًا,سعر متاح مبدئيًا
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,TSLA,20,2,0,18,الأصل: TSLA | الاتجاه الفني: صاعد | عدد الأخبا...,ضمن النطاق المتوسط,أخبار إيجابية نسبيًا,إيجابي نسبيًا,سعر متاح مبدئيًا
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد,AAPL,1,0,0,1,الأصل: AAPL | الاتجاه الفني: صاعد | عدد الأخبا...,ضمن النطاق المتوسط,أخبار محايدة,مختلط أو يحتاج متابعة,سعر متاح مبدئيًا
3,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,MSFT,35,8,1,26,الأصل: MSFT | الاتجاه الفني: صاعد | عدد الأخبا...,تشبع شرائي محتمل,أخبار إيجابية نسبيًا,مختلط أو يحتاج متابعة,سعر متاح مبدئيًا
4,أمازون,AMZN,258.58,252.83,258.35,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط,AMZN,17,4,0,13,الأصل: AMZN | الاتجاه الفني: مختلط | عدد الأخب...,ضمن النطاق المتوسط,أخبار إيجابية نسبيًا,مختلط أو يحتاج متابعة,سعر متاح مبدئيًا
5,ألفابت,GOOGL,353.78,346.53,345.69,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد,GOOGL,22,6,0,16,الأصل: GOOGL | الاتجاه الفني: صاعد | عدد الأخب...,ضمن النطاق المتوسط,أخبار إيجابية نسبيًا,إيجابي نسبيًا,سعر متاح مبدئيًا
6,ميتا,META,762.50,727.58,646.59,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد,META,2,1,0,1,الأصل: META | الاتجاه الفني: صاعد | عدد الأخبا...,ضمن النطاق المتوسط,أخبار إيجابية نسبيًا,إيجابي نسبيًا,سعر متاح مبدئيًا
7,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد,QQQ,4,1,0,3,الأصل: QQQ | الاتجاه الفني: صاعد | عدد الأخبار...,ضمن النطاق المتوسط,أخبار إيجابية نسبيًا,إيجابي نسبيًا,سعر متاح مبدئيًا
8,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد,SPY,50,11,11,28,الأصل: SPY | الاتجاه الفني: صاعد | عدد الأخبار...,ضمن النطاق المتوسط,أخبار غير كافية للتقييم,مختلط أو يحتاج متابعة,سعر متاح مبدئيًا

🌧️ انتهت عملية استعادة الجداول الثلاثة.
🔒 لم يتم تعديل الجداول المصدرية.
⚠️ التقارير أُعيد بناؤها من البيانات المتاحة حاليًا؛
   وقد لا تطابق جميع تفاصيل النسخ السابقة حرفيًا.

In [ ]:
# ============================================================
# 🌧️ الودق AI — النظام الشامل للمراحل 49 إلى 57
# دمج الأخبار والتحليل الفني وتقييم الفرص ومراجعة الجودة
# ============================================================
# مهم:
# - لا يعدّل الجداول الأصلية.
# - لا يعيد تحميل الأسعار أو الأخبار.
# - لا يخترع بيانات ناقصة.
# - لا ينفذ أوامر شراء أو بيع.
# ============================================================
import pandas as pd
import numpy as np
from datetime import datetime
from zoneinfo import ZoneInfo
print("🌧️ الودق AI — بدء النظام الشامل")
print("=" * 75)
# ------------------------------------------------------------
# أدوات مساعدة
# ------------------------------------------------------------
wadq_run_time = datetime.now(
    ZoneInfo("Asia/Riyadh")
).strftime("%Y-%m-%d %H:%M:%S")
wadq_stage_results = []
wadq_warnings = []
def wadq_log(stage, status, details):
    wadq_stage_results.append({
        "المرحلة": stage,
        "الحالة": status,
        "التفاصيل": details
    })
    print(f"{status} | {stage} | {details}")
def wadq_first_existing(names):
    for name in names:
        obj = globals().get(name)
        if isinstance(obj, pd.DataFrame):
            return name, obj.copy(deep=True)
    return None, None
def wadq_numeric(df, col):
    if col not in df.columns:
        return pd.Series(np.nan, index=df.index, dtype=float)
    return pd.to_numeric(df[col], errors="coerce")
# ------------------------------------------------------------
# المرحلة 49 — فحص مصادر البيانات
# ------------------------------------------------------------
print("\n🔹 المرحلة 49 — فحص مصادر البيانات")
source_candidates = [
    "wadq_final_ai_report",
    "wadq_smart_report",
    "wadq_evaluation_df",
    "wadq_integrated_df"
]
source_name, source_df = wadq_first_existing(source_candidates)
if source_df is None:
    raise RuntimeError(
        "لم يُعثر على أي تقرير أمريكي موحد. "
        "شغّلي الخلايا السابقة التي أنشأت wadq_integrated_df."
    )
wadq_us_df = source_df.copy(deep=True)
wadq_log(
    "49 — فحص المصدر الأمريكي",
    "✅",
    f"المصدر {source_name}: {len(wadq_us_df)} صف و{len(wadq_us_df.columns)} عمود"
)
global_name, global_source = wadq_first_existing([
    "wadq_global_master_report_df",
    "wadq_global_alerts_df",
    "wadq_phase48_df",
    "wadq_phase47_df"
])
if global_source is not None:
    wadq_global_source_df = global_source.copy(deep=True)
    wadq_log(
        "49 — فحص المصدر العالمي",
        "✅",
        f"المصدر {global_name}: {len(wadq_global_source_df)} صف"
    )
else:
    wadq_global_source_df = pd.DataFrame()
    wadq_warnings.append("لم يُعثر على جدول عالمي مناسب.")
    wadq_log("49 — فحص المصدر العالمي", "⚠️", "المصدر العالمي غير متاح")
# ------------------------------------------------------------
# المرحلة 50 — توحيد أسماء الأعمدة الأساسية
# ------------------------------------------------------------
print("\n🔹 المرحلة 50 — تجهيز البيانات الموحدة")
wadq_us = wadq_us_df.copy(deep=True)
# توحيد الرمز
if "الرمز" not in wadq_us.columns:
    if "ticker" in wadq_us.columns:
        wadq_us["الرمز"] = wadq_us["ticker"]
    else:
        wadq_us["الرمز"] = np.nan
# توحيد اسم الأصل
if "السهم" not in wadq_us.columns:
    if "الأصل" in wadq_us.columns:
        wadq_us["السهم"] = wadq_us["الأصل"]
    else:
        wadq_us["السهم"] = wadq_us["الرمز"]
# الاحتفاظ بالأخبار والمؤشرات كما هي.
# لا ندمج الجدولين العالمي والأمريكي عشوائيًا لأن بنيتهما مختلفة.
wadq_unified_df = wadq_us.copy(deep=True)
wadq_log(
    "50 — توحيد الأعمدة",
    "✅",
    f"تم تجهيز {len(wadq_unified_df)} أصلًا أمريكيًا دون تعديل المصدر"
)
# ------------------------------------------------------------
# المرحلة 51 — تحليل الاتجاه والمؤشرات الفنية
# ------------------------------------------------------------
print("\n🔹 المرحلة 51 — التحليل الفني")
wadq_analysis_df = wadq_unified_df.copy(deep=True)
if "الاتجاه" not in wadq_analysis_df.columns:
    wadq_analysis_df["الاتجاه"] = "غير متاح"
if "RSI" in wadq_analysis_df.columns:
    wadq_rsi = wadq_numeric(wadq_analysis_df, "RSI")
    wadq_analysis_df["حالة RSI المراجعة"] = np.select(
        [
            wadq_rsi.notna() & (wadq_rsi < 30),
            wadq_rsi.notna() & (wadq_rsi > 70),
            wadq_rsi.notna()
        ],
        [
            "تشبع بيعي محتمل",
            "تشبع شرائي محتمل",
            "ضمن النطاق المتوسط"
        ],
        default="غير متاح"
    )
else:
    wadq_analysis_df["حالة RSI المراجعة"] = "غير متاح"
if all(c in wadq_analysis_df.columns for c in ["MACD", "إشارة MACD"]):
    wadq_macd = wadq_numeric(wadq_analysis_df, "MACD")
    wadq_signal = wadq_numeric(wadq_analysis_df, "إشارة MACD")
    wadq_analysis_df["حالة MACD المراجعة"] = np.select(
        [
            wadq_macd.notna() & wadq_signal.notna() & (wadq_macd > wadq_signal),
            wadq_macd.notna() & wadq_signal.notna() & (wadq_macd < wadq_signal),
        ],
        [
            "MACD أعلى من الإشارة",
            "MACD أدنى من الإشارة"
        ],
        default="غير متاح"
    )
else:
    wadq_analysis_df["حالة MACD المراجعة"] = "غير متاح"
wadq_log(
    "51 — التحليل الفني",
    "✅",
    "تمت مراجعة الاتجاه وRSI وMACD بحسب الأعمدة المتاحة"
)
# ------------------------------------------------------------
# المرحلة 52 — تحليل الأخبار
# ------------------------------------------------------------
print("\n🔹 المرحلة 52 — تحليل الأخبار")
wadq_news_df = wadq_analysis_df.copy(deep=True)
for col in ["positive_news", "negative_news", "neutral_news", "news_count"]:
    if col in wadq_news_df.columns:
        wadq_news_df[col] = pd.to_numeric(
            wadq_news_df[col], errors="coerce"
        )
if all(c in wadq_news_df.columns for c in [
    "positive_news", "negative_news", "neutral_news"
]):
    pos = wadq_numeric(wadq_news_df, "positive_news").fillna(0)
    neg = wadq_numeric(wadq_news_df, "negative_news").fillna(0)
    neu = wadq_numeric(wadq_news_df, "neutral_news").fillna(0)
    wadq_news_df["تصنيف الأخبار المراجع"] = np.select(
        [
            (pos > neg) & (pos > 0),
            (neg > pos) & (neg > 0),
            (pos == neg) & ((pos + neg) > 0),
            (pos == 0) & (neg == 0) & (neu > 0)
        ],
        [
            "إيجابية نسبيًا",
            "سلبية نسبيًا",
            "إيجابية وسلبية بالتساوي",
            "محايدة"
        ],
        default="غير كافية أو غير متاحة"
    )
else:
    wadq_news_df["تصنيف الأخبار المراجع"] = "بيانات تصنيف الأخبار غير متاحة"
wadq_log(
    "52 — تحليل الأخبار",
    "✅",
    "تم تصنيف الأخبار بحسب أعدادها الموجودة، دون جلب أخبار جديدة"
)
# ------------------------------------------------------------
# المرحلة 53 — حساب درجة تقييم أولية قابلة للتفسير
# ------------------------------------------------------------
print("\n🔹 المرحلة 53 — تقييم الفرص")
wadq_score_df = wadq_news_df.copy(deep=True)
wadq_score_df["درجة فنية أولية"] = 0.0
wadq_score_df["درجة أخبار أولية"] = 0.0
wadq_score_df["عدد عناصر التقييم المتاحة"] = 0
# الاتجاه الفني: لا يُحتسب إلا إذا كانت قيمته معروفة
trend = wadq_score_df["الاتجاه"].astype(str).str.strip().str.lower()
wadq_score_df.loc[trend.isin(["صاعد", "up", "bullish"]), "درجة فنية أولية"] += 1
wadq_score_df.loc[trend.isin(["هابط", "down", "bearish"]), "درجة فنية أولية"] -= 1
trend_known = trend.isin([
    "صاعد", "هابط", "مختلط",
    "up", "down", "bullish", "bearish"
])
wadq_score_df["عدد عناصر التقييم المتاحة"] += trend_known.astype(int)
# MACD
if "MACD" in wadq_score_df.columns and "إشارة MACD" in wadq_score_df.columns:
    m = wadq_numeric(wadq_score_df, "MACD")
    s = wadq_numeric(wadq_score_df, "إشارة MACD")
    macd_valid = m.notna() & s.notna()
    wadq_score_df.loc[macd_valid & (m > s), "درجة فنية أولية"] += 1
    wadq_score_df.loc[macd_valid & (m < s), "درجة فنية أولية"] -= 1
    wadq_score_df["عدد عناصر التقييم المتاحة"] += macd_valid.astype(int)
# RSI: الحذر عند التشبع الشرائي، وليس إشارة بيع مؤكدة
if "RSI" in wadq_score_df.columns:
    rsi = wadq_numeric(wadq_score_df, "RSI")
    rsi_valid = rsi.notna()
    wadq_score_df.loc[rsi_valid & (rsi < 30), "درجة فنية أولية"] += 0.5
    wadq_score_df.loc[rsi_valid & (rsi > 70), "درجة فنية أولية"] -= 0.5
    wadq_score_df["عدد عناصر التقييم المتاحة"] += rsi_valid.astype(int)
# الأخبار: مقارنة التصنيفات فقط، لا اعتبار عدد الأخبار وحده قوةً للتأثير
if all(c in wadq_score_df.columns for c in [
    "positive_news", "negative_news"
]):
    pos = wadq_numeric(wadq_score_df, "positive_news")
    neg = wadq_numeric(wadq_score_df, "negative_news")
    news_valid = pos.notna() & neg.notna()
    wadq_score_df.loc[news_valid & (pos > neg), "درجة أخبار أولية"] = 1
    wadq_score_df.loc[news_valid & (neg > pos), "درجة أخبار أولية"] = -1
    wadq_score_df.loc[news_valid & (pos == neg), "درجة أخبار أولية"] = 0
    wadq_score_df["عدد عناصر التقييم المتاحة"] += news_valid.astype(int)
wadq_score_df["الدرجة الأولية الإجمالية"] = (
    wadq_score_df["درجة فنية أولية"]
    + wadq_score_df["درجة أخبار أولية"]
)
def wadq_opportunity_label(row):
    available = row["عدد عناصر التقييم المتاحة"]
    score = row["الدرجة الأولية الإجمالية"]
    if available < 2:
        return "بيانات غير كافية للتقييم"
    if score >= 2:
        return "إيجابي نسبيًا — يحتاج تحققًا"
    if score <= -2:
        return "حذر — إشارات سلبية"
    return "مختلط — يحتاج متابعة"
wadq_score_df["التقييم الأولي للودق"] = (
    wadq_score_df.apply(wadq_opportunity_label, axis=1)
)
wadq_log(
    "53 — تقييم الفرص",
    "✅",
    "تم احتساب درجات أولية قابلة للتفسير، وليست احتمالات ربح"
)
# ------------------------------------------------------------
# المرحلة 54 — مراجعة توفر الأسعار
# ------------------------------------------------------------
print("\n🔹 المرحلة 54 — مراجعة الأسعار")
wadq_quality_df = wadq_score_df.copy(deep=True)
price_col = None
for candidate in ["آخر إغلاق", "أحدث سعر متاح", "السعر", "سعر التحديث"]:
    if candidate in wadq_quality_df.columns:
        price_col = candidate
        break
if price_col:
    price = wadq_numeric(wadq_quality_df, price_col)
    wadq_quality_df["نتيجة فحص السعر"] = np.where(
        price.notna() & (price > 0),
        "سعر موجب متاح",
        "سعر مفقود أو غير صالح"
    )
else:
    wadq_quality_df["نتيجة فحص السعر"] = "عمود السعر غير متاح"
date_col = None
for candidate in ["تاريخ آخر بيانات", "تاريخ التحديث", "التاريخ"]:
    if candidate in wadq_quality_df.columns:
        date_col = candidate
        break
today = pd.Timestamp(datetime.now(ZoneInfo("Asia/Riyadh")).date())
if date_col:
    parsed_date = pd.to_datetime(
        wadq_quality_df[date_col], errors="coerce", utc=True
    ).dt.tz_convert("Asia/Riyadh").dt.tz_localize(None).dt.normalize()
    wadq_quality_df["عمر البيانات المحسوب بالأيام"] = (
        today - parsed_date
    ).dt.days
    wadq_quality_df["نتيجة فحص التاريخ"] = np.select(
        [
            parsed_date.isna(),
            parsed_date > today,
            parsed_date == today,
            parsed_date < today
        ],
        [
            "تاريخ مفقود أو غير صالح",
            "تاريخ مستقبلي يحتاج تحققًا",
            "تاريخ اليوم",
            "تاريخ سابق"
        ],
        default="غير محدد"
    )
else:
    wadq_quality_df["عمر البيانات المحسوب بالأيام"] = np.nan
    wadq_quality_df["نتيجة فحص التاريخ"] = "عمود التاريخ غير متاح"
wadq_log(
    "54 — جودة الأسعار والتواريخ",
    "✅",
    "تم فحص السعر والتاريخ عند توفر أعمدتهما"
)
# ------------------------------------------------------------
# المرحلة 55 — إنشاء لوحة القرار
# ------------------------------------------------------------
print("\n🔹 المرحلة 55 — لوحة القرار")
decision_cols = [
    "السهم", "الأصل", "الرمز", "ticker",
    "آخر إغلاق", "أحدث سعر متاح", "السعر",
    "الاتجاه", "RSI", "حالة RSI المراجعة",
    "MACD", "إشارة MACD", "حالة MACD المراجعة",
    "news_count", "positive_news", "negative_news", "neutral_news",
    "تصنيف الأخبار المراجع",
    "درجة فنية أولية", "درجة أخبار أولية",
    "الدرجة الأولية الإجمالية", "التقييم الأولي للودق",
    "نتيجة فحص السعر", "نتيجة فحص التاريخ",
    "عمر البيانات المحسوب بالأيام"
]
wadq_decision_cols = [
    c for c in decision_cols if c in wadq_quality_df.columns
]
wadq_decision_board_df = wadq_quality_df[wadq_decision_cols].copy()
# إزالة التكرار حسب الرمز إن توفر، دون دمج أصول مختلفة
symbol_col = "الرمز" if "الرمز" in wadq_decision_board_df.columns else (
    "ticker" if "ticker" in wadq_decision_board_df.columns else None
)
if symbol_col:
    wadq_decision_board_df = wadq_decision_board_df.drop_duplicates(
        subset=[symbol_col], keep="first"
    )
wadq_log(
    "55 — لوحة القرار",
    "✅",
    f"تم إنشاء لوحة تحتوي على {len(wadq_decision_board_df)} أصلًا"
)
# ------------------------------------------------------------
# المرحلة 56 — اختبار الجودة
# ------------------------------------------------------------
print("\n🔹 المرحلة 56 — اختبار الجودة")
wadq_quality_checks = []
def add_quality_check(name, passed, detail):
    wadq_quality_checks.append({
        "الفحص": name,
        "النتيجة": "ناجح" if passed else "يحتاج مراجعة",
        "التفاصيل": detail
    })
add_quality_check(
    "وجود بيانات المصدر",
    len(wadq_quality_df) > 0,
    f"عدد الصفوف: {len(wadq_quality_df)}"
)
if symbol_col:
    missing_symbols = wadq_decision_board_df[symbol_col].isna().sum()
    add_quality_check(
        "توفر رموز الأصول",
        missing_symbols == 0,
        f"عدد الرموز المفقودة: {missing_symbols}"
    )
else:
    add_quality_check(
        "توفر رموز الأصول",
        False,
        "لم يُعثر على عمود الرمز"
    )
if "نتيجة فحص السعر" in wadq_quality_df.columns:
    invalid_prices = (
        wadq_quality_df["نتيجة فحص السعر"] != "سعر موجب متاح"
    ).sum()
    add_quality_check(
        "جودة الأسعار",
        invalid_prices == 0,
        f"صفوف تحتاج مراجعة: {invalid_prices}"
    )
if "نتيجة فحص التاريخ" in wadq_quality_df.columns:
    future_dates = (
        wadq_quality_df["نتيجة فحص التاريخ"]
        == "تاريخ مستقبلي يحتاج تحققًا"
    ).sum()
    add_quality_check(
        "التواريخ المستقبلية",
        future_dates == 0,
        f"تواريخ مستقبلية: {future_dates}"
    )
wadq_quality_report_df = pd.DataFrame(wadq_quality_checks)
wadq_log(
    "56 — اختبار الجودة",
    "✅",
    f"تم إجراء {len(wadq_quality_report_df)} اختبارات جودة"
)
# ------------------------------------------------------------
# المرحلة 57 — التقرير النهائي
# ------------------------------------------------------------
print("\n🔹 المرحلة 57 — التقرير النهائي")
wadq_final_report_df = wadq_quality_df.copy(deep=True)
wadq_final_report_df["وقت إنشاء التقرير"] = wadq_run_time
# حالة الجاهزية لكل أصل
def wadq_readiness(row):
    issues = []
    if row.get("نتيجة فحص السعر") == "سعر مفقود أو غير صالح":
        issues.append("السعر")
    elif row.get("نتيجة فحص السعر") == "عمود السعر غير متاح":
        issues.append("مصدر السعر")
    if row.get("نتيجة فحص التاريخ") in [
        "تاريخ مستقبلي يحتاج تحققًا",
        "تاريخ مفقود أو غير صالح"
    ]:
        issues.append("التاريخ")
    if row.get("التقييم الأولي للودق") == "بيانات غير كافية للتقييم":
        issues.append("التقييم")
    if issues:
        return "يحتاج مراجعة: " + "، ".join(issues)
    return "اجتاز الفحوص الأولية — ليس ضمانًا للتوصية"
wadq_final_report_df["حالة الجاهزية"] = (
    wadq_final_report_df.apply(wadq_readiness, axis=1)
)
# إنشاء ملخص عالمي مستقل إن توفرت البيانات العالمية
if not wadq_global_source_df.empty:
    wadq_global_review_df = wadq_global_source_df.copy(deep=True)
else:
    wadq_global_review_df = pd.DataFrame()
# ملخص النتائج
wadq_summary_df = pd.DataFrame([
    {"البند": "وقت تشغيل النظام", "القيمة": wadq_run_time},
    {"البند": "مصدر التقرير الأمريكي", "القيمة": source_name},
    {"البند": "عدد الأصول الأمريكية", "القيمة": len(wadq_final_report_df)},
    {"البند": "عدد أعمدة التقرير النهائي", "القيمة": len(wadq_final_report_df.columns)},
    {"البند": "عدد الأصول في لوحة القرار", "القيمة": len(wadq_decision_board_df)},
    {"البند": "عدد اختبارات الجودة", "القيمة": len(wadq_quality_report_df)},
    {"البند": "عدد اختبارات الجودة التي تحتاج مراجعة",
     "القيمة": int((wadq_quality_report_df["النتيجة"] == "يحتاج مراجعة").sum())},
    {"البند": "عدد الأصول في المصدر العالمي",
     "القيمة": len(wadq_global_review_df)}
])
wadq_log(
    "57 — التقرير النهائي",
    "✅",
    "اكتمل إنشاء التقارير الأولية ولوحة القرار واختبارات الجودة"
)
# ------------------------------------------------------------
# عرض النتائج
# ------------------------------------------------------------
wadq_stage_log_df = pd.DataFrame(wadq_stage_results)
print("\n" + "=" * 75)
print("🌧️ ملخص المراحل")
display(wadq_stage_log_df)
print("\n📊 ملخص النظام")
display(wadq_summary_df)
print("\n🎯 لوحة القرار الاستثماري الأولية")
display(wadq_decision_board_df.head(20))
print("\n🔎 اختبارات الجودة")
display(wadq_quality_report_df)
print("\n📋 التقرير النهائي — أول 20 صفًا")
display(wadq_final_report_df.head(20))
if not wadq_global_review_df.empty:
    print("\n🌍 معاينة التقرير العالمي")
    display(wadq_global_review_df.head(10))
print("\n" + "=" * 75)
print("🌧️ اكتمل تنفيذ المراحل 49–57.")
print("📌 التقرير النهائي: wadq_final_report_df")
print("📌 لوحة القرار: wadq_decision_board_df")
print("📌 اختبارات الجودة: wadq_quality_report_df")
print("📌 ملخص النظام: wadq_summary_df")
print("📌 سجل المراحل: wadq_stage_log_df")
print("📌 التقرير العالمي: wadq_global_review_df")
print("⚠️ هذه مخرجات تحليلية أولية وليست ضمانًا لصحة الأسعار أو الأرباح.")
print("🔒 لم يتم تعديل الجداول الأصلية.")

🌧️ الودق AI — بدء النظام الشامل
===========================================================================

🔹 المرحلة 49 — فحص مصادر البيانات
✅ | 49 — فحص المصدر الأمريكي | المصدر wadq_final_ai_report: 9 صف و20 عمود
✅ | 49 — فحص المصدر العالمي | المصدر wadq_global_master_report_df: 17 صف

🔹 المرحلة 50 — تجهيز البيانات الموحدة
✅ | 50 — توحيد الأعمدة | تم تجهيز 9 أصلًا أمريكيًا دون تعديل المصدر

🔹 المرحلة 51 — التحليل الفني
✅ | 51 — التحليل الفني | تمت مراجعة الاتجاه وRSI وMACD بحسب الأعمدة المتاحة

🔹 المرحلة 52 — تحليل الأخبار
✅ | 52 — تحليل الأخبار | تم تصنيف الأخبار بحسب أعدادها الموجودة، دون جلب أخبار جديدة

🔹 المرحلة 53 — تقييم الفرص
✅ | 53 — تقييم الفرص | تم احتساب درجات أولية قابلة للتفسير، وليست احتمالات ربح

🔹 المرحلة 54 — مراجعة الأسعار
✅ | 54 — جودة الأسعار والتواريخ | تم فحص السعر والتاريخ عند توفر أعمدتهما

🔹 المرحلة 55 — لوحة القرار
✅ | 55 — لوحة القرار | تم إنشاء لوحة تحتوي على 9 أصلًا

🔹 المرحلة 56 — اختبار الجودة
✅ | 56 — اختبار الجودة | تم إجراء 4 اختبارات جودة

🔹 المرحلة 57 — التقرير النهائي
✅ | 57 — التقرير النهائي | اكتمل إنشاء التقارير الأولية ولوحة القرار واختبارات الجودة

===========================================================================
🌧️ ملخص المراحل

,المرحلة,الحالة,التفاصيل
0,49 — فحص المصدر الأمريكي,✅,المصدر wadq_final_ai_report: 9 صف و20 عمود
1,49 — فحص المصدر العالمي,✅,المصدر wadq_global_master_report_df: 17 صف
2,50 — توحيد الأعمدة,✅,تم تجهيز 9 أصلًا أمريكيًا دون تعديل المصدر
3,51 — التحليل الفني,✅,تمت مراجعة الاتجاه وRSI وMACD بحسب الأعمدة الم...
4,52 — تحليل الأخبار,✅,تم تصنيف الأخبار بحسب أعدادها الموجودة، دون جل...
5,53 — تقييم الفرص,✅,تم احتساب درجات أولية قابلة للتفسير، وليست احت...
6,54 — جودة الأسعار والتواريخ,✅,تم فحص السعر والتاريخ عند توفر أعمدتهما
7,55 — لوحة القرار,✅,تم إنشاء لوحة تحتوي على 9 أصلًا
8,56 — اختبار الجودة,✅,تم إجراء 4 اختبارات جودة
9,57 — التقرير النهائي,✅,اكتمل إنشاء التقارير الأولية ولوحة القرار واخت...

📊 ملخص النظام

                                   البند                القيمة
0                       وقت تشغيل النظام   2026-10-14 02:53:01
1                  مصدر التقرير الأمريكي  wadq_final_ai_report
2                   عدد الأصول الأمريكية                     9
3              عدد أعمدة التقرير النهائي                    33
4              عدد الأصول في لوحة القرار                     9
5                    عدد اختبارات الجودة                     4
6  عدد اختبارات الجودة التي تحتاج مراجعة                     0
7           عدد الأصول في المصدر العالمي                    17

🎯 لوحة القرار الاستثماري الأولية

,السهم,الرمز,ticker,آخر إغلاق,الاتجاه,RSI,حالة RSI المراجعة,MACD,إشارة MACD,حالة MACD المراجعة,...,negative_news,neutral_news,تصنيف الأخبار المراجع,درجة فنية أولية,درجة أخبار أولية,الدرجة الأولية الإجمالية,التقييم الأولي للودق,نتيجة فحص السعر,نتيجة فحص التاريخ,عمر البيانات المحسوب بالأيام
0,إنفيديا,NVDA,NVDA,228.52,صاعد,52.03,ضمن النطاق المتوسط,2.9231,3.5905,MACD أدنى من الإشارة,...,1,36,إيجابية نسبيًا,0.0,1.0,1.0,مختلط — يحتاج متابعة,سعر موجب متاح,عمود التاريخ غير متاح,NaN
1,تسلا,TSLA,TSLA,375.23,صاعد,54.53,ضمن النطاق المتوسط,4.9187,4.3678,MACD أعلى من الإشارة,...,0,18,إيجابية نسبيًا,2.0,1.0,3.0,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,عمود التاريخ غير متاح,NaN
2,آبل,AAPL,AAPL,341.27,صاعد,60.50,ضمن النطاق المتوسط,3.7919,3.8268,MACD أدنى من الإشارة,...,0,1,محايدة,0.0,0.0,0.0,مختلط — يحتاج متابعة,سعر موجب متاح,عمود التاريخ غير متاح,NaN
3,مايكروسوفت,MSFT,MSFT,543.45,صاعد,70.79,تشبع شرائي محتمل,12.3949,10.2280,MACD أعلى من الإشارة,...,1,26,إيجابية نسبيًا,1.5,1.0,2.5,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,عمود التاريخ غير متاح,NaN
4,أمازون,AMZN,AMZN,258.58,مختلط,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,MACD أعلى من الإشارة,...,0,13,إيجابية نسبيًا,1.0,1.0,2.0,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,عمود التاريخ غير متاح,NaN
5,ألفابت,GOOGL,GOOGL,353.78,صاعد,58.22,ضمن النطاق المتوسط,2.0625,0.9157,MACD أعلى من الإشارة,...,0,16,إيجابية نسبيًا,2.0,1.0,3.0,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,عمود التاريخ غير متاح,NaN
6,ميتا,META,META,762.50,صاعد,66.04,ضمن النطاق المتوسط,25.9815,28.9692,MACD أدنى من الإشارة,...,0,1,إيجابية نسبيًا,0.0,1.0,1.0,مختلط — يحتاج متابعة,سعر موجب متاح,عمود التاريخ غير متاح,NaN
7,ناسداك 100,QQQ,QQQ,743.57,صاعد,54.74,ضمن النطاق المتوسط,8.1107,8.7652,MACD أدنى من الإشارة,...,0,3,إيجابية نسبيًا,0.0,1.0,1.0,مختلط — يحتاج متابعة,سعر موجب متاح,عمود التاريخ غير متاح,NaN
8,ستاندرد آند بورز 500,SPY,SPY,778.01,صاعد,59.80,ضمن النطاق المتوسط,3.9933,3.0564,MACD أعلى من الإشارة,...,11,28,إيجابية وسلبية بالتساوي,2.0,0.0,2.0,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,عمود التاريخ غير متاح,NaN

🔎 اختبارات الجودة

                 الفحص النتيجة                التفاصيل
0   وجود بيانات المصدر    ناجح           عدد الصفوف: 9
1     توفر رموز الأصول    ناجح  عدد الرموز المفقودة: 0
2         جودة الأسعار    ناجح    صفوف تحتاج مراجعة: 0
3  التواريخ المستقبلية    ناجح      تواريخ مستقبلية: 0

📋 التقرير النهائي — أول 20 صفًا

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,...,درجة فنية أولية,درجة أخبار أولية,عدد عناصر التقييم المتاحة,الدرجة الأولية الإجمالية,التقييم الأولي للودق,نتيجة فحص السعر,عمر البيانات المحسوب بالأيام,نتيجة فحص التاريخ,وقت إنشاء التقرير,حالة الجاهزية
0,إنفيديا,NVDA,228.52,228.32,222.90,52.03,ضمن النطاق المتوسط,2.9231,3.5905,صاعد,...,0.0,1.0,4,1.0,مختلط — يحتاج متابعة,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية
1,تسلا,TSLA,375.23,370.54,357.14,54.53,ضمن النطاق المتوسط,4.9187,4.3678,صاعد,...,2.0,1.0,4,3.0,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية
2,آبل,AAPL,341.27,336.28,323.77,60.50,ضمن النطاق المتوسط,3.7919,3.8268,صاعد,...,0.0,0.0,4,0.0,مختلط — يحتاج متابعة,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية
3,مايكروسوفت,MSFT,543.45,514.20,502.87,70.79,تشبع شرائي محتمل,12.3949,10.2280,صاعد,...,1.5,1.0,4,2.5,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية
4,أمازون,AMZN,258.58,252.83,258.35,54.44,ضمن النطاق المتوسط,0.9722,-0.3643,مختلط,...,1.0,1.0,4,2.0,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية
5,ألفابت,GOOGL,353.78,346.53,345.69,58.22,ضمن النطاق المتوسط,2.0625,0.9157,صاعد,...,2.0,1.0,4,3.0,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية
6,ميتا,META,762.50,727.58,646.59,66.04,ضمن النطاق المتوسط,25.9815,28.9692,صاعد,...,0.0,1.0,4,1.0,مختلط — يحتاج متابعة,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية
7,ناسداك 100,QQQ,743.57,741.22,726.06,54.74,ضمن النطاق المتوسط,8.1107,8.7652,صاعد,...,0.0,1.0,4,1.0,مختلط — يحتاج متابعة,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية
8,ستاندرد آند بورز 500,SPY,778.01,769.68,767.39,59.80,ضمن النطاق المتوسط,3.9933,3.0564,صاعد,...,2.0,0.0,4,2.0,إيجابي نسبيًا — يحتاج تحققًا,سعر موجب متاح,NaN,عمود التاريخ غير متاح,2026-10-14 02:53:01,اجتاز الفحوص الأولية — ليس ضمانًا للتوصية

🌍 معاينة التقرير العالمي

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات
0,^GSPC,S&P 500 - أمريكا,7805.450195,7807.240234,-0.022928,2026-10-13
1,^IXIC,Nasdaq Composite - أمريكا,27204.380859,27245.900391,-0.152388,2026-10-13
2,^DJI,Dow Jones - أمريكا,51670.101562,51850.550781,-0.348018,2026-10-13
3,^GDAXI,DAX - ألمانيا,25259.900391,25277.679688,-0.070336,2026-10-13
4,^FCHI,CAC 40 - فرنسا,7827.629883,7832.879883,-0.067025,2026-10-13
5,^FTSE,FTSE 100 - بريطانيا,10650.330078,10656.299805,-0.056021,2026-10-13
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,2026-10-09
7,^HSI,Hang Seng - هونغ كونغ,24271.199219,24211.349609,0.247197,2026-10-12
8,GC=F,الذهب,4183.000000,4190.600098,-0.181361,2026-10-13
9,SI=F,الفضة,59.369999,60.140999,-1.281987,2026-10-13

===========================================================================
🌧️ اكتمل تنفيذ المراحل 49–57.
📌 التقرير النهائي: wadq_final_report_df
📌 لوحة القرار: wadq_decision_board_df
📌 اختبارات الجودة: wadq_quality_report_df
📌 ملخص النظام: wadq_summary_df
📌 سجل المراحل: wadq_stage_log_df
📌 التقرير العالمي: wadq_global_review_df
⚠️ هذه مخرجات تحليلية أولية وليست ضمانًا لصحة الأسعار أو الأرباح.
🔒 لم يتم تعديل الجداول الأصلية.

In [ ]:
# ================================================================
# 🌧️ الودق AI — المرحلة 58
# فحص تواريخ البيانات وحداثتها
# ================================================================

import pandas as pd
import numpy as np
from datetime import datetime

print("🌧️ الودق AI — المرحلة 58")
print("=" * 70)

# ------------------------------------------------
# 1. التحقق من وجود الجداول السابقة
# ------------------------------------------------

required_tables = {
    "wadq_final_report_df": "التقرير النهائي",
    "wadq_decision_board_df": "لوحة القرار",
    "wadq_global_master_report_df": "التقرير العالمي",
    "wadq_final_ai_report": "المصدر الأمريكي الأصلي",
}

available_tables = {}

for var_name, description in required_tables.items():
    obj = globals().get(var_name)

    if isinstance(obj, pd.DataFrame):
        available_tables[var_name] = obj
        print(
            f"✅ {description}: "
            f"{obj.shape[0]} صف × {obj.shape[1]} عمود"
        )
    else:
        print(f"⚠️ {description}: الجدول غير متاح حاليًا")

# ------------------------------------------------
# 2. تحديد التاريخ المرجعي
# ------------------------------------------------

today = pd.Timestamp.now(tz="Asia/Riyadh").date()

print(f"\n📅 تاريخ الفحص: {today}")

# ------------------------------------------------
# 3. البحث عن أعمدة التاريخ
# ------------------------------------------------

date_keywords = [
    "date",
    "datetime",
    "timestamp",
    "time",
    "تاريخ",
    "آخر بيانات",
    "تاريخ البيانات",
]

def find_date_column(df):
    """البحث عن عمود قد يحتوي على تاريخ البيانات."""

    for col in df.columns:
        name = str(col).strip().lower()

        if any(keyword in name for keyword in date_keywords):
            return col

    return None


def find_ticker_column(df):
    """البحث عن عمود رموز الأصول."""

    possible_names = [
        "ticker",
        "symbol",
        "الرمز",
        "رمز السهم",
    ]

    for col in df.columns:
        if str(col).strip().lower() in possible_names:
            return col

    return None


# ------------------------------------------------
# 4. تحديد مصادر البيانات المتاحة
# ------------------------------------------------

source_candidates = [
    "wadq_final_report_df",
    "wadq_decision_board_df",
    "wadq_final_ai_report",
    "wadq_global_master_report_df",
    "us_technical_df",
    "technical_df",
    "wadq_global_integrated_df",
    "wadq_global_market_df",
]

date_sources = {}

for source_name in source_candidates:
    source_df = globals().get(source_name)

    if isinstance(source_df, pd.DataFrame):
        date_col = find_date_column(source_df)

        if date_col is not None:
            date_sources[source_name] = {
                "df": source_df,
                "date_col": date_col,
                "ticker_col": find_ticker_column(source_df),
            }

            print(
                f"🔎 مصدر تاريخ محتمل: {source_name} "
                f"| عمود التاريخ: {date_col}"
            )

# ------------------------------------------------
# 5. تجهيز الأصول الأمريكية والعالمية
# ------------------------------------------------

records = []

us_df = globals().get("wadq_final_ai_report")

if isinstance(us_df, pd.DataFrame):

    ticker_col = find_ticker_column(us_df)

    for idx, row in us_df.iterrows():

        ticker = (
            str(row[ticker_col])
            if ticker_col is not None
            else str(idx)
        )

        records.append({
            "نوع السوق": "أمريكي",
            "الرمز": ticker,
            "المصدر الأساسي": "wadq_final_ai_report",
            "تاريخ البيانات": pd.NaT,
            "عمر البيانات بالأيام": np.nan,
            "حالة التاريخ": "لم يتم تحديد التاريخ بعد",
        })


global_df = globals().get("wadq_global_master_report_df")

if isinstance(global_df, pd.DataFrame):

    ticker_col = find_ticker_column(global_df)

    for idx, row in global_df.iterrows():

        ticker = (
            str(row[ticker_col])
            if ticker_col is not None
            else str(idx)
        )

        records.append({
            "نوع السوق": "عالمي",
            "الرمز": ticker,
            "المصدر الأساسي": "wadq_global_master_report_df",
            "تاريخ البيانات": pd.NaT,
            "عمر البيانات بالأيام": np.nan,
            "حالة التاريخ": "لم يتم تحديد التاريخ بعد",
        })


wadq_stage58_date_quality_df = pd.DataFrame(records)

# ------------------------------------------------
# 6. مطابقة تواريخ المصادر المتاحة
# ------------------------------------------------

def parse_date(value):
    """تحويل القيمة إلى تاريخ صالح، إن أمكن."""

    if pd.isna(value):
        return pd.NaT

    try:
        parsed = pd.to_datetime(value, errors="coerce", utc=True)

        if pd.isna(parsed):
            return pd.NaT

        return parsed.tz_convert("Asia/Riyadh").date()

    except Exception:
        return pd.NaT


for i, record in wadq_stage58_date_quality_df.iterrows():

    ticker = str(record["الرمز"]).strip()
    market = record["نوع السوق"]

    preferred_sources = (
        ["us_technical_df", "technical_df",
         "wadq_final_report_df", "wadq_final_ai_report"]
        if market == "أمريكي"
        else ["wadq_global_master_report_df",
              "wadq_global_integrated_df",
              "wadq_global_market_df"]
    )

    matched_date = None
    matched_source = None

    for source_name in preferred_sources:

        if source_name not in date_sources:
            continue

        source_info = date_sources[source_name]
        source_df = source_info["df"]
        date_col = source_info["date_col"]
        source_ticker_col = source_info["ticker_col"]

        try:
            if source_ticker_col is not None:

                mask = (
                    source_df[source_ticker_col]
                    .astype(str)
                    .str.strip()
                    .str.upper()
                    == ticker.upper()
                )

                matched_rows = source_df.loc[mask]

                if matched_rows.empty:
                    continue

                raw_dates = matched_rows[date_col].dropna()

            elif len(source_df) == 1:

                raw_dates = source_df[date_col].dropna()

            else:
                continue

            parsed_dates = [
                parse_date(value)
                for value in raw_dates
            ]

            valid_dates = [
                value for value in parsed_dates
                if value is not None and not pd.isna(value)
            ]

            if valid_dates:
                matched_date = max(valid_dates)
                matched_source = source_name
                break

        except Exception:
            continue

    if matched_date is not None:

        age_days = (today - matched_date).days

        if age_days < 0:
            status = "⚠️ تاريخ مستقبلي يحتاج مراجعة"
        elif age_days == 0:
            status = "✅ بيانات بتاريخ اليوم"
        elif age_days <= 3:
            status = "✅ بيانات حديثة نسبيًا"
        else:
            status = "⚠️ بيانات قديمة نسبيًا"

        wadq_stage58_date_quality_df.at[
            i, "تاريخ البيانات"
        ] = str(matched_date)

        wadq_stage58_date_quality_df.at[
            i, "عمر البيانات بالأيام"
        ] = age_days

        wadq_stage58_date_quality_df.at[
            i, "حالة التاريخ"
        ] = status

        wadq_stage58_date_quality_df.at[
            i, "المصدر الأساسي"
        ] = matched_source

    else:

        wadq_stage58_date_quality_df.at[
            i, "حالة التاريخ"
        ] = "⚠️ التاريخ غير متاح — يلزم التحقق من المصدر"


# ------------------------------------------------
# 7. إنشاء ملخص جودة التواريخ
# ------------------------------------------------

total_assets = len(wadq_stage58_date_quality_df)

missing_dates = (
    wadq_stage58_date_quality_df["تاريخ البيانات"]
    .isna()
    .sum()
)

future_dates = (
    wadq_stage58_date_quality_df["حالة التاريخ"]
    .astype(str)
    .str.contains("مستقبلي", na=False)
    .sum()
)

old_dates = (
    wadq_stage58_date_quality_df["حالة التاريخ"]
    .astype(str)
    .str.contains("قديمة", na=False)
    .sum()
)

wadq_stage58_summary_df = pd.DataFrame([
    {"البند": "تاريخ الفحص", "القيمة": str(today)},
    {"البند": "إجمالي الأصول", "القيمة": total_assets},
    {"البند": "تواريخ غير متاحة", "القيمة": int(missing_dates)},
    {"البند": "تواريخ مستقبلية", "القيمة": int(future_dates)},
    {"البند": "بيانات قديمة نسبيًا", "القيمة": int(old_dates)},
    {
        "البند": "حالة المرحلة",
        "القيمة": (
            "تحتاج مراجعة"
            if missing_dates > 0 or future_dates > 0
            else "اجتازت الفحص الأولي"
        )
    },
])

# ------------------------------------------------
# 8. تسجيل المرحلة دون تعديل السجلات السابقة
# ------------------------------------------------

stage58_log = {
    "المرحلة": "58 — فحص تواريخ البيانات",
    "الحالة": "اكتمل الفحص الأولي",
    "التفاصيل": (
        f"إجمالي الأصول: {total_assets} | "
        f"تواريخ غير متاحة: {missing_dates} | "
        f"تواريخ مستقبلية: {future_dates}"
    ),
    "وقت التنفيذ": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
}

if isinstance(globals().get("wadq_stage_log_df"), pd.DataFrame):

    wadq_stage_log_df = pd.concat(
        [
            wadq_stage_log_df,
            pd.DataFrame([stage58_log])
        ],
        ignore_index=True
    )

else:
    wadq_stage_log_df = pd.DataFrame([stage58_log])

# ------------------------------------------------
# 9. عرض النتائج
# ------------------------------------------------

print("\n" + "=" * 70)
print("🌧️ نتيجة المرحلة 58")
print("=" * 70)

print("\n📊 فحص تواريخ الأصول:")
display(wadq_stage58_date_quality_df)

print("\n📋 ملخص جودة التواريخ:")
display(wadq_stage58_summary_df)

print("\n" + "=" * 70)
print("✅ انتهى الفحص الأولي للمرحلة 58")
print("📌 جدول التفاصيل: wadq_stage58_date_quality_df")
print("📌 جدول الملخص: wadq_stage58_summary_df")
print("📌 سجل المراحل: wadq_stage_log_df")
print("🔒 لم يتم تعديل الجداول الأصلية.")
print("⚠️ لم يتم جلب أسعار جديدة في هذه المرحلة.")
print("=" * 70)

🌧️ الودق AI — المرحلة 58
======================================================================
✅ التقرير النهائي: 9 صف × 33 عمود
✅ لوحة القرار: 9 صف × 22 عمود
✅ التقرير العالمي: 17 صف × 6 عمود
✅ المصدر الأمريكي الأصلي: 9 صف × 20 عمود

📅 تاريخ الفحص: 2026-10-14
🔎 مصدر تاريخ محتمل: wadq_final_report_df | عمود التاريخ: نتيجة فحص التاريخ
🔎 مصدر تاريخ محتمل: wadq_decision_board_df | عمود التاريخ: نتيجة فحص التاريخ
🔎 مصدر تاريخ محتمل: wadq_global_master_report_df | عمود التاريخ: تاريخ آخر بيانات
🔎 مصدر تاريخ محتمل: wadq_global_market_df | عمود التاريخ: تاريخ آخر بيانات

======================================================================
🌧️ نتيجة المرحلة 58
======================================================================

📊 فحص تواريخ الأصول:

,نوع السوق,الرمز,المصدر الأساسي,تاريخ البيانات,عمر البيانات بالأيام,حالة التاريخ
0,أمريكي,NVDA,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
1,أمريكي,TSLA,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
2,أمريكي,AAPL,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
3,أمريكي,MSFT,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
4,أمريكي,AMZN,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
5,أمريكي,GOOGL,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
6,أمريكي,META,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
7,أمريكي,QQQ,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
8,أمريكي,SPY,wadq_final_ai_report,NaT,NaN,⚠️ التاريخ غير متاح — يلزم التحقق من المصدر
9,عالمي,^GSPC,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
10,عالمي,^IXIC,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
11,عالمي,^DJI,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
12,عالمي,^GDAXI,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
13,عالمي,^FCHI,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
14,عالمي,^FTSE,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
15,عالمي,^N225,wadq_global_master_report_df,2026-10-09,5.0,⚠️ بيانات قديمة نسبيًا
16,عالمي,^HSI,wadq_global_master_report_df,2026-10-12,2.0,✅ بيانات حديثة نسبيًا
17,عالمي,GC=F,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
18,عالمي,SI=F,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
19,عالمي,CL=F,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
20,عالمي,BZ=F,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
21,عالمي,NG=F,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
22,عالمي,EURUSD=X,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
23,عالمي,JPY=X,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
24,عالمي,BTC-USD,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا
25,عالمي,ETH-USD,wadq_global_master_report_df,2026-10-13,1.0,✅ بيانات حديثة نسبيًا

📋 ملخص جودة التواريخ:

                 البند        القيمة
0          تاريخ الفحص    2026-10-14
1        إجمالي الأصول            26
2     تواريخ غير متاحة             9
3      تواريخ مستقبلية             0
4  بيانات قديمة نسبيًا             1
5         حالة المرحلة  تحتاج مراجعة

======================================================================
✅ انتهى الفحص الأولي للمرحلة 58
📌 جدول التفاصيل: wadq_stage58_date_quality_df
📌 جدول الملخص: wadq_stage58_summary_df
📌 سجل المراحل: wadq_stage_log_df
🔒 لم يتم تعديل الجداول الأصلية.
⚠️ لم يتم جلب أسعار جديدة في هذه المرحلة.
======================================================================

In [ ]:
# ================================================================
# 🌧️ الودق AI — النظام الشامل
# المراحل 59 إلى 66 في خلية واحدة
# تحديث البيانات، التحليل الفني، التقييم، المخاطر، والتقارير
# ================================================================

import sys
import subprocess
import warnings
import time
from datetime import datetime

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

print("🌧️ الودق AI — بدء المراحل 59 إلى 66")
print("=" * 75)

# ================================================================
# المرحلة 59 — تحديث الأسعار والتحقق من التواريخ
# ================================================================

print("\n🔹 المرحلة 59 — تحديث الأسعار")

try:
    import yfinance as yf
except ImportError:
    print("📦 جارٍ تثبيت مكتبة yfinance...")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-q", "yfinance"]
    )
    import yfinance as yf

# الاحتفاظ بنسخ مستقلة من المصادر الأصلية
us_source = globals().get("wadq_final_ai_report")
global_source = globals().get("wadq_global_master_report_df")

if not isinstance(us_source, pd.DataFrame):
    raise ValueError(
        "المصدر الأمريكي wadq_final_ai_report غير متاح. "
        "توقفي هنا ولا تحذفي الجداول السابقة."
    )

if not isinstance(global_source, pd.DataFrame):
    raise ValueError(
        "المصدر العالمي wadq_global_master_report_df غير متاح."
    )

us_source = us_source.copy(deep=True)
global_source = global_source.copy(deep=True)

def find_col(df, candidates):
    """العثور على أول عمود متاح من قائمة أسماء محتملة."""
    normalized = {
        str(c).strip().lower(): c
        for c in df.columns
    }

    for name in candidates:
        if name.lower() in normalized:
            return normalized[name.lower()]

    for col in df.columns:
        text = str(col).strip().lower()
        for name in candidates:
            if name.lower() in text:
                return col

    return None

us_ticker_col = find_col(
    us_source, ["ticker", "symbol", "الرمز", "رمز السهم"]
)

global_ticker_col = find_col(
    global_source, ["ticker", "symbol", "الرمز", "رمز الأصل"]
)

global_name_col = find_col(
    global_source, ["الأصل", "اسم الأصل", "asset", "name"]
)

if us_ticker_col is None or global_ticker_col is None:
    raise ValueError(
        "تعذر تحديد عمود الرموز. "
        "لم يتم تعديل الجداول الأصلية."
    )

# إعداد قائمة الأصول
assets = {}

for _, row in us_source.iterrows():
    ticker = str(row[us_ticker_col]).strip().upper()

    if ticker and ticker != "NAN":
        assets[ticker] = {
            "market": "أمريكي",
            "name": str(row.get("السهم", ticker)),
            "old_row": row.to_dict(),
        }

for _, row in global_source.iterrows():
    ticker = str(row[global_ticker_col]).strip().upper()

    if ticker and ticker != "NAN":
        if ticker not in assets:
            name = (
                row[global_name_col]
                if global_name_col is not None
                else ticker
            )

            assets[ticker] = {
                "market": "عالمي",
                "name": str(name),
                "old_row": row.to_dict(),
            }

tickers = list(assets.keys())

print(f"📊 عدد الأصول المطلوب تحديثها: {len(tickers)}")

# محاولة جلب بيانات تاريخية لآخر 6 أشهر
price_data = {}
download_errors = {}

try:
    downloaded = yf.download(
        tickers=tickers,
        period="6mo",
        interval="1d",
        auto_adjust=True,
        group_by="ticker",
        progress=False,
        threads=True,
        timeout=30,
    )

    for ticker in tickers:
        try:
            if downloaded is None or downloaded.empty:
                raise ValueError("مصدر البيانات لم يرجع أسعارًا")

            if isinstance(downloaded.columns, pd.MultiIndex):
                if ticker not in downloaded.columns.get_level_values(0):
                    raise ValueError("لم تُرجع البيانات لهذا الرمز")

                hist = downloaded[ticker].copy()

            else:
                if len(tickers) != 1:
                    raise ValueError("تعذر تحديد أعمدة الرمز")

                hist = downloaded.copy()

            if "Close" not in hist.columns:
                raise ValueError("عمود الإغلاق غير متاح")

            hist = hist.dropna(subset=["Close"])

            if hist.empty:
                raise ValueError("لا توجد أسعار إغلاق صالحة")

            price_data[ticker] = hist

        except Exception as exc:
            download_errors[ticker] = str(exc)

except Exception as exc:
    download_errors["ALL"] = str(exc)

    print("⚠️ تعذر الاتصال بمصدر الأسعار:")
    print(str(exc)[:400])

print(f"✅ أصول جرى جلب بياناتها: {len(price_data)}")
print(f"⚠️ أصول تعذر جلب بياناتها: {len(download_errors)}")

# ================================================================
# المرحلة 60 — جودة البيانات والتواريخ
# ================================================================

print("\n🔹 المرحلة 60 — فحص جودة البيانات")

now = pd.Timestamp.now(tz="UTC")
quality_records = []
market_records = []

def calculate_rsi(close, period=14):
    delta = close.diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(
        alpha=1 / period,
        min_periods=period,
        adjust=False
    ).mean()

    avg_loss = loss.ewm(
        alpha=1 / period,
        min_periods=period,
        adjust=False
    ).mean()

    rs = avg_gain / avg_loss.replace(0, np.nan)
    rsi = 100 - (100 / (1 + rs))

    rsi = rsi.mask(
        (avg_loss == 0) & (avg_gain > 0), 100
    )

    return rsi

def calculate_indicators(hist):
    hist = hist.copy()

    close = pd.to_numeric(
        hist["Close"], errors="coerce"
    ).dropna()

    if len(close) < 2:
        raise ValueError("عدد الأسعار غير كافٍ")

    hist = hist.loc[close.index].copy()
    close = hist["Close"]

    hist["SMA20"] = close.rolling(20).mean()
    hist["SMA50"] = close.rolling(50).mean()
    hist["RSI14"] = calculate_rsi(close)

    ema12 = close.ewm(
        span=12, adjust=False
    ).mean()

    ema26 = close.ewm(
        span=26, adjust=False
    ).mean()

    hist["MACD"] = ema12 - ema26

    hist["MACD_signal"] = hist["MACD"].ewm(
        span=9, adjust=False
    ).mean()

    previous_close = close.shift(1)

    if "High" in hist.columns and "Low" in hist.columns:
        true_range = pd.concat(
            [
                hist["High"] - hist["Low"],
                (hist["High"] - previous_close).abs(),
                (hist["Low"] - previous_close).abs(),
            ],
            axis=1
        ).max(axis=1)

        hist["ATR14"] = true_range.rolling(14).mean()

    else:
        hist["ATR14"] = np.nan

    return hist

indicator_data = {}

for ticker, hist in price_data.items():
    try:
        enriched = calculate_indicators(hist)
        indicator_data[ticker] = enriched

        valid = enriched.dropna(subset=["Close"])

        last = valid.iloc[-1]
        last_index = valid.index[-1]

        date_value = pd.Timestamp(last_index)

        if date_value.tzinfo is None:
            date_value = date_value.tz_localize("UTC")
        else:
            date_value = date_value.tz_convert("UTC")

        age_hours = (
            now - date_value
        ).total_seconds() / 3600

        close = float(last["Close"])
        previous = (
            float(valid["Close"].iloc[-2])
            if len(valid) >= 2 else np.nan
        )

        change_pct = (
            (close / previous - 1) * 100
            if pd.notna(previous) and previous != 0
            else np.nan
        )

        if close <= 0:
            price_status = "سعر غير صالح"
        elif age_hours < -24:
            price_status = "تاريخ مستقبلي يحتاج مراجعة"
        elif age_hours <= 36:
            price_status = "حديث زمنيًا"
        elif age_hours <= 120:
            price_status = "قد يكون بسبب عطلة السوق"
        else:
            price_status = "قديم — يلزم مراجعة"

        quality_records.append({
            "الرمز": ticker,
            "السوق": assets[ticker]["market"],
            "تاريخ آخر سعر": str(date_value.date()),
            "عمر البيانات بالساعات": round(age_hours, 2),
            "السعر": close,
            "حالة السعر": price_status,
            "عدد المشاهدات التاريخية": len(valid),
        })

        market_records.append({
            "الرمز": ticker,
            "الأصل": assets[ticker]["name"],
            "السوق": assets[ticker]["market"],
            "السعر السابق": previous,
            "أحدث إغلاق": close,
            "التغير اليومي %": change_pct,
            "تاريخ آخر بيانات": str(date_value.date()),
            "حالة البيانات": price_status,
            "RSI": last.get("RSI14", np.nan),
            "SMA20": last.get("SMA20", np.nan),
            "SMA50": last.get("SMA50", np.nan),
            "MACD": last.get("MACD", np.nan),
            "MACD Signal": last.get("MACD_signal", np.nan),
            "ATR14": last.get("ATR14", np.nan),
        })

    except Exception as exc:
        quality_records.append({
            "الرمز": ticker,
            "السوق": assets[ticker]["market"],
            "تاريخ آخر سعر": None,
            "عمر البيانات بالساعات": np.nan,
            "السعر": np.nan,
            "حالة السعر": "تعذر التحقق",
            "عدد المشاهدات التاريخية": 0,
        })

        print(f"⚠️ {ticker}: {str(exc)[:150]}")

wadq_stage60_quality_df = pd.DataFrame(quality_records)
wadq_stage60_market_df = pd.DataFrame(market_records)

# ================================================================
# المرحلة 61 — تقييم الفرص الاستثمارية
# ================================================================

print("\n🔹 المرحلة 61 — تقييم الفرص")

opportunity_records = []

for _, row in wadq_stage60_market_df.iterrows():

    score = 0
    reasons = []

    price = row["أحدث إغلاق"]
    sma20 = row["SMA20"]
    sma50 = row["SMA50"]
    rsi = row["RSI"]
    macd = row["MACD"]
    signal = row["MACD Signal"]

    if pd.notna(price) and pd.notna(sma20):
        if price > sma20:
            score += 1
            reasons.append("السعر أعلى من متوسط 20")

    if pd.notna(sma20) and pd.notna(sma50):
        if sma20 > sma50:
            score += 1
            reasons.append("متوسط 20 أعلى من متوسط 50")

    if pd.notna(rsi):
        if 50 <= rsi < 70:
            score += 1
            reasons.append("RSI داعم نسبيًا")
        elif rsi >= 70:
            reasons.append("احتمال تشبع شرائي")
        elif rsi < 30:
            reasons.append("احتمال تشبع بيعي")

    if pd.notna(macd) and pd.notna(signal):
        if macd > signal:
            score += 1
            reasons.append("MACD أعلى من خط الإشارة")

    if "حديث زمنيًا" not in str(row["حالة البيانات"]):
        recommendation = "البيانات تحتاج تحققًا"
    elif score >= 3:
        recommendation = "إيجابي فنيًا — يحتاج تحققًا"
    elif score == 2:
        recommendation = "مختلط — يحتاج متابعة"
    else:
        recommendation = "إشارة غير كافية"

    opportunity_records.append({
        "الرمز": row["الرمز"],
        "الأصل": row["الأصل"],
        "السوق": row["السوق"],
        "السعر": price,
        "التغير اليومي %": row["التغير اليومي %"],
        "RSI": rsi,
        "MACD": macd,
        "درجة فنية أولية": score,
        "أسباب التقييم": "؛ ".join(reasons),
        "التقييم الأولي": recommendation,
        "تاريخ البيانات": row["تاريخ آخر بيانات"],
        "حالة البيانات": row["حالة البيانات"],
    })

wadq_stage61_opportunities_df = pd.DataFrame(
    opportunity_records
)

if not wadq_stage61_opportunities_df.empty:
    wadq_stage61_opportunities_df = (
        wadq_stage61_opportunities_df.sort_values(
            "درجة فنية أولية",
            ascending=False
        ).reset_index(drop=True)
    )

# ================================================================
# المرحلة 62 — مستويات فنية استرشادية
# ================================================================

print("\n🔹 المرحلة 62 — مستويات فنية استرشادية")

levels_records = []

for _, row in wadq_stage60_market_df.iterrows():

    price = row["أحدث إغلاق"]
    atr = row["ATR14"]

    if (
        pd.notna(price)
        and price > 0
        and pd.notna(atr)
        and atr > 0
        and "حديث زمنيًا" in str(row["حالة البيانات"])
    ):
        stop = price - 2 * atr
        target1 = price + 2 * atr
        target2 = price + 3 * atr

        level_status = "مستويات حسابية استرشادية"

    else:
        stop = np.nan
        target1 = np.nan
        target2 = np.nan

        level_status = "لا توجد بيانات كافية لحساب المستويات"

    levels_records.append({
        "الرمز": row["الرمز"],
        "السعر المرجعي": price,
        "وقف خسارة استرشادي": stop,
        "هدف استرشادي 1": target1,
        "هدف استرشادي 2": target2,
        "ATR14": atr,
        "حالة المستويات": level_status,
    })

wadq_stage62_levels_df = pd.DataFrame(levels_records)

# ================================================================
# المرحلة 63 — إدارة المخاطر
# ================================================================

print("\n🔹 المرحلة 63 — إدارة المخاطر")

# رأس المال الافتراضي بالريال السعودي.
# غيّري الرقم إذا أردتِ دراسة رأس مال مختلف.
CAPITAL_SAR = 100.0

# نسبة المخاطرة الافتراضية لكل صفقة
RISK_PERCENT = 1.0

risk_budget = CAPITAL_SAR * RISK_PERCENT / 100

risk_records = []

for _, row in wadq_stage62_levels_df.iterrows():

    price = row["السعر المرجعي"]
    stop = row["وقف خسارة استرشادي"]

    if (
        pd.notna(price)
        and pd.notna(stop)
        and price > stop > 0
    ):
        risk_per_unit = price - stop

        quantity = (
            risk_budget / risk_per_unit
            if risk_per_unit > 0
            else 0
        )

        quantity = max(0, quantity)

        capital_needed = quantity * price

        status = (
            "حساب نظري — راعي العملة والعمولات"
        )

    else:
        risk_per_unit = np.nan
        quantity = np.nan
        capital_needed = np.nan

        status = "لا يمكن الحساب دون بيانات صالحة"

    risk_records.append({
        "الرمز": row["الرمز"],
        "رأس المال الافتراضي بالريال": CAPITAL_SAR,
        "ميزانية المخاطرة بالريال": risk_budget,
        "المخاطرة لكل وحدة بعملة الأصل": risk_per_unit,
        "الكمية النظرية": quantity,
        "القيمة النظرية بعملة الأصل": capital_needed,
        "الحالة": status,
    })

wadq_stage63_risk_df = pd.DataFrame(risk_records)

# ================================================================
# المرحلة 64 — تقرير الأسعار الموحد
# ================================================================

print("\n🔹 المرحلة 64 — التقرير الموحد")

wadq_stage64_unified_df = (
    wadq_stage60_market_df.merge(
        wadq_stage61_opportunities_df[
            [
                "الرمز",
                "درجة فنية أولية",
                "أسباب التقييم",
                "التقييم الأولي",
            ]
        ],
        on="الرمز",
        how="left"
    )
)

wadq_stage64_unified_df = (
    wadq_stage64_unified_df.merge(
        wadq_stage62_levels_df.drop(
            columns=["السعر المرجعي", "ATR14"],
            errors="ignore"
        ),
        on="الرمز",
        how="left"
    )
)

wadq_stage64_unified_df = (
    wadq_stage64_unified_df.merge(
        wadq_stage63_risk_df[
            [
                "الرمز",
                "ميزانية المخاطرة بالريال",
                "الكمية النظرية",
                "الحالة",
            ]
        ].rename(columns={"الحالة": "حالة حساب المخاطر"}),
        on="الرمز",
        how="left"
    )
)

# ================================================================
# المرحلة 65 — اختبارات الجودة وسجل المراحل
# ================================================================

print("\n🔹 المرحلة 65 — اختبارات الجودة")

quality_tests = []

def add_test(name, passed, details):
    quality_tests.append({
        "الفحص": name,
        "النتيجة": "ناجح" if passed else "يحتاج مراجعة",
        "التفاصيل": details,
    })

add_test(
    "وجود بيانات أسعار",
    not wadq_stage60_market_df.empty,
    f"عدد الأصول: {len(wadq_stage60_market_df)}"
)

add_test(
    "توفر الرموز",
    wadq_stage60_market_df["الرمز"].notna().all()
    if not wadq_stage60_market_df.empty else False,
    "فحص رموز الأصول"
)

add_test(
    "الأسعار موجبة",
    (
        (wadq_stage60_market_df["أحدث إغلاق"] > 0).all()
        if not wadq_stage60_market_df.empty else False
    ),
    "الأسعار التي جرى جلبها فقط"
)

future_count = 0

if not wadq_stage60_quality_df.empty:
    future_count = (
        wadq_stage60_quality_df["حالة السعر"]
        .astype(str)
        .str.contains("مستقبلي", na=False)
        .sum()
    )

add_test(
    "التواريخ المستقبلية",
    future_count == 0,
    f"عدد الحالات: {future_count}"
)

wadq_stage65_quality_report_df = pd.DataFrame(
    quality_tests
)

# ================================================================
# المرحلة 66 — التقرير النهائي
# ================================================================

print("\n🔹 المرحلة 66 — إنشاء التقرير النهائي")

wadq_stage66_final_report_df = wadq_stage64_unified_df.copy()

run_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

wadq_stage66_summary_df = pd.DataFrame([
    {
        "البند": "وقت التنفيذ",
        "القيمة": run_time
    },
    {
        "البند": "عدد الأصول المطلوبة",
        "القيمة": len(tickers)
    },
    {
        "البند": "عدد الأصول التي جرى تحديثها",
        "القيمة": len(price_data)
    },
    {
        "البند": "عدد الأصول في التقرير النهائي",
        "القيمة": len(wadq_stage66_final_report_df)
    },
    {
        "البند": "عدد اختبارات الجودة",
        "القيمة": len(wadq_stage65_quality_report_df)
    },
    {
        "البند": "عدد اختبارات الجودة التي تحتاج مراجعة",
        "القيمة": int(
            (
                wadq_stage65_quality_report_df["النتيجة"]
                == "يحتاج مراجعة"
            ).sum()
        )
    },
])

# سجل مستقل للمراحل 59 إلى 66
stage_rows = []

stage_descriptions = [
    (59, "تحديث الأسعار", f"بيانات متاحة لـ {len(price_data)} أصل"),
    (60, "جودة البيانات", f"فحص {len(wadq_stage60_quality_df)} أصل"),
    (61, "تقييم الفرص", f"تقييم {len(wadq_stage61_opportunities_df)} أصل"),
    (62, "المستويات الفنية", "مستويات استرشادية بحسب البيانات المتاحة"),
    (63, "إدارة المخاطر", f"رأس مال افتراضي {CAPITAL_SAR} ريال"),
    (64, "التقرير الموحد", "دمج نتائج التحليل والمخاطر"),
    (65, "اختبارات الجودة", f"عدد الاختبارات {len(quality_tests)}"),
    (66, "التقرير النهائي", "إنشاء التقرير والملخص"),
]

for number, name, details in stage_descriptions:
    stage_rows.append({
        "المرحلة": f"{number} — {name}",
        "الحالة": "اكتمل التنفيذ البرمجي",
        "التفاصيل": details,
        "وقت التنفيذ": run_time,
    })

wadq_stage59_66_log_df = pd.DataFrame(stage_rows)

# حفظ السجل في متغير جديد دون تغيير سجل المراحل السابق
wadq_stage_log_59_66_df = wadq_stage59_66_log_df.copy()

# ================================================================
# عرض النتائج
# ================================================================

print("\n" + "=" * 75)
print("🌧️ الودق AI — اكتمل تشغيل الخلية الشاملة")
print("=" * 75)

print("\n📊 ملخص النظام:")
display(wadq_stage66_summary_df)

print("\n💹 معاينة التقرير الموحد:")
display(wadq_stage66_final_report_df.head(30))

print("\n📅 جودة الأسعار والتواريخ:")
display(wadq_stage60_quality_df)

print("\n🎯 ترتيب الفرص الفنية الأولي:")
display(wadq_stage61_opportunities_df)

print("\n🛡️ مستويات إدارة المخاطر:")
display(wadq_stage63_risk_df)

print("\n🔎 اختبارات الجودة:")
display(wadq_stage65_quality_report_df)

print("\n📋 سجل المراحل:")
display(wadq_stage59_66_log_df)

print("\n" + "=" * 75)
print("📌 الجداول الناتجة:")
print("1. wadq_stage60_quality_df")
print("2. wadq_stage60_market_df")
print("3. wadq_stage61_opportunities_df")
print("4. wadq_stage62_levels_df")
print("5. wadq_stage63_risk_df")
print("6. wadq_stage64_unified_df")
print("7. wadq_stage65_quality_report_df")
print("8. wadq_stage66_final_report_df")
print("9. wadq_stage66_summary_df")
print("10. wadq_stage59_66_log_df")
print("=" * 75)

print("🔒 لم يتم تعديل الجداول الأصلية عمدًا.")
print("⚠️ النتائج ليست توصيات شراء أو ضمانًا للربح.")
print("⚠️ المستويات الفنية حسابات استرشادية وليست إشارات تنفيذ.")
print("⚠️ تأكدي من تاريخ الأسعار وعملة الأصل والعمولات قبل أي قرار.")

🌧️ الودق AI — بدء المراحل 59 إلى 66
===========================================================================

🔹 المرحلة 59 — تحديث الأسعار
📊 عدد الأصول المطلوب تحديثها: 26
✅ أصول جرى جلب بياناتها: 26
⚠️ أصول تعذر جلب بياناتها: 0

🔹 المرحلة 60 — فحص جودة البيانات

🔹 المرحلة 61 — تقييم الفرص

🔹 المرحلة 62 — مستويات فنية استرشادية

🔹 المرحلة 63 — إدارة المخاطر

🔹 المرحلة 64 — التقرير الموحد

🔹 المرحلة 65 — اختبارات الجودة

🔹 المرحلة 66 — إنشاء التقرير النهائي

===========================================================================
🌧️ الودق AI — اكتمل تشغيل الخلية الشاملة
===========================================================================

📊 ملخص النظام:

                                   البند               القيمة
0                            وقت التنفيذ  2026-10-14 00:03:24
1                    عدد الأصول المطلوبة                   26
2            عدد الأصول التي جرى تحديثها                   26
3          عدد الأصول في التقرير النهائي                   26
4                    عدد اختبارات الجودة                    4
5  عدد اختبارات الجودة التي تحتاج مراجعة                    0

💹 معاينة التقرير الموحد:

,الرمز,الأصل,السوق,السعر السابق,أحدث إغلاق,التغير اليومي %,تاريخ آخر بيانات,حالة البيانات,RSI,SMA20,...,درجة فنية أولية,أسباب التقييم,التقييم الأولي,وقف خسارة استرشادي,هدف استرشادي 1,هدف استرشادي 2,حالة المستويات,ميزانية المخاطرة بالريال,الكمية النظرية,حالة حساب المخاطر
0,NVDA,إنفيديا,أمريكي,229.279999,226.320007,-1.290994,2026-10-12,قد يكون بسبب عطلة السوق,49.410859,227.502000,...,1,متوسط 20 أعلى من متوسط 50,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
1,TSLA,تسلا,أمريكي,382.700012,378.029999,-1.220280,2026-10-12,قد يكون بسبب عطلة السوق,56.467198,369.612497,...,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
2,AAPL,آبل,أمريكي,336.640015,340.970001,1.286236,2026-10-12,قد يكون بسبب عطلة السوق,60.229951,335.783504,...,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
3,MSFT,مايكروسوفت,أمريكي,535.070007,541.150024,1.136303,2026-10-12,قد يكون بسبب عطلة السوق,69.919740,511.886499,...,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
4,AMZN,أمازون,أمريكي,262.429993,259.529999,-1.105054,2026-10-12,قد يكون بسبب عطلة السوق,55.573637,252.319001,...,3,السعر أعلى من متوسط 20؛ RSI داعم نسبيًا؛ MACD ...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
5,GOOGL,ألفابت,أمريكي,351.660004,352.720001,0.301427,2026-10-12,قد يكون بسبب عطلة السوق,57.292530,346.088499,...,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
6,META,ميتا,أمريكي,718.669983,742.960022,3.379860,2026-10-12,قد يكون بسبب عطلة السوق,62.312773,722.944876,...,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
7,QQQ,ناسداك 100,أمريكي,751.270020,746.039978,-0.696160,2026-10-12,قد يكون بسبب عطلة السوق,56.717787,739.236288,...,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
8,SPY,ستاندرد آند بورز 500,أمريكي,778.570007,778.099976,-0.060371,2026-10-12,قد يكون بسبب عطلة السوق,59.918979,768.556354,...,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
9,^GSPC,S&P 500 - أمريكا,عالمي,7807.240234,7805.450195,-0.022928,2026-10-13,حديث زمنيًا,59.199982,7725.123047,...,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,7685.150181,7925.750209,7985.900216,مستويات حسابية استرشادية,1.0,0.008313,حساب نظري — راعي العملة والعمولات
10,^IXIC,Nasdaq Composite - أمريكا,عالمي,27245.900391,27204.380859,-0.152388,2026-10-13,حديث زمنيًا,56.396250,27019.839355,...,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,26633.570312,27775.191406,28060.596680,مستويات حسابية استرشادية,1.0,0.001752,حساب نظري — راعي العملة والعمولات
11,^DJI,Dow Jones - أمريكا,عالمي,51850.550781,51670.101562,-0.348018,2026-10-13,حديث زمنيًا,48.170673,51487.129297,...,2,السعر أعلى من متوسط 20؛ MACD أعلى من خط الإشارة,مختلط — يحتاج متابعة,50703.177455,52637.025670,53120.487723,مستويات حسابية استرشادية,1.0,0.001034,حساب نظري — راعي العملة والعمولات
12,^GDAXI,DAX - ألمانيا,عالمي,25087.269531,25277.679688,0.758991,2026-10-12,قد يكون بسبب عطلة السوق,47.543511,25316.175488,...,0,,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
13,^FCHI,CAC 40 - فرنسا,عالمي,7803.330078,7832.879883,0.378682,2026-10-12,قد يكون بسبب عطلة السوق,36.053026,7985.247485,...,0,,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
14,^FTSE,FTSE 100 - بريطانيا,عالمي,10552.099609,10656.299805,0.987483,2026-10-12,قد يكون بسبب عطلة السوق,52.163674,10615.784912,...,3,السعر أعلى من متوسط 20؛ RSI داعم نسبيًا؛ MACD ...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
15,^N225,Nikkei 225 - اليابان,عالمي,69042.109375,69030.921875,-0.016204,2026-10-09,قديم — يلزم مراجعة,59.799746,66523.845703,...,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
16,^HSI,Hang Seng - هونغ كونغ,عالمي,24211.349609,24271.199219,0.247197,2026-10-12,قد يكون بسبب عطلة السوق,43.506278,24518.043262,...,0,,البيانات تحتاج تحققًا,NaN,NaN,NaN,لا توجد بيانات كافية لحساب المستويات,1.0,NaN,لا يمكن الحساب دون بيانات صالحة
17,GC=F,الذهب,عالمي,4190.600098,4180.100098,-0.250561,2026-10-13,حديث زمنيًا,40.498891,4251.900000,...,0,,إشارة غير كافية,4031.771589,4328.428606,4402.592861,مستويات حسابية استرشادية,1.0,0.006742,حساب نظري — راعي العملة والعمولات
18,SI=F,الفضة,عالمي,60.140999,59.230000,-1.514772,2026-10-13,حديث زمنيًا,38.743611,62.194200,...,0,,إشارة غير كافية,56.764713,61.695286,62.927930,مستويات حسابية استرشادية,1.0,0.405632,حساب نظري — راعي العملة والعمولات
19,CL=F,النفط الأمريكي,عالمي,93.739998,94.860001,1.194797,2026-10-13,حديث زمنيًا,55.803750,93.483000,...,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,86.840001,102.880001,106.890000,مستويات حسابية استرشادية,1.0,0.124688,حساب نظري — راعي العملة والعمولات
20,BZ=F,نفط برنت,عالمي,106.650002,106.389999,-0.243790,2026-10-13,حديث زمنيًا,60.613724,103.360500,...,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,98.014283,114.765715,118.953573,مستويات حسابية استرشادية,1.0,0.119393,حساب نظري — راعي العملة والعمولات
21,NG=F,الغاز الطبيعي,عالمي,3.167000,3.318000,4.767920,2026-10-13,حديث زمنيًا,65.082877,3.065800,...,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,3.012000,3.624000,3.777000,مستويات حسابية استرشادية,1.0,3.267973,حساب نظري — راعي العملة والعمولات
22,EURUSD=X,اليورو مقابل الدولار,عالمي,1.116022,1.120197,0.374145,2026-10-14,حديث زمنيًا,29.025016,1.132349,...,0,احتمال تشبع بيعي,إشارة غير كافية,1.106583,1.133811,1.140618,مستويات حسابية استرشادية,1.0,73.454125,حساب نظري — راعي العملة والعمولات
23,JPY=X,الدولار مقابل الين,عالمي,158.520004,158.326004,-0.122382,2026-10-14,حديث زمنيًا,55.698554,157.698801,...,3,السعر أعلى من متوسط 20؛ RSI داعم نسبيًا؛ MACD ...,إيجابي فنيًا — يحتاج تحققًا,156.447867,160.204141,161.143209,مستويات حسابية استرشادية,1.0,0.532443,حساب نظري — راعي العملة والعمولات
24,BTC-USD,بيتكوين,عالمي,81762.562500,83166.648438,1.717272,2026-10-14,حديث زمنيًا,52.104466,83945.762891,...,2,متوسط 20 أعلى من متوسط 50؛ RSI داعم نسبيًا,مختلط — يحتاج متابعة,78952.142857,87381.154018,89488.406808,مستويات حسابية استرشادية,1.0,0.000237,حساب نظري — راعي العملة والعمولات
25,ETH-USD,إيثيريوم,عالمي,2444.357422,2498.360107,2.209279,2026-10-14,حديث زمنيًا,43.271659,2625.870544,...,1,متوسط 20 أعلى من متوسط 50,إشارة غير كافية,2334.696638,2662.023577,2743.855312,مستويات حسابية استرشادية,1.0,0.006110,حساب نظري — راعي العملة والعمولات

📅 جودة الأسعار والتواريخ:

,الرمز,السوق,تاريخ آخر سعر,عمر البيانات بالساعات,السعر,حالة السعر,عدد المشاهدات التاريخية
0,NVDA,أمريكي,2026-10-12,48.06,226.320007,قد يكون بسبب عطلة السوق,126
1,TSLA,أمريكي,2026-10-12,48.06,378.029999,قد يكون بسبب عطلة السوق,126
2,AAPL,أمريكي,2026-10-12,48.06,340.970001,قد يكون بسبب عطلة السوق,126
3,MSFT,أمريكي,2026-10-12,48.06,541.150024,قد يكون بسبب عطلة السوق,126
4,AMZN,أمريكي,2026-10-12,48.06,259.529999,قد يكون بسبب عطلة السوق,126
5,GOOGL,أمريكي,2026-10-12,48.06,352.720001,قد يكون بسبب عطلة السوق,126
6,META,أمريكي,2026-10-12,48.06,742.960022,قد يكون بسبب عطلة السوق,126
7,QQQ,أمريكي,2026-10-12,48.06,746.039978,قد يكون بسبب عطلة السوق,126
8,SPY,أمريكي,2026-10-12,48.06,778.099976,قد يكون بسبب عطلة السوق,126
9,^GSPC,عالمي,2026-10-13,24.06,7805.450195,حديث زمنيًا,127
10,^IXIC,عالمي,2026-10-13,24.06,27204.380859,حديث زمنيًا,127
11,^DJI,عالمي,2026-10-13,24.06,51670.101562,حديث زمنيًا,127
12,^GDAXI,عالمي,2026-10-12,48.06,25277.679688,قد يكون بسبب عطلة السوق,130
13,^FCHI,عالمي,2026-10-12,48.06,7832.879883,قد يكون بسبب عطلة السوق,130
14,^FTSE,عالمي,2026-10-12,48.06,10656.299805,قد يكون بسبب عطلة السوق,128
15,^N225,عالمي,2026-10-09,120.06,69030.921875,قديم — يلزم مراجعة,120
16,^HSI,عالمي,2026-10-12,48.06,24271.199219,قد يكون بسبب عطلة السوق,126
17,GC=F,عالمي,2026-10-13,24.06,4180.100098,حديث زمنيًا,128
18,SI=F,عالمي,2026-10-13,24.06,59.230000,حديث زمنيًا,128
19,CL=F,عالمي,2026-10-13,24.06,94.860001,حديث زمنيًا,128
20,BZ=F,عالمي,2026-10-13,24.06,106.389999,حديث زمنيًا,128
21,NG=F,عالمي,2026-10-13,24.06,3.318000,حديث زمنيًا,128
22,EURUSD=X,عالمي,2026-10-14,0.06,1.120197,حديث زمنيًا,132
23,JPY=X,عالمي,2026-10-14,0.06,158.326004,حديث زمنيًا,132
24,BTC-USD,عالمي,2026-10-14,0.06,83166.648438,حديث زمنيًا,183
25,ETH-USD,عالمي,2026-10-14,0.06,2498.360107,حديث زمنيًا,183

🎯 ترتيب الفرص الفنية الأولي:

,الرمز,الأصل,السوق,السعر,التغير اليومي %,RSI,MACD,درجة فنية أولية,أسباب التقييم,التقييم الأولي,تاريخ البيانات,حالة البيانات
0,TSLA,تسلا,أمريكي,378.029999,-1.220280,56.467198,5.143887,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
1,MSFT,مايكروسوفت,أمريكي,541.150024,1.136303,69.919740,11.618712,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
2,^GSPC,S&P 500 - أمريكا,عالمي,7805.450195,-0.022928,59.199982,37.796257,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,2026-10-13,حديث زمنيًا
3,GOOGL,ألفابت,أمريكي,352.720001,0.301427,57.292530,1.684420,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
4,SPY,ستاندرد آند بورز 500,أمريكي,778.099976,-0.060371,59.918979,3.876383,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
5,QQQ,ناسداك 100,أمريكي,746.039978,-0.696160,56.717787,9.001081,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
6,NG=F,الغاز الطبيعي,عالمي,3.318000,4.767920,65.082877,0.085403,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,2026-10-13,حديث زمنيًا
7,^N225,Nikkei 225 - اليابان,عالمي,69030.921875,-0.016204,59.799746,1094.992036,4,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,2026-10-09,قديم — يلزم مراجعة
8,AMZN,أمازون,أمريكي,259.529999,-1.105054,55.573637,0.756399,3,السعر أعلى من متوسط 20؛ RSI داعم نسبيًا؛ MACD ...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
9,AAPL,آبل,أمريكي,340.970001,1.286236,60.229951,3.645672,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
10,JPY=X,الدولار مقابل الين,عالمي,158.326004,-0.122382,55.698554,0.257419,3,السعر أعلى من متوسط 20؛ RSI داعم نسبيًا؛ MACD ...,إيجابي فنيًا — يحتاج تحققًا,2026-10-14,حديث زمنيًا
11,META,ميتا,أمريكي,742.960022,3.379860,62.312773,24.896398,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
12,^FTSE,FTSE 100 - بريطانيا,عالمي,10656.299805,0.987483,52.163674,-54.872628,3,السعر أعلى من متوسط 20؛ RSI داعم نسبيًا؛ MACD ...,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
13,^IXIC,Nasdaq Composite - أمريكا,عالمي,27204.380859,-0.152388,56.396250,245.477816,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,2026-10-13,حديث زمنيًا
14,CL=F,النفط الأمريكي,عالمي,94.860001,1.194797,55.803750,0.155887,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,2026-10-13,حديث زمنيًا
15,BZ=F,نفط برنت,عالمي,106.389999,-0.243790,60.613724,1.888417,3,السعر أعلى من متوسط 20؛ متوسط 20 أعلى من متوسط...,إيجابي فنيًا — يحتاج تحققًا,2026-10-13,حديث زمنيًا
16,BTC-USD,بيتكوين,عالمي,83166.648438,1.717272,52.104466,632.098837,2,متوسط 20 أعلى من متوسط 50؛ RSI داعم نسبيًا,مختلط — يحتاج متابعة,2026-10-14,حديث زمنيًا
17,^DJI,Dow Jones - أمريكا,عالمي,51670.101562,-0.348018,48.170673,-253.082638,2,السعر أعلى من متوسط 20؛ MACD أعلى من خط الإشارة,مختلط — يحتاج متابعة,2026-10-13,حديث زمنيًا
18,NVDA,إنفيديا,أمريكي,226.320007,-1.290994,49.410859,3.313420,1,متوسط 20 أعلى من متوسط 50,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
19,ETH-USD,إيثيريوم,عالمي,2498.360107,2.209279,43.271659,-17.817527,1,متوسط 20 أعلى من متوسط 50,إشارة غير كافية,2026-10-14,حديث زمنيًا
20,^GDAXI,DAX - ألمانيا,عالمي,25277.679688,0.758991,47.543511,-167.336484,0,,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
21,^FCHI,CAC 40 - فرنسا,عالمي,7832.879883,0.378682,36.053026,-129.412695,0,,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
22,GC=F,الذهب,عالمي,4180.100098,-0.250561,40.498891,-59.218729,0,,إشارة غير كافية,2026-10-13,حديث زمنيًا
23,^HSI,Hang Seng - هونغ كونغ,عالمي,24271.199219,0.247197,43.506278,-280.766738,0,,البيانات تحتاج تحققًا,2026-10-12,قد يكون بسبب عطلة السوق
24,SI=F,الفضة,عالمي,59.230000,-1.514772,38.743611,-1.363697,0,,إشارة غير كافية,2026-10-13,حديث زمنيًا
25,EURUSD=X,اليورو مقابل الدولار,عالمي,1.120197,0.374145,29.025016,-0.009191,0,احتمال تشبع بيعي,إشارة غير كافية,2026-10-14,حديث زمنيًا

🛡️ مستويات إدارة المخاطر:

,الرمز,رأس المال الافتراضي بالريال,ميزانية المخاطرة بالريال,المخاطرة لكل وحدة بعملة الأصل,الكمية النظرية,القيمة النظرية بعملة الأصل,الحالة
0,NVDA,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
1,TSLA,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
2,AAPL,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
3,MSFT,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
4,AMZN,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
5,GOOGL,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
6,META,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
7,QQQ,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
8,SPY,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
9,^GSPC,100.0,1.0,120.300014,0.008313,64.883203,حساب نظري — راعي العملة والعمولات
10,^IXIC,100.0,1.0,570.810547,0.001752,47.659212,حساب نظري — راعي العملة والعمولات
11,^DJI,100.0,1.0,966.924107,0.001034,53.437598,حساب نظري — راعي العملة والعمولات
12,^GDAXI,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
13,^FCHI,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
14,^FTSE,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
15,^N225,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
16,^HSI,100.0,1.0,NaN,NaN,NaN,لا يمكن الحساب دون بيانات صالحة
17,GC=F,100.0,1.0,148.328509,0.006742,28.181367,حساب نظري — راعي العملة والعمولات
18,SI=F,100.0,1.0,2.465287,0.405632,24.025602,حساب نظري — راعي العملة والعمولات
19,CL=F,100.0,1.0,8.020000,0.124688,11.827930,حساب نظري — راعي العملة والعمولات
20,BZ=F,100.0,1.0,8.375716,0.119393,12.702197,حساب نظري — راعي العملة والعمولات
21,NG=F,100.0,1.0,0.306000,3.267973,10.843135,حساب نظري — راعي العملة والعمولات
22,EURUSD=X,100.0,1.0,0.013614,73.454125,82.283104,حساب نظري — راعي العملة والعمولات
23,JPY=X,100.0,1.0,1.878137,0.532443,84.299507,حساب نظري — راعي العملة والعمولات
24,BTC-USD,100.0,1.0,4214.505580,0.000237,19.733429,حساب نظري — راعي العملة والعمولات
25,ETH-USD,100.0,1.0,163.663470,0.006110,15.265228,حساب نظري — راعي العملة والعمولات

🔎 اختبارات الجودة:

                 الفحص النتيجة                    التفاصيل
0    وجود بيانات أسعار    ناجح              عدد الأصول: 26
1          توفر الرموز    ناجح             فحص رموز الأصول
2        الأسعار موجبة    ناجح  الأسعار التي جرى جلبها فقط
3  التواريخ المستقبلية    ناجح              عدد الحالات: 0

📋 سجل المراحل:

,المرحلة,الحالة,التفاصيل,وقت التنفيذ
0,59 — تحديث الأسعار,اكتمل التنفيذ البرمجي,بيانات متاحة لـ 26 أصل,2026-10-14 00:03:24
1,60 — جودة البيانات,اكتمل التنفيذ البرمجي,فحص 26 أصل,2026-10-14 00:03:24
2,61 — تقييم الفرص,اكتمل التنفيذ البرمجي,تقييم 26 أصل,2026-10-14 00:03:24
3,62 — المستويات الفنية,اكتمل التنفيذ البرمجي,مستويات استرشادية بحسب البيانات المتاحة,2026-10-14 00:03:24
4,63 — إدارة المخاطر,اكتمل التنفيذ البرمجي,رأس مال افتراضي 100.0 ريال,2026-10-14 00:03:24
5,64 — التقرير الموحد,اكتمل التنفيذ البرمجي,دمج نتائج التحليل والمخاطر,2026-10-14 00:03:24
6,65 — اختبارات الجودة,اكتمل التنفيذ البرمجي,عدد الاختبارات 4,2026-10-14 00:03:24
7,66 — التقرير النهائي,اكتمل التنفيذ البرمجي,إنشاء التقرير والملخص,2026-10-14 00:03:24

===========================================================================
📌 الجداول الناتجة:
1. wadq_stage60_quality_df
2. wadq_stage60_market_df
3. wadq_stage61_opportunities_df
4. wadq_stage62_levels_df
5. wadq_stage63_risk_df
6. wadq_stage64_unified_df
7. wadq_stage65_quality_report_df
8. wadq_stage66_final_report_df
9. wadq_stage66_summary_df
10. wadq_stage59_66_log_df
===========================================================================
🔒 لم يتم تعديل الجداول الأصلية عمدًا.
⚠️ النتائج ليست توصيات شراء أو ضمانًا للربح.
⚠️ المستويات الفنية حسابات استرشادية وليست إشارات تنفيذ.
⚠️ تأكدي من تاريخ الأسعار وعملة الأصل والعمولات قبل أي قرار.

In [ ]:
# ============================================================
# 🌧️ الودق AI — حفظ احتياطي للجداول
# يحفظ جميع جداول DataFrame الموجودة في الذاكرة
# دون تعديل الجداول الأصلية أو حذفها.
# يستخدم اسم ملف ثابت لتجنب النسخ المتكررة.
# ============================================================

import os
import pickle
import pandas as pd
from datetime import datetime
from google.colab import drive

print("=" * 65)
print("🌧️ الودق AI — بدء الحفظ الاحتياطي")
print("=" * 65)

# 1. الاتصال بـ Google Drive
drive.mount('/content/drive')

# 2. مجلد ثابت للحفظ لتجنب تكرار الملفات
backup_folder = '/content/drive/MyDrive/الودق_AI_نسخة_احتياطية'
os.makedirs(backup_folder, exist_ok=True)

# 3. جمع جداول DataFrame الموجودة في الذاكرة
tables_to_save = {}

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        tables_to_save[name] = obj.copy(deep=True)

if not tables_to_save:
    print("\n⚠️ لم نعثر على جداول DataFrame في الذاكرة.")
    print("لم يُنشأ ملف احتياطي فارغ.")
else:
    # 4. حفظ جميع الجداول في ملف واحد
    # يُستبدل الملف السابق بالاسم نفسه عند إعادة الحفظ
    backup_path = os.path.join(
        backup_folder,
        'wadq_ai_tables_backup.pkl'
    )

    temp_path = backup_path + '.tmp'

    try:
        with open(temp_path, 'wb') as f:
            pickle.dump(
                tables_to_save,
                f,
                protocol=pickle.HIGHEST_PROTOCOL
            )

        os.replace(temp_path, backup_path)

        # 5. إنشاء قائمة بأسماء الجداول وأحجامها
        inventory = pd.DataFrame([
            {
                'اسم الجدول': name,
                'عدد الصفوف': len(df),
                'عدد الأعمدة': len(df.columns),
                'الأعمدة': ' | '.join(map(str, df.columns))
            }
            for name, df in tables_to_save.items()
        ])

        inventory_path = os.path.join(
            backup_folder,
            'wadq_ai_tables_inventory.csv'
        )

        inventory.to_csv(
            inventory_path,
            index=False,
            encoding='utf-8-sig'
        )

        print("\n✅ اكتمل حفظ الجداول بنجاح.")
        print("📊 عدد الجداول المحفوظة:", len(tables_to_save))
        print("📁 مجلد الحفظ:", backup_folder)
        print("💾 ملف الجداول:", backup_path)
        print("📋 فهرس الجداول:", inventory_path)
        print("\n📊 ملخص الجداول:")
        display(inventory[
            ['اسم الجدول', 'عدد الصفوف', 'عدد الأعمدة']
        ])

        print("\n🔒 لم تُحذف أو تُعدّل الجداول الأصلية.")
        print("⚠️ احتفظي بملف PKL؛ فهو يحتوي على البيانات اللازمة للاستعادة.")

    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)

print("\n🌧️ انتهى كود الحفظ.")

=================================================================
🌧️ الودق AI — بدء الحفظ الاحتياطي
=================================================================
Mounted at /content/drive

⚠️ لم نعثر على جداول DataFrame في الذاكرة.
لم يُنشأ ملف احتياطي فارغ.

🌧️ انتهى كود الحفظ.

In [ ]:
# ================================================================
# 🌧️ الودق AI — المرحلة 67
# التدقيق الشامل لجودة البيانات والمستويات وإدارة المخاطر
# خلية مستقلة — المحافظة على جميع الجداول الأصلية
# ================================================================

import pandas as pd
import numpy as np
from datetime import datetime

print("=" * 75)
print("🌧️ الودق AI — المرحلة 67: التدقيق الشامل")
print("=" * 75)

# ------------------------------------------------
# 1. البحث عن أفضل مصدر متاح دون تعديل الجداول الأصلية
# ------------------------------------------------

source_candidates = [
    "wadq_stage66_final_report_df",
    "wadq_stage64_unified_df",
    "wadq_stage63_risk_df",
    "wadq_stage62_levels_df",
    "wadq_stage61_opportunities_df",
    "wadq_global_us_unified_df"
]

source_name = None
source_df = None

for name in source_candidates:
    obj = globals().get(name)
    if isinstance(obj, pd.DataFrame) and not obj.empty:
        source_name = name
        source_df = obj.copy(deep=True)
        break

if source_df is None:
    raise ValueError(
        "لم يُعثر على جدول مصدر مناسب. "
        "تأكدي من تشغيل المراحل السابقة في الجلسة الحالية."
    )

print(f"\n✅ مصدر التدقيق: {source_name}")
print(f"📊 عدد الصفوف: {len(source_df)}")

# ------------------------------------------------
# 2. أدوات مساعدة للتعامل مع اختلاف أسماء الأعمدة
# ------------------------------------------------

def find_col(df, candidates):
    normalized = {
        str(c).strip().lower(): c for c in df.columns
    }

    for candidate in candidates:
        if candidate in df.columns:
            return candidate

    for c in df.columns:
        cl = str(c).strip().lower()
        for candidate in candidates:
            if candidate.lower() in cl:
                return c

    return None


symbol_col = find_col(
    source_df,
    ["الرمز", "symbol", "ticker"]
)

price_col = find_col(
    source_df,
    ["أحدث إغلاق", "السعر", "السعر الحالي",
     "latest price", "close", "price"]
)

date_col = find_col(
    source_df,
    ["تاريخ آخر بيانات", "تاريخ آخر سعر",
     "تاريخ البيانات", "date", "latest date"]
)

market_col = find_col(
    source_df,
    ["السوق", "market"]
)

rsi_col = find_col(
    source_df,
    ["RSI", "rsi"]
)

stop_col = find_col(
    source_df,
    ["وقف خسارة استرشادي", "وقف الخسارة",
     "stop loss", "stop_loss"]
)

target1_col = find_col(
    source_df,
    ["هدف استرشادي 1", "الهدف الأول",
     "target 1", "target1"]
)

target2_col = find_col(
    source_df,
    ["هدف استرشادي 2", "الهدف الثاني",
     "target 2", "target2"]
)

qty_col = find_col(
    source_df,
    ["الكمية النظرية", "الكمية",
     "theoretical quantity", "quantity"]
)

if symbol_col is None:
    raise ValueError("تعذر تحديد عمود الرمز في جدول المصدر.")

if price_col is None:
    raise ValueError("تعذر تحديد عمود السعر في جدول المصدر.")

# ------------------------------------------------
# 3. إنشاء نسخة تدقيق مستقلة
# ------------------------------------------------

audit_df = source_df.copy(deep=True)

audit_df["67_السعر_الرقمي"] = pd.to_numeric(
    audit_df[price_col], errors="coerce"
)

if date_col is not None:
    audit_df["67_تاريخ_البيانات"] = pd.to_datetime(
        audit_df[date_col], errors="coerce", utc=True
    )
else:
    audit_df["67_تاريخ_البيانات"] = pd.NaT

audit_df["67_صلاحية_السعر"] = (
    audit_df["67_السعر_الرقمي"].notna()
    & (audit_df["67_السعر_الرقمي"] > 0)
)

audit_df["67_صلاحية_التاريخ"] = (
    audit_df["67_تاريخ_البيانات"].notna()
    & (
        audit_df["67_تاريخ_البيانات"]
        <= pd.Timestamp.now(tz="UTC")
    )
)

# ------------------------------------------------
# 4. تدقيق حداثة البيانات
# لا نفترض أن كل سوق يعمل يوميًا
# ------------------------------------------------

now_utc = pd.Timestamp.now(tz="UTC")

audit_df["67_عمر_البيانات_بالأيام"] = (
    now_utc - audit_df["67_تاريخ_البيانات"]
).dt.total_seconds() / 86400

def classify_freshness(row):
    if not row["67_صلاحية_السعر"]:
        return "سعر مفقود أو غير صالح"

    if not row["67_صلاحية_التاريخ"]:
        return "تاريخ مفقود أو مستقبلي"

    age = row["67_عمر_البيانات_بالأيام"]

    if pd.isna(age):
        return "تعذر التحقق من التاريخ"

    if age <= 1.5:
        return "حديث نسبيًا"

    if age <= 3.5:
        return "تحقق من تقويم السوق"

    return "قديم — يلزم التحقق"

audit_df["67_حالة_الحداثة"] = audit_df.apply(
    classify_freshness, axis=1
)

# ------------------------------------------------
# 5. تدقيق المؤشرات الفنية
# ------------------------------------------------

if rsi_col is not None:
    audit_df["67_RSI_رقمي"] = pd.to_numeric(
        audit_df[rsi_col], errors="coerce"
    )

    audit_df["67_حالة_RSI"] = np.select(
        [
            audit_df["67_RSI_رقمي"].isna(),
            ~audit_df["67_RSI_رقمي"].between(0, 100)
        ],
        [
            "مفقود",
            "خارج النطاق المتوقع"
        ],
        default="ضمن النطاق"
    )
else:
    audit_df["67_RSI_رقمي"] = np.nan
    audit_df["67_حالة_RSI"] = "عمود RSI غير متوفر"

# ------------------------------------------------
# 6. تدقيق المستويات الفنية
# ------------------------------------------------

for col in [stop_col, target1_col, target2_col]:
    if col is not None:
        audit_df[col] = pd.to_numeric(
            audit_df[col], errors="coerce"
        )

audit_df["67_حالة_المستويات"] = "غير مكتملة"

if all(
    c is not None
    for c in [stop_col, target1_col, target2_col]
):
    valid_levels = (
        audit_df[stop_col].notna()
        & audit_df[target1_col].notna()
        & audit_df[target2_col].notna()
        & (audit_df[stop_col] > 0)
        & (audit_df[target1_col] > 0)
        & (audit_df[target2_col] > 0)
    )

    audit_df.loc[
        valid_levels, "67_حالة_المستويات"
    ] = "موجودة — يلزم التحقق من منطقها"

    audit_df.loc[
        ~valid_levels, "67_حالة_المستويات"
    ] = "مفقودة أو غير صالحة"

    if "67_السعر_الرقمي" in audit_df.columns:
        price = audit_df["67_السعر_الرقمي"]
        stop = audit_df[stop_col]
        t1 = audit_df[target1_col]
        t2 = audit_df[target2_col]

        long_logic = (
            valid_levels
            & (stop < price)
            & (t1 > price)
            & (t2 >= t1)
        )

        short_logic = (
            valid_levels
            & (stop > price)
            & (t1 < price)
            & (t2 <= t1)
        )

        audit_df.loc[
            long_logic | short_logic,
            "67_حالة_المستويات"
        ] = "ترتيب حسابي متسق مبدئيًا"

        audit_df.loc[
            valid_levels & ~(long_logic | short_logic),
            "67_حالة_المستويات"
        ] = "تحتاج مراجعة ترتيب المستويات"

# ------------------------------------------------
# 7. تدقيق الكميات النظرية
# لا ننشئ كميات بديلة ولا نفترض وحدات العقود
# ------------------------------------------------

if qty_col is not None:
    audit_df["67_الكمية_الرقمية"] = pd.to_numeric(
        audit_df[qty_col], errors="coerce"
    )

    audit_df["67_حالة_الكمية"] = np.select(
        [
            audit_df["67_الكمية_الرقمية"].isna(),
            audit_df["67_الكمية_الرقمية"] <= 0
        ],
        [
            "غير محسوبة",
            "غير صالحة"
        ],
        default="كمية نظرية — تحتاج تحققًا"
    )
else:
    audit_df["67_الكمية_الرقمية"] = np.nan
    audit_df["67_حالة_الكمية"] = "عمود الكمية غير متوفر"

# ------------------------------------------------
# 8. تحديد حالة كل أصل
# ------------------------------------------------

def determine_status(row):
    reasons = []

    if not row["67_صلاحية_السعر"]:
        reasons.append("السعر غير صالح")

    if not row["67_صلاحية_التاريخ"]:
        reasons.append("التاريخ يحتاج مراجعة")

    freshness = row["67_حالة_الحداثة"]
    if freshness in [
        "قديم — يلزم التحقق",
        "تحقق من تقويم السوق",
        "تعذر التحقق من التاريخ"
    ]:
        reasons.append("حداثة البيانات غير مؤكدة")

    if row["67_حالة_المستويات"] in [
        "مفقودة أو غير صالحة",
        "تحتاج مراجعة ترتيب المستويات",
        "غير مكتملة"
    ]:
        reasons.append("المستويات غير مكتملة أو تحتاج مراجعة")

    if row["67_حالة_الكمية"] in [
        "غير محسوبة",
        "غير صالحة",
        "عمود الكمية غير متوفر"
    ]:
        reasons.append("الكمية النظرية غير مكتملة")

    if row["67_حالة_RSI"] in [
        "مفقود",
        "خارج النطاق المتوقع",
        "عمود RSI غير متوفر"
    ]:
        reasons.append("مؤشر RSI يحتاج مراجعة")

    if reasons:
        return "يحتاج مراجعة", "؛ ".join(reasons)

    return (
        "اجتاز الفحوص الأولية",
        "اجتاز الفحوص الآلية المحددة فقط"
    )

status_results = audit_df.apply(
    determine_status, axis=1
)

audit_df["67_الحالة_النهائية"] = [
    x[0] for x in status_results
]

audit_df["67_أسباب_المراجعة"] = [
    x[1] for x in status_results
]

# ------------------------------------------------
# 9. إنشاء جداول المرحلة 67 المستقلة
# ------------------------------------------------

wadq_stage67_audit_df = audit_df.copy(deep=True)

wadq_stage67_review_df = audit_df[
    audit_df["67_الحالة_النهائية"] == "يحتاج مراجعة"
].copy()

wadq_stage67_passed_df = audit_df[
    audit_df["67_الحالة_النهائية"] == "اجتاز الفحوص الأولية"
].copy()

# ملخص حالات البيانات
wadq_stage67_summary_df = pd.DataFrame({
    "البند": [
        "وقت التنفيذ",
        "مصدر التدقيق",
        "إجمالي الأصول",
        "أسعار صالحة رقميًا",
        "تواريخ صالحة وغير مستقبلية",
        "أصول تحتاج مراجعة",
        "أصول اجتازت الفحوص الأولية",
        "أصول بمستويات غير مكتملة أو تحتاج مراجعة",
        "أصول بكميات غير محسوبة أو غير صالحة"
    ],
    "القيمة": [
        datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        source_name,
        len(audit_df),
        int(audit_df["67_صلاحية_السعر"].sum()),
        int(audit_df["67_صلاحية_التاريخ"].sum()),
        len(wadq_stage67_review_df),
        len(wadq_stage67_passed_df),
        int(
            audit_df["67_حالة_المستويات"].isin([
                "مفقودة أو غير صالحة",
                "تحتاج مراجعة ترتيب المستويات",
                "غير مكتملة"
            ]).sum()
        ),
        int(
            audit_df["67_حالة_الكمية"].isin([
                "غير محسوبة", "غير صالحة",
                "عمود الكمية غير متوفر"
            ]).sum()
        )
    ]
})

# سجل المرحلة
wadq_stage67_log_df = pd.DataFrame([{
    "المرحلة": "67 — التدقيق الشامل",
    "الحالة": "اكتمل التدقيق البرمجي",
    "مصدر البيانات": source_name,
    "عدد الأصول": len(audit_df),
    "عدد الأصول التي تحتاج مراجعة": len(wadq_stage67_review_df),
    "وقت التنفيذ": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    "ملاحظة": (
        "التدقيق الآلي لا يؤكد صلاحية التداول. "
        "يلزم التحقق من تقويم السوق والعملة والعقود والعمولات."
    )
}])

# ------------------------------------------------
# 10. عرض النتائج
# ------------------------------------------------

print("\n" + "=" * 75)
print("📊 ملخص المرحلة 67")
print("=" * 75)
display(wadq_stage67_summary_df)

print("\n🔎 معاينة تقرير التدقيق:")
preview_cols = [
    symbol_col,
    price_col,
    "67_حالة_الحداثة",
    "67_حالة_RSI",
    "67_حالة_المستويات",
    "67_حالة_الكمية",
    "67_الحالة_النهائية",
    "67_أسباب_المراجعة"
]

preview_cols = list(dict.fromkeys(
    c for c in preview_cols if c in audit_df.columns
))

display(wadq_stage67_audit_df[preview_cols])

print("\n⚠️ الأصول التي تحتاج مراجعة:")
if wadq_stage67_review_df.empty:
    print("لم تُكتشف حالات تستوجب المراجعة ضمن الفحوص الحالية.")
else:
    display(wadq_stage67_review_df[preview_cols])

print("\n" + "=" * 75)
print("✅ انتهت المرحلة 67")
print("📌 لم يتم تعديل الجداول الأصلية.")
print("📌 لم تُنشأ توصيات شراء أو بيع.")
print("📌 اجتياز الفحوص الآلية لا يضمن صلاحية التداول.")
print("=" * 75)

print("\n📋 الجداول الجديدة:")
print("1. wadq_stage67_audit_df")
print("2. wadq_stage67_review_df")
print("3. wadq_stage67_passed_df")
print("4. wadq_stage67_summary_df")
print("5. wadq_stage67_log_df")

===========================================================================
🌧️ الودق AI — المرحلة 67: التدقيق الشامل
===========================================================================

✅ مصدر التدقيق: wadq_stage66_final_report_df
📊 عدد الصفوف: 26

===========================================================================
📊 ملخص المرحلة 67
===========================================================================

                                      البند                        القيمة
0                               وقت التنفيذ           2026-10-14 00:08:33
1                              مصدر التدقيق  wadq_stage66_final_report_df
2                             إجمالي الأصول                            26
3                        أسعار صالحة رقميًا                            26
4                تواريخ صالحة وغير مستقبلية                            26
5                         أصول تحتاج مراجعة                            14
6                أصول اجتازت الفحوص الأولية                            12
7  أصول بمستويات غير مكتملة أو تحتاج مراجعة                            14
8       أصول بكميات غير محسوبة أو غير صالحة                            14

🔎 معاينة تقرير التدقيق:

,الرمز,أحدث إغلاق,67_حالة_الحداثة,67_حالة_RSI,67_حالة_المستويات,67_حالة_الكمية,67_الحالة_النهائية,67_أسباب_المراجعة
0,NVDA,226.320007,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
1,TSLA,378.029999,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
2,AAPL,340.970001,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
3,MSFT,541.150024,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
4,AMZN,259.529999,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
5,GOOGL,352.720001,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
6,META,742.960022,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
7,QQQ,746.039978,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
8,SPY,778.099976,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
9,^GSPC,7805.450195,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
10,^IXIC,27204.380859,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
11,^DJI,51670.101562,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
12,^GDAXI,25277.679688,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
13,^FCHI,7832.879883,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
14,^FTSE,10656.299805,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
15,^N225,69030.921875,قديم — يلزم التحقق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
16,^HSI,24271.199219,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
17,GC=F,4180.100098,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
18,SI=F,59.230000,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
19,CL=F,94.860001,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
20,BZ=F,106.389999,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
21,NG=F,3.318000,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
22,EURUSD=X,1.120197,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
23,JPY=X,158.326004,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
24,BTC-USD,83166.648438,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط
25,ETH-USD,2498.360107,حديث نسبيًا,ضمن النطاق,ترتيب حسابي متسق مبدئيًا,كمية نظرية — تحتاج تحققًا,اجتاز الفحوص الأولية,اجتاز الفحوص الآلية المحددة فقط

⚠️ الأصول التي تحتاج مراجعة:

,الرمز,أحدث إغلاق,67_حالة_الحداثة,67_حالة_RSI,67_حالة_المستويات,67_حالة_الكمية,67_الحالة_النهائية,67_أسباب_المراجعة
0,NVDA,226.320007,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
1,TSLA,378.029999,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
2,AAPL,340.970001,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
3,MSFT,541.150024,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
4,AMZN,259.529999,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
5,GOOGL,352.720001,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
6,META,742.960022,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
7,QQQ,746.039978,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
8,SPY,778.099976,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
12,^GDAXI,25277.679688,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
13,^FCHI,7832.879883,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
14,^FTSE,10656.299805,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
15,^N225,69030.921875,قديم — يلزم التحقق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...
16,^HSI,24271.199219,تحقق من تقويم السوق,ضمن النطاق,مفقودة أو غير صالحة,غير محسوبة,يحتاج مراجعة,حداثة البيانات غير مؤكدة؛ المستويات غير مكتملة...

===========================================================================
✅ انتهت المرحلة 67
📌 لم يتم تعديل الجداول الأصلية.
📌 لم تُنشأ توصيات شراء أو بيع.
📌 اجتياز الفحوص الآلية لا يضمن صلاحية التداول.
===========================================================================

📋 الجداول الجديدة:
1. wadq_stage67_audit_df
2. wadq_stage67_review_df
3. wadq_stage67_passed_df
4. wadq_stage67_summary_df
5. wadq_stage67_log_df

In [ ]:
# ============================================================
# 🌧️ الودق AI — سجل الحفظ والاستئناف
# يحفظ حالة المشروع للعودة إليها دون ارتباك
# ============================================================
from google.colab import drive
from pathlib import Path
from datetime import datetime
# الاتصال بـ Google Drive
drive.mount('/content/drive')
# مجلد حفظ المشروع
save_dir = Path('/content/drive/MyDrive/الودق AI - سجل المشروع')
save_dir.mkdir(parents=True, exist_ok=True)
# بيانات حالة المشروع
project_note = """
============================================================
🌧️ مشروع الودق AI — سجل التقدم
============================================================
تاريخ آخر تحديث: 2026-10-14
اسم ملف المشروع:
Copy of الودق AI
آخر مرحلة مكتملة:
المرحلة 67 — التدقيق الشامل لجودة البيانات والمخاطر
المراحل المكتملة:
- المرحلة 59: تحديث الأسعار
- المرحلة 60: فحص جودة البيانات
- المرحلة 61: تقييم الفرص الفنية
- المرحلة 62: مستويات فنية استرشادية
- المرحلة 63: إدارة المخاطر
- المرحلة 64: التقرير الموحد
- المرحلة 65: اختبارات الجودة
- المرحلة 66: إنشاء التقرير النهائي
- المرحلة 67: التدقيق الشامل
عدد الأصول:
26 أصلًا
نتائج المرحلة 67:
- 26 سعرًا صالحًا رقميًا
- 26 تاريخًا صالحًا وغير مستقبلي
- 12 أصلًا اجتاز الفحوص الأولية
- 14 أصلًا يحتاج إلى مراجعة
- 14 أصلًا لديه مستويات غير مكتملة أو تحتاج إلى مراجعة
- 14 أصلًا لديه كميات غير محسوبة أو غير صالحة
الجداول الأصلية لم تُعدّل عمدًا.
الجداول التي أنشأتها المرحلة 67:
1. wadq_stage67_audit_df
2. wadq_stage67_review_df
3. wadq_stage67_passed_df
4. wadq_stage67_summary_df
5. wadq_stage67_log_df
الخطوة التالية:
المرحلة 68A — فحص مصادر الأسعار التاريخية
ومعرفة الجداول المتاحة وأعمدتها قبل إصلاح البيانات.
بعد المرحلة 68A:
تحديد مصدر الأسعار التاريخية الصحيح،
ثم إصلاح المستويات الفنية وحسابات المخاطر.
تعليمات مهمة عند العودة:
1. لا تحذف أي خلية سابقة.
2. لا تضغط Run all.
3. لا تعيدي تشغيل المراحل السابقة دون حاجة.
4. افتحي ملف Copy of الودق AI نفسه.
5. تحققي من آخر مرحلة مكتملة قبل المتابعة.
6. إذا اختفت الجداول، افحصي المصادر المتاحة أولًا.
7. أضيفي المراحل الجديدة أسفل آخر خلية.
8. لا تعتمدي على كمية تداول نظرية قبل التحقق
   من العملة والعقد والعمولات وشروط الوسيط.
ملاحظة:
هذا السجل يحفظ وصف حالة المشروع، وليس الجداول
الموجودة في ذاكرة جلسة Colab.
============================================================
"""
# حفظ سجل المشروع
note_path = save_dir / 'سجل_الودق_AI.txt'
note_path.write_text(project_note, encoding='utf-8')
# إنشاء سجل متجدد لتاريخ الحفظ
history_path = save_dir / 'سجل_الاستئناف.txt'
entry = f"""
وقت الحفظ: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
آخر مرحلة مكتملة: 67
الخطوة التالية: 68A
ملف المشروع: Copy of الودق AI
----------------------------------------
"""
with history_path.open('a', encoding='utf-8') as f:
    f.write(entry)
print("=" * 60)
print("🌧️ تم حفظ سجل مشروع الودق AI")
print("=" * 60)
print(f"📁 مجلد الحفظ: {save_dir}")
print(f"📄 سجل المشروع: {note_path.name}")
print(f"📄 سجل الاستئناف: {history_path.name}")
print("✅ آخر مرحلة مكتملة: 67")
print("➡️ المرحلة التالية: 68A")
print("⚠️ هذا السجل لا يحفظ الجداول الموجودة في ذاكرة Colab.")
print("=" * 60)

Mounted at /content/drive
============================================================
🌧️ تم حفظ سجل مشروع الودق AI
============================================================
📁 مجلد الحفظ: /content/drive/MyDrive/الودق AI - سجل المشروع
📄 سجل المشروع: سجل_الودق_AI.txt
📄 سجل الاستئناف: سجل_الاستئناف.txt
✅ آخر مرحلة مكتملة: 67
➡️ المرحلة التالية: 68A
⚠️ هذا السجل لا يحفظ الجداول الموجودة في ذاكرة Colab.
============================================================

In [ ]:
# 🌧️ الودق AI - فحص جاهزية الربط

print("فحص جداول الودق AI")
print("=" * 40)

for name in ["us_technical_df", "us_results", "wadq_news_df",
             "wadq_news_scored_df", "wadq_ticker_news_df"]:

    if name in globals():
        obj = globals()[name]
        print(f"✅ {name}: موجود")

        if hasattr(obj, "shape"):
            print("   حجم الجدول:", obj.shape)

    else:
        print(f"⚠️ {name}: غير موجود")

فحص جداول الودق AI
========================================
✅ us_technical_df: موجود
   حجم الجدول: (9, 10)
✅ us_results: موجود
✅ wadq_news_df: موجود
   حجم الجدول: (544, 5)
✅ wadq_news_scored_df: موجود
   حجم الجدول: (544, 8)
✅ wadq_ticker_news_df: موجود
   حجم الجدول: (197, 6)

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 68
# تحليل الأصول التي تحتاج مراجعة
# خلية مستقلة — دون تعديل الجداول الأصلية
# ============================================================

import pandas as pd
from datetime import datetime

print("=" * 75)
print("🌧️ الودق AI — المرحلة 68: تحليل الأصول التي تحتاج مراجعة")
print("=" * 75)

# ------------------------------------------------------------
# 1. التأكد من وجود جدول المرحلة 67
# ------------------------------------------------------------

if "wadq_stage67_review_df" not in globals():
    raise ValueError(
        "❌ جدول المرحلة 67 غير موجود. "
        "يجب تشغيل المرحلة 67 أولاً."
    )

# إنشاء نسخة مستقلة
wadq_stage68_review_df = wadq_stage67_review_df.copy(deep=True)

print("✅ مصدر البيانات: wadq_stage67_review_df")
print("📊 عدد الأصول التي تحتاج مراجعة:",
      len(wadq_stage68_review_df))

# ------------------------------------------------------------
# 2. عرض أسباب المراجعة
# ------------------------------------------------------------

reason_columns = [
    col for col in wadq_stage68_review_df.columns
    if "سبب" in str(col) or "مراجعة" in str(col)
]

if reason_columns:
    print("\n🔎 أسباب المراجعة:")
    display(wadq_stage68_review_df[reason_columns])

# ------------------------------------------------------------
# 3. فحص أعمدة المستويات الفنية والكميات
# ------------------------------------------------------------

technical_columns = [
    col for col in wadq_stage68_review_df.columns
    if any(word in str(col).lower() for word in [
        "stop", "target", "support", "resistance",
        "كمية", "مستوى", "هدف", "وقف"
    ])
]

if technical_columns:
    print("\n📈 بيانات المستويات والكميات:")
    display(wadq_stage68_review_df[technical_columns])

else:
    print("\n⚠️ لم تظهر أعمدة المستويات الفنية والكميات "
          "في جدول المراجعة.")

# ------------------------------------------------------------
# 4. عرض تقرير المراجعة الكامل
# ------------------------------------------------------------

print("\n📋 تقرير الأصول التي تحتاج مراجعة:")

display(wadq_stage68_review_df)

# ------------------------------------------------------------
# 5. تسجيل المرحلة
# ------------------------------------------------------------

wadq_stage68_log_df = pd.DataFrame({
    "البند": [
        "وقت التنفيذ",
        "مصدر البيانات",
        "عدد الأصول التي تحتاج مراجعة",
        "نوع المرحلة",
        "حالة التوصيات"
    ],
    "القيمة": [
        datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "wadq_stage67_review_df",
        len(wadq_stage68_review_df),
        "تحليل ومراجعة البيانات",
        "لم يتم إنشاء توصيات شراء أو بيع"
    ]
})

print("\n" + "=" * 75)
print("✅ انتهت المرحلة 68")
print("📌 لم يتم تعديل الجداول الأصلية.")
print("📌 لم يتم تحديث الأسعار.")
print("📌 لم يتم إنشاء توصيات شراء أو بيع.")
print("=" * 75)

display(wadq_stage68_log_df)

===========================================================================
🌧️ الودق AI — المرحلة 68: تحليل الأصول التي تحتاج مراجعة
===========================================================================

ValueError: ❌ جدول المرحلة 67 غير موجود. يجب تشغيل المرحلة 67 أولاً.

In [ ]:
# 🌧️ الودق AI — فحص جداول المرحلة 67

print("=" * 60)
print("🔎 فحص الجداول المحفوظة في الذاكرة")
print("=" * 60)

stage67_tables = [
    "wadq_stage67_audit_df",
    "wadq_stage67_review_df",
    "wadq_stage67_passed_df",
    "wadq_stage67_summary_df",
    "wadq_stage67_log_df"
]

for name in stage67_tables:
    if name in globals():
        df = globals()[name]
        print(f"✅ {name} موجود — الحجم: {df.shape}")
    else:
        print(f"❌ {name} غير موجود")

print("=" * 60)

============================================================
🔎 فحص الجداول المحفوظة في الذاكرة
============================================================
❌ wadq_stage67_audit_df غير موجود
❌ wadq_stage67_review_df غير موجود
❌ wadq_stage67_passed_df غير موجود
❌ wadq_stage67_summary_df غير موجود
❌ wadq_stage67_log_df غير موجود
============================================================

In [ ]:
# 🌧️ الودق AI — فحص مصدر المرحلة 66

print("=" * 60)
print("🔎 فحص مصدر المرحلة 67")
print("=" * 60)

if "wadq_stage66_final_report_df" in globals():
    print("✅ مصدر المرحلة 66 موجود في الذاكرة")
    print("📊 حجم الجدول:", wadq_stage66_final_report_df.shape)
    display(wadq_stage66_final_report_df.head())
else:
    print("❌ مصدر المرحلة 66 غير موجود في الذاكرة")

print("=" * 60)

============================================================
🔎 فحص مصدر المرحلة 67
============================================================
❌ مصدر المرحلة 66 غير موجود في الذاكرة
============================================================

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة الرابعة: التقرير الموحد للأخبار والتحليل الفني
# إنشاء جدول جديد دون تعديل الجداول الأصلية
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - إنشاء التقرير الموحد")
print("=" * 55)

# 1. التأكد من توفر الجداول
required_tables = [
    "us_technical_df",
    "wadq_ticker_news_df"
]

missing_tables = [
    name for name in required_tables
    if name not in globals()
]

if missing_tables:
    print("الجداول التالية غير متاحة:", missing_tables)

else:
    # 2. إنشاء نسخ مستقلة
    wadq_us_copy = us_technical_df.copy()
    wadq_news_copy = wadq_ticker_news_df.copy()

    # 3. توحيد أسماء الأعمدة
    wadq_us_copy.columns = [
        str(c).strip() for c in wadq_us_copy.columns
    ]

    print("\nأعمدة التحليل الفني:")
    print(wadq_us_copy.columns.tolist())

    # 4. التعرف على عمود رمز السهم
    possible_ticker_columns = [
        "ticker", "Ticker", "symbol", "Symbol",
        "stock", "Stock", "رمز السهم"
    ]

    ticker_col = next(
        (
            c for c in possible_ticker_columns
            if c in wadq_us_copy.columns
        ),
        None
    )

    # البحث في الفهرس إذا لم يكن الرمز عمودًا
    if ticker_col is None:
        index_values = [
            str(x).upper().strip()
            for x in wadq_us_copy.index
        ]

        known_tickers = {
            "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
            "GOOGL", "META", "QQQ", "SPY"
        }

        if any(x in known_tickers for x in index_values):
            wadq_us_copy = wadq_us_copy.reset_index()
            ticker_col = wadq_us_copy.columns[0]

    if ticker_col is None:
        print(
            "\nلم أتعرف على عمود رمز السهم تلقائيًا."
            "\nأرسلي لي أسماء الأعمدة الظاهرة أعلاه."
        )

    else:
        # 5. توحيد رموز الأسهم
        wadq_us_copy["_wadq_ticker"] = (
            wadq_us_copy[ticker_col]
            .astype(str)
            .str.upper()
            .str.strip()
        )

        wadq_news_copy["_wadq_ticker"] = (
            wadq_news_copy["ticker"]
            .astype(str)
            .str.upper()
            .str.strip()
        )

        # 6. تلخيص الأخبار لكل سهم
        if wadq_news_copy.empty:
            wadq_news_summary = pd.DataFrame(
                columns=[
                    "_wadq_ticker",
                    "news_count",
                    "positive_news",
                    "negative_news",
                    "neutral_news"
                ]
            )

        else:
            wadq_news_copy["_positive"] = (
                wadq_news_copy["sentiment"]
                .eq("إيجابي مبدئي")
                .astype(int)
            )

            wadq_news_copy["_negative"] = (
                wadq_news_copy["sentiment"]
                .eq("سلبي مبدئي")
                .astype(int)
            )

            wadq_news_copy["_neutral"] = (
                wadq_news_copy["sentiment"]
                .eq("محايد أو غير واضح")
                .astype(int)
            )

            wadq_news_summary = (
                wadq_news_copy.groupby(
                    "_wadq_ticker",
                    as_index=False
                )
                .agg(
                    news_count=("_wadq_ticker", "size"),
                    positive_news=("_positive", "sum"),
                    negative_news=("_negative", "sum"),
                    neutral_news=("_neutral", "sum")
                )
            )

        # 7. دمج البيانات في جدول مستقل
        wadq_integrated_df = wadq_us_copy.merge(
            wadq_news_summary,
            on="_wadq_ticker",
            how="left"
        )

        # 8. توضيح عدم توفر أخبار مرتبطة
        count_columns = [
            "news_count",
            "positive_news",
            "negative_news",
            "neutral_news"
        ]

        for col in count_columns:
            if col in wadq_integrated_df.columns:
                wadq_integrated_df[col] = (
                    wadq_integrated_df[col]
                    .fillna(0)
                    .astype(int)
                )

        wadq_integrated_df["news_status"] = (
            wadq_integrated_df["news_count"]
            .gt(0)
            .map({
                True: "توجد أخبار مرتبطة",
                False: "لم يُعثر على أخبار مرتبطة"
            })
        )

        # 9. عرض التقرير
        wadq_integrated_df = (
            wadq_integrated_df.drop(
                columns=["_wadq_ticker"]
            )
        )

        print("\n✅ تم إنشاء التقرير الموحد")
        print("عدد صفوف التقرير:", len(wadq_integrated_df))
        print("\nالنتائج:")

        display(wadq_integrated_df)

        print("\nاسم جدول التقرير:")
        print("wadq_integrated_df")

🌧️ الودق AI - إنشاء التقرير الموحد
=======================================================

أعمدة التحليل الفني:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

لم أتعرف على عمود رمز السهم تلقائيًا.
أرسلي لي أسماء الأعمدة الظاهرة أعلاه.

In [ ]:
# 🌧️ الودق AI
# إصلاح التعرف على رمز السهم دون تعديل الجداول الأصلية

print("🌧️ الودق AI - فحص أعمدة التحليل الفني")
print("=" * 50)

if "us_technical_df" in globals():

    print("أعمدة التحليل الفني:")
    print(us_technical_df.columns.tolist())

    print("\nأول 5 صفوف:")
    display(us_technical_df.head())

else:
    print("⚠️ جدول us_technical_df غير موجود في الجلسة الحالية.")

if "wadq_ticker_news_df" in globals():

    print("\nأعمدة الأخبار:")
    print(wadq_ticker_news_df.columns.tolist())

    print("\nأول 5 صفوف من الأخبار:")
    display(wadq_ticker_news_df.head())

else:
    print("⚠️ جدول wadq_ticker_news_df غير موجود في الجلسة الحالية.")

🌧️ الودق AI - فحص أعمدة التحليل الفني
==================================================
أعمدة التحليل الفني:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

أول 5 صفوف:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط

أعمدة الأخبار:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

أول 5 صفوف من الأخبار:

,ticker,news_title,sentiment,category,published,link
0,QQQ,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,الأسواق الأمريكية,"Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
1,SPY,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,الأسواق الأمريكية,"Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
2,SPY,"The S&P 500 Hits a New Record High, Powered by...",إيجابي مبدئي,الأسواق الأمريكية,"Tue, 06 Oct 2026 21:33:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...
3,SPY,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...",محايد أو غير واضح,الأسواق الأمريكية,"Wed, 07 Oct 2026 20:11:09 GMT",https://news.google.com/rss/articles/CBMiuAFBV...
4,SPY,"S&P 500, Nasdaq end lower as crude prices jump...",محايد أو غير واضح,الأسواق الأمريكية,"Thu, 08 Oct 2026 23:09:38 GMT",https://news.google.com/rss/articles/CBMinAFBV...

In [ ]:
# 🌧️ الودق AI
# المرحلة الرابعة - فحص البيانات قبل الدمج

print("🌧️ الودق AI - فحص الجداول")
print("=" * 50)

# فحص التحليل الفني
if "us_technical_df" in globals():

    print("\n📊 أعمدة التحليل الفني:")
    print(us_technical_df.columns.tolist())

    print("\nأول 5 صفوف:")
    display(us_technical_df.head())

else:
    print("⚠️ جدول التحليل الفني غير موجود.")

# فحص الأخبار
if "wadq_ticker_news_df" in globals():

    print("\n📰 أعمدة الأخبار:")
    print(wadq_ticker_news_df.columns.tolist())

    print("\nأول 5 صفوف:")
    display(wadq_ticker_news_df.head())

else:
    print("⚠️ جدول أخبار الأسهم غير موجود.")

🌧️ الودق AI - فحص الجداول
==================================================

📊 أعمدة التحليل الفني:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

أول 5 صفوف:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط

📰 أعمدة الأخبار:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

أول 5 صفوف:

,ticker,news_title,sentiment,category,published,link
0,QQQ,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,الأسواق الأمريكية,"Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
1,SPY,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,الأسواق الأمريكية,"Sun, 11 Oct 2026 18:45:06 GMT",https://news.google.com/rss/articles/CBMiwgFBV...
2,SPY,"The S&P 500 Hits a New Record High, Powered by...",إيجابي مبدئي,الأسواق الأمريكية,"Tue, 06 Oct 2026 21:33:00 GMT",https://news.google.com/rss/articles/CBMisAFBV...
3,SPY,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...",محايد أو غير واضح,الأسواق الأمريكية,"Wed, 07 Oct 2026 20:11:09 GMT",https://news.google.com/rss/articles/CBMiuAFBV...
4,SPY,"S&P 500, Nasdaq end lower as crude prices jump...",محايد أو غير واضح,الأسواق الأمريكية,"Thu, 08 Oct 2026 23:09:38 GMT",https://news.google.com/rss/articles/CBMinAFBV...

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة الرابعة: ربط الأخبار بالتحليل الفني
# إنشاء جدول جديد دون تعديل الجداول الأصلية
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - التقرير الموحد")
print("=" * 55)

# التأكد من وجود الجدولين
if (
    "us_technical_df" not in globals()
    or "wadq_ticker_news_df" not in globals()
):
    print("⚠️ أحد الجدولين غير موجود. تأكدي من تشغيل خلاياه السابقة.")

else:
    # إنشاء نسخ مستقلة
    tech = us_technical_df.copy()
    news = wadq_ticker_news_df.copy()

    # تنظيف أسماء الأعمدة
    tech.columns = tech.columns.astype(str).str.strip()
    news.columns = news.columns.astype(str).str.strip()

    # تحديد عمود رمز السهم في التحليل الفني
    possible_columns = [
        "ticker", "Ticker", "symbol", "Symbol",
        "stock", "Stock", "الرمز", "السهم", "رمز السهم"
    ]

    ticker_col = next(
        (c for c in possible_columns if c in tech.columns),
        None
    )

    # إذا كان رمز السهم محفوظًا في الفهرس
    if ticker_col is None:
        index_tickers = {
            str(x).strip().upper() for x in tech.index
        }

        known_tickers = {
            "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
            "GOOGL", "META", "QQQ", "SPY"
        }

        if index_tickers.intersection(known_tickers):
            tech = tech.reset_index()
            ticker_col = tech.columns[0]

    if ticker_col is None:
        print("⚠️ لم يتم تحديد عمود رمز السهم.")
        print("أعمدة التحليل الفني:", tech.columns.tolist())

    elif "ticker" not in news.columns:
        print("⚠️ عمود ticker غير موجود في جدول الأخبار.")

    elif "sentiment" not in news.columns:
        print("⚠️ عمود sentiment غير موجود في جدول الأخبار.")

    else:
        # توحيد رموز الأسهم
        tech["_ticker_key"] = (
            tech[ticker_col].astype(str).str.upper().str.strip()
        )

        news["_ticker_key"] = (
            news["ticker"].astype(str).str.upper().str.strip()
        )

        # تصنيف المشاعر
        news["_positive"] = (
            news["sentiment"].astype(str).str.contains(
                "إيجابي", na=False
            ).astype(int)
        )

        news["_negative"] = (
            news["sentiment"].astype(str).str.contains(
                "سلبي", na=False
            ).astype(int)
        )

        news["_neutral"] = (
            news["sentiment"].astype(str).str.contains(
                "محايد|غير واضح", na=False
            ).astype(int)
        )

        # تلخيص الأخبار لكل سهم
        summary = (
            news.groupby("_ticker_key", as_index=False)
            .agg(
                news_count=("_ticker_key", "size"),
                positive_news=("_positive", "sum"),
                negative_news=("_negative", "sum"),
                neutral_news=("_neutral", "sum")
            )
        )

        # دمج الملخص مع التحليل الفني
        wadq_integrated_df = tech.merge(
            summary,
            on="_ticker_key",
            how="left"
        )

        # معالجة الأسهم التي لا توجد لها أخبار
        count_columns = [
            "news_count",
            "positive_news",
            "negative_news",
            "neutral_news"
        ]

        wadq_integrated_df[count_columns] = (
            wadq_integrated_df[count_columns]
            .fillna(0)
            .astype(int)
        )

        wadq_integrated_df["news_status"] = (
            wadq_integrated_df["news_count"]
            .gt(0)
            .map({
                True: "توجد أخبار",
                False: "لا توجد أخبار مرتبطة"
            })
        )

        # حذف عمود الربط الداخلي فقط من التقرير الجديد
        wadq_integrated_df.drop(
            columns=["_ticker_key"],
            inplace=True
        )

        print("✅ تم إنشاء التقرير الموحد بنجاح!")
        print("عدد الأسهم:", len(wadq_integrated_df))
        print("\n📊 التقرير الموحد:")
        display(wadq_integrated_df)

        print("\nاسم جدول التقرير: wadq_integrated_df")

🌧️ الودق AI - التقرير الموحد
=======================================================
✅ تم إنشاء التقرير الموحد بنجاح!
عدد الأسهم: 9

📊 التقرير الموحد:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,news_count,positive_news,negative_news,neutral_news,news_status
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,45,9,1,35,توجد أخبار
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,20,2,0,18,توجد أخبار
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,1,0,0,1,توجد أخبار
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,33,7,1,25,توجد أخبار
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,17,4,0,13,توجد أخبار
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,21,5,0,16,توجد أخبار
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,3,1,0,2,توجد أخبار
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,3,2,0,1,توجد أخبار
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,54,15,12,27,توجد أخبار

اسم جدول التقرير: wadq_integrated_df

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة الخامسة: التقييم الموحد للأسهم
# لا يعدل التقرير الأصلي
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - التقييم الموحد للأسهم")
print("=" * 55)

if "wadq_integrated_df" not in globals():
    print("⚠️ شغّلي كود التقرير الموحد أولًا.")

else:
    # إنشاء نسخة مستقلة
    wadq_evaluation_df = wadq_integrated_df.copy()

    # البحث عن الأعمدة بأسمائها المحتملة
    def find_column(df, names):
        for name in names:
            if name in df.columns:
                return name
        return None

    ticker_col = find_column(
        wadq_evaluation_df,
        ["ticker", "Ticker", "symbol", "Symbol", "الرمز"]
    )

    rsi_col = find_column(
        wadq_evaluation_df,
        ["RSI", "rsi"]
    )

    trend_col = find_column(
        wadq_evaluation_df,
        ["الاتجاه", "trend", "Trend"]
    )

    macd_col = find_column(
        wadq_evaluation_df,
        ["إشارة MACD", "MACD", "macd_signal"]
    )

    required_news_cols = [
        "positive_news",
        "negative_news",
        "neutral_news"
    ]

    if rsi_col is None:
        print("⚠️ لم يُعثر على عمود RSI.")

    elif trend_col is None:
        print("⚠️ لم يُعثر على عمود الاتجاه.")

    elif not all(
        col in wadq_evaluation_df.columns
        for col in required_news_cols
    ):
        print("⚠️ أعمدة ملخص الأخبار غير مكتملة.")

    else:
        # تحويل القيم الرقمية
        wadq_evaluation_df["_rsi_value"] = pd.to_numeric(
            wadq_evaluation_df[rsi_col],
            errors="coerce"
        )

        positive = wadq_evaluation_df["positive_news"]
        negative = wadq_evaluation_df["negative_news"]

        trend = (
            wadq_evaluation_df[trend_col]
            .astype(str)
            .str.strip()
        )

        # تصنيف المؤشر الفني RSI
        wadq_evaluation_df["تقييم RSI"] = "متوسط"

        wadq_evaluation_df.loc[
            wadq_evaluation_df["_rsi_value"] < 30,
            "تقييم RSI"
        ] = "تشبع بيعي محتمل"

        wadq_evaluation_df.loc[
            wadq_evaluation_df["_rsi_value"] > 70,
            "تقييم RSI"
        ] = "تشبع شرائي محتمل"

        # تقييم الأخبار
        wadq_evaluation_df["تقييم الأخبار"] = "محايد مبدئي"

        wadq_evaluation_df.loc[
            positive > negative,
            "تقييم الأخبار"
        ] = "إيجابي مبدئي"

        wadq_evaluation_df.loc[
            negative > positive,
            "تقييم الأخبار"
        ] = "سلبي مبدئي"

        # التقييم النهائي الأولي
        wadq_evaluation_df["تقييم الودق"] = (
            "إشارات مختلطة أو بيانات غير كافية"
        )

        bullish_trend = trend.str.contains(
            "صاعد|إيجابي|شراء|uptrend|bullish",
            case=False,
            na=False
        )

        bearish_trend = trend.str.contains(
            "هابط|سلبي|بيع|downtrend|bearish",
            case=False,
            na=False
        )

        wadq_evaluation_df.loc[
            bullish_trend & (positive > negative),
            "تقييم الودق"
        ] = "توافق إيجابي مبدئي"

        wadq_evaluation_df.loc[
            bearish_trend & (negative > positive),
            "تقييم الودق"
        ] = "توافق سلبي مبدئي"

        wadq_evaluation_df.loc[
            bullish_trend & (negative > positive),
            "تقييم الودق"
        ] = "تعارض: اتجاه فني إيجابي وأخبار سلبية"

        wadq_evaluation_df.loc[
            bearish_trend & (positive > negative),
            "تقييم الودق"
        ] = "تعارض: اتجاه فني سلبي وأخبار إيجابية"

        # عرض الأعمدة المفيدة فقط مع الاحتفاظ بكل البيانات
        wadq_evaluation_df.drop(
            columns=["_rsi_value"],
            inplace=True
        )

        print("✅ اكتمل التقييم المبدئي.")
        display(wadq_evaluation_df)

        print("\nاسم جدول التقييم:")
        print("wadq_evaluation_df")

🌧️ الودق AI - التقييم الموحد للأسهم
=======================================================
✅ اكتمل التقييم المبدئي.

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,news_count,positive_news,negative_news,neutral_news,news_status,تقييم RSI,تقييم الأخبار,تقييم الودق
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,45,9,1,35,توجد أخبار,متوسط,إيجابي مبدئي,توافق إيجابي مبدئي
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,20,2,0,18,توجد أخبار,متوسط,إيجابي مبدئي,توافق إيجابي مبدئي
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,1,0,0,1,توجد أخبار,متوسط,محايد مبدئي,إشارات مختلطة أو بيانات غير كافية
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,33,7,1,25,توجد أخبار,متوسط,إيجابي مبدئي,توافق إيجابي مبدئي
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,17,4,0,13,توجد أخبار,متوسط,إيجابي مبدئي,إشارات مختلطة أو بيانات غير كافية
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,21,5,0,16,توجد أخبار,متوسط,إيجابي مبدئي,إشارات مختلطة أو بيانات غير كافية
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,3,1,0,2,توجد أخبار,متوسط,إيجابي مبدئي,إشارات مختلطة أو بيانات غير كافية
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,3,2,0,1,توجد أخبار,متوسط,إيجابي مبدئي,توافق إيجابي مبدئي
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,54,15,12,27,توجد أخبار,متوسط,إيجابي مبدئي,توافق إيجابي مبدئي

اسم جدول التقييم:
wadq_evaluation_df

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة السادسة: لوحة ترتيب الأسهم
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - لوحة ترتيب الأسهم")
print("=" * 55)

if "wadq_evaluation_df" not in globals():

    print("⚠️ شغّلي كود المرحلة الخامسة أولًا.")

else:
    wadq_ranking_df = wadq_evaluation_df.copy()

    # تحديد عمود رمز السهم
    ticker_candidates = [
        "ticker", "Ticker", "symbol", "Symbol",
        "الرمز", "السهم"
    ]

    ticker_col = next(
        (
            c for c in ticker_candidates
            if c in wadq_ranking_df.columns
        ),
        None
    )

    # التأكد من توفر الأعمدة اللازمة
    needed = [
        "تقييم الأخبار",
        "تقييم الودق",
        "تقييم RSI",
        "news_count"
    ]

    missing = [
        c for c in needed
        if c not in wadq_ranking_df.columns
    ]

    if ticker_col is None:
        print("⚠️ لم يُعثر على عمود رمز السهم.")
        print("الأعمدة المتاحة:", wadq_ranking_df.columns.tolist())

    elif missing:
        print("⚠️ أعمدة غير متوفرة:", missing)

    else:
        # حساب نقاط استرشادية للأخبار
        wadq_ranking_df["نقاط الأخبار"] = (
            wadq_ranking_df["positive_news"]
            - wadq_ranking_df["negative_news"]
        )

        # ترتيب النتائج وفقًا لنقاط الأخبار فقط
        wadq_ranking_df["ترتيب الأخبار"] = (
            wadq_ranking_df["نقاط الأخبار"]
            .rank(method="dense", ascending=False)
            .astype(int)
        )

        # توضيح مستوى اكتمال البيانات
        wadq_ranking_df["حالة البيانات"] = (
            wadq_ranking_df["news_count"]
            .gt(0)
            .map({
                True: "تتوفر أخبار مرتبطة",
                False: "لا توجد أخبار مرتبطة"
            })
        )

        # عرض تقرير مختصر
        report_columns = [
            ticker_col,
            "تقييم RSI",
            "تقييم الأخبار",
            "نقاط الأخبار",
            "ترتيب الأخبار",
            "تقييم الودق",
            "حالة البيانات"
        ]

        wadq_ranking_report = (
            wadq_ranking_df[report_columns]
            .sort_values(
                by="نقاط الأخبار",
                ascending=False
            )
            .reset_index(drop=True)
        )

        print("✅ تم إنشاء لوحة ترتيب الأسهم.")
        print("ملاحظة: الترتيب مبني على عدد الأخبار الإيجابية والسلبية،")
        print("ولا يمثل احتمال الربح أو توصية شراء أو بيع.")

        display(wadq_ranking_report)

        print("\nاسم جدول الترتيب:")
        print("wadq_ranking_report")

🌧️ الودق AI - لوحة ترتيب الأسهم
=======================================================
✅ تم إنشاء لوحة ترتيب الأسهم.
ملاحظة: الترتيب مبني على عدد الأخبار الإيجابية والسلبية،
ولا يمثل احتمال الربح أو توصية شراء أو بيع.

,الرمز,تقييم RSI,تقييم الأخبار,نقاط الأخبار,ترتيب الأخبار,تقييم الودق,حالة البيانات
0,NVDA,متوسط,إيجابي مبدئي,8,1,توافق إيجابي مبدئي,تتوفر أخبار مرتبطة
1,MSFT,متوسط,إيجابي مبدئي,6,2,توافق إيجابي مبدئي,تتوفر أخبار مرتبطة
2,GOOGL,متوسط,إيجابي مبدئي,5,3,إشارات مختلطة أو بيانات غير كافية,تتوفر أخبار مرتبطة
3,AMZN,متوسط,إيجابي مبدئي,4,4,إشارات مختلطة أو بيانات غير كافية,تتوفر أخبار مرتبطة
4,SPY,متوسط,إيجابي مبدئي,3,5,توافق إيجابي مبدئي,تتوفر أخبار مرتبطة
5,QQQ,متوسط,إيجابي مبدئي,2,6,توافق إيجابي مبدئي,تتوفر أخبار مرتبطة
6,TSLA,متوسط,إيجابي مبدئي,2,6,توافق إيجابي مبدئي,تتوفر أخبار مرتبطة
7,META,متوسط,إيجابي مبدئي,1,7,إشارات مختلطة أو بيانات غير كافية,تتوفر أخبار مرتبطة
8,AAPL,متوسط,محايد مبدئي,0,8,إشارات مختلطة أو بيانات غير كافية,تتوفر أخبار مرتبطة

اسم جدول الترتيب:
wadq_ranking_report

In [ ]:
# 🌧️ الودق AI
# المرحلة السابعة: فحص بيانات بناء التقييم المتقدم

print("🌧️ الودق AI - فحص البيانات")
print("=" * 50)

if "wadq_integrated_df" in globals():

    print("\n📊 أعمدة التحليل الفني والتقرير الموحد:")
    print(wadq_integrated_df.columns.tolist())

else:
    print("جدول wadq_integrated_df غير موجود.")

if "wadq_ticker_news_df" in globals():

    print("\n📰 أعمدة الأخبار:")
    print(wadq_ticker_news_df.columns.tolist())

    if "published" in wadq_ticker_news_df.columns:
        print("\n⏰ أحدث أوقات نشر الأخبار:")
        display(
            wadq_ticker_news_df[
                ["ticker", "news_title", "published"]
            ].head(10)
        )

else:
    print("جدول الأخبار غير موجود.")

🌧️ الودق AI - فحص البيانات
==================================================

📊 أعمدة التحليل الفني والتقرير الموحد:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'news_count', 'positive_news', 'negative_news', 'neutral_news', 'news_status']

📰 أعمدة الأخبار:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

⏰ أحدث أوقات نشر الأخبار:

,ticker,news_title,published
0,QQQ,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...","Sun, 11 Oct 2026 18:45:06 GMT"
1,SPY,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...","Sun, 11 Oct 2026 18:45:06 GMT"
2,SPY,"The S&P 500 Hits a New Record High, Powered by...","Tue, 06 Oct 2026 21:33:00 GMT"
3,SPY,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...","Wed, 07 Oct 2026 20:11:09 GMT"
4,SPY,"S&P 500, Nasdaq end lower as crude prices jump...","Thu, 08 Oct 2026 23:09:38 GMT"
5,SPY,S&P 500 and Nasdaq surge to record highs after...,"Tue, 06 Oct 2026 20:38:00 GMT"
6,SPY,U.S. stock market drops: S&P 500 and Nasdaq fa...,"Thu, 08 Oct 2026 15:04:08 GMT"
7,QQQ,"Stock Market Today: S&P 500, Dow Jones, Nasdaq...","Fri, 09 Oct 2026 13:21:00 GMT"
8,SPY,"Stock Market Today: S&P 500, Dow Jones, Nasdaq...","Fri, 09 Oct 2026 13:21:00 GMT"
9,SPY,"S&P 500 dips, Nasdaq higher after data shows m...","Wed, 30 Sep 2026 07:00:00 GMT"

In [ ]:
# 🌧️ الودق AI - فحص البيانات قبل التقييم المتقدم

print("🌧️ الودق AI | فحص الجداول")
print("=" * 50)

if "wadq_integrated_df" in globals():
    print("\n📊 أعمدة التحليل الفني:")
    print(wadq_integrated_df.columns.tolist())

    print("\nعينة من بيانات التحليل الفني:")
    display(wadq_integrated_df.head(3))

if "wadq_ticker_news_df" in globals():
    print("\n📰 أعمدة الأخبار:")
    print(wadq_ticker_news_df.columns.tolist())

    print("\nعدد الأخبار:", len(wadq_ticker_news_df))

    if "published" in wadq_ticker_news_df.columns:
        news_check = wadq_ticker_news_df[
            ["ticker", "sentiment", "published"]
        ].copy()

        news_check["published"] = pd.to_datetime(
            news_check["published"],
            errors="coerce",
            utc=True
        )

        print("\nأحدث 10 أخبار حسب وقت النشر:")
        display(
            news_check.sort_values(
                "published",
                ascending=False
            ).head(10)
        )

else:
    print("\n⚠️ جدول الأخبار غير موجود.")

🌧️ الودق AI | فحص الجداول
==================================================

📊 أعمدة التحليل الفني:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'news_count', 'positive_news', 'negative_news', 'neutral_news', 'news_status']

عينة من بيانات التحليل الفني:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,news_count,positive_news,negative_news,neutral_news,news_status
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,45,9,1,35,توجد أخبار
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,20,2,0,18,توجد أخبار
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,1,0,0,1,توجد أخبار

📰 أعمدة الأخبار:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

عدد الأخبار: 197

أحدث 10 أخبار حسب وقت النشر:

   ticker          sentiment                 published
0     QQQ  محايد أو غير واضح 2026-10-11 18:45:06+00:00
1     SPY  محايد أو غير واضح 2026-10-11 18:45:06+00:00
23    SPY       إيجابي مبدئي 2026-10-11 07:51:12+00:00
58    SPY  محايد أو غير واضح 2026-10-09 21:04:49+00:00
12    SPY       إيجابي مبدئي 2026-10-09 13:35:30+00:00
7     QQQ       إيجابي مبدئي 2026-10-09 13:21:00+00:00
8     SPY       إيجابي مبدئي 2026-10-09 13:21:00+00:00
4     SPY  محايد أو غير واضح 2026-10-08 23:09:38+00:00
6     SPY         سلبي مبدئي 2026-10-08 15:04:08+00:00
3     SPY  محايد أو غير واضح 2026-10-07 20:11:09+00:00

In [ ]:
# 🌧️ الودق AI
# فحص أعمدة التحليل الفني فقط

print("🌧️ الودق AI - فحص التحليل الفني")
print("=" * 50)

if "wadq_integrated_df" in globals():

    print("\nأسماء الأعمدة:")
    print(wadq_integrated_df.columns.tolist())

    print("\nعينة من أول 3 أسهم:")
    display(wadq_integrated_df.head(3))

else:
    print("⚠️ جدول wadq_integrated_df غير موجود.")

🌧️ الودق AI - فحص التحليل الفني
==================================================

أسماء الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'news_count', 'positive_news', 'negative_news', 'neutral_news', 'news_status']

عينة من أول 3 أسهم:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,news_count,positive_news,negative_news,neutral_news,news_status
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,45,9,1,35,توجد أخبار
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,20,2,0,18,توجد أخبار
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,1,0,0,1,توجد أخبار

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة الثامنة: التقييم الذكي الموحد
# لا يغيّر الجداول الأصلية
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - التقييم الذكي الموحد")
print("=" * 55)

if "wadq_integrated_df" not in globals() or "wadq_ticker_news_df" not in globals():
    print("⚠️ تأكدي من تشغيل خلايا التحليل الفني والأخبار والتقرير الموحد.")

else:
    # نسخ مستقلة لحماية البيانات الأصلية
    tech = wadq_integrated_df.copy()
    news = wadq_ticker_news_df.copy()

    tech.columns = tech.columns.astype(str).str.strip()
    news.columns = news.columns.astype(str).str.strip()

    # تحديد عمود رمز السهم
    ticker_col = next(
        (c for c in ["الرمز", "ticker", "Ticker", "symbol", "Symbol"]
         if c in tech.columns),
        None
    )

    required_news = {"ticker", "sentiment", "published"}

    if ticker_col is None:
        print("⚠️ لم يتم العثور على عمود رمز السهم.")
        print("الأعمدة المتاحة:", tech.columns.tolist())

    elif not required_news.issubset(news.columns):
        print("⚠️ بعض أعمدة الأخبار المطلوبة غير موجودة.")
        print("أعمدة الأخبار:", news.columns.tolist())

    else:
        # توحيد رموز الأسهم
        tech["_ticker_key"] = (
            tech[ticker_col].astype(str).str.upper().str.strip()
        )
        news["_ticker_key"] = (
            news["ticker"].astype(str).str.upper().str.strip()
        )

        # تحويل تواريخ الأخبار
        news["_published_dt"] = pd.to_datetime(
            news["published"], errors="coerce", utc=True
        )

        # حساب عمر الخبر بالساعات
        now_utc = pd.Timestamp.now(tz="UTC")
        news["_age_hours"] = (
            now_utc - news["_published_dt"]
        ).dt.total_seconds() / 3600

        # استبعاد الأخبار ذات التواريخ المستقبلية أو غير الصالحة
        news = news[
            news["_published_dt"].notna()
            & (news["_age_hours"] >= 0)
        ].copy()

        # إعطاء الأخبار الحديثة وزنًا أعلى
        news["_weight"] = 0.5 ** (
            news["_age_hours"] / 24
        )

        sentiment = news["sentiment"].astype(str)

        news["_positive_weight"] = (
            sentiment.str.contains("إيجابي", na=False).astype(int)
            * news["_weight"]
        )

        news["_negative_weight"] = (
            sentiment.str.contains("سلبي", na=False).astype(int)
            * news["_weight"]
        )

        news["_neutral_weight"] = (
            sentiment.str.contains("محايد|غير واضح", na=False).astype(int)
            * news["_weight"]
        )

        # تلخيص الأخبار الموزونة لكل سهم
        summary = news.groupby("_ticker_key").agg(
            عدد_الأخبار_الحديثة=("_ticker_key", "size"),
            وزن_الأخبار_الإيجابية=("_positive_weight", "sum"),
            وزن_الأخبار_السلبية=("_negative_weight", "sum"),
            وزن_الأخبار_المحايدة=("_neutral_weight", "sum")
        ).reset_index()

        result = tech.merge(
            summary, on="_ticker_key", how="left"
        )

        count_cols = [
            "عدد_الأخبار_الحديثة",
            "وزن_الأخبار_الإيجابية",
            "وزن_الأخبار_السلبية",
            "وزن_الأخبار_المحايدة"
        ]

        result[count_cols] = result[count_cols].fillna(0)

        # تقييم الأخبار وفق الأوزان الزمنية
        result["إشارة الأخبار"] = "لا توجد أخبار كافية"

        has_news = result["عدد_الأخبار_الحديثة"] > 0
        pos = result["وزن_الأخبار_الإيجابية"]
        neg = result["وزن_الأخبار_السلبية"]

        result.loc[has_news & (pos > neg), "إشارة الأخبار"] = "إيجابية مبدئيًا"
        result.loc[has_news & (neg > pos), "إشارة الأخبار"] = "سلبية مبدئيًا"
        result.loc[has_news & (pos == neg), "إشارة الأخبار"] = "محايدة أو مختلطة"

        # قراءة الاتجاه الفني الموجود
        trend_col = next(
            (c for c in ["الاتجاه", "trend", "Trend"] if c in result.columns),
            None
        )

        result["التقييم الموحد"] = "إشارات مختلطة أو بيانات غير كافية"

        if trend_col is not None:
            trend = result[trend_col].astype(str).str.strip()

            bullish = trend.str.contains(
                "صاعد|إيجابي|bullish|uptrend",
                case=False, na=False
            )
            bearish = trend.str.contains(
                "هابط|سلبي|bearish|downtrend",
                case=False, na=False
            )

            result.loc[
                bullish & (result["إشارة الأخبار"] == "إيجابية مبدئيًا"),
                "التقييم الموحد"
            ] = "توافق إيجابي مبدئي"

            result.loc[
                bearish & (result["إشارة الأخبار"] == "سلبية مبدئيًا"),
                "التقييم الموحد"
            ] = "توافق سلبي مبدئي"

            result.loc[
                bullish & (result["إشارة الأخبار"] == "سلبية مبدئيًا"),
                "التقييم الموحد"
            ] = "تعارض: الاتجاه صاعد والأخبار سلبية"

            result.loc[
                bearish & (result["إشارة الأخبار"] == "إيجابية مبدئيًا"),
                "التقييم الموحد"
            ] = "تعارض: الاتجاه هابط والأخبار إيجابية"

        # إنشاء الجدول النهائي المستقل
        wadq_smart_report = result.drop(
            columns=["_ticker_key"], errors="ignore"
        )

        print("✅ تم إنشاء التقرير الذكي الموحد.")
        print("عدد الأسهم:", len(wadq_smart_report))
        print("ملاحظة: التقييم استرشادي وليس توصية شراء أو بيع.")

        display(wadq_smart_report)

        print("\nاسم الجدول: wadq_smart_report")

🌧️ الودق AI - التقييم الذكي الموحد
=======================================================
✅ تم إنشاء التقرير الذكي الموحد.
عدد الأسهم: 9
ملاحظة: التقييم استرشادي وليس توصية شراء أو بيع.

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,...,positive_news,negative_news,neutral_news,news_status,عدد_الأخبار_الحديثة,وزن_الأخبار_الإيجابية,وزن_الأخبار_السلبية,وزن_الأخبار_المحايدة,إشارة الأخبار,التقييم الموحد
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,...,9,1,35,توجد أخبار,45,2.308699e-80,4.061507e-67,1.417292e-14,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,...,2,0,18,توجد أخبار,20,1.769395e-110,0.000000e+00,1.126351e-21,إيجابية مبدئيًا,توافق إيجابي مبدئي
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,...,0,0,1,توجد أخبار,1,0.000000e+00,0.000000e+00,2.109284e-117,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,...,7,1,25,توجد أخبار,33,2.308699e-80,4.061507e-67,1.453080e-19,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,...,4,0,13,توجد أخبار,17,6.257742e-100,0.000000e+00,1.205547e-21,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,...,5,0,16,توجد أخبار,21,2.308699e-80,0.000000e+00,2.304922e-33,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,...,1,0,2,توجد أخبار,3,1.318302e-118,0.000000e+00,1.981497e-08,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,...,2,0,1,توجد أخبار,3,2.003276e-01,0.000000e+00,9.335626e-01,إيجابية مبدئيًا,توافق إيجابي مبدئي
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,...,15,12,27,توجد أخبار,54,1.146833e+00,1.704521e-01,1.387934e+00,إيجابية مبدئيًا,توافق إيجابي مبدئي

اسم الجدول: wadq_smart_report

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة التاسعة: لوحة المتابعة المختصرة
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - لوحة متابعة الأسهم")
print("=" * 60)

if "wadq_smart_report" not in globals():

    print("⚠️ شغّلي كود المرحلة الثامنة أولًا.")

else:
    df = wadq_smart_report.copy()

    # اختيار الأعمدة المتاحة تلقائيًا
    preferred_columns = [
        "السهم",
        "الرمز",
        "آخر إغلاق",
        "الاتجاه",
        "RSI",
        "حالة RSI",
        "MACD",
        "إشارة MACD",
        "news_count",
        "positive_news",
        "negative_news",
        "neutral_news",
        "عدد_الأخبار_الحديثة",
        "وزن_الأخبار_الإيجابية",
        "وزن_الأخبار_السلبية",
        "إشارة الأخبار",
        "التقييم الموحد"
    ]

    available_columns = [
        c for c in preferred_columns
        if c in df.columns
    ]

    if not available_columns:
        print("⚠️ لم يتم العثور على الأعمدة المطلوبة.")
        print("الأعمدة المتاحة:")
        print(df.columns.tolist())

    else:
        wadq_dashboard_df = df[available_columns].copy()

        print("✅ تم إنشاء لوحة المتابعة.")
        print("عدد الأسهم:", len(wadq_dashboard_df))
        print("عدد الأعمدة:", len(wadq_dashboard_df.columns))

        display(wadq_dashboard_df)

        print("\nاسم الجدول:")
        print("wadq_dashboard_df")

🌧️ الودق AI - لوحة متابعة الأسهم
============================================================
✅ تم إنشاء لوحة المتابعة.
عدد الأسهم: 9
عدد الأعمدة: 17

,السهم,الرمز,آخر إغلاق,الاتجاه,RSI,حالة RSI,MACD,إشارة MACD,news_count,positive_news,negative_news,neutral_news,عدد_الأخبار_الحديثة,وزن_الأخبار_الإيجابية,وزن_الأخبار_السلبية,إشارة الأخبار,التقييم الموحد
0,إنفيديا,NVDA,229.28,صاعد,53.03,ضمن النطاق المتوسط,3.9880,3.8692,45,9,1,35,45,2.308699e-80,4.061507e-67,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية
1,تسلا,TSLA,382.70,صاعد,59.74,ضمن النطاق المتوسط,5.0724,4.0030,20,2,0,18,20,1.769395e-110,0.000000e+00,إيجابية مبدئيًا,توافق إيجابي مبدئي
2,آبل,AAPL,336.64,صاعد,56.14,ضمن النطاق المتوسط,3.4365,3.8828,1,0,0,1,1,0.000000e+00,0.000000e+00,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية
3,مايكروسوفت,MSFT,535.07,صاعد,67.53,ضمن النطاق المتوسط,10.6946,9.2052,33,7,1,25,33,2.308699e-80,4.061507e-67,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية
4,أمازون,AMZN,262.43,مختلط,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,17,4,0,13,17,6.257742e-100,0.000000e+00,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية
5,ألفابت,GOOGL,351.66,مختلط,56.39,ضمن النطاق المتوسط,1.2863,0.3666,21,5,0,16,21,2.308699e-80,0.000000e+00,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية
6,ميتا,META,718.67,مختلط,56.85,ضمن النطاق المتوسط,25.1409,30.9242,3,1,0,2,3,1.318302e-118,0.000000e+00,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية
7,ناسداك 100,QQQ,751.27,صاعد,61.05,ضمن النطاق المتوسط,9.7563,8.9125,3,2,0,1,3,2.003276e-01,0.000000e+00,إيجابية مبدئيًا,توافق إيجابي مبدئي
8,ستاندرد آند بورز 500,SPY,778.57,صاعد,60.49,ضمن النطاق المتوسط,3.6626,2.5600,54,15,12,27,54,1.146833e+00,1.704521e-01,إيجابية مبدئيًا,توافق إيجابي مبدئي

اسم الجدول:
wadq_dashboard_df

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة العاشرة: حفظ التقرير في Excel
# =====================================================

import os
import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - حفظ التقرير")
print("=" * 50)

if "wadq_dashboard_df" not in globals():

    print("⚠️ شغّلي خلية لوحة المتابعة أولًا.")

else:
    # إنشاء نسخة مستقلة للحفظ
    wadq_excel_df = wadq_dashboard_df.copy()

    # اسم الملف
    file_path = "/content/wadq_ai_dashboard.xlsx"

    # حفظ التقرير
    with pd.ExcelWriter(
        file_path,
        engine="openpyxl"
    ) as writer:

        wadq_excel_df.to_excel(
            writer,
            sheet_name="لوحة المتابعة",
            index=False
        )

        # إضافة ورقة للتقرير الذكي الكامل إن كان متاحًا
        if "wadq_smart_report" in globals():
            wadq_smart_report.to_excel(
                writer,
                sheet_name="التقرير الذكي",
                index=False
            )

    print("✅ تم حفظ ملف Excel بنجاح!")
    print("اسم الملف: wadq_ai_dashboard.xlsx")
    print("عدد الأسهم:", len(wadq_excel_df))

    # تنزيل الملف إلى جهازك
    from google.colab import files
    files.download(file_path)

🌧️ الودق AI - حفظ التقرير
==================================================
✅ تم حفظ ملف Excel بنجاح!
اسم الملف: wadq_ai_dashboard.xlsx
عدد الأسهم: 9

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة 11: فحص إمكانية تحديث أسعار الأسهم
# =====================================================

import yfinance as yf
import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - فحص تحديث أسعار الأسهم")
print("=" * 50)

wadq_tickers = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY"
]

wadq_latest_prices = yf.download(
    wadq_tickers,
    period="5d",
    interval="1d",
    auto_adjust=True,
    progress=False,
    threads=True
)

if wadq_latest_prices.empty:
    print("⚠️ لم تصل بيانات الأسعار. قد تكون هناك مشكلة اتصال.")
else:
    wadq_close = wadq_latest_prices["Close"]

    wadq_latest_summary = (
        wadq_close
        .ffill()
        .iloc[-1]
        .rename("آخر سعر متاح")
        .reset_index()
    )

    wadq_latest_summary.columns = ["رمز السهم", "آخر سعر متاح"]

    print("✅ تم جلب أحدث أسعار الإغلاق المتاحة.")
    print("ملاحظة: قد تكون الأسعار متأخرة وليست أسعارًا لحظية.")

    display(wadq_latest_summary)

🌧️ الودق AI - فحص تحديث أسعار الأسهم
==================================================
✅ تم جلب أحدث أسعار الإغلاق المتاحة.
ملاحظة: قد تكون الأسعار متأخرة وليست أسعارًا لحظية.

  رمز السهم  آخر سعر متاح
0      AAPL    336.640015
1      AMZN    262.429993
2     GOOGL    351.660004
3      META    718.669983
4      MSFT    535.070007
5      NVDA    229.279999
6       QQQ    751.270020
7       SPY    778.570007
8      TSLA    382.700012

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة 12: مقارنة الأسعار الجديدة بالتقرير السابق
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - مقارنة الأسعار")
print("=" * 50)

if "wadq_latest_summary" not in globals():
    print("⚠️ شغّلي خلية تحديث الأسعار أولًا.")

elif "wadq_integrated_df" not in globals():
    print("⚠️ جدول التحليل الفني السابق غير موجود.")

else:
    # نسخ مستقلة
    latest = wadq_latest_summary.copy()
    old = wadq_integrated_df.copy()

    # تنظيف أسماء الأعمدة
    latest.columns = latest.columns.astype(str).str.strip()
    old.columns = old.columns.astype(str).str.strip()

    # تحديد عمود الرمز والسعر السابق
    ticker_col = next(
        (c for c in ["الرمز", "ticker", "Ticker", "symbol", "Symbol"]
         if c in old.columns),
        None
    )

    price_col = next(
        (c for c in ["آخر إغلاق", "last_close", "Close", "السعر"]
         if c in old.columns),
        None
    )

    if ticker_col is None or price_col is None:
        print("⚠️ لم يتم التعرف على عمود الرمز أو السعر السابق.")
        print("أعمدة التقرير:", old.columns.tolist())

    else:
        # توحيد رموز الأسهم
        latest["_ticker"] = (
            latest["رمز السهم"].astype(str).str.upper().str.strip()
        )

        old["_ticker"] = (
            old[ticker_col].astype(str).str.upper().str.strip()
        )

        # اختيار السعر السابق
        old["_old_price"] = pd.to_numeric(
            old[price_col], errors="coerce"
        )

        latest["_new_price"] = pd.to_numeric(
            latest["آخر سعر متاح"], errors="coerce"
        )

        # دمج البيانات في جدول مستقل
        wadq_price_comparison = latest[
            ["_ticker", "_new_price"]
        ].merge(
            old[["_ticker", "_old_price"]],
            on="_ticker",
            how="left"
        )

        wadq_price_comparison.rename(
            columns={
                "_ticker": "رمز السهم",
                "_old_price": "السعر السابق",
                "_new_price": "أحدث سعر متاح"
            },
            inplace=True
        )

        # حساب الفرق والتغير النسبي
        wadq_price_comparison["فرق السعر"] = (
            wadq_price_comparison["أحدث سعر متاح"]
            - wadq_price_comparison["السعر السابق"]
        )

        wadq_price_comparison["التغير %"] = (
            wadq_price_comparison["فرق السعر"]
            / wadq_price_comparison["السعر السابق"]
            * 100
        )

        print("✅ تم إنشاء جدول مقارنة الأسعار.")
        print("تنبيه: المقارنة بين بيانات المصدر والتقرير السابق،")
        print("وقد تختلف التواريخ أو توقيت تحديث الأسعار.")

        display(wadq_price_comparison)

        print("\nاسم الجدول: wadq_price_comparison")

🌧️ الودق AI - مقارنة الأسعار
==================================================
✅ تم إنشاء جدول مقارنة الأسعار.
تنبيه: المقارنة بين بيانات المصدر والتقرير السابق،
وقد تختلف التواريخ أو توقيت تحديث الأسعار.

  رمز السهم  أحدث سعر متاح  السعر السابق  فرق السعر      التغير %
0      AAPL     336.640015        336.64   0.000015  4.351366e-06
1      AMZN     262.429993        262.43  -0.000007 -2.790923e-06
2     GOOGL     351.660004        351.66   0.000004  1.041378e-06
3      META     718.669983        718.67  -0.000017 -2.377982e-06
4      MSFT     535.070007        535.07   0.000007  1.368834e-06
5      NVDA     229.279999        229.28  -0.000001 -5.324072e-07
6       QQQ     751.270020        751.27   0.000020  2.599764e-06
7       SPY     778.570007        778.57   0.000007  9.407271e-07
8      TSLA     382.700012        382.70   0.000012  3.189713e-06

اسم الجدول: wadq_price_comparison

In [ ]:
print("جدول مقارنة الأسعار:")
print(wadq_price_comparison.columns.tolist())

print("\nجدول التقرير الذكي:")
print(wadq_smart_report.columns.tolist())

print("\nجدول الأخبار:")
print(wadq_ticker_news_df.columns.tolist())

جدول مقارنة الأسعار:
['رمز السهم', 'أحدث سعر متاح', 'السعر السابق', 'فرق السعر', 'التغير %']

جدول التقرير الذكي:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'news_count', 'positive_news', 'negative_news', 'neutral_news', 'news_status', 'عدد_الأخبار_الحديثة', 'وزن_الأخبار_الإيجابية', 'وزن_الأخبار_السلبية', 'وزن_الأخبار_المحايدة', 'إشارة الأخبار', 'التقييم الموحد']

جدول الأخبار:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

In [ ]:
print("أعمدة التقرير الذكي كاملة:")
for col in wadq_smart_report.columns:
    print(repr(col))

أعمدة التقرير الذكي كاملة:
'السهم'
'الرمز'
'آخر إغلاق'
'المتوسط 20'
'المتوسط 50'
'RSI'
'حالة RSI'
'MACD'
'إشارة MACD'
'الاتجاه'
'news_count'
'positive_news'
'negative_news'
'neutral_news'
'news_status'
'عدد_الأخبار_الحديثة'
'وزن_الأخبار_الإيجابية'
'وزن_الأخبار_السلبية'
'وزن_الأخبار_المحايدة'
'إشارة الأخبار'
'التقييم الموحد'

In [ ]:
# ==========================================================
# 🌧️ الودق AI
# المرحلة التالية: التقرير النهائي الموحد للأخبار والأسعار
# إنشاء جدول جديد مع المحافظة على الجداول الأصلية
# ==========================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - التقرير النهائي الذكي")
print("=" * 60)

# 1. التأكد من وجود الجداول المطلوبة
required = [
    "wadq_smart_report",
    "wadq_ticker_news_df",
    "wadq_price_comparison"
]

missing = [name for name in required if name not in globals()]

if missing:
    print("⚠️ الجداول التالية غير متاحة:", missing)

else:
    # 2. إنشاء نسخ مستقلة
    final_df = wadq_smart_report.copy()
    news_df = wadq_ticker_news_df.copy()
    price_df = wadq_price_comparison.copy()

    # 3. تنظيف أسماء الأعمدة
    for df in [final_df, news_df, price_df]:
        df.columns = df.columns.astype(str).str.strip()

    # 4. التحقق من الأعمدة الأساسية
    if "الرمز" not in final_df.columns:
        print("⚠️ لم يُعثر على عمود الرمز في التقرير الذكي.")
        print(final_df.columns.tolist())

    elif not {"ticker", "sentiment"}.issubset(news_df.columns):
        print("⚠️ أعمدة الأخبار غير مكتملة.")
        print(news_df.columns.tolist())

    elif "رمز السهم" not in price_df.columns:
        print("⚠️ لم يُعثر على رمز السهم في جدول الأسعار.")
        print(price_df.columns.tolist())

    else:
        # 5. توحيد رموز الأسهم
        final_df["_ticker"] = (
            final_df["الرمز"]
            .astype(str).str.upper().str.strip()
        )

        news_df["_ticker"] = (
            news_df["ticker"]
            .astype(str).str.upper().str.strip()
        )

        price_df["_ticker"] = (
            price_df["رمز السهم"]
            .astype(str).str.upper().str.strip()
        )

        # 6. تلخيص الأخبار لكل سهم
        news_df["_positive"] = (
            news_df["sentiment"].eq("إيجابي مبدئي").astype(int)
        )

        news_df["_negative"] = (
            news_df["sentiment"].eq("سلبي مبدئي").astype(int)
        )

        news_df["_neutral"] = (
            news_df["sentiment"].eq("محايد أو غير واضح").astype(int)
        )

        news_summary = (
            news_df.groupby("_ticker")
            .agg(
                عدد_الأخبار=("_ticker", "size"),
                الأخبار_الإيجابية=("_positive", "sum"),
                الأخبار_السلبية=("_negative", "sum"),
                الأخبار_المحايدة=("_neutral", "sum")
            )
            .reset_index()
        )

        # 7. إضافة ملخص الأخبار إلى نسخة التقرير
        final_df = final_df.merge(
            news_summary,
            on="_ticker",
            how="left"
        )

        # 8. إضافة أحدث الأسعار والتغيرات المتاحة
        price_columns = [
            c for c in [
                "_ticker",
                "أحدث سعر متاح",
                "فرق السعر",
                "التغير %"
            ]
            if c in price_df.columns
        ]

        if len(price_columns) > 1:
            final_df = final_df.merge(
                price_df[price_columns].drop_duplicates(
                    subset="_ticker"
                ),
                on="_ticker",
                how="left"
            )

        # 9. معالجة غياب الأخبار
        count_columns = [
            "عدد_الأخبار",
            "الأخبار_الإيجابية",
            "الأخبار_السلبية",
            "الأخبار_المحايدة"
        ]

        for col in count_columns:
            final_df[col] = final_df[col].fillna(0).astype(int)

        # 10. تحديد الانطباع الأولي للأخبار
        def classify_news(row):
            if row["عدد_الأخبار"] == 0:
                return "لا توجد أخبار مرتبطة"

            positive = row["الأخبار_الإيجابية"]
            negative = row["الأخبار_السلبية"]

            if positive > negative:
                return "الأخبار إيجابية مبدئيًا"
            elif negative > positive:
                return "الأخبار سلبية مبدئيًا"
            else:
                return "الأخبار مختلطة أو غير حاسمة"

        final_df["ملخص الأخبار"] = final_df.apply(
            classify_news,
            axis=1
        )

        # 11. المحافظة على الرموز وإزالة العمود المساعد
        final_df.drop(columns=["_ticker"], inplace=True)

        # 12. عرض التقرير النهائي
        wadq_final_ai_report = final_df.copy()

        print("✅ تم إنشاء التقرير النهائي بنجاح")
        print("عدد الأسهم:", len(wadq_final_ai_report))
        print("عدد الأعمدة:", len(wadq_final_ai_report.columns))
        print("\n📊 التقرير النهائي:")

        display(wadq_final_ai_report)

        print("\nاسم الجدول: wadq_final_ai_report")
        print("⚠️ هذا التقرير تحليلي وليس توصية شراء أو بيع.")

🌧️ الودق AI - التقرير النهائي الذكي
============================================================
✅ تم إنشاء التقرير النهائي بنجاح
عدد الأسهم: 9
عدد الأعمدة: 29

📊 التقرير النهائي:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,...,إشارة الأخبار,التقييم الموحد,عدد_الأخبار,الأخبار_الإيجابية,الأخبار_السلبية,الأخبار_المحايدة,أحدث سعر متاح,فرق السعر,التغير %,ملخص الأخبار
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,...,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,45,9,1,35,229.279999,-0.000001,-5.324072e-07,الأخبار إيجابية مبدئيًا
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,20,2,0,18,382.700012,0.000012,3.189713e-06,الأخبار إيجابية مبدئيًا
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,...,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية,1,0,0,1,336.640015,0.000015,4.351366e-06,الأخبار مختلطة أو غير حاسمة
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,...,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,33,7,1,25,535.070007,0.000007,1.368834e-06,الأخبار إيجابية مبدئيًا
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,17,4,0,13,262.429993,-0.000007,-2.790923e-06,الأخبار إيجابية مبدئيًا
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,21,5,0,16,351.660004,0.000004,1.041378e-06,الأخبار إيجابية مبدئيًا
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,3,1,0,2,718.669983,-0.000017,-2.377982e-06,الأخبار إيجابية مبدئيًا
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,3,2,0,1,751.270020,0.000020,2.599764e-06,الأخبار إيجابية مبدئيًا
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,54,15,12,27,778.570007,0.000007,9.407271e-07,الأخبار إيجابية مبدئيًا

اسم الجدول: wadq_final_ai_report
⚠️ هذا التقرير تحليلي وليس توصية شراء أو بيع.

In [ ]:
# ==========================================================
# 🌧️ الودق AI
# المرحلة التالية: ترتيب الأسهم حسب توافق الأخبار والتحليل الفني
# ==========================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - ترتيب الأسهم الذكي")
print("=" * 55)

if "wadq_final_ai_report" not in globals():
    print("⚠️ شغّلي كود التقرير النهائي أولًا.")

else:
    # إنشاء نسخة مستقلة
    wadq_ranking_report = wadq_final_ai_report.copy()

    # تحديد أعمدة الاتجاه الفني
    trend_col = next(
        (
            c for c in ["الاتجاه", "الإشارة", "التوصية الفنية"]
            if c in wadq_ranking_report.columns
        ),
        None
    )

    # التأكد من توفر ملخص الأخبار
    if "ملخص الأخبار" not in wadq_ranking_report.columns:
        print("⚠️ عمود ملخص الأخبار غير موجود.")

    elif trend_col is None:
        print("⚠️ لم أتعرف على عمود الاتجاه الفني.")
        print("أعمدة التقرير:")
        print(wadq_ranking_report.columns.tolist())

    else:
        # تقييم مبدئي لتوافق الإشارات
        def evaluate_stock(row):
            trend = str(row[trend_col]).strip()
            news = str(row["ملخص الأخبار"]).strip()

            if "صاعد" in trend and "إيجابية" in news:
                return "توافق إيجابي مبدئي"

            elif "هابط" in trend and "سلبية" in news:
                return "توافق سلبي مبدئي"

            elif "لا توجد أخبار" in news:
                return "الأخبار غير كافية"

            else:
                return "إشارات مختلطة أو غير حاسمة"

        wadq_ranking_report["توافق الأخبار والتحليل"] = (
            wadq_ranking_report.apply(evaluate_stock, axis=1)
        )

        # ترتيب النتائج حسب توافق الإشارات
        priority = {
            "توافق إيجابي مبدئي": 1,
            "توافق سلبي مبدئي": 2,
            "إشارات مختلطة أو غير حاسمة": 3,
            "الأخبار غير كافية": 4
        }

        wadq_ranking_report["_priority"] = (
            wadq_ranking_report["توافق الأخبار والتحليل"]
            .map(priority)
            .fillna(5)
        )

        wadq_ranking_report = (
            wadq_ranking_report
            .sort_values("_priority")
            .drop(columns="_priority")
            .reset_index(drop=True)
        )

        print("✅ اكتمل ترتيب الأسهم مبدئيًا.")
        print("عدد الأسهم:", len(wadq_ranking_report))
        display(wadq_ranking_report)

        print("\nاسم الجدول: wadq_ranking_report")
        print("ملاحظة: الترتيب تحليلي أولي وليس توصية استثمارية.")

🌧️ الودق AI - ترتيب الأسهم الذكي
=======================================================
✅ اكتمل ترتيب الأسهم مبدئيًا.
عدد الأسهم: 9

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,...,التقييم الموحد,عدد_الأخبار,الأخبار_الإيجابية,الأخبار_السلبية,الأخبار_المحايدة,أحدث سعر متاح,فرق السعر,التغير %,ملخص الأخبار,توافق الأخبار والتحليل
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,...,تعارض: الاتجاه صاعد والأخبار سلبية,45,9,1,35,229.279999,-0.000001,-5.324072e-07,الأخبار إيجابية مبدئيًا,توافق إيجابي مبدئي
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,...,توافق إيجابي مبدئي,20,2,0,18,382.700012,0.000012,3.189713e-06,الأخبار إيجابية مبدئيًا,توافق إيجابي مبدئي
2,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,...,تعارض: الاتجاه صاعد والأخبار سلبية,33,7,1,25,535.070007,0.000007,1.368834e-06,الأخبار إيجابية مبدئيًا,توافق إيجابي مبدئي
3,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,...,توافق إيجابي مبدئي,3,2,0,1,751.270020,0.000020,2.599764e-06,الأخبار إيجابية مبدئيًا,توافق إيجابي مبدئي
4,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,...,توافق إيجابي مبدئي,54,15,12,27,778.570007,0.000007,9.407271e-07,الأخبار إيجابية مبدئيًا,توافق إيجابي مبدئي
5,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,...,إشارات مختلطة أو بيانات غير كافية,1,0,0,1,336.640015,0.000015,4.351366e-06,الأخبار مختلطة أو غير حاسمة,إشارات مختلطة أو غير حاسمة
6,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,...,إشارات مختلطة أو بيانات غير كافية,21,5,0,16,351.660004,0.000004,1.041378e-06,الأخبار إيجابية مبدئيًا,إشارات مختلطة أو غير حاسمة
7,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,...,إشارات مختلطة أو بيانات غير كافية,17,4,0,13,262.429993,-0.000007,-2.790923e-06,الأخبار إيجابية مبدئيًا,إشارات مختلطة أو غير حاسمة
8,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,...,إشارات مختلطة أو بيانات غير كافية,3,1,0,2,718.669983,-0.000017,-2.377982e-06,الأخبار إيجابية مبدئيًا,إشارات مختلطة أو غير حاسمة

اسم الجدول: wadq_ranking_report
ملاحظة: الترتيب تحليلي أولي وليس توصية استثمارية.

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة التالية: ملخص أفضل الأسهم توافقًا
# دون تعديل الجداول السابقة
# =====================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - ملخص توافق الأخبار والتحليل الفني")
print("=" * 60)

if "wadq_ranking_report" not in globals():
    print("⚠️ جدول الترتيب غير موجود. شغّلي خليته السابقة أولًا.")

else:
    # نسخة مستقلة للمحافظة على الجدول الأصلي
    wadq_signal_summary = wadq_ranking_report.copy()

    # تحديد الأعمدة المطلوبة
    required_cols = [
        "الرمز",
        "الاتجاه",
        "ملخص الأخبار",
        "توافق الأخبار والتحليل"
    ]

    missing_cols = [
        c for c in required_cols
        if c not in wadq_signal_summary.columns
    ]

    if missing_cols:
        print("الأعمدة التالية غير موجودة:", missing_cols)
        print("أسماء الأعمدة المتاحة:")
        print(wadq_signal_summary.columns.tolist())

    else:
        # عرض ملخص مختصر
        wadq_signal_summary = wadq_signal_summary[
            required_cols
        ].copy()

        print("عدد الأسهم:", len(wadq_signal_summary))
        print("\nنتائج توافق الأخبار والتحليل الفني:")

        display(wadq_signal_summary)

        print("\nتوزيع حالات التوافق:")
        display(
            wadq_signal_summary[
                "توافق الأخبار والتحليل"
            ].value_counts().rename_axis(
                "حالة التوافق"
            ).reset_index(name="عدد الأسهم")
        )

        print("\n✅ اسم الجدول: wadq_signal_summary")
        print("هذا الملخص تحليلي، وليس توصية شراء أو بيع.")

🌧️ الودق AI - ملخص توافق الأخبار والتحليل الفني
============================================================
عدد الأسهم: 9

نتائج توافق الأخبار والتحليل الفني:

   الرمز الاتجاه                 ملخص الأخبار      توافق الأخبار والتحليل
0   NVDA    صاعد      الأخبار إيجابية مبدئيًا          توافق إيجابي مبدئي
1   TSLA    صاعد      الأخبار إيجابية مبدئيًا          توافق إيجابي مبدئي
2   MSFT    صاعد      الأخبار إيجابية مبدئيًا          توافق إيجابي مبدئي
3    QQQ    صاعد      الأخبار إيجابية مبدئيًا          توافق إيجابي مبدئي
4    SPY    صاعد      الأخبار إيجابية مبدئيًا          توافق إيجابي مبدئي
5   AAPL    صاعد  الأخبار مختلطة أو غير حاسمة  إشارات مختلطة أو غير حاسمة
6  GOOGL   مختلط      الأخبار إيجابية مبدئيًا  إشارات مختلطة أو غير حاسمة
7   AMZN   مختلط      الأخبار إيجابية مبدئيًا  إشارات مختلطة أو غير حاسمة
8   META   مختلط      الأخبار إيجابية مبدئيًا  إشارات مختلطة أو غير حاسمة

توزيع حالات التوافق:

                 حالة التوافق  عدد الأسهم
0          توافق إيجابي مبدئي           5
1  إشارات مختلطة أو غير حاسمة           4

✅ اسم الجدول: wadq_signal_summary
هذا الملخص تحليلي، وليس توصية شراء أو بيع.

In [ ]:
# ==========================================================
# 🌧️ الودق AI
# المرحلة التالية: تحليل الأخبار حسب تأثيرها المحتمل
# لا يعدّل أي جدول سابق
# ==========================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - تحليل تأثير الأخبار")
print("=" * 60)

if "wadq_news_df" not in globals():
    print("⚠️ جدول الأخبار الأصلي wadq_news_df غير موجود.")

elif "wadq_ticker_news_df" not in globals():
    print("⚠️ جدول الأخبار المرتبطة بالأسهم غير موجود.")

else:
    # إنشاء نسخة مستقلة من الأخبار المرتبطة بالأسهم
    wadq_impact_news_df = wadq_ticker_news_df.copy()

    # التحقق من الأعمدة
    needed = ["ticker", "news_title", "sentiment", "category"]
    missing = [
        c for c in needed
        if c not in wadq_impact_news_df.columns
    ]

    if missing:
        print("⚠️ أعمدة غير موجودة:", missing)
        print("الأعمدة المتاحة:")
        print(wadq_impact_news_df.columns.tolist())

    else:
        # تنظيف النصوص
        for col in ["ticker", "news_title", "sentiment", "category"]:
            wadq_impact_news_df[col] = (
                wadq_impact_news_df[col]
                .fillna("")
                .astype(str)
                .str.strip()
            )

        # تحديد موضوع الخبر بكلمات مفتاحية
        def identify_topic(row):
            text = (
                row["news_title"] + " " + row["category"]
            ).lower()

            topics = {
                "الاقتصاد والفائدة": [
                    "federal reserve", "fed ", "interest rate",
                    "inflation", "inflation data", "الاحتياطي الفيدرالي",
                    "الفائدة", "التضخم"
                ],
                "النفط والطاقة": [
                    "oil", "crude", "opec", "energy",
                    "النفط", "أوبك", "الطاقة"
                ],
                "التقنية والذكاء الاصطناعي": [
                    "artificial intelligence", " ai ",
                    "semiconductor", "chip", "technology",
                    "الذكاء الاصطناعي", "الرقائق", "التقنية"
                ],
                "السوق الأمريكي": [
                    "s&p 500", "nasdaq", "dow jones",
                    "wall street", "stock market"
                ]
            }

            for topic, keywords in topics.items():
                if any(word in text for word in keywords):
                    return topic

            return "أخبار عامة أو موضوع غير محدد"

        wadq_impact_news_df["موضوع الخبر"] = (
            wadq_impact_news_df.apply(identify_topic, axis=1)
        )

        # تقدير أولي للاتجاه بحسب تصنيف الخبر المتوفر
        sentiment_map = {
            "إيجابي مبدئي": "إيجابي مبدئي",
            "سلبي مبدئي": "سلبي مبدئي",
            "محايد أو غير واضح": "محايد أو غير واضح"
        }

        wadq_impact_news_df["التقييم الأولي"] = (
            wadq_impact_news_df["sentiment"]
            .map(sentiment_map)
            .fillna("يحتاج إلى مراجعة")
        )

        # عرض النتائج
        display_columns = [
            "ticker",
            "news_title",
            "category",
            "موضوع الخبر",
            "sentiment",
            "التقييم الأولي"
        ]

        wadq_impact_news_df = wadq_impact_news_df[
            display_columns
        ].copy()

        print("✅ اكتمل تصنيف الأخبار مبدئيًا.")
        print("عدد الأخبار:", len(wadq_impact_news_df))
        print("\nعينة من النتائج:")

        display(wadq_impact_news_df.head(15))

        print("\nتوزيع الأخبار حسب الموضوع:")
        display(
            wadq_impact_news_df["موضوع الخبر"]
            .value_counts()
            .rename_axis("موضوع الخبر")
            .reset_index(name="عدد الأخبار")
        )

        print("\nاسم الجدول: wadq_impact_news_df")
        print("ملاحظة: تصنيف الكلمات المفتاحية لا يحدد وحده أثر الخبر الحقيقي على السهم.")

🌧️ الودق AI - تحليل تأثير الأخبار
============================================================
✅ اكتمل تصنيف الأخبار مبدئيًا.
عدد الأخبار: 197

عينة من النتائج:

,ticker,news_title,category,موضوع الخبر,sentiment,التقييم الأولي
0,QQQ,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",الأسواق الأمريكية,السوق الأمريكي,محايد أو غير واضح,محايد أو غير واضح
1,SPY,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",الأسواق الأمريكية,السوق الأمريكي,محايد أو غير واضح,محايد أو غير واضح
2,SPY,"The S&P 500 Hits a New Record High, Powered by...",الأسواق الأمريكية,السوق الأمريكي,إيجابي مبدئي,إيجابي مبدئي
3,SPY,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...",الأسواق الأمريكية,السوق الأمريكي,محايد أو غير واضح,محايد أو غير واضح
4,SPY,"S&P 500, Nasdaq end lower as crude prices jump...",الأسواق الأمريكية,النفط والطاقة,محايد أو غير واضح,محايد أو غير واضح
5,SPY,S&P 500 and Nasdaq surge to record highs after...,الأسواق الأمريكية,التقنية والذكاء الاصطناعي,إيجابي مبدئي,إيجابي مبدئي
6,SPY,U.S. stock market drops: S&P 500 and Nasdaq fa...,الأسواق الأمريكية,الاقتصاد والفائدة,سلبي مبدئي,سلبي مبدئي
7,QQQ,"Stock Market Today: S&P 500, Dow Jones, Nasdaq...",الأسواق الأمريكية,السوق الأمريكي,إيجابي مبدئي,إيجابي مبدئي
8,SPY,"Stock Market Today: S&P 500, Dow Jones, Nasdaq...",الأسواق الأمريكية,السوق الأمريكي,إيجابي مبدئي,إيجابي مبدئي
9,SPY,"S&P 500 dips, Nasdaq higher after data shows m...",الأسواق الأمريكية,الاقتصاد والفائدة,إيجابي مبدئي,إيجابي مبدئي
10,SPY,S&P 500 Hits All-Time High on AI Bets as Oil D...,الأسواق الأمريكية,النفط والطاقة,سلبي مبدئي,سلبي مبدئي
11,SPY,"Stock Market Today: S&P 500, Dow, Nasdaq Futur...",الأسواق الأمريكية,السوق الأمريكي,سلبي مبدئي,سلبي مبدئي
12,SPY,"US Stock Market Today: Dow, S&P 500, Nasdaq Ri...",الأسواق الأمريكية,السوق الأمريكي,إيجابي مبدئي,إيجابي مبدئي
13,SPY,US Stock Market Today: S&P 500 Futures Climb A...,الأسواق الأمريكية,الاقتصاد والفائدة,محايد أو غير واضح,محايد أو غير واضح
14,SPY,"Wall Street Today: Dow, S&P 500, Nasdaq Comp R...",الأسواق الأمريكية,السوق الأمريكي,إيجابي مبدئي,إيجابي مبدئي

توزيع الأخبار حسب الموضوع:

                    موضوع الخبر  عدد الأخبار
0  أخبار عامة أو موضوع غير محدد          117
1                السوق الأمريكي           35
2     التقنية والذكاء الاصطناعي           20
3                 النفط والطاقة           14
4             الاقتصاد والفائدة           11

اسم الجدول: wadq_impact_news_df
ملاحظة: تصنيف الكلمات المفتاحية لا يحدد وحده أثر الخبر الحقيقي على السهم.

In [ ]:
# ==========================================================
# 🌧️ الودق AI
# المرحلة التالية: ربط الأخبار بالأسهم الأمريكية
# إنشاء جدول جديد دون تعديل الجداول الأصلية
# ==========================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - ربط الأخبار بالأسهم")
print("=" * 55)

# التحقق من الجداول
if "us_technical_df" not in globals():
    print("⚠️ جدول التحليل الفني الأمريكي غير موجود.")

elif "wadq_ticker_news_df" not in globals():
    print("⚠️ جدول الأخبار المرتبطة بالأسهم غير موجود.")

else:
    # نسخ مستقلة
    technical = us_technical_df.copy()
    news = wadq_ticker_news_df.copy()

    technical.columns = technical.columns.astype(str).str.strip()
    news.columns = news.columns.astype(str).str.strip()

    # تحديد عمود رمز السهم
    ticker_col = next(
        (
            c for c in [
                "الرمز", "ticker", "Ticker",
                "symbol", "Symbol"
            ]
            if c in technical.columns
        ),
        None
    )

    if ticker_col is None:
        print("⚠️ لم يُعثر على عمود رمز السهم.")
        print("أعمدة التحليل الفني:")
        print(technical.columns.tolist())

    elif not {"ticker", "sentiment"}.issubset(news.columns):
        print("⚠️ أعمدة الأخبار غير مكتملة.")
        print(news.columns.tolist())

    else:
        # توحيد رموز الأسهم
        technical["_ticker"] = (
            technical[ticker_col]
            .astype(str).str.upper().str.strip()
        )

        news["_ticker"] = (
            news["ticker"]
            .astype(str).str.upper().str.strip()
        )

        # حساب الأخبار لكل سهم
        news["_positive"] = (
            news["sentiment"]
            .eq("إيجابي مبدئي")
            .astype(int)
        )

        news["_negative"] = (
            news["sentiment"]
            .eq("سلبي مبدئي")
            .astype(int)
        )

        news["_neutral"] = (
            news["sentiment"]
            .eq("محايد أو غير واضح")
            .astype(int)
        )

        summary = (
            news.groupby("_ticker")
            .agg(
                عدد_الأخبار=("_ticker", "size"),
                أخبار_إيجابية=("_positive", "sum"),
                أخبار_سلبية=("_negative", "sum"),
                أخبار_محايدة=("_neutral", "sum")
            )
            .reset_index()
        )

        # دمج الأخبار مع التحليل الفني
        wadq_us_news_technical = technical.merge(
            summary,
            on="_ticker",
            how="left"
        )

        # معالجة الأسهم التي لم نجد لها أخبارًا مرتبطة
        count_cols = [
            "عدد_الأخبار",
            "أخبار_إيجابية",
            "أخبار_سلبية",
            "أخبار_محايدة"
        ]

        for col in count_cols:
            wadq_us_news_technical[col] = (
                wadq_us_news_technical[col]
                .fillna(0)
                .astype(int)
            )

        # وصف أولي للأخبار
        def news_assessment(row):
            if row["عدد_الأخبار"] == 0:
                return "لا توجد أخبار مرتبطة"

            if row["أخبار_إيجابية"] > row["أخبار_سلبية"]:
                return "إيجابية مبدئيًا"

            if row["أخبار_سلبية"] > row["أخبار_إيجابية"]:
                return "سلبية مبدئيًا"

            return "مختلطة أو غير حاسمة"

        wadq_us_news_technical["تقييم الأخبار"] = (
            wadq_us_news_technical.apply(
                news_assessment, axis=1
            )
        )

        # إزالة العمود المساعد
        wadq_us_news_technical.drop(
            columns=["_ticker"],
            inplace=True
        )

        print("✅ اكتمل الربط بين الأخبار والتحليل الفني.")
        print("عدد الأصول:", len(wadq_us_news_technical))
        print("\nالنتائج:")

        display(wadq_us_news_technical)

        print("\nاسم الجدول: wadq_us_news_technical")
        print("هذا التحليل مبدئي ولا يمثل توصية استثمارية.")

🌧️ الودق AI - ربط الأخبار بالأسهم
=======================================================
✅ اكتمل الربط بين الأخبار والتحليل الفني.
عدد الأصول: 9

النتائج:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,تقييم الأخبار
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,45,9,1,35,إيجابية مبدئيًا
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,20,2,0,18,إيجابية مبدئيًا
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,1,0,0,1,مختلطة أو غير حاسمة
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,33,7,1,25,إيجابية مبدئيًا
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,17,4,0,13,إيجابية مبدئيًا
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,21,5,0,16,إيجابية مبدئيًا
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,3,1,0,2,إيجابية مبدئيًا
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,3,2,0,1,إيجابية مبدئيًا
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,54,15,12,27,إيجابية مبدئيًا

اسم الجدول: wadq_us_news_technical
هذا التحليل مبدئي ولا يمثل توصية استثمارية.

In [ ]:
# 🌧️ الودق AI - فحص جاهزية التقرير النهائي

import pandas as pd

print("🌧️ الودق AI")
print("=" * 45)

# التحقق من وجود الجداول الأساسية
required_tables = [
    "us_technical_df",
    "wadq_ticker_news_df",
    "wadq_us_news_technical",
    "wadq_final_ai_report",
    "wadq_ranking_report"
]

for table_name in required_tables:
    if table_name in globals():
        table = globals()[table_name]
        if isinstance(table, pd.DataFrame):
            print(
                f"✅ {table_name}: "
                f"{len(table)} صف × {len(table.columns)} عمود"
            )
        else:
            print(f"ℹ️ {table_name}: موجود")
    else:
        print(f"ℹ️ {table_name}: غير موجود في الذاكرة الحالية")

print("=" * 45)
print("اكتمل فحص الجداول دون تعديل البيانات الأصلية.")

🌧️ الودق AI
=============================================
✅ us_technical_df: 9 صف × 10 عمود
✅ wadq_ticker_news_df: 197 صف × 6 عمود
✅ wadq_us_news_technical: 9 صف × 15 عمود
✅ wadq_final_ai_report: 9 صف × 29 عمود
✅ wadq_ranking_report: 9 صف × 30 عمود
=============================================
اكتمل فحص الجداول دون تعديل البيانات الأصلية.

In [ ]:
# 🌧️ الودق AI - فحص توافق الأخبار مع التحليل الفني
# هذا الكود لا يعدل الجداول الأصلية

import pandas as pd

df = wadq_final_ai_report.copy()

print("🌧️ الودق AI")
print("=" * 55)
print("فحص أعمدة التقرير النهائي:\n")

for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

print("\n" + "=" * 55)
print("عدد الأسهم:", len(df))
print("عدد الأعمدة:", len(df.columns))

print("\nعينة من التقرير النهائي:")
display(df.head(3))

🌧️ الودق AI
=======================================================
فحص أعمدة التقرير النهائي:

1. السهم
2. الرمز
3. آخر إغلاق
4. المتوسط 20
5. المتوسط 50
6. RSI
7. حالة RSI
8. MACD
9. إشارة MACD
10. الاتجاه
11. news_count
12. positive_news
13. negative_news
14. neutral_news
15. news_status
16. عدد_الأخبار_الحديثة
17. وزن_الأخبار_الإيجابية
18. وزن_الأخبار_السلبية
19. وزن_الأخبار_المحايدة
20. إشارة الأخبار
21. التقييم الموحد
22. عدد_الأخبار
23. الأخبار_الإيجابية
24. الأخبار_السلبية
25. الأخبار_المحايدة
26. أحدث سعر متاح
27. فرق السعر
28. التغير %
29. ملخص الأخبار

=======================================================
عدد الأسهم: 9
عدد الأعمدة: 29

عينة من التقرير النهائي:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,...,إشارة الأخبار,التقييم الموحد,عدد_الأخبار,الأخبار_الإيجابية,الأخبار_السلبية,الأخبار_المحايدة,أحدث سعر متاح,فرق السعر,التغير %,ملخص الأخبار
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,...,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,45,9,1,35,229.279999,-0.000001,-5.324072e-07,الأخبار إيجابية مبدئيًا
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,20,2,0,18,382.700012,0.000012,3.189713e-06,الأخبار إيجابية مبدئيًا
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,...,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية,1,0,0,1,336.640015,0.000015,4.351366e-06,الأخبار مختلطة أو غير حاسمة

In [ ]:
# 🌧️ الودق AI — فحص جاهزية التقييم الذكي
# فحص فقط، دون تعديل البيانات الأصلية

import pandas as pd

print("=" * 60)
print("🌧️ الودق AI — فحص جاهزية التقييم الذكي")
print("=" * 60)

if 'wadq_final_ai_report' in globals():

    df = wadq_final_ai_report

    print("\n✅ التقرير النهائي موجود")
    print(f"عدد الأسهم: {len(df)}")
    print(f"عدد الأعمدة: {len(df.columns)}")

    important_columns = [
        'السهم',
        'الرمز',
        'آخر إغلاق',
        'المتوسط 20',
        'المتوسط 50',
        'RSI',
        'حالة RSI',
        'MACD',
        'إشارة MACD',
        'الاتجاه',
        'news_count',
        'positive_news',
        'negative_news',
        'neutral_news',
        'news_status',
        'إشارة الأخبار',
        'التقييم الموحد',
        'ملخص الأخبار'
    ]

    available = [
        c for c in important_columns
        if c in df.columns
    ]

    missing = [
        c for c in important_columns
        if c not in df.columns
    ]

    print("\n📊 الأعمدة المتاحة:")
    print(available)

    print("\n🔎 الأعمدة غير الموجودة بالاسم المحدد:")
    print(missing)

    print("\n📈 عينة من التقرير:")
    display(df[available].head(9))

else:
    print("⚠️ التقرير النهائي غير موجود في الذاكرة.")
    print("لا تشغلي أي كود آخر الآن؛ سنعالج ذلك أولًا.")

print("\n✅ انتهى الفحص دون تعديل البيانات الأصلية.")

============================================================
🌧️ الودق AI — فحص جاهزية التقييم الذكي
============================================================

✅ التقرير النهائي موجود
عدد الأسهم: 9
عدد الأعمدة: 29

📊 الأعمدة المتاحة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'news_count', 'positive_news', 'negative_news', 'neutral_news', 'news_status', 'إشارة الأخبار', 'التقييم الموحد', 'ملخص الأخبار']

🔎 الأعمدة غير الموجودة بالاسم المحدد:
[]

📈 عينة من التقرير:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,news_count,positive_news,negative_news,neutral_news,news_status,إشارة الأخبار,التقييم الموحد,ملخص الأخبار
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,45,9,1,35,توجد أخبار,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,الأخبار إيجابية مبدئيًا
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,20,2,0,18,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,1,0,0,1,توجد أخبار,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية,الأخبار مختلطة أو غير حاسمة
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,33,7,1,25,توجد أخبار,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,الأخبار إيجابية مبدئيًا
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,17,4,0,13,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,21,5,0,16,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,3,1,0,2,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,3,2,0,1,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,54,15,12,27,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا

✅ انتهى الفحص دون تعديل البيانات الأصلية.

In [ ]:
# 🌧️ الودق AI — فحص جاهزية التقرير النهائي
# فحص فقط دون تعديل البيانات الأصلية

import pandas as pd

print("=" * 60)
print("🌧️ الودق AI — فحص جاهزية التقرير الذكي")
print("=" * 60)

if 'wadq_final_ai_report' in globals():

    df = wadq_final_ai_report

    print("\n✅ التقرير النهائي موجود")
    print(f"عدد الأسهم: {len(df)}")
    print(f"عدد الأعمدة: {len(df.columns)}")

    important_columns = [
        'السهم',
        'الرمز',
        'آخر إغلاق',
        'المتوسط 20',
        'المتوسط 50',
        'RSI',
        'حالة RSI',
        'MACD',
        'إشارة MACD',
        'الاتجاه',
        'news_count',
        'positive_news',
        'negative_news',
        'neutral_news',
        'news_status',
        'إشارة الأخبار',
        'التقييم الموحد',
        'ملخص الأخبار'
    ]

    available = [
        c for c in important_columns
        if c in df.columns
    ]

    missing = [
        c for c in important_columns
        if c not in df.columns
    ]

    print("\n📊 الأعمدة المتاحة:")
    print(available)

    print("\n🔎 الأعمدة غير الموجودة بالاسم المحدد:")
    print(missing)

    print("\n📈 عينة من التقرير:")
    display(df[available].head(9))

else:
    print("⚠️ التقرير النهائي غير موجود في الذاكرة.")
    print("لن نعدل أي بيانات.")

print("\n✅ انتهى الفحص دون تعديل البيانات الأصلية.")

============================================================
🌧️ الودق AI — فحص جاهزية التقرير الذكي
============================================================

✅ التقرير النهائي موجود
عدد الأسهم: 9
عدد الأعمدة: 29

📊 الأعمدة المتاحة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'news_count', 'positive_news', 'negative_news', 'neutral_news', 'news_status', 'إشارة الأخبار', 'التقييم الموحد', 'ملخص الأخبار']

🔎 الأعمدة غير الموجودة بالاسم المحدد:
[]

📈 عينة من التقرير:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,news_count,positive_news,negative_news,neutral_news,news_status,إشارة الأخبار,التقييم الموحد,ملخص الأخبار
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,45,9,1,35,توجد أخبار,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,الأخبار إيجابية مبدئيًا
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,20,2,0,18,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,1,0,0,1,توجد أخبار,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية,الأخبار مختلطة أو غير حاسمة
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,33,7,1,25,توجد أخبار,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,الأخبار إيجابية مبدئيًا
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,17,4,0,13,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,21,5,0,16,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,3,1,0,2,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,3,2,0,1,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,54,15,12,27,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا

✅ انتهى الفحص دون تعديل البيانات الأصلية.

In [ ]:
# 🌧️ الودق AI — فحص جاهزية التقرير النهائي
# فحص فقط دون تعديل البيانات الأصلية

import pandas as pd

print("=" * 60)
print("🌧️ الودق AI — فحص جاهزية التقرير الذكي")
print("=" * 60)

if 'wadq_final_ai_report' in globals():

    df = wadq_final_ai_report

    print("\n✅ التقرير النهائي موجود")
    print(f"عدد الأسهم: {len(df)}")
    print(f"عدد الأعمدة: {len(df.columns)}")

    important_columns = [
        'السهم',
        'الرمز',
        'آخر إغلاق',
        'المتوسط 20',
        'المتوسط 50',
        'RSI',
        'حالة RSI',
        'MACD',
        'إشارة MACD',
        'الاتجاه',
        'news_count',
        'positive_news',
        'negative_news',
        'neutral_news',
        'news_status',
        'إشارة الأخبار',
        'التقييم الموحد',
        'ملخص الأخبار'
    ]

    available = [
        c for c in important_columns
        if c in df.columns
    ]

    missing = [
        c for c in important_columns
        if c not in df.columns
    ]

    print("\n📊 الأعمدة المتاحة:")
    print(available)

    print("\n🔎 الأعمدة غير الموجودة بالاسم المحدد:")
    print(missing)

    print("\n📈 عينة من التقرير:")
    display(df[available].head(9))

else:
    print("⚠️ التقرير النهائي غير موجود في الذاكرة.")
    print("لن نعدل أي بيانات.")

print("\n✅ انتهى الفحص دون تعديل البيانات الأصلية.")

============================================================
🌧️ الودق AI — فحص جاهزية التقرير الذكي
============================================================

✅ التقرير النهائي موجود
عدد الأسهم: 9
عدد الأعمدة: 29

📊 الأعمدة المتاحة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'news_count', 'positive_news', 'negative_news', 'neutral_news', 'news_status', 'إشارة الأخبار', 'التقييم الموحد', 'ملخص الأخبار']

🔎 الأعمدة غير الموجودة بالاسم المحدد:
[]

📈 عينة من التقرير:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,news_count,positive_news,negative_news,neutral_news,news_status,إشارة الأخبار,التقييم الموحد,ملخص الأخبار
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,45,9,1,35,توجد أخبار,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,الأخبار إيجابية مبدئيًا
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,20,2,0,18,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,1,0,0,1,توجد أخبار,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية,الأخبار مختلطة أو غير حاسمة
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,33,7,1,25,توجد أخبار,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,الأخبار إيجابية مبدئيًا
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,17,4,0,13,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,21,5,0,16,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,3,1,0,2,توجد أخبار,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,الأخبار إيجابية مبدئيًا
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,3,2,0,1,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,54,15,12,27,توجد أخبار,إيجابية مبدئيًا,توافق إيجابي مبدئي,الأخبار إيجابية مبدئيًا

✅ انتهى الفحص دون تعديل البيانات الأصلية.

In [ ]:
# 🌧️ الودق AI — فحص جاهزية التقرير النهائي

print("=" * 50)
print("🌧️ الودق AI — فحص جاهزية التقرير")
print("=" * 50)

if 'wadq_final_ai_report' in globals():

    df = wadq_final_ai_report

    print("✅ التقرير النهائي موجود")
    print("عدد الأسهم:", len(df))
    print("عدد الأعمدة:", len(df.columns))

    print("\n📊 أسماء الأعمدة:")
    for i, col in enumerate(df.columns, 1):
        print(f"{i}. {col}")

    print("\n📈 عينة من التقرير النهائي:")
    display(df.head(9))

else:
    print("⚠️ التقرير النهائي غير موجود في الذاكرة.")
    print("سنحتاج إلى التأكد من اسم جدول التقرير.")

print("\n✅ انتهى الفحص دون تعديل البيانات الأصلية.")

==================================================
🌧️ الودق AI — فحص جاهزية التقرير
==================================================
✅ التقرير النهائي موجود
عدد الأسهم: 9
عدد الأعمدة: 29

📊 أسماء الأعمدة:
1. السهم
2. الرمز
3. آخر إغلاق
4. المتوسط 20
5. المتوسط 50
6. RSI
7. حالة RSI
8. MACD
9. إشارة MACD
10. الاتجاه
11. news_count
12. positive_news
13. negative_news
14. neutral_news
15. news_status
16. عدد_الأخبار_الحديثة
17. وزن_الأخبار_الإيجابية
18. وزن_الأخبار_السلبية
19. وزن_الأخبار_المحايدة
20. إشارة الأخبار
21. التقييم الموحد
22. عدد_الأخبار
23. الأخبار_الإيجابية
24. الأخبار_السلبية
25. الأخبار_المحايدة
26. أحدث سعر متاح
27. فرق السعر
28. التغير %
29. ملخص الأخبار

📈 عينة من التقرير النهائي:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,...,إشارة الأخبار,التقييم الموحد,عدد_الأخبار,الأخبار_الإيجابية,الأخبار_السلبية,الأخبار_المحايدة,أحدث سعر متاح,فرق السعر,التغير %,ملخص الأخبار
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,...,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,45,9,1,35,229.279999,-0.000001,-5.324072e-07,الأخبار إيجابية مبدئيًا
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,20,2,0,18,382.700012,0.000012,3.189713e-06,الأخبار إيجابية مبدئيًا
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,...,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية,1,0,0,1,336.640015,0.000015,4.351366e-06,الأخبار مختلطة أو غير حاسمة
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,...,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,33,7,1,25,535.070007,0.000007,1.368834e-06,الأخبار إيجابية مبدئيًا
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,17,4,0,13,262.429993,-0.000007,-2.790923e-06,الأخبار إيجابية مبدئيًا
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,21,5,0,16,351.660004,0.000004,1.041378e-06,الأخبار إيجابية مبدئيًا
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,3,1,0,2,718.669983,-0.000017,-2.377982e-06,الأخبار إيجابية مبدئيًا
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,3,2,0,1,751.270020,0.000020,2.599764e-06,الأخبار إيجابية مبدئيًا
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,54,15,12,27,778.570007,0.000007,9.407271e-07,الأخبار إيجابية مبدئيًا

✅ انتهى الفحص دون تعديل البيانات الأصلية.

In [ ]:
# 🌧️ الودق AI - فحص التقرير النهائي

print("🌧️ فحص التقرير النهائي")

if 'wadq_final_ai_report' in globals():

    df = wadq_final_ai_report

    print("✅ التقرير موجود")
    print("عدد الأسهم:", len(df))
    print("عدد الأعمدة:", len(df.columns))

    print("\n📊 أسماء الأعمدة:")
    print(df.columns.tolist())

    print("\n📈 التقرير النهائي:")
    display(df.head(9))

else:
    print("⚠️ التقرير النهائي غير موجود في الذاكرة.")
    print("سنتحقق من أسماء الجداول الموجودة.")

print("\n✅ انتهى الفحص")

🌧️ فحص التقرير النهائي
✅ التقرير موجود
عدد الأسهم: 9
عدد الأعمدة: 29

📊 أسماء الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'news_count', 'positive_news', 'negative_news', 'neutral_news', 'news_status', 'عدد_الأخبار_الحديثة', 'وزن_الأخبار_الإيجابية', 'وزن_الأخبار_السلبية', 'وزن_الأخبار_المحايدة', 'إشارة الأخبار', 'التقييم الموحد', 'عدد_الأخبار', 'الأخبار_الإيجابية', 'الأخبار_السلبية', 'الأخبار_المحايدة', 'أحدث سعر متاح', 'فرق السعر', 'التغير %', 'ملخص الأخبار']

📈 التقرير النهائي:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,...,إشارة الأخبار,التقييم الموحد,عدد_الأخبار,الأخبار_الإيجابية,الأخبار_السلبية,الأخبار_المحايدة,أحدث سعر متاح,فرق السعر,التغير %,ملخص الأخبار
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,...,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,45,9,1,35,229.279999,-0.000001,-5.324072e-07,الأخبار إيجابية مبدئيًا
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,20,2,0,18,382.700012,0.000012,3.189713e-06,الأخبار إيجابية مبدئيًا
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,...,محايدة أو مختلطة,إشارات مختلطة أو بيانات غير كافية,1,0,0,1,336.640015,0.000015,4.351366e-06,الأخبار مختلطة أو غير حاسمة
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,...,سلبية مبدئيًا,تعارض: الاتجاه صاعد والأخبار سلبية,33,7,1,25,535.070007,0.000007,1.368834e-06,الأخبار إيجابية مبدئيًا
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,17,4,0,13,262.429993,-0.000007,-2.790923e-06,الأخبار إيجابية مبدئيًا
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,21,5,0,16,351.660004,0.000004,1.041378e-06,الأخبار إيجابية مبدئيًا
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,...,إيجابية مبدئيًا,إشارات مختلطة أو بيانات غير كافية,3,1,0,2,718.669983,-0.000017,-2.377982e-06,الأخبار إيجابية مبدئيًا
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,3,2,0,1,751.270020,0.000020,2.599764e-06,الأخبار إيجابية مبدئيًا
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,...,إيجابية مبدئيًا,توافق إيجابي مبدئي,54,15,12,27,778.570007,0.000007,9.407271e-07,الأخبار إيجابية مبدئيًا

✅ انتهى الفحص

In [ ]:
print("🌧️ فحص جداول الودق AI")

names = [
    "wadq_final_ai_report",
    "wadq_ranking_report",
    "wadq_smart_report",
    "wadq_ticker_news_df",
    "us_technical_df"
]

for name in names:
    if name in globals():
        obj = globals()[name]
        if hasattr(obj, "shape"):
            print(f"✅ {name}: عدد الصفوف والأعمدة {obj.shape}")
        else:
            print(f"✅ {name}: موجود")
    else:
        print(f"⚠️ {name}: غير موجود في الذاكرة")

print("\nانتهى الفحص دون تعديل البيانات.")

🌧️ فحص جداول الودق AI
✅ wadq_final_ai_report: عدد الصفوف والأعمدة (9, 29)
✅ wadq_ranking_report: عدد الصفوف والأعمدة (9, 30)
✅ wadq_smart_report: عدد الصفوف والأعمدة (9, 21)
✅ wadq_ticker_news_df: عدد الصفوف والأعمدة (197, 6)
✅ us_technical_df: عدد الصفوف والأعمدة (9, 10)

انتهى الفحص دون تعديل البيانات.

In [ ]:
# 🌧️ الودق AI - ربط الأخبار بالتحليل الفني الأمريكي

import pandas as pd

print("🌧️ بدء ربط الأخبار بالتحليل الفني")

# نسخ جدول التحليل الفني دون تعديل الجدول الأصلي
wadq_integrated_df = us_technical_df.copy()

# التحقق من وجود رمز السهم في الجدولين
if "ticker" in wadq_ticker_news_df.columns:
    news_ticker_col = "ticker"
elif "الرمز" in wadq_ticker_news_df.columns:
    news_ticker_col = "الرمز"
else:
    news_ticker_col = None

if "الرمز" in wadq_integrated_df.columns:
    technical_ticker_col = "الرمز"
elif "ticker" in wadq_integrated_df.columns:
    technical_ticker_col = "ticker"
else:
    technical_ticker_col = None

if news_ticker_col and technical_ticker_col:

    news = wadq_ticker_news_df.copy()

    # توحيد رموز الأسهم
    news[news_ticker_col] = (
        news[news_ticker_col].astype(str).str.upper().str.strip()
    )

    wadq_integrated_df[technical_ticker_col] = (
        wadq_integrated_df[technical_ticker_col]
        .astype(str).str.upper().str.strip()
    )

    # حساب عدد الأخبار لكل سهم
    news_counts = (
        news.groupby(news_ticker_col)
        .size()
        .rename("عدد الأخبار")
    )

    # حساب الأخبار الإيجابية والسلبية والمحايدة
    if "sentiment" in news.columns:

        news["sentiment_clean"] = (
            news["sentiment"].astype(str).str.strip().str.lower()
        )

        positive_words = [
            "positive", "bullish", "إيجابي", "ايجابي"
        ]

        negative_words = [
            "negative", "bearish", "سلبي"
        ]

        neutral_words = [
            "neutral", "محايد"
        ]

        def classify_sentiment(value):
            if value in positive_words:
                return "إيجابي"
            elif value in negative_words:
                return "سلبي"
            elif value in neutral_words:
                return "محايد"
            return "غير محدد"

        news["تصنيف الخبر"] = news["sentiment_clean"].apply(
            classify_sentiment
        )

        sentiment_counts = pd.crosstab(
            news[news_ticker_col],
            news["تصنيف الخبر"]
        )

        sentiment_counts.columns = [
            f"عدد الأخبار {col}"
            for col in sentiment_counts.columns
        ]

        news_summary = pd.concat(
            [news_counts, sentiment_counts],
            axis=1
        ).reset_index()

    else:
        news_summary = news_counts.reset_index()

    # دمج الأخبار مع التحليل الفني
    wadq_integrated_df = wadq_integrated_df.merge(
        news_summary,
        left_on=technical_ticker_col,
        right_on=news_ticker_col,
        how="left"
    )

    # ملء القيم الفارغة في أعمدة أعداد الأخبار
    for col in wadq_integrated_df.columns:
        if col == "عدد الأخبار" or col.startswith("عدد الأخبار "):
            wadq_integrated_df[col] = (
                wadq_integrated_df[col].fillna(0).astype(int)
            )

    print("✅ نجح ربط الأخبار بالتحليل الفني")
    print("عدد الأسهم:", len(wadq_integrated_df))
    print("عدد الأعمدة:", len(wadq_integrated_df.columns))

    display(wadq_integrated_df)

else:
    print("⚠️ تعذر تحديد عمود رمز السهم.")
    print("أعمدة التحليل الفني:", us_technical_df.columns.tolist())
    print("أعمدة الأخبار:", wadq_ticker_news_df.columns.tolist())

print("انتهى التنفيذ دون تعديل الجداول الأصلية.")

🌧️ بدء ربط الأخبار بالتحليل الفني
✅ نجح ربط الأخبار بالتحليل الفني
عدد الأسهم: 9
عدد الأعمدة: 13

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد الأخبار,عدد الأخبار غير محدد
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,NVDA,45,45
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,TSLA,20,20
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,AAPL,1,1
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,MSFT,33,33
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,AMZN,17,17
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,GOOGL,21,21
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,META,3,3
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,QQQ,3,3
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,SPY,54,54

انتهى التنفيذ دون تعديل الجداول الأصلية.

In [ ]:
# 🌧️ الودق AI - فحص جدول ربط الأخبار والتحليل الفني

print("🌧️ فحص جدول الربط")

if "wadq_integrated_df" in globals():

    print("✅ جدول الربط موجود")
    print("عدد الأسهم:", len(wadq_integrated_df))
    print("عدد الأعمدة:", len(wadq_integrated_df.columns))

    print("\nأسماء الأعمدة:")
    print(wadq_integrated_df.columns.tolist())

    print("\nعينة من الجدول:")
    display(wadq_integrated_df.head(9))

else:
    print("⚠️ جدول الربط غير موجود في الذاكرة")

print("\nانتهى الفحص دون تعديل البيانات الأصلية.")

🌧️ فحص جدول الربط
✅ جدول الربط موجود
عدد الأسهم: 9
عدد الأعمدة: 13

أسماء الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'ticker', 'عدد الأخبار', 'عدد الأخبار غير محدد']

عينة من الجدول:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,ticker,عدد الأخبار,عدد الأخبار غير محدد
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,NVDA,45,45
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,TSLA,20,20
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,AAPL,1,1
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,MSFT,33,33
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,AMZN,17,17
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,GOOGL,21,21
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,META,3,3
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,QQQ,3,3
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,SPY,54,54

انتهى الفحص دون تعديل البيانات الأصلية.

In [ ]:
# =====================================================
# 🌧️ الودق AI
# المرحلة 14: فحص بيانات الأسواق العالمية الموجودة
# =====================================================

print("🌍 فحص جداول الأسواق العالمية في الودق AI")
print("=" * 55)

check_names = [
    "wadq_final_ai_report",
    "wadq_ranking_report",
    "us_technical_df",
    "wadq_latest_summary",
    "wadq_global_market_df",
    "wadq_world_markets_df",
    "wadq_global_assets_df"
]

for name in check_names:
    if name in globals():
        obj = globals()[name]

        if hasattr(obj, "shape"):
            print(f"✅ {name}: {obj.shape[0]} صف × {obj.shape[1]} عمود")
        else:
            print(f"✅ {name}: موجود")
    else:
        print(f"➖ {name}: غير موجود حاليًا")

print("\nانتهى الفحص دون تعديل أي بيانات.")

🌍 فحص جداول الأسواق العالمية في الودق AI
=======================================================
✅ wadq_final_ai_report: 9 صف × 29 عمود
✅ wadq_ranking_report: 9 صف × 30 عمود
✅ us_technical_df: 9 صف × 10 عمود
✅ wadq_latest_summary: 9 صف × 2 عمود
➖ wadq_global_market_df: غير موجود حاليًا
➖ wadq_world_markets_df: غير موجود حاليًا
➖ wadq_global_assets_df: غير موجود حاليًا

انتهى الفحص دون تعديل أي بيانات.

In [ ]:
# =========================================================
# 🌧️ الودق AI
# المرحلة 14 - الخطوة 1: جمع بيانات الأسواق العالمية
# إنشاء جدول مستقل دون تعديل الجداول السابقة
# =========================================================

import pandas as pd
import yfinance as yf
from IPython.display import display

print("🌍 الودق AI - جمع بيانات الأسواق العالمية")
print("=" * 60)

# رموز الأصول العالمية
global_assets = {
    "^GSPC": "S&P 500 - أمريكا",
    "^IXIC": "Nasdaq Composite - أمريكا",
    "^DJI": "Dow Jones - أمريكا",
    "^GDAXI": "DAX - ألمانيا",
    "^FCHI": "CAC 40 - فرنسا",
    "^FTSE": "FTSE 100 - بريطانيا",
    "^N225": "Nikkei 225 - اليابان",
    "^HSI": "Hang Seng - هونغ كونغ",
    "GC=F": "الذهب",
    "SI=F": "الفضة",
    "CL=F": "النفط الأمريكي",
    "BZ=F": "نفط برنت",
    "NG=F": "الغاز الطبيعي",
    "EURUSD=X": "اليورو مقابل الدولار",
    "JPY=X": "الدولار مقابل الين",
    "BTC-USD": "بيتكوين",
    "ETH-USD": "إيثيريوم"
}

rows = []

for ticker, asset_name in global_assets.items():
    try:
        data = yf.download(
            ticker,
            period="5d",
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False
        )

        if data.empty or "Close" not in data.columns:
            print(f"⚠️ لا توجد بيانات متاحة حاليًا: {ticker}")
            continue

        close = data["Close"].dropna()

        if isinstance(close, pd.DataFrame):
            close = close.iloc[:, 0]

        if close.empty:
            print(f"⚠️ لا توجد أسعار صالحة: {ticker}")
            continue

        latest_price = float(close.iloc[-1])
        previous_price = (
            float(close.iloc[-2]) if len(close) >= 2 else None
        )

        if previous_price is not None and previous_price != 0:
            change_pct = (
                (latest_price - previous_price)
                / previous_price
            ) * 100
        else:
            change_pct = None

        rows.append({
            "الرمز": ticker,
            "الأصل": asset_name,
            "أحدث سعر متاح": latest_price,
            "السعر السابق": previous_price,
            "التغير اليومي %": change_pct,
            "تاريخ آخر بيانات": str(close.index[-1].date())
        })

    except Exception as e:
        print(f"⚠️ تعذر جلب {ticker}: {str(e)[:150]}")

# إنشاء جدول مستقل
wadq_global_market_df = pd.DataFrame(rows)

if not wadq_global_market_df.empty:
    print("\n✅ اكتمل جمع البيانات المتاحة.")
    print("عدد الأصول التي جُمعت بياناتها:", len(wadq_global_market_df))
    print("اسم الجدول: wadq_global_market_df")
    print("تنبيه: الأسعار هي أحدث بيانات أعادها المصدر، وليست بالضرورة لحظية.")
    display(wadq_global_market_df)
else:
    print("\n⚠️ لم تُسترجع بيانات. تحققي من اتصال الإنترنت في كولاب.")

print("\nلم يتم تعديل أي جدول سابق.")

🌍 الودق AI - جمع بيانات الأسواق العالمية
============================================================

✅ اكتمل جمع البيانات المتاحة.
عدد الأصول التي جُمعت بياناتها: 17
اسم الجدول: wadq_global_market_df
تنبيه: الأسعار هي أحدث بيانات أعادها المصدر، وليست بالضرورة لحظية.

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات
0,^GSPC,S&P 500 - أمريكا,7805.450195,7807.240234,-0.022928,2026-10-13
1,^IXIC,Nasdaq Composite - أمريكا,27204.380859,27245.900391,-0.152388,2026-10-13
2,^DJI,Dow Jones - أمريكا,51670.101562,51850.550781,-0.348018,2026-10-13
3,^GDAXI,DAX - ألمانيا,25259.900391,25277.679688,-0.070336,2026-10-13
4,^FCHI,CAC 40 - فرنسا,7827.629883,7832.879883,-0.067025,2026-10-13
5,^FTSE,FTSE 100 - بريطانيا,10650.330078,10656.299805,-0.056021,2026-10-13
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,2026-10-09
7,^HSI,Hang Seng - هونغ كونغ,24271.199219,24211.349609,0.247197,2026-10-12
8,GC=F,الذهب,4183.000000,4190.600098,-0.181361,2026-10-13
9,SI=F,الفضة,59.369999,60.140999,-1.281987,2026-10-13
10,CL=F,النفط الأمريكي,94.809998,93.739998,1.141455,2026-10-13
11,BZ=F,نفط برنت,106.370003,106.650002,-0.262540,2026-10-13
12,NG=F,الغاز الطبيعي,3.322000,3.167000,4.894221,2026-10-13
13,EURUSD=X,اليورو مقابل الدولار,1.120072,1.120473,-0.035833,2026-10-13
14,JPY=X,الدولار مقابل الين,158.320999,158.203003,0.074585,2026-10-13
15,BTC-USD,بيتكوين,83349.679688,81762.562500,1.941129,2026-10-13
16,ETH-USD,إيثيريوم,2507.969971,2444.357422,2.602424,2026-10-13

لم يتم تعديل أي جدول سابق.

In [ ]:
# =========================================================
# 🌧️ الودق AI — فحص الجداول المطلوبة للمرحلة 20
# فحص فقط دون تعديل أي جدول
# =========================================================

import pandas as pd

table_names = [
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_global_news_analysis_df",
    "wadq_global_master_report_df"
]

print("🌧️ الودق AI — فحص الجداول")
print("=" * 60)

for name in table_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ الجدول: {name}")
        print(f"   عدد الصفوف: {len(obj)}")
        print(f"   عدد الأعمدة: {len(obj.columns)}")
        print("-" * 60)
    else:
        print(f"⚠️ الجدول غير موجود في الذاكرة: {name}")

print("انتهى الفحص دون تعديل أي جدول.")

🌧️ الودق AI — فحص الجداول
============================================================
✅ الجدول: wadq_global_market_df
   عدد الصفوف: 17
   عدد الأعمدة: 6
------------------------------------------------------------
⚠️ الجدول غير موجود في الذاكرة: wadq_global_alerts_df
⚠️ الجدول غير موجود في الذاكرة: wadq_global_news_analysis_df
⚠️ الجدول غير موجود في الذاكرة: wadq_global_master_report_df
انتهى الفحص دون تعديل أي جدول.

In [ ]:
# =========================================================
# 🌧️ الودق AI — المرحلة 40
# البحث عن الجداول والبيانات المتاحة في الذاكرة
# فحص فقط دون تعديل أي بيانات
# =========================================================

import pandas as pd

print("🌧️ الودق AI — البحث عن الجداول")
print("=" * 60)

found_tables = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        found_tables.append((name, len(obj), len(obj.columns)))

if found_tables:
    for name, rows, cols in found_tables:
        print(f"✅ {name} | الصفوف: {rows} | الأعمدة: {cols}")
else:
    print("⚠️ لا توجد جداول DataFrame في الذاكرة.")

print("=" * 60)
print("انتهى البحث دون تعديل أي جدول.")

🌧️ الودق AI — البحث عن الجداول
============================================================
✅ data | الصفوف: 5 | الأعمدة: 5
✅ wadq_global_market_df | الصفوف: 17 | الأعمدة: 6
============================================================
انتهى البحث دون تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — فحص جدول data
# فحص فقط دون تعديل البيانات

import pandas as pd
from IPython.display import display

if "data" in globals() and isinstance(data, pd.DataFrame):
    print("✅ تم العثور على الجدول data")
    print("عدد الصفوف:", len(data))
    print("عدد الأعمدة:", len(data.columns))
    print("أسماء الأعمدة:")
    print(list(data.columns))
    print("\nمحتويات الجدول:")
    display(data)
else:
    print("⚠️ الجدول data غير موجود.")

✅ تم العثور على الجدول data
عدد الصفوف: 5
عدد الأعمدة: 5
أسماء الأعمدة:
[('Close', 'ETH-USD'), ('High', 'ETH-USD'), ('Low', 'ETH-USD'), ('Open', 'ETH-USD'), ('Volume', 'ETH-USD')]

محتويات الجدول:

Price             Close         High          Low         Open       Volume
Ticker          ETH-USD      ETH-USD      ETH-USD      ETH-USD      ETH-USD
Date
2026-10-09  2485.538574  2514.896973  2469.229004  2471.912598   9046002553
2026-10-10  2504.027832  2516.615479  2483.797363  2485.538574   5558396432
2026-10-11  2534.699219  2551.531494  2495.720215  2504.027832   8283770666
2026-10-12  2444.357422  2576.577393  2441.676270  2534.699219  13398139928
2026-10-13  2507.969971  2534.017334  2419.049072  2444.144531  14131687424

In [ ]:
# =========================================================
# 🌧️ الودق AI — فحص جميع الجداول المتاحة
# فحص فقط دون تعديل البيانات
# =========================================================

import pandas as pd

print("🌧️ الودق AI — فحص الجداول")
print("=" * 65)

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(f"\n✅ اسم الجدول: {name}")
        print(f"عدد الصفوف: {len(obj)}")
        print(f"عدد الأعمدة: {len(obj.columns)}")
        print(f"الأعمدة: {list(obj.columns)}")

print("\n" + "=" * 65)
print("انتهى الفحص دون تعديل أي جدول.")# =========================================================
# 🌧️ الودق AI — فحص جميع الجداول المتاحة
# فحص فقط دون تعديل البيانات
# =========================================================

import pandas as pd

print("🌧️ الودق AI — فحص الجداول")
print("=" * 65)

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(f"\n✅ اسم الجدول: {name}")
        print(f"عدد الصفوف: {len(obj)}")
        print(f"عدد الأعمدة: {len(obj.columns)}")
        print(f"الأعمدة: {list(obj.columns)}")

print("\n" + "=" * 65)
print("انتهى الفحص دون تعديل أي جدول.")

🌧️ الودق AI — فحص الجداول
=================================================================

✅ اسم الجدول: data
عدد الصفوف: 5
عدد الأعمدة: 5
الأعمدة: [('Close', 'ETH-USD'), ('High', 'ETH-USD'), ('Low', 'ETH-USD'), ('Open', 'ETH-USD'), ('Volume', 'ETH-USD')]

✅ اسم الجدول: wadq_global_market_df
عدد الصفوف: 17
عدد الأعمدة: 6
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

=================================================================
انتهى الفحص دون تعديل أي جدول.
🌧️ الودق AI — فحص الجداول
=================================================================

✅ اسم الجدول: data
عدد الصفوف: 5
عدد الأعمدة: 5
الأعمدة: [('Close', 'ETH-USD'), ('High', 'ETH-USD'), ('Low', 'ETH-USD'), ('Open', 'ETH-USD'), ('Volume', 'ETH-USD')]

✅ اسم الجدول: wadq_global_market_df
عدد الصفوف: 17
عدد الأعمدة: 6
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

=================================================================
انتهى الفحص دون تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI
# المرحلة التالية: فحص جاهزية ربط الأسواق العالمية بالتقرير النهائي
# فحص فقط — دون تعديل أي جدول موجود

required_tables = [
    "wadq_final_ai_report",
    "wadq_global_market_df"
]

print("🌍 فحص جاهزية ربط الأسواق العالمية")
print("=" * 50)

missing_tables = []

for name in required_tables:
    if name in globals():
        obj = globals()[name]
        if hasattr(obj, "shape"):
            print(f"✅ {name}: {obj.shape[0]} صف × {obj.shape[1]} عمود")
        else:
            print(f"✅ {name}: موجود")
    else:
        missing_tables.append(name)
        print(f"⚠️ {name}: غير موجود في الذاكرة")

if not missing_tables:
    print("\n✅ الجداول جاهزة للمرحلة التالية.")
    print("لم يتم تعديل أي بيانات.")
else:
    print("\n⚠️ لن ننشئ جدول الربط قبل التأكد من توفر الجداول المطلوبة.")

🌍 فحص جاهزية ربط الأسواق العالمية
==================================================
✅ wadq_final_ai_report: 9 صف × 29 عمود
✅ wadq_global_market_df: 17 صف × 6 عمود

✅ الجداول جاهزة للمرحلة التالية.
لم يتم تعديل أي بيانات.

In [ ]:
# 🌧️ الودق AI
# المرحلة التالية: إنشاء تقرير مستقل يربط الأسهم بالأسواق العالمية
# المحافظة على الجداول الأصلية دون تعديل

import pandas as pd
from IPython.display import display

if "wadq_final_ai_report" not in globals() or "wadq_global_market_df" not in globals():
    print("⚠️ أحد الجدولين غير موجود. لم يتم إنشاء التقرير.")
else:
    # نسخ الجداول الأصلية للعمل عليها
    stocks_df = wadq_final_ai_report.copy()
    markets_df = wadq_global_market_df.copy()

    # استخراج ملخص الأسواق العالمية
    global_summary = {
        "عدد الأصول العالمية": len(markets_df)
    }

    if "الأصل" in markets_df.columns:
        global_summary["الأصول العالمية"] = "، ".join(
            markets_df["الأصل"].dropna().astype(str).tolist()
        )

    if "التغيير اليومي %" in markets_df.columns:
        changes = pd.to_numeric(
            markets_df["التغيير اليومي %"], errors="coerce"
        )
        global_summary["عدد الأصول المرتفعة"] = int((changes > 0).sum())
        global_summary["عدد الأصول المنخفضة"] = int((changes < 0).sum())
        global_summary["عدد الأصول دون تغيير"] = int((changes == 0).sum())

    # إنشاء نسخة مستقلة وإضافة ملخص الأسواق لكل سهم
    wadq_global_integrated_df = stocks_df.copy()

    for column, value in global_summary.items():
        wadq_global_integrated_df[column] = value

    print("✅ تم إنشاء تقرير ربط مستقل بنجاح.")
    print("اسم الجدول: wadq_global_integrated_df")
    print("عدد الأسهم:", len(wadq_global_integrated_df))
    print("عدد الأعمدة:", len(wadq_global_integrated_df.columns))
    print("لم يتم تعديل الجداول الأصلية.")

    display(wadq_global_integrated_df)

✅ تم إنشاء تقرير ربط مستقل بنجاح.
اسم الجدول: wadq_global_integrated_df
عدد الأسهم: 9
عدد الأعمدة: 31
لم يتم تعديل الجداول الأصلية.

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,...,عدد_الأخبار,الأخبار_الإيجابية,الأخبار_السلبية,الأخبار_المحايدة,أحدث سعر متاح,فرق السعر,التغير %,ملخص الأخبار,عدد الأصول العالمية,الأصول العالمية
0,إنفيديا,NVDA,229.28,226.73,221.94,53.03,ضمن النطاق المتوسط,3.9880,3.8692,صاعد,...,45,9,1,35,229.279999,-0.000001,-5.324072e-07,الأخبار إيجابية مبدئيًا,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...
1,تسلا,TSLA,382.70,368.66,354.74,59.74,ضمن النطاق المتوسط,5.0724,4.0030,صاعد,...,20,2,0,18,382.700012,0.000012,3.189713e-06,الأخبار إيجابية مبدئيًا,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...
2,آبل,AAPL,336.64,335.39,322.36,56.14,ضمن النطاق المتوسط,3.4365,3.8828,صاعد,...,1,0,0,1,336.640015,0.000015,4.351366e-06,الأخبار مختلطة أو غير حاسمة,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...
3,مايكروسوفت,MSFT,535.07,510.10,500.19,67.53,ضمن النطاق المتوسط,10.6946,9.2052,صاعد,...,33,7,1,25,535.070007,0.000007,1.368834e-06,الأخبار إيجابية مبدئيًا,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...
4,أمازون,AMZN,262.43,252.02,259.10,59.05,ضمن النطاق المتوسط,0.3739,-1.0611,مختلط,...,17,4,0,13,262.429993,-0.000007,-2.790923e-06,الأخبار إيجابية مبدئيًا,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...
5,ألفابت,GOOGL,351.66,345.92,346.14,56.39,ضمن النطاق المتوسط,1.2863,0.3666,مختلط,...,21,5,0,16,351.660004,0.000004,1.041378e-06,الأخبار إيجابية مبدئيًا,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...
6,ميتا,META,718.67,719.05,639.40,56.85,ضمن النطاق المتوسط,25.1409,30.9242,مختلط,...,3,1,0,2,718.669983,-0.000017,-2.377982e-06,الأخبار إيجابية مبدئيًا,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...
7,ناسداك 100,QQQ,751.27,737.36,724.00,61.05,ضمن النطاق المتوسط,9.7563,8.9125,صاعد,...,3,2,0,1,751.270020,0.000020,2.599764e-06,الأخبار إيجابية مبدئيًا,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...
8,ستاندرد آند بورز 500,SPY,778.57,767.60,766.28,60.49,ضمن النطاق المتوسط,3.6626,2.5600,صاعد,...,54,15,12,27,778.570007,0.000007,9.407271e-07,الأخبار إيجابية مبدئيًا,17,S&P 500 - أمريكا، Nasdaq Composite - أمريكا، D...

In [ ]:
print("هل جدول الربط موجود؟", "wadq_global_integrated_df" in globals())

if "wadq_global_integrated_df" in globals():
    print("عدد الصفوف والأعمدة:", wadq_global_integrated_df.shape)

print("هل التقرير الأصلي محفوظ؟", "wadq_final_ai_report" in globals())

هل جدول الربط موجود؟ True
عدد الصفوف والأعمدة: (9, 31)
هل التقرير الأصلي محفوظ؟ True

In [ ]:
print("🌧️ فحص متغيرات الأخبار الموجودة")
print("=" * 45)

news_names = [
    "wadq_ticker_news_df",
    "wadq_impact_news_df",
    "wadq_us_news_technical",
    "wadq_global_news_df",
    "wadq_world_news_df"
]

for name in news_names:
    if name in globals():
        obj = globals()[name]
        if hasattr(obj, "shape"):
            print(f"✅ {name}: {obj.shape}")
        else:
            print(f"✅ {name}: موجود")
    else:
        print(f"➖ {name}: غير موجود")

🌧️ فحص متغيرات الأخبار الموجودة
=============================================
✅ wadq_ticker_news_df: (197, 6)
✅ wadq_impact_news_df: (197, 6)
✅ wadq_us_news_technical: (9, 15)
➖ wadq_global_news_df: غير موجود
➖ wadq_world_news_df: غير موجود

In [ ]:
print("🌧️ فحص متغيرات الأخبار الموجودة")

🌧️ فحص متغيرات الأخبار الموجودة

In [ ]:
# 🌧️ الودق AI - ملخص فحص الجداول
print("✅ wadq_ticker_news_df: (197, 6)")
print("✅ wadq_impact_news_df: (197, 6)")
print("➖ wadq_global_news_df: غير موجود")

✅ wadq_ticker_news_df: (197, 6)
✅ wadq_impact_news_df: (197, 6)
➖ wadq_global_news_df: غير موجود

In [ ]:
# 🌧️ الودق AI
# اختبار مصادر الأخبار العالمية دون مفتاح API

import requests
import pandas as pd
import xml.etree.ElementTree as ET

news_sources = {
    "Google News - الاقتصاد العالمي":
        "https://news.google.com/rss/search?q=global+economy+markets&hl=en-US&gl=US&ceid=US:en",

    "Google News - الذهب والنفط":
        "https://news.google.com/rss/search?q=gold+oil+prices&hl=en-US&gl=US&ceid=US:en",

    "Google News - البنوك المركزية":
        "https://news.google.com/rss/search?q=central+banks+interest+rates&hl=en-US&gl=US&ceid=US:en"
}

print("🌍 الودق AI - اختبار مصادر الأخبار العالمية")
print("=" * 55)

for source_name, url in news_sources.items():
    try:
        response = requests.get(
            url,
            timeout=20,
            headers={"User-Agent": "Mozilla/5.0"}
        )
        response.raise_for_status()

        root = ET.fromstring(response.content)
        items = root.findall(".//item")

        print(f"✅ {source_name}: {len(items)} خبرًا متاحًا")

    except Exception as e:
        print(f"⚠️ {source_name}: تعذر الاتصال ({str(e)[:100]})")

print("\nانتهى الاختبار دون تعديل أي جدول سابق.")

🌍 الودق AI - اختبار مصادر الأخبار العالمية
=======================================================
✅ Google News - الاقتصاد العالمي: 100 خبرًا متاحًا
✅ Google News - الذهب والنفط: 100 خبرًا متاحًا
✅ Google News - البنوك المركزية: 100 خبرًا متاحًا

انتهى الاختبار دون تعديل أي جدول سابق.

In [ ]:
# =========================================================
# 🌧️ الودق AI
# المرحلة 15: إنشاء جدول الأخبار العالمية
# دون تعديل أي جدول سابق
# =========================================================

import requests
import pandas as pd
import xml.etree.ElementTree as ET
from IPython.display import display

news_sources = {
    "الاقتصاد العالمي والأسواق":
        "https://news.google.com/rss/search?q=global+economy+markets&hl=en-US&gl=US&ceid=US:en",

    "الذهب والنفط":
        "https://news.google.com/rss/search?q=gold+oil+prices&hl=en-US&gl=US&ceid=US:en",

    "البنوك المركزية وأسعار الفائدة":
        "https://news.google.com/rss/search?q=central+banks+interest+rates&hl=en-US&gl=US&ceid=US:en"
}

all_news = []

print("🌍 الودق AI - جمع الأخبار العالمية")
print("=" * 55)

for topic, url in news_sources.items():
    try:
        response = requests.get(
            url,
            timeout=25,
            headers={"User-Agent": "Mozilla/5.0"}
        )
        response.raise_for_status()

        root = ET.fromstring(response.content)
        items = root.findall(".//item")

        for item in items:
            title = item.findtext("title", default="").strip()
            link = item.findtext("link", default="").strip()
            published = item.findtext("pubDate", default="").strip()

            source_element = item.find("source")
            source_name = (
                source_element.text.strip()
                if source_element is not None and source_element.text
                else "Google News"
            )

            if title and link:
                all_news.append({
                    "news_title": title,
                    "source": source_name,
                    "published": published,
                    "link": link,
                    "category": topic
                })

        print(f"✅ {topic}: جُمعت {len(items)} نتيجة")

    except Exception as e:
        print(f"⚠️ تعذر جمع {topic}: {str(e)[:150]}")

# إنشاء جدول مستقل
wadq_global_news_df = pd.DataFrame(
    all_news,
    columns=[
        "news_title",
        "source",
        "published",
        "link",
        "category"
    ]
)

if not wadq_global_news_df.empty:
    before = len(wadq_global_news_df)

    wadq_global_news_df = (
        wadq_global_news_df
        .drop_duplicates(subset=["link"])
        .reset_index(drop=True)
    )

    removed = before - len(wadq_global_news_df)

    print("\n✅ تم إنشاء جدول الأخبار العالمية.")
    print("عدد النتائج قبل إزالة التكرار:", before)
    print("عدد التكرارات المحذوفة:", removed)
    print("عدد الأخبار الفريدة:", len(wadq_global_news_df))
    print("اسم الجدول: wadq_global_news_df")

    display(wadq_global_news_df.head(15))

else:
    print("\n⚠️ لم تُجمع أخبار. تحققي من اتصال الإنترنت.")

print("\nلم يتم تعديل أي جدول سابق.")

🌍 الودق AI - جمع الأخبار العالمية
=======================================================
✅ الاقتصاد العالمي والأسواق: جُمعت 100 نتيجة
✅ الذهب والنفط: جُمعت 100 نتيجة
✅ البنوك المركزية وأسعار الفائدة: جُمعت 100 نتيجة

✅ تم إنشاء جدول الأخبار العالمية.
عدد النتائج قبل إزالة التكرار: 300
عدد التكرارات المحذوفة: 1
عدد الأخبار الفريدة: 299
اسم الجدول: wadq_global_news_df

,news_title,source,published,link,category
0,Global growth remains solid in a challenging e...,Peterson Institute for International Economics,"Tue, 06 Oct 2026 17:05:41 GMT",https://news.google.com/rss/articles/CBMipAFBV...,الاقتصاد العالمي والأسواق
1,"World economic growth to slow to 2.6% in 2026,...",Reuters,"Fri, 09 Oct 2026 09:02:39 GMT",https://news.google.com/rss/articles/CBMirAFBV...,الاقتصاد العالمي والأسواق
2,Musk Says SpaceX Could Be Worth Orders of Magn...,BigGo Finance,"Sun, 11 Oct 2026 18:16:00 GMT",https://news.google.com/rss/articles/CBMidkFVX...,الاقتصاد العالمي والأسواق
3,The Global Imbalance Triangle: How European Sa...,semivision,"Sun, 11 Oct 2026 01:52:19 GMT",https://news.google.com/rss/articles/CBMif0FVX...,الاقتصاد العالمي والأسواق
4,The global economy has been resilient — so far...,World Bank Blogs,"Mon, 28 Sep 2026 12:44:57 GMT",https://news.google.com/rss/articles/CBMimAFBV...,الاقتصاد العالمي والأسواق
5,What’s happening this week in economics? - Del...,Deloitte,"Tue, 06 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiowFBV...,الاقتصاد العالمي والأسواق
6,Charting the Global Economy: Sentiment among U...,The Economic Times,"Sun, 11 Oct 2026 04:51:04 GMT",https://news.google.com/rss/articles/CBMi4wFBV...,الاقتصاد العالمي والأسواق
7,Annual meetings 2026: Storms lurk behind resil...,OMFIF,"Sat, 10 Oct 2026 03:59:29 GMT",https://news.google.com/rss/articles/CBMiiAFBV...,الاقتصاد العالمي والأسواق
8,CNBC Daily Open: Bond yield whiplash grips glo...,CNBC,"Fri, 02 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMicEFVX...,الاقتصاد العالمي والأسواق
9,Asia to Drive 59% of Global Growth as World Ec...,Retail News Asia,"Sun, 11 Oct 2026 19:10:41 GMT",https://news.google.com/rss/articles/CBMikAFBV...,الاقتصاد العالمي والأسواق
10,"Eyes on US Inflation, China Export Data as Glo...",bloomingbit,"Sun, 11 Oct 2026 05:55:06 GMT",https://news.google.com/rss/articles/CBMiVEFVX...,الاقتصاد العالمي والأسواق
11,Bonds are like the “hidden wiring connecting t...,marketplace.org,"Wed, 23 Sep 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMigwFBV...,الاقتصاد العالمي والأسواق
12,"Putin says sales of Russian diesel to US, glob...",Anadolu Ajansı,"Fri, 09 Oct 2026 20:47:10 GMT",https://news.google.com/rss/articles/CBMiwAFBV...,الاقتصاد العالمي والأسواق
13,"Putin says Russian diesel supplies to US, glob...",Türkiye Today,"Sat, 10 Oct 2026 06:56:51 GMT",https://news.google.com/rss/articles/CBMiuAFBV...,الاقتصاد العالمي والأسواق
14,Putin: Russian diesel exports to US to boost g...,Yeni Şafak English,"Sat, 10 Oct 2026 08:12:15 GMT",https://news.google.com/rss/articles/CBMioAFBV...,الاقتصاد العالمي والأسواق

لم يتم تعديل أي جدول سابق.

In [ ]:
# =========================================================
# 🌧️ الودق AI
# المرحلة 16: تحليل وتصنيف الأخبار العالمية
# إنشاء جدول مستقل دون تعديل الأخبار الأصلية
# =========================================================

import pandas as pd
from IPython.display import display

if "wadq_global_news_df" not in globals():
    print("⚠️ جدول الأخبار العالمية غير موجود. شغّلي مرحلة جمع الأخبار أولًا.")

else:
    # نسخة مستقلة للعمل عليها
    news_df = wadq_global_news_df.copy()

    # التأكد من وجود عمود العنوان
    if "news_title" not in news_df.columns:
        print("⚠️ لم يُعثر على عمود news_title.")
        print("الأعمدة المتاحة:", news_df.columns.tolist())

    else:
        # كلمات مفتاحية أولية للتصنيف
        categories = {
            "البنوك المركزية والفائدة": [
                "interest rate", "central bank", "federal reserve",
                "fed ", "ecb", "bank of japan", "monetary policy",
                "rate cut", "rate hike", "borrowing cost"
            ],
            "التضخم والاقتصاد": [
                "inflation", "cpi", "pce", "gdp", "economic growth",
                "recession", "unemployment", "jobs report",
                "consumer prices", "global economy"
            ],
            "الذهب والفضة": [
                "gold", "silver", "bullion", "precious metal"
            ],
            "النفط والغاز والطاقة": [
                "oil", "crude", "brent", "natural gas",
                "opec", "energy prices", "petroleum"
            ],
            "الأسهم والأسواق المالية": [
                "stock market", "stocks", "shares", "s&p 500",
                "nasdaq", "dow jones", "equities", "wall street",
                "bond yields", "bond market"
            ],
            "العملات وأسواق الصرف": [
                "forex", "currency", "currencies", "dollar",
                "euro", "yen", "exchange rate"
            ],
            "العملات الرقمية": [
                "bitcoin", "ethereum", "crypto", "cryptocurrency",
                "digital asset"
            ],
            "السياسة والمخاطر الجيوسياسية": [
                "war ", "conflict", "sanctions", "geopolitical",
                "tariff", "trade war", "election", "military",
                "iran", "russia", "ukraine", "middle east"
            ],
            "الشركات والتكنولوجيا": [
                "company", "earnings", "revenue", "profit",
                "artificial intelligence", "chipmaker", "technology",
                "tesla", "nvidia", "apple", "microsoft"
            ]
        }

        # ربط الموضوع بالأصول المحتمل تأثرها
        related_assets = {
            "البنوك المركزية والفائدة":
                "السندات، العملات، الأسهم، الذهب",
            "التضخم والاقتصاد":
                "المؤشرات العالمية، السندات، العملات، الذهب",
            "الذهب والفضة":
                "الذهب، الفضة، الدولار",
            "النفط والغاز والطاقة":
                "النفط، الغاز الطبيعي، أسهم الطاقة",
            "الأسهم والأسواق المالية":
                "المؤشرات والأسهم",
            "العملات وأسواق الصرف":
                "أزواج العملات، الذهب",
            "العملات الرقمية":
                "بيتكوين، إيثيريوم، الأصول الرقمية",
            "السياسة والمخاطر الجيوسياسية":
                "النفط، الذهب، العملات، المؤشرات العالمية",
            "الشركات والتكنولوجيا":
                "أسهم الشركات والقطاع المعني"
        }

        def classify_global_news(title):
            title = str(title).lower()

            matches = []
            for category, keywords in categories.items():
                if any(keyword in title for keyword in keywords):
                    matches.append(category)

            if not matches:
                return (
                    "اقتصاد وأسواق عامة",
                    "تحتاج إلى تحليل إضافي"
                )

            # الاحتفاظ بأكثر من موضوع عند وجود مؤشرات متعددة
            primary = matches[0]
            return (
                "؛ ".join(matches),
                related_assets.get(primary, "تحتاج إلى تحليل إضافي")
            )

        results = news_df["news_title"].apply(classify_global_news)

        news_df["موضوع الخبر"] = results.apply(lambda x: x[0])
        news_df["الأصول المحتمل تأثرها"] = results.apply(lambda x: x[1])

        # إنشاء جدول مستقل
        wadq_global_news_analysis_df = news_df.copy()

        print("✅ اكتمل تصنيف الأخبار العالمية مبدئيًا.")
        print("عدد الأخبار:", len(wadq_global_news_analysis_df))
        print("عدد الأعمدة:", len(wadq_global_news_analysis_df.columns))
        print("اسم الجدول: wadq_global_news_analysis_df")

        print("\nعدد الأخبار حسب الموضوع:")
        print(
            wadq_global_news_analysis_df["موضوع الخبر"]
            .value_counts()
            .head(15)
            .to_string()
        )

        print("\nعينة من النتائج:")
        display(wadq_global_news_analysis_df.head(10))

        print("\n⚠️ التصنيف يعتمد على كلمات العناوين؛ وهو تصنيف أولي وليس تحليلًا مؤكدًا للتأثير.")
        print("لم يتم تعديل أي جدول سابق.")

✅ اكتمل تصنيف الأخبار العالمية مبدئيًا.
عدد الأخبار: 299
عدد الأعمدة: 7
اسم الجدول: wadq_global_news_analysis_df

عدد الأخبار حسب الموضوع:
موضوع الخبر
البنوك المركزية والفائدة                                        59
اقتصاد وأسواق عامة                                              34
التضخم والاقتصاد                                                34
الذهب والفضة؛ النفط والغاز والطاقة                              32
الذهب والفضة؛ النفط والغاز والطاقة؛ العملات وأسواق الصرف        15
البنوك المركزية والفائدة؛ التضخم والاقتصاد                      14
البنوك المركزية والفائدة؛ الذهب والفضة؛ النفط والغاز والطاقة    12
التضخم والاقتصاد؛ السياسة والمخاطر الجيوسياسية                  12
الذهب والفضة                                                    11
التضخم والاقتصاد؛ الذهب والفضة؛ النفط والغاز والطاقة            10
البنوك المركزية والفائدة؛ العملات وأسواق الصرف                   7
البنوك المركزية والفائدة؛ السياسة والمخاطر الجيوسياسية           6
البنوك المركزية والفائدة؛ الذهب والفضة                           6
السياسة والمخاطر الجيوسياسية                                     6
الذهب والفضة؛ النفط والغاز والطاقة؛ الأسهم والأسواق المالية      6

عينة من النتائج:

,news_title,source,published,link,category,موضوع الخبر,الأصول المحتمل تأثرها
0,Global growth remains solid in a challenging e...,Peterson Institute for International Economics,"Tue, 06 Oct 2026 17:05:41 GMT",https://news.google.com/rss/articles/CBMipAFBV...,الاقتصاد العالمي والأسواق,اقتصاد وأسواق عامة,تحتاج إلى تحليل إضافي
1,"World economic growth to slow to 2.6% in 2026,...",Reuters,"Fri, 09 Oct 2026 09:02:39 GMT",https://news.google.com/rss/articles/CBMirAFBV...,الاقتصاد العالمي والأسواق,التضخم والاقتصاد,المؤشرات العالمية، السندات، العملات، الذهب
2,Musk Says SpaceX Could Be Worth Orders of Magn...,BigGo Finance,"Sun, 11 Oct 2026 18:16:00 GMT",https://news.google.com/rss/articles/CBMidkFVX...,الاقتصاد العالمي والأسواق,التضخم والاقتصاد,المؤشرات العالمية، السندات، العملات، الذهب
3,The Global Imbalance Triangle: How European Sa...,semivision,"Sun, 11 Oct 2026 01:52:19 GMT",https://news.google.com/rss/articles/CBMif0FVX...,الاقتصاد العالمي والأسواق,العملات وأسواق الصرف,أزواج العملات، الذهب
4,The global economy has been resilient — so far...,World Bank Blogs,"Mon, 28 Sep 2026 12:44:57 GMT",https://news.google.com/rss/articles/CBMimAFBV...,الاقتصاد العالمي والأسواق,التضخم والاقتصاد,المؤشرات العالمية، السندات، العملات، الذهب
5,What’s happening this week in economics? - Del...,Deloitte,"Tue, 06 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiowFBV...,الاقتصاد العالمي والأسواق,اقتصاد وأسواق عامة,تحتاج إلى تحليل إضافي
6,Charting the Global Economy: Sentiment among U...,The Economic Times,"Sun, 11 Oct 2026 04:51:04 GMT",https://news.google.com/rss/articles/CBMi4wFBV...,الاقتصاد العالمي والأسواق,التضخم والاقتصاد,المؤشرات العالمية، السندات، العملات، الذهب
7,Annual meetings 2026: Storms lurk behind resil...,OMFIF,"Sat, 10 Oct 2026 03:59:29 GMT",https://news.google.com/rss/articles/CBMiiAFBV...,الاقتصاد العالمي والأسواق,اقتصاد وأسواق عامة,تحتاج إلى تحليل إضافي
8,CNBC Daily Open: Bond yield whiplash grips glo...,CNBC,"Fri, 02 Oct 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMicEFVX...,الاقتصاد العالمي والأسواق,التضخم والاقتصاد,المؤشرات العالمية، السندات، العملات، الذهب
9,Asia to Drive 59% of Global Growth as World Ec...,Retail News Asia,"Sun, 11 Oct 2026 19:10:41 GMT",https://news.google.com/rss/articles/CBMikAFBV...,الاقتصاد العالمي والأسواق,اقتصاد وأسواق عامة,تحتاج إلى تحليل إضافي

⚠️ التصنيف يعتمد على كلمات العناوين؛ وهو تصنيف أولي وليس تحليلًا مؤكدًا للتأثير.
لم يتم تعديل أي جدول سابق.

In [ ]:
# 🌧️ الودق AI
# المرحلة 17 - فحص جاهزية ربط الأخبار بالأسواق

check_tables = [
    "wadq_global_news_analysis_df",
    "wadq_global_market_df",
    "wadq_final_ai_report",
    "wadq_global_integrated_df"
]

print("🌍 فحص جاهزية ربط الأخبار بالأسواق")
print("=" * 50)

for name in check_tables:
    if name in globals():
        obj = globals()[name]
        if hasattr(obj, "shape"):
            print(f"✅ {name}: {obj.shape[0]} صف × {obj.shape[1]} أعمدة")
        else:
            print(f"✅ {name}: موجود")
    else:
        print(f"➖ {name}: غير موجود")

print("\nانتهى الفحص دون تعديل أي بيانات.")

🌍 فحص جاهزية ربط الأخبار بالأسواق
==================================================
✅ wadq_global_news_analysis_df: 299 صف × 7 أعمدة
✅ wadq_global_market_df: 17 صف × 6 أعمدة
✅ wadq_final_ai_report: 9 صف × 29 أعمدة
✅ wadq_global_integrated_df: 9 صف × 31 أعمدة

انتهى الفحص دون تعديل أي بيانات.

In [ ]:
# =========================================================
# 🌧️ الودق AI
# المرحلة 17: ربط الأخبار العالمية بالأصول المحتمل تأثرها
# إنشاء جدول مستقل دون تعديل الجداول الأصلية
# =========================================================

import pandas as pd
from IPython.display import display

if (
    "wadq_global_news_analysis_df" not in globals()
    or "wadq_global_market_df" not in globals()
):
    print("⚠️ أحد الجدولين غير موجود. لم يتم إنشاء جدول الربط.")

else:
    news_df = wadq_global_news_analysis_df.copy()
    markets_df = wadq_global_market_df.copy()

    # التحقق من الأعمدة اللازمة
    required_news = [
        "news_title",
        "source",
        "published",
        "link",
        "موضوع الخبر",
        "الأصول المحتمل تأثرها"
    ]

    missing_news = [
        col for col in required_news
        if col not in news_df.columns
    ]

    if missing_news:
        print("⚠️ أعمدة الأخبار الناقصة:", missing_news)

    elif not {"الرمز", "الأصل"}.issubset(markets_df.columns):
        print("⚠️ لم يتم العثور على عمودي الرمز والأصل في جدول الأسواق.")

    else:
        # إنشاء قائمة تربط كل خبر بالأصول المطابقة لكلمات موضوعه
        asset_keywords = {
            "الذهب": ["الذهب", "gold"],
            "الفضة": ["الفضة", "silver"],
            "النفط": ["النفط", "oil", "brent", "crude"],
            "الغاز الطبيعي": ["الغاز الطبيعي", "natural gas"],
            "المؤشرات الأمريكية": [
                "الأسهم والأسواق المالية",
                "المؤشرات العالمية",
                "s&p 500", "nasdaq", "dow jones"
            ],
            "العملات": [
                "العملات", "الدولار", "اليورو",
                "الين", "forex", "currency"
            ],
            "العملات الرقمية": [
                "العملات الرقمية", "بيتكوين",
                "إيثيريوم", "bitcoin", "ethereum", "crypto"
            ]
        }

        rows = []

        for _, news in news_df.iterrows():
            title = str(news["news_title"])
            topic = str(news["موضوع الخبر"])
            related = str(news["الأصول المحتمل تأثرها"])

            search_text = (title + " " + topic + " " + related).lower()

            matched_assets = []

            for asset_group, keywords in asset_keywords.items():
                if any(word.lower() in search_text for word in keywords):
                    matched_assets.append(asset_group)

            # الاحتفاظ بالخبر حتى إذا لم تتحدد أصول واضحة
            if not matched_assets:
                matched_assets = ["غير محدد — يحتاج مراجعة"]

            for asset_group in matched_assets:
                rows.append({
                    "news_title": news["news_title"],
                    "source": news["source"],
                    "published": news["published"],
                    "link": news["link"],
                    "موضوع الخبر": news["موضوع الخبر"],
                    "مجموعة الأصل المحتمل": asset_group,
                    "ملاحظة": "ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا"
                })

        wadq_global_news_market_df = pd.DataFrame(rows)

        print("✅ تم إنشاء جدول ربط الأخبار بالأصول.")
        print("اسم الجدول: wadq_global_news_market_df")
        print("عدد صفوف الربط:", len(wadq_global_news_market_df))
        print("عدد الأخبار الأصلية:", len(news_df))
        print("عدد مجموعات الأصول:",
              wadq_global_news_market_df["مجموعة الأصل المحتمل"].nunique())

        print("\nعدد الروابط حسب مجموعة الأصل:")
        print(
            wadq_global_news_market_df["مجموعة الأصل المحتمل"]
            .value_counts()
            .to_string()
        )

        display(wadq_global_news_market_df.head(10))

        print("\nلم يتم تعديل أي جدول سابق.")

✅ تم إنشاء جدول ربط الأخبار بالأصول.
اسم الجدول: wadq_global_news_market_df
عدد صفوف الربط: 840
عدد الأخبار الأصلية: 299
عدد مجموعات الأصول: 7

عدد الروابط حسب مجموعة الأصل:
مجموعة الأصل المحتمل
العملات                    259
الذهب                      258
الفضة                      104
النفط                       99
المؤشرات الأمريكية          83
غير محدد — يحتاج مراجعة     35
الغاز الطبيعي                2

,news_title,source,published,link,موضوع الخبر,مجموعة الأصل المحتمل,ملاحظة
0,Global growth remains solid in a challenging e...,Peterson Institute for International Economics,"Tue, 06 Oct 2026 17:05:41 GMT",https://news.google.com/rss/articles/CBMipAFBV...,اقتصاد وأسواق عامة,غير محدد — يحتاج مراجعة,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
1,"World economic growth to slow to 2.6% in 2026,...",Reuters,"Fri, 09 Oct 2026 09:02:39 GMT",https://news.google.com/rss/articles/CBMirAFBV...,التضخم والاقتصاد,الذهب,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
2,"World economic growth to slow to 2.6% in 2026,...",Reuters,"Fri, 09 Oct 2026 09:02:39 GMT",https://news.google.com/rss/articles/CBMirAFBV...,التضخم والاقتصاد,المؤشرات الأمريكية,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
3,"World economic growth to slow to 2.6% in 2026,...",Reuters,"Fri, 09 Oct 2026 09:02:39 GMT",https://news.google.com/rss/articles/CBMirAFBV...,التضخم والاقتصاد,العملات,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
4,Musk Says SpaceX Could Be Worth Orders of Magn...,BigGo Finance,"Sun, 11 Oct 2026 18:16:00 GMT",https://news.google.com/rss/articles/CBMidkFVX...,التضخم والاقتصاد,الذهب,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
5,Musk Says SpaceX Could Be Worth Orders of Magn...,BigGo Finance,"Sun, 11 Oct 2026 18:16:00 GMT",https://news.google.com/rss/articles/CBMidkFVX...,التضخم والاقتصاد,المؤشرات الأمريكية,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
6,Musk Says SpaceX Could Be Worth Orders of Magn...,BigGo Finance,"Sun, 11 Oct 2026 18:16:00 GMT",https://news.google.com/rss/articles/CBMidkFVX...,التضخم والاقتصاد,العملات,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
7,The Global Imbalance Triangle: How European Sa...,semivision,"Sun, 11 Oct 2026 01:52:19 GMT",https://news.google.com/rss/articles/CBMif0FVX...,العملات وأسواق الصرف,الذهب,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
8,The Global Imbalance Triangle: How European Sa...,semivision,"Sun, 11 Oct 2026 01:52:19 GMT",https://news.google.com/rss/articles/CBMif0FVX...,العملات وأسواق الصرف,العملات,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا
9,The global economy has been resilient — so far...,World Bank Blogs,"Mon, 28 Sep 2026 12:44:57 GMT",https://news.google.com/rss/articles/CBMimAFBV...,التضخم والاقتصاد,الذهب,ارتباط موضوعي أولي، وليس تأثيرًا سعريًا مثبتًا

لم يتم تعديل أي جدول سابق.

In [ ]:
# =========================================================
# 🌧️ الودق AI
# المرحلة 18: تقرير الأخبار وحركة الأسواق العالمية
# إنشاء جدول مستقل دون تعديل الجداول السابقة
# =========================================================

import pandas as pd
from IPython.display import display

if (
    "wadq_global_news_analysis_df" not in globals()
    or "wadq_global_market_df" not in globals()
):
    print("⚠️ جداول الأخبار أو الأسواق غير موجودة.")
else:
    news_df = wadq_global_news_analysis_df.copy()
    market_df = wadq_global_market_df.copy()

    # تجهيز ملخص حركة الأسواق
    market_cols = [
        "الرمز", "الأصل", "أحدث سعر متاح",
        "السعر السابق", "التغير اليومي %", "تاريخ آخر بيانات"
    ]

    missing = [c for c in market_cols if c not in market_df.columns]

    if missing:
        print("⚠️ أعمدة غير موجودة في جدول الأسواق:", missing)
        print("الأعمدة المتاحة:", market_df.columns.tolist())

    else:
        # إنشاء نسخة مستقلة من بيانات الأسواق
        market_summary = market_df[market_cols].copy()

        # تحويل القيم الرقمية عند الحاجة
        for col in ["أحدث سعر متاح", "السعر السابق", "التغير اليومي %"]:
            market_summary[col] = pd.to_numeric(
                market_summary[col], errors="coerce"
            )

        # تصنيف حركة السعر وصفياً
        def describe_move(value):
            if pd.isna(value):
                return "بيانات التغير غير متاحة"
            elif value > 0:
                return "ارتفاع"
            elif value < 0:
                return "انخفاض"
            return "دون تغيير"

        market_summary["وصف الحركة"] = (
            market_summary["التغير اليومي %"].apply(describe_move)
        )

        # إنشاء صف لكل أصل مع ملخص الأخبار ذات الصلة الموضوعية
        rows = []

        for _, asset in market_summary.iterrows():
            symbol = asset["الرمز"]
            asset_name = str(asset["الأصل"]).lower()

            # البحث عن الأخبار باستخدام مجموعات الكلمات المفتاحية
            if any(x in asset_name for x in ["gold", "الذهب"]):
                terms = ["الذهب والفضة", "الذهب", "gold"]
            elif any(x in asset_name for x in ["silver", "الفضة"]):
                terms = ["الذهب والفضة", "الفضة", "silver"]
            elif any(x in asset_name for x in ["oil", "نفط", "gas", "الغاز"]):
                terms = ["النفط والغاز والطاقة", "النفط", "الغاز", "oil", "energy"]
            elif any(x in asset_name for x in ["bitcoin", "ethereum", "بيتكوين", "إيثيريوم"]):
                terms = ["العملات الرقمية", "bitcoin", "ethereum", "crypto"]
            elif any(x in asset_name for x in ["eur", "jpy", "اليورو", "الين", "الدولار"]):
                terms = ["العملات وأسواق الصرف", "البنوك المركزية والفائدة", "الدولار"]
            else:
                terms = [
                    "الأسهم والأسواق المالية",
                    "التضخم والاقتصاد",
                    "البنوك المركزية والفائدة",
                    "السياسة والمخاطر الجيوسياسية"
                ]

            mask = news_df["موضوع الخبر"].astype(str).apply(
                lambda text: any(term.lower() in text.lower() for term in terms)
            )

            related_news = news_df.loc[mask].copy()

            rows.append({
                "الرمز": symbol,
                "الأصل": asset["الأصل"],
                "أحدث سعر متاح": asset["أحدث سعر متاح"],
                "السعر السابق": asset["السعر السابق"],
                "التغير اليومي %": asset["التغير اليومي %"],
                "وصف الحركة": asset["وصف الحركة"],
                "تاريخ آخر بيانات": asset["تاريخ آخر بيانات"],
                "عدد الأخبار المرتبطة موضوعياً": len(related_news),
                "أمثلة عناوين الأخبار": " | ".join(
                    related_news["news_title"].astype(str).head(3).tolist()
                ),
                "تنبيه": "ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر"
            })

        wadq_global_impact_report_df = pd.DataFrame(rows)

        print("✅ تم إنشاء تقرير حركة الأسواق والأخبار.")
        print("اسم الجدول: wadq_global_impact_report_df")
        print("عدد الأصول:", len(wadq_global_impact_report_df))
        print("عدد الأعمدة:", len(wadq_global_impact_report_df.columns))

        display(wadq_global_impact_report_df)

        print("\nلم يتم تعديل أي جدول سابق.")

✅ تم إنشاء تقرير حركة الأسواق والأخبار.
اسم الجدول: wadq_global_impact_report_df
عدد الأصول: 17
عدد الأعمدة: 10

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,وصف الحركة,تاريخ آخر بيانات,عدد الأخبار المرتبطة موضوعياً,أمثلة عناوين الأخبار,تنبيه
0,^GSPC,S&P 500 - أمريكا,7811.540039,7765.359863,0.594695,ارتفاع,2026-10-09,203,"World economic growth to slow to 2.6% in 2026,...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
1,^IXIC,Nasdaq Composite - أمريكا,27366.169922,27193.339844,0.635560,ارتفاع,2026-10-09,203,"World economic growth to slow to 2.6% in 2026,...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
2,^DJI,Dow Jones - أمريكا,51654.949219,51231.640625,0.826264,ارتفاع,2026-10-09,203,"World economic growth to slow to 2.6% in 2026,...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
3,^GDAXI,DAX - ألمانيا,25087.269531,24806.970703,1.129920,ارتفاع,2026-10-09,203,"World economic growth to slow to 2.6% in 2026,...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
4,^FCHI,CAC 40 - فرنسا,7803.330078,7729.689941,0.952692,ارتفاع,2026-10-09,203,"World economic growth to slow to 2.6% in 2026,...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
5,^FTSE,FTSE 100 - بريطانيا,10552.099609,10441.599609,1.058267,ارتفاع,2026-10-09,203,"World economic growth to slow to 2.6% in 2026,...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,انخفاض,2026-10-09,203,"World economic growth to slow to 2.6% in 2026,...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
7,^HSI,Hang Seng - هونغ كونغ,24211.349609,23785.789062,1.789138,ارتفاع,2026-10-09,203,"World economic growth to slow to 2.6% in 2026,...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
8,GC=F,الذهب,4212.000000,4216.299805,-0.101981,انخفاض,2026-10-11,104,Gold’s rollercoaster ride shows the messy stat...,ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
9,SI=F,الفضة,61.209999,60.669998,0.890063,ارتفاع,2026-10-11,104,Gold’s rollercoaster ride shows the messy stat...,ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
10,CL=F,النفط الأمريكي,92.470001,91.849998,0.675017,ارتفاع,2026-10-11,93,"Putin says Russian oil supplies to US will ""po...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
11,BZ=F,نفط برنت,105.400002,104.720001,0.649351,ارتفاع,2026-10-11,93,"Putin says Russian oil supplies to US will ""po...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
12,NG=F,الغاز الطبيعي,3.186000,3.220000,-1.055898,انخفاض,2026-10-11,93,"Putin says Russian oil supplies to US will ""po...",ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
13,EURUSD=X,اليورو مقابل الدولار,1.120197,1.121302,-0.098574,انخفاض,2026-10-11,138,The Global Imbalance Triangle: How European Sa...,ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
14,JPY=X,الدولار مقابل الين,158.302002,158.063004,0.151205,ارتفاع,2026-10-11,138,The Global Imbalance Triangle: How European Sa...,ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
15,BTC-USD,بيتكوين,83540.007812,82912.226562,0.757164,ارتفاع,2026-10-11,0,,ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر
16,ETH-USD,إيثيريوم,2531.459961,2504.027832,1.095520,ارتفاع,2026-10-11,0,,ارتباط موضوعي فقط؛ لا يثبت تأثير الخبر على السعر

لم يتم تعديل أي جدول سابق.

In [ ]:
# =========================================================
# 🌧️ الودق AI
# المرحلة 19: لوحة الإنذارات الذكية للأسواق العالمية
# إنشاء جدول مستقل دون تعديل الجداول السابقة
# =========================================================

import pandas as pd
from IPython.display import display

if "wadq_global_market_df" not in globals():
    print("⚠️ جدول الأسواق العالمية غير موجود.")

else:
    market_df = wadq_global_market_df.copy()

    required = [
        "الرمز",
        "الأصل",
        "أحدث سعر متاح",
        "التغير اليومي %",
        "تاريخ آخر بيانات"
    ]

    missing = [c for c in required if c not in market_df.columns]

    if missing:
        print("⚠️ أعمدة ناقصة:", missing)

    else:
        market_df["التغير اليومي %"] = pd.to_numeric(
            market_df["التغير اليومي %"], errors="coerce"
        )

        def classify_alert(row):
            change = row["التغير اليومي %"]

            if pd.isna(change):
                return "بيانات غير كافية"

            if change >= 2:
                return "ارتفاع ملحوظ — يحتاج مراجعة"

            if change <= -2:
                return "انخفاض ملحوظ — يحتاج مراجعة"

            if change > 0:
                return "ارتفاع محدود"

            if change < 0:
                return "انخفاض محدود"

            return "دون تغيير"

        wadq_global_alerts_df = market_df[required].copy()

        wadq_global_alerts_df["حالة الحركة"] = (
            market_df.apply(classify_alert, axis=1)
        )

        wadq_global_alerts_df["ملاحظة"] = (
            "تنبيه مبني على تغير السعر فقط، وليس توصية تداول"
        )

        wadq_global_alerts_df = wadq_global_alerts_df.sort_values(
            "التغير اليومي %",
            ascending=False,
            na_position="last"
        ).reset_index(drop=True)

        print("✅ تم إنشاء لوحة الإنذارات الأولية.")
        print("اسم الجدول: wadq_global_alerts_df")
        print("عدد الأصول:", len(wadq_global_alerts_df))
        print("عدد الأعمدة:", len(wadq_global_alerts_df.columns))

        display(wadq_global_alerts_df)

        print("\nلم يتم تعديل أي جدول سابق.")

✅ تم إنشاء لوحة الإنذارات الأولية.
اسم الجدول: wadq_global_alerts_df
عدد الأصول: 17
عدد الأعمدة: 7

,الرمز,الأصل,أحدث سعر متاح,التغير اليومي %,تاريخ آخر بيانات,حالة الحركة,ملاحظة
0,^HSI,Hang Seng - هونغ كونغ,24211.349609,1.789138,2026-10-09,ارتفاع محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
1,CL=F,النفط الأمريكي,93.309998,1.589547,2026-10-12,ارتفاع محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
2,BZ=F,نفط برنت,106.190002,1.403744,2026-10-12,ارتفاع محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
3,^FTSE,FTSE 100 - بريطانيا,10656.280273,0.987298,2026-10-12,ارتفاع محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
4,^GDAXI,DAX - ألمانيا,25277.679688,0.758991,2026-10-12,ارتفاع محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
5,^FCHI,CAC 40 - فرنسا,7832.879883,0.378682,2026-10-12,ارتفاع محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
6,^DJI,Dow Jones - أمريكا,51850.550781,0.378670,2026-10-12,ارتفاع محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
7,JPY=X,الدولار مقابل الين,158.654007,0.373904,2026-10-12,ارتفاع محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
8,^N225,Nikkei 225 - اليابان,69030.921875,-0.016204,2026-10-09,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
9,^GSPC,S&P 500 - أمريكا,7807.240234,-0.055044,2026-10-12,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
10,SI=F,الفضة,60.480000,-0.313167,2026-10-12,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
11,^IXIC,Nasdaq Composite - أمريكا,27245.902344,-0.439475,2026-10-12,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
12,EURUSD=X,اليورو مقابل الدولار,1.115573,-0.510931,2026-10-12,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
13,GC=F,الذهب,4193.299805,-0.545502,2026-10-12,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
14,ETH-USD,إيثيريوم,2519.070068,-0.616608,2026-10-12,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
15,BTC-USD,بيتكوين,82809.937500,-1.039121,2026-10-12,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
16,NG=F,الغاز الطبيعي,3.169000,-1.583855,2026-10-12,انخفاض محدود,تنبيه مبني على تغير السعر فقط، وليس توصية تداول

لم يتم تعديل أي جدول سابق.

In [ ]:
# =========================================================
# 🌧️ الودق AI
# المرحلة 20: التقرير العالمي الموحد
# إنشاء جدول جديد دون تعديل الجداول الأصلية
# =========================================================

import pandas as pd
from IPython.display import display

required_tables = [
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_global_news_analysis_df"
]

missing_tables = [
    name for name in required_tables
    if name not in globals()
]

if missing_tables:
    print("⚠️ الجداول التالية غير موجودة:", missing_tables)

else:
    markets = wadq_global_market_df.copy()
    alerts = wadq_global_alerts_df.copy()
    news = wadq_global_news_analysis_df.copy()

    # التحقق من الأعمدة الأساسية
    required_market_cols = [
        "الرمز", "الأصل", "أحدث سعر متاح",
        "التغير اليومي %", "تاريخ آخر بيانات"
    ]

    required_alert_cols = [
        "الرمز", "حالة الحركة"
    ]

    required_news_cols = [
        "news_title", "موضوع الخبر",
        "الأصول المحتمل تأثرها"
    ]

    missing = (
        [c for c in required_market_cols if c not in markets.columns]
        + [c for c in required_alert_cols if c not in alerts.columns]
        + [c for c in required_news_cols if c not in news.columns]
    )

    if missing:
        print("⚠️ توجد أعمدة مطلوبة غير موجودة:", missing)

    else:
        # ربط الأسعار والتنبيهات بواسطة رمز الأصل
        report = markets.merge(
            alerts[["الرمز", "حالة الحركة"]],
            on="الرمز",
            how="left",
            validate="one_to_one"
        )

        # البحث الموضوعي عن الأخبار المرتبطة بكل أصل
        def get_related_news(asset_name, symbol):
            asset_name = str(asset_name).lower()
            symbol = str(symbol).lower()

            keywords = {
                "الذهب": ["gold", "الذهب"],
                "الفضة": ["silver", "الفضة"],
                "النفط": ["oil", "crude", "brent", "النفط"],
                "الغاز": ["natural gas", "الغاز الطبيعي"],
                "بيتكوين": ["bitcoin", "crypto", "بيتكوين"],
                "إيثيريوم": ["ethereum", "crypto", "إيثيريوم"],
                "اليورو": ["euro", "eurusd", "اليورو"],
                "الين": ["yen", "jpy", "الين"],
                "ناسداك": ["nasdaq", "technology", "التكنولوجيا"],
                "s&p 500": ["s&p 500", "stocks", "equities"],
                "dow jones": ["dow jones", "stocks", "equities"],
                "dax": ["dax", "germany", "ألمانيا"],
                "cac 40": ["cac 40", "france", "فرنسا"],
                "ftse": ["ftse", "britain", "بريطانيا"],
                "nikkei": ["nikkei", "japan", "اليابان"],
                "hang seng": ["hang seng", "hong kong", "هونغ كونغ"]
            }

            selected_terms = []
            for key, terms in keywords.items():
                if key in asset_name:
                    selected_terms.extend(terms)

            if not selected_terms:
                selected_terms = [
                    "global economy",
                    "inflation",
                    "central banks",
                    "الاقتصاد العالمي"
                ]

            text = (
                news["news_title"].fillna("").astype(str)
                + " "
                + news["موضوع الخبر"].fillna("").astype(str)
                + " "
                + news["الأصول المحتمل تأثرها"].fillna("").astype(str)
            ).str.lower()

            mask = text.apply(
                lambda value: any(term.lower() in value for term in selected_terms)
            )

            related = news.loc[mask, "news_title"].drop_duplicates()

            return len(related), " | ".join(related.head(3).tolist())

        results = report.apply(
            lambda row: get_related_news(row["الأصل"], row["الرمز"]),
            axis=1
        )

        report["عدد الأخبار المرتبطة موضوعيًا"] = results.apply(lambda x: x[0])
        report["أمثلة عناوين الأخبار"] = results.apply(lambda x: x[1])
        report["تنبيه التفسير"] = (
            "الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا لتأثيرها على السعر"
        )

        wadq_global_master_report_df = report.copy()

        print("✅ تم إنشاء التقرير العالمي الموحد.")
        print("اسم الجدول: wadq_global_master_report_df")
        print("عدد الأصول:", len(wadq_global_master_report_df))
        print("عدد الأعمدة:", len(wadq_global_master_report_df.columns))

        display(wadq_global_master_report_df)

        print("\nلم يتم تعديل أي جدول سابق.")

✅ تم إنشاء التقرير العالمي الموحد.
اسم الجدول: wadq_global_master_report_df
عدد الأصول: 17
عدد الأعمدة: 10

,الرمز,الأصل,أحدث سعر متاح,السعر السابق,التغير اليومي %,تاريخ آخر بيانات,حالة الحركة,عدد الأخبار المرتبطة موضوعيًا,أمثلة عناوين الأخبار,تنبيه التفسير
0,^GSPC,S&P 500 - أمريكا,7811.540039,7765.359863,0.594695,2026-10-09,ارتفاع محدود,5,"Eyes on US Inflation, China Export Data as Glo...",الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
1,^IXIC,Nasdaq Composite - أمريكا,27366.169922,27193.339844,0.635560,2026-10-09,ارتفاع محدود,109,Musk Says SpaceX Could Be Worth Orders of Magn...,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
2,^DJI,Dow Jones - أمريكا,51654.949219,51231.640625,0.826264,2026-10-09,ارتفاع محدود,5,"Eyes on US Inflation, China Export Data as Glo...",الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
3,^GDAXI,DAX - ألمانيا,25087.269531,24806.970703,1.129920,2026-10-09,ارتفاع محدود,0,,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
4,^FCHI,CAC 40 - فرنسا,7803.330078,7729.689941,0.952692,2026-10-09,ارتفاع محدود,0,,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
5,^FTSE,FTSE 100 - بريطانيا,10552.099609,10441.599609,1.058267,2026-10-09,ارتفاع محدود,0,,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
6,^N225,Nikkei 225 - اليابان,69030.921875,69042.109375,-0.016204,2026-10-09,انخفاض محدود,1,India's central bank delivers first rate hike ...,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
7,^HSI,Hang Seng - هونغ كونغ,24211.349609,23785.789062,1.789138,2026-10-09,ارتفاع محدود,0,,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
8,GC=F,الذهب,4212.000000,4216.299805,-0.101981,2026-10-11,انخفاض محدود,256,"World economic growth to slow to 2.6% in 2026,...",الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
9,SI=F,الفضة,61.209999,60.669998,0.890063,2026-10-11,ارتفاع محدود,104,Gold’s rollercoaster ride shows the messy stat...,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
10,CL=F,النفط الأمريكي,92.470001,91.849998,0.675017,2026-10-11,ارتفاع محدود,99,"Putin says sales of Russian diesel to US, glob...",الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
11,BZ=F,نفط برنت,105.400002,104.720001,0.649351,2026-10-11,ارتفاع محدود,109,Musk Says SpaceX Could Be Worth Orders of Magn...,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
12,NG=F,الغاز الطبيعي,3.186000,3.220000,-1.055898,2026-10-11,انخفاض محدود,2,From chokepoint to crisis: The Strait of Hormu...,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
13,EURUSD=X,اليورو مقابل الدولار,1.120197,1.121302,-0.098574,2026-10-11,انخفاض محدود,10,The Global Imbalance Triangle: How European Sa...,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
14,JPY=X,الدولار مقابل الين,158.302002,158.063004,0.151205,2026-10-11,ارتفاع محدود,1,Putin: Russian diesel exports to US to boost g...,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
15,BTC-USD,بيتكوين,83540.007812,82912.226562,0.757164,2026-10-11,ارتفاع محدود,0,,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...
16,ETH-USD,إيثيريوم,2531.459961,2504.027832,1.095520,2026-10-11,ارتفاع محدود,0,,الارتباط بالأخبار موضوعي مبدئي، وليس إثباتًا ل...

لم يتم تعديل أي جدول سابق.

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 21
# إنشاء نظام تقييم وترتيب الأصول العالمية
# دون تعديل الجداول السابقة
# ============================================================

import pandas as pd
from IPython.display import display

# التحقق من وجود الجداول المطلوبة
required_tables = [
    "wadq_global_master_report_df",
    "wadq_global_alerts_df"
]

missing_tables = [
    name for name in required_tables
    if name not in globals()
]

if missing_tables:
    print("⚠️ الجداول التالية غير موجودة:", missing_tables)

else:
    # نسخ البيانات للعمل عليها دون تعديل الأصل
    report = wadq_global_master_report_df.copy()
    alerts = wadq_global_alerts_df.copy()

    # التحقق من الأعمدة الأساسية
    required_columns = [
        "الرمز",
        "الأصل",
        "التغير اليومي %"
    ]

    missing_columns = [
        col for col in required_columns
        if col not in report.columns
    ]

    if missing_columns:
        print("⚠️ أعمدة غير موجودة في التقرير:", missing_columns)
        print("الأعمدة المتاحة:", report.columns.tolist())

    else:
        # إنشاء جدول تقييم مستقل
        wadq_global_ranking_df = report[
            ["الرمز", "الأصل", "التغير اليومي %"]
        ].copy()

        # تحويل التغير اليومي إلى قيمة رقمية
        wadq_global_ranking_df["التغير اليومي %"] = pd.to_numeric(
            wadq_global_ranking_df["التغير اليومي %"],
            errors="coerce"
        )

        # تحديد اتجاه الحركة
        wadq_global_ranking_df["اتجاه الحركة"] = (
            wadq_global_ranking_df["التغير اليومي %"].apply(
                lambda x: (
                    "ارتفاع" if x > 0
                    else "انخفاض" if x < 0
                    else "ثبات" if pd.notna(x)
                    else "بيانات غير متاحة"
                )
            )
        )

        # حساب قوة الحركة المطلقة
        wadq_global_ranking_df["قوة الحركة %"] = (
            wadq_global_ranking_df["التغير اليومي %"].abs()
        )

        # إضافة عدد الأخبار المرتبطة، إن توفر
        if "عدد الأخبار المرتبطة موضوعيًا" in report.columns:
            wadq_global_ranking_df["عدد الأخبار"] = pd.to_numeric(
                report["عدد الأخبار المرتبطة موضوعيًا"],
                errors="coerce"
            ).fillna(0)

        # ترتيب الأصول حسب قوة الحركة
        wadq_global_ranking_df = (
            wadq_global_ranking_df.sort_values(
                by="قوة الحركة %",
                ascending=False,
                na_position="last"
            ).reset_index(drop=True)
        )

        # إضافة ترتيب مستقل
        wadq_global_ranking_df.insert(
            0,
            "الترتيب",
            range(1, len(wadq_global_ranking_df) + 1)
        )

        print("✅ نجحت المرحلة 21: تقييم وترتيب الأصول العالمية")
        print("عدد الأصول:", len(wadq_global_ranking_df))
        print("عدد الأعمدة:", len(wadq_global_ranking_df.columns))
        print("ملاحظة: الترتيب حسب مقدار حركة السعر، وليس توصية شراء أو بيع.")

        display(wadq_global_ranking_df)

⚠️ الجداول التالية غير موجودة: ['wadq_global_master_report_df', 'wadq_global_alerts_df']

In [ ]:
# فحص الجداول الموجودة فعليًا في جلسة الودق الحالية

table_names = [
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_ticker_news_df",
    "us_technical_df",
    "wadq_global_news_analysis_df",
    "wadq_global_master_report_df"
]

print("🌧️ فحص جداول الودق AI")
print("=" * 45)

for name in table_names:
    if name in globals():
        table = globals()[name]
        if hasattr(table, "shape"):
            print(f"✅ {name}: {table.shape[0]} صف × {table.shape[1]} أعمدة")
        else:
            print(f"⚠️ {name}: موجود، لكنه ليس جدول بيانات")
    else:
        print(f"❌ {name}: غير موجود في الجلسة الحالية")

🌧️ فحص جداول الودق AI
=============================================
✅ wadq_global_market_df: 17 صف × 6 أعمدة
✅ wadq_global_alerts_df: 17 صف × 7 أعمدة
❌ wadq_ticker_news_df: غير موجود في الجلسة الحالية
✅ us_technical_df: 9 صف × 10 أعمدة
❌ wadq_global_news_analysis_df: غير موجود في الجلسة الحالية
❌ wadq_global_master_report_df: غير موجود في الجلسة الحالية

In [ ]:
# 🌧️ الودق AI - فحص الجداول الموجودة
# فحص فقط، دون تعديل أي جدول سابق

from IPython.display import display

tables_to_check = [
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_news_df",
    "wadq_news_scored_df",
    "wadq_ticker_news_df",
    "wadq_global_news_analysis_df",
    "us_technical_df",
    "wadq_integrated_df",
    "wadq_global_master_report_df"
]

print("🌧️ الودق AI - فحص حالة الجداول")
print("=" * 50)

for name in tables_to_check:
    if name in globals():
        obj = globals()[name]
        if hasattr(obj, "shape"):
            print(f"✅ {name}: {obj.shape[0]} صف × {obj.shape[1]} أعمدة")
        else:
            print(f"✅ {name}: موجود")
    else:
        print(f"⚠️ {name}: غير موجود في الجلسة الحالية")

print("\nاكتمل الفحص دون تعديل الجداول.")

🌧️ الودق AI - فحص حالة الجداول
==================================================
✅ wadq_global_market_df: 17 صف × 6 أعمدة
✅ wadq_global_alerts_df: 17 صف × 7 أعمدة
✅ wadq_news_df: 565 صف × 5 أعمدة
✅ wadq_news_scored_df: 565 صف × 8 أعمدة
✅ wadq_ticker_news_df: 195 صف × 6 أعمدة
⚠️ wadq_global_news_analysis_df: غير موجود في الجلسة الحالية
✅ us_technical_df: 9 صف × 10 أعمدة
⚠️ wadq_integrated_df: غير موجود في الجلسة الحالية
⚠️ wadq_global_master_report_df: غير موجود في الجلسة الحالية

اكتمل الفحص دون تعديل الجداول.

In [ ]:
# 🌧️ الودق AI
# المرحلة التالية: دمج التحليل الفني مع الأخبار
# إنشاء جدول جديد دون تعديل الجداول الأصلية

import pandas as pd
from IPython.display import display

# التأكد من وجود الجداول المطلوبة
required_tables = [
    "us_technical_df",
    "wadq_ticker_news_df"
]

missing_tables = [
    name for name in required_tables
    if name not in globals()
]

if missing_tables:
    print("⚠️ الجداول التالية غير موجودة:", missing_tables)

else:
    technical = us_technical_df.copy()
    news = wadq_ticker_news_df.copy()

    # توحيد الرموز
    technical["الرمز"] = technical["الرمز"].astype(str).str.upper().str.strip()
    news["ticker"] = news["ticker"].astype(str).str.upper().str.strip()

    # تجميع الأخبار المرتبطة بكل رمز
    news_summary = []

    for ticker in technical["الرمز"].unique():
        ticker_news = news[news["ticker"] == ticker]

        sentiment = (
            ticker_news["sentiment"]
            .astype(str)
            .str.strip()
            .str.lower()
        )

        news_summary.append({
            "الرمز": ticker,
            "عدد الأخبار": len(ticker_news),
            "الأخبار الإيجابية": int(
                sentiment.str.contains(
                    "إيجابي|positive",
                    regex=True
                ).sum()
            ),
            "الأخبار السلبية": int(
                sentiment.str.contains(
                    "سلبي|negative",
                    regex=True
                ).sum()
            ),
            "الأخبار المحايدة": int(
                sentiment.str.contains(
                    "محايد|neutral",
                    regex=True
                ).sum()
            )
        })

    news_summary_df = pd.DataFrame(news_summary)

    # دمج التحليل الفني والأخبار في جدول مستقل
    wadq_integrated_df = technical.merge(
        news_summary_df,
        on="الرمز",
        how="left"
    )

    # معالجة القيم الفارغة
    news_columns = [
        "عدد الأخبار",
        "الأخبار الإيجابية",
        "الأخبار السلبية",
        "الأخبار المحايدة"
    ]

    wadq_integrated_df[news_columns] = (
        wadq_integrated_df[news_columns]
        .fillna(0)
        .astype(int)
    )

    print("🌧️ تم إنشاء جدول دمج التحليل الفني والأخبار")
    print("اسم الجدول: wadq_integrated_df")
    print("عدد الصفوف:", len(wadq_integrated_df))
    print("عدد الأعمدة:", len(wadq_integrated_df.columns))

    display(wadq_integrated_df)

🌧️ تم إنشاء جدول دمج التحليل الفني والأخبار
اسم الجدول: wadq_integrated_df
عدد الصفوف: 9
عدد الأعمدة: 14

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,عدد الأخبار,الأخبار الإيجابية,الأخبار السلبية,الأخبار المحايدة
0,إنفيديا,NVDA,226.32,227.50,222.46,49.42,ضمن النطاق المتوسط,3.3139,3.7581,مختلط,46,9,1,36
1,تسلا,TSLA,378.03,369.61,356.08,56.46,ضمن النطاق المتوسط,5.1446,4.2311,صاعد,20,2,0,18
2,آبل,AAPL,340.97,335.78,323.00,60.22,ضمن النطاق المتوسط,3.6456,3.8354,صاعد,1,0,0,1
3,مايكروسوفت,MSFT,541.15,511.89,501.73,69.92,ضمن النطاق المتوسط,11.6192,9.6870,صاعد,34,7,1,26
4,أمازون,AMZN,259.53,252.32,258.85,55.59,ضمن النطاق المتوسط,0.7570,-0.6976,مختلط,17,4,0,13
5,ألفابت,GOOGL,352.72,346.09,346.08,57.30,ضمن النطاق المتوسط,1.6851,0.6300,صاعد,20,5,0,15
6,ميتا,META,742.96,722.94,643.13,62.32,ضمن النطاق المتوسط,24.8981,29.7186,صاعد,2,1,0,1
7,ناسداك 100,QQQ,746.04,739.24,725.18,56.72,ضمن النطاق المتوسط,9.0018,8.9299,صاعد,5,2,0,3
8,ستاندرد آند بورز 500,SPY,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد,50,15,8,27

In [ ]:
# 🌧️ الودق AI
# المرحلة 22: التقييم الموحد للأسهم الأمريكية
# إنشاء جدول جديد دون تعديل الجداول السابقة

import pandas as pd
from IPython.display import display

# التأكد من وجود جدول الدمج
if "wadq_integrated_df" not in globals():
    print("⚠️ جدول wadq_integrated_df غير موجود.")
else:

    # إنشاء نسخة مستقلة
    wadq_us_ranking_df = wadq_integrated_df.copy()

    # تحويل الأعمدة الرقمية
    numeric_columns = [
        "السعر الحالي",
        "المتوسط 20",
        "المتوسط 50",
        "الأخبار الإيجابية",
        "الأخبار السلبية",
        "الأخبار المحايدة"
    ]

    for col in numeric_columns:
        if col in wadq_us_ranking_df.columns:
            wadq_us_ranking_df[col] = pd.to_numeric(
                wadq_us_ranking_df[col],
                errors="coerce"
            )

    # حساب التقييم الفني
    def wadq_technical_score(row):
        score = 0

        price = row.get("السعر الحالي")
        ma20 = row.get("المتوسط 20")
        ma50 = row.get("المتوسط 50")

        if pd.notna(price) and pd.notna(ma20):
            score += 1 if price > ma20 else -1 if price < ma20 else 0

        if pd.notna(ma20) and pd.notna(ma50):
            score += 1 if ma20 > ma50 else -1 if ma20 < ma50 else 0

        macd_signal = str(row.get("إشارة MACD", "")).lower()

        if any(word in macd_signal for word in ["صاعد", "إيجابي", "شراء"]):
            score += 1
        elif any(word in macd_signal for word in ["هابط", "سلبي", "بيع"]):
            score -= 1

        return score

    wadq_us_ranking_df["التقييم الفني"] = (
        wadq_us_ranking_df.apply(wadq_technical_score, axis=1)
    )

    # حساب أثر الأخبار
    positive = wadq_us_ranking_df.get(
        "الأخبار الإيجابية",
        pd.Series(0, index=wadq_us_ranking_df.index)
    ).fillna(0)

    negative = wadq_us_ranking_df.get(
        "الأخبار السلبية",
        pd.Series(0, index=wadq_us_ranking_df.index)
    ).fillna(0)

    wadq_us_ranking_df["صافي الأخبار"] = positive - negative

    # التقييم الموحد
    wadq_us_ranking_df["النتيجة الموحدة"] = (
        wadq_us_ranking_df["التقييم الفني"]
        + wadq_us_ranking_df["صافي الأخبار"].apply(
            lambda x: 1 if x > 0 else -1 if x < 0 else 0
        )
    )

    # التصنيف المبدئي
    def wadq_classify_stock(score):
        if score >= 2:
            return "إيجابي مبدئيًا"
        elif score <= -2:
            return "سلبي مبدئيًا"
        return "محايد أو متضارب"

    wadq_us_ranking_df["التقييم النهائي"] = (
        wadq_us_ranking_df["النتيجة الموحدة"].apply(
            wadq_classify_stock
        )
    )

    # ترتيب الأسهم حسب النتيجة
    wadq_us_ranking_df = wadq_us_ranking_df.sort_values(
        "النتيجة الموحدة",
        ascending=False
    ).reset_index(drop=True)

    print("🌧️ تم إنشاء التقييم الموحد للأسهم الأمريكية")
    print("اسم الجدول: wadq_us_ranking_df")
    print("عدد الأسهم:", len(wadq_us_ranking_df))
    print("=" * 55)

    display(wadq_us_ranking_df)

    print(
        "\nتنبيه: التصنيف مبدئي للتقييم والتحليل، "
        "وليس توصية شراء أو بيع."
    )

🌧️ تم إنشاء التقييم الموحد للأسهم الأمريكية
اسم الجدول: wadq_us_ranking_df
عدد الأسهم: 9
=======================================================

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,عدد الأخبار,الأخبار الإيجابية,الأخبار السلبية,الأخبار المحايدة,التقييم الفني,صافي الأخبار,النتيجة الموحدة,التقييم النهائي
0,إنفيديا,NVDA,226.32,227.50,222.46,49.42,ضمن النطاق المتوسط,3.3139,3.7581,مختلط,46,9,1,36,1,8,2,إيجابي مبدئيًا
1,تسلا,TSLA,378.03,369.61,356.08,56.46,ضمن النطاق المتوسط,5.1446,4.2311,صاعد,20,2,0,18,1,2,2,إيجابي مبدئيًا
2,مايكروسوفت,MSFT,541.15,511.89,501.73,69.92,ضمن النطاق المتوسط,11.6192,9.6870,صاعد,34,7,1,26,1,6,2,إيجابي مبدئيًا
3,ميتا,META,742.96,722.94,643.13,62.32,ضمن النطاق المتوسط,24.8981,29.7186,صاعد,2,1,0,1,1,1,2,إيجابي مبدئيًا
4,ألفابت,GOOGL,352.72,346.09,346.08,57.30,ضمن النطاق المتوسط,1.6851,0.6300,صاعد,20,5,0,15,1,5,2,إيجابي مبدئيًا
5,ناسداك 100,QQQ,746.04,739.24,725.18,56.72,ضمن النطاق المتوسط,9.0018,8.9299,صاعد,5,2,0,3,1,2,2,إيجابي مبدئيًا
6,ستاندرد آند بورز 500,SPY,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد,50,15,8,27,1,7,2,إيجابي مبدئيًا
7,آبل,AAPL,340.97,335.78,323.00,60.22,ضمن النطاق المتوسط,3.6456,3.8354,صاعد,1,0,0,1,1,0,1,محايد أو متضارب
8,أمازون,AMZN,259.53,252.32,258.85,55.59,ضمن النطاق المتوسط,0.7570,-0.6976,مختلط,17,4,0,13,-1,4,0,محايد أو متضارب

تنبيه: التصنيف مبدئي للتقييم والتحليل، وليس توصية شراء أو بيع.

In [ ]:
# ==========================================================
# 🌧️ الودق AI
# المرحلة 23: إنشاء التقرير العالمي الموحّد
# إنشاء جدول مستقل دون تعديل الجداول السابقة
# ==========================================================

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - إنشاء التقرير العالمي الموحّد")
print("=" * 65)

# 1. التأكد من وجود الجداول الأساسية
required_tables = [
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_us_ranking_df"
]

missing_tables = [
    name for name in required_tables
    if name not in globals()
]

if missing_tables:
    print("⚠️ الجداول التالية غير موجودة:")
    for name in missing_tables:
        print("-", name)

    print("\nلم يتم إنشاء التقرير. تأكدي من تشغيل خلايا الجداول المطلوبة أولًا.")

else:

    # 2. دالة للعثور على العمود المناسب دون افتراض اسم واحد
    def wadq_get_value(row, candidates, default=None):
        for col in candidates:
            if col in row.index:
                value = row[col]
                if pd.notna(value):
                    return value
        return default

    # 3. إنشاء قائمة مستقلة للتقرير
    report_rows = []

    # 4. إضافة بيانات الأسواق العالمية والإنذارات
    market_df = wadq_global_market_df.copy()
    alerts_df = wadq_global_alerts_df.copy()

    # دمج الإنذارات مع بيانات الأسواق باستخدام الرمز
    symbol_candidates = ["الرمز", "symbol", "ticker", "رمز الأصل"]

    market_symbol_col = next(
        (c for c in symbol_candidates if c in market_df.columns),
        None
    )

    alert_symbol_col = next(
        (c for c in symbol_candidates if c in alerts_df.columns),
        None
    )

    if market_symbol_col and alert_symbol_col:
        alert_lookup = alerts_df.drop_duplicates(
            subset=[alert_symbol_col]
        ).set_index(alert_symbol_col)

        for _, row in market_df.iterrows():

            symbol = row[market_symbol_col]

            alert_row = (
                alert_lookup.loc[symbol]
                if symbol in alert_lookup.index
                else pd.Series(dtype=object)
            )

            report_rows.append({
                "نوع الأصل": "سوق عالمي",
                "الرمز": symbol,
                "الأصل": wadq_get_value(
                    row, ["الأصل", "اسم الأصل", "name"], symbol
                ),
                "السعر": wadq_get_value(
                    row,
                    ["أحدث سعر متاح", "السعر الحالي", "السعر"],
                    None
                ),
                "التغير اليومي %": wadq_get_value(
                    row,
                    ["% التغير اليومي", "التغير اليومي %", "التغير اليومي"],
                    None
                ),
                "حالة الحركة": wadq_get_value(
                    alert_row,
                    ["حالة الحركة", "الحالة"],
                    "غير محددة"
                ),
                "عدد الأخبار": None,
                "الأخبار الإيجابية": None,
                "الأخبار السلبية": None,
                "الأخبار المحايدة": None,
                "النتيجة الموحدة": None,
                "التقييم": None,
                "تاريخ البيانات": wadq_get_value(
                    row,
                    ["تاريخ آخر بيانات", "تاريخ البيانات"],
                    None
                ),
                "ملاحظة": wadq_get_value(
                    alert_row, ["ملاحظة", "ملاحظات"], ""
                )
            })

    else:
        print("⚠️ تعذر تحديد عمود الرمز في جداول الأسواق.")

    # 5. إضافة نتائج تحليل الأسهم الأمريكية
    us_df = wadq_us_ranking_df.copy()

    for _, row in us_df.iterrows():

        symbol = wadq_get_value(
            row,
            ["الرمز", "السهم", "ticker", "symbol"],
            "غير محدد"
        )

        report_rows.append({
            "نوع الأصل": "سهم أمريكي",
            "الرمز": symbol,
            "الأصل": wadq_get_value(
                row,
                ["الاسم", "الأصل", "اسم السهم", "السهم"],
                symbol
            ),
            "السعر": wadq_get_value(
                row,
                ["السعر الحالي", "أحدث سعر متاح", "السعر", "آخر سعر متاح"],
                None
            ),
            "التغير اليومي %": wadq_get_value(
                row,
                ["% التغير اليومي", "التغير اليومي %"],
                None
            ),
            "حالة الحركة": "تحليل فني وأخبار",
            "عدد الأخبار": wadq_get_value(
                row, ["عدد الأخبار"], 0
            ),
            "الأخبار الإيجابية": wadq_get_value(
                row, ["الأخبار الإيجابية"], 0
            ),
            "الأخبار السلبية": wadq_get_value(
                row, ["الأخبار السلبية"], 0
            ),
            "الأخبار المحايدة": wadq_get_value(
                row, ["الأخبار المحايدة"], 0
            ),
            "النتيجة الموحدة": wadq_get_value(
                row, ["النتيجة الموحدة"], None
            ),
            "التقييم": wadq_get_value(
                row, ["التقييم النهائي"], "غير محدد"
            ),
            "تاريخ البيانات": None,
            "ملاحظة": "التقييم مبدئي وليس توصية استثمارية"
        })

    # 6. إنشاء جدول التقرير العالمي الجديد
    wadq_global_master_report_df = pd.DataFrame(report_rows)

    # 7. ترتيب الأعمدة
    report_columns = [
        "نوع الأصل",
        "الرمز",
        "الأصل",
        "السعر",
        "التغير اليومي %",
        "حالة الحركة",
        "عدد الأخبار",
        "الأخبار الإيجابية",
        "الأخبار السلبية",
        "الأخبار المحايدة",
        "النتيجة الموحدة",
        "التقييم",
        "تاريخ البيانات",
        "ملاحظة"
    ]

    wadq_global_master_report_df = (
        wadq_global_master_report_df[report_columns]
    )

    # 8. عرض النتيجة
    print("\n✅ تم إنشاء التقرير العالمي الموحّد")
    print("اسم الجدول: wadq_global_master_report_df")
    print("عدد الصفوف:", len(wadq_global_master_report_df))
    print("عدد الأعمدة:", len(wadq_global_master_report_df.columns))

    print("\nعدد الأصول حسب النوع:")
    print(
        wadq_global_master_report_df["نوع الأصل"]
        .value_counts()
    )

    display(wadq_global_master_report_df)

    print("\n🌧️ اكتملت المرحلة 23.")
    print("تم إنشاء جدول جديد دون تعديل الجداول الأصلية.")

🌧️ الودق AI - إنشاء التقرير العالمي الموحّد
=================================================================

✅ تم إنشاء التقرير العالمي الموحّد
اسم الجدول: wadq_global_master_report_df
عدد الصفوف: 26
عدد الأعمدة: 14

عدد الأصول حسب النوع:
نوع الأصل
سوق عالمي     17
سهم أمريكي     9
Name: count, dtype: int64

,نوع الأصل,الرمز,الأصل,السعر,التغير اليومي %,حالة الحركة,عدد الأخبار,الأخبار الإيجابية,الأخبار السلبية,الأخبار المحايدة,النتيجة الموحدة,التقييم,تاريخ البيانات,ملاحظة
0,سوق عالمي,^GSPC,S&P 500 - أمريكا,7807.240234,-0.055044,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
1,سوق عالمي,^IXIC,Nasdaq Composite - أمريكا,27245.902344,-0.439475,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
2,سوق عالمي,^DJI,Dow Jones - أمريكا,51850.550781,0.378670,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
3,سوق عالمي,^GDAXI,DAX - ألمانيا,25277.679688,0.758991,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
4,سوق عالمي,^FCHI,CAC 40 - فرنسا,7832.879883,0.378682,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
5,سوق عالمي,^FTSE,FTSE 100 - بريطانيا,10656.280273,0.987298,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
6,سوق عالمي,^N225,Nikkei 225 - اليابان,69030.921875,-0.016204,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-09,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
7,سوق عالمي,^HSI,Hang Seng - هونغ كونغ,24211.349609,1.789138,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-09,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
8,سوق عالمي,GC=F,الذهب,4193.299805,-0.545502,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
9,سوق عالمي,SI=F,الفضة,60.480000,-0.313167,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
10,سوق عالمي,CL=F,النفط الأمريكي,93.309998,1.589547,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
11,سوق عالمي,BZ=F,نفط برنت,106.190002,1.403744,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
12,سوق عالمي,NG=F,الغاز الطبيعي,3.169000,-1.583855,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
13,سوق عالمي,EURUSD=X,اليورو مقابل الدولار,1.115573,-0.510931,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
14,سوق عالمي,JPY=X,الدولار مقابل الين,158.654007,0.373904,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
15,سوق عالمي,BTC-USD,بيتكوين,82809.937500,-1.039121,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
16,سوق عالمي,ETH-USD,إيثيريوم,2519.070068,-0.616608,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
17,سهم أمريكي,NVDA,إنفيديا,NaN,NaN,تحليل فني وأخبار,46.0,9.0,1.0,36.0,2.0,إيجابي مبدئيًا,None,التقييم مبدئي وليس توصية استثمارية
18,سهم أمريكي,TSLA,تسلا,NaN,NaN,تحليل فني وأخبار,20.0,2.0,0.0,18.0,2.0,إيجابي مبدئيًا,None,التقييم مبدئي وليس توصية استثمارية
19,سهم أمريكي,MSFT,مايكروسوفت,NaN,NaN,تحليل فني وأخبار,34.0,7.0,1.0,26.0,2.0,إيجابي مبدئيًا,None,التقييم مبدئي وليس توصية استثمارية
20,سهم أمريكي,META,ميتا,NaN,NaN,تحليل فني وأخبار,2.0,1.0,0.0,1.0,2.0,إيجابي مبدئيًا,None,التقييم مبدئي وليس توصية استثمارية
21,سهم أمريكي,GOOGL,ألفابت,NaN,NaN,تحليل فني وأخبار,20.0,5.0,0.0,15.0,2.0,إيجابي مبدئيًا,None,التقييم مبدئي وليس توصية استثمارية
22,سهم أمريكي,QQQ,ناسداك 100,NaN,NaN,تحليل فني وأخبار,5.0,2.0,0.0,3.0,2.0,إيجابي مبدئيًا,None,التقييم مبدئي وليس توصية استثمارية
23,سهم أمريكي,SPY,ستاندرد آند بورز 500,NaN,NaN,تحليل فني وأخبار,50.0,15.0,8.0,27.0,2.0,إيجابي مبدئيًا,None,التقييم مبدئي وليس توصية استثمارية
24,سهم أمريكي,AAPL,آبل,NaN,NaN,تحليل فني وأخبار,1.0,0.0,0.0,1.0,1.0,محايد أو متضارب,None,التقييم مبدئي وليس توصية استثمارية
25,سهم أمريكي,AMZN,أمازون,NaN,NaN,تحليل فني وأخبار,17.0,4.0,0.0,13.0,0.0,محايد أو متضارب,None,التقييم مبدئي وليس توصية استثمارية

🌧️ اكتملت المرحلة 23.
تم إنشاء جدول جديد دون تعديل الجداول الأصلية.

In [ ]:
# 🌧️ الودق AI - المرحلة 23.1
# فحص التقرير الموحّد وتحديد مصادر البيانات المتاحة

import pandas as pd
from IPython.display import display

print("🌧️ فحص التقرير العالمي الموحّد")
print("=" * 50)

tables_to_check = [
    "wadq_global_master_report_df",
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_ticker_news_df",
    "wadq_news_scored_df",
    "us_technical_df",
    "wadq_us_ranking_df"
]

for table_name in tables_to_check:
    if table_name in globals():
        table = globals()[table_name]
        if isinstance(table, pd.DataFrame):
            print(f"\n✅ {table_name}")
            print("عدد الصفوف:", len(table))
            print("الأعمدة:", list(table.columns))
    else:
        print(f"\n⚠️ {table_name}: غير موجود في الجلسة الحالية")

if "wadq_global_master_report_df" in globals():
    print("\n📊 معاينة التقرير الموحّد:")
    display(wadq_global_master_report_df.head(5))

🌧️ فحص التقرير العالمي الموحّد
==================================================

✅ wadq_global_master_report_df
عدد الصفوف: 26
الأعمدة: ['نوع الأصل', 'الرمز', 'الأصل', 'السعر', 'التغير اليومي %', 'حالة الحركة', 'عدد الأخبار', 'الأخبار الإيجابية', 'الأخبار السلبية', 'الأخبار المحايدة', 'النتيجة الموحدة', 'التقييم', 'تاريخ البيانات', 'ملاحظة']

✅ wadq_global_market_df
عدد الصفوف: 17
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

✅ wadq_global_alerts_df
عدد الصفوف: 17
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'التغير اليومي %', 'تاريخ آخر بيانات', 'حالة الحركة', 'ملاحظة']

✅ wadq_ticker_news_df
عدد الصفوف: 195
الأعمدة: ['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

✅ wadq_news_scored_df
عدد الصفوف: 565
الأعمدة: ['category', 'title', 'published', 'link', 'fetched_at_utc', 'sentiment', 'related_tickers', 'ticker_count']

✅ us_technical_df
عدد الصفوف: 9
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

✅ wadq_us_ranking_df
عدد الصفوف: 9
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه', 'عدد الأخبار', 'الأخبار الإيجابية', 'الأخبار السلبية', 'الأخبار المحايدة', 'التقييم الفني', 'صافي الأخبار', 'النتيجة الموحدة', 'التقييم النهائي']

📊 معاينة التقرير الموحّد:

,نوع الأصل,الرمز,الأصل,السعر,التغير اليومي %,حالة الحركة,عدد الأخبار,الأخبار الإيجابية,الأخبار السلبية,الأخبار المحايدة,النتيجة الموحدة,التقييم,تاريخ البيانات,ملاحظة
0,سوق عالمي,^GSPC,S&P 500 - أمريكا,7807.240234,-0.055044,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
1,سوق عالمي,^IXIC,Nasdaq Composite - أمريكا,27245.902344,-0.439475,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
2,سوق عالمي,^DJI,Dow Jones - أمريكا,51850.550781,0.378670,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
3,سوق عالمي,^GDAXI,DAX - ألمانيا,25277.679688,0.758991,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
4,سوق عالمي,^FCHI,CAC 40 - فرنسا,7832.879883,0.378682,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول

In [ ]:
# 🌧️ الودق AI - فحص ربط الأخبار بالتقرير
from IPython.display import display

tables_to_inspect = [
    "wadq_global_master_report_df",
    "wadq_ticker_news_df",
    "wadq_news_scored_df",
    "us_technical_df"
]

for name in tables_to_inspect:
    print("\n" + "=" * 60)
    print("📊 الجدول:", name)

    if name in globals():
        df = globals()[name]
        print("عدد الصفوف:", len(df))
        print("أسماء الأعمدة:")
        print(df.columns.tolist())
        print("\nأول 3 صفوف:")
        display(df.head(3))
    else:
        print("⚠️ الجدول غير موجود في الجلسة الحالية")

============================================================
📊 الجدول: wadq_global_master_report_df
عدد الصفوف: 26
أسماء الأعمدة:
['نوع الأصل', 'الرمز', 'الأصل', 'السعر', 'التغير اليومي %', 'حالة الحركة', 'عدد الأخبار', 'الأخبار الإيجابية', 'الأخبار السلبية', 'الأخبار المحايدة', 'النتيجة الموحدة', 'التقييم', 'تاريخ البيانات', 'ملاحظة']

أول 3 صفوف:

,نوع الأصل,الرمز,الأصل,السعر,التغير اليومي %,حالة الحركة,عدد الأخبار,الأخبار الإيجابية,الأخبار السلبية,الأخبار المحايدة,النتيجة الموحدة,التقييم,تاريخ البيانات,ملاحظة
0,سوق عالمي,^GSPC,S&P 500 - أمريكا,7807.240234,-0.055044,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
1,سوق عالمي,^IXIC,Nasdaq Composite - أمريكا,27245.902344,-0.439475,انخفاض محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
2,سوق عالمي,^DJI,Dow Jones - أمريكا,51850.550781,0.378670,ارتفاع محدود,NaN,NaN,NaN,NaN,NaN,None,2026-10-12,تنبيه مبني على تغير السعر فقط، وليس توصية تداول

============================================================
📊 الجدول: wadq_ticker_news_df
عدد الصفوف: 195
أسماء الأعمدة:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

أول 3 صفوف:

,ticker,news_title,sentiment,category,published,link
0,SPY,"Stock Market Today: Dow gains but S&P 500, Nas...",إيجابي مبدئي,الأسواق الأمريكية,"Mon, 12 Oct 2026 19:07:00 GMT",https://news.google.com/rss/articles/CBMiugFBV...
1,SPY,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...",إيجابي مبدئي,الأسواق الأمريكية,"Mon, 12 Oct 2026 18:43:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...
2,QQQ,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 12 Oct 2026 12:29:52 GMT",https://news.google.com/rss/articles/CBMiqgJBV...

============================================================
📊 الجدول: wadq_news_scored_df
عدد الصفوف: 565
أسماء الأعمدة:
['category', 'title', 'published', 'link', 'fetched_at_utc', 'sentiment', 'related_tickers', 'ticker_count']

أول 3 صفوف:

,category,title,published,link,fetched_at_utc,sentiment,related_tickers,ticker_count
0,الأسواق الأمريكية,Update: Equities Mostly Down Intraday Ahead of...,"Mon, 12 Oct 2026 17:59:06 GMT",https://news.google.com/rss/articles/CBMiogFBV...,2026-10-12T20:24:17.168470+00:00,محايد أو غير واضح,[],0
1,الأسواق الأمريكية,U.S. Markets Ended Monday Mixed As Fair Isaac ...,"Mon, 12 Oct 2026 20:10:00 GMT",https://news.google.com/rss/articles/CBMitAFBV...,2026-10-12T20:24:17.168495+00:00,محايد أو غير واضح,[],0
2,الأسواق الأمريكية,Stocks Face a Tricky Patch. Banks and Bonds Co...,"Mon, 12 Oct 2026 17:35:00 GMT",https://news.google.com/rss/articles/CBMihwFBV...,2026-10-12T20:24:17.168502+00:00,محايد أو غير واضح,[],0

============================================================
📊 الجدول: us_technical_df
عدد الصفوف: 9
أسماء الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

أول 3 صفوف:

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,226.32,227.50,222.46,49.42,ضمن النطاق المتوسط,3.3139,3.7581,مختلط
1,تسلا,TSLA,378.03,369.61,356.08,56.46,ضمن النطاق المتوسط,5.1446,4.2311,صاعد
2,آبل,AAPL,340.97,335.78,323.00,60.22,ضمن النطاق المتوسط,3.6456,3.8354,صاعد

In [ ]:
# 🌧️ الودق AI - المرحلة 24
# فحص تطابق رموز الأسهم بين الأخبار والتحليل الفني

import pandas as pd
from IPython.display import display

print("🌧️ فحص ربط الأخبار بالتحليل الفني")
print("=" * 50)

if "wadq_ticker_news_df" in globals() and "us_technical_df" in globals():

    news_tickers = set(
        wadq_ticker_news_df["ticker"]
        .dropna()
        .astype(str)
        .str.upper()
    )

    technical_tickers = set(
        us_technical_df["الرمز"]
        .dropna()
        .astype(str)
        .str.upper()
    )

    print("عدد رموز الأسهم في الأخبار:", len(news_tickers))
    print("عدد رموز الأسهم في التحليل الفني:", len(technical_tickers))

    print("\nالرموز المشتركة:")
    print(sorted(news_tickers & technical_tickers))

    print("\nرموز التحليل الفني التي لا توجد لها أخبار مرتبطة:")
    print(sorted(technical_tickers - news_tickers))

    print("\nأعمدة الأخبار:")
    print(wadq_ticker_news_df.columns.tolist())

    print("\nأعمدة التحليل الفني:")
    print(us_technical_df.columns.tolist())

else:
    print("⚠️ أحد الجدولين غير موجود في الجلسة الحالية.")

🌧️ فحص ربط الأخبار بالتحليل الفني
==================================================
عدد رموز الأسهم في الأخبار: 9
عدد رموز الأسهم في التحليل الفني: 9

الرموز المشتركة:
['AAPL', 'AMZN', 'GOOGL', 'META', 'MSFT', 'NVDA', 'QQQ', 'SPY', 'TSLA']

رموز التحليل الفني التي لا توجد لها أخبار مرتبطة:
[]

أعمدة الأخبار:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

أعمدة التحليل الفني:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

In [ ]:
# 🌧️ الودق AI - المرحلة 25
# دمج الأخبار مع التحليل الفني للأسهم الأمريكية
# إنشاء جدول جديد دون تعديل الجداول الأصلية

import pandas as pd
from IPython.display import display

print("🌧️ الودق AI - دمج الأخبار والتحليل الفني")
print("=" * 60)

# 1. التحقق من وجود الجداول المطلوبة
if "wadq_ticker_news_df" not in globals():
    raise ValueError(
        "جدول الأخبار غير موجود. شغّلي خلية جمع الأخبار أولاً."
    )

if "us_technical_df" not in globals():
    raise ValueError(
        "جدول التحليل الفني غير موجود في الجلسة الحالية."
    )

# 2. إنشاء نسخ مستقلة للعمل
news = wadq_ticker_news_df.copy()
technical = us_technical_df.copy()

# 3. التحقق من الأعمدة المطلوبة
required_news_columns = [
    "ticker", "news_title", "sentiment", "published", "link"
]

required_technical_columns = ["الرمز"]

missing_news = [
    col for col in required_news_columns
    if col not in news.columns
]

missing_technical = [
    col for col in required_technical_columns
    if col not in technical.columns
]

if missing_news:
    raise ValueError(
        f"أعمدة ناقصة في جدول الأخبار: {missing_news}"
    )

if missing_technical:
    raise ValueError(
        f"أعمدة ناقصة في جدول التحليل الفني: {missing_technical}"
    )

# 4. توحيد رموز الأسهم
news["ticker"] = (
    news["ticker"].astype(str).str.upper().str.strip()
)

technical["الرمز"] = (
    technical["الرمز"].astype(str).str.upper().str.strip()
)

# 5. ترتيب الأخبار من الأحدث إلى الأقدم
news["published"] = pd.to_datetime(
    news["published"],
    errors="coerce",
    utc=True
)

news = news.sort_values(
    "published",
    ascending=False,
    na_position="last"
)

# 6. حساب عدد الأخبار المرتبطة بكل سهم
news_summary = (
    news.groupby("ticker")
    .size()
    .reset_index(name="عدد الأخبار")
    .rename(columns={"ticker": "الرمز"})
)

# 7. استخراج أحدث خبر لكل سهم
latest_news = (
    news.drop_duplicates(
        subset=["ticker"],
        keep="first"
    )
    [["ticker", "news_title", "sentiment", "published", "link"]]
    .rename(columns={
        "ticker": "الرمز",
        "news_title": "أحدث عنوان خبر",
        "sentiment": "تقييم أحدث خبر",
        "published": "تاريخ أحدث خبر",
        "link": "رابط أحدث خبر"
    })
)

# 8. دمج الأخبار مع التحليل الفني
wadq_us_news_technical_df = (
    technical
    .merge(news_summary, on="الرمز", how="left")
    .merge(latest_news, on="الرمز", how="left")
)

# 9. معالجة عدد الأخبار غير المتوفر
wadq_us_news_technical_df["عدد الأخبار"] = (
    wadq_us_news_technical_df["عدد الأخبار"]
    .fillna(0)
    .astype(int)
)

# 10. عرض النتائج
print("\n✅ تم إنشاء جدول الأخبار والتحليل الفني.")
print("اسم الجدول: wadq_us_news_technical_df")
print("عدد الأسهم:", len(wadq_us_news_technical_df))
print("عدد الأعمدة:", len(wadq_us_news_technical_df.columns))

display(wadq_us_news_technical_df)

print("\n🌧️ انتهت المرحلة 25.")

🌧️ الودق AI - دمج الأخبار والتحليل الفني
============================================================

✅ تم إنشاء جدول الأخبار والتحليل الفني.
اسم الجدول: wadq_us_news_technical_df
عدد الأسهم: 9
عدد الأعمدة: 15

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه,عدد الأخبار,أحدث عنوان خبر,تقييم أحدث خبر,تاريخ أحدث خبر,رابط أحدث خبر
0,إنفيديا,NVDA,226.32,227.50,222.46,49.42,ضمن النطاق المتوسط,3.3139,3.7581,مختلط,46,Wall Street stocks end tad lower after hot inf...,محايد أو غير واضح,2026-08-26 07:00:00+00:00,https://news.google.com/rss/articles/CBMiqwFBV...
1,تسلا,TSLA,378.03,369.61,356.08,56.46,ضمن النطاق المتوسط,5.1446,4.2311,صاعد,20,Zacks Investment Ideas feature highlights: App...,محايد أو غير واضح,2026-08-03 07:00:00+00:00,https://news.google.com/rss/articles/CBMiqgFBV...
2,آبل,AAPL,340.97,335.78,323.00,60.22,ضمن النطاق المتوسط,3.6456,3.8354,صاعد,1,"Are Amazon, Apple stocks overpriced? Here are ...",محايد أو غير واضح,2025-09-19 07:00:00+00:00,https://news.google.com/rss/articles/CBMitAFBV...
3,مايكروسوفت,MSFT,541.15,511.89,501.73,69.92,ضمن النطاق المتوسط,11.6192,9.6870,صاعد,34,Here are Monday's biggest analyst calls: Nvidi...,محايد أو غير واضح,2026-08-10 07:00:00+00:00,https://news.google.com/rss/articles/CBMimgFBV...
4,أمازون,AMZN,259.53,252.32,258.85,55.59,ضمن النطاق المتوسط,0.7570,-0.6976,مختلط,17,Zacks Investment Ideas feature highlights: App...,محايد أو غير واضح,2026-08-03 07:00:00+00:00,https://news.google.com/rss/articles/CBMiqgFBV...
5,ألفابت,GOOGL,352.72,346.09,346.08,57.30,ضمن النطاق المتوسط,1.6851,0.6300,صاعد,20,"Micron's up, but Nvidia, Alphabet, Meta, Micro...",محايد أو غير واضح,2026-06-25 07:00:00+00:00,https://news.google.com/rss/articles/CBMixAFBV...
6,ميتا,META,742.96,722.94,643.13,62.32,ضمن النطاق المتوسط,24.8981,29.7186,صاعد,2,I Predicted That Oracle and Netflix Would Join...,محايد أو غير واضح,2026-02-13 08:00:00+00:00,https://news.google.com/rss/articles/CBMilAFBV...
7,ناسداك 100,QQQ,746.04,739.24,725.18,56.72,ضمن النطاق المتوسط,9.0018,8.9299,صاعد,5,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,2026-10-12 12:29:52+00:00,https://news.google.com/rss/articles/CBMiqgJBV...
8,ستاندرد آند بورز 500,SPY,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد,50,"Stock Market Today: Dow gains but S&P 500, Nas...",إيجابي مبدئي,2026-10-12 19:07:00+00:00,https://news.google.com/rss/articles/CBMiugFBV...

🌧️ انتهت المرحلة 25.

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 26
# ربط الأخبار الأمريكية بالتحليل الفني
# خلية جديدة دون تعديل الجداول السابقة
# ============================================================

import pandas as pd

# التأكد من وجود الجداول المطلوبة
if "us_technical_df" not in globals():
    print("⚠️ جدول التحليل الفني الأمريكي غير موجود.")
    print("شغّلي خلية إنشاء us_technical_df أولاً.")

elif "wadq_ticker_news_df" not in globals():
    print("⚠️ جدول أخبار الأسهم غير موجود.")
    print("شغّلي خلية إنشاء wadq_ticker_news_df أولاً.")

else:
    technical = us_technical_df.copy()
    news = wadq_ticker_news_df.copy()

    # تحديد أسماء الأعمدة المتاحة
    ticker_col = (
        "الرمز" if "الرمز" in technical.columns
        else "ticker" if "ticker" in technical.columns
        else "symbol" if "symbol" in technical.columns
        else None
    )

    news_ticker_col = (
        "ticker" if "ticker" in news.columns
        else "الرمز" if "الرمز" in news.columns
        else None
    )

    if ticker_col is None or news_ticker_col is None:
        print("⚠️ تعذر تحديد عمود رمز السهم.")
        print("أعمدة التحليل الفني:", technical.columns.tolist())
        print("أعمدة الأخبار:", news.columns.tolist())

    else:
        # توحيد الرموز
        technical[ticker_col] = (
            technical[ticker_col].astype(str).str.upper().str.strip()
        )

        news[news_ticker_col] = (
            news[news_ticker_col].astype(str).str.upper().str.strip()
        )

        # أسماء الأعمدة المحتملة
        title_col = (
            "news_title" if "news_title" in news.columns
            else "title" if "title" in news.columns
            else None
        )

        sentiment_col = (
            "sentiment" if "sentiment" in news.columns
            else None
        )

        # الاحتفاظ بأسماء الجداول الأصلية دون تغيير
        wadq_us_news_technical_df = news.merge(
            technical,
            left_on=news_ticker_col,
            right_on=ticker_col,
            how="left",
            suffixes=("_خبر", "_فني")
        )

        print("🌧️ الودق AI — المرحلة 26")
        print("=" * 50)
        print("✅ تم إنشاء جدول ربط الأخبار بالتحليل الفني.")
        print("اسم الجدول: wadq_us_news_technical_df")
        print("عدد الأخبار:", len(wadq_us_news_technical_df))
        print("عدد الأعمدة:", len(wadq_us_news_technical_df.columns))

        if title_col is not None:
            columns_to_show = [
                news_ticker_col,
                title_col
            ]

            if sentiment_col is not None:
                columns_to_show.append(sentiment_col)

            extra_columns = [
                col for col in technical.columns
                if col != ticker_col
            ]

            columns_to_show += extra_columns

            columns_to_show = [
                col for col in columns_to_show
                if col in wadq_us_news_technical_df.columns
            ]

            display(
                wadq_us_news_technical_df[columns_to_show].head(20)
            )
        else:
            display(wadq_us_news_technical_df.head(20))

        print("\n✅ انتهت المرحلة 26.")

🌧️ الودق AI — المرحلة 26
==================================================
✅ تم إنشاء جدول ربط الأخبار بالتحليل الفني.
اسم الجدول: wadq_us_news_technical_df
عدد الأخبار: 195
عدد الأعمدة: 16

,ticker,news_title,sentiment,السهم,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,SPY,"Stock Market Today: Dow gains but S&P 500, Nas...",إيجابي مبدئي,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
1,SPY,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...",إيجابي مبدئي,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
2,QQQ,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,ناسداك 100,746.04,739.24,725.18,56.72,ضمن النطاق المتوسط,9.0018,8.9299,صاعد
3,SPY,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
4,QQQ,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,ناسداك 100,746.04,739.24,725.18,56.72,ضمن النطاق المتوسط,9.0018,8.9299,صاعد
5,SPY,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
6,SPY,"S&P 500 little changed, Dow and Nasdaq mixed a...",محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
7,SPY,"Stock market today: Dow and S&P 500 gain, Nasd...",إيجابي مبدئي,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
8,SPY,"S&P 500, Nasdaq end lower as crude prices jump...",محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
9,SPY,"The S&P 500 Hits a New Record High, Powered by...",إيجابي مبدئي,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
10,SPY,"S&P 500 dips, Nasdaq higher after data shows m...",إيجابي مبدئي,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
11,SPY,"S&P 500, Nasdaq, Dow Forecast: Wall Street Spl...",محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
12,QQQ,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,ناسداك 100,746.04,739.24,725.18,56.72,ضمن النطاق المتوسط,9.0018,8.9299,صاعد
13,SPY,"Dow Jones, S&P 500, Nasdaq 100 Outlook: Top St...",محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
14,SPY,S&P 500 and Nasdaq surge to record highs after...,إيجابي مبدئي,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
15,SPY,U.S. stock market drops: S&P 500 and Nasdaq fa...,سلبي مبدئي,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
16,SPY,S&P 500 ends marginally lower as investors foc...,محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
17,SPY,"Stock Market Today: S&P 500, Dow, Nasdaq Futur...",سلبي مبدئي,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
18,SPY,"S&P 500, Nasdaq end down on tech stocks, inves...",محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد
19,SPY,US Stock Market Today: S&P 500 Futures Climb A...,محايد أو غير واضح,ستاندرد آند بورز 500,778.07,768.55,766.94,59.89,ضمن النطاق المتوسط,3.8745,2.8224,صاعد

✅ انتهت المرحلة 26.

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 27
# التقرير العالمي الموحد للأسواق والأخبار والتحليل الفني
# إضافة خلية جديدة دون تعديل الخلايا السابقة
# ============================================================

import pandas as pd

print("🌧️ الودق AI")
print("=" * 65)
print("بدء إنشاء التقرير العالمي الموحد...")
print()

# ------------------------------------------------------------
# 1. تحديد الجداول المتاحة
# ------------------------------------------------------------

global_df = globals().get("wadq_global_alerts_df")
technical_df = globals().get("us_technical_df")
news_df = globals().get("wadq_ticker_news_df")

# التحقق من الجداول الأساسية
if not isinstance(global_df, pd.DataFrame):
    global_df = globals().get("wadq_global_market_df")

if not isinstance(global_df, pd.DataFrame):
    print("⚠️ جدول الأسواق العالمية غير موجود.")
    print("شغّلي خلية إنشاء بيانات الأسواق العالمية أولاً.")

elif not isinstance(technical_df, pd.DataFrame):
    print("⚠️ جدول التحليل الفني الأمريكي غير موجود.")
    print("شغّلي خلية التحليل الفني الأمريكي أولاً.")

else:

    # --------------------------------------------------------
    # 2. دالة لاكتشاف أسماء الأعمدة
    # --------------------------------------------------------

    def wadq_find_column(df, candidates):
        for col in candidates:
            if col in df.columns:
                return col
        return None

    # --------------------------------------------------------
    # 3. تجهيز بيانات الأسواق العالمية
    # --------------------------------------------------------

    global_symbol_col = wadq_find_column(
        global_df,
        ["الرمز", "ticker", "symbol"]
    )

    global_name_col = wadq_find_column(
        global_df,
        ["الأصل", "السهم", "الاسم", "name"]
    )

    global_price_col = wadq_find_column(
        global_df,
        ["أحدث سعر متاح", "آخر إغلاق", "السعر", "price"]
    )

    global_change_col = wadq_find_column(
        global_df,
        ["التغير اليومي %", "التغير اليومي", "change_pct"]
    )

    global_status_col = wadq_find_column(
        global_df,
        ["حالة الحركة", "الاتجاه", "الحالة"]
    )

    global_note_col = wadq_find_column(
        global_df,
        ["ملاحظة", "التنبيه"]
    )

    if global_symbol_col is None:
        print("⚠️ لم أتمكن من تحديد عمود رموز الأسواق العالمية.")
        print("الأعمدة المتاحة:", global_df.columns.tolist())

    else:

        global_report = pd.DataFrame()

        global_report["الرمز"] = (
            global_df[global_symbol_col].astype(str).str.strip()
        )

        global_report["الأصل"] = (
            global_df[global_name_col]
            if global_name_col else global_report["الرمز"]
        )

        global_report["السعر"] = (
            global_df[global_price_col]
            if global_price_col else float("nan")
        )

        global_report["التغير اليومي %"] = (
            global_df[global_change_col]
            if global_change_col else float("nan")
        )

        global_report["الاتجاه الفني"] = (
            global_df[global_status_col]
            if global_status_col else "غير متاح"
        )

        global_report["RSI"] = float("nan")
        global_report["إشارة MACD"] = "غير متاح"

        global_report["ملاحظة السوق"] = (
            global_df[global_note_col]
            if global_note_col else ""
        )

        global_report["نوع الأصل"] = "سوق عالمي"

        # ----------------------------------------------------
        # 4. إضافة الأسهم الأمريكية والتحليل الفني
        # ----------------------------------------------------

        us_symbol_col = wadq_find_column(
            technical_df,
            ["الرمز", "ticker", "symbol"]
        )

        us_name_col = wadq_find_column(
            technical_df,
            ["السهم", "الأصل", "الاسم", "name"]
        )

        us_price_col = wadq_find_column(
            technical_df,
            ["آخر إغلاق", "أحدث سعر", "السعر", "Close"]
        )

        us_change_col = wadq_find_column(
            technical_df,
            ["التغير اليومي %", "التغير %", "change_pct"]
        )

        us_rsi_col = wadq_find_column(
            technical_df,
            ["RSI"]
        )

        us_macd_col = wadq_find_column(
            technical_df,
            ["إشارة MACD", "MACD"]
        )

        us_trend_col = wadq_find_column(
            technical_df,
            ["الاتجاه", "الاتجاه الفني", "حالة الاتجاه"]
        )

        if us_symbol_col is None:
            print("⚠️ لم يتم العثور على رمز السهم الأمريكي.")
            print("أعمدة التحليل الفني:", technical_df.columns.tolist())

        else:

            us_report = pd.DataFrame()

            us_report["الرمز"] = (
                technical_df[us_symbol_col]
                .astype(str)
                .str.strip()
            )

            us_report["الأصل"] = (
                technical_df[us_name_col]
                if us_name_col else us_report["الرمز"]
            )

            us_report["السعر"] = (
                technical_df[us_price_col]
                if us_price_col else float("nan")
            )

            us_report["التغير اليومي %"] = (
                technical_df[us_change_col]
                if us_change_col else float("nan")
            )

            us_report["الاتجاه الفني"] = (
                technical_df[us_trend_col]
                if us_trend_col else "غير متاح"
            )

            us_report["RSI"] = (
                technical_df[us_rsi_col]
                if us_rsi_col else float("nan")
            )

            us_report["إشارة MACD"] = (
                technical_df[us_macd_col]
                if us_macd_col else "غير متاح"
            )

            us_report["ملاحظة السوق"] = ""
            us_report["نوع الأصل"] = "سهم أمريكي"

            # دمج الأسواق العالمية والأسهم الأمريكية
            wadq_global_master_report_df = pd.concat(
                [global_report, us_report],
                ignore_index=True
            )

            # إزالة تكرار الرمز إن وجد
            wadq_global_master_report_df = (
                wadq_global_master_report_df
                .drop_duplicates(subset=["الرمز"], keep="last")
                .reset_index(drop=True)
            )

            # ------------------------------------------------
            # 5. تلخيص الأخبار المرتبطة بكل سهم
            # ------------------------------------------------

            if (
                isinstance(news_df, pd.DataFrame)
                and not news_df.empty
            ):

                news_symbol_col = wadq_find_column(
                    news_df,
                    ["ticker", "الرمز", "symbol"]
                )

                news_title_col = wadq_find_column(
                    news_df,
                    ["news_title", "title", "عنوان الخبر"]
                )

                news_sentiment_col = wadq_find_column(
                    news_df,
                    ["sentiment", "المشاعر", "التصنيف"]
                )

                if news_symbol_col is not None:

                    news_work = news_df.copy()

                    news_work["_symbol"] = (
                        news_work[news_symbol_col]
                        .astype(str)
                        .str.strip()
                    )

                    news_work["_sentiment"] = (
                        news_work[news_sentiment_col]
                        .astype(str)
                        if news_sentiment_col
                        else "غير مصنف"
                    )

                    news_work["_title"] = (
                        news_work[news_title_col]
                        .astype(str)
                        if news_title_col
                        else ""
                    )

                    news_work["_positive"] = (
                        news_work["_sentiment"]
                        .str.contains("إيجابي|إيجاب", regex=True)
                    ).astype(int)

                    news_work["_negative"] = (
                        news_work["_sentiment"]
                        .str.contains("سلبي", regex=True)
                    ).astype(int)

                    news_work["_neutral"] = (
                        (
                            news_work["_positive"].eq(0)
                            & news_work["_negative"].eq(0)
                        )
                    ).astype(int)

                    wadq_news_summary_df = (
                        news_work.groupby("_symbol")
                        .agg(
                            عدد_الأخبار=("_title", "count"),
                            أخبار_إيجابية=("_positive", "sum"),
                            أخبار_سلبية=("_negative", "sum"),
                            أخبار_محايدة=("_neutral", "sum"),
                            أحدث_عنوان_متاح=("_title", "first")
                        )
                        .reset_index()
                        .rename(columns={"_symbol": "الرمز"})
                    )

                    wadq_global_master_report_df = (
                        wadq_global_master_report_df.merge(
                            wadq_news_summary_df,
                            on="الرمز",
                            how="left"
                        )
                    )

            # ------------------------------------------------
            # 6. معالجة الأصول التي لا تتوفر لها أخبار
            # ------------------------------------------------

            news_columns = [
                "عدد_الأخبار",
                "أخبار_إيجابية",
                "أخبار_سلبية",
                "أخبار_محايدة"
            ]

            for col in news_columns:
                if col not in wadq_global_master_report_df.columns:
                    wadq_global_master_report_df[col] = 0

                wadq_global_master_report_df[col] = (
                    wadq_global_master_report_df[col]
                    .fillna(0)
                    .astype(int)
                )

            if "أحدث_عنوان_متاح" not in wadq_global_master_report_df.columns:
                wadq_global_master_report_df["أحدث_عنوان_متاح"] = ""

            # ------------------------------------------------
            # 7. ترتيب أعمدة التقرير
            # ------------------------------------------------

            report_columns = [
                "نوع الأصل",
                "الأصل",
                "الرمز",
                "السعر",
                "التغير اليومي %",
                "الاتجاه الفني",
                "RSI",
                "إشارة MACD",
                "عدد_الأخبار",
                "أخبار_إيجابية",
                "أخبار_سلبية",
                "أخبار_محايدة",
                "أحدث_عنوان_متاح",
                "ملاحظة السوق"
            ]

            wadq_global_master_report_df = (
                wadq_global_master_report_df[report_columns]
            )

            # ------------------------------------------------
            # 8. عرض التقرير العالمي الموحد
            # ------------------------------------------------

            print("✅ تم إنشاء التقرير العالمي الموحد!")
            print("=" * 65)

            print(
                "اسم الجدول: wadq_global_master_report_df"
            )

            print(
                "عدد الأصول:",
                len(wadq_global_master_report_df)
            )

            print(
                "عدد الأعمدة:",
                len(wadq_global_master_report_df.columns)
            )

            print()

            display(wadq_global_master_report_df)

            print()
            print("🌧️ انتهت المرحلة 27 بنجاح.")

🌧️ الودق AI
=================================================================
بدء إنشاء التقرير العالمي الموحد...

✅ تم إنشاء التقرير العالمي الموحد!
=================================================================
اسم الجدول: wadq_global_master_report_df
عدد الأصول: 26
عدد الأعمدة: 14

,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق
0,سوق عالمي,Hang Seng - هونغ كونغ,^HSI,24211.349609,1.789138,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
1,سوق عالمي,النفط الأمريكي,CL=F,93.309998,1.589547,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
2,سوق عالمي,نفط برنت,BZ=F,106.190002,1.403744,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
3,سوق عالمي,FTSE 100 - بريطانيا,^FTSE,10656.280273,0.987298,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
4,سوق عالمي,DAX - ألمانيا,^GDAXI,25277.679688,0.758991,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
5,سوق عالمي,CAC 40 - فرنسا,^FCHI,7832.879883,0.378682,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
6,سوق عالمي,Dow Jones - أمريكا,^DJI,51850.550781,0.378670,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
7,سوق عالمي,الدولار مقابل الين,JPY=X,158.654007,0.373904,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
8,سوق عالمي,Nikkei 225 - اليابان,^N225,69030.921875,-0.016204,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
9,سوق عالمي,S&P 500 - أمريكا,^GSPC,7807.240234,-0.055044,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
10,سوق عالمي,الفضة,SI=F,60.480000,-0.313167,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
11,سوق عالمي,Nasdaq Composite - أمريكا,^IXIC,27245.902344,-0.439475,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
12,سوق عالمي,اليورو مقابل الدولار,EURUSD=X,1.115573,-0.510931,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
13,سوق عالمي,الذهب,GC=F,4193.299805,-0.545502,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
14,سوق عالمي,إيثيريوم,ETH-USD,2519.070068,-0.616608,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
15,سوق عالمي,بيتكوين,BTC-USD,82809.937500,-1.039121,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
16,سوق عالمي,الغاز الطبيعي,NG=F,3.169000,-1.583855,انخفاض محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
17,سهم أمريكي,إنفيديا,NVDA,226.320000,NaN,مختلط,49.42,3.7581,46,9,1,36,Wall Street stocks end tad lower after hot inf...,
18,سهم أمريكي,تسلا,TSLA,378.030000,NaN,صاعد,56.46,4.2311,20,2,0,18,Zacks Investment Ideas feature highlights: App...,
19,سهم أمريكي,آبل,AAPL,340.970000,NaN,صاعد,60.22,3.8354,1,0,0,1,"Are Amazon, Apple stocks overpriced? Here are ...",
20,سهم أمريكي,مايكروسوفت,MSFT,541.150000,NaN,صاعد,69.92,9.687,34,7,1,26,Zacks Investment Ideas feature highlights: App...,
21,سهم أمريكي,أمازون,AMZN,259.530000,NaN,مختلط,55.59,-0.6976,17,4,0,13,Zacks Investment Ideas feature highlights: App...,
22,سهم أمريكي,ألفابت,GOOGL,352.720000,NaN,صاعد,57.30,0.63,20,5,0,15,"Prediction: Nvidia Will Overtake Alphabet, App...",
23,سهم أمريكي,ميتا,META,742.960000,NaN,صاعد,62.32,29.7186,2,1,0,1,I Predicted That Oracle and Netflix Would Join...,
24,سهم أمريكي,ناسداك 100,QQQ,746.040000,NaN,صاعد,56.72,8.9299,5,2,0,3,"Stock Market Today: S&P 500, Dow Futures Gain,...",
25,سهم أمريكي,ستاندرد آند بورز 500,SPY,778.070000,NaN,صاعد,59.89,2.8224,50,15,8,27,"Stock Market Today: Dow gains but S&P 500, Nas...",

🌧️ انتهت المرحلة 27 بنجاح.

In [ ]:
# =========================================================
# 🌧️ الودق AI — فحص مصادر التقرير العالمي
# فحص فقط دون تعديل الجداول
# =========================================================

import pandas as pd

print("🌧️ فحص مصادر التقرير العالمي")
print("=" * 55)

table_names = [
    "wadq_global_market_df",
    "us_technical_df",
    "wadq_ticker_news_df"
]

for name in table_names:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name} موجود")
        print("عدد الصفوف:", len(obj))
        print("عدد الأعمدة:", len(obj.columns))
    else:
        print(f"⚠️ {name} غير موجود في الذاكرة الحالية")

print("=" * 55)
print("انتهى الفحص دون تعديل أي جدول.")

🌧️ فحص مصادر التقرير العالمي
=======================================================
⚠️ wadq_global_market_df غير موجود في الذاكرة الحالية
⚠️ us_technical_df غير موجود في الذاكرة الحالية
⚠️ wadq_ticker_news_df غير موجود في الذاكرة الحالية
=======================================================
انتهى الفحص دون تعديل أي جدول.

In [ ]:
# ============================================================
# 🌧️ الودق AI — المرحلة 28
# تحليل توافق الأخبار مع الاتجاه الفني
# ============================================================

import pandas as pd

report_name = "wadq_global_master_report_df"

if report_name not in globals():
    print("⚠️ التقرير العالمي الموحد غير موجود.")
    print("شغّلي خلية المرحلة 27 أولاً.")

else:
    report = globals()[report_name].copy()

    # التأكد من وجود أعمدة الأخبار
    news_columns = [
        "أخبار_إيجابية",
        "أخبار_سلبية",
        "أخبار_محايدة"
    ]

    for col in news_columns:
        if col not in report.columns:
            report[col] = 0

        report[col] = pd.to_numeric(
            report[col],
            errors="coerce"
        ).fillna(0)

    # تحديد المشاعر العامة للأخبار
    def wadq_news_mood(row):
        positive = row["أخبار_إيجابية"]
        negative = row["أخبار_سلبية"]
        neutral = row["أخبار_محايدة"]

        total = positive + negative + neutral

        if total == 0:
            return "أخبار غير متاحة"

        if positive > negative:
            return "إيجابي"

        if negative > positive:
            return "سلبي"

        return "محايد أو مختلط"

    report["تقييم الأخبار"] = report.apply(
        wadq_news_mood,
        axis=1
    )

    # قراءة الاتجاه الفني
    trend_col = (
        "الاتجاه الفني"
        if "الاتجاه الفني" in report.columns
        else "ملاحظة السوق"
        if "ملاحظة السوق" in report.columns
        else None
    )

    def wadq_read_trend(value):
        if pd.isna(value):
            return "غير متاح"

        value = str(value).strip().lower()

        if any(word in value for word in [
            "صاعد", "ارتفاع", "إيجابي", "bullish", "uptrend"
        ]):
            return "صاعد"

        if any(word in value for word in [
            "هابط", "انخفاض", "سلبي", "bearish", "downtrend"
        ]):
            return "هابط"

        return "غير واضح"

    if trend_col:
        report["الاتجاه المقروء"] = report[trend_col].apply(
            wadq_read_trend
        )
    else:
        report["الاتجاه المقروء"] = "غير متاح"

    # مقارنة الأخبار بالاتجاه الفني
    def wadq_compare_news_trend(row):
        mood = row["تقييم الأخبار"]
        trend = row["الاتجاه المقروء"]

        if mood == "أخبار غير متاحة":
            return "بيانات الأخبار غير كافية"

        if trend == "غير متاح" or trend == "غير واضح":
            return "الاتجاه الفني غير واضح"

        if mood == "محايد أو مختلط":
            return "الأخبار مختلطة؛ يلزم تحليل إضافي"

        if mood == "إيجابي" and trend == "صاعد":
            return "توافق إيجابي"

        if mood == "سلبي" and trend == "هابط":
            return "توافق سلبي"

        return "تعارض بين الأخبار والاتجاه"

    report["توافق الأخبار والفني"] = report.apply(
        wadq_compare_news_trend,
        axis=1
    )

    # حفظ النتيجة في جدول جديد
    wadq_global_analysis_df = report.copy()

    # عرض التقرير
    display_columns = [
        col for col in [
            "نوع الأصل",
            "الأصل",
            "الرمز",
            "التغير اليومي %",
            "الاتجاه المقروء",
            "تقييم الأخبار",
            "عدد_الأخبار",
            "توافق الأخبار والفني"
        ]
        if col in wadq_global_analysis_df.columns
    ]

    print("🌧️ الودق AI — المرحلة 28")
    print("=" * 55)
    print("✅ اكتمل تحليل توافق الأخبار والاتجاه الفني.")
    print("اسم الجدول: wadq_global_analysis_df")
    print("عدد الأصول:", len(wadq_global_analysis_df))
    print()

    display(
        wadq_global_analysis_df[display_columns]
    )

    print("\n✅ انتهت المرحلة 28.")
    print("ملاحظة: هذه مؤشرات تحليلية وليست توصيات شراء أو بيع.")

🌧️ الودق AI — المرحلة 28
=======================================================
✅ اكتمل تحليل توافق الأخبار والاتجاه الفني.
اسم الجدول: wadq_global_analysis_df
عدد الأصول: 26

,نوع الأصل,الأصل,الرمز,التغير اليومي %,الاتجاه المقروء,تقييم الأخبار,عدد_الأخبار,توافق الأخبار والفني
0,سوق عالمي,Hang Seng - هونغ كونغ,^HSI,1.789138,صاعد,أخبار غير متاحة,0,بيانات الأخبار غير كافية
1,سوق عالمي,النفط الأمريكي,CL=F,1.589547,صاعد,أخبار غير متاحة,0,بيانات الأخبار غير كافية
2,سوق عالمي,نفط برنت,BZ=F,1.403744,صاعد,أخبار غير متاحة,0,بيانات الأخبار غير كافية
3,سوق عالمي,FTSE 100 - بريطانيا,^FTSE,0.987298,صاعد,أخبار غير متاحة,0,بيانات الأخبار غير كافية
4,سوق عالمي,DAX - ألمانيا,^GDAXI,0.758991,صاعد,أخبار غير متاحة,0,بيانات الأخبار غير كافية
5,سوق عالمي,CAC 40 - فرنسا,^FCHI,0.378682,صاعد,أخبار غير متاحة,0,بيانات الأخبار غير كافية
6,سوق عالمي,Dow Jones - أمريكا,^DJI,0.378670,صاعد,أخبار غير متاحة,0,بيانات الأخبار غير كافية
7,سوق عالمي,الدولار مقابل الين,JPY=X,0.373904,صاعد,أخبار غير متاحة,0,بيانات الأخبار غير كافية
8,سوق عالمي,Nikkei 225 - اليابان,^N225,-0.016204,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
9,سوق عالمي,S&P 500 - أمريكا,^GSPC,-0.055044,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
10,سوق عالمي,الفضة,SI=F,-0.313167,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
11,سوق عالمي,Nasdaq Composite - أمريكا,^IXIC,-0.439475,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
12,سوق عالمي,اليورو مقابل الدولار,EURUSD=X,-0.510931,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
13,سوق عالمي,الذهب,GC=F,-0.545502,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
14,سوق عالمي,إيثيريوم,ETH-USD,-0.616608,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
15,سوق عالمي,بيتكوين,BTC-USD,-1.039121,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
16,سوق عالمي,الغاز الطبيعي,NG=F,-1.583855,هابط,أخبار غير متاحة,0,بيانات الأخبار غير كافية
17,سهم أمريكي,إنفيديا,NVDA,NaN,غير واضح,إيجابي,46,الاتجاه الفني غير واضح
18,سهم أمريكي,تسلا,TSLA,NaN,صاعد,إيجابي,20,توافق إيجابي
19,سهم أمريكي,آبل,AAPL,NaN,صاعد,محايد أو مختلط,1,الأخبار مختلطة؛ يلزم تحليل إضافي
20,سهم أمريكي,مايكروسوفت,MSFT,NaN,صاعد,إيجابي,34,توافق إيجابي
21,سهم أمريكي,أمازون,AMZN,NaN,غير واضح,إيجابي,17,الاتجاه الفني غير واضح
22,سهم أمريكي,ألفابت,GOOGL,NaN,صاعد,إيجابي,20,توافق إيجابي
23,سهم أمريكي,ميتا,META,NaN,صاعد,إيجابي,2,توافق إيجابي
24,سهم أمريكي,ناسداك 100,QQQ,NaN,صاعد,إيجابي,5,توافق إيجابي
25,سهم أمريكي,ستاندرد آند بورز 500,SPY,NaN,صاعد,إيجابي,50,توافق إيجابي

✅ انتهت المرحلة 28.
ملاحظة: هذه مؤشرات تحليلية وليست توصيات شراء أو بيع.

In [ ]:
# 🌧️ الودق AI — المرحلة 29
# فحص البيانات قبل إصلاح التقرير الموحد

print("🌧️ فحص بيانات الودق AI")
print("=" * 45)

tables_to_check = [
    "us_technical_df",
    "wadq_global_market_df",
    "wadq_global_alerts_df",
    "wadq_global_master_report_df",
    "wadq_ticker_news_df"
]

for name in tables_to_check:
    if name in globals():
        df = globals()[name]

        print(f"\n✅ الجدول: {name}")
        print("عدد الصفوف:", len(df))
        print("الأعمدة:", df.columns.tolist())

        if "الرمز" in df.columns:
            print("الرموز:", df["الرمز"].astype(str).tolist())

        elif "ticker" in df.columns:
            print("الرموز:", df["ticker"].astype(str).tolist())

        elif "symbol" in df.columns:
            print("الرموز:", df["symbol"].astype(str).tolist())

    else:
        print(f"\n⚠️ الجدول غير موجود: {name}")

print("\n✅ انتهى الفحص دون تعديل أي جدول.")

🌧️ فحص بيانات الودق AI
=============================================

✅ الجدول: us_technical_df
عدد الصفوف: 9
الأعمدة: ['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']
الرموز: ['NVDA', 'TSLA', 'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'QQQ', 'SPY']

✅ الجدول: wadq_global_market_df
عدد الصفوف: 17
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']
الرموز: ['^GSPC', '^IXIC', '^DJI', '^GDAXI', '^FCHI', '^FTSE', '^N225', '^HSI', 'GC=F', 'SI=F', 'CL=F', 'BZ=F', 'NG=F', 'EURUSD=X', 'JPY=X', 'BTC-USD', 'ETH-USD']

✅ الجدول: wadq_global_alerts_df
عدد الصفوف: 17
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'التغير اليومي %', 'تاريخ آخر بيانات', 'حالة الحركة', 'ملاحظة']
الرموز: ['^HSI', 'CL=F', 'BZ=F', '^FTSE', '^GDAXI', '^FCHI', '^DJI', 'JPY=X', '^N225', '^GSPC', 'SI=F', '^IXIC', 'EURUSD=X', 'GC=F', 'ETH-USD', 'BTC-USD', 'NG=F']

✅ الجدول: wadq_global_master_report_df
عدد الصفوف: 26
الأعمدة: ['نوع الأصل', 'الأصل', 'الرمز', 'السعر', 'التغير اليومي %', 'الاتجاه الفني', 'RSI', 'إشارة MACD', 'عدد_الأخبار', 'أخبار_إيجابية', 'أخبار_سلبية', 'أخبار_محايدة', 'أحدث_عنوان_متاح', 'ملاحظة السوق']
الرموز: ['^HSI', 'CL=F', 'BZ=F', '^FTSE', '^GDAXI', '^FCHI', '^DJI', 'JPY=X', '^N225', '^GSPC', 'SI=F', '^IXIC', 'EURUSD=X', 'GC=F', 'ETH-USD', 'BTC-USD', 'NG=F', 'NVDA', 'TSLA', 'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'QQQ', 'SPY']

✅ الجدول: wadq_ticker_news_df
عدد الصفوف: 195
الأعمدة: ['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']
الرموز: ['SPY', 'SPY', 'QQQ', 'SPY', 'QQQ', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'QQQ', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'NVDA', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'QQQ', 'SPY', 'SPY', 'SPY', 'SPY', 'QQQ', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'NVDA', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'SPY', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'NVDA', 'MSFT', 'NVDA', 'MSFT', 'GOOGL', 'NVDA', 'TSLA', 'MSFT', 'GOOGL', 'NVDA', 'MSFT', 'NVDA', 'MSFT', 'GOOGL', 'NVDA', 'MSFT', 'NVDA', 'TSLA', 'NVDA', 'TSLA', 'MSFT', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'MSFT', 'NVDA', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'GOOGL', 'META', 'NVDA', 'MSFT', 'GOOGL', 'NVDA', 'MSFT', 'NVDA', 'MSFT', 'GOOGL', 'NVDA', 'TSLA', 'NVDA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'NVDA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'TSLA', 'AMZN', 'NVDA', 'TSLA', 'MSFT', 'NVDA', 'TSLA', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'GOOGL', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'TSLA', 'NVDA', 'MSFT', 'GOOGL', 'NVDA', 'NVDA', 'MSFT', 'GOOGL', 'NVDA', 'SPY', 'NVDA', 'MSFT', 'MSFT', 'NVDA', 'MSFT', 'AMZN', 'AAPL', 'AMZN', 'NVDA', 'TSLA', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'NVDA', 'MSFT', 'NVDA', 'TSLA', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'MSFT', 'AMZN', 'GOOGL', 'META', 'NVDA', 'MSFT', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'TSLA', 'MSFT', 'AMZN', 'GOOGL', 'NVDA', 'TSLA', 'MSFT']

✅ انتهى الفحص دون تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — المرحلة 29
# فحص أسباب نقص البيانات الفنية في التقرير الموحد

print("🌧️ فحص البيانات الفنية")
print("=" * 50)

if "us_technical_df" in globals():
    print("\n1️⃣ بيانات التحليل الفني للأسهم الأمريكية:")
    print("الأعمدة:")
    print(us_technical_df.columns.tolist())
    display(us_technical_df.head(3))
else:
    print("⚠️ جدول us_technical_df غير موجود")

if "wadq_global_master_report_df" in globals():
    print("\n2️⃣ بيانات التقرير العالمي الموحد:")
    print("الأعمدة:")
    print(wadq_global_master_report_df.columns.tolist())
    display(wadq_global_master_report_df.head(5))
else:
    print("⚠️ التقرير العالمي الموحد غير موجود")

print("\n✅ انتهى الفحص دون تعديل أي جدول.")

🌧️ فحص البيانات الفنية
==================================================

1️⃣ بيانات التحليل الفني للأسهم الأمريكية:
الأعمدة:
['السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

,السهم,الرمز,آخر إغلاق,المتوسط 20,المتوسط 50,RSI,حالة RSI,MACD,إشارة MACD,الاتجاه
0,إنفيديا,NVDA,226.32,227.50,222.46,49.42,ضمن النطاق المتوسط,3.3139,3.7581,مختلط
1,تسلا,TSLA,378.03,369.61,356.08,56.46,ضمن النطاق المتوسط,5.1446,4.2311,صاعد
2,آبل,AAPL,340.97,335.78,323.00,60.22,ضمن النطاق المتوسط,3.6456,3.8354,صاعد

2️⃣ بيانات التقرير العالمي الموحد:
الأعمدة:
['نوع الأصل', 'الأصل', 'الرمز', 'السعر', 'التغير اليومي %', 'الاتجاه الفني', 'RSI', 'إشارة MACD', 'عدد_الأخبار', 'أخبار_إيجابية', 'أخبار_سلبية', 'أخبار_محايدة', 'أحدث_عنوان_متاح', 'ملاحظة السوق']

,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق
0,سوق عالمي,Hang Seng - هونغ كونغ,^HSI,24211.349609,1.789138,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
1,سوق عالمي,النفط الأمريكي,CL=F,93.309998,1.589547,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
2,سوق عالمي,نفط برنت,BZ=F,106.190002,1.403744,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
3,سوق عالمي,FTSE 100 - بريطانيا,^FTSE,10656.280273,0.987298,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول
4,سوق عالمي,DAX - ألمانيا,^GDAXI,25277.679688,0.758991,ارتفاع محدود,NaN,غير متاح,0,0,0,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول

✅ انتهى الفحص دون تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — المرحلة 30
# ربط التحليل الفني الأمريكي بالتقرير العالمي
# دون تعديل الجداول الأصلية

import pandas as pd

print("🌧️ بدء ربط البيانات الفنية بالتقرير العالمي")
print("=" * 55)

# التأكد من وجود الجدولين
if (
    "us_technical_df" in globals()
    and "wadq_global_master_report_df" in globals()
):
    # إنشاء نسخة جديدة من التقرير
    wadq_global_master_report_v2_df = (
        wadq_global_master_report_df.copy()
    )

    # إنشاء نسخة من التحليل الفني
    us_tech = us_technical_df.copy()

    # توحيد الرموز
    us_tech["الرمز"] = (
        us_tech["الرمز"].astype(str).str.strip()
    )

    wadq_global_master_report_v2_df["الرمز"] = (
        wadq_global_master_report_v2_df["الرمز"]
        .astype(str)
        .str.strip()
    )

    # الأعمدة الفنية المطلوب ربطها
    technical_columns = [
        "الاتجاه",
        "MACD إشارة",
        "MACD",
        "حالة RSI",
        "RSI",
        "المتوسط 50",
        "المتوسط 20",
        "آخر إغلاق",
    ]

    # الاحتفاظ بالأعمدة الموجودة فعلًا
    available_columns = [
        col for col in technical_columns
        if col in us_tech.columns
    ]

    # إنشاء جدول فني بمفتاح الرمز
    us_tech_lookup = (
        us_tech[["الرمز"] + available_columns]
        .drop_duplicates(subset=["الرمز"], keep="last")
        .set_index("الرمز")
    )

    # ربط القيم الفنية بالأسهم المطابقة
    for col in available_columns:
        if col not in wadq_global_master_report_v2_df.columns:
            wadq_global_master_report_v2_df[col] = None

        mapped_values = (
            wadq_global_master_report_v2_df["الرمز"]
            .map(us_tech_lookup[col])
        )

        mask = mapped_values.notna()

        wadq_global_master_report_v2_df.loc[
            mask, col
        ] = mapped_values.loc[mask]

    print("✅ اكتمل الربط.")
    print(
        "عدد الأصول في التقرير:",
        len(wadq_global_master_report_v2_df)
    )

    # عرض الأسهم الأمريكية بعد الربط
    us_symbols = us_tech["الرمز"].unique()

    result = wadq_global_master_report_v2_df[
        wadq_global_master_report_v2_df["الرمز"].isin(us_symbols)
    ]

    print("\n📊 نتيجة الربط للأسهم الأمريكية:")
    display(result)

    print(
        "\n✅ حُفظت النتيجة في جدول جديد:",
        "wadq_global_master_report_v2_df"
    )

else:
    print("⚠️ أحد الجدولين غير موجود في الجلسة الحالية.")

🌧️ بدء ربط البيانات الفنية بالتقرير العالمي
=======================================================
✅ اكتمل الربط.
عدد الأصول في التقرير: 26

📊 نتيجة الربط للأسهم الأمريكية:

,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق,الاتجاه,MACD,حالة RSI,المتوسط 50,المتوسط 20,آخر إغلاق
17,سهم أمريكي,إنفيديا,NVDA,226.32,NaN,مختلط,49.42,3.7581,46,9,1,36,Wall Street stocks end tad lower after hot inf...,,مختلط,3.3139,ضمن النطاق المتوسط,222.46,227.5,226.32
18,سهم أمريكي,تسلا,TSLA,378.03,NaN,صاعد,56.46,4.2311,20,2,0,18,Zacks Investment Ideas feature highlights: App...,,صاعد,5.1446,ضمن النطاق المتوسط,356.08,369.61,378.03
19,سهم أمريكي,آبل,AAPL,340.97,NaN,صاعد,60.22,3.8354,1,0,0,1,"Are Amazon, Apple stocks overpriced? Here are ...",,صاعد,3.6456,ضمن النطاق المتوسط,323.0,335.78,340.97
20,سهم أمريكي,مايكروسوفت,MSFT,541.15,NaN,صاعد,69.92,9.687,34,7,1,26,Zacks Investment Ideas feature highlights: App...,,صاعد,11.6192,ضمن النطاق المتوسط,501.73,511.89,541.15
21,سهم أمريكي,أمازون,AMZN,259.53,NaN,مختلط,55.59,-0.6976,17,4,0,13,Zacks Investment Ideas feature highlights: App...,,مختلط,0.757,ضمن النطاق المتوسط,258.85,252.32,259.53
22,سهم أمريكي,ألفابت,GOOGL,352.72,NaN,صاعد,57.30,0.63,20,5,0,15,"Prediction: Nvidia Will Overtake Alphabet, App...",,صاعد,1.6851,ضمن النطاق المتوسط,346.08,346.09,352.72
23,سهم أمريكي,ميتا,META,742.96,NaN,صاعد,62.32,29.7186,2,1,0,1,I Predicted That Oracle and Netflix Would Join...,,صاعد,24.8981,ضمن النطاق المتوسط,643.13,722.94,742.96
24,سهم أمريكي,ناسداك 100,QQQ,746.04,NaN,صاعد,56.72,8.9299,5,2,0,3,"Stock Market Today: S&P 500, Dow Futures Gain,...",,صاعد,9.0018,ضمن النطاق المتوسط,725.18,739.24,746.04
25,سهم أمريكي,ستاندرد آند بورز 500,SPY,778.07,NaN,صاعد,59.89,2.8224,50,15,8,27,"Stock Market Today: Dow gains but S&P 500, Nas...",,صاعد,3.8745,ضمن النطاق المتوسط,766.94,768.55,778.07

✅ حُفظت النتيجة في جدول جديد: wadq_global_master_report_v2_df

In [ ]:
# 🌧️ الودق AI — المرحلة 31
# استكمال التغير اليومي للأسهم الأمريكية
# مع الحفاظ على التقرير الأصلي

import yfinance as yf
import pandas as pd

print("🌧️ بدء فحص التغير اليومي للأسهم الأمريكية")
print("=" * 50)

if "wadq_global_master_report_v2_df" not in globals():
    print("⚠️ التقرير الموحد الجديد غير موجود.")

else:
    # إنشاء نسخة مستقلة للحفاظ على التقرير السابق
    wadq_global_master_report_v3_df = (
        wadq_global_master_report_v2_df.copy()
    )

    # الأسهم الأمريكية التسعة
    us_symbols = [
        "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
        "GOOGL", "META", "QQQ", "SPY"
    ]

    daily_changes = {}

    for ticker in us_symbols:
        try:
            hist = yf.Ticker(ticker).history(
                period="5d",
                interval="1d",
                auto_adjust=False
            )

            closes = hist["Close"].dropna()

            if len(closes) >= 2:
                change = (
                    (closes.iloc[-1] / closes.iloc[-2]) - 1
                ) * 100

                daily_changes[ticker] = round(
                    float(change), 3
                )

                print(
                    f"✅ {ticker}: "
                    f"{daily_changes[ticker]}%"
                )

            else:
                print(
                    f"⚠️ {ticker}: "
                    "لا توجد بيانات كافية لحساب التغير."
                )

        except Exception as e:
            print(f"⚠️ {ticker}: تعذر جلب البيانات.")

    # تحديد عمود الرمز وعمود التغير اليومي
    report = wadq_global_master_report_v3_df

    if "الرمز" in report.columns:
        symbol_col = "الرمز"
    elif "ticker" in report.columns:
        symbol_col = "ticker"
    else:
        symbol_col = None

    change_col = next(
        (
            col for col in [
                "التغير اليومي %",
                "التغير اليومي",
                "التغير اليومي %"
            ]
            if col in report.columns
        ),
        None
    )

    if symbol_col is not None and change_col is not None:
        mask = report[symbol_col].isin(daily_changes)

        for ticker, change in daily_changes.items():
            report.loc[
                report[symbol_col] == ticker,
                change_col
            ] = change

        print("\n✅ تم تحديث التغير اليومي في النسخة الجديدة.")
        print("عدد الأسهم التي جرى حساب تغيرها:", len(daily_changes))

        display(
            report.loc[
                report[symbol_col].isin(us_symbols)
            ]
        )

    else:
        print("⚠️ تعذر تحديد عمود الرمز أو التغير اليومي.")
        print("أعمدة التقرير:", report.columns.tolist())

    print("\n🌧️ اسم التقرير الجديد:")
    print("wadq_global_master_report_v3_df")

🌧️ بدء فحص التغير اليومي للأسهم الأمريكية
==================================================
✅ NVDA: -1.291%
✅ TSLA: -1.22%
✅ AAPL: 1.286%
✅ MSFT: 1.136%
✅ AMZN: -1.105%
✅ GOOGL: 0.301%
✅ META: 3.38%
✅ QQQ: -0.696%
✅ SPY: -0.06%

✅ تم تحديث التغير اليومي في النسخة الجديدة.
عدد الأسهم التي جرى حساب تغيرها: 9

,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق,الاتجاه,MACD,حالة RSI,المتوسط 50,المتوسط 20,آخر إغلاق
17,سهم أمريكي,إنفيديا,NVDA,226.32,-1.291,مختلط,49.42,3.7581,46,9,1,36,Wall Street stocks end tad lower after hot inf...,,مختلط,3.3139,ضمن النطاق المتوسط,222.46,227.5,226.32
18,سهم أمريكي,تسلا,TSLA,378.03,-1.220,صاعد,56.46,4.2311,20,2,0,18,Zacks Investment Ideas feature highlights: App...,,صاعد,5.1446,ضمن النطاق المتوسط,356.08,369.61,378.03
19,سهم أمريكي,آبل,AAPL,340.97,1.286,صاعد,60.22,3.8354,1,0,0,1,"Are Amazon, Apple stocks overpriced? Here are ...",,صاعد,3.6456,ضمن النطاق المتوسط,323.0,335.78,340.97
20,سهم أمريكي,مايكروسوفت,MSFT,541.15,1.136,صاعد,69.92,9.687,34,7,1,26,Zacks Investment Ideas feature highlights: App...,,صاعد,11.6192,ضمن النطاق المتوسط,501.73,511.89,541.15
21,سهم أمريكي,أمازون,AMZN,259.53,-1.105,مختلط,55.59,-0.6976,17,4,0,13,Zacks Investment Ideas feature highlights: App...,,مختلط,0.757,ضمن النطاق المتوسط,258.85,252.32,259.53
22,سهم أمريكي,ألفابت,GOOGL,352.72,0.301,صاعد,57.30,0.63,20,5,0,15,"Prediction: Nvidia Will Overtake Alphabet, App...",,صاعد,1.6851,ضمن النطاق المتوسط,346.08,346.09,352.72
23,سهم أمريكي,ميتا,META,742.96,3.380,صاعد,62.32,29.7186,2,1,0,1,I Predicted That Oracle and Netflix Would Join...,,صاعد,24.8981,ضمن النطاق المتوسط,643.13,722.94,742.96
24,سهم أمريكي,ناسداك 100,QQQ,746.04,-0.696,صاعد,56.72,8.9299,5,2,0,3,"Stock Market Today: S&P 500, Dow Futures Gain,...",,صاعد,9.0018,ضمن النطاق المتوسط,725.18,739.24,746.04
25,سهم أمريكي,ستاندرد آند بورز 500,SPY,778.07,-0.060,صاعد,59.89,2.8224,50,15,8,27,"Stock Market Today: Dow gains but S&P 500, Nas...",,صاعد,3.8745,ضمن النطاق المتوسط,766.94,768.55,778.07

🌧️ اسم التقرير الجديد:
wadq_global_master_report_v3_df

In [ ]:
# 🌧️ الودق AI — المرحلة 32
# إنشاء نظام تقييم وترتيب الأسهم الأمريكية
# مع الحفاظ على التقارير السابقة

import pandas as pd

print("🌧️ بدء المرحلة 32: تقييم الأسهم الأمريكية")
print("=" * 50)

# التحقق من وجود التقرير الجديد
if "wadq_global_master_report_v3_df" not in globals():

    print("⚠️ التقرير المطلوب غير موجود.")
    print("يرجى التأكد من تشغيل المرحلة 31 أولاً.")

else:

    # إنشاء نسخة مستقلة لحماية التقرير الأصلي
    wadq_us_ranking_df = wadq_global_master_report_v3_df.copy()

    # البحث عن عمود رمز السهم
    symbol_col = next(
        (
            col for col in ["الرمز", "ticker"]
            if col in wadq_us_ranking_df.columns
        ),
        None
    )

    # البحث عن عمود التغير اليومي
    change_col = next(
        (
            col for col in [
                "التغير اليومي %",
                "التغير اليومي",
                "التغير اليومي % "
            ]
            if col in wadq_us_ranking_df.columns
        ),
        None
    )

    if symbol_col is None or change_col is None:

        print("⚠️ لم يتم العثور على أعمدة الرمز والتغير اليومي.")
        print("الأعمدة الموجودة:")
        print(wadq_us_ranking_df.columns.tolist())

    else:

        # تحويل التغير اليومي إلى أرقام
        wadq_us_ranking_df[change_col] = pd.to_numeric(
            wadq_us_ranking_df[change_col],
            errors="coerce"
        )

        # إنشاء تصنيف أولي لحركة السهم
        wadq_us_ranking_df["تقييم الحركة"] = (
            wadq_us_ranking_df[change_col].apply(
                lambda x:
                    "إيجابي" if pd.notna(x) and x > 0
                    else "سلبي" if pd.notna(x) and x < 0
                    else "محايد" if pd.notna(x)
                    else "بيانات غير متاحة"
            )
        )

        # ترتيب الأصول حسب التغير اليومي
        wadq_us_ranking_df = wadq_us_ranking_df.sort_values(
            by=change_col,
            ascending=False,
            na_position="last"
        ).reset_index(drop=True)

        # إضافة ترتيب مستقل
        wadq_us_ranking_df.insert(
            0,
            "الترتيب حسب التغير اليومي",
            range(1, len(wadq_us_ranking_df) + 1)
        )

        print("✅ تم إنشاء جدول تقييم الأسهم.")
        print("عدد الأصول:", len(wadq_us_ranking_df))
        print("\n📊 معاينة النتائج:")

        display(wadq_us_ranking_df)

        print("\n🌧️ اسم الجدول الجديد:")
        print("wadq_us_ranking_df")

🌧️ بدء المرحلة 32: تقييم الأسهم الأمريكية
==================================================
✅ تم إنشاء جدول تقييم الأسهم.
عدد الأصول: 26

📊 معاينة النتائج:

,الترتيب حسب التغير اليومي,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,...,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق,الاتجاه,MACD,حالة RSI,المتوسط 50,المتوسط 20,آخر إغلاق,تقييم الحركة
0,1,سهم أمريكي,ميتا,META,742.960000,3.380000,صاعد,62.32,29.7186,2,...,1,I Predicted That Oracle and Netflix Would Join...,,صاعد,24.8981,ضمن النطاق المتوسط,643.13,722.94,742.96,إيجابي
1,2,سوق عالمي,Hang Seng - هونغ كونغ,^HSI,24211.349609,1.789138,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
2,3,سوق عالمي,النفط الأمريكي,CL=F,93.309998,1.589547,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
3,4,سوق عالمي,نفط برنت,BZ=F,106.190002,1.403744,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
4,5,سهم أمريكي,آبل,AAPL,340.970000,1.286000,صاعد,60.22,3.8354,1,...,1,"Are Amazon, Apple stocks overpriced? Here are ...",,صاعد,3.6456,ضمن النطاق المتوسط,323.0,335.78,340.97,إيجابي
5,6,سهم أمريكي,مايكروسوفت,MSFT,541.150000,1.136000,صاعد,69.92,9.687,34,...,26,Zacks Investment Ideas feature highlights: App...,,صاعد,11.6192,ضمن النطاق المتوسط,501.73,511.89,541.15,إيجابي
6,7,سوق عالمي,FTSE 100 - بريطانيا,^FTSE,10656.280273,0.987298,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
7,8,سوق عالمي,DAX - ألمانيا,^GDAXI,25277.679688,0.758991,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
8,9,سوق عالمي,CAC 40 - فرنسا,^FCHI,7832.879883,0.378682,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
9,10,سوق عالمي,Dow Jones - أمريكا,^DJI,51850.550781,0.378670,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
10,11,سوق عالمي,الدولار مقابل الين,JPY=X,158.654007,0.373904,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
11,12,سهم أمريكي,ألفابت,GOOGL,352.720000,0.301000,صاعد,57.30,0.63,20,...,15,"Prediction: Nvidia Will Overtake Alphabet, App...",,صاعد,1.6851,ضمن النطاق المتوسط,346.08,346.09,352.72,إيجابي
12,13,سوق عالمي,Nikkei 225 - اليابان,^N225,69030.921875,-0.016204,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي
13,14,سوق عالمي,S&P 500 - أمريكا,^GSPC,7807.240234,-0.055044,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي
14,15,سهم أمريكي,ستاندرد آند بورز 500,SPY,778.070000,-0.060000,صاعد,59.89,2.8224,50,...,27,"Stock Market Today: Dow gains but S&P 500, Nas...",,صاعد,3.8745,ضمن النطاق المتوسط,766.94,768.55,778.07,سلبي
15,16,سوق عالمي,الفضة,SI=F,60.480000,-0.313167,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي
16,17,سوق عالمي,Nasdaq Composite - أمريكا,^IXIC,27245.902344,-0.439475,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي
17,18,سوق عالمي,اليورو مقابل الدولار,EURUSD=X,1.115573,-0.510931,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي
18,19,سوق عالمي,الذهب,GC=F,4193.299805,-0.545502,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي
19,20,سوق عالمي,إيثيريوم,ETH-USD,2519.070068,-0.616608,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي
20,21,سهم أمريكي,ناسداك 100,QQQ,746.040000,-0.696000,صاعد,56.72,8.9299,5,...,3,"Stock Market Today: S&P 500, Dow Futures Gain,...",,صاعد,9.0018,ضمن النطاق المتوسط,725.18,739.24,746.04,سلبي
21,22,سوق عالمي,بيتكوين,BTC-USD,82809.937500,-1.039121,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي
22,23,سهم أمريكي,أمازون,AMZN,259.530000,-1.105000,مختلط,55.59,-0.6976,17,...,13,Zacks Investment Ideas feature highlights: App...,,مختلط,0.757,ضمن النطاق المتوسط,258.85,252.32,259.53,سلبي
23,24,سهم أمريكي,تسلا,TSLA,378.030000,-1.220000,صاعد,56.46,4.2311,20,...,18,Zacks Investment Ideas feature highlights: App...,,صاعد,5.1446,ضمن النطاق المتوسط,356.08,369.61,378.03,سلبي
24,25,سهم أمريكي,إنفيديا,NVDA,226.320000,-1.291000,مختلط,49.42,3.7581,46,...,36,Wall Street stocks end tad lower after hot inf...,,مختلط,3.3139,ضمن النطاق المتوسط,222.46,227.5,226.32,سلبي
25,26,سوق عالمي,الغاز الطبيعي,NG=F,3.169000,-1.583855,انخفاض محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,سلبي

🌧️ اسم الجدول الجديد:
wadq_us_ranking_df

In [ ]:
# 🌧️ الودق AI — فحص نتائج المرحلة 32

print("🌧️ فحص جدول تقييم الأسهم")
print("=" * 45)

if "wadq_us_ranking_df" in globals():

    print("✅ الجدول موجود")
    print("عدد الصفوف:", len(wadq_us_ranking_df))
    print("عدد الأعمدة:", len(wadq_us_ranking_df.columns))

    print("\nالأعمدة الموجودة:")
    print(wadq_us_ranking_df.columns.tolist())

    print("\nعدد القيم المفقودة في كل عمود:")
    display(wadq_us_ranking_df.isna().sum().to_frame("عدد القيم المفقودة"))

    print("\nمعاينة أول 10 صفوف:")
    display(wadq_us_ranking_df.head(10))

else:
    print("⚠️ جدول تقييم الأسهم غير موجود.")

🌧️ فحص جدول تقييم الأسهم
=============================================
✅ الجدول موجود
عدد الصفوف: 26
عدد الأعمدة: 22

الأعمدة الموجودة:
['الترتيب حسب التغير اليومي', 'نوع الأصل', 'الأصل', 'الرمز', 'السعر', 'التغير اليومي %', 'الاتجاه الفني', 'RSI', 'إشارة MACD', 'عدد_الأخبار', 'أخبار_إيجابية', 'أخبار_سلبية', 'أخبار_محايدة', 'أحدث_عنوان_متاح', 'ملاحظة السوق', 'الاتجاه', 'MACD', 'حالة RSI', 'المتوسط 50', 'المتوسط 20', 'آخر إغلاق', 'تقييم الحركة']

عدد القيم المفقودة في كل عمود:

                           عدد القيم المفقودة
الترتيب حسب التغير اليومي                   0
نوع الأصل                                   0
الأصل                                       0
الرمز                                       0
السعر                                       0
التغير اليومي %                             0
الاتجاه الفني                               0
RSI                                        17
إشارة MACD                                  0
عدد_الأخبار                                 0
أخبار_إيجابية                               0
أخبار_سلبية                                 0
أخبار_محايدة                                0
أحدث_عنوان_متاح                            17
ملاحظة السوق                                0
الاتجاه                                    17
MACD                                       17
حالة RSI                                   17
المتوسط 50                                 17
المتوسط 20                                 17
آخر إغلاق                                  17
تقييم الحركة                                0

معاينة أول 10 صفوف:

,الترتيب حسب التغير اليومي,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,...,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق,الاتجاه,MACD,حالة RSI,المتوسط 50,المتوسط 20,آخر إغلاق,تقييم الحركة
0,1,سهم أمريكي,ميتا,META,742.960000,3.380000,صاعد,62.32,29.7186,2,...,1,I Predicted That Oracle and Netflix Would Join...,,صاعد,24.8981,ضمن النطاق المتوسط,643.13,722.94,742.96,إيجابي
1,2,سوق عالمي,Hang Seng - هونغ كونغ,^HSI,24211.349609,1.789138,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
2,3,سوق عالمي,النفط الأمريكي,CL=F,93.309998,1.589547,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
3,4,سوق عالمي,نفط برنت,BZ=F,106.190002,1.403744,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
4,5,سهم أمريكي,آبل,AAPL,340.970000,1.286000,صاعد,60.22,3.8354,1,...,1,"Are Amazon, Apple stocks overpriced? Here are ...",,صاعد,3.6456,ضمن النطاق المتوسط,323.0,335.78,340.97,إيجابي
5,6,سهم أمريكي,مايكروسوفت,MSFT,541.150000,1.136000,صاعد,69.92,9.687,34,...,26,Zacks Investment Ideas feature highlights: App...,,صاعد,11.6192,ضمن النطاق المتوسط,501.73,511.89,541.15,إيجابي
6,7,سوق عالمي,FTSE 100 - بريطانيا,^FTSE,10656.280273,0.987298,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
7,8,سوق عالمي,DAX - ألمانيا,^GDAXI,25277.679688,0.758991,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
8,9,سوق عالمي,CAC 40 - فرنسا,^FCHI,7832.879883,0.378682,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي
9,10,سوق عالمي,Dow Jones - أمريكا,^DJI,51850.550781,0.378670,ارتفاع محدود,NaN,غير متاح,0,...,0,NaN,تنبيه مبني على تغير السعر فقط، وليس توصية تداول,None,None,None,None,None,None,إيجابي

In [ ]:
# 🌧️ الودق AI — المرحلة 32
# فحص الأسهم الأمريكية التسعة

us_symbols = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY"
]

print("🌧️ فحص الأسهم الأمريكية")
print("=" * 45)

if "wadq_us_ranking_df" in globals():

    df = wadq_us_ranking_df

    symbol_col = next(
        (c for c in ["الرمز", "ticker"] if c in df.columns),
        None
    )

    if symbol_col is None:
        print("⚠️ لم يتم العثور على عمود رمز السهم.")
        print("الأعمدة:", df.columns.tolist())

    else:
        us_df = df[df[symbol_col].astype(str).isin(us_symbols)]

        print("عدد الأسهم الأمريكية الموجودة:", len(us_df))
        print("\nالأسهم التي عثرنا عليها:")

        display(us_df)

        missing = [
            s for s in us_symbols
            if s not in us_df[symbol_col].astype(str).tolist()
        ]

        print("\nالأسهم غير الموجودة:", missing)

else:
    print("⚠️ جدول التقييم غير موجود.")

🌧️ فحص الأسهم الأمريكية
=============================================
عدد الأسهم الأمريكية الموجودة: 9

الأسهم التي عثرنا عليها:

,الترتيب حسب التغير اليومي,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,...,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق,الاتجاه,MACD,حالة RSI,المتوسط 50,المتوسط 20,آخر إغلاق,تقييم الحركة
0,1,سهم أمريكي,ميتا,META,742.96,3.380,صاعد,62.32,29.7186,2,...,1,I Predicted That Oracle and Netflix Would Join...,,صاعد,24.8981,ضمن النطاق المتوسط,643.13,722.94,742.96,إيجابي
4,5,سهم أمريكي,آبل,AAPL,340.97,1.286,صاعد,60.22,3.8354,1,...,1,"Are Amazon, Apple stocks overpriced? Here are ...",,صاعد,3.6456,ضمن النطاق المتوسط,323.0,335.78,340.97,إيجابي
5,6,سهم أمريكي,مايكروسوفت,MSFT,541.15,1.136,صاعد,69.92,9.687,34,...,26,Zacks Investment Ideas feature highlights: App...,,صاعد,11.6192,ضمن النطاق المتوسط,501.73,511.89,541.15,إيجابي
11,12,سهم أمريكي,ألفابت,GOOGL,352.72,0.301,صاعد,57.30,0.63,20,...,15,"Prediction: Nvidia Will Overtake Alphabet, App...",,صاعد,1.6851,ضمن النطاق المتوسط,346.08,346.09,352.72,إيجابي
14,15,سهم أمريكي,ستاندرد آند بورز 500,SPY,778.07,-0.060,صاعد,59.89,2.8224,50,...,27,"Stock Market Today: Dow gains but S&P 500, Nas...",,صاعد,3.8745,ضمن النطاق المتوسط,766.94,768.55,778.07,سلبي
20,21,سهم أمريكي,ناسداك 100,QQQ,746.04,-0.696,صاعد,56.72,8.9299,5,...,3,"Stock Market Today: S&P 500, Dow Futures Gain,...",,صاعد,9.0018,ضمن النطاق المتوسط,725.18,739.24,746.04,سلبي
22,23,سهم أمريكي,أمازون,AMZN,259.53,-1.105,مختلط,55.59,-0.6976,17,...,13,Zacks Investment Ideas feature highlights: App...,,مختلط,0.757,ضمن النطاق المتوسط,258.85,252.32,259.53,سلبي
23,24,سهم أمريكي,تسلا,TSLA,378.03,-1.220,صاعد,56.46,4.2311,20,...,18,Zacks Investment Ideas feature highlights: App...,,صاعد,5.1446,ضمن النطاق المتوسط,356.08,369.61,378.03,سلبي
24,25,سهم أمريكي,إنفيديا,NVDA,226.32,-1.291,مختلط,49.42,3.7581,46,...,36,Wall Street stocks end tad lower after hot inf...,,مختلط,3.3139,ضمن النطاق المتوسط,222.46,227.5,226.32,سلبي

الأسهم غير الموجودة: []

In [ ]:
# 🌧️ الودق AI — المرحلة 32
# ملخص مستقل للأسهم الأمريكية التسعة

import pandas as pd

us_symbols = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY"
]

source_df = wadq_global_master_report_v3_df.copy()

symbol_col = next(
    (c for c in ["الرمز", "ticker"] if c in source_df.columns),
    None
)

change_col = next(
    (
        c for c in [
            "التغير اليومي %",
            "التغير اليومي",
            "التغير اليومي % "
        ]
        if c in source_df.columns
    ),
    None
)

if symbol_col is None or change_col is None:

    print("⚠️ تعذر العثور على عمود الرمز أو التغير اليومي.")
    print("الأعمدة المتاحة:")
    print(source_df.columns.tolist())

else:

    wadq_us_summary_df = source_df[
        source_df[symbol_col].astype(str).isin(us_symbols)
    ].copy()

    wadq_us_summary_df[change_col] = pd.to_numeric(
        wadq_us_summary_df[change_col],
        errors="coerce"
    )

    wadq_us_summary_df = wadq_us_summary_df.sort_values(
        change_col,
        ascending=False,
        na_position="last"
    ).reset_index(drop=True)

    wadq_us_summary_df.insert(
        0,
        "ترتيب التغير اليومي",
        range(1, len(wadq_us_summary_df) + 1)
    )

    wadq_us_summary_df["اتجاه الحركة"] = (
        wadq_us_summary_df[change_col].apply(
            lambda x:
                "إيجابي" if pd.notna(x) and x > 0
                else "سلبي" if pd.notna(x) and x < 0
                else "محايد" if pd.notna(x)
                else "غير متاح"
        )
    )

    print("🌧️ ملخص الأسهم الأمريكية")
    print("=" * 45)
    print("عدد الأصول الموجودة:", len(wadq_us_summary_df))

    display(wadq_us_summary_df)

    print("\n✅ اسم الجدول الجديد:")
    print("wadq_us_summary_df")

🌧️ ملخص الأسهم الأمريكية
=============================================
عدد الأصول الموجودة: 9

,ترتيب التغير اليومي,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,...,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق,الاتجاه,MACD,حالة RSI,المتوسط 50,المتوسط 20,آخر إغلاق,اتجاه الحركة
0,1,سهم أمريكي,ميتا,META,742.96,3.380,صاعد,62.32,29.7186,2,...,1,I Predicted That Oracle and Netflix Would Join...,,صاعد,24.8981,ضمن النطاق المتوسط,643.13,722.94,742.96,إيجابي
1,2,سهم أمريكي,آبل,AAPL,340.97,1.286,صاعد,60.22,3.8354,1,...,1,"Are Amazon, Apple stocks overpriced? Here are ...",,صاعد,3.6456,ضمن النطاق المتوسط,323.0,335.78,340.97,إيجابي
2,3,سهم أمريكي,مايكروسوفت,MSFT,541.15,1.136,صاعد,69.92,9.687,34,...,26,Zacks Investment Ideas feature highlights: App...,,صاعد,11.6192,ضمن النطاق المتوسط,501.73,511.89,541.15,إيجابي
3,4,سهم أمريكي,ألفابت,GOOGL,352.72,0.301,صاعد,57.30,0.63,20,...,15,"Prediction: Nvidia Will Overtake Alphabet, App...",,صاعد,1.6851,ضمن النطاق المتوسط,346.08,346.09,352.72,إيجابي
4,5,سهم أمريكي,ستاندرد آند بورز 500,SPY,778.07,-0.060,صاعد,59.89,2.8224,50,...,27,"Stock Market Today: Dow gains but S&P 500, Nas...",,صاعد,3.8745,ضمن النطاق المتوسط,766.94,768.55,778.07,سلبي
5,6,سهم أمريكي,ناسداك 100,QQQ,746.04,-0.696,صاعد,56.72,8.9299,5,...,3,"Stock Market Today: S&P 500, Dow Futures Gain,...",,صاعد,9.0018,ضمن النطاق المتوسط,725.18,739.24,746.04,سلبي
6,7,سهم أمريكي,أمازون,AMZN,259.53,-1.105,مختلط,55.59,-0.6976,17,...,13,Zacks Investment Ideas feature highlights: App...,,مختلط,0.757,ضمن النطاق المتوسط,258.85,252.32,259.53,سلبي
7,8,سهم أمريكي,تسلا,TSLA,378.03,-1.220,صاعد,56.46,4.2311,20,...,18,Zacks Investment Ideas feature highlights: App...,,صاعد,5.1446,ضمن النطاق المتوسط,356.08,369.61,378.03,سلبي
8,9,سهم أمريكي,إنفيديا,NVDA,226.32,-1.291,مختلط,49.42,3.7581,46,...,36,Wall Street stocks end tad lower after hot inf...,,مختلط,3.3139,ضمن النطاق المتوسط,222.46,227.5,226.32,سلبي

✅ اسم الجدول الجديد:
wadq_us_summary_df

In [ ]:
# 🌧️ الودق AI — المرحلة 32
# ملخص مستقل للأسهم الأمريكية التسعة

import pandas as pd

us_symbols = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY"
]

source_df = wadq_global_master_report_v3_df.copy()

symbol_col = next(
    (c for c in ["الرمز", "ticker"] if c in source_df.columns),
    None
)

change_col = next(
    (
        c for c in [
            "التغير اليومي %",
            "التغير اليومي",
            "التغير اليومي % "
        ]
        if c in source_df.columns
    ),
    None
)

if symbol_col is None or change_col is None:

    print("⚠️ تعذر العثور على عمود الرمز أو التغير اليومي.")
    print("الأعمدة المتاحة:")
    print(source_df.columns.tolist())

else:

    wadq_us_summary_df = source_df[
        source_df[symbol_col].astype(str).isin(us_symbols)
    ].copy()

    wadq_us_summary_df[change_col] = pd.to_numeric(
        wadq_us_summary_df[change_col],
        errors="coerce"
    )

    wadq_us_summary_df = wadq_us_summary_df.sort_values(
        change_col,
        ascending=False,
        na_position="last"
    ).reset_index(drop=True)

    wadq_us_summary_df.insert(
        0,
        "ترتيب التغير اليومي",
        range(1, len(wadq_us_summary_df) + 1)
    )

    wadq_us_summary_df["اتجاه الحركة"] = (
        wadq_us_summary_df[change_col].apply(
            lambda x:
                "إيجابي" if pd.notna(x) and x > 0
                else "سلبي" if pd.notna(x) and x < 0
                else "محايد" if pd.notna(x)
                else "غير متاح"
        )
    )

    print("🌧️ ملخص الأسهم الأمريكية")
    print("=" * 45)
    print("عدد الأصول الموجودة:", len(wadq_us_summary_df))

    display(wadq_us_summary_df)

    print("\n✅ اسم الجدول الجديد:")
    print("wadq_us_summary_df")

🌧️ ملخص الأسهم الأمريكية
=============================================
عدد الأصول الموجودة: 9

,ترتيب التغير اليومي,نوع الأصل,الأصل,الرمز,السعر,التغير اليومي %,الاتجاه الفني,RSI,إشارة MACD,عدد_الأخبار,...,أخبار_محايدة,أحدث_عنوان_متاح,ملاحظة السوق,الاتجاه,MACD,حالة RSI,المتوسط 50,المتوسط 20,آخر إغلاق,اتجاه الحركة
0,1,سهم أمريكي,ميتا,META,742.96,3.380,صاعد,62.32,29.7186,2,...,1,I Predicted That Oracle and Netflix Would Join...,,صاعد,24.8981,ضمن النطاق المتوسط,643.13,722.94,742.96,إيجابي
1,2,سهم أمريكي,آبل,AAPL,340.97,1.286,صاعد,60.22,3.8354,1,...,1,"Are Amazon, Apple stocks overpriced? Here are ...",,صاعد,3.6456,ضمن النطاق المتوسط,323.0,335.78,340.97,إيجابي
2,3,سهم أمريكي,مايكروسوفت,MSFT,541.15,1.136,صاعد,69.92,9.687,34,...,26,Zacks Investment Ideas feature highlights: App...,,صاعد,11.6192,ضمن النطاق المتوسط,501.73,511.89,541.15,إيجابي
3,4,سهم أمريكي,ألفابت,GOOGL,352.72,0.301,صاعد,57.30,0.63,20,...,15,"Prediction: Nvidia Will Overtake Alphabet, App...",,صاعد,1.6851,ضمن النطاق المتوسط,346.08,346.09,352.72,إيجابي
4,5,سهم أمريكي,ستاندرد آند بورز 500,SPY,778.07,-0.060,صاعد,59.89,2.8224,50,...,27,"Stock Market Today: Dow gains but S&P 500, Nas...",,صاعد,3.8745,ضمن النطاق المتوسط,766.94,768.55,778.07,سلبي
5,6,سهم أمريكي,ناسداك 100,QQQ,746.04,-0.696,صاعد,56.72,8.9299,5,...,3,"Stock Market Today: S&P 500, Dow Futures Gain,...",,صاعد,9.0018,ضمن النطاق المتوسط,725.18,739.24,746.04,سلبي
6,7,سهم أمريكي,أمازون,AMZN,259.53,-1.105,مختلط,55.59,-0.6976,17,...,13,Zacks Investment Ideas feature highlights: App...,,مختلط,0.757,ضمن النطاق المتوسط,258.85,252.32,259.53,سلبي
7,8,سهم أمريكي,تسلا,TSLA,378.03,-1.220,صاعد,56.46,4.2311,20,...,18,Zacks Investment Ideas feature highlights: App...,,صاعد,5.1446,ضمن النطاق المتوسط,356.08,369.61,378.03,سلبي
8,9,سهم أمريكي,إنفيديا,NVDA,226.32,-1.291,مختلط,49.42,3.7581,46,...,36,Wall Street stocks end tad lower after hot inf...,,مختلط,3.3139,ضمن النطاق المتوسط,222.46,227.5,226.32,سلبي

✅ اسم الجدول الجديد:
wadq_us_summary_df

In [ ]:
# 🌧️ الودق AI — المرحلة 33
# إنشاء نظام الإشارات الفنية الأولية للأسهم الأمريكية
# مع الحفاظ على التقارير السابقة

import pandas as pd
import yfinance as yf

print("🌧️ الودق AI — المرحلة 33")
print("=" * 55)

us_symbols = [
    "NVDA", "TSLA", "AAPL", "MSFT", "AMZN",
    "GOOGL", "META", "QQQ", "SPY"
]

wadq_us_signals = []

for ticker in us_symbols:
    try:
        hist = yf.Ticker(ticker).history(
            period="6mo",
            interval="1d",
            auto_adjust=True
        )

        if hist.empty or len(hist) < 30:
            print(f"⚠️ بيانات غير كافية: {ticker}")
            continue

        close = hist["Close"].dropna()

        # المتوسطات المتحركة
        ma20 = close.rolling(20).mean().iloc[-1]
        ma50 = close.rolling(50).mean().iloc[-1]

        # مؤشر القوة النسبية RSI
        delta = close.diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        avg_gain = gain.rolling(14).mean()
        avg_loss = loss.rolling(14).mean()

        rs = avg_gain / avg_loss
        rsi = (100 - (100 / (1 + rs))).iloc[-1]

        last_price = close.iloc[-1]

        # تحديد الاتجاه الفني
        if last_price > ma20 and ma20 > ma50:
            trend = "صاعد"
        elif last_price < ma20 and ma20 < ma50:
            trend = "هابط"
        else:
            trend = "متذبذب"

        # إشارة أولية وليست توصية استثمارية
        if trend == "صاعد" and 50 <= rsi < 70:
            signal = "إيجابية مبدئية"
        elif trend == "هابط" and rsi < 50:
            signal = "سلبية مبدئية"
        else:
            signal = "انتظار"

        wadq_us_signals.append({
            "الرمز": ticker,
            "آخر سعر": round(float(last_price), 2),
            "المتوسط المتحرك 20": round(float(ma20), 2),
            "المتوسط المتحرك 50": round(float(ma50), 2),
            "RSI": round(float(rsi), 2),
            "الاتجاه الفني": trend,
            "الإشارة الأولية": signal,
            "تاريخ آخر جلسة": str(close.index[-1].date())
        })

        print(f"✅ اكتمل تحليل {ticker}")

    except Exception as e:
        print(f"⚠️ تعذر تحليل {ticker}: {e}")

# إنشاء جدول مستقل
wadq_us_signals_df = pd.DataFrame(wadq_us_signals)

if not wadq_us_signals_df.empty:
    print("\n✅ اكتملت المرحلة 33")
    print("عدد الأصول التي تم تحليلها:", len(wadq_us_signals_df))
    display(wadq_us_signals_df)
else:
    print("\n⚠️ لم تُنشأ نتائج. تحققي من اتصال البيانات.")

🌧️ الودق AI — المرحلة 33
=======================================================
✅ اكتمل تحليل NVDA
✅ اكتمل تحليل TSLA
✅ اكتمل تحليل AAPL
✅ اكتمل تحليل MSFT
✅ اكتمل تحليل AMZN
✅ اكتمل تحليل GOOGL
✅ اكتمل تحليل META
✅ اكتمل تحليل QQQ
✅ اكتمل تحليل SPY

✅ اكتملت المرحلة 33
عدد الأصول التي تم تحليلها: 9

,الرمز,آخر سعر,المتوسط المتحرك 20,المتوسط المتحرك 50,RSI,الاتجاه الفني,الإشارة الأولية,تاريخ آخر جلسة
0,NVDA,226.32,227.50,222.46,46.37,متذبذب,انتظار,2026-10-12
1,TSLA,378.03,369.61,356.08,49.43,صاعد,انتظار,2026-10-12
2,AAPL,340.97,335.78,323.00,51.30,صاعد,إيجابية مبدئية,2026-10-12
3,MSFT,541.15,511.89,501.73,77.88,صاعد,انتظار,2026-10-12
4,AMZN,259.53,252.32,258.85,55.34,متذبذب,انتظار,2026-10-12
5,GOOGL,352.72,346.09,346.08,51.55,صاعد,إيجابية مبدئية,2026-10-12
6,META,742.96,722.94,643.13,51.56,صاعد,إيجابية مبدئية,2026-10-12
7,QQQ,746.04,739.24,725.18,48.85,صاعد,انتظار,2026-10-12
8,SPY,778.10,768.56,766.94,55.15,صاعد,إيجابية مبدئية,2026-10-12

In [ ]:
# 🌧️ الودق AI — المرحلة 34
# إنشاء لوحة ملخص الإشارات الفنية

import pandas as pd

print("🌧️ الودق AI — المرحلة 34")
print("=" * 50)

if "wadq_us_signals_df" not in globals():

    print("⚠️ جدول الإشارات الفنية غير موجود.")
    print("يرجى التأكد من نجاح المرحلة 33.")

else:

    # إنشاء نسخة مستقلة للحفاظ على النتائج الأصلية
    wadq_us_dashboard_df = wadq_us_signals_df.copy()

    # التحقق من عمود الإشارة
    signal_col = "الإشارة الأولية"
    trend_col = "الاتجاه الفني"

    if signal_col not in wadq_us_dashboard_df.columns:

        print("⚠️ عمود الإشارة الأولية غير موجود.")

    else:

        # حساب ملخص الإشارات
        wadq_signal_summary_df = (
            wadq_us_dashboard_df[signal_col]
            .value_counts(dropna=False)
            .rename_axis("الإشارة")
            .reset_index(name="عدد الأصول")
        )

        print("✅ تم إنشاء لوحة الإشارات الفنية")
        print("عدد الأصول:", len(wadq_us_dashboard_df))

        print("\n📊 ملخص الإشارات:")
        display(wadq_signal_summary_df)

        print("\n📈 تفاصيل الأصول:")
        display(wadq_us_dashboard_df)

        print("\n🌧️ أسماء الجداول الجديدة:")
        print("wadq_us_dashboard_df")
        print("wadq_signal_summary_df")

🌧️ الودق AI — المرحلة 34
==================================================
✅ تم إنشاء لوحة الإشارات الفنية
عدد الأصول: 9

📊 ملخص الإشارات:

          الإشارة  عدد الأصول
0          انتظار           5
1  إيجابية مبدئية           4

📈 تفاصيل الأصول:

,الرمز,آخر سعر,المتوسط المتحرك 20,المتوسط المتحرك 50,RSI,الاتجاه الفني,الإشارة الأولية,تاريخ آخر جلسة
0,NVDA,226.32,227.50,222.46,46.37,متذبذب,انتظار,2026-10-12
1,TSLA,378.03,369.61,356.08,49.43,صاعد,انتظار,2026-10-12
2,AAPL,340.97,335.78,323.00,51.30,صاعد,إيجابية مبدئية,2026-10-12
3,MSFT,541.15,511.89,501.73,77.88,صاعد,انتظار,2026-10-12
4,AMZN,259.53,252.32,258.85,55.34,متذبذب,انتظار,2026-10-12
5,GOOGL,352.72,346.09,346.08,51.55,صاعد,إيجابية مبدئية,2026-10-12
6,META,742.96,722.94,643.13,51.56,صاعد,إيجابية مبدئية,2026-10-12
7,QQQ,746.04,739.24,725.18,48.85,صاعد,انتظار,2026-10-12
8,SPY,778.10,768.56,766.94,55.15,صاعد,إيجابية مبدئية,2026-10-12

🌧️ أسماء الجداول الجديدة:
wadq_us_dashboard_df
wadq_signal_summary_df

In [ ]:
# 🌧️ الودق AI — المرحلة 35
# تجهيز جدول دمج الإشارات الفنية والأخبار
# دون تعديل الجداول السابقة

import pandas as pd

print("🌧️ الودق AI — المرحلة 35")
print("=" * 50)

if "wadq_us_signals_df" not in globals():
    print("⚠️ جدول الإشارات الفنية غير موجود.")

else:
    # إنشاء نسخة مستقلة من الإشارات الفنية
    wadq_us_news_signals_df = wadq_us_signals_df.copy()

    # البحث عن جداول الأخبار الموجودة مسبقًا
    news_candidates = [
        name for name in globals()
        if "news" in name.lower()
        and isinstance(globals()[name], pd.DataFrame)
    ]

    print("✅ تم تجهيز جدول الإشارات الفنية.")
    print("عدد الأصول:", len(wadq_us_news_signals_df))

    print("\nجداول الأخبار المكتشفة:")
    if news_candidates:
        for name in news_candidates:
            print("-", name, "| عدد الصفوف:", len(globals()[name]))
    else:
        print("لم يُكتشف جدول أخبار باسم يحتوي على news.")

    print("\nمعاينة الإشارات الفنية:")
    display(wadq_us_news_signals_df)

    print("\nاسم الجدول الجديد:")
    print("wadq_us_news_signals_df")

🌧️ الودق AI — المرحلة 35
==================================================
✅ تم تجهيز جدول الإشارات الفنية.
عدد الأصول: 9

جداول الأخبار المكتشفة:
- wadq_news_df | عدد الصفوف: 565
- wadq_news_scored_df | عدد الصفوف: 565
- wadq_ticker_news_df | عدد الصفوف: 195
- news | عدد الصفوف: 195
- news_summary | عدد الصفوف: 9
- ticker_news | عدد الصفوف: 50
- news_summary_df | عدد الصفوف: 9
- latest_news | عدد الصفوف: 9
- wadq_us_news_technical_df | عدد الصفوف: 195
- news_df | عدد الصفوف: 195
- news_work | عدد الصفوف: 195
- wadq_news_summary_df | عدد الصفوف: 9
- wadq_us_news_signals_df | عدد الصفوف: 9

معاينة الإشارات الفنية:

,الرمز,آخر سعر,المتوسط المتحرك 20,المتوسط المتحرك 50,RSI,الاتجاه الفني,الإشارة الأولية,تاريخ آخر جلسة
0,NVDA,226.32,227.50,222.46,46.37,متذبذب,انتظار,2026-10-12
1,TSLA,378.03,369.61,356.08,49.43,صاعد,انتظار,2026-10-12
2,AAPL,340.97,335.78,323.00,51.30,صاعد,إيجابية مبدئية,2026-10-12
3,MSFT,541.15,511.89,501.73,77.88,صاعد,انتظار,2026-10-12
4,AMZN,259.53,252.32,258.85,55.34,متذبذب,انتظار,2026-10-12
5,GOOGL,352.72,346.09,346.08,51.55,صاعد,إيجابية مبدئية,2026-10-12
6,META,742.96,722.94,643.13,51.56,صاعد,إيجابية مبدئية,2026-10-12
7,QQQ,746.04,739.24,725.18,48.85,صاعد,انتظار,2026-10-12
8,SPY,778.10,768.56,766.94,55.15,صاعد,إيجابية مبدئية,2026-10-12

اسم الجدول الجديد:
wadq_us_news_signals_df

In [ ]:
# 🌧️ الودق AI — فحص جداول الأخبار الموجودة

import pandas as pd

print("🌧️ البحث عن جداول الأخبار في الودق AI")
print("=" * 50)

news_tables = []

for name, obj in globals().copy().items():
    if isinstance(obj, pd.DataFrame):
        if any(word in name.lower() for word in ["news", "خبر", "اخبار", "أخبار"]):
            news_tables.append(name)

if news_tables:
    print("✅ جداول الأخبار المكتشفة:")

    for name in news_tables:
        df = globals()[name]

        print("\nاسم الجدول:", name)
        print("عدد الصفوف:", len(df))
        print("عدد الأعمدة:", len(df.columns))
        print("الأعمدة:", df.columns.tolist())

else:
    print("⚠️ لم يُعثر على جدول يحمل اسمًا مرتبطًا بالأخبار.")
    print("سنفحص الجداول الأخرى في الخطوة التالية.")

🌧️ البحث عن جداول الأخبار في الودق AI
==================================================
✅ جداول الأخبار المكتشفة:

اسم الجدول: wadq_news_df
عدد الصفوف: 565
عدد الأعمدة: 5
الأعمدة: ['category', 'title', 'published', 'link', 'fetched_at_utc']

اسم الجدول: wadq_news_scored_df
عدد الصفوف: 565
عدد الأعمدة: 8
الأعمدة: ['category', 'title', 'published', 'link', 'fetched_at_utc', 'sentiment', 'related_tickers', 'ticker_count']

اسم الجدول: wadq_ticker_news_df
عدد الصفوف: 195
عدد الأعمدة: 6
الأعمدة: ['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

اسم الجدول: news
عدد الصفوف: 195
عدد الأعمدة: 6
الأعمدة: ['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

اسم الجدول: news_summary
عدد الصفوف: 9
عدد الأعمدة: 2
الأعمدة: ['الرمز', 'عدد الأخبار']

اسم الجدول: ticker_news
عدد الصفوف: 50
عدد الأعمدة: 6
الأعمدة: ['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

اسم الجدول: news_summary_df
عدد الصفوف: 9
عدد الأعمدة: 5
الأعمدة: ['الرمز', 'عدد الأخبار', 'الأخبار الإيجابية', 'الأخبار السلبية', 'الأخبار المحايدة']

اسم الجدول: latest_news
عدد الصفوف: 9
عدد الأعمدة: 5
الأعمدة: ['الرمز', 'أحدث عنوان خبر', 'تقييم أحدث خبر', 'تاريخ أحدث خبر', 'رابط أحدث خبر']

اسم الجدول: wadq_us_news_technical_df
عدد الصفوف: 195
عدد الأعمدة: 16
الأعمدة: ['ticker', 'news_title', 'sentiment', 'category', 'published', 'link', 'السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

اسم الجدول: news_df
عدد الصفوف: 195
عدد الأعمدة: 6
الأعمدة: ['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

اسم الجدول: news_work
عدد الصفوف: 195
عدد الأعمدة: 12
الأعمدة: ['ticker', 'news_title', 'sentiment', 'category', 'published', 'link', '_symbol', '_sentiment', '_title', '_positive', '_negative', '_neutral']

اسم الجدول: wadq_news_summary_df
عدد الصفوف: 9
عدد الأعمدة: 6
الأعمدة: ['الرمز', 'عدد_الأخبار', 'أخبار_إيجابية', 'أخبار_سلبية', 'أخبار_محايدة', 'أحدث_عنوان_متاح']

اسم الجدول: wadq_us_news_signals_df
عدد الصفوف: 9
عدد الأعمدة: 8
الأعمدة: ['الرمز', 'آخر سعر', 'المتوسط المتحرك 20', 'المتوسط المتحرك 50', 'RSI', 'الاتجاه الفني', 'الإشارة الأولية', 'تاريخ آخر جلسة']

In [ ]:
# 🌧️ الودق AI — المرحلة 35
# فحص جداول الأخبار قبل الربط

import pandas as pd

tables_to_check = [
    "latest_news",
    "wadq_us_news_technical_df",
    "news_df",
    "news_work",
    "wadq_news_summary_df",
    "wadq_us_news_signals_df"
]

print("🌧️ فحص مصادر الأخبار في الودق AI")
print("=" * 55)

for name in tables_to_check:

    if name in globals() and isinstance(globals()[name], pd.DataFrame):

        df = globals()[name]

        print(f"\n📊 اسم الجدول: {name}")
        print("عدد الصفوف:", len(df))
        print("عدد الأعمدة:", len(df.columns))
        print("أسماء الأعمدة:")
        print(df.columns.tolist())

        # عرض عينة صغيرة من جدول الأخبار الأساسي
        if name in ["latest_news", "news_df", "wadq_news_summary_df"]:
            display(df.head(3))

    else:
        print(f"\n⚠️ الجدول غير موجود: {name}")

print("\n✅ انتهى فحص جداول الأخبار.")

🌧️ فحص مصادر الأخبار في الودق AI
=======================================================

📊 اسم الجدول: latest_news
عدد الصفوف: 9
عدد الأعمدة: 5
أسماء الأعمدة:
['الرمز', 'أحدث عنوان خبر', 'تقييم أحدث خبر', 'تاريخ أحدث خبر', 'رابط أحدث خبر']

,الرمز,أحدث عنوان خبر,تقييم أحدث خبر,تاريخ أحدث خبر,رابط أحدث خبر
0,SPY,"Stock Market Today: Dow gains but S&P 500, Nas...",إيجابي مبدئي,2026-10-12 19:07:00+00:00,https://news.google.com/rss/articles/CBMiugFBV...
2,QQQ,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,2026-10-12 12:29:52+00:00,https://news.google.com/rss/articles/CBMiqgJBV...
23,NVDA,Wall Street stocks end tad lower after hot inf...,محايد أو غير واضح,2026-08-26 07:00:00+00:00,https://news.google.com/rss/articles/CBMiqwFBV...

📊 اسم الجدول: wadq_us_news_technical_df
عدد الصفوف: 195
عدد الأعمدة: 16
أسماء الأعمدة:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link', 'السهم', 'الرمز', 'آخر إغلاق', 'المتوسط 20', 'المتوسط 50', 'RSI', 'حالة RSI', 'MACD', 'إشارة MACD', 'الاتجاه']

📊 اسم الجدول: news_df
عدد الصفوف: 195
عدد الأعمدة: 6
أسماء الأعمدة:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link']

,ticker,news_title,sentiment,category,published,link
0,SPY,"Stock Market Today: Dow gains but S&P 500, Nas...",إيجابي مبدئي,الأسواق الأمريكية,"Mon, 12 Oct 2026 19:07:00 GMT",https://news.google.com/rss/articles/CBMiugFBV...
1,SPY,"S&P 500, Nasdaq Slip as Oil Rises on Russia St...",إيجابي مبدئي,الأسواق الأمريكية,"Mon, 12 Oct 2026 18:43:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...
2,QQQ,"Stock Market Today: S&P 500, Dow Futures Gain,...",محايد أو غير واضح,الأسواق الأمريكية,"Mon, 12 Oct 2026 12:29:52 GMT",https://news.google.com/rss/articles/CBMiqgJBV...

📊 اسم الجدول: news_work
عدد الصفوف: 195
عدد الأعمدة: 12
أسماء الأعمدة:
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link', '_symbol', '_sentiment', '_title', '_positive', '_negative', '_neutral']

📊 اسم الجدول: wadq_news_summary_df
عدد الصفوف: 9
عدد الأعمدة: 6
أسماء الأعمدة:
['الرمز', 'عدد_الأخبار', 'أخبار_إيجابية', 'أخبار_سلبية', 'أخبار_محايدة', 'أحدث_عنوان_متاح']

,الرمز,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح
0,AAPL,1,0,0,1,"Are Amazon, Apple stocks overpriced? Here are ..."
1,AMZN,17,4,0,13,Zacks Investment Ideas feature highlights: App...
2,GOOGL,20,5,0,15,"Prediction: Nvidia Will Overtake Alphabet, App..."

📊 اسم الجدول: wadq_us_news_signals_df
عدد الصفوف: 9
عدد الأعمدة: 8
أسماء الأعمدة:
['الرمز', 'آخر سعر', 'المتوسط المتحرك 20', 'المتوسط المتحرك 50', 'RSI', 'الاتجاه الفني', 'الإشارة الأولية', 'تاريخ آخر جلسة']

✅ انتهى فحص جداول الأخبار.

In [ ]:
# 🌧️ الودق AI — المرحلة 35
# ربط ملخص الأخبار بالإشارات الفنية
# مع الحفاظ على الجداول السابقة

import pandas as pd

print("🌧️ بدء ربط الأخبار بالإشارات الفنية")
print("=" * 50)

if (
    "wadq_us_signals_df" not in globals()
    or "wadq_news_summary_df" not in globals()
):
    print("⚠️ أحد الجدولين المطلوبين غير موجود.")

else:
    technical_df = wadq_us_signals_df.copy()
    news_df = wadq_news_summary_df.copy()

    # توحيد أسماء أعمدة الربط المحتملة
    technical_symbol = next(
        (c for c in ["الرمز", "ticker", "symbol"]
         if c in technical_df.columns),
        None
    )

    news_symbol = next(
        (c for c in ["الرمز", "ticker", "symbol"]
         if c in news_df.columns),
        None
    )

    if technical_symbol is None or news_symbol is None:
        print("⚠️ تعذر تحديد عمود الرمز في أحد الجدولين.")
        print("أعمدة التحليل الفني:", technical_df.columns.tolist())
        print("أعمدة الأخبار:", news_df.columns.tolist())

    else:
        # توحيد شكل رموز الأسهم
        technical_df[technical_symbol] = (
            technical_df[technical_symbol].astype(str).str.upper().str.strip()
        )

        news_df[news_symbol] = (
            news_df[news_symbol].astype(str).str.upper().str.strip()
        )

        # الدمج مع الاحتفاظ بجميع الأسهم الأمريكية
        wadq_us_news_integrated_df = technical_df.merge(
            news_df,
            left_on=technical_symbol,
            right_on=news_symbol,
            how="left",
            suffixes=("_فني", "_أخبار")
        )

        print("✅ تم إنشاء جدول الدمج.")
        print("عدد صفوف الجدول:", len(wadq_us_news_integrated_df))
        print("عدد الأعمدة:", len(wadq_us_news_integrated_df.columns))
        print("\nأسماء الأعمدة:")
        print(wadq_us_news_integrated_df.columns.tolist())

        display(wadq_us_news_integrated_df)

        print("\nاسم الجدول الجديد:")
        print("wadq_us_news_integrated_df")

🌧️ بدء ربط الأخبار بالإشارات الفنية
==================================================
✅ تم إنشاء جدول الدمج.
عدد صفوف الجدول: 9
عدد الأعمدة: 13

أسماء الأعمدة:
['الرمز', 'آخر سعر', 'المتوسط المتحرك 20', 'المتوسط المتحرك 50', 'RSI', 'الاتجاه الفني', 'الإشارة الأولية', 'تاريخ آخر جلسة', 'عدد_الأخبار', 'أخبار_إيجابية', 'أخبار_سلبية', 'أخبار_محايدة', 'أحدث_عنوان_متاح']

,الرمز,آخر سعر,المتوسط المتحرك 20,المتوسط المتحرك 50,RSI,الاتجاه الفني,الإشارة الأولية,تاريخ آخر جلسة,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح
0,NVDA,226.32,227.50,222.46,46.37,متذبذب,انتظار,2026-10-12,46,9,1,36,Wall Street stocks end tad lower after hot inf...
1,TSLA,378.03,369.61,356.08,49.43,صاعد,انتظار,2026-10-12,20,2,0,18,Zacks Investment Ideas feature highlights: App...
2,AAPL,340.97,335.78,323.00,51.30,صاعد,إيجابية مبدئية,2026-10-12,1,0,0,1,"Are Amazon, Apple stocks overpriced? Here are ..."
3,MSFT,541.15,511.89,501.73,77.88,صاعد,انتظار,2026-10-12,34,7,1,26,Zacks Investment Ideas feature highlights: App...
4,AMZN,259.53,252.32,258.85,55.34,متذبذب,انتظار,2026-10-12,17,4,0,13,Zacks Investment Ideas feature highlights: App...
5,GOOGL,352.72,346.09,346.08,51.55,صاعد,إيجابية مبدئية,2026-10-12,20,5,0,15,"Prediction: Nvidia Will Overtake Alphabet, App..."
6,META,742.96,722.94,643.13,51.56,صاعد,إيجابية مبدئية,2026-10-12,2,1,0,1,I Predicted That Oracle and Netflix Would Join...
7,QQQ,746.04,739.24,725.18,48.85,صاعد,انتظار,2026-10-12,5,2,0,3,"Stock Market Today: S&P 500, Dow Futures Gain,..."
8,SPY,778.10,768.56,766.94,55.15,صاعد,إيجابية مبدئية,2026-10-12,50,15,8,27,"Stock Market Today: Dow gains but S&P 500, Nas..."

اسم الجدول الجديد:
wadq_us_news_integrated_df

In [ ]:
# 🌧️ الودق AI — المرحلة 35
# فحص جودة دمج الأخبار والإشارات الفنية

import pandas as pd

print("🌧️ فحص جودة ربط الأخبار بالأسهم")
print("=" * 50)

if "wadq_us_news_integrated_df" not in globals():

    print("⚠️ جدول الدمج غير موجود.")

else:

    df = wadq_us_news_integrated_df

    print("عدد الصفوف:", len(df))
    print("عدد الأعمدة:", len(df.columns))

    print("\nالأعمدة التي تحتوي على بيانات الأخبار:")

    news_cols = [
        c for c in df.columns
        if any(word in str(c).lower()
               for word in ["news", "خبر", "أخبار", "عنوان", "sentiment"])
    ]

    print(news_cols)

    print("\nمعاينة رموز الأسهم والأخبار:")

    symbol_col = next(
        (c for c in ["الرمز", "ticker", "symbol"]
         if c in df.columns),
        None
    )

    title_cols = [
        c for c in df.columns
        if any(word in str(c).lower()
               for word in ["news_title", "news title", "عنوان الخبر", "news_title_أخبار"])
    ]

    if symbol_col is not None:
        cols_to_show = [symbol_col] + [
            c for c in title_cols if c in df.columns
        ]

        if len(cols_to_show) > 1:
            display(df[cols_to_show].head(10))
        else:
            display(df[[symbol_col]].head(10))

    print("\nعينة من أول صفين:")
    display(df.head(2))

🌧️ فحص جودة ربط الأخبار بالأسهم
==================================================
عدد الصفوف: 9
عدد الأعمدة: 13

الأعمدة التي تحتوي على بيانات الأخبار:
['عدد_الأخبار', 'أخبار_إيجابية', 'أخبار_سلبية', 'أخبار_محايدة', 'أحدث_عنوان_متاح']

معاينة رموز الأسهم والأخبار:

   الرمز
0   NVDA
1   TSLA
2   AAPL
3   MSFT
4   AMZN
5  GOOGL
6   META
7    QQQ
8    SPY

عينة من أول صفين:

,الرمز,آخر سعر,المتوسط المتحرك 20,المتوسط المتحرك 50,RSI,الاتجاه الفني,الإشارة الأولية,تاريخ آخر جلسة,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح
0,NVDA,226.32,227.50,222.46,46.37,متذبذب,انتظار,2026-10-12,46,9,1,36,Wall Street stocks end tad lower after hot inf...
1,TSLA,378.03,369.61,356.08,49.43,صاعد,انتظار,2026-10-12,20,2,0,18,Zacks Investment Ideas feature highlights: App...

In [ ]:
# 🌧️ الودق AI — المرحلة 35
# التحقق من ارتباط الأخبار بالأسهم

import pandas as pd

print("🌧️ فحص ربط الأخبار بالأسهم")
print("=" * 45)

if "wadq_us_news_integrated_df" not in globals():

    print("⚠️ جدول الدمج غير موجود.")

else:
    df = wadq_us_news_integrated_df

    print("عدد الصفوف:", len(df))
    print("\nجميع الأعمدة:")
    for col in df.columns:
        print("-", col)

    # البحث عن أعمدة الأخبار
    news_cols = [
        col for col in df.columns
        if any(word in str(col).lower()
               for word in ["news", "title", "sentiment", "خبر", "عنوان"])
    ]

    print("\nأعمدة الأخبار المكتشفة:")
    print(news_cols)

    if news_cols:
        print("\nعينة من بيانات الأخبار:")
        display(df[news_cols].head(9))
    else:
        print("\n⚠️ لم يتم العثور على أعمدة واضحة للأخبار.")

    print("\n🌧️ انتهى الفحص.")

🌧️ فحص ربط الأخبار بالأسهم
=============================================
عدد الصفوف: 9

جميع الأعمدة:
- الرمز
- آخر سعر
- المتوسط المتحرك 20
- المتوسط المتحرك 50
- RSI
- الاتجاه الفني
- الإشارة الأولية
- تاريخ آخر جلسة
- عدد_الأخبار
- أخبار_إيجابية
- أخبار_سلبية
- أخبار_محايدة
- أحدث_عنوان_متاح

أعمدة الأخبار المكتشفة:
['أحدث_عنوان_متاح']

عينة من بيانات الأخبار:

                                     أحدث_عنوان_متاح
0  Wall Street stocks end tad lower after hot inf...
1  Zacks Investment Ideas feature highlights: App...
2  Are Amazon, Apple stocks overpriced? Here are ...
3  Zacks Investment Ideas feature highlights: App...
4  Zacks Investment Ideas feature highlights: App...
5  Prediction: Nvidia Will Overtake Alphabet, App...
6  I Predicted That Oracle and Netflix Would Join...
7  Stock Market Today: S&P 500, Dow Futures Gain,...
8  Stock Market Today: Dow gains but S&P 500, Nas...

🌧️ انتهى الفحص.

In [ ]:
# 🌧️ الودق AI — فحص مصدر الأخبار الحقيقي

import pandas as pd

print("🌧️ فحص جدول ملخص الأخبار")
print("=" * 50)

if "wadq_news_summary_df" in globals():

    news = wadq_news_summary_df.copy()

    print("عدد الصفوف:", len(news))
    print("عدد الأعمدة:", len(news.columns))
    print("\nأسماء الأعمدة:")
    print(news.columns.tolist())

    print("\nعرض جميع الأخبار:")
    display(news)

elif "news_work" in globals():

    news = news_work.copy()

    print("تم اختيار جدول news_work")
    print("عدد الصفوف:", len(news))
    print("أسماء الأعمدة:")
    print(news.columns.tolist())

    display(news.head(10))

else:
    print("⚠️ لم يتم العثور على جداول الأخبار المطلوبة.")

🌧️ فحص جدول ملخص الأخبار
==================================================
عدد الصفوف: 9
عدد الأعمدة: 6

أسماء الأعمدة:
['الرمز', 'عدد_الأخبار', 'أخبار_إيجابية', 'أخبار_سلبية', 'أخبار_محايدة', 'أحدث_عنوان_متاح']

عرض جميع الأخبار:

,الرمز,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح
0,AAPL,1,0,0,1,"Are Amazon, Apple stocks overpriced? Here are ..."
1,AMZN,17,4,0,13,Zacks Investment Ideas feature highlights: App...
2,GOOGL,20,5,0,15,"Prediction: Nvidia Will Overtake Alphabet, App..."
3,META,2,1,0,1,I Predicted That Oracle and Netflix Would Join...
4,MSFT,34,7,1,26,Zacks Investment Ideas feature highlights: App...
5,NVDA,46,9,1,36,Wall Street stocks end tad lower after hot inf...
6,QQQ,5,2,0,3,"Stock Market Today: S&P 500, Dow Futures Gain,..."
7,SPY,50,15,8,27,"Stock Market Today: Dow gains but S&P 500, Nas..."
8,TSLA,20,2,0,18,Zacks Investment Ideas feature highlights: App...

In [ ]:
# 🌧️ الودق AI — فحص الأخبار بدون صور

print("===== ملخص الأخبار =====")

if "wadq_news_summary_df" in globals():
    print(wadq_news_summary_df.to_string(index=False))

else:
    print("جدول ملخص الأخبار غير موجود")

print("\n===== أعمدة جدول الأخبار =====")

if "news_work" in globals():
    print(news_work.columns.tolist())
    print("\nأول 3 أخبار:")
    print(news_work.head(3).to_string(index=False))

else:
    print("جدول الأخبار غير موجود")

===== ملخص الأخبار =====
الرمز  عدد_الأخبار  أخبار_إيجابية  أخبار_سلبية  أخبار_محايدة                                                                                                                                                                                                                     أحدث_عنوان_متاح
 AAPL            1              0            0             1                                                                                                                                        Are Amazon, Apple stocks overpriced? Here are alternatives to the Magnificent 7. - USA Today
 AMZN           17              4            0            13                                                                                                                         Zacks Investment Ideas feature highlights: Apple, Microsoft, Meta, Amazon, Nvidia and Tesla - Yahoo Finance
GOOGL           20              5            0            15                   Prediction: Nvidia Will Overtake Alphabet, Apple, and Microsoft to Become the World's Most Profitable Company by the End of 2027. Here's Why the "Magnificent Seven" Stock Is a Buy in January. - The Motley Fool
 META            2              1            0             1 I Predicted That Oracle and Netflix Would Join Nvidia, Alphabet, Apple, Microsoft, Amazon, Broadcom, Meta Platforms, and Tesla in the $1 Trillion Club by 2030. Here's Why That Forecast Is Being Tested in 2026. - The Motley Fool
 MSFT           34              7            1            26                                                                                                                         Zacks Investment Ideas feature highlights: Apple, Microsoft, Meta, Amazon, Nvidia and Tesla - Yahoo Finance
 NVDA           46              9            1            36                                                                                                                                        Wall Street stocks end tad lower after hot inflation data ahead of Nvidia earnings - Reuters
  QQQ            5              2            0             3                                                            Stock Market Today: S&P 500, Dow Futures Gain, Nasdaq 100 Falls as Iran Flags ‘Inadequate’ US Response to Peace Terms — SMP, QMCO, SVRN in Focus (UPDATED) - TradingView
  SPY           50             15            8            27                                                                                                                         Stock Market Today: Dow gains but S&P 500, Nasdaq slip as chip stocks dip and oil prices rise - MarketWatch
 TSLA           20              2            0            18                                                                                                                         Zacks Investment Ideas feature highlights: Apple, Microsoft, Meta, Amazon, Nvidia and Tesla - Yahoo Finance

===== أعمدة جدول الأخبار =====
['ticker', 'news_title', 'sentiment', 'category', 'published', 'link', '_symbol', '_sentiment', '_title', '_positive', '_negative', '_neutral']

أول 3 أخبار:
ticker                                                                                                                                                               news_title         sentiment          category                     published                                                                                                                                                                                                                                                                                                                                                                                                                                                           link _symbol        _sentiment                                                                                                                                                                   _title  _positive  _negative  _neutral
   SPY                                                              Stock Market Today: Dow gains but S&P 500, Nasdaq slip as chip stocks dip and oil prices rise - MarketWatch      إيجابي مبدئي الأسواق الأمريكية Mon, 12 Oct 2026 19:07:00 GMT                                                                                                                                                      https://news.google.com/rss/articles/CBMiugFBVV95cUxNSW9zS0d3SUlWb3NJVktabzFrdHpjdjRYakhIZmtrM0Y2MU9uSV9yLVlmQlBwT2V2UGc0R2VfZzFEaWw1a2VoSFI3R19Na2Y5cjhxaVlpVTFIS21rNUZSc1otMS1xRnEteTU5MTlGLUtSZXJTX01wVFJfeFVaWElOTXNTcW5TR3ZXeGRRSlRhR3poUW5CaFg4UFJlTmdvZW9LcVpSeFJ6Um5ubWVFMnBKU2wzLUhkTl9NMWc?oc=5     SPY      إيجابي مبدئي                                                              Stock Market Today: Dow gains but S&P 500, Nasdaq slip as chip stocks dip and oil prices rise - MarketWatch          1          0         0
   SPY                                                                                                     S&P 500, Nasdaq Slip as Oil Rises on Russia Strikes in Ukraine - WSJ      إيجابي مبدئي الأسواق الأمريكية Mon, 12 Oct 2026 18:43:00 GMT                                                                                                                                          https://news.google.com/rss/articles/CBMiwwFBVV95cUxPamJ2ZGp1bmNfdEs1MUlid3YzVTcxNmRtZW9DRjE5LUhjM0E5cHJ3elNrYzVXTVBWOVNYX0hVTVJ2anJUUG44QnBvWnJfNVVUbnRTTDZEcVdqSTFSeWxuemlXOVJvWUhObmhiOVk0X083ckp4WEtQTUU3dnVNMW1wd3VxUlctaG5RbGpISVI3bVNQZXpHT3hWVEZZbDJrblZTYmhPVG9pVlJxUUJ3MnFNUmozQk5iNkp6OFlzNWppUEN1VXc?oc=5     SPY      إيجابي مبدئي                                                                                                     S&P 500, Nasdaq Slip as Oil Rises on Russia Strikes in Ukraine - WSJ          1          0         0
   QQQ Stock Market Today: S&P 500, Dow Futures Gain, Nasdaq 100 Falls as Iran Flags ‘Inadequate’ US Response to Peace Terms — SMP, QMCO, SVRN in Focus (UPDATED) - TradingView محايد أو غير واضح الأسواق الأمريكية Mon, 12 Oct 2026 12:29:52 GMT https://news.google.com/rss/articles/CBMiqgJBVV95cUxPVWVJZGktV0hUd05SREJkRFNiWTl0NHc4UUF0UDJSTXhfbGVBU1BMUjBMY1hDejFTRXU3b2ZVc19hQkJmYjR3emxhTXpyU3ZSQ2pIS1BKZkZXd1VQWEt0VkZSbDBiYllweTdvSTFsRmFnYzZlYVc0M0lrY1RjaXIwYTZTbC1yeDBHNG1YQnd6S2J2aEwxM080c1FDVmI1TG5GOE9GSXVlc0pWYl9LMTBxaE5tbDF0S04wZE1kakhoalBlMFdhcGQ0ajc3MTUzbExGVUtXTlA5NnlGckJyTnotSmI0Vko0dU94WlhfWnhpMWx2dnVRRlJVaDFxdncxSWdYc3V1RVRCdGhkWkI4djNJd0YxMnh6REZZT2o5Q2tHbkRuVS1yYTVEbUV3?oc=5     QQQ محايد أو غير واضح Stock Market Today: S&P 500, Dow Futures Gain, Nasdaq 100 Falls as Iran Flags ‘Inadequate’ US Response to Peace Terms — SMP, QMCO, SVRN in Focus (UPDATED) - TradingView          0          0         1

In [ ]:
# 🌧️ الودق AI — المرحلة 36
# دمج التحليل الفني مع ملخص الأخبار
# مع الحفاظ على جميع الجداول السابقة

import pandas as pd
import numpy as np

print("🌧️ الودق AI — المرحلة 36")
print("=" * 55)

if (
    "wadq_us_signals_df" not in globals()
    or "wadq_news_summary_df" not in globals()
):
    print("⚠️ أحد الجدولين المطلوبين غير موجود.")

else:
    # نسخ مستقلة للحفاظ على البيانات الأصلية
    technical = wadq_us_signals_df.copy()
    news = wadq_news_summary_df.copy()

    # توحيد أسماء رموز الأصول
    technical["الرمز"] = (
        technical["الرمز"].astype(str).str.upper().str.strip()
    )

    news["الرمز"] = (
        news["الرمز"].astype(str).str.upper().str.strip()
    )

    # تحويل أعداد الأخبار إلى أرقام
    count_cols = [
        "عدد_الأخبار",
        "أخبار_إيجابية",
        "أخبار_سلبية",
        "أخبار_محايدة"
    ]

    for col in count_cols:
        if col in news.columns:
            news[col] = pd.to_numeric(
                news[col], errors="coerce"
            ).fillna(0)

    # دمج الفني مع الأخبار حسب الرمز
    wadq_us_ai_report_df = technical.merge(
        news,
        on="الرمز",
        how="left",
        validate="one_to_one",
        suffixes=("_فني", "_أخبار")
    )

    # تعويض غياب الأخبار بالأصفار مع الاحتفاظ بحقيقة عدم توفرها
    wadq_us_ai_report_df["حالة توفر الأخبار"] = (
        wadq_us_ai_report_df["عدد_الأخبار"]
        .apply(
            lambda x:
                "متاحة" if pd.notna(x) and x > 0
                else "لا توجد أخبار مطابقة"
        )
    )

    for col in count_cols:
        if col in wadq_us_ai_report_df.columns:
            wadq_us_ai_report_df[col] = (
                wadq_us_ai_report_df[col].fillna(0)
            )

    # مؤشر مشاعر أولي: نسبة الإيجابي ناقص نسبة السلبي
    total = wadq_us_ai_report_df["عدد_الأخبار"]

    positive_ratio = (
        wadq_us_ai_report_df["أخبار_إيجابية"]
        .div(total.where(total > 0))
    )

    negative_ratio = (
        wadq_us_ai_report_df["أخبار_سلبية"]
        .div(total.where(total > 0))
    )

    wadq_us_ai_report_df["مؤشر المشاعر الإخبارية"] = (
        (positive_ratio - negative_ratio) * 100
    ).round(2)

    wadq_us_ai_report_df.loc[
        total <= 0, "مؤشر المشاعر الإخبارية"
    ] = np.nan

    print("✅ تم إنشاء التقرير الموحد.")
    print("عدد الأصول:", len(wadq_us_ai_report_df))
    print("عدد الأعمدة:", len(wadq_us_ai_report_df.columns))

    print("\n📊 التقرير الفني والإخباري الموحد:")
    display(wadq_us_ai_report_df)

    print("\nاسم الجدول الجديد:")
    print("wadq_us_ai_report_df")

🌧️ الودق AI — المرحلة 36
=======================================================
✅ تم إنشاء التقرير الموحد.
عدد الأصول: 9
عدد الأعمدة: 15

📊 التقرير الفني والإخباري الموحد:

,الرمز,آخر سعر,المتوسط المتحرك 20,المتوسط المتحرك 50,RSI,الاتجاه الفني,الإشارة الأولية,تاريخ آخر جلسة,عدد_الأخبار,أخبار_إيجابية,أخبار_سلبية,أخبار_محايدة,أحدث_عنوان_متاح,حالة توفر الأخبار,مؤشر المشاعر الإخبارية
0,NVDA,226.32,227.50,222.46,46.37,متذبذب,انتظار,2026-10-12,46,9,1,36,Wall Street stocks end tad lower after hot inf...,متاحة,17.39
1,TSLA,378.03,369.61,356.08,49.43,صاعد,انتظار,2026-10-12,20,2,0,18,Zacks Investment Ideas feature highlights: App...,متاحة,10.00
2,AAPL,340.97,335.78,323.00,51.30,صاعد,إيجابية مبدئية,2026-10-12,1,0,0,1,"Are Amazon, Apple stocks overpriced? Here are ...",متاحة,0.00
3,MSFT,541.15,511.89,501.73,77.88,صاعد,انتظار,2026-10-12,34,7,1,26,Zacks Investment Ideas feature highlights: App...,متاحة,17.65
4,AMZN,259.53,252.32,258.85,55.34,متذبذب,انتظار,2026-10-12,17,4,0,13,Zacks Investment Ideas feature highlights: App...,متاحة,23.53
5,GOOGL,352.72,346.09,346.08,51.55,صاعد,إيجابية مبدئية,2026-10-12,20,5,0,15,"Prediction: Nvidia Will Overtake Alphabet, App...",متاحة,25.00
6,META,742.96,722.94,643.13,51.56,صاعد,إيجابية مبدئية,2026-10-12,2,1,0,1,I Predicted That Oracle and Netflix Would Join...,متاحة,50.00
7,QQQ,746.04,739.24,725.18,48.85,صاعد,انتظار,2026-10-12,5,2,0,3,"Stock Market Today: S&P 500, Dow Futures Gain,...",متاحة,40.00
8,SPY,778.10,768.56,766.94,55.15,صاعد,إيجابية مبدئية,2026-10-12,50,15,8,27,"Stock Market Today: Dow gains but S&P 500, Nas...",متاحة,14.00

اسم الجدول الجديد:
wadq_us_ai_report_df

In [ ]:
# 🌧️ الودق AI — المرحلة 36
# بناء الإشارات الفنية والإخبارية المدمجة

import pandas as pd
import numpy as np

print("🌧️ الودق AI — المرحلة 36")
print("=" * 55)

if "wadq_us_ai_report_df" not in globals():

    print("⚠️ التقرير الموحد غير موجود.")
    print("شغّلي خلية إنشاء wadq_us_ai_report_df أولًا.")

else:
    # إنشاء نسخة مستقلة دون تعديل التقرير الأصلي
    df = wadq_us_ai_report_df.copy()

    # التأكد من الأعمدة المطلوبة
    required = [
        "الرمز",
        "آخر سعر",
        "المتوسط المتحرك 20",
        "المتوسط المتحرك 50",
        "RSI",
        "عدد_الأخبار",
        "مؤشر المشاعر الإخبارية"
    ]

    missing = [c for c in required if c not in df.columns]

    if missing:
        print("⚠️ أعمدة غير موجودة:", missing)

    else:
        # تحويل القيم الرقمية
        numeric_cols = [
            "آخر سعر",
            "المتوسط المتحرك 20",
            "المتوسط المتحرك 50",
            "RSI",
            "عدد_الأخبار",
            "مؤشر المشاعر الإخبارية"
        ]

        for col in numeric_cols:
            df[col] = pd.to_numeric(df[col], errors="coerce")

        # الدرجة الفنية من 0 إلى 3
        df["الدرجة الفنية"] = (
            (df["آخر سعر"] > df["المتوسط المتحرك 20"]).astype(int)
            + (df["آخر سعر"] > df["المتوسط المتحرك 50"]).astype(int)
            + df["RSI"].between(50, 69.99).astype(int)
        )

        # تصنيف الأخبار
        def classify_news(row):
            n = row["عدد_الأخبار"]
            s = row["مؤشر المشاعر الإخبارية"]

            if pd.isna(n) or n <= 0 or pd.isna(s):
                return "أخبار غير كافية"
            elif s >= 20:
                return "إيجابية مبدئيًا"
            elif s > 0:
                return "إيجابية ضعيفة"
            elif s < 0:
                return "سلبية مبدئيًا"
            else:
                return "محايدة أو غير حاسمة"

        df["تصنيف الأخبار"] = df.apply(classify_news, axis=1)

        # الإشارة المدمجة
        def combined_signal(row):
            price = row["آخر سعر"]
            ma20 = row["المتوسط المتحرك 20"]
            ma50 = row["المتوسط المتحرك 50"]
            rsi = row["RSI"]
            n = row["عدد_الأخبار"]
            sentiment = row["مؤشر المشاعر الإخبارية"]

            if any(pd.isna(x) for x in [price, ma20, ma50, rsi]):
                return "بيانات فنية غير كافية"

            if rsi >= 70:
                return "حذر — مؤشر RSI مرتفع"

            if pd.isna(n) or n <= 0 or pd.isna(sentiment):
                return "انتظار — الأخبار غير كافية"

            if (
                price > ma20
                and price > ma50
                and 50 <= rsi < 70
                and sentiment > 0
            ):
                return "مراقبة إيجابية"

            if (
                price < ma20
                and price < ma50
                and sentiment < 0
            ):
                return "حذر — توافق سلبي"

            return "انتظار — الإشارات غير متوافقة"

        df["الإشارة المدمجة"] = df.apply(combined_signal, axis=1)

        # تفسير موجز
        def explain(row):
            reasons = []

            if row["آخر سعر"] > row["المتوسط المتحرك 20"]:
                reasons.append("السعر فوق متوسط 20")
            else:
                reasons.append("السعر دون متوسط 20")

            if row["آخر سعر"] > row["المتوسط المتحرك 50"]:
                reasons.append("السعر فوق متوسط 50")
            else:
                reasons.append("السعر دون متوسط 50")

            if row["RSI"] >= 70:
                reasons.append("RSI مرتفع ويستدعي الحذر")
            elif row["RSI"] < 50:
                reasons.append("الزخم دون 50")

            reasons.append("الأخبار: " + row["تصنيف الأخبار"])

            return "؛ ".join(reasons)

        df["تفسير الإشارة"] = df.apply(explain, axis=1)

        # حفظ النتيجة في جدول مستقل
        output_cols = [
            "الرمز",
            "آخر سعر",
            "RSI",
            "الدرجة الفنية",
            "عدد_الأخبار",
            "مؤشر المشاعر الإخبارية",
            "تصنيف الأخبار",
            "الإشارة المدمجة",
            "تفسير الإشارة"
        ]

        wadq_us_final_signals_df = (
            df[output_cols]
            .sort_values(
                by=["الدرجة الفنية", "مؤشر المشاعر الإخبارية"],
                ascending=[False, False],
                na_position="last"
            )
            .reset_index(drop=True)
        )

        print("✅ اكتملت خطوة الإشارات المدمجة.")
        print("عدد الأصول:", len(wadq_us_final_signals_df))
        print("\n📊 النتائج:")

        display(wadq_us_final_signals_df)

        print("\nاسم الجدول الجديد:")
        print("wadq_us_final_signals_df")

🌧️ الودق AI — المرحلة 36
=======================================================
✅ اكتملت خطوة الإشارات المدمجة.
عدد الأصول: 9

📊 النتائج:

,الرمز,آخر سعر,RSI,الدرجة الفنية,عدد_الأخبار,مؤشر المشاعر الإخبارية,تصنيف الأخبار,الإشارة المدمجة,تفسير الإشارة
0,META,742.96,51.56,3,2,50.00,إيجابية مبدئيًا,مراقبة إيجابية,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...
1,GOOGL,352.72,51.55,3,20,25.00,إيجابية مبدئيًا,مراقبة إيجابية,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...
2,AMZN,259.53,55.34,3,17,23.53,إيجابية مبدئيًا,مراقبة إيجابية,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...
3,SPY,778.10,55.15,3,50,14.00,إيجابية ضعيفة,مراقبة إيجابية,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...
4,AAPL,340.97,51.30,3,1,0.00,محايدة أو غير حاسمة,انتظار — الإشارات غير متوافقة,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...
5,QQQ,746.04,48.85,2,5,40.00,إيجابية مبدئيًا,انتظار — الإشارات غير متوافقة,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الزخم ...
6,MSFT,541.15,77.88,2,34,17.65,إيجابية ضعيفة,حذر — مؤشر RSI مرتفع,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ RSI مر...
7,TSLA,378.03,49.43,2,20,10.00,إيجابية ضعيفة,انتظار — الإشارات غير متوافقة,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الزخم ...
8,NVDA,226.32,46.37,1,46,17.39,إيجابية ضعيفة,انتظار — الإشارات غير متوافقة,السعر دون متوسط 20؛ السعر فوق متوسط 50؛ الزخم ...

اسم الجدول الجديد:
wadq_us_final_signals_df

In [ ]:
# 🌧️ الودق AI — المرحلة 36
# تقييم كفاية عينة الأخبار

import pandas as pd

print("🌧️ الودق AI — تقييم كفاية الأخبار")
print("=" * 55)

if "wadq_us_final_signals_df" not in globals():
    print("⚠️ جدول الإشارات المدمجة غير موجود.")

elif "wadq_us_ai_report_df" not in globals():
    print("⚠️ التقرير الفني والإخباري الموحد غير موجود.")

else:
    # إنشاء نسخة مستقلة
    wadq_us_news_quality_df = (
        wadq_us_final_signals_df.copy()
    )

    # إضافة عدد الأخبار من التقرير الموحد باستخدام الرمز
    counts = wadq_us_ai_report_df[
        ["الرمز", "عدد_الأخبار"]
    ].copy()

    wadq_us_news_quality_df = (
        wadq_us_news_quality_df.drop(
            columns=["عدد_الأخبار"],
            errors="ignore"
        ).merge(
            counts,
            on="الرمز",
            how="left",
            validate="one_to_one"
        )
    )

    def assess_news_count(n):
        if pd.isna(n) or n == 0:
            return "غير كافية — لا توجد أخبار"
        elif n < 3:
            return "محدودة جدًا"
        elif n < 10:
            return "محدودة"
        else:
            return "عينة أكبر نسبيًا"

    wadq_us_news_quality_df["كفاية عينة الأخبار"] = (
        wadq_us_news_quality_df["عدد_الأخبار"].apply(
            assess_news_count
        )
    )

    print("✅ تم تقييم كفاية عينة الأخبار.")
    print("عدد الأصول:", len(wadq_us_news_quality_df))

    display(
        wadq_us_news_quality_df[
            [
                "الرمز",
                "عدد_الأخبار",
                "مؤشر المشاعر الإخبارية",
                "كفاية عينة الأخبار",
                "الإشارة المدمجة"
            ]
        ]
    )

    print("\nاسم الجدول الجديد:")
    print("wadq_us_news_quality_df")

🌧️ الودق AI — تقييم كفاية الأخبار
=======================================================
✅ تم تقييم كفاية عينة الأخبار.
عدد الأصول: 9

,الرمز,عدد_الأخبار,مؤشر المشاعر الإخبارية,كفاية عينة الأخبار,الإشارة المدمجة
0,META,2,50.00,محدودة جدًا,مراقبة إيجابية
1,GOOGL,20,25.00,عينة أكبر نسبيًا,مراقبة إيجابية
2,AMZN,17,23.53,عينة أكبر نسبيًا,مراقبة إيجابية
3,SPY,50,14.00,عينة أكبر نسبيًا,مراقبة إيجابية
4,AAPL,1,0.00,محدودة جدًا,انتظار — الإشارات غير متوافقة
5,QQQ,5,40.00,محدودة,انتظار — الإشارات غير متوافقة
6,MSFT,34,17.65,عينة أكبر نسبيًا,حذر — مؤشر RSI مرتفع
7,TSLA,20,10.00,عينة أكبر نسبيًا,انتظار — الإشارات غير متوافقة
8,NVDA,46,17.39,عينة أكبر نسبيًا,انتظار — الإشارات غير متوافقة

اسم الجدول الجديد:
wadq_us_news_quality_df

In [ ]:
# 🌧️ الودق AI — المرحلة 36
# إنشاء قائمة أولويات المتابعة

import pandas as pd

print("🌧️ الودق AI — أولويات المتابعة")
print("=" * 55)

if "wadq_us_news_quality_df" not in globals():

    print("⚠️ جدول جودة الأخبار غير موجود.")

else:

    df = wadq_us_news_quality_df.copy()

    def priority(row):
        signal = str(row.get("الإشارة المدمجة", ""))
        quality = str(row.get("كفاية عينة الأخبار", ""))

        if signal == "مراقبة إيجابية":
            if quality == "عينة أكبر نسبيًا":
                return "أولوية متابعة أعلى"

            elif quality == "محدودة":
                return "متابعة بحذر"

            else:
                return "متابعة بحذر شديد"

        elif signal == "حذر — مؤشر RSI مرتفع":
            return "تنبيه فني — مراجعة الزخم"

        elif signal == "حذر — توافق سلبي":
            return "مراجعة المخاطر"

        else:
            return "مراقبة عادية"

    df["أولوية المتابعة"] = df.apply(priority, axis=1)

    # ترتيب النتائج حسب الأولوية
    priority_order = {
        "أولوية متابعة أعلى": 1,
        "تنبيه فني — مراجعة الزخم": 2,
        "متابعة بحذر": 3,
        "متابعة بحذر شديد": 4,
        "مراجعة المخاطر": 5,
        "مراقبة عادية": 6
    }

    df["_ترتيب"] = df["أولوية المتابعة"].map(priority_order)

    df = (
        df.sort_values("_ترتيب")
        .drop(columns="_ترتيب")
        .reset_index(drop=True)
    )

    wadq_us_priority_df = df.copy()

    print("✅ تم إنشاء قائمة أولويات المتابعة.")
    print("عدد الأصول:", len(wadq_us_priority_df))

    display(
        wadq_us_priority_df[
            [
                "الرمز",
                "الإشارة المدمجة",
                "عدد_الأخبار",
                "كفاية عينة الأخبار",
                "أولوية المتابعة"
            ]
        ]
    )

    print("\nاسم الجدول الجديد:")
    print("wadq_us_priority_df")

🌧️ الودق AI — أولويات المتابعة
=======================================================
✅ تم إنشاء قائمة أولويات المتابعة.
عدد الأصول: 9

,الرمز,الإشارة المدمجة,عدد_الأخبار,كفاية عينة الأخبار,أولوية المتابعة
0,GOOGL,مراقبة إيجابية,20,عينة أكبر نسبيًا,أولوية متابعة أعلى
1,AMZN,مراقبة إيجابية,17,عينة أكبر نسبيًا,أولوية متابعة أعلى
2,SPY,مراقبة إيجابية,50,عينة أكبر نسبيًا,أولوية متابعة أعلى
3,MSFT,حذر — مؤشر RSI مرتفع,34,عينة أكبر نسبيًا,تنبيه فني — مراجعة الزخم
4,META,مراقبة إيجابية,2,محدودة جدًا,متابعة بحذر شديد
5,AAPL,انتظار — الإشارات غير متوافقة,1,محدودة جدًا,مراقبة عادية
6,QQQ,انتظار — الإشارات غير متوافقة,5,محدودة,مراقبة عادية
7,TSLA,انتظار — الإشارات غير متوافقة,20,عينة أكبر نسبيًا,مراقبة عادية
8,NVDA,انتظار — الإشارات غير متوافقة,46,عينة أكبر نسبيًا,مراقبة عادية

اسم الجدول الجديد:
wadq_us_priority_df

In [ ]:
# 🌧️ الودق AI — المرحلة 37
# إنشاء لوحة المتابعة الموحدة للأصول الأمريكية

import pandas as pd

print("🌧️ الودق AI — المرحلة 37")
print("=" * 60)

# التحقق من وجود الجداول السابقة
required_tables = [
    "wadq_us_ai_report_df",
    "wadq_us_final_signals_df",
    "wadq_us_priority_df"
]

missing_tables = [
    name for name in required_tables
    if name not in globals()
]

if missing_tables:

    print("⚠️ الجداول التالية غير موجودة:")
    print(missing_tables)
    print("لن يتم إنشاء اللوحة حتى تتوفر الجداول المطلوبة.")

else:

    # نسخ مستقلة لحماية الجداول السابقة
    report_df = wadq_us_ai_report_df.copy()
    signals_df = wadq_us_final_signals_df.copy()
    priority_df = wadq_us_priority_df.copy()

    # اختيار الأعمدة الأساسية المتاحة
    report_cols = [
        c for c in [
            "الرمز",
            "آخر سعر",
            "تاريخ آخر جلسة",
            "الاتجاه الفني",
            "الإشارة الأولية",
            "RSI",
            "عدد_الأخبار",
            "مؤشر المشاعر الإخبارية"
        ]
        if c in report_df.columns
    ]

    signals_cols = [
        c for c in [
            "الرمز",
            "الدرجة الفنية",
            "تصنيف الأخبار",
            "الإشارة المدمجة",
            "تفسير الإشارة"
        ]
        if c in signals_df.columns
    ]

    priority_cols = [
        c for c in [
            "الرمز",
            "كفاية عينة الأخبار",
            "أولوية المتابعة"
        ]
        if c in priority_df.columns
    ]

    # دمج الجداول باستخدام رمز الأصل
    wadq_us_monitoring_df = report_df[report_cols].copy()

    if len(signals_cols) > 1:
        wadq_us_monitoring_df = wadq_us_monitoring_df.merge(
            signals_df[signals_cols],
            on="الرمز",
            how="left",
            validate="one_to_one",
            suffixes=("", "_إشارات")
        )

    if len(priority_cols) > 1:
        wadq_us_monitoring_df = wadq_us_monitoring_df.merge(
            priority_df[priority_cols],
            on="الرمز",
            how="left",
            validate="one_to_one",
            suffixes=("", "_متابعة")
        )

    # ترتيب حسب أولوية المتابعة
    priority_order = {
        "أولوية متابعة أعلى": 1,
        "تنبيه فني — مراجعة الزخم": 2,
        "متابعة بحذر": 3,
        "متابعة بحذر شديد": 4,
        "مراجعة المخاطر": 5,
        "مراقبة عادية": 6
    }

    if "أولوية المتابعة" in wadq_us_monitoring_df.columns:

        wadq_us_monitoring_df["_ترتيب"] = (
            wadq_us_monitoring_df["أولوية المتابعة"]
            .map(priority_order)
            .fillna(99)
        )

        wadq_us_monitoring_df = (
            wadq_us_monitoring_df
            .sort_values("_ترتيب")
            .drop(columns="_ترتيب")
            .reset_index(drop=True)
        )

    # ملخص عدد الأصول حسب الأولوية
    if "أولوية المتابعة" in wadq_us_monitoring_df.columns:

        wadq_us_monitoring_summary_df = (
            wadq_us_monitoring_df["أولوية المتابعة"]
            .value_counts(dropna=False)
            .rename_axis("أولوية المتابعة")
            .reset_index(name="عدد الأصول")
        )

    print("✅ تم إنشاء لوحة المتابعة الموحدة.")
    print("عدد الأصول:", len(wadq_us_monitoring_df))
    print("عدد الأعمدة:", len(wadq_us_monitoring_df.columns))

    print("\n📊 لوحة المتابعة:")
    display(wadq_us_monitoring_df)

    if "wadq_us_monitoring_summary_df" in globals():
        print("\n📈 ملخص أولويات المتابعة:")
        display(wadq_us_monitoring_summary_df)

    print("\nأسماء الجداول الجديدة:")
    print("wadq_us_monitoring_df")
    print("wadq_us_monitoring_summary_df")

🌧️ الودق AI — المرحلة 37
============================================================
✅ تم إنشاء لوحة المتابعة الموحدة.
عدد الأصول: 9
عدد الأعمدة: 14

📊 لوحة المتابعة:

,الرمز,آخر سعر,تاريخ آخر جلسة,الاتجاه الفني,الإشارة الأولية,RSI,عدد_الأخبار,مؤشر المشاعر الإخبارية,الدرجة الفنية,تصنيف الأخبار,الإشارة المدمجة,تفسير الإشارة,كفاية عينة الأخبار,أولوية المتابعة
0,GOOGL,352.72,2026-10-12,صاعد,إيجابية مبدئية,51.55,20,25.00,3,إيجابية مبدئيًا,مراقبة إيجابية,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...,عينة أكبر نسبيًا,أولوية متابعة أعلى
1,AMZN,259.53,2026-10-12,متذبذب,انتظار,55.34,17,23.53,3,إيجابية مبدئيًا,مراقبة إيجابية,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...,عينة أكبر نسبيًا,أولوية متابعة أعلى
2,SPY,778.10,2026-10-12,صاعد,إيجابية مبدئية,55.15,50,14.00,3,إيجابية ضعيفة,مراقبة إيجابية,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...,عينة أكبر نسبيًا,أولوية متابعة أعلى
3,MSFT,541.15,2026-10-12,صاعد,انتظار,77.88,34,17.65,2,إيجابية ضعيفة,حذر — مؤشر RSI مرتفع,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ RSI مر...,عينة أكبر نسبيًا,تنبيه فني — مراجعة الزخم
4,META,742.96,2026-10-12,صاعد,إيجابية مبدئية,51.56,2,50.00,3,إيجابية مبدئيًا,مراقبة إيجابية,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...,محدودة جدًا,متابعة بحذر شديد
5,AAPL,340.97,2026-10-12,صاعد,إيجابية مبدئية,51.30,1,0.00,3,محايدة أو غير حاسمة,انتظار — الإشارات غير متوافقة,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الأخبا...,محدودة جدًا,مراقبة عادية
6,NVDA,226.32,2026-10-12,متذبذب,انتظار,46.37,46,17.39,1,إيجابية ضعيفة,انتظار — الإشارات غير متوافقة,السعر دون متوسط 20؛ السعر فوق متوسط 50؛ الزخم ...,عينة أكبر نسبيًا,مراقبة عادية
7,TSLA,378.03,2026-10-12,صاعد,انتظار,49.43,20,10.00,2,إيجابية ضعيفة,انتظار — الإشارات غير متوافقة,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الزخم ...,عينة أكبر نسبيًا,مراقبة عادية
8,QQQ,746.04,2026-10-12,صاعد,انتظار,48.85,5,40.00,2,إيجابية مبدئيًا,انتظار — الإشارات غير متوافقة,السعر فوق متوسط 20؛ السعر فوق متوسط 50؛ الزخم ...,محدودة,مراقبة عادية

📈 ملخص أولويات المتابعة:

            أولوية المتابعة  عدد الأصول
0              مراقبة عادية           4
1        أولوية متابعة أعلى           3
2  تنبيه فني — مراجعة الزخم           1
3          متابعة بحذر شديد           1

أسماء الجداول الجديدة:
wadq_us_monitoring_df
wadq_us_monitoring_summary_df

In [ ]:
# 🌧️ الودق AI — المرحلة 38
# فحص جداول الأسواق السعودية والأمريكية والعالمية

import pandas as pd

print("🌧️ الودق AI — فحص جداول الأسواق")
print("=" * 60)

keywords = [
    "saudi", "ksa", "tadawul", "السعودية", "السعودي",
    "global", "world", "global_alerts", "العالمي",
    "us_", "usa", "american", "أمريكي",
    "technical", "master_report", "alerts"
]

found = []

for name, obj in list(globals().items()):

    if isinstance(obj, pd.DataFrame):

        if any(word in name.lower() for word in keywords):

            found.append(name)

            print(f"\n📊 اسم الجدول: {name}")
            print("عدد الصفوف:", len(obj))
            print("عدد الأعمدة:", len(obj.columns))
            print("الأعمدة:", obj.columns.tolist())

print("\n" + "=" * 60)

if found:
    print("✅ عدد الجداول المكتشفة:", len(found))
else:
    print("لم يُعثر على جداول مطابقة في الجلسة الحالية.")

print("\nانتهى الفحص دون تعديل أي جدول.")

🌧️ الودق AI — فحص جداول الأسواق
============================================================

📊 اسم الجدول: wadq_global_market_df
عدد الصفوف: 17
عدد الأعمدة: 6
الأعمدة: ['الرمز', 'الأصل', 'أحدث سعر متاح', 'السعر السابق', 'التغير اليومي %', 'تاريخ آخر بيانات']

============================================================
✅ عدد الجداول المكتشفة: 1

انتهى الفحص دون تعديل أي جدول.

In [ ]:
# =====================================================
# 🌧️ الودق AI — فحص الجداول لاستعادة المرحلة 41
# دون تعديل الجداول الأصلية
# =====================================================

import pandas as pd

print("🌧️ الودق AI — فحص البيانات")
print("=" * 60)

# الجداول المهمة لاستعادة المرحلة 41
required_tables = [
    "global_df",
    "us_df",
    "wadq_global_us_unified_df",
    "wadq_executive_summary_df",
    "wadq_global_master_report_df",
    "wadq_global_master_report_v3_df",
    "wadq_stage41_decision_df",
]

found_count = 0

for name in required_tables:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        found_count += 1
        print(f"\n✅ الجدول: {name}")
        print(f"   عدد الصفوف: {len(obj)}")
        print(f"   عدد الأعمدة: {len(obj.columns)}")
        print(f"   أسماء الأعمدة: {list(obj.columns)}")
    else:
        print(f"\n⚠️ الجدول غير موجود في الذاكرة: {name}")

print("\n" + "=" * 60)
print(f"📊 عدد الجداول المتاحة من القائمة: {found_count}")
print("🔎 انتهى الفحص — لم يتم تعديل أي جدول.")

🌧️ الودق AI — فحص البيانات
============================================================

⚠️ الجدول غير موجود في الذاكرة: global_df

⚠️ الجدول غير موجود في الذاكرة: us_df

⚠️ الجدول غير موجود في الذاكرة: wadq_global_us_unified_df

⚠️ الجدول غير موجود في الذاكرة: wadq_executive_summary_df

⚠️ الجدول غير موجود في الذاكرة: wadq_global_master_report_df

⚠️ الجدول غير موجود في الذاكرة: wadq_global_master_report_v3_df

⚠️ الجدول غير موجود في الذاكرة: wadq_stage41_decision_df

============================================================
📊 عدد الجداول المتاحة من القائمة: 0
🔎 انتهى الفحص — لم يتم تعديل أي جدول.

In [ ]:
# 🌧️ الودق AI — المرحلة 38
# إنشاء لوحة موحدة للأسواق العالمية والأمريكية
# دون تعديل الجداول السابقة

import pandas as pd

print("🌧️ الودق AI — المرحلة 38")
print("=" * 60)

# التحقق من الجداول المطلوبة
required_tables = [
    "wadq_global_master_report_v3_df",
    "wadq_us_monitoring_df"
]

missing = [
    name for name in required_tables
    if name not in globals()
]

if missing:
    print("⚠️ الجداول التالية غير موجودة:")
    print(missing)

else:
    # نسخ مستقلة لحماية البيانات الأصلية
    global_df = wadq_global_master_report_v3_df.copy()
    us_df = wadq_us_monitoring_df.copy()

    # توحيد الرموز
    global_df["الرمز"] = (
        global_df["الرمز"].astype(str).str.upper().str.strip()
    )

    us_df["الرمز"] = (
        us_df["الرمز"].astype(str).str.upper().str.strip()
    )

    # اختيار بيانات الأسهم الأمريكية التي نريد إضافتها
    us_columns = [
        "الرمز",
        "الإشارة المدمجة",
        "أولوية المتابعة",
        "كفاية عينة الأخبار",
        "مؤشر المشاعر الإخبارية"
    ]

    available_us_columns = [
        col for col in us_columns
        if col in us_df.columns
    ]

    us_lookup = us_df[available_us_columns].copy()

    # تجنب تكرار الأعمدة الموجودة في التقرير العالمي
    columns_to_add = [
        col for col in available_us_columns
        if col == "الرمز" or col not in global_df.columns
    ]

    us_lookup = us_lookup[columns_to_add]

    # دمج بيانات المتابعة الأمريكية حسب الرمز
    wadq_global_us_unified_df = global_df.merge(
        us_lookup,
        on="الرمز",
        how="left",
        validate="one_to_one"
    )

    # تحديد ما إذا كانت بيانات المتابعة الأمريكية متاحة
    if "الإشارة المدمجة" in wadq_global_us_unified_df.columns:
        wadq_global_us_unified_df["حالة بيانات المتابعة"] = (
            wadq_global_us_unified_df["الإشارة المدمجة"]
            .notna()
            .map({
                True: "بيانات متابعة أمريكية متاحة",
                False: "لا توجد مطابقة في لوحة المتابعة الأمريكية"
            })
        )

    print("✅ تم إنشاء اللوحة الموحدة.")
    print("عدد الأصول:", len(wadq_global_us_unified_df))
    print("عدد الأعمدة:", len(wadq_global_us_unified_df.columns))

    print("\n📊 معاينة اللوحة الموحدة:")
    display(wadq_global_us_unified_df)

    print("\nاسم الجدول الجديد:")
    print("wadq_global_us_unified_df")

🌧️ الودق AI — المرحلة 38
============================================================
⚠️ الجداول التالية غير موجودة:
['wadq_global_master_report_v3_df', 'wadq_us_monitoring_df']

In [ ]:
# 🌧️ الودق AI — التحقق النهائي من المرحلة 38

print("🌧️ الودق AI — فحص اللوحة الموحدة")
print("=" * 50)

print("عدد الأصول:", len(wadq_global_us_unified_df))
print("عدد الأعمدة:", len(wadq_global_us_unified_df.columns))

print("\nحالة بيانات المتابعة:")
print(
    wadq_global_us_unified_df["حالة بيانات المتابعة"]
    .value_counts(dropna=False)
)

print("\nالأصول المرتبطة بالمتابعة الأمريكية:")
display(
    wadq_global_us_unified_df.loc[
        wadq_global_us_unified_df["حالة بيانات المتابعة"]
        == "بيانات متابعة أمريكية متاحة",
        ["الأصل", "الرمز", "الإشارة المدمجة", "أولوية المتابعة"]
    ]
)

print("\nاسم الجدول:")
print("wadq_global_us_unified_df")

🌧️ الودق AI — فحص اللوحة الموحدة
==================================================
عدد الأصول: 26
عدد الأعمدة: 25

حالة بيانات المتابعة:
حالة بيانات المتابعة
لا توجد مطابقة في لوحة المتابعة الأمريكية    17
بيانات متابعة أمريكية متاحة                   9
Name: count, dtype: int64

الأصول المرتبطة بالمتابعة الأمريكية:

,الأصل,الرمز,الإشارة المدمجة,أولوية المتابعة
17,إنفيديا,NVDA,انتظار — الإشارات غير متوافقة,مراقبة عادية
18,تسلا,TSLA,انتظار — الإشارات غير متوافقة,مراقبة عادية
19,آبل,AAPL,انتظار — الإشارات غير متوافقة,مراقبة عادية
20,مايكروسوفت,MSFT,حذر — مؤشر RSI مرتفع,تنبيه فني — مراجعة الزخم
21,أمازون,AMZN,مراقبة إيجابية,أولوية متابعة أعلى
22,ألفابت,GOOGL,مراقبة إيجابية,أولوية متابعة أعلى
23,ميتا,META,مراقبة إيجابية,متابعة بحذر شديد
24,ناسداك 100,QQQ,انتظار — الإشارات غير متوافقة,مراقبة عادية
25,ستاندرد آند بورز 500,SPY,مراقبة إيجابية,أولوية متابعة أعلى

اسم الجدول:
wadq_global_us_unified_df

In [ ]:
# 🌧️ الودق AI — فحص الجداول المصدرية
import pandas as pd

print("🌧️ فحص الجداول المطلوبة لاستعادة المرحلة 40")
print("=" * 55)

for name in ["global_df", "us_df"]:
    obj = globals().get(name)

    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name} موجود")
        print("عدد الصفوف:", len(obj))
        print("عدد الأعمدة:", len(obj.columns))
        print("الأعمدة:", list(obj.columns))
    else:
        print(f"⚠️ {name} غير موجود في الذاكرة الحالية")

print("=" * 55)
print("انتهى الفحص دون تعديل أي جدول.")

🌧️ فحص الجداول المطلوبة لاستعادة المرحلة 40
=======================================================
⚠️ global_df غير موجود في الذاكرة الحالية
⚠️ us_df غير موجود في الذاكرة الحالية
=======================================================
انتهى الفحص دون تعديل أي جدول.

In [ ]:
# =========================================================
# 🌧️ الودق AI — البحث عن مصادر بيانات المرحلة 40
# فحص فقط دون تعديل أو حذف أي بيانات
# =========================================================

import pandas as pd

print("🌧️ الودق AI — البحث عن جداول المرحلة 40")
print("=" * 60)

keywords = [
    "global_df",
    "us_df",
    "global",
    "us_technical_df",
    "technical_df",
    "market",
    "news",
    "unified"
]

found = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        if any(word in name.lower() for word in keywords):
            found.append((name, len(obj), len(obj.columns)))

if found:
    print("✅ الجداول التي عُثر عليها:")
    for name, rows, cols in found:
        print(f"📊 {name} | الصفوف: {rows} | الأعمدة: {cols}")
else:
    print("⚠️ لم يُعثر على جداول مطابقة في الذاكرة الحالية.")

print("=" * 60)
print("انتهى الفحص دون تعديل الجداول.")

🌧️ الودق AI — البحث عن جداول المرحلة 40
============================================================
⚠️ لم يُعثر على جداول مطابقة في الذاكرة الحالية.
============================================================
انتهى الفحص دون تعديل الجداول.

In [ ]:
print("🌧️ فحص جداول الودق AI")
print("=" * 45)

tables = [
    "wadq_global_master_report_df",
    "wadq_global_master_report_v2_df",
    "wadq_global_master_report_v3_df",
    "us_technical_df",
    "wadq_us_monitoring_df",
    "wadq_global_us_unified_df",
    "wadq_global_priority_df"
]

for name in tables:
    obj = globals().get(name)
    if isinstance(obj, pd.DataFrame):
        print(f"✅ {name}: {len(obj)} صف، {len(obj.columns)} عمود")
    else:
        print(f"⚠️ {name}: غير موجود في الذاكرة")

🌧️ فحص جداول الودق AI
=============================================
⚠️ wadq_global_master_report_df: غير موجود في الذاكرة
⚠️ wadq_global_master_report_v2_df: غير موجود في الذاكرة
⚠️ wadq_global_master_report_v3_df: غير موجود في الذاكرة
⚠️ us_technical_df: غير موجود في الذاكرة
⚠️ wadq_us_monitoring_df: غير موجود في الذاكرة
⚠️ wadq_global_us_unified_df: غير موجود في الذاكرة
⚠️ wadq_global_priority_df: غير موجود في الذاكرة

In [33]:
# =========================================================
# 🌧️ الودق AI — حفظ احتياطي للجداول والتقارير
# يحفظ الجداول الموجودة في ذاكرة Colab داخل Google Drive
# =========================================================

import os
import pandas as pd
from datetime import datetime
from google.colab import drive

# الاتصال بـ Google Drive
drive.mount('/content/drive')

# إنشاء مجلد نسخة احتياطية مستقل
backup_root = "/content/drive/MyDrive/نسخ احتياطية الودق AI"
os.makedirs(backup_root, exist_ok=True)

# مجلد بتاريخ ووقت الحفظ حتى لا نستبدل نسخة سابقة
backup_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
backup_folder = os.path.join(backup_root, backup_time)
os.makedirs(backup_folder, exist_ok=True)

# البحث عن جميع الجداول الموجودة في ذاكرة Colab
saved_tables = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        try:
            # حفظ الجدول بصيغة CSV
            csv_path = os.path.join(backup_folder, f"{name}.csv")
            obj.to_csv(csv_path, index=False, encoding="utf-8-sig")

            # حفظ نسخة تحافظ على بنية الجدول وأنواع البيانات
            pickle_path = os.path.join(backup_folder, f"{name}.pkl")
            obj.to_pickle(pickle_path)

            saved_tables.append(name)
            print(f"✅ تم حفظ: {name} | {obj.shape}")

        except Exception as e:
            print(f"⚠️ تعذر حفظ {name}: {e}")

# حفظ قائمة بأسماء الجداول
with open(
    os.path.join(backup_folder, "قائمة_الجداول.txt"),
    "w",
    encoding="utf-8"
) as f:
    f.write("الجداول المحفوظة في نسخة الودق AI\n")
    f.write(f"تاريخ الحفظ: {backup_time}\n\n")
    for name in saved_tables:
        f.write(name + "\n")

print("\n" + "=" * 50)
print("🌧️ انتهى الحفظ الاحتياطي")
print("عدد الجداول المحفوظة:", len(saved_tables))
print("مجلد النسخة الاحتياطية:")
print(backup_folder)
print("=" * 50)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ تم حفظ: df | (52, 16)
✅ تم حفظ: wadq_price_df | (26, 9)
✅ تم حفظ: wadq_technical_df | (26, 10)
✅ تم حفظ: wadq_evaluation_df | (26, 9)
✅ تم حفظ: wadq_risk_df | (26, 9)
✅ تم حفظ: wadq_final_ai_report | (26, 17)
✅ تم حفظ: wadq_decision_board_df | (26, 9)
✅ تم حفظ: wadq_quality_df | (26, 5)
✅ تم حفظ: wadq_global_master_report_df | (14, 17)
✅ تم حفظ: wadq_saudi_report_df | (3, 17)
✅ تم حفظ: wadq76_report | (41, 20)
✅ تم حفظ: wadq77_trade_plan | (41, 11)
✅ تم حفظ: wadq_85C_trades | (612, 13)
✅ تم حفظ: wadq_85C_daily | (2067, 8)
✅ تم حفظ: wadq_85C_summary | (1, 9)
✅ تم حفظ: core_check_df | (9, 5)
✅ تم حفظ: trades | (612, 13)
✅ تم حفظ: final_report | (26, 17)
✅ تم حفظ: df_source | (26, 9)
✅ تم حفظ: raw_data | (307, 111)
✅ تم حفظ: wadq_phase87_df | (21, 27)
✅ تم حفظ: wadq_phase87_opportunities_df | (2, 27)
✅ تم حفظ: wadq_phase87_watchlist_df | (1, 27)
✅ تم حفظ: wadq_phase87_avoid_df | (18, 27)
✅ تم حفظ: wadq_phase87_summary_df | (1, 9)

==================================================
🌧️ انتهى الحفظ الاحتياطي
عدد الجداول المحفوظة: 25
مجلد النسخة الاحتياطية:
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14
==================================================

In [1]:
# =========================================================
# 🌧️ الودق AI — فحص جميع الجداول المحفوظة في الذاكرة
# =========================================================

import pandas as pd
import os

print("=" * 65)
print("🌧️ الودق AI — فحص الجداول")
print("=" * 65)

# فحص جميع الجداول الموجودة في ذاكرة Colab
tables = {
    name: obj
    for name, obj in globals().items()
    if isinstance(obj, pd.DataFrame)
}

if tables:
    print(f"\n✅ عدد الجداول الموجودة في الذاكرة: {len(tables)}")

    for name, df in sorted(tables.items()):
        print("-" * 65)
        print(f"📊 اسم الجدول: {name}")
        print(f"عدد الصفوف: {len(df)}")
        print(f"عدد الأعمدة: {len(df.columns)}")
        print(f"الأعمدة: {list(df.columns)}")

else:
    print("\n⚠️ لم يتم العثور على جداول DataFrame في الذاكرة الحالية.")

# فحص وجود نسخة احتياطية في Google Drive
backup_path = "/content/drive/MyDrive/الودق AI"

print("\n" + "=" * 65)
print("📁 فحص النسخ الاحتياطية في Google Drive")
print("=" * 65)

if os.path.exists("/content/drive/MyDrive"):
    print("✅ Google Drive متصل")

    if os.path.exists(backup_path):
        print(f"✅ مجلد المشروع موجود: {backup_path}")

        for root, dirs, files in os.walk(backup_path):
            for file in files:
                if file.endswith((".csv", ".pkl", ".parquet")):
                    print("📄", os.path.join(root, file))
    else:
        print("⚠️ لم يتم العثور على مجلد بهذا الاسم.")
        print("قد تكون النسخة الاحتياطية في مجلد آخر.")

else:
    print("⚠️ Google Drive غير متصل حاليًا.")v

SyntaxError: invalid syntax (643673322.py, line 54)

In [4]:
import os

base_path = "/content/drive/MyDrive"

print("🌧️ الودق AI — تحديد مجلد النسخة الاحتياطية")
print("=" * 50)

for root, dirs, files in os.walk(base_path):
    if "20261017" in root:
        print("\n📁 المجلد:", root)

        for file in files:
            if file.endswith((".csv", ".xlsx", ".pkl")):
                print("📄", file)

🌧️ الودق AI — تحديد مجلد النسخة الاحتياطية
==================================================

📁 المجلد: /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449
📄 wadq_ai_final_report.xlsx
📄 wadq_price_df.csv
📄 wadq_technical_df.csv
📄 wadq_evaluation_df.csv
📄 wadq_risk_df.csv
📄 wadq_final_ai_report.csv
📄 wadq_decision_board_df.csv
📄 wadq_quality_df.csv
📄 wadq_global_master_report_df.csv
📄 wadq_saudi_report_df.csv

In [5]:
# ==========================================================
# 🌧️ الودق AI — فحص الجداول والملفات المحفوظة
# لا يحذف أو يعدل أي جدول
# ==========================================================

import os
import pandas as pd

print("🌧️ فحص مشروع الودق AI")
print("=" * 50)

# أولاً: فحص الجداول الموجودة في ذاكرة كولاب
tables = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        tables.append((name, obj))

if tables:
    print(f"\n✅ عدد الجداول الموجودة في الذاكرة: {len(tables)}")

    for name, df in tables:
        print(f"\n📊 {name}")
        print(f"عدد الصفوف: {df.shape[0]}")
        print(f"عدد الأعمدة: {df.shape[1]}")
else:
    print("\n⚠️ لا توجد جداول DataFrame في الذاكرة الحالية.")

# ثانياً: فحص ملفات Google Drive
base_path = "/content/drive/MyDrive"

if os.path.exists(base_path):
    print("\n" + "=" * 50)
    print("📁 فحص ملفات المشروع في Google Drive")

    found = 0

    for root, dirs, files in os.walk(base_path):
        for file in files:
            if file.endswith((".csv", ".xlsx", ".parquet", ".pkl")):
                if "الودق" in root or "wadq" in file.lower():
                    print(os.path.join(root, file))
                    found += 1

    print(f"\n✅ عدد الملفات التي عثرنا عليها: {found}")

else:
    print("\n⚠️ Google Drive غير متصل.")

🌧️ فحص مشروع الودق AI
==================================================

⚠️ لا توجد جداول DataFrame في الذاكرة الحالية.

==================================================
📁 فحص ملفات المشروع في Google Drive
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_الجداول_المستعادة.xlsx
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_68.xlsx
/content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_69.xlsx
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_ai_final_report.xlsx
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_price_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_technical_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_evaluation_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_risk_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_final_ai_report.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_decision_board_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_quality_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_global_master_report_df.csv
/content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_saudi_report_df.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.xlsx
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.xlsx
/content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_trades_20261017_213918.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_daily_20261017_213918.csv
/content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_summary_20261017_213918.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_price_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_price_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_technical_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_technical_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_evaluation_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_evaluation_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_risk_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_risk_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_final_ai_report.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_final_ai_report.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_decision_board_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_decision_board_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_quality_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_quality_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_global_master_report_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_global_master_report_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_saudi_report_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_saudi_report_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq76_report.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq76_report.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq77_trade_plan.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq77_trade_plan.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_trades.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_trades.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_daily.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_daily.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_summary.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_summary.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/core_check_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/core_check_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/trades.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/trades.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/final_report.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/final_report.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/df_source.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/df_source.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/raw_data.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/raw_data.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_opportunities_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_opportunities_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_watchlist_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_watchlist_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_avoid_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_avoid_df.pkl
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_summary_df.csv
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_summary_df.pkl

✅ عدد الملفات التي عثرنا عليها: 70

In [6]:
# ============================================================
# 🌧️ الودق AI — استعادة مباشرة لجميع الجداول المطلوبة
# استعادة من النسخة الاحتياطية بتاريخ 2026-10-18
# ============================================================

import os
import pandas as pd
from google.colab import drive

# 1. الاتصال بـ Google Drive
if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")

# 2. تحديد النسخة الاحتياطية
BACKUP_PATH = (
    "/content/drive/MyDrive/نسخ احتياطية الودق AI/"
    "2026-10-18_22-06-14"
)

if not os.path.exists(BACKUP_PATH):
    raise FileNotFoundError(
        "❌ لم يتم العثور على النسخة الاحتياطية."
    )

# 3. أسماء الجداول المطلوبة
TABLES = [
    "df",
    "df_source",
    "raw_data",
    "wadq_price_df",
    "wadq_technical_df",
    "wadq_evaluation_df",
    "wadq_risk_df",
    "wadq_final_ai_report",
    "wadq_decision_board_df",
    "wadq_quality_df",
    "wadq_global_master_report_df",
    "wadq_saudi_report_df",
    "wadq76_report",
    "wadq77_trade_plan",
    "wadq_85C_trades",
    "wadq_85C_daily",
    "wadq_85C_summary",
    "core_check_df",
    "trades",
    "final_report",
    "wadq_phase87_df",
    "wadq_phase87_opportunities_df",
    "wadq_phase87_watchlist_df",
    "wadq_phase87_avoid_df",
    "wadq_phase87_summary_df"
]

# 4. استعادة الجداول
restored = []
missing = []
errors = []

for name in TABLES:

    pkl_path = os.path.join(BACKUP_PATH, name + ".pkl")
    csv_path = os.path.join(BACKUP_PATH, name + ".csv")

    try:

        if os.path.exists(pkl_path):
            df = pd.read_pickle(pkl_path)

        elif os.path.exists(csv_path):
            df = pd.read_csv(csv_path)

        else:
            missing.append(name)
            continue

        # وضع الجدول في ذاكرة كولاب
        globals()[name] = df

        restored.append(name)

    except Exception as e:
        errors.append((name, str(e)))

# 5. عرض نتيجة الاستعادة
print("\n" + "=" * 60)
print("🌧️ الودق AI — نتيجة استعادة الجداول")
print("=" * 60)

print(f"\n✅ عدد الجداول المستعادة: {len(restored)}")

for name in restored:
    df = globals()[name]
    print(f"📊 {name}: {df.shape[0]} صف × {df.shape[1]} عمود")

if missing:
    print("\n⚠️ جداول غير موجودة في النسخة الاحتياطية:")
    for name in missing:
        print(name)

if errors:
    print("\n⚠️ جداول تعذر استعادتها:")
    for name, error in errors:
        print(f"{name}: {error}")

print("\n" + "=" * 60)

if "wadq_phase87_df" in restored:
    print("✅ تم استعادة جدول المرحلة 87 الرئيسي.")

if "wadq_phase87_opportunities_df" in restored:
    print("✅ تم استعادة جدول فرص التداول.")

if "wadq_phase87_watchlist_df" in restored:
    print("✅ تم استعادة قائمة المراقبة.")

if "wadq_phase87_avoid_df" in restored:
    print("✅ تم استعادة قائمة تجنب التداول.")

print("\n🌧️ انتهت الاستعادة.")
print("لم يتم تنفيذ أي شراء أو بيع.")

============================================================
🌧️ الودق AI — نتيجة استعادة الجداول
============================================================

✅ عدد الجداول المستعادة: 25
📊 df: 1 صف × 9 عمود
📊 df_source: 26 صف × 9 عمود
📊 raw_data: 307 صف × 111 عمود
📊 wadq_price_df: 26 صف × 9 عمود
📊 wadq_technical_df: 26 صف × 10 عمود
📊 wadq_evaluation_df: 26 صف × 9 عمود
📊 wadq_risk_df: 26 صف × 9 عمود
📊 wadq_final_ai_report: 26 صف × 17 عمود
📊 wadq_decision_board_df: 26 صف × 9 عمود
📊 wadq_quality_df: 26 صف × 5 عمود
📊 wadq_global_master_report_df: 14 صف × 17 عمود
📊 wadq_saudi_report_df: 3 صف × 17 عمود
📊 wadq76_report: 41 صف × 20 عمود
📊 wadq77_trade_plan: 41 صف × 11 عمود
📊 wadq_85C_trades: 612 صف × 13 عمود
📊 wadq_85C_daily: 2067 صف × 8 عمود
📊 wadq_85C_summary: 1 صف × 9 عمود
📊 core_check_df: 9 صف × 5 عمود
📊 trades: 612 صف × 13 عمود
📊 final_report: 26 صف × 17 عمود
📊 wadq_phase87_df: 21 صف × 27 عمود
📊 wadq_phase87_opportunities_df: 2 صف × 27 عمود
📊 wadq_phase87_watchlist_df: 1 صف × 27 عمود
📊 wadq_phase87_avoid_df: 18 صف × 27 عمود
📊 wadq_phase87_summary_df: 1 صف × 9 عمود

============================================================
✅ تم استعادة جدول المرحلة 87 الرئيسي.
✅ تم استعادة جدول فرص التداول.
✅ تم استعادة قائمة المراقبة.
✅ تم استعادة قائمة تجنب التداول.

🌧️ انتهت الاستعادة.
لم يتم تنفيذ أي شراء أو بيع.

In [7]:
# ==========================================================
# 🌧️ الودق AI — مراجعة نتائج المرحلة 87
# ==========================================================

print("=" * 60)
print("🌧️ الودق AI — تقرير المرحلة 87")
print("=" * 60)

# التقرير الرئيسي
if "wadq_phase87_df" in globals():
    print("\n📊 التقرير الرئيسي:")
    display(wadq_phase87_df)

# فرص التداول
if "wadq_phase87_opportunities_df" in globals():
    print("\n🎯 فرص التداول:")
    display(wadq_phase87_opportunities_df)

# قائمة المراقبة
if "wadq_phase87_watchlist_df" in globals():
    print("\n👀 قائمة المراقبة:")
    display(wadq_phase87_watchlist_df)

# قائمة تجنب التداول
if "wadq_phase87_avoid_df" in globals():
    print("\n⚠️ قائمة تجنب التداول:")
    display(wadq_phase87_avoid_df)

# الملخص
if "wadq_phase87_summary_df" in globals():
    print("\n📋 ملخص المرحلة:")
    display(wadq_phase87_summary_df)

============================================================
🌧️ الودق AI — تقرير المرحلة 87
============================================================

📊 التقرير الرئيسي:

,ticker,market,latest_close,latest_date,data_age_days,data_fresh,daily_change_pct,RSI14,SMA20,SMA50,...,stop_loss,target1,target2,quantity_before_portfolio_limit,position_value_sar,risk_sar,currency_rate,recommended_quantity,recommended_position_sar,recommended_risk_sar
0,AAPL,السوق الأمريكي,343.460,2026-10-16,2,True,0.43,62.08,337.4240,325.6940,...,330.0800,356.8400,363.5300,1,1287.97,50.18,3.75,1,1287.97,50.17
1,MSFT,السوق الأمريكي,529.050,2026-10-16,2,True,-1.93,57.36,520.2205,505.3655,...,505.5686,552.5314,564.2721,1,1983.94,88.06,3.75,1,1983.94,88.06
2,2222.SR,السوق السعودي,25.800,2026-10-18,0,True,2.06,52.58,25.6050,25.8939,...,25.1943,26.4057,26.7086,77,1986.60,46.64,1.00,0,0.00,0.00
3,META,السوق الأمريكي,709.330,2026-10-16,2,True,-3.72,50.26,735.7750,654.9556,...,665.1014,753.5586,775.6729,0,0.00,0.00,3.75,0,0.00,0.00
4,SPY,السوق الأمريكي,763.250,2026-10-16,2,True,-1.11,44.19,771.1840,767.4000,...,749.4771,777.0229,783.9093,0,0.00,0.00,3.75,0,0.00,0.00
5,QQQ,السوق الأمريكي,709.800,2026-10-16,2,True,-2.50,35.14,742.5190,726.3260,...,689.6414,729.9585,740.0378,0,0.00,0.00,3.75,0,0.00,0.00
6,AMZN,السوق الأمريكي,250.000,2026-10-16,2,True,-1.87,44.99,253.2260,257.0760,...,238.1957,261.8043,267.7064,2,1875.00,88.53,3.75,0,0.00,0.00
7,GOOGL,السوق الأمريكي,340.590,2026-10-16,2,True,-2.47,44.47,346.4140,344.4919,...,322.6686,358.5114,367.4721,1,1277.21,67.21,3.75,0,0.00,0.00
8,NVDA,السوق الأمريكي,214.130,2026-10-16,2,True,-1.43,37.56,228.1770,222.9632,...,202.6071,225.6529,231.4143,2,1605.98,86.42,3.75,0,0.00,0.00
9,TSLA,السوق الأمريكي,354.720,2026-10-16,2,True,-2.13,42.20,370.3335,359.4622,...,333.0057,376.4343,387.2914,1,1330.20,81.43,3.75,0,0.00,0.00
10,GPRO,السوق الأمريكي,1.050,2026-10-16,2,True,-8.70,37.45,1.2527,1.0825,...,0.9239,1.1761,1.2392,211,830.81,99.81,3.75,0,0.00,0.00
11,OPEN,السوق الأمريكي,2.115,2026-10-16,2,True,-8.84,35.98,2.3557,2.8690,...,1.7866,2.4434,2.6076,81,642.43,99.76,3.75,0,0.00,0.00
12,2010.SR,السوق السعودي,45.720,2026-10-18,0,True,2.60,41.08,46.4270,48.3021,...,43.9914,47.4486,48.3129,43,1965.96,74.33,1.00,0,0.00,0.00
13,SOAR,السوق الأمريكي,0.232,2026-10-16,2,True,-0.43,47.32,0.2591,0.2170,...,0.1310,0.3330,0.3835,264,229.68,99.99,3.75,0,0.00,0.00
14,HIMX,السوق الأمريكي,11.650,2026-10-16,2,True,-3.80,32.00,13.7690,13.9298,...,10.3557,12.9443,13.5914,20,873.75,97.07,3.75,0,0.00,0.00
15,SLXN,السوق الأمريكي,0.153,2026-10-16,2,True,-19.05,29.55,0.2625,0.3999,...,0.0733,0.2327,0.2726,334,191.63,99.84,3.75,0,0.00,0.00
16,WKHS,السوق الأمريكي,2.640,2026-10-16,2,True,-8.97,31.75,2.9330,3.0564,...,2.3824,2.8976,3.0264,103,1019.70,99.49,3.75,0,0.00,0.00
17,1120.SR,السوق السعودي,61.150,2026-10-18,0,True,0.25,35.53,63.0564,64.0563,...,59.5143,62.7857,63.6036,32,1956.80,52.34,1.00,0,0.00,0.00
18,ARAY,السوق الأمريكي,0.160,2026-10-16,2,True,-5.88,29.58,0.2380,0.2560,...,0.0957,0.2243,0.2564,414,248.40,99.80,3.75,0,0.00,0.00
19,ARBE,السوق الأمريكي,0.460,2026-10-16,2,True,-5.54,23.53,0.5895,0.6660,...,0.3863,0.5337,0.5706,361,622.73,99.79,3.75,0,0.00,0.00
20,BBAI,السوق الأمريكي,2.160,2026-10-16,2,True,-7.30,30.74,2.5725,2.8566,...,1.8367,2.4833,2.6449,82,664.20,99.41,3.75,0,0.00,0.00

🎯 فرص التداول:

,ticker,market,latest_close,latest_date,data_age_days,data_fresh,daily_change_pct,RSI14,SMA20,SMA50,...,stop_loss,target1,target2,quantity_before_portfolio_limit,position_value_sar,risk_sar,currency_rate,recommended_quantity,recommended_position_sar,recommended_risk_sar
0,AAPL,السوق الأمريكي,343.46,2026-10-16,2,True,0.43,62.08,337.4240,325.6940,...,330.0800,356.8400,363.5300,1,1287.97,50.18,3.75,1,1287.97,50.17
1,MSFT,السوق الأمريكي,529.05,2026-10-16,2,True,-1.93,57.36,520.2205,505.3655,...,505.5686,552.5314,564.2721,1,1983.94,88.06,3.75,1,1983.94,88.06

👀 قائمة المراقبة:

,ticker,market,latest_close,latest_date,data_age_days,data_fresh,daily_change_pct,RSI14,SMA20,SMA50,...,stop_loss,target1,target2,quantity_before_portfolio_limit,position_value_sar,risk_sar,currency_rate,recommended_quantity,recommended_position_sar,recommended_risk_sar
2,2222.SR,السوق السعودي,25.8,2026-10-18,0,True,2.06,52.58,25.605,25.8939,...,25.1943,26.4057,26.7086,77,1986.6,46.64,1.0,0,0.0,0.0

⚠️ قائمة تجنب التداول:

,ticker,market,latest_close,latest_date,data_age_days,data_fresh,daily_change_pct,RSI14,SMA20,SMA50,...,stop_loss,target1,target2,quantity_before_portfolio_limit,position_value_sar,risk_sar,currency_rate,recommended_quantity,recommended_position_sar,recommended_risk_sar
3,META,السوق الأمريكي,709.330,2026-10-16,2,True,-3.72,50.26,735.7750,654.9556,...,665.1014,753.5586,775.6729,0,0.00,0.00,3.75,0,0.0,0.0
4,SPY,السوق الأمريكي,763.250,2026-10-16,2,True,-1.11,44.19,771.1840,767.4000,...,749.4771,777.0229,783.9093,0,0.00,0.00,3.75,0,0.0,0.0
5,QQQ,السوق الأمريكي,709.800,2026-10-16,2,True,-2.50,35.14,742.5190,726.3260,...,689.6414,729.9585,740.0378,0,0.00,0.00,3.75,0,0.0,0.0
6,AMZN,السوق الأمريكي,250.000,2026-10-16,2,True,-1.87,44.99,253.2260,257.0760,...,238.1957,261.8043,267.7064,2,1875.00,88.53,3.75,0,0.0,0.0
7,GOOGL,السوق الأمريكي,340.590,2026-10-16,2,True,-2.47,44.47,346.4140,344.4919,...,322.6686,358.5114,367.4721,1,1277.21,67.21,3.75,0,0.0,0.0
8,NVDA,السوق الأمريكي,214.130,2026-10-16,2,True,-1.43,37.56,228.1770,222.9632,...,202.6071,225.6529,231.4143,2,1605.98,86.42,3.75,0,0.0,0.0
9,TSLA,السوق الأمريكي,354.720,2026-10-16,2,True,-2.13,42.20,370.3335,359.4622,...,333.0057,376.4343,387.2914,1,1330.20,81.43,3.75,0,0.0,0.0
10,GPRO,السوق الأمريكي,1.050,2026-10-16,2,True,-8.70,37.45,1.2527,1.0825,...,0.9239,1.1761,1.2392,211,830.81,99.81,3.75,0,0.0,0.0
11,OPEN,السوق الأمريكي,2.115,2026-10-16,2,True,-8.84,35.98,2.3557,2.8690,...,1.7866,2.4434,2.6076,81,642.43,99.76,3.75,0,0.0,0.0
12,2010.SR,السوق السعودي,45.720,2026-10-18,0,True,2.60,41.08,46.4270,48.3021,...,43.9914,47.4486,48.3129,43,1965.96,74.33,1.00,0,0.0,0.0
13,SOAR,السوق الأمريكي,0.232,2026-10-16,2,True,-0.43,47.32,0.2591,0.2170,...,0.1310,0.3330,0.3835,264,229.68,99.99,3.75,0,0.0,0.0
14,HIMX,السوق الأمريكي,11.650,2026-10-16,2,True,-3.80,32.00,13.7690,13.9298,...,10.3557,12.9443,13.5914,20,873.75,97.07,3.75,0,0.0,0.0
15,SLXN,السوق الأمريكي,0.153,2026-10-16,2,True,-19.05,29.55,0.2625,0.3999,...,0.0733,0.2327,0.2726,334,191.63,99.84,3.75,0,0.0,0.0
16,WKHS,السوق الأمريكي,2.640,2026-10-16,2,True,-8.97,31.75,2.9330,3.0564,...,2.3824,2.8976,3.0264,103,1019.70,99.49,3.75,0,0.0,0.0
17,1120.SR,السوق السعودي,61.150,2026-10-18,0,True,0.25,35.53,63.0564,64.0563,...,59.5143,62.7857,63.6036,32,1956.80,52.34,1.00,0,0.0,0.0
18,ARAY,السوق الأمريكي,0.160,2026-10-16,2,True,-5.88,29.58,0.2380,0.2560,...,0.0957,0.2243,0.2564,414,248.40,99.80,3.75,0,0.0,0.0
19,ARBE,السوق الأمريكي,0.460,2026-10-16,2,True,-5.54,23.53,0.5895,0.6660,...,0.3863,0.5337,0.5706,361,622.73,99.79,3.75,0,0.0,0.0
20,BBAI,السوق الأمريكي,2.160,2026-10-16,2,True,-7.30,30.74,2.5725,2.8566,...,1.8367,2.4833,2.6449,82,664.20,99.41,3.75,0,0.0,0.0

📋 ملخص المرحلة:

,execution_time,assets_analyzed,buy_candidates,watchlist_count,avoid_count,capital_sar,total_recommended_position_sar,total_theoretical_risk_sar,live_trading_executed
0,2026-10-18 19:39:42,21,2,1,18,10000,3271.91,138.23,False

In [8]:
# ============================================================
# 🌧️ الودق AI — المرحلة 88
# استعادة جميع الجداول من النسخة الاحتياطية
# والتحقق منها وحفظ نسخة جديدة
# ============================================================

import os
import glob
import pickle
import pandas as pd
from datetime import datetime

from google.colab import drive

print("=" * 65)
print("🌧️ الودق AI — المرحلة 88")
print("استعادة الجداول والتحقق منها")
print("=" * 65)

# ------------------------------------------------------------
# 1. الاتصال بـ Google Drive
# ------------------------------------------------------------

drive.mount('/content/drive', force_remount=False)

# ------------------------------------------------------------
# 2. البحث عن أحدث نسخة احتياطية
# ------------------------------------------------------------

backup_root = "/content/drive/MyDrive/نسخ احتياطية الودق AI"

backup_folders = glob.glob(
    os.path.join(backup_root, "*")
)

backup_folders = [
    folder for folder in backup_folders
    if os.path.isdir(folder)
]

if not backup_folders:
    raise FileNotFoundError(
        "لم يتم العثور على مجلد النسخ الاحتياطية."
    )

# نختار النسخة التي تحتوي على جداول المرحلة 87
required_file = "wadq_phase87_df.pkl"

valid_backups = [
    folder for folder in backup_folders
    if os.path.exists(os.path.join(folder, required_file))
]

if not valid_backups:
    raise FileNotFoundError(
        "لم نجد نسخة احتياطية تحتوي على جدول المرحلة 87."
    )

backup_folder = max(
    valid_backups,
    key=os.path.getmtime
)

print("\n📁 النسخة الاحتياطية المختارة:")
print(backup_folder)

# ------------------------------------------------------------
# 3. أسماء الجداول المطلوبة
# ------------------------------------------------------------

table_names = [
    "df",
    "df_source",
    "raw_data",
    "wadq_price_df",
    "wadq_technical_df",
    "wadq_evaluation_df",
    "wadq_risk_df",
    "wadq_final_ai_report",
    "wadq_decision_board_df",
    "wadq_quality_df",
    "wadq_global_master_report_df",
    "wadq_saudi_report_df",
    "wadq76_report",
    "wadq77_trade_plan",
    "wadq_85C_trades",
    "wadq_85C_daily",
    "wadq_85C_summary",
    "core_check_df",
    "trades",
    "final_report",
    "wadq_phase87_df",
    "wadq_phase87_opportunities_df",
    "wadq_phase87_watchlist_df",
    "wadq_phase87_avoid_df",
    "wadq_phase87_summary_df"
]

# ------------------------------------------------------------
# 4. استعادة الجداول
# ------------------------------------------------------------

restored_tables = {}
missing_tables = []

for name in table_names:

    pkl_path = os.path.join(
        backup_folder,
        name + ".pkl"
    )

    csv_path = os.path.join(
        backup_folder,
        name + ".csv"
    )

    try:

        if os.path.exists(pkl_path):

            with open(pkl_path, "rb") as f:
                obj = pickle.load(f)

        elif os.path.exists(csv_path):

            obj = pd.read_csv(csv_path)

        else:

            missing_tables.append(name)
            continue

        if isinstance(obj, pd.DataFrame):

            restored_tables[name] = obj

            # استعادة الجدول بالاسم الأصلي في الذاكرة
            globals()[name] = obj

            print(
                f"✅ {name}: "
                f"{obj.shape[0]} صف × "
                f"{obj.shape[1]} عمود"
            )

        else:

            print(
                f"⚠️ {name}: الملف موجود "
                "ولكن محتواه ليس DataFrame"
            )

    except Exception as e:

        print(f"❌ تعذر استعادة {name}: {e}")

# ------------------------------------------------------------
# 5. التحقق من الجداول الأساسية
# ------------------------------------------------------------

core_tables = [
    "wadq_phase87_df",
    "wadq_phase87_opportunities_df",
    "wadq_phase87_watchlist_df",
    "wadq_phase87_avoid_df",
    "wadq_phase87_summary_df",
    "wadq_price_df",
    "wadq_technical_df",
    "wadq_final_ai_report"
]

print("\n" + "=" * 65)
print("🔍 فحص الجداول الأساسية")
print("=" * 65)

for name in core_tables:

    if name in restored_tables:

        table = restored_tables[name]

        print(
            f"✅ {name} "
            f"| عدد الصفوف: {len(table)}"
        )

    else:

        print(f"❌ الجدول غير موجود: {name}")

# ------------------------------------------------------------
# 6. حفظ نسخة احتياطية جديدة
# ------------------------------------------------------------

timestamp = datetime.now().strftime(
    "%Y-%m-%d_%H-%M-%S"
)

new_backup_folder = os.path.join(
    backup_root,
    "المرحلة_88_" + timestamp
)

os.makedirs(
    new_backup_folder,
    exist_ok=True
)

for name, table in restored_tables.items():

    # حفظ بصيغة CSV
    table.to_csv(
        os.path.join(
            new_backup_folder,
            name + ".csv"
        ),
        index=False,
        encoding="utf-8-sig"
    )

    # حفظ بصيغة PKL للحفاظ على أنواع البيانات
    with open(
        os.path.join(
            new_backup_folder,
            name + ".pkl"
        ),
        "wb"
    ) as f:

        pickle.dump(
            table,
            f,
            protocol=pickle.HIGHEST_PROTOCOL
        )

# ------------------------------------------------------------
# 7. النتيجة النهائية
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("🌧️ اكتملت المرحلة 88")
print("=" * 65)

print(
    f"✅ عدد الجداول المستعادة: "
    f"{len(restored_tables)}"
)

print(
    f"⚠️ عدد الجداول غير الموجودة: "
    f"{len(missing_tables)}"
)

if missing_tables:

    print("\nالجداول غير الموجودة:")
    for name in missing_tables:
        print("-", name)

print("\n📁 النسخة الاحتياطية الجديدة:")
print(new_backup_folder)

print("\n💾 جميع الجداول المستعادة محفوظة.")
print("⛔ لم يتم تنفيذ أي عملية شراء أو بيع.")

=================================================================
🌧️ الودق AI — المرحلة 88
استعادة الجداول والتحقق منها
=================================================================
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

📁 النسخة الاحتياطية المختارة:
/content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14
✅ df: 52 صف × 16 عمود
✅ df_source: 26 صف × 9 عمود
✅ raw_data: 307 صف × 111 عمود
✅ wadq_price_df: 26 صف × 9 عمود
✅ wadq_technical_df: 26 صف × 10 عمود
✅ wadq_evaluation_df: 26 صف × 9 عمود
✅ wadq_risk_df: 26 صف × 9 عمود
✅ wadq_final_ai_report: 26 صف × 17 عمود
✅ wadq_decision_board_df: 26 صف × 9 عمود
✅ wadq_quality_df: 26 صف × 5 عمود
✅ wadq_global_master_report_df: 14 صف × 17 عمود
✅ wadq_saudi_report_df: 3 صف × 17 عمود
✅ wadq76_report: 41 صف × 20 عمود
✅ wadq77_trade_plan: 41 صف × 11 عمود
✅ wadq_85C_trades: 612 صف × 13 عمود
✅ wadq_85C_daily: 2067 صف × 8 عمود
✅ wadq_85C_summary: 1 صف × 9 عمود
✅ core_check_df: 9 صف × 5 عمود
✅ trades: 612 صف × 13 عمود
✅ final_report: 26 صف × 17 عمود
✅ wadq_phase87_df: 21 صف × 27 عمود
✅ wadq_phase87_opportunities_df: 2 صف × 27 عمود
✅ wadq_phase87_watchlist_df: 1 صف × 27 عمود
✅ wadq_phase87_avoid_df: 18 صف × 27 عمود
✅ wadq_phase87_summary_df: 1 صف × 9 عمود

=================================================================
🔍 فحص الجداول الأساسية
=================================================================
✅ wadq_phase87_df | عدد الصفوف: 21
✅ wadq_phase87_opportunities_df | عدد الصفوف: 2
✅ wadq_phase87_watchlist_df | عدد الصفوف: 1
✅ wadq_phase87_avoid_df | عدد الصفوف: 18
✅ wadq_phase87_summary_df | عدد الصفوف: 1
✅ wadq_price_df | عدد الصفوف: 26
✅ wadq_technical_df | عدد الصفوف: 26
✅ wadq_final_ai_report | عدد الصفوف: 26

=================================================================
🌧️ اكتملت المرحلة 88
=================================================================
✅ عدد الجداول المستعادة: 25
⚠️ عدد الجداول غير الموجودة: 0

📁 النسخة الاحتياطية الجديدة:
/content/drive/MyDrive/نسخ احتياطية الودق AI/المرحلة_88_2026-10-19_18-55-07

💾 جميع الجداول المستعادة محفوظة.
⛔ لم يتم تنفيذ أي عملية شراء أو بيع.

In [2]:
import pandas as pd

print("🌧️ فحص جداول الودق AI")
print("=" * 40)

tables = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        tables.append((name, obj))

if len(tables) == 0:
    print("لم يتم العثور على جداول في الذاكرة الحالية.")
else:
    print(f"عدد الجداول الموجودة: {len(tables)}")

    for name, df in tables:
        print(f"\n✅ {name}")
        print(f"الصفوف: {df.shape[0]} | الأعمدة: {df.shape[1]}")

print("\nانتهى الفحص.")

🌧️ فحص جداول الودق AI
========================================
لم يتم العثور على جداول في الذاكرة الحالية.

انتهى الفحص.

In [3]:
# 🌧️ الودق AI — البحث عن ملفات الجداول المحفوظة

import os

from google.colab import drive

# ربط Google Drive
drive.mount('/content/drive')

# البحث في مجلد المشروع
base_path = "/content/drive/MyDrive"

print("\n🔍 البحث عن ملفات الجداول المحفوظة...\n")

found_files = []

for root, dirs, files in os.walk(base_path):
    for file in files:
        if file.endswith((".csv", ".pkl", ".parquet", ".xlsx")):
            path = os.path.join(root, file)
            found_files.append(path)

if found_files:
    print(f"✅ تم العثور على {len(found_files)} ملف:\n")

    for path in found_files:
        print("📄", path)
else:
    print("⚠️ لم يتم العثور على ملفات جداول محفوظة في Google Drive.")

Mounted at /content/drive

🔍 البحث عن ملفات الجداول المحفوظة...

✅ تم العثور على 70 ملف:

📄 /content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_الجداول_المستعادة.xlsx
📄 /content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_68.xlsx
📄 /content/drive/MyDrive/الودق AI - سجل المشروع/الودق_AI_المرحلة_69.xlsx
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_ai_final_report.xlsx
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_price_df.csv
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_technical_df.csv
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_evaluation_df.csv
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_risk_df.csv
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_final_ai_report.csv
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_decision_board_df.csv
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_quality_df.csv
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_global_master_report_df.csv
📄 /content/drive/MyDrive/الودق AI - نتائج إعادة البناء/تقرير_20261017_140449/wadq_saudi_report_df.csv
📄 /content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.xlsx
📄 /content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq76_report_20261017_142233.csv
📄 /content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.xlsx
📄 /content/drive/MyDrive/الودق AI - نتائج المرحلة 76/wadq77_trade_plan_20261017_143605.csv
📄 /content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_trades_20261017_213918.csv
📄 /content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_daily_20261017_213918.csv
📄 /content/drive/MyDrive/الودق AI - نتائج المرحلة 85C/wadq_85C_summary_20261017_213918.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_price_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_price_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_technical_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_technical_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_evaluation_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_evaluation_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_risk_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_risk_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_final_ai_report.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_final_ai_report.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_decision_board_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_decision_board_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_quality_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_quality_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_global_master_report_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_global_master_report_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_saudi_report_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_saudi_report_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq76_report.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq76_report.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq77_trade_plan.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq77_trade_plan.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_trades.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_trades.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_daily.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_daily.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_summary.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_85C_summary.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/core_check_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/core_check_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/trades.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/trades.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/final_report.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/final_report.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/df_source.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/df_source.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/raw_data.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/raw_data.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_opportunities_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_opportunities_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_watchlist_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_watchlist_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_avoid_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_avoid_df.pkl
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_summary_df.csv
📄 /content/drive/MyDrive/نسخ احتياطية الودق AI/2026-10-18_22-06-14/wadq_phase87_summary_df.pkl